### ISSUE TITLE
`cargo test` with Rust from nixpkgs-mozilla can't run doctests on darwin

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#56228]
## Issue description

Using `cargo test` from nixpkgs-mozilla's nightly compiler results in:

```
  = note: dyld: Symbol not found: __ZTIN4llvm2cl18GenericOptionValueE
            Referenced from: /nix/store/dbhg05567nbca8wf0skbdrbgcr7x29x5-llvm-5.0.2-lib/lib/libLTO.dylib
            Expected in: /nix/store/8kgj67vyzwa417av8layghqj6fqvwypy-rust-1.32.0-2019-01-16-9fda7c223/lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib
           in /nix/store/dbhg05567nbca8wf0skbdrbgcr7x29x5-llvm-5.0.2-lib/lib/libLTO.dylib
```

Full output:

```
---- src/nix.rs - nix::CallOpts::attribute (line 74) stdout ----
error: linking with `cc` failed: exit code: 254
  |
  = note: "cc" "-m64" "-L" "/nix/store/8kgj67vyzwa417av8layghqj6fqvwypy-rust-1.32.0-2019-01-16-9fda7c223/lib/rustlib/x86_64-apple-darwin/lib" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.0.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.1.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.10.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.11.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.12.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.13.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.14.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.2.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.3.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.4.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.5.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.6.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.7.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.8.rcgu.o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.rust_out.7rcbfp3g-cgu.9.rcgu.o" "-o" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out" "/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/rustdoctestM73O0O/rust_out.33dyzt1ekirinwy8.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/distiller/project/target/debug/deps" "-L" "/Users/distiller/project/target/debug/deps" "-L" "/nix/store/8kgj67vyzwa417av8layghqj6fqvwypy-rust-1.32.0-2019-01-16-9fda7c223/lib/rustlib/x86_64-apple-darwin/lib" "/Users/distiller/project/target/debug/deps/libx-7135a826dc2d241b.rlib" "/Users/distiller/project/target/debug/deps/libmd5-0e9c73391ad352fe.rlib" "/Users/distiller/project/target/debug/deps/libtempfile-a6b539e10dc5d65f.rlib" "/Users/distiller/project/target/debug/deps/libremove_dir_all-ac17c59261deb099.rlib" "/Users/distiller/project/target/debug/deps/librand-3395b469e4796e03.rlib" "/Users/distiller/project/target/debug/deps/librand_xorshift-77c15e36f8b62cf8.rlib" "/Users/distiller/project/target/debug/deps/librand_pcg-1e5f2cf70c9b40c6.rlib" "/Users/distiller/project/target/debug/deps/librand_hc-e13f3f5761300725.rlib" "/Users/distiller/project/target/debug/deps/librand_chacha-45ce4bd7117518d9.rlib" "/Users/distiller/project/target/debug/deps/librand_isaac-d550d7c2d8478d31.rlib" "/Users/distiller/project/target/debug/deps/librand_core-a03d82c11fe14d01.rlib" "/Users/distiller/project/target/debug/deps/librand_os-2eec1e32c71e1107.rlib" "/Users/distiller/project/target/debug/deps/librand_jitter-4aee14e90c2df05c.rlib" "/Users/distiller/project/target/debug/deps/librand_core-fd14db0168e8be29.rlib" "/Users/distiller/project/target/debug/deps/libnotify-1b9ac574eb60d85c.rlib" "/Users/distiller/project/target/debug/deps/libwalkdir-2d449cb32a353c8e.rlib" "/Users/distiller/project/target/debug/deps/libsame_file-207e1b983596d3d6.rlib" "/Users/distiller/project/target/debug/deps/libfsevent-fece5afeb3731481.rlib" "/Users/distiller/project/target/debug/deps/libbitflags-9ac60c81b453094a.rlib" "/Users/distiller/project/target/debug/deps/libfsevent_sys-0696025107065a46.rlib" "/Users/distiller/project/target/debug/deps/libfiletime-0c20681abc7ed6ac.rlib" "/Users/distiller/project/target/debug/deps/libfutures-e4f230ef9bb51fea.rlib" "/Users/distiller/project/target/debug/deps/libdirectories-62eb1e19f64b0b88.rlib" "/Users/distiller/project/target/debug/deps/libserde_json-ffae744dbd6cc2b2.rlib" "/Users/distiller/project/target/debug/deps/libryu-baca06a237bffa6f.rlib" "/Users/distiller/project/target/debug/deps/libitoa-17b8c39a7a49ea6f.rlib" "/Users/distiller/project/target/debug/deps/libserde-2d97f2713a5c3e91.rlib" "/Users/distiller/project/target/debug/deps/libenv_logger-0561930959b9b0bf.rlib" "/Users/distiller/project/target/debug/deps/libregex-b4a0b6220344365b.rlib" "/Users/distiller/project/target/debug/deps/libutf8_ranges-88eacd4848a2473a.rlib" "/Users/distiller/project/target/debug/deps/libregex_syntax-844ae7bbdd52290a.rlib" "/Users/distiller/project/target/debug/deps/libucd_util-81dc0358472971b0.rlib" "/Users/distiller/project/target/debug/deps/libthread_local-afdc181f85644685.rlib" "/Users/distiller/project/target/debug/deps/liblazy_static-bd7de5c8fabcfd46.rlib" "/Users/distiller/project/target/debug/deps/libaho_corasick-bf6fcd41547ee68b.rlib" "/Users/distiller/project/target/debug/deps/libmemchr-2fc13292a6983aba.rlib" "/Users/distiller/project/target/debug/deps/libhumantime-a637286b73bb5bb1.rlib" "/Users/distiller/project/target/debug/deps/libquick_error-74f3ee3500fb9539.rlib" "/Users/distiller/project/target/debug/deps/libtermcolor-1ab471232e309b94.rlib" "/Users/distiller/project/target/debug/deps/liblog-fc3ccfb0c92a64ac.rlib" "/Users/distiller/project/target/debug/deps/libcfg_if-461d14ec077780d2.rlib" "/Users/distiller/project/target/debug/deps/libstructopt-60ce7fe6765c9922.rlib" "/Users/distiller/project/target/debug/deps/libclap-15c44185bb8d6ad5.rlib" "/Users/distiller/project/target/debug/deps/libvec_map-12b37cc6073f7a1a.rlib" "/Users/distiller/project/target/debug/deps/libtextwrap-840ff548898c703e.rlib" "/Users/distiller/project/target/debug/deps/libunicode_width-0c94f0e96f9b3288.rlib" "/Users/distiller/project/target/debug/deps/libstrsim-94158d471d7b5d17.rlib" "/Users/distiller/project/target/debug/deps/libbitflags-861218943972ef93.rlib" "/Users/distiller/project/target/debug/deps/libatty-299f9bf1d6b2ae0e.rlib" "/Users/distiller/project/target/debug/deps/liblibc-83d68bd06eb59687.rlib" "/Users/distiller/project/target/debug/deps/libansi_term-f89397fb61253897.rlib" "/nix/store/qzmjqlmlg6l1jcycn8qmkq4ihzihq8zv-rust/lib/rustlib/x86_64-apple-darwin/lib/libstd-edeacefc1391b975.rlib" "/nix/store/qzmjqlmlg6l1jcycn8qmkq4ihzihq8zv-rust/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-661c88e34f871df0.rlib" "/nix/store/qzmjqlmlg6l1jcycn8qmkq4ihzihq8zv-rust/lib/rustlib/x86_64-apple-darwin/lib/libunwind-f7c06680fdd716f3.rlib" "/nix/store/qzmjqlmlg6l1jcycn8qmkq4ihzihq8zv-rust/lib/rustlib/x86_64-apple-darwin/lib/liblibc-f2e753da53df829c.rlib" "/nix/store/qzmjqlmlg6l1jcycn8qmkq4ihzihq8zv-rust/lib/rustlib/x86_64-apple-darwin/lib/liballoc-961b28aeeb5bc8e1.rlib" "/nix/store/qzmjqlmlg6l1jcycn8qmkq4ihzihq8zv-rust/lib/rustlib/x86_64-apple-darwin/lib/libcore-b6f6b59b6a29ec3a.rlib" "/nix/store/qzmjqlmlg6l1jcycn8qmkq4ihzihq8zv-rust/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f31526d6d86acb04.rlib" "-framework" "Security" "-framework" "CoreServices" "-framework" "CoreServices" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: dyld: Symbol not found: __ZTIN4llvm2cl18GenericOptionValueE
            Referenced from: /nix/store/dbhg05567nbca8wf0skbdrbgcr7x29x5-llvm-5.0.2-lib/lib/libLTO.dylib
            Expected in: /nix/store/8kgj67vyzwa417av8layghqj6fqvwypy-rust-1.32.0-2019-01-16-9fda7c223/lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib
           in /nix/store/dbhg05567nbca8wf0skbdrbgcr7x29x5-llvm-5.0.2-lib/lib/libLTO.dylib
          clang-5.0: error: unable to execute command: Abort trap: 6
          clang-5.0: error: linker command failed due to signal (use -v to see invocation)
```

### Steps to reproduce

where nixpkgs is at `ad3e9191d16722ea3eec32f4cd689eea730f39f6`:

```nix
pkgs.mkShell {
  name = "foo";
  buildInputs = [
    pkgs.latest.rustChannels.stable.rust
    pkgs.bashInteractive
    pkgs.git
  ] ++
  pkgs.stdenv.lib.optionals pkgs.stdenv.isDarwin [
    pkgs.darwin.cf-private
    pkgs.darwin.Security
    pkgs.darwin.apple_sdk.frameworks.CoreServices
  ];
}
```

run `cargo test` in a project with doctests on Darwin.

**Comment by grahamc** [comment]
Fixed after bumping to 2a81eceeba6d9b0499c0a9dc569921765321cdd0, sorry for the noise  :)
