### ISSUE TITLE
pkgs.phpPackages.apc installation failed

### ISSUE THREAD

**Issue by katyo** [NixOS/nixpkgs#7518]
Can't download apc-3.1.13.tgz

Trying to download http://pecl.php.net/get/apc-3.1.13.tgz, but actually url is a http://pecl.php.net/get/APC-3.1.13.tgz (APC in upper case).

**Comment by jagajaga** [comment]
I've fixed link but recieved
```
/tmp/nix-build-php-APC-3.1.13.drv-0/APC-3.1.13/apc_cache.c: In function '_apc_cache_user_update':
/tmp/nix-build-php-APC-3.1.13.drv-0/APC-3.1.13/apc_cache.c:818:63: error: 'IS_CONSTANT_INDEX' undeclared (first use in this function)
             switch(Z_TYPE_P((*slot)->value->data.user.val) & ~IS_CONSTANT_INDEX) {
                                                               ^
/tmp/nix-build-php-APC-3.1.13.drv-0/APC-3.1.13/apc_cache.c:818:63: note: each undeclared identifier is reported only once for each function it appears in
/tmp/nix-build-php-APC-3.1.13.drv-0/APC-3.1.13/apc_cache.c:820:22: error: 'IS_CONSTANT_ARRAY' undeclared (first use in this function)
                 case IS_CONSTANT_ARRAY:
                      ^
Makefile:186: recipe for target 'apc_cache.lo' failed
make: *** [apc_cache.lo] Error 1
```
Can you create a patch?

**Comment by pSub** [comment]
It seems APC does not compile with php versions >5.5:
http://serverfault.com/questions/593888/pecl-apc-install-error-make-failed

**Comment by pSub** [comment]
Some more information on this: http://www.devside.net/wamp-server/installing-apc-for-php-5-5

**Comment by katyo** [comment]
I create pull request #7614

**Comment by katyo** [comment]
I fixed this issue for release-14.12 at pl #7615

**Comment by pSub** [comment]
I am closing this issue because of 2514f80bdf326d349ce85991ec5a36645e7feaf3.
