### PR TITLE
zeroad: pin boost183 and allow implicit-function-declaration to fix build

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Does it have to be 1.83? I just dealt with all the other uses of that. It looks like it was building until recently, so `boost186` should work?

**Comment by SuperSandro2000** [comment]
It doesn't build with 1.86 because a deprecated leaf() method got removed and all-packages.nix  revealed that as the next lower version.

**Comment by SuperSandro2000** [comment]
Thats the error:

```
0ad> OverlayRenderer.cpp
0ad> ParticleRenderer.cpp
0ad> PatchRData.cpp
0ad> PostprocManager.cpp
0ad> RenderModifiers.cpp
0ad> Renderer.cpp
0ad> ../../../source/graphics/TextureManager.cpp: In member function 'CTextureConverter::Settings CTextureManagerImpl::GetConverterSettings(const CTexturePtr&)':
0ad> ../../../source/graphics/TextureManager.cpp:788:87: error: 'boost::filesystem::wpath' {aka 'class boost::filesystem::path'} has no member named 'leaf'
0ad>   788 |                 return m_TextureConverter.ComputeSettings(GetWstringFromWpath(srcPath.leaf()), files);
0ad>       |                                                                                       ^~~~
0ad> RenderingOptions.cpp
0ad> Scene.cpp
0ad> SceneRenderer.cpp
0ad> ShadowMap.cpp
0ad> SilhouetteRenderer.cpp
0ad> SkyManager.cpp
0ad> TerrainOverlay.cpp
0ad> TerrainRenderer.cpp
0ad> TexturedLineRData.cpp
```

**Comment by SuperSandro2000** [comment]
Assuming that question got answered and since multiple people have asked me to fix zeroad I am going ahead and merging this.
