### PR TITLE
boost: support for libcxx and specific clang version

### PR DESCRIPTION
**Pull request by bzizou**
###### Motivation for this change

Currently in the process of creating packages for iRods, I need a boost version compiled with a specific version of clang and libcxx. I added support for libcxx and possible override of the clang version.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

File: pkgs/development/libraries/boost/generic.nix [hunk 1]
```diff
@@ -40,12 +41,19 @@ let
   # To avoid library name collisions
   layout = if taggedLayout then "tagged" else "system";
 
+  libcxxflags = if enableLibcxx then
+                  "-nostdinc++ -I${llvmPackages.libcxx}/include/c++/v1"
+                else
+                  "";
+
   cflags = if enablePIC && enableExceptions then
```
Comment (bzizou) [inline pkgs/development/libraries/boost/generic.nix]: OK, thank you. Currently testing the mod with nox-review...

Comment (bzizou) [inline pkgs/development/libraries/boost/generic.nix]: Actually, testing something else: using stdenv=libcxxStdenv might be a better alternative...

**Comment by copumpkin** [comment]
Can't this be done with a `clangStdenv` without adding any special logic to boost? Keep in mind that the darwin builds already use LLVM and libc++ (and boost builds fine), so I'm a little confused as to why you need to be creating a special boost expression with an exact version of libcxx and clang.

My sense is that if you used `clangStdenv`, you'd automatically get the `-nostdinc` and `libcxx` in scope, as well as `toolset = "clang"` and so on.

**Comment by bzizou** [comment]
@copumpkin : 

> My sense is that if you used clangStdenv, you'd automatically get the -nostdinc and libcxx in scope, as well as toolset = "clang" and so on.

Yes, you're right. Not with clangStdenv, but It correctly builds against libcxx with libcxxStdenv actually.
My problem is that I need to build boost with clang_38 (not clang_37 which is the default) and I'm probably doing something wrong as it fails...

**Comment by copumpkin** [comment]
cc @shlevy who I think made `libcxxStdenv`. The obvious thing would be to make a `libcxx38Stdenv` and so on, but ideally we'd factor that stuff out a bit more. For example, `clangStdenv` is just `llvmPackages.stdenv`, but `libcxxStdenv` doesn't appear to have a similar analog.

Also, it'd help us help you if you said how it fails 😄

**Comment by bzizou** [comment]
It fails miserably with tons of errors that don't seem to stop the compile process... I attach an output and give an example here:
```
[boost160libcxx.out.txt](https://github.com/NixOS/nixpkgs/files/550608/boost160libcxx.out.txt)
/nix/store/m3azisclqx55zb40lsa4kmsfnw1g7mm9-libc++-3.8.1/include/c++/v1/cmath:317:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^ 
```
For testing, I changed `llvmPackages = recurseIntoAttrs llvmPackages_37;` into ` llvmPackages = recurseIntoAttrs llvmPackages_38;` into `all-packages.nix`
And created a boost160libcxx package definition:
```
  boost160libcxx = callPackage ../development/libraries/boost/1.60.nix {
       stdenv = libcxxStdenv;
  };
```
Thank you very much for your help... I spent hours on this problem and the only fix that worked was this patch to correctly compile boost with clang and libcxx 3.8 without changing the default.

**Comment by shlevy** [comment]
@copumpkin we could add a libcxxStdenv attribute to each llvm package set.

**Comment by bzizou** [comment]
It should be really great to have a working libcxx38Stdenv! If I can help doing this... at least I will be able to test it

**Comment by copumpkin** [comment]
@bzizou not really sure what to suggest other than perhaps comparing what the darwin stdenv is doing differently from the Linux clang one. The darwin one isn't doing anything particularly fancy to build its compiler and boost1.6 works fine with LLVM 3.8 on there. See for example this build on Hydra: http://hydra.nixos.org/build/42510536/nixlog/2/raw

**Comment by shlevy** [comment]
Testing adding a libcxxStdenv to llvmPackages now, I think that's all @bzizou was asking for?

**Comment by copumpkin** [comment]
I thought it still didn't build with a 3.8 version of `libcxxStdenv`. If it does, that's great!

**Comment by shlevy** [comment]
That's how I interpreted " the only fix that worked was this patch to correctly compile boost with clang and libcxx 3.8 without changing the default."

**Comment by bzizou** [comment]
Closing. I finally managed to do the iRods packaging: #19898
Thank you very much for your help!
