### PR TITLE
qelectrotech: fix build and resource paths

### LINKED ISSUE #532690: Build failure: qelectrotech
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

Attempt to build locally or in Hydra (error same in both)

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

https://hydra.nixos.org/build/328807323

### Relevant log output

```console
[ 80%] Building CXX object CMakeFiles/qelectrotech.dir/sources/TerminalStrip/ui/terminalstripeditor.cpp.o
In file included from /build/source/sources/TerminalStrip/ui/terminalstripeditor.cpp:19:
/build/source/build/qelectrotech_autogen/include/ui_terminalstripeditor.h:29:10: fatal error: kcolorcombo.h: No such file or directory
   29 | #include "kcolorcombo.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/qelectrotech.dir/build.make:24727: CMakeFiles/qelectrotech.dir/sources/TerminalStrip/ui/terminalstripeditor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/qelectrotech.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Additional context

Broken by https://github.com/NixOS/nixpkgs/pull/513691

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.92, NixOS, 25.11 (Xantusia), 25.11.20260608.e820eb4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.93.4
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/merikei/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/merikei/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/merikei/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/merikei/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/merikei/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/yjcffnriqddwdmd4488fzxxw77b0i93m-gnome-settings-daemon-49.1/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/jg51azacksxdmvwwyjv66kjkmxj918fl-lix-2.93.4/share`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/149h1h9bpd4vnl0rnm4s3dm7mh5pgv6q-source`

### Notify maintainers

@yvesf

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #534359: qelectrotech: language setting has no effect
### Nixpkgs version

- Stable (26.05)

### Describe the bug

Changing the language has no effect, for me it's all french.

The issue came up in https://github.com/NixOS/nixpkgs/pull/533961

### Steps to reproduce

```
$ /nix/store/dln78cvs4ggz503hg9adxf6gjj10gb4f-qelectrotech-0.100/bin/qelectrotech 2>&1  | grep lang
failed to load qet_en "/usr/local/share/qelectrotech/lang/" ( /build/source/sources/qetapp.cpp 239 setLanguage )
19:54:29.905 Info:  OS System language: "en_US" 
19:54:29.905 Info:  System language defined in QET configuration: "de" 
19:54:29.905 Info:  language Path: "/usr/local/share/qelectrotech/lang/" 
```

### Expected behaviour

The language setting should be honored after restarting the application.

### Screenshots

_No response_

### Relevant log output

```console

```

### Additional context

_No response_

### System metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.18.33, NixOS, 26.05 (Yarara), 26.05.20260531.b51242d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.7`
 - nixpkgs: `/nix/store/i936ws2xplkqgbzkxkacqqq2dpag3ndf-source`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by geri1701**
Fixes the `qelectrotech` build without reintroducing KF5 by adding Qt-only replacements for the remaining `KColorButton` and `KColorCombo` uses.

Also adjusts the manual `installPhase` to install files from the source tree when CMake builds out-of-source, and passes qelectrotech's resource path options through the Qt wrapper so translations, elements, and titleblocks load from `$out/share/qelectrotech/...` instead of upstream's `/usr/local/share/qelectrotech/...` default.

Closes #532690
Closes #534359

Assisted-by: pi coding agent / Mika (OpenAI GPT-5.5)

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [x] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [x] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

**Comment by yvesf** [comment]
@geri1701 please have a look at https://github.com/NixOS/nixpkgs/pull/513691
My first impression (after having very quick look only) is that this PR reverts these changes.
My understanding there was that we are waiting for KF6 update in qelectrotech because we don't want KF5 in NixOS. Alternatively, qelectrotech also has a non-Kde Framework build option, which was unfortunely broken when i checked.

**Comment by geri1701** [comment]
Thanks, good catch. You are right: the previous version effectively reintroduced KF5.

   I reworked the fix to keep `BUILD_WITH_KF5=OFF` and added small Qt-only replacements for
 the remaining `KColorButton`/`KColorCombo` uses instead. Locally, `qelectrotech` builds and
 the closure no longer contains KF5/KCoreAddons/KWidgetsAddons.

**Review by yvesf — APPROVED** [review]
The change fixes the compilation for me.
I18n is broken, but I suspect this is not related this change:
```
$ /nix/store/dln78cvs4ggz503hg9adxf6gjj10gb4f-qelectrotech-0.100/bin/qelectrotech 2>&1  | grep lang
failed to load qet_en "/usr/local/share/qelectrotech/lang/" ( /build/source/sources/qetapp.cpp 239 setLanguage )
19:54:29.905 Info:  OS System language: "en_US" 
19:54:29.905 Info:  System language defined in QET configuration: "de" 
19:54:29.905 Info:  language Path: "/usr/local/share/qelectrotech/lang/" 
```

**Comment by geri1701** [comment]
> The change fixes the compilation for me. I18n is broken, but I suspect this is not related this change:

   Thanks for testing.

   I can reproduce the i18n/resource path issue too. It looks unrelated to this build fix:
 qelectrotech is compiled with upstream's default `/usr/local/share/qelectrotech/...` paths
 while nixpkgs installs the resources under `$out/share/qelectrotech/...`.

   I'd keep this PR scoped to the build fix.

**Comment by geri1701** [comment]
Small update: I folded the resource-path fix into this PR as well.

I initially suggested keeping this scoped to the build fix, but since `qelectrotech` currently does not build on `master`, a separate fix for #534359 would have to be stacked on this branch anyway.

File: pkgs/by-name/qe/qelectrotech/package.nix [hunk 1]
```diff
@@ -60,21 +62,30 @@ stdenv.mkDerivation rec {
...
   ];
 
+  qtWrapperArgs = [
+    "--add-flags"
+    "--common-elements-dir=${placeholder "out"}/share/qelectrotech/elements"
+    "--add-flags"
+    "--common-tbt-dir=${placeholder "out"}/share/qelectrotech/titleblocks"
+    "--add-flags"
+    "--lang-dir=${placeholder "out"}/share/qelectrotech/lang"
+  ];
```
Comment (yvesf) [inline pkgs/by-name/qe/qelectrotech/package.nix:73]: alternative fix:
```diff
--- a/pkgs/by-name/qe/qelectrotech/package.nix
+++ b/pkgs/by-name/qe/qelectrotech/package.nix
@@ -38,6 +38,8 @@ stdenv.mkDerivation rec {
   postPatch = ''
     substituteInPlace cmake/fetch_kdeaddons.cmake \
       --replace-fail "DEFINED BUILD_WITH_KF5" "BUILD_WITH_KF5"
+    substituteInPlace cmake/paths_compilation_installation.cmake \
+      --replace-fail 'set(INSTALL_PREFIX              "/usr/local/")' 'set(INSTALL_PREFIX              "${placeholder "out"}/")'
   '';
 
   cmakeFlags = [
```

this results in:
```
Paths used for compilation and installation of QET
--------------------------------------------------
COMPIL_PREFIX              /usr/local/
INSTALL_PREFIX             /nix/store/9qm9yp8k32p9nagakf4780100slfs370-qelectrotech-0.100/
QET_BINARY_PATH            bin/
QET_COMMON_COLLECTION_PATH /nix/store/9qm9yp8k32p9nagakf4780100slfs370-qelectrotech-0.100/share/qelectrotech/elements/
QET_COMMON_TBT_PATH        /nix/store/9qm9yp8k32p9nagakf4780100slfs370-qelectrotech-0.100/share/qelectrotech/titleblocks/
QET_LANG_PATH              /nix/store/9qm9yp8k32p9nagakf4780100slfs370-qelectrotech-0.100/share/qelectrotech/lang/
QET_EXAMPLES_PATH          /nix/store/9qm9yp8k32p9nagakf4780100slfs370-qelectrotech-0.100/share/qelectrotech/examples/
QET_LICENSE_PATH           doc/qelectrotech/
QET_MIME_PACKAGE_PATH      ../share/mime/packages/
QET_DESKTOP_PATH           share/applications/
QET_ICONS_PATH             share/icons/hicolor/
QET_MAN_PATH               man/
QET_APPDATA_PATH           share/appdata
```

whereas the qtwrapper results in adding this to the wrapping starter script:
```
   17      --add-flags '--common-elements-dir=/nix/store/7rjiwz9hnjfzpcfar8c6ycqvnsfj5h4w-qelectrotech-0.100/share/qelectrotech/elements' \                                                                      
   18      --add-flags '--common-tbt-dir=/nix/store/7rjiwz9hnjfzpcfar8c6ycqvnsfj5h4w-qelectrotech-0.100/share/qelectrotech/titleblocks' \                                                                        
   19      --add-flags '--lang-dir=/nix/store/7rjiwz9hnjfzpcfar8c6ycqvnsfj5h4w-qelectrotech-0.100/share/qelectrotech/lang' \           
```
while INSTALL_PREFIX stays with /usr/local.

I honestly don't know what's the better approach. Both works for me. I'm totally fine with qtwrapper version.

**Comment by yvesf** [comment]
Thank you, looks good to me (I already approved).

@NixOS/nixpkgs-merge-bot merge

(following https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#how-to-merge-pull-requests-yourself)

**Comment by Merikei** [comment]
Works, including language switching.
Thank you so much @geri1701 !

**Comment by K900** [comment]
Can this be upstreamed?

**Comment by geri1701** [comment]
> Can this be upstreamed?

Yes, the Qt-only replacement patch should be upstreamable. It fixes the `BUILD_WITH_KF5=OFF` build path by replacing the remaining KF5 color widgets.

The resource-path/wrapper and installPhase bits are nixpkgs-specific packaging adjustments, but the widget fallback itself should make sense upstream. I can try to submit that upstream separately; I would still prefer to keep this PR
unblocked because qelectrotech currently does not build on master and this fixes the nixpkgs package in the meantime.

**Comment by doronbehar** [comment]
> Yes, the Qt-only replacement patch should be upstreamable.

Then please do it :) Let's wait also a day or two for their response.

**Comment by geri1701** [comment]
> Then please do it :) Let's wait also a day or two for their response.

Thanks. I agree that the Qt-only widget patch is a good candidate for upstreaming, and I can try to do that separately when I have time. However, I do not want to make this PR depend on that follow-up work.

I do not personally use qelectrotech; my motivation here is to restore a working package for nixpkgs users. The package currently does not build on `master`, and another user has already confirmed that this PR fixes the package, including language switching.

Since the resource path, wrapper and installPhase changes are nixpkgs-specific packaging fixes anyway, I do not think this nixpkgs fix should be blocked on waiting for an upstream response.

If upstreaming first is considered a hard requirement for merging this, that is fine too. In that case I would rather leave this for someone who needs qelectrotech or has the time to drive the upstream side as well. I might have time to look into it next week at the earliest.

**Comment by doronbehar** [comment]
> > Then please do it :) Let's wait also a day or two for their response.
> 
> Thanks. I agree that the Qt-only widget patch is a good candidate for upstreaming, and I can try to do that separately when I have time. However, I do not want to make this PR depend on that follow-up work.
> 
> I do not personally use qelectrotech; my motivation here is to restore a working package for nixpkgs users. The package currently does not build on `master`, and another user has already confirmed that this PR fixes the package, including language switching.

That's nice of you to put this effort for them, so maybe the package maintainer would like to send that patch upstream (it shouldn't be that hard...).

Also it'd be nice to fix the distinct issues in separate commits here in Nixpkgs if possible.

**Comment by geri1701** [comment]
> > > Then please do it :) Let's wait also a day or two for their response.
> > 
> > 
> > Thanks. I agree that the Qt-only widget patch is a good candidate for upstreaming, and I can try to do that separately when I have time. However, I do not want to make this PR depend on that follow-up work.
> > I do not personally use qelectrotech; my motivation here is to restore a working package for nixpkgs users. The package currently does not build on `master`, and another user has already confirmed that this PR fixes the package, including language switching.
> 
> That's nice of you to put this effort for them, so maybe the package maintainer would like to send that patch upstream (it shouldn't be that hard...).
> 
> Also it'd be nice to fix the distinct issues in separate commits here in Nixpkgs if possible.

Done. I split the PR into two commits:
- `qelectrotech: fix Qt-only build`
- `qelectrotech: fix resource paths`

The upstream side is done as well: QElectroTech accepted and merged the no-KF5 fix in qelectrotech/qelectrotech-source-mirror#533.

Until the next QElectroTech release, this keeps the nixpkgs package buildable on master without reintroducing KF5, with the nixpkgs-specific resource path fix kept separate.

Re-tested locally with `nix build`, targeted `nixpkgs-review -p qelectrotech`, and basic `qelectrotech --version` / `--help` smoke tests.

File: pkgs/by-name/qe/qelectrotech/package.nix [hunk 2]
```diff
@@ -30,6 +30,8 @@ stdenv.mkDerivation rec {
   patches = [
     # stripped down version of https://codeberg.org/gentoo/gentoo/src/branch/master/sci-electronics/qelectrotech/files/qelectrotech-0.90_pre20250820-cmake.patch
     ./system-pugixml.patch
+    # Qt-only replacements for upstream's KF5 color widgets.
+    ./qt-color-widgets.patch
```
Comment (doronbehar) [inline pkgs/by-name/qe/qelectrotech/package.nix:35]: So in such cases, if there's an upstream PR that fixes this, it is common & good practice to use `fetchpatch` for it, with a link to the upstream PR or commit - this way it is easy to fully verify whether upstream has included it in the next release etc. It also saves space in Nixpkgs' source (which is already pretty big!).

File: pkgs/by-name/qe/qelectrotech/package.nix [hunk 3]
```diff
@@ -65,16 +67,16 @@ stdenv.mkDerivation rec {
...
-    cp -r lang $out/share/qelectrotech
-    cp -r examples $out/share/qelectrotech
+    cp -r ../elements $out/share/qelectrotech
+    cp -r ../titleblocks $out/share/qelectrotech
+    cp -r ../lang $out/share/qelectrotech
+    cp -r ../examples $out/share/qelectrotech
 
     mkdir -p $out/share/icons/hicolor
-    cp -r ico $out/share/icons/hicolor
+    cp -r ../ico $out/share/icons/hicolor
```
Comment (doronbehar) [inline pkgs/by-name/qe/qelectrotech/package.nix:89]: Don't these changes belong to the 2nd commit?

File: pkgs/by-name/qe/qelectrotech/package.nix [hunk 4]
```diff
@@ -62,6 +62,15 @@ stdenv.mkDerivation rec {
...
   ];
 
+  qtWrapperArgs = [
+    "--add-flags"
+    "--common-elements-dir=${placeholder "out"}/share/qelectrotech/elements"
+    "--add-flags"
+    "--common-tbt-dir=${placeholder "out"}/share/qelectrotech/titleblocks"
+    "--add-flags"
+    "--lang-dir=${placeholder "out"}/share/qelectrotech/lang"
+  ];
```
Comment (doronbehar) [inline pkgs/by-name/qe/qelectrotech/package.nix:73]: Definitly I'd put the previous comment's changes in the 2nd commit.

**Review by doronbehar — COMMENTED** [review]
1 last round of review I'm pretty sure!

File: pkgs/by-name/qe/qelectrotech/package.nix (hunk 2 above)
Comment (geri1701) [reply pkgs/by-name/qe/qelectrotech/package.nix:35]: Thanks, I checked this. In principle I agree, but in this case the upstream PR was merged after 0.100 on current upstream master, and the upstream patch does not apply cleanly to the 0.100 release source used here.

Using it directly would turn this into a larger adapted backport, so I kept the small 0.100-compatible patch for this interim nixpkgs fix until a QElectroTech release includes the upstream work.

File: pkgs/by-name/qe/qelectrotech/package.nix (hunk 3 above)
Comment (geri1701) [reply pkgs/by-name/qe/qelectrotech/package.nix:89]: I kept these in the first commit intentionally because that commit should build on its own. After the no-KF5 build fix, the build reaches `installPhase`; without these `../...` source-tree paths it fails there because nixpkgs builds out of source and `misc/qelectrotech.desktop`, `elements`, `lang`, etc. are not in the build directory.

The second commit is limited to the runtime resource-path wrapper flags.

File: pkgs/by-name/qe/qelectrotech/package.nix (hunk 4 above)
Comment (geri1701) [reply pkgs/by-name/qe/qelectrotech/package.nix:73]: Answered above: I kept those `installPhase` path changes in the first commit so
 the first commit builds on its own. The second commit is only the runtime wrapper
 flags shown here.

File: pkgs/by-name/qe/qelectrotech/package.nix (hunk 3 above)
Comment (doronbehar) [reply pkgs/by-name/qe/qelectrotech/package.nix:89]: > The second commit is limited to the runtime resource-path wrapper flags.

Fair enough, thanks for your patience.

File: pkgs/by-name/qe/qelectrotech/package.nix (hunk 2 above)
Comment (doronbehar) [reply pkgs/by-name/qe/qelectrotech/package.nix:35]: I see. Still mentioning at least in a comment that this is a manual backport patch for upstream PR X would be nice.

Comment (geri1701) [reply pkgs/by-name/qe/qelectrotech/package.nix:35]: Done, thanks. I added a short comment next to the local patch, pointing to the upstream PR and clarifying that this is the 0.100-compatible manual backport of the Qt-only color widget fallback.

**Comment by doronbehar** [comment]
Thanks again for your cooperation!
