### PR TITLE
evdi: 1.6.4 -> git-2020-01-16

### LINKED ISSUE #74698: evdi broken: /build/source/module/evdi_drv.h:23:10: fatal error: linux/reservation.h: No such file or directory
## Issue description

Tried to update my unstable installation and it fails on evdi compliation:

```
'/nix/store/j5gbwl29jg11sgc8cjk2h8v95sq06fiy-busybox-1.31.1/sbin/cut' -> '/nix/store/jfc463n33x86wn3ylclag0gwyx80mz7z-extra-utils/bin/cut'
building '/nix/store/2iywkkpvirmmj0sn2xlb3b2ji9mmkzjk-fc-cache.drv'...
In file included from /build/source/module/evdi_drv.c:16:
/build/source/module/evdi_drv.h:23:10: fatal error: linux/reservation.h: No such file or directory
 #include <linux/reservation.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

## Technical details

Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.11, NixOS, 20.03pre202088.e89b21504f3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(hyper): `"nixos-19.09pre185402.5eac339829b"`
 - channels(root): `"nixos-20.03pre203172.0ee0489d42e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by sjau**
###### Motivation for this change

EVDI 1.6.4 doesn't compile/work on kernel 5.4.11. A user in the support groups supplied a patch that works on latest git.

It fixes #74698

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/os-specific/linux/evdi/default.nix [hunk 1]
```diff
@@ -1,37 +1,40 @@
-{ stdenv, fetchFromGitHub, kernel, libdrm }:
+{ stdenv, fetchFromGitHub, fetchgit, fetchpatch, kernel, libdrm }:
```
Comment (peterhoeg) [inline pkgs/os-specific/linux/evdi/default.nix]: You don't need `fetchgit`.

File: pkgs/os-specific/linux/evdi/default.nix [hunk 2]
```diff
@@ -1,37 +1,40 @@
...
 
 stdenv.mkDerivation rec {
   pname = "evdi";
-  version = "1.6.4";
+  version = "-git-2019-01-16";
```
Comment (peterhoeg) [inline pkgs/os-specific/linux/evdi/default.nix]: I think we use `unstable-yyyymmdd` for date tags.

File: pkgs/os-specific/linux/evdi/default.nix [hunk 3]
```diff
@@ -1,37 +1,40 @@
...
   };
 
   nativeBuildInputs = kernel.moduleBuildDependencies;
 
   buildInputs = [ kernel libdrm ];
 
-  makeFlags = [
-    "KDIR=${kernel.dev}/lib/modules/${kernel.modDirVersion}/build"
-    "KVER=${kernel.modDirVersion}"
+  patchFlags = [ "-Np1" ];
```
Comment (peterhoeg) [inline pkgs/os-specific/linux/evdi/default.nix]: Shouldn't be needed.

File: pkgs/os-specific/linux/evdi/default.nix [hunk 4]
```diff
@@ -1,37 +1,40 @@
...
+  patches = [
```
Comment (peterhoeg) [inline pkgs/os-specific/linux/evdi/default.nix]: That formatting is odd.

File: pkgs/os-specific/linux/evdi/default.nix [hunk 5]
```diff
@@ -1,37 +1,40 @@
...
+     (fetchpatch {   url    = "https://crazy.dev.frugalware.org/evdi-all-in-one-fixes.patch";
+                     sha256 = "03hs68v8c2akf8a4rc02m15fzyp14ay70rcx8kwg2y98qkqh7w30"; })
   ];
 
+  makeFlags = [ "KVER=${kernel.modDirVersion}" "KDIR=${kernel.dev}/lib/modules/${kernel.modDirVersion}/build" ];
```
Comment (peterhoeg) [inline pkgs/os-specific/linux/evdi/default.nix]: One string per line please.

File: pkgs/os-specific/linux/evdi/default.nix [hunk 6]
```diff
@@ -1,37 +1,40 @@
...
+    install -Dm755 library/libevdi.so.1.6.4 $out/lib/libevdi.so
   '';
 
   meta = with stdenv.lib; {
     description = "Extensible Virtual Display Interface";
-    homepage = "https://www.displaylink.com/";
-    license = with licenses; [ lgpl21 gpl2 ];
     platforms = platforms.linux;
+    license = with licenses; [ lgpl21 gpl2 ];
+    homepage = https://www.displaylink.com/;
```
Comment (peterhoeg) [inline pkgs/os-specific/linux/evdi/default.nix]: Quotes around the url please.

File: pkgs/os-specific/linux/evdi/default.nix [hunk 7]
```diff
@@ -1,37 +1,40 @@
...
-    "KVER=${kernel.modDirVersion}"
+  patchFlags = [ "-Np1" ];
+  patches = [
+     (fetchpatch {   url    = "https://crazy.dev.frugalware.org/evdi-all-in-one-fixes.patch";
+                     sha256 = "03hs68v8c2akf8a4rc02m15fzyp14ay70rcx8kwg2y98qkqh7w30"; })
   ];
 
+  makeFlags = [ "KVER=${kernel.modDirVersion}" "KDIR=${kernel.dev}/lib/modules/${kernel.modDirVersion}/build" ];
+
   hardeningDisable = [ "format" "pic" "fortify" ];
```
Comment (peterhoeg) [inline pkgs/os-specific/linux/evdi/default.nix]: Are you sure these are still needed? Would be great if we could one (or all) of them

Comment (sjau) [reply pkgs/os-specific/linux/evdi/default.nix]: Not sure what you mean by "these" but then I have no idea... I just modified current to get it working with git and the patch.

File: pkgs/os-specific/linux/evdi/default.nix (hunk 1 above)
Comment (sjau) [reply pkgs/os-specific/linux/evdi/default.nix]: fixed.

File: pkgs/os-specific/linux/evdi/default.nix (hunk 4 above)
Comment (sjau) [reply pkgs/os-specific/linux/evdi/default.nix]: Not sure what you mean by that.

Comment (Legogris) [reply pkgs/os-specific/linux/evdi/default.nix]: I think they mean that the indentation, prefer something like this:

```
  patches = [
    (fetchpatch {
      url = "https://crazy.dev.frugalware.org/evdi-all-in-one-fixes.patch";
      sha256 = "03hs68v8c2akf8a4rc02m15fzyp14ay70rcx8kwg2y98qkqh7w30"; })
  ];
```

Comment (sjau) [reply pkgs/os-specific/linux/evdi/default.nix]: Fixed that now. Thx.

**Comment by Legogris** [comment]
@sjau I tried this locally and it works fine on nixpkgs linux latest (with setting xrandr provider, documented it here: https://nixos.wiki/wiki/Displaylink).

Maybe to ease merging this sooner, squash the commits to make the commit history nicer?

**Comment by sjau** [comment]
> @sjau I tried this locally and it works fine on nixpkgs linux latest (with setting xrandr provider, documented it here: https://nixos.wiki/wiki/Displaylink).

I had to run that xrandr command once and KDE remmebers it. Didn't need to alter any files.

> Maybe to ease merging this sooner, squash the commits to make the commit history nicer?

No idea how to do that. I'm just a basic git user.

**Comment by Legogris** [comment]
> > Maybe to ease merging this sooner, squash the commits to make the commit history nicer?
> 
> No idea how to do that. I'm just a basic git user.

You can do an interactive rebase: `$ git rebase -i origin/master` (or replace `origin` with whatever you named the upstream remote), `pick` the top commit and `squash` or `fixup` the rest, and it should combine all your changes in a single commit. After the fact you can also `git commit --amend` if you want to change the commit message of the latest commit.

**Review by Legogris — APPROVED** [review]

**Comment by sjau** [comment]
@peterhoeg *ping*

**Comment by peterhoeg** [comment]
All good!

**Comment by dasJ** [comment]
@sjau Does this build for you? Because the `broken` meta attribute is still set to 4.19

**Comment by sjau** [comment]
@dasJ 

the broken attribute is set to 4.9 or older.

https://github.com/sjau/nixpkgs/blob/edd636f7cd25826efc70a99962db4d1c7c824b3f/pkgs/os-specific/linux/evdi/default.nix#L42

**Comment by dasJ** [comment]
oh…
