### ISSUE TITLE
gettext fails to build on osx 10.10 during stdenv-darwin-boot-*

### ISSUE THREAD

**Issue by yiding** [NixOS/nixpkgs#6596]
I get this when attempting to build basically anything:

```
areadlink.c:38:24: error: use of undeclared identifier 'AT_FDCWD'
  return careadlinkat (AT_FDCWD, filename, NULL, 0, NULL, careadlinkatcwd);
                       ^
1 error generated.
careadlinkat.c:51:13: error: use of undeclared identifier 'AT_FDCWD'
  if (fd != AT_FDCWD)
            ^
make[5]: *** [areadlink.o] Error 1
make[5]: *** Waiting for unfinished jobs....
1 error generated.
make[5]: *** [careadlinkat.o] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
note: keeping build directory ‘/private/var/folders/85/xq6d18ks7lx2pfd2zrys9kg90qpwsm/T/nix-build-gettext-0.18.2.drv-1’
builder for ‘/nix/store/njpl2l5gh9mcfcls2y52fcflq366d4gf-gettext-0.18.2.drv’ failed with exit code 2
building path(s) ‘/nix/store/l69a579vj5976sz2q2gs1j0hl9kavmzk-autoconf-2.69’
cannot build derivation ‘/nix/store/qmxxa8wvd13mpz733ilfhi7afdgvkkq3-sharutils-4.11.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/mghwrq2mvf84b9034hfi5ghlzy9l374q-libarchive-3.1.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/7ghamn8nwszzfbm9wq2pafnaq0h4phvq-cmake-2.8.12.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/xkrj0mysq1jy9llhn524afra8nyx86ag-clang-3.5.0.drv’: 1 dependencies couldn't be built
```

It seems that AT_FDCWD is not declared in the relevant file (fcntl.h) in 10.9 SDK, but it is declared in 10.10 SDK (or the root /usr/include if the system is running on 10.10).

Might be related to dad86b4f544db4d497e4bbe769dec0bb3e9cfbd7 which introduced picking 10.9 sdk over using whatever is present on the system.

**Comment by gridaphobe** [comment]
@yiding That commit is indeed the source of the issue, but we've since fixed it in master. Can you verify that the current master builds for you?

**Comment by yiding** [comment]
Seems fine now.
