### ISSUE TITLE
GLIBC 2.38 linking error with fsanitize with nixpkgs/nixos-23.11

### ISSUE THREAD

**Issue by m1dugh** [NixOS/nixpkgs#279706]
### Describe the bug
With nixpkgs 23.11, when building a C project with automake using -fsanitize=address flags, a build error occurs involving `libstdc++`.

### Steps To Reproduce
1. Create a C project with automake
2. Compile and link with -fsanitize=address

### Observed behavior
```
...
/nix/store/1fn92b0783crypjcxvdv6ycmvi27by0j-binutils-2.40/bin/ld:
/nix/store/myw67gkgayf3s2mniij7zwd79lxy8v0k-gcc-12.3.0-lib/lib/libstdc++.so.6:
undefined reference to `__isoc23_strtoul@GLIBC_2.38'
collect2: error: ld returned 1 exit status
```

### Expected behavior
Proper linking not involving `libstdc++`.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.20230815.bfd953b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(user): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/store/zq7ldyawbgkjhj0k0fphrds5dphm4ksy-source`
```
PS: This has been run using a flake running `nixpkgs/nixos-23.11`, despite the environment, and works properly in `nixpkgs/nixos-23.05`.

**Comment by shymega** [comment]
I'm experiencing this bug with NixOS 23.11, using Rust and `libcpuid` via `cpuid-rs`.

Currently working on using the NixOS 23.05 Flake input, so I can still work on my project, but this should be bumped for examination in prep for next NixOS release.
