### PR TITLE
cen64: unstable-2022-10-02 -> 0-unstable-2023-05-29, fix build with gcc14

### PR DESCRIPTION
**Pull request by ghpzin**
cen64: unstable-2022-10-02 -> 0-unstable-2023-05-29

---

cen64: fix build with gcc14
- add patch from unmerged upstream PR (only `bus/controller.c`, other changes are already applied in master):
https://github.com/n64dev/cen64/pull/191/commits/f13bdf94c00a9da3b152ed9fe20001e240215b96
fixes error from gcc14:
`error: initialization of ... from incompatible pointer type`

- add patch from unmerged upstream PR:
https://github.com/n64dev/cen64/pull/237
fixes errors from gcc14:
`error: passing argument 1 of 'cen64_thread_setname' makes pointer from integer without a cast [-Wint-conversion]`
`error: passing argument 1 of 'cen64_thread_setname' makes integer from pointer without a cast [-Wint-conversion]`

---

Fixes build failure of `cen64` since `2025-01-14` (update to GCC14 in #356812):
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.cen64.x86_64-linux
https://hydra.nixos.org/build/292986743

Error log (fixed with `cast-mi_regs-callbacks.patch`):
```text
/build/source/bus/controller.c: In function 'bus_init':
/build/source/bus/controller.c:47:6: error: initialization of 'int (*)(void *, uint32_t,  uint32_t *)' {aka 'int (*)(void *, unsigned int,  unsigned int *)'} from incompatible pointer type 'int (*)(struct vr4300 *, uint32_t,  uint32_t *)' {aka 'int (*)(struct vr4300 *, unsigned int,  unsigned int *)'} []
   47 |     {read_mi_regs, write_mi_regs, MI_REGS_BASE_ADDRESS, MI_REGS_ADDRESS_LEN},
      |      ^~~~~~~~~~~~
/build/source/bus/controller.c:47:6: note: (near initialization for 'mappings[2].read')
/build/source/bus/controller.c:47:20: error: initialization of 'int (*)(void *, uint32_t,  uint32_t,  uint32_t)' {aka 'int (*)(void *, unsigned int,  unsigned int,  unsigned int)'} from incompatible pointer type 'int (*)(struct vr4300 *, uint32_t,  uint32_t,  uint32_t)' {aka 'int (*)(struct vr4300 *, unsigned int,  unsigned int,  unsigned int)'} []
   47 |     {read_mi_regs, write_mi_regs, MI_REGS_BASE_ADDRESS, MI_REGS_ADDRESS_LEN},
      |                    ^~~~~~~~~~~~~
/build/source/bus/controller.c:47:20: note: (near initialization for 'mappings[2].write')
```

After applying first patch other errors come up (fixed with `fix-thread-arg-type-for-pthread_setname_np.patch`):
```text
/build/source/cen64.c:475:24: error: passing argument 1 of 'cen64_thread_setname' makes pointer from integer without a cast [-Wint-conversion]
  475 |   cen64_thread_setname(thread, "device");
      |                        ^~~~~~
      |                        |
      |                        cen64_thread {aka long unsigned int}
In file included from /build/source/device/device.h:26,
                 from /build/source/cen64.c:15:
/build/source/os/posix/thread.h:59:54: note: expected 'cen64_thread *' {aka 'long unsigned int *'} but argument is of type 'cen64_thread' {aka 'lo>
   59 | static inline int cen64_thread_setname(cen64_thread *t, const char *name) {
      |                                        ~~~~~~~~~~~~~~^
```
```text
/build/source/gdb/gdb.c:82:24: error: passing argument 1 of 'cen64_thread_setname' makes integer from pointer without a cast [-Wint-conversion]
   82 |   cen64_thread_setname(NULL, "gdb");
      |                        ^~~~
      |                        |
      |                        void *
/build/source/os/posix/thread.h:59:53: note: expected 'cen64_thread' {aka 'long unsigned int'} but argument is of type 'void *'
   59 | static inline int cen64_thread_setname(cen64_thread t, const char *name) {
      |                                        ~~~~~~~~~~~~~^
```

Upstream PRs with included patches:
https://github.com/n64dev/cen64/pull/191
https://github.com/n64dev/cen64/pull/237

Tracking issue: #388196

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ghpzin** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 393091`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>cen64</li>
  </ul>
</details>

File: pkgs/by-name/ce/cen64/package.nix [hunk 1]
```diff
@@ -11,15 +11,23 @@
 
 stdenv.mkDerivation rec {
   pname = "cen64";
-  version = "unstable-2022-10-02";
+  version = "unstable-2023-05-29";
```
Comment (petrzjunior) [inline pkgs/by-name/ce/cen64/package.nix:14]:
```suggestion
  version = "0-unstable-2023-05-29";
```
per https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#versioning
