### PR TITLE
haskellPackages.apecs-physics: fix build on darwin

### LINKED ISSUE #107358: haskellPackages.apecs-gloss fails to build
**Describe the bug**
`haskellPackagea.apecs-gloss` fails to build with error

```
running nix build -f. haskellPackages.apecs-gloss
builder for '/nix/store/vwr9wdbqn7ahf8kii2xznqvqsk0y9qnf-apecs-physics-0.4.4.drv' failed with exit code 1; last 10 log lines:
  
  Chipmunk2D/src/cpHastySpace.c:11:10: error:
       fatal error: sys/sysctl.h: No such file or directory
         11 | #include <sys/sysctl.h>
            |          ^~~~~~~~~~~~~~
     |
  11 | #include <sys/sysctl.h>
     |          ^
  compilation terminated.
  `cc' failed in phase `C Compiler'. (Exit code: 1)
```

I ran a git bisect with range from around now to 15K commits ago, when the build still worked. First bad commit is 30286ebcc178aec1fb3797ba3ec88cf75feb282b.

<details>
<summary>Git bisect log</summary>

```
git bisect log
git bisect start
# bad: [5f04cf274984c76439ba8ed5998593b2e5a5ef7a] Merge pull request #107108 from veprbl/pr/awkward_1_0_1
git bisect bad 5f04cf274984c76439ba8ed5998593b2e5a5ef7a
# good: [8c9e7a7c7ec280f5acb496ab5ac717d82ccdf1e0] Merge pull request #86446 from gnidorah/cpu-x
git bisect good 8c9e7a7c7ec280f5acb496ab5ac717d82ccdf1e0
# good: [12d10868fcac6d3c361408ae6929447c291d6e9e] Merge pull request #97168 from r-ryantm/auto-update/hcloud
git bisect good 12d10868fcac6d3c361408ae6929447c291d6e9e
# bad: [11fc05583669cf3cb8c99dc6cb6f6ca7d93fa01d] pam_mount: add support for LUKS2
git bisect bad 11fc05583669cf3cb8c99dc6cb6f6ca7d93fa01d
# good: [8cae8e54a144897c1e58d0f48c3f9bc6740e1dc1] Revert "mediatomb/gerbera: Add release note information for 20.09"
git bisect good 8cae8e54a144897c1e58d0f48c3f9bc6740e1dc1
# bad: [582f622f6c82e8db2efc4d490e5945db177ed597] Merge pull request #101481 from makefu/pkgs/cozy/0.7.2
git bisect bad 582f622f6c82e8db2efc4d490e5945db177ed597
# bad: [1c0f102220df0b5ed01b28712579e7f76435063e] pyocr: Use tesseract without alias
git bisect bad 1c0f102220df0b5ed01b28712579e7f76435063e
# good: [6bae92a3eea8c56999d9c76417809a81e0fedfa6] Merge pull request #99980 from romildo/upd.marwaita-ubuntu
git bisect good 6bae92a3eea8c56999d9c76417809a81e0fedfa6
# good: [725a65545ece5d948c002af2c61ab35877c8f9fc] perlPackages: group aliases
git bisect good 725a65545ece5d948c002af2c61ab35877c8f9fc
# bad: [d544b64c7db02a7c8855247f8598cae10dc10e89] libheif: 1.8.0 -> 1.9.1
git bisect bad d544b64c7db02a7c8855247f8598cae10dc10e89
# bad: [25e60944c6b6c1527cebd4fe11428cf3f438b9dd] python3Packages.python-engineio: fix build w/glibc-2.32
git bisect bad 25e60944c6b6c1527cebd4fe11428cf3f438b9dd
# bad: [883bdf8070d413ae1b11d7af797db934b4eb9e29] xawtv: fix build w/glibc-2.32
git bisect bad 883bdf8070d413ae1b11d7af797db934b4eb9e29
# good: [61517de024cc9e61c18f2434656c18067a2d68a4] Merge pull request #93912 from thefloweringash/cctools-tapi
git bisect good 61517de024cc9e61c18f2434656c18067a2d68a4
# good: [97bfffe7bad60bd70e920bf738effffb7339289e] Merge pull request #97729 from marsam/update-node-14x
git bisect good 97bfffe7bad60bd70e920bf738effffb7339289e
# good: [2e075ba96c57dacec742f08636fecce11e8f5223] Merge pull request #96906 from kampka/gts
git bisect good 2e075ba96c57dacec742f08636fecce11e8f5223
# bad: [08bc71284367bf3490b0d97792dc0bc27a059ef2] dateutils: fix build w/glibc-2.32
git bisect bad 08bc71284367bf3490b0d97792dc0bc27a059ef2
# bad: [30286ebcc178aec1fb3797ba3ec88cf75feb282b] glibc: 2.31 -> 2.32
git bisect bad 30286ebcc178aec1fb3797ba3ec88cf75feb282b
# first bad commit: [30286ebcc178aec1fb3797ba3ec88cf75feb282b] glibc: 2.31 -> 2.32
```
</details>

**To Reproduce**
```
$ nix build -f '<nixpkgs>' haskellPackages.apecs-gloss
```

**Expected behavior**
Build should succeed.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.80, NixOS, 21.03pre257780.e9158eca70a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre255513.8ee7c2505f9"`
 - channels(siraben): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

apecs-physics was broken by glibc 2.32 which removed sys/sysctl.h. Since
sysctl is only used on macOS in the offending source file, we patch it
to only include the header on macOS, fixing the build on linux.

Resolves #107358.

Testing this fix on darwin may be a good idea.

apecs-stm is broken for an unrelated reason, it seems.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
cc @siraben  for testing

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 107395` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by siraben** [comment]
<details>
<summary>Suggestion</summary>

```diff
diff --git a/pkgs/development/haskell-modules/hackage-packages.nix b/pkgs/development/haskell-modules/hackage-packages.nix
index f172a3d4247..8eb07a0dfbe 100644
--- a/pkgs/development/haskell-modules/hackage-packages.nix
+++ b/pkgs/development/haskell-modules/hackage-packages.nix
@@ -30736,7 +30736,6 @@ self: {
        description = "Simple gloss renderer for apecs";
        license = stdenv.lib.licenses.bsd3;
        hydraPlatforms = stdenv.lib.platforms.none;
-       broken = true;
      }) {};
 
   "apecs-physics" = callPackage
@@ -30754,7 +30753,6 @@ self: {
        description = "2D physics for apecs";
        license = stdenv.lib.licenses.bsd3;
        hydraPlatforms = stdenv.lib.platforms.none;
-       broken = true;
      }) {};
 
   "apecs-physics-gloss" = callPackage
@@ -30767,7 +30765,6 @@ self: {
        description = "Gloss rendering for apecs-physics";
        license = stdenv.lib.licenses.bsd3;
        hydraPlatforms = stdenv.lib.platforms.none;
-       broken = true;
      }) {};
 
   "apecs-stm" = callPackage

```
</details>

**Comment by sternenseemann** [comment]
No, this is done automatically during the next haskellPackage update. The [process is described here](https://www.youtube.com/watch?v=KLhkAEk8I20). To test the change, you'll have to checkout the branch, build and set NIXPKGS_ALLOW_BROKEN=1 temporarily.

**Comment by siraben** [comment]
I see, I wasn't aware of that! Thanks!

**Comment by siraben** [comment]
Build fails on darwin

```
Preprocessing library for apecs-physics-0.4.4..
Building library for apecs-physics-0.4.4..
[1 of 9] Compiling Apecs.Physics.Types ( src/Apecs/Physics/Types.hs, dist/build/Apecs/Physics/Types.o, dist/build/Apecs/Physics/Types.dyn_o )

src/Apecs/Physics/Types.hs:24:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
24 | import           Data.Monoid               ((<>))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2 of 9] Compiling Apecs.Physics.Space ( src/Apecs/Physics/Space.hs, dist/build/Apecs/Physics/Space.o, dist/build/Apecs/Physics/Space.dyn_o )

src/Apecs/Physics/Space.hs:19:1: warning: [-Wunused-imports]
    The import of ‘liftIO’
    from module ‘Control.Monad.IO.Class’ is redundant
   |
19 | import           Control.Monad.IO.Class (liftIO, MonadIO)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In file included from /private/tmp/nix-build-apecs-physics-0.4.4.drv-0/ghc65731_0/ghc_13.c:2:0: error:
    

In file included from Chipmunk2D/include/chipmunk/chipmunk.h:60:0: error:
    

Chipmunk2D/include/chipmunk/chipmunk_types.h:45:12: error:
     fatal error: 'ApplicationServices/ApplicationServices.h' file not found
                    #include <ApplicationServices/ApplicationServices.h>
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   |
45 |                 #include <ApplicationServices/ApplicationServices.h>
   |            ^
1 error generated.

<no location info>: error:
    `cc' failed in phase `C Compiler'. (Exit code: 1)
[5 of 9] Compiling Apecs.Physics.Geometry ( src/Apecs/Physics/Geometry.hs, dist/build/Apecs/Physics/Geometry.o, dist/build/Apecs/Physics/Geometry.dyn_o )
builder for '/nix/store/g9704wwzvl8iazs2wmim2r8wqb7xx3i5-apecs-physics-0.4.4.drv' failed with exit code 1
error: build of '/nix/store/g9704wwzvl8iazs2wmim2r8wqb7xx3i5-apecs-physics-0.4.4.drv', '/nix/store/knwc67mbs388ag01rdmqbjxz79ryhnfy-apecs-gloss-0.2.4.drv' failed
```

**Comment by sternenseemann** [comment]
This build failure is at least unrelated to the change, seems like it is caused by this inclusion <https://github.com/slembcke/Chipmunk2D/blob/master/include/chipmunk/chipmunk_types.h#L44-L46>. I tried adding `ApplicationServices` in the latest commit, can you try again?

**Comment by siraben** [comment]
Builds succeed.

```
/nix/store/c1pg6nwma239hl3frmnps5xvraqs0490-apecs-physics-gloss-0.1.0.0/lib/ghc-8.10.2/x86_64-osx-ghc-8.10.2/libHSapecs-physics-gloss-0.1.0.0-3bBGdoAytgO4tSFqGMPwDX-ghc8.10.2.dylib: fixing dylib
/nix/store/c1pg6nwma239hl3frmnps5xvraqs0490-apecs-physics-gloss-0.1.0.0/lib/ghc-8.10.2/x86_64-osx-ghc-8.10.2/libHSapecs-physics-gloss-0.1.0.0-3bBGdoAytgO4tSFqGMPwDX-ghc8.10.2.dylib: fixing dylib
strip is /nix/store/i1mccwrczhhacpk0jn58wmixqiqh1vkb-cctools-binutils-darwin-949.0.1/bin/strip
patching script interpreter paths in /nix/store/d6wx7dvw47hr6ymhg5nwfvz9pasa9kc5-apecs-physics-gloss-0.1.0.0-doc
/nix/store/7v431007lprfk4m6hxh6lalikvdmm5ha-apecs-physics-0.4.4
/nix/store/98kvmwv6as2n0svrxwxi7mwslniclzql-apecs-gloss-0.2.4
/nix/store/c1pg6nwma239hl3frmnps5xvraqs0490-apecs-physics-gloss-0.1.0.0
```

File: pkgs/development/haskell-modules/configuration-common.nix [hunk 1]
```diff
@@ -1541,4 +1541,15 @@ self: super: {
...
+  # Add ApplicationServices on darwin
+  # Patch can be removed if https://github.com/jonascarpay/apecs/pull/77 is resolved
+  apecs-physics =
+    let
+      sysDeps = pkgs.lib.optional pkgs.stdenv.isDarwin pkgs.darwin.apple_sdk.frameworks.ApplicationServices;
+    in addPkgconfigDepends (appendPatch super.apecs-physics (pkgs.fetchpatch {
+      url = "https://github.com/jonascarpay/apecs/pull/77/commits/24975a4e689fb9920168bbbcb451d8fb8a16abdb.patch";
+      sha256 = "0w7ivv9wgrkba9psbc4920y0apg5cpyz9fwwzizfgqhy0gz6ss7y";
+      stripLen = 1;
+    })) sysDeps;
```
Comment (cdepillabout) [inline pkgs/development/haskell-modules/configuration-common.nix:1553]: Ping @jonascarpay.

Does this change look okay to you, or does it make more sense just to wait for you to release a new version of `apecs-physics` to Hackage?

**Comment by jonascarpay** [comment]
@cdepillabout Yeah, I think this is best fixed properly upstream. I'll push a new version today.

**Comment by sternenseemann** [comment]
To fix the darwin build, 96376c6a8c1ba53dcebcb87d3deefbb03e825a73 should be cherry-picked or merged either way though.

**Comment by jonascarpay** [comment]
@sternenseemann Why is that the case? The [stock Chipmunk2D](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/chipmunk/default.nix) doesn't have that. Is there something I can do about that?

**Comment by sternenseemann** [comment]
@jonascarpay Judging from this comment, seems like the normal Chipmunk hasn't been really tested on macOS: <https://github.com/NixOS/nixpkgs/blob/179eb032dfdce82e9c0cf1c2edfd531d9ecebab6/pkgs/development/libraries/chipmunk/default.nix#L35>

As far as I understand in `apec-physics` Chipmunk is vendored anyways right?

On darwin the build fails because `ApplicationServices/ApplicationServices.h` is missing on macOS (<https://github.com/NixOS/nixpkgs/pull/107395#issuecomment-749537379>) which is fixed by the mentioned commit by adding that as a build dependency.

**Comment by jonascarpay** [comment]
> Judging from this comment, seems like the normal Chipmunk hasn't been really tested on macOS

ahh I see, thanks, I overlooked that line

> As far as I understand in apec-physics Chipmunk is vendored anyways right?

Yeah, just asking for my own edification.

**Comment by jonascarpay** [comment]
I just pushed 0.4.5 to hackage, which includes the [`sysctl.h` guard](https://github.com/jonascarpay/apecs/blob/900b41fb2803c157254f4189f3f5119c4fa19ea8/apecs-physics/Chipmunk2D/src/cpHastySpace.c#L11-L13).

**Comment by sternenseemann** [comment]
@cdepillabout is it alright to just update the pin to 0.4.5 for the next haskell-update like in 96796994bf684689bcc6997d65d91d1368c17049?

**Comment by cdepillabout** [comment]
> @cdepillabout is it alright to just update the pin to 0.4.5 for the next haskell-update like in 9679699?

I *think* this should be okay, but let's confirm with @maralorn.

@maralorn, a short explanation is that `apecs-physics` just had a new version released which partially fixed it here in nixpkgs.  I imagine this will be available next time the stackage-nightly version is bumped. @sternenseemann has directly bumped it in 9679699, and I just wanted to confirm that this won't cause any weird problems next time you and peti bump it during the weekly merge thing?

**Comment by siraben** [comment]
Build still succeeds

```
strip is /nix/store/i1mccwrczhhacpk0jn58wmixqiqh1vkb-cctools-binutils-darwin-949.0.1/bin/strip
patching script interpreter paths in /nix/store/qij59k6ccvv1liagvwwp1fb7d14vbdc3-apecs-physics-gloss-0.1.0.0-doc
/nix/store/yafv97h26d1iig2m6cqx4a96sijdxx6a-apecs-physics-0.4.4
/nix/store/lc80b4n4zlblganrplmpn1mrr17kwgv7-apecs-gloss-0.2.4
/nix/store/yhc0axljjmvwk5jcnprck1xvkhdzd2zg-apecs-physics-gloss-0.1.0.0
```

**Comment by sternenseemann** [comment]
(Should be broken on linux until the update is actually performed though)

**Comment by maralorn** [comment]
Huh, @cdepillabout, the problem is that those pins are automatically generated from stackage-nightly. So I am pretty sure this bump would just be reverted if it hasn‘t happened in stackage-nightly.

I think normally we do this by using a "apecs-physics = super.apecs-physics_0_4_5" override. I am not sure if there is a way to override the stackage version in the yaml file.

**Comment by sternenseemann** [comment]
Maybe it's a better idea to merge the darwin fix only which can be done right now and I check after the next haskell-update if we have to override `apecs-physics` or can just mark the packages as unbroken?

**Comment by cdepillabout** [comment]
@sternenseemann That sounds like an easy thing to do right away if you're willing to update this PR again.

**Comment by sternenseemann** [comment]
@cdepillabout Yeah, no problem!

`hackage2nix` is run on fridays usually right?

**Comment by cdepillabout** [comment]
> hackage2nix is run on fridays usually right?

hackage2nix is usually run once a day, but `haskell-updates` is merged into `master` normally once a week on fridays.  I think at the same time the stackage nightly version is updated.  It is normally peti and maralorn doing this: https://www.twitch.tv/videos/841867369

**Comment by sternenseemann** [comment]
@cdepillabout okay, then I'll wait till the new stackage-nightly is out.

Should I force push to drop the second commit then, so you can merge the darwin fix?

**Comment by cdepillabout** [comment]
@sternenseemann This looks good, thanks.

Also, I checked the stackage nightly releases, and it looks like they completely stopped two weeks ago or so.  Don't know what's up: https://www.stackage.org/snapshots
