### ISSUE TITLE
Build failure: xgboost 2.0.0 fails on darwin

### ISSUE THREAD

**Issue by nviets** [NixOS/nixpkgs#257752]
xgboost fails on darwin since the update to 2.0.0. See https://github.com/NixOS/nixpkgs/pull/255061

### Steps To Reproduce

1. On an M1 Mac, run: export NIXPKGS_ALLOW_BROKEN=1
2. nix build -f default.nix xgboost

### Build log

```
...
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /nix/store/xq8s0kxa8awzg9xhkkblbqa0bcl6gky8-libSystem-11.0.0/include
-- /tmp/nix-build-xgboost-2.0.0.drv-0/source/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
Error: Could not run sw_vers:
No such file or directory
Error: Could not run sw_vers:
No such file or directory
Error: Could not run sw_vers:
No such file or directory
-- /tmp/nix-build-xgboost-2.0.0.drv-0/source/dmlc-core/test/unittest/build_config.h.in -> /tmp/nix-build-xgboost-2.0.0.drv-0/source/dmlc-core/test/unittest/build_config.h
-- Found GTest: /nix/store/zpww7sl38rg0amhmkhzzq57py7qq7bll-gtest-1.12.1-dev/lib/cmake/GTest/GTestConfig.cmake (found version "1.12.1")
-- Configuring done (6.2s)
-- Generating done (0.1s)
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_POLICY_DEFAULT_CMP0025


-- Build files have been written to: /tmp/nix-build-xgboost-2.0.0.drv-0/source/build
cmake: enabled parallel building
cmake: enabled parallel installing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j8 SHELL=/nix/store/zqx1fik7mcyg1037s015kfbw2zq0qhqn-bash-5.2-p15/bin/bash
[  1%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io.cc.o
[  1%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o
[  1%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/data.cc.o
[  2%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/line_split.cc.o
[  2%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/input_split_base.cc.o
[  3%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/indexed_recordio_split.cc.o
[  3%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/recordio_split.cc.o
[  3%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/recordio.cc.o
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
[  4%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/filesys.cc.o
[  4%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/local_filesys.cc.o
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
[  5%] Linking CXX static library libdmlc.a
[  5%] Built target dmlc
[  5%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_json.cc.o
[  5%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_any.cc.o
[  6%] Building CXX object src/CMakeFiles/objxgboost.dir/c_api/c_api.cc.o
[  7%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_inputsplit.cc.o
[  7%] Building CXX object src/CMakeFiles/objxgboost.dir/c_api/c_api_error.cc.o
[  7%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_array_view.cc.o
[  8%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_config.cc.o
[  8%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_env.cc.o
[  9%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_lockfree.cc.o
[ 10%] Building CXX object src/CMakeFiles/objxgboost.dir/collective/communicator.cc.o
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/c_api.cc:29:
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/../data/simple_dmatrix.h:16:
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/../data/gradient_index.h:19:
/tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/../data/../common/ref_resource_view.h:79:32: error: member reference base type 'Span' is not a structure or union
    return Span{data(), size()}.size_bytes();
           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
[ 10%] Building CXX object src/CMakeFiles/objxgboost.dir/collective/in_memory_communicator.cc.o
[ 11%] Building CXX object src/CMakeFiles/objxgboost.dir/collective/in_memory_handler.cc.o
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/c_api.cc:6:
In file included from /nix/store/8r1v2mbnfri07zvblalna9xgdfnc763i-libcxx-11.1.0-dev/include/c++/v1/algorithm:643:
/nix/store/8r1v2mbnfri07zvblalna9xgdfnc763i-libcxx-11.1.0-dev/include/c++/v1/memory:3455:7: error: exception specification of overriding function is more lax than base version
class __shared_ptr_emplace
      ^
/nix/store/8r1v2mbnfri07zvblalna9xgdfnc763i-libcxx-11.1.0-dev/include/c++/v1/memory:4291:26: note: in instantiation of template class 'std::__1::__shared_ptr_emplace<xgboost::common::MmapResource, std::__1::allocator<xgboost::common::MmapResource>>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/../common/io.h:387:40: note: in instantiation of function template specialization 'std::__1::make_shared<xgboost::common::MmapResource, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> &, unsigned long &, unsigned long &>' requested here
      : AlignedResourceReadStream{std::make_shared<MmapResource>(path, offset, length)} {}
                                       ^
/nix/store/8r1v2mbnfri07zvblalna9xgdfnc763i-libcxx-11.1.0-dev/include/c++/v1/memory:3364:13: note: overridden virtual function is here
    virtual ~__shared_weak_count();
            ^
[ 11%] Building CXX object src/CMakeFiles/objxgboost.dir/collective/socket.cc.o
2 errors generated.
make[2]: *** [src/CMakeFiles/objxgboost.dir/build.make:76: src/CMakeFiles/objxgboost.dir/c_api/c_api.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 11%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_logging.cc.o
[ 12%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_main.cc.o
[ 12%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_optional.cc.o
[ 13%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_param.cc.o
[ 13%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_parquet_parser.cc.o
[ 14%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_parser.cc.o
[ 14%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_serializer.cc.o
make[1]: *** [CMakeFiles/Makefile2:1110: src/CMakeFiles/objxgboost.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 14%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_tempdir.cc.o
[ 15%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_thread_group.cc.o
[ 15%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_threaditer.cc.o
[ 16%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_threaditer_exc_handling.cc.o
[ 16%] Linking CXX executable dmlc_unit_tests
[ 16%] Built target dmlc_unit_tests
make: *** [Makefile:166: all] Error 2
```

### Additional context

I noticed this on an M1 macbook, and I'm not sure it the same is true on intel macbooks. In the recent PR, all darwin builds are flagged as broken.

**Comment by nviets** [comment]
@trivialfis - Congratulations on the 2.0.0 release! We are excited to update, and it's already available in nixpkgs. I noticed the build began to fail on darwin. Are any special steps or flags required to get it working? I didn't see anything new in [the documentation](https://xgboost.readthedocs.io/en/latest/build.html#building-on-macos). The update can be found in https://github.com/NixOS/nixpkgs/pull/255061.

**Comment by trivialfis** [comment]
Yeah, that's apple clang's issue. `std::make_shared` sometimes don't work. I will patch the release and try to make a 2.0.1.

**Comment by nviets** [comment]
Thanks for the confirmation, @trivialfis - I'll update as soon as you release. Appreciate your quick response.

**Comment by nviets** [comment]
Thanks for the fix! Watching for your next release.

**Comment by trivialfis** [comment]
Hi @nviets , is it possible that you can help run a build with macos+nix using the [latest 2.0 branch](https://github.com/dmlc/xgboost/tree/release_2.0.0) of xgboost when you are available? I can't be certain that we have workaround all issues related to apple clang, for instance, I don't know what's the cause of https://github.com/dmlc/xgboost/issues/9667 . Would be great if I can confirm it's working on nixos before making a new release.

**Comment by nviets** [comment]
I tried a build using `6ab6577511e596fbbd5e9eb30bc3b45bde2c43e9`, but it fails on:

```
[  8%] Building CXX object dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/unittest_json.cc.o
[  9%] Building CXX object src/CMakeFiles/objxgboost.dir/collective/communicator.cc.o
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/c_api.cc:29:
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/../data/simple_dmatrix.h:16:
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/../data/gradient_index.h:19:
/tmp/nix-build-xgboost-2.0.0.drv-0/source/src/c_api/../data/../common/ref_resource_view.h:79:32: error: member reference base type 'Span' is not a structure or union
    return Span{data(), size()}.size_bytes();
           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```
When I free up from work, I'll start a 2.0.1 branch where it will be easier to share logs.

**Comment by trivialfis** [comment]
Let me try to reproduce it on AWS. Haven't touched a Mac before, might reach out for additional help. :-)

**Comment by nviets** [comment]
@trivialfis - please have a look at https://github.com/NixOS/nixpkgs/pull/260985. I'll post some logs shortly.

**Comment by hcho3** [comment]
@trivialfis I am getting my hands on an M1 mini soon. I can help once I get it.

**Comment by trivialfis** [comment]
@hcho3 That's awesome!

**Comment by hcho3** [comment]
@nviets Can you try https://github.com/dmlc/xgboost/pull/9684 ? I was able to build it on M1 Mac.

**Comment by nviets** [comment]
@hcho3  - Thanks for the update. This commit reached 62%, but failed on the error below:

```
...
[ 60%] Building CXX object CMakeFiles/testxgboost.dir/tests/cpp/common/test_io.cc.o
[ 60%] Building CXX object CMakeFiles/testxgboost.dir/tests/cpp/common/test_json.cc.o
[ 61%] Building CXX object CMakeFiles/testxgboost.dir/tests/cpp/common/test_linalg.cc.o
[ 61%] Linking CXX executable /tmp/nix-build-xgboost-2.0.0.drv-0/source/xgboost
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/objective/lambdarank_obj.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/objective/lambdarank_obj.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/objective/lambdarank_obj.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/objective/lambdarank_obj.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/objective/lambdarank_obj.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/objective/lambdarank_obj.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const* xgboost::Cast<xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const* xgboost::Cast<xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const* xgboost::Cast<xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const* xgboost::Cast<xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<long long, (xgboost::Value::ValueKind)10>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const* xgboost::Cast<xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const* xgboost::Cast<xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const* xgboost::Cast<xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const* xgboost::Cast<xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<unsigned char, (xgboost::Value::ValueKind)8>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const* xgboost::Cast<xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const* xgboost::Cast<xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const* xgboost::Cast<xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const* xgboost::Cast<xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/multi_target_tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<int, (xgboost::Value::ValueKind)9>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const* xgboost::Cast<xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7> const, xgboost::Value>(xgboost::Value*)' from file 'src/CMakeFiles/objxgboost.dir/tree/tree_model.cc.o' to global weak symbol 'typeinfo for xgboost::JsonTypedArray<float, (xgboost::Value::ValueKind)7>' from file 'src/CMakeFiles/objxgboost.dir/common/json.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[ 62%] Built target xgboost
make[1]: *** [CMakeFiles/Makefile2:278: CMakeFiles/testxgboost.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by nviets** [comment]
Btw, sorry I haven't uploaded full logs yet. The script I was using to post on github isn't working any longer, and I haven't found an alternative yet.

**Comment by nviets** [comment]
You can reproduce from my branch directly, with: 
```
nix build github:nviets/nixpkgs/bce262b71a40582567e0ca6128b6fe4564026d0b#xgboost
```

**Comment by hcho3** [comment]
@nviets Are these link warnings considered an error?

**Comment by nviets** [comment]
I am not sure about the ld messages, but I failed to copy the actual error earlier. Here it is:

```
...
[ 61%] Built target runxgboost
[ 61%] Building CXX object CMakeFiles/testxgboost.dir/tests/cpp/common/test_monitor.cc.o
In file included from /tmp/nix-build-xgboost-2.0.0.drv-0/source/tests/cpp/common/test_io.cc:4:
In file included from /nix/store/zpww7sl38rg0amhmkhzzq57py7qq7bll-gtest-1.12.1-dev/include/gtest/gtest.h:54:
/nix/store/8r1v2mbnfri07zvblalna9xgdfnc763i-libcxx-11.1.0-dev/include/c++/v1/memory:3455:7: error: exception specification of overriding function is more lax than base version
class __shared_ptr_emplace
      ^
/nix/store/8r1v2mbnfri07zvblalna9xgdfnc763i-libcxx-11.1.0-dev/include/c++/v1/memory:4291:26: note: in instantiation of template class 'std::__1::__shared_ptr_emplace<xgboost::common::MmapResource, std::__1::allocator<xgboost::common::MmapResource>>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/tmp/nix-build-xgboost-2.0.0.drv-0/source/tests/cpp/common/test_io.cc:151:26: note: in instantiation of function template specialization 'std::__1::make_shared<xgboost::common::MmapResource, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> &, int, unsigned long>' requested here
    auto resource = std::make_shared<MmapResource>(path, 0, sizeof(double));
                         ^
/nix/store/8r1v2mbnfri07zvblalna9xgdfnc763i-libcxx-11.1.0-dev/include/c++/v1/memory:3364:13: note: overridden virtual function is here
    virtual ~__shared_weak_count();
            ^
1 error generated.
make[2]: *** [CMakeFiles/testxgboost.dir/build.make:286: CMakeFiles/testxgboost.dir/tests/cpp/common/test_io.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 62%] Linking CXX shared library /tmp/nix-build-xgboost-2.0.0.drv-0/source/lib/libxgboost.dylib
...
```

**Comment by trivialfis** [comment]
I think the link warning should be fine based on the message,

**Comment by hcho3** [comment]
@nviets Please update this line
https://github.com/NixOS/nixpkgs/blob/bce262b71a40582567e0ca6128b6fe4564026d0b/pkgs/development/libraries/xgboost/default.nix#L54

to the latest commit hash `b7aafa58987b84fc68976a7b26b65dfc1675f764`. https://github.com/dmlc/xgboost/pull/9684 had two commits, and your branch picked up only one of them.

**Comment by hcho3** [comment]
> What's your timeline for a 2.0.1 release?

Probably next week

**Comment by nviets** [comment]
Thanks, I'll watch for it and update quickly.

**Comment by hcho3** [comment]
@nviets XGBoost 2.0.1 is now released. Can you give it a try?

**Comment by nviets** [comment]
This did the trick. Thanks @hcho3. I am updating in nixpkgs.
