### ISSUE TITLE
cc-wrappers inconsistently treats `-idirafter` between native and cross-compilers

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#245455]
### Describe the bug

This works:

```
$ printf '#error "DO NOT INCLUDE ME"' > stdio.h
$ nix shell nixpkgs#stdenv.cc
$$ printf "#include <stdio.h>" | gcc -E - -o - -idirafter . >/dev/null; echo $?
0
```

This does not:

```
$ printf '#error "DO NOT INCLUDE ME"' > stdio.h
$ nix shell nixpkgs#pkgsCross.aarch64-multiplatform.stdenv.cc
$$ printf "#include <stdio.h>" | aarch64-unknown-linux-gnu-gcc -E - -o - -idirafter . >/dev/null; echo $?
In file included from <stdin>:1:
./stdio.h:1:2: error: #error "DO NOT INCLUDE ME"
    1 | #error "DO NOT INCLUDE ME"
      |  ^~~~~
1
```

### Expected behavior
Both should work: `-idirafter` should have a preference below system headers (as it does for ~unwrapped `gcc`and~ other linux distributions).

~It's a side-effect of `cc-wrapper` using `-idirafter` to inject `libc` headers into a reasonable place. But this fails this override semantics.~ UPDATE: I'm not sure what exactly causes it. Maybe it's a `--with-headers=` or `--with-native-system-header-dir=` side-effect. Needs a research.

Practically this causes issues in other packages like `ubootTools` and various attempts at using include injection like https://github.com/NixOS/nixpkgs/pull/219421

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.3, NixOS, 23.11 (Tapir), 23.11.20230725.4076c4f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `""`
 - channels(slyfox): `""`
 - nixpkgs: `/run/current-system/sw/share/nixos-flakes/inputs/nixpkgs`
```

**Comment by trofi** [comment]
And it does seem to be a regression. `22.05` does not fail:

```
$ nix shell github:NixOS/nixpkgs/release-22.05#pkgsCross.aarch64-multiplatform.stdenv.cc
$$ cat stdio.h
#error "DO NOT INCLUDE ME"[nz] /tmp:
$$ printf "#include <stdio.h>" | aarch64-unknown-linux-gnu-gcc -E - -o - -idirafter . >/dev/null; echo $?
0
```

**Comment by trofi** [comment]
Bisected down to https://github.com/NixOS/nixpkgs/pull/219811 `gcc: do not install sys-include headers for cross-compilers`

Proposed the revert in https://github.com/NixOS/nixpkgs/pull/245550

**Comment by risicle** [comment]
Can we close this now that's merged?

Then I should be able to adapt #219421

**Comment by trofi** [comment]
Sounds good. Closing.
