### ISSUE TITLE
qbittorrent: compile error

### ISSUE THREAD

**Issue by rasendubi** [NixOS/nixpkgs#16971]
## Issue description
```
linking qbittorrent
session.o: In function `BitTorrent::Session::getPendingAlerts(std::vector<libtorrent::alert*, std::allocator<libtorrent::alert*> >&, unsigned long)':
/tmp/nix-build-qbittorrent-3.3.5.drv-0/qbittorrent-3.3.5/src/base/bittorrent/session.cpp:2347: undefined reference to `libtorrent::session_handle::wait_for_alert(std::chrono::duration<long, std::ratio<1l, 1000000000l> >)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:849: qbittorrent] Error 1
make[1]: Leaving directory '/tmp/nix-build-qbittorrent-3.3.5.drv-0/qbittorrent-3.3.5/src'
make: *** [Makefile:43: sub-src-make_first] Error 2
builder for ‘/nix/store/g8f4faj2kw1xg2n8zf274bfdwz6zgari-qbittorrent-3.3.5.drv’ failed with exit code 2
error: build of ‘/nix/store/g8f4faj2kw1xg2n8zf274bfdwz6zgari-qbittorrent-3.3.5.drv’ failed
```

### Steps to reproduce

`nix-build -A qbittorrent`

## Technical details

* System: 16.09.git.125ffff (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09.git.efe4d48 and latest master (4b8c31d)

**Comment by rasendubi** [comment]
The issue is caused by #16547. (cc author @womfoo)

I've pushed a fix: https://github.com/NixOS/nixpkgs/pull/16972
