### PR TITLE
{libratbag,openrazer-daemon,whipper}: fix typelib error

### LINKED ISSUE #310205: Openrazer-daemon broke after system update
### Describe the bug
As title says, openrazer-daemon no longer work after update.

### Steps To Reproduce
1. update system
2. reboot
3. openrazer-daemon fail to start.

### Expected behavior
Openrazer-daemon start on boot.

### Additional context
Manually calling openrazer-daemon -Fv print me this:
```shell
openrazer-daemon -Fv
Traceback (most recent call last):
  File "/nix/store/s8vsc4p2cyqc2kim2cjvvl85d9fdz54x-python3.11-openrazer-daemon-3.8.0/bin/.openrazer-daemon-wrapped", line 13, in <module>
    from openrazer_daemon.daemon import RazerDaemon, __version__
  File "/nix/store/s8vsc4p2cyqc2kim2cjvvl85d9fdz54x-python3.11-openrazer-daemon-3.8.0/lib/python3.11/site-packages/openrazer_daemon/daemon.py", line 20, in <module>
    from gi.repository import GLib
  File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GLib, introspection typelib not found
``` 

```shell
`nix-store -q --requisites /run/current-system | cut -d- -f2- | sort | uniq | grep openrazer
openrazer-3.8.0-6.8.9
python3.11-openrazer-3.8.0
python3.11-openrazer-daemon-3.8.0
python3.11-openrazer-daemon-3.8.0-man
unit-openrazer-daemon.service`
``` 

### Notify maintainers
@evanjs 
@roelvandijk
@Lucus16

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240507.b211b39`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.22.0pre20240422_5ecd820`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/f0ssy3p6898x9k880l23mhd0fl6rvrb2-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #312306: whipper execution fails with ImportError
### Describe the bug
When trying to launch whipper it instead fails with the following trace:
```
Traceback (most recent call last):
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/bin/.whipper-wrapped", line 6, in <module>
    from whipper.command.main import main
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/command/main.py", line 11, in <module>
    from whipper.command import cd, offset, drive, image, accurip, mblookup
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/command/cd.py", line 28, in <module>
    from whipper.common import (
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/common/program.py", line 30, in <module>
    from whipper.common import accurip, checksum, common, mbngs, path
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/common/checksum.py", line 28, in <module>
    from whipper.extern.task import task as etask
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/extern/task/task.py", line 24, in <module>
    from gi.repository import GLib as GLib
  File "/nix/store/9njwgmbs7jlpsrnnr731k2vv5xqghqr4-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GLib, introspection typelib not found
```

### Steps To Reproduce
1. `nix run nixpkgs#whipper -- --version` or any equivalent way of running the whipper program

### Expected behavior
Clearly, I expect the program to execute without an error.

### Additional context
I bisected the error and the bug was introduced in ba69532efcec53e3f6243837b364174ad9d840a6 which bumped `gobject-introspection`.

### Notify maintainers
@emilazy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(anton): `""`
 - nixpkgs: `/nix/store/0qd773b63yg8435w8hpm13zqz7iipcbs-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #316701: `ratbagctl` (from `libratbag`) fails to run
### Describe the bug
it's impossible to use `ratbagctl` due to an import error:
```console
[user@system:~]$ ratbagctl info
Traceback (most recent call last):
  File "/nix/store/4x1mm4cm6a891yyl1a9ky08fxril160h-libratbag-0.17/bin/ratbagctl", line 36, in <module>
    from gi.repository import Gio, GLib, GObject
  File "/nix/store/czg030czd0sc7vmwjf71afhd9zskf5n2-python3-3.11.9-env/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gio, introspection typelib not found

[user@system:~]$
```

### Steps To Reproduce
1. set `services.ratbagd.enable = true;`
2. try to run eg `ratbagctl info` 

### Expected behavior
ratbagctl "shows something". (i.e. current mouse hardware/mapping etc.)

### Screenshots
(no gui, cli only)

### Additional context
I (may) need `ratbagctl` because it has infos/options that are not yet fully implemented in `piper`

### Notify maintainers
@mvnetbiz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240529.ad57eef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Artturin**
Fixes https://github.com/NixOS/nixpkgs/issues/316701
Fixes https://github.com/NixOS/nixpkgs/issues/310205
Fixes https://github.com/NixOS/nixpkgs/issues/312306

```
[user@system:~]$ ratbagctl info
Traceback (most recent call last):
  File "/nix/store/4x1mm4cm6a891yyl1a9ky08fxril160h-libratbag-0.17/bin/ratbagctl", line 36, in <module>
    from gi.repository import Gio, GLib, GObject
  File "/nix/store/czg030czd0sc7vmwjf71afhd9zskf5n2-python3-3.11.9-env/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gio, introspection typelib not found
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eclairevoyant — COMMENTED** [review]
Don't we have `wrapGAppsNoGuiHook` for exactly this use case?

**Comment by Sorixelle** [comment]
[`targetcli`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/targetcli/default.nix) also seems to be affected, can we fix it there as well?
