### ISSUE TITLE
onlykey-cli crashing due to new fido2 version not supported by onlykey-solo-python package

### ISSUE THREAD

**Issue by Lgmrszd** [NixOS/nixpkgs#253127]
### Describe the bug
I tried to run `onlykey-cli` and it crashes on commands like `onlykey-cli credential ls`

### Steps To Reproduce
1. `nix shell nixpkgs#onlykey-cli`
2. `onlykey-cli credential ls`
3. 
```shell
PIN: 
Traceback (most recent call last):
  File "/nix/store/3akrqg5nnkwlfsffw92j7m4v5apiwiv0-onlykey-cli-1.2.9/bin/.onlykey-cli-wrapped", line 9, in <module>
    sys.exit(main())
    
    ...
    
  File "/nix/store/vywnxqfbry5cwmkfhlklmp8rk5cc1nnd-python3.10-onlykey-solo-python-0.0.32/lib/python3.10/site-packages/solo/devices/base.py", line 116, in cred_mgmt
    token = client.client_pin.get_pin_token(pin)
AttributeError: 'Fido2Client' object has no attribute 'client_pin'

```

### Expected behavior
The program works as intended

### Screenshots
Example of error is in "Steps To Reproduce"

### Additional context
https://github.com/NixOS/nixpkgs/blob/aa8aa7e2ea35ce655297e8322dc82bf77a31d04b/pkgs/development/python-modules/onlykey-solo-python/default.nix#L24-L34
I noticed that `onlykey-solo-python` python package in nixpkgs is patched to work with `fido2` package newer than 0.9.3 but it seems that at some point the compatibility broke again. Maybe new patch is needed or `fido2` package should be locked to the version that patch supports.

### Notify maintainers

@dotlambda @mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.49, NixOS, 23.11 (Tapir), 23.11.20230830.e7f38be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
> ### Notify maintainers
> @dotlambda @mweinelt

We are not the maintainers. Please look at https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/onlykey-cli/default.nix.

**Comment by Lgmrszd** [comment]
Apologies.
@kalbasit can you take a look at this?
