### ISSUE TITLE
RStudio fails to build

### ISSUE THREAD

**Issue by changlinli** [NixOS/nixpkgs#25315]
## Issue description

RStudio fails to build even though it has built in the past successfully, which is odd because its build file hasn't changed in years.

### Steps to reproduce

Simply try building it and it bombs out.

`nix-env -f <nixpkgs-location> -iA rstudio` results in an error which looks like the following:

```
[ 32%] Building CXX object src/cpp/r/CMakeFiles/rstudio-r.dir/RErrorCategory.cpp.o
[ 33%] Building CXX object src/cpp/r/CMakeFiles/rstudio-r.dir/RExec.cpp.o
[ 33%] Building CXX object src/cpp/r/CMakeFiles/rstudio-r.dir/RFunctionHook.cpp.o
[ 33%] Building CXX object src/cpp/r/CMakeFiles/rstudio-r.dir/RJson.cpp.o
[ 34%] Building CXX object src/cpp/r/CMakeFiles/rstudio-r.dir/RJsonRpc.cpp.o
[ 34%] Building CXX object src/cpp/r/CMakeFiles/rstudio-r.dir/ROptions.cpp.o
[ 34%] Building CXX object src/cpp/r/CMakeFiles/rstudio-r.dir/RRoutines.cpp.o
/tmp/nix-build-RStudio-0.98.110.drv-0/rstudio-0.98.110/src/cpp/r/RRoutines.cpp: In function 'void r::routines::registerAll()':
/tmp/nix-build-RStudio-0.98.110.drv-0/rstudio-0.98.110/src/cpp/r/RRoutines.cpp:49:21: error: 'struct R_CMethodDef' has no member named 'styles'
       nullMethodDef.styles = NULL;
                     ^
make[2]: *** [src/cpp/r/CMakeFiles/rstudio-r.dir/build.make:207: src/cpp/r/CMakeFiles/rstudio-r.dir/RRoutines.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:364: src/cpp/r/CMakeFiles/rstudio-r.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
builder for ‘/nix/store/32azgxih4g3v6n0nhq454zfxk9xzzi1b-RStudio-0.98.110.drv’ failed with exit code 2
error: build of ‘/nix/store/32azgxih4g3v6n0nhq454zfxk9xzzi1b-RStudio-0.98.110.drv’ failed
```

## Technical details

* System: 17.09.git.f0fac3b (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.09.git.7f3b857d0d"

Note that the last time this build worked for me was at commit f0fac3b578086066b47360de17618448d066b30e (which was around April 15th).

**Comment by pbogdan** [comment]
`git bisect` points to d16c38a260ef41ae648f994918f491437fb7c75c as the change where the build starts failing. I would guess that RStudio 0.98.110 which seems quite old is in some way incompatible with the new R version.

**Comment by alecuba16** [comment]
Same problem here about rstudio-1.0.153:

`
/var/tmp/portage/sci-mathematics/rstudio-1.0.153/work/rstudio-1.0.153/src/cpp/r/RRoutines.cpp: In function ‘void rstudio::r::routines::registerAll()’:
/var/tmp/portage/sci-mathematics/rstudio-1.0.153/work/rstudio-1.0.153/src/cpp/r/RRoutines.cpp:62:21: error: ‘struct R_CMethodDef’ has no member named ‘styles’; did you mean ‘types’?
       nullMethodDef.styles = NULL;
                     ^~~~~~
`

**Comment by sungreen** [comment]
> /var/tmp/portage/sci-mathematics/rstudio-1.0.153/work/rstudio-1.0.153/src/cpp/r/RRoutines.cpp: In function ‘void rstudio::r::routines::registerAll()’: /var/tmp/portage/sci-mathematics/rstudio-1.0.153/work/rstudio-1.0.153/src/cpp/r/RRoutines.cpp:62:21: error: ‘struct R_CMethodDef’ has no member named ‘styles’; did you mean ‘types’? nullMethodDef.styles = NULL; ^~~~~~

I have the same problem rstudio-1.0.153 on gentoo
