### ISSUE TITLE
dmenu: Build fails on 17.09

### ISSUE THREAD

**Issue by fmthoma** [NixOS/nixpkgs#30924]
## Issue description

`dmenu` cannot be built on `nixos-17.09`, apparently because of compilation errors. I did a `git bisect` between the `nixos-17.03` and `nixos-17.09` and it shows that the update commit is at fault:

```
46de05a3dd6975e5db4cf06eca49e579557a03d6 is the first bad commit
commit 46de05a3dd6975e5db4cf06eca49e579557a03d6
Author: Pascal Wittmann <pascal.wittmann@red6-es.de>
Date:   Mon May 29 09:23:15 2017 +0200

    dmenu: 4.6 -> 4.7

:040000 040000 3cdc2ce7709d5d34b0cf9445d94ca77258c50274 b2815bc940a09d31e64340862bba145afa677720 M	pkgs
```

The full error message is below (build `dmenu` inside a local `nixpkgs` clone):

```
> nix-build -A dmenu
these derivations will be built:
  /nix/store/wf07mqkrja0s5ryl323r6xjmc1yimwf4-dmenu-4.7.drv
building path(s) ‘/nix/store/2zb836yvw7188j4wn81hmhnlx32w3ki3-dmenu-4.7’
unpacking sources
unpacking source archive /nix/store/an0ll0h565jn7vrl0vd09m0pn8722f8f-dmenu-4.7.tar.gz
source root is dmenu-4.7
setting SOURCE_DATE_EPOCH to timestamp 1493743007 of file dmenu-4.7/util.h
patching sources
configuring
'/nix/store/zajfnfzh6vd4y6l6raixr37lx2yzjif3-config.solarized-dark.h' -> 'config.h'
building
make flags: SHELL=/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash    
dmenu build options:
CFLAGS   = -std=c99 -pedantic -Wall -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -DVERSION="4.7" -DXINERAMA
LDFLAGS  = -s -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft
CC       = cc
CC dmenu.c
In file included from /nix/store/vrr9maj9lqj2xwndlx3kh07vhnc111i2-glibc-2.25-dev/include/string.h:634:0,
                 from dmenu.c:6:
dmenu.c: In function 'keypress':
dmenu.c:327:32: error: 'worddelimiters' undeclared (first use in this function)
    while (cursor > 0 && strchr(worddelimiters, text[nextrune(-1)]))
                                ^
dmenu.c:327:32: note: each undeclared identifier is reported only once for each function it appears in
dmenu.c: In function 'setup':
dmenu.c:555:43: error: 'colors' undeclared (first use in this function)
  scheme[SchemeNorm] = drw_scm_create(drw, colors[SchemeNorm], 2);
                                           ^
dmenu.c: In function 'main':
dmenu.c:674:4: error: 'colors' undeclared (first use in this function)
    colors[SchemeNorm][ColBg] = argv[++i];
    ^
In file included from dmenu.c:55:0:
dmenu.c: At top level:
config.h:11:20: warning: 'normbgcolor' defined but not used [-Wunused-variable]
 static const char *normbgcolor = "#002b36"; /* -nb option; normal background                 */
                    ^
config.h:12:20: warning: 'normfgcolor' defined but not used [-Wunused-variable]
 static const char *normfgcolor = "#839496"; /* -nf option; normal foreground                 */
                    ^
config.h:13:20: warning: 'selbgcolor' defined but not used [-Wunused-variable]
 static const char *selbgcolor  = "#073642"; /* -sb option; selected background               */
                    ^
config.h:14:20: warning: 'selfgcolor' defined but not used [-Wunused-variable]
 static const char *selfgcolor  = "#93a1a1"; /* -sf option; selected foreground               */
                    ^
config.h:15:20: warning: 'outbgcolor' defined but not used [-Wunused-variable]
 static const char *outbgcolor  = "#2aa198";
                    ^
config.h:16:20: warning: 'outfgcolor' defined but not used [-Wunused-variable]
 static const char *outfgcolor  = "#002b36";
                    ^
make: *** [Makefile:19: dmenu.o] Error 1
builder for ‘/nix/store/wf07mqkrja0s5ryl323r6xjmc1yimwf4-dmenu-4.7.drv’ failed with exit code 2
error: build of ‘/nix/store/wf07mqkrja0s5ryl323r6xjmc1yimwf4-dmenu-4.7.drv’ failed
```

### Steps to reproduce

`nix-env -i dmenu` on NixOS 17.09.

Alternatively: On a local clone of `nixpkgs`, check out `channels/nixos-17.09` and do `nix-build -A dmenu`.

## Technical details

* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: Starting with commit 46de05a3dd6975e5db4cf06eca49e579557a03d6
* Sandboxing enabled: `false`

**Comment by pbogdan** [comment]
Seems to build fine locally and on Hydra as well, perhaps your custom config needs to be updated for 4.7?

**Comment by fmthoma** [comment]
@pbogdan Ouch, you're right. I completely forgot that I have some overrides defined for `dmenu`. Feeling embarrassed... But thanks for pointing this out!

**Comment by fmthoma** [comment]
On a different notice: I would expect that `nix-build -A <package>` in a local nixpkgs clone would not apply my `packageOverrides`, but apparently it does?
