### PR TITLE
tini: fix build with musl libc 1.2.5

### PR DESCRIPTION
**Pull request by edef1c**
Adds upstream patch to fix build with musl libc 1.2.5, which removed `basename()` from `<string.h>`.
The patch includes `<libgen.h>` for the POSIX-compliant `basename()`.

Upstream commit: https://github.com/krallin/tini/commit/924c4bd6028457188942ecbfdc75e6a343fa9395

Fixes `pkgsStatic.tini` build failure:
```
error: implicit declaration of function 'basename' [-Wimplicit-function-declaration]
```

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

### CODE REVIEW

**Review by alyssais — APPROVED** [review]
Might be worth asking upstream for a release?  There hasn't been one in five years.
