### ISSUE TITLE
pjsip fails to compile with "undefined reference to `__dso_handle"

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#30317]
## Issue description

```
account.cpp:(.text+0x8c76): undefined reference to `__dso_handle'
/nix/store/z470j6lybdsy4ql972k392490bprhd2g-binutils-2.28.1/bin/ld: ../bin/pjsua2-test-x86_64-unknown-linux-gnu: hidden symbol `__dso_handle' isn't defined
/nix/store/z470j6lybdsy4ql972k392490bprhd2g-binutils-2.28.1/bin/ld: final link failed: Bad value
make[2]: *** [/tmp/nix-build-pjsip-2.6.drv-0/pjproject-2.6/build/rules.mak:125: ../bin/pjsua2-test-x86_64-unknown-linux-gnu] Error 1
make[2]: Leaving directory '/tmp/nix-build-pjsip-2.6.drv-0/pjproject-2.6/pjsip/build'
make[1]: *** [Makefile:280: pjsua2-test-x86_64-unknown-linux-gnu] Error 2
make[1]: Leaving directory '/tmp/nix-build-pjsip-2.6.drv-0/pjproject-2.6/pjsip/build'
make: *** [Makefile:14: all] Error 1
builder for ‘/nix/store/7xsljaz2vw5ygzf60ixkjhb0wh6hmhjr-pjsip-2.6.drv’ failed with exit code 2
e
```

Cc: @viric 

### Steps to reproduce

1. check out unstable
2. ```nix-build -A pjsip $(pwd)```

Fails with the same error for version 2.7 (not currently in nixpkgs).

## Technical details

* NixOS: 18.03.git.9205014c52M (Impala)
* Nix: nix-env (Nix) 1.11.15
* nixpkgs: 18.03pre-git
* Sandboxing enabled:  true

**Comment by peterhoeg** [comment]
Works with 2.8
