### PR TITLE
vscode-extensions.rust-lang.rust-analyzer: 0.3.1059 -> 0.3.1426

### PR DESCRIPTION
**Pull request by Garmelon**
###### Description of changes

Changelog: [Changelog #130](https://rust-analyzer.github.io/thisweek/2022/05/23/changelog-130.html) to [Changelog #168](https://rust-analyzer.github.io/thisweek/2023/02/13/changelog-168.html)

Supersedes #213850. Only after doing all the updating did I realize somebody else had already opened a PR, but the RA release cycle marches on relentlessly.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by cyplo — APPROVED** [review]

**Comment by superherointj** [comment]
Please fix the conflict:
pkgs/development/node-packages/node-packages.nix

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 216246` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vscode-extensions.matklad.rust-analyzer</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@Garmelon Please check for failure on build.

**Comment by superherointj** [comment]
> I noticed as well, sorry. Apparently, the new `node-packages.nix` is missing the `anser` package so I do need to do a full regeneration, which will take a few hours. I could bump `vscode-extensions.rust-lang.rust-analyzer` while I'm at it but it probably makes sense to open a new PR for that instead.

I agree ideally should be a discrete PR for node. When merged, rebase, and I can merge here, no problem.

**Comment by Garmelon** [comment]
So I should open a new PR just for node-packages? I think that would fail to pick up the new rust-analyzer dependency because `pkgs/applications/editors/vscode/extensions/rust-analyzer/build-deps/package.json` won't include the new dependency yet. On the other hand, I can't update the rust-analyzer plugin without updating `node-packages.nix` because then the build will fail due to a missing dependency.

As far as I understand, the `node-packages.nix` update needs to happen at the same time as the `rust-analyzer` vscode plugin update.

**Comment by superherointj** [comment]
> `node-packages.nix`

The node-packages.nix bump is global, right? Affecting all node/JS packages?
If it is, I think ideally it should be not part of this PR.
Then, once that lands, just rebase this PR, and it will build fine.

**Comment by Garmelon** [comment]
I think when updating `node-packages.nix`, `node2nix` uses the contents of `pkgs/applications/editors/vscode/extensions/rust-analyzer/build-deps/package.json` (among other files). This means that I can't update `node-packages.nix` *before* I update the `rust-analyzer` extension because its package.json won't include the `anser` dependency yet, so it won't be included in `node-packages.nix`.

I also can't update it *after* I update the extension because then the extension won't build until `node-packages.nix` is updated again.

This means that it has to be updated in the same PR as the extension because the extension dependencies changed (unless I'm missing something obvious).

**Comment by superherointj** [comment]
> I think when updating `node-packages.nix`, `node2nix` uses the contents of `pkgs/applications/editors/vscode/extensions/rust-analyzer/build-deps/package.json` (among other files). This means that I can't update `node-packages.nix` _before_ I update the `rust-analyzer` extension because its package.json won't include the `anser` dependency yet, so it won't be included in `node-packages.nix`.
> 
> I also can't update it _after_ I update the extension because then the extension won't build until `node-packages.nix` is updated again.
> 
> This means that it has to be updated in the same PR as the extension because the extension dependencies changed (unless I'm missing something obvious).

Right. It is local lock to this extension then. I was thinking it was a general bump of JS packages (global).

**Comment by superherointj** [comment]
> `node-packages.nix` is global, yes

If it is global, make it a discrete PR.

**Comment by Garmelon** [comment]
I can't

**Comment by Garmelon** [comment]
Looking the [history](https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/node-packages/node-packages.nix), `node-packages.nix` seems to commonly be updated along with other applications, usually in the same commit.

**Comment by superherointj** [comment]
> Though looking through those commits, sometimes packages are added manually to node-packages.json. Maybe that's what I should do in this case? 

That is how I would do it. A discrete PR for JS, one commit for adding package, one for bumping JS packages globally.

`node-packages`' `generate.sh` previously picked up on the new `rust-analyzer` dependency without me touching that file though.

I don't know what happened. Sorry.

**Comment by superherointj** [comment]
@Garmelon Coupling a global JS bump + package addition to a VSCode extension bump is not ideal. If you had already decoupled JS changes the JS part would have been accepted/merged already. Seems to me there are less people willing to review VSCode extensions than JS bumps. Also the VSCode reviewer wouldn't have to review the JS bumps. Win-win.

**Comment by Garmelon** [comment]
Okay, I will try to separate the JS change into a new PR. Do you think I should add all of rust-analyzer's new dependencies while I'm at it? Most of them are not part of `node-packages.json` yet. In any case, hopefully the people maintaining the node packages will shout at me if I do it wrong :D

This section on [Javascript packages inside nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#javascript-packages-inside-nixpkgs-javascript-packages-nixpkgs) seems to suggest I should.

> As a rule of thumb, the package set should only provide end user software packages, such as command-line utilities. Libraries should only be added to the package set if there is a non-NPM package that requires it.

Thanks for your time so far.

**Comment by superherointj** [comment]
Maybe `node2nix` could be used to make dependencies local to this package? So you don't have to bother about changing global packages?

**Comment by Garmelon** [comment]
So far, I've been using the extension's `update.sh` script, which always updates `node-packages.nix` (either via `sed` directly or via `node2nix` if the dependencies changed). Maybe that script should be adjusted as well if the workflow of packaging the extension should change, but I don't know enough to do that.

The more I look into this, the less I understand it. I don't know whether the update script does the right thing or is horribly outdated.

**Comment by superherointj** [comment]
Asked on Matrix:
image

**Comment by Garmelon** [comment]
> Maybe node2nix could be used to make dependencies local to this package?

The extension seems to have originally been packaged that way, then moved to the global `node-packages.nix` in https://github.com/NixOS/nixpkgs/commit/8318c36a4b1d40be930092787a8bb64e255f8620

**Comment by superherointj** [comment]
Let's do a global update then.

**Comment by Garmelon** [comment]
In that case, the question remains whether I should bump this PR to the latest extension version as well

**Comment by Garmelon** [comment]
I don't know enough about the hacks and other things this derivation is doing to make that switch. For example, the `update.sh` script combines `dependencies` and `devDependencies` for some reason. Even if I did, it would probably be worth a separate PR.

I'll push a normal update in a few hours once the update script finishes.

**Comment by superherointj** [comment]
> in a few hours once the update script finishes.

That doesn't sound right... Bumping this extension should lead to that...
I think we should just ignore update script and package this extension properly using `buildNpmPackage`.

**Comment by Garmelon** [comment]
Updating `node-packages.nix` takes a long time

**Comment by superherointj** [comment]
> pkgs/development/node-packages/node-packages.nix

Needs to be a discrete commit.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 216246` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bibtex-tidy</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>emanote</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>gtop</li>
    <li>joplin</li>
    <li>lighthouse</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>node2nix</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>slack</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>thelounge</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wrangler</li>
    <li>yaml-language-server</li>
    <li>zx</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 216246` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bibtex-tidy</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>emanote</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>gtop</li>
    <li>joplin</li>
    <li>lighthouse</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>node2nix</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>slack</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>thelounge</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wrangler</li>
    <li>yaml-language-server</li>
    <li>zx</li>
  </ul>
</details>

**Comment by Garmelon** [comment]
During building of `openmoji`, I get the error
```
/build/source/helpers/generate-font-glyphs.js:13
const svgFiles = glob('./color/svg/*.svg');
                 ^
TypeError: glob is not a function
```
This seems to be the same error as with https://github.com/NixOS/nixpkgs/issues/219202 which was caused by https://github.com/NixOS/nixpkgs/pull/218736, so at least this PR didn't break anything that wasn't already broken.

**Review by superherointj — APPROVED** [review]
