### ISSUE TITLE
sysdig fails to build on NixOS 17.03

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#28191]
## Issue description
A recent update broke building sysdig on release-17.03 branch.

### Steps to reproduce
```
$ nix-build -A linuxPackages.sysdig
...
[ 58%] Building CXX object userspace/libsinsp/CMakeFiles/sinsp.dir/marathon_component.cpp.o
[ 59%] Building CXX object userspace/libsinsp/CMakeFiles/sinsp.dir/marathon_http.cpp.o
/tmp/nix-build-sysdig-0.15.0.drv-0/sysdig-0.15.0/userspace/libsinsp/marathon_http.cpp:10:28: fatal error: curl/curlbuild.h: No such file or directory
compilation terminated.
make[2]: *** [userspace/libsinsp/CMakeFiles/sinsp.dir/build.make:1047: userspace/libsinsp/CMakeFiles/sinsp.dir/marathon_http.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:517: userspace/libsinsp/CMakeFiles/sinsp.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
builder for ‘/nix/store/4ws62lyvffyqam1d6srbcg39d7fn3rbi-sysdig-0.15.0.drv’ failed with exit code 2
error: build of ‘/nix/store/4ws62lyvffyqam1d6srbcg39d7fn3rbi-sysdig-0.15.0.drv’ failed
```

## Technical details
* Nixpkgs version: 36b4c4ed44333d561ad59c7c0b474439b0443dae

**Comment by Mic92** [comment]
Does newer versions of sysdig solve the problem?

**Comment by Mic92** [comment]
https://github.com/draios/sysdig/issues/895

**Comment by globin** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/ec8d5081dd9be39b9468d5c873755ce438ed7a66

**Comment by bjornfor** [comment]
Thanks!
