### PR TITLE
coqPackages.QuickChick: Fix QuickChick command in Coq

### PR DESCRIPTION
**Pull request by Chobbes**
###### Description of changes

I've noticed that the QuickChick command does not work in Coq because it can't find the ocaml libraries installed with Coq. This adds a patch so that when `ocamlbuild` is called in the `QuickChick` command it uses `ocamlfind`. I'm not 100% sure if this is the right way to make `ocamlbuild` find the libraries in nix... but it does work, and QuickChick now works, which is great :).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ x ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
Can you please elaborate on the thing that you are fixing (e.g., provide a way to reproduce the failure) and move the addition of version 1.5.1 to a separate commit? Thanks.

Also, as you’re patching source code, did you consider reporting the issue upstream?

**Comment by Chobbes** [comment]
Here's a repository that reproduces the issue:

https://github.com/Chobbes/nix-quickchick-test

The `Test.v` file contains a trivial QuickChick test:

```
Require Import QuickChick.QuickChick.

QuickChick true.
```

When you do `nix develop ".#brokenQC" -i` and run `make clean && make` you get the following error:

```
bash-5.1$ make clean && make 
rm -f Test.vo
rm -f Test.vok
rm -f Test.vos
rm -f Test.glob
coqc Test.v
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
QuickChecking true
/bin/sh: line 1: tput: command not found
+ /bin/ocamlopt.opt unix.cmxa QuickChick7e0c86.cmx -o QuickChick7e0c86.native
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlopen':
(.text.caml_dlopen+0x14): undefined reference to `dlopen'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlclose':
(.text.caml_dlclose+0x6): undefined reference to `dlclose'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlsym':
(.text.caml_dlsym+0x6): undefined reference to `dlsym'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_globalsym':
(.text.caml_globalsym+0xb): undefined reference to `dlsym'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlerror':
(.text.caml_dlerror+0x6): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
Command exited with code 2.
Compilation unsuccessful after building 5 targets (0 cached) in 00:00:00.
File "./Test.v", line 3, characters 0-16:
Error: Could not compile test program


make: *** [Makefile:4: Test.vo] Error 1
```

QuickChick works by extracting the Coq program to ocaml within a test harness, and then using `ocamlbuild` to create an executable to run the test cases. Without the `-use-ocamlfind` flag `ocamlbuild` is unable to find libraries in the nix store, and as a result cannot build the test program, so the `QuickChick` command in `Test.v` fails.

You want to be able to use `QuickChick` in your development environment to write and execute tests, so it's unfortunate that this functionality is broken in the dev shell in nix :(. This also means that you cannot run QuickChick tests within Proof General (or CoqIDE or whatever).

Alternatively, if you run `nix develop ".#fixedQC" -i`, which uses a patched version of QC the command succeeds and the tests pass:

```
bash-5.1$ make clean && make
rm -f Test.vo
rm -f Test.vok
rm -f Test.vos
rm -f Test.glob
coqc Test.v
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
QuickChecking true
/bin/sh: line 1: tput: command not found
Finished, 5 targets (0 cached) in 00:00:00.
+++ Passed 10000 tests (0 discards)
```

(Don't worry about the silly `tput` error, it's just for prettier printing I believe)

This is why I believe this should be patched --- QuickChick is not usable for development without this.

However, I have just noticed that `nix build ".#brokenQC"` seems to work. I do not have any idea why that would build just fine when it doesn't work with `nix develop`... Any ideas?

**Comment by Chobbes** [comment]
Version bump separated out here: https://github.com/NixOS/nixpkgs/pull/165952

**Comment by vbgl** [comment]
Thanks for the details. Do you have `ocamlbuild` in your path?

**Comment by vbgl** [comment]
This used to work (and I fear your fix won’t help). `git bisect` leads to 7e20e9039e7f2c41d478441d0ef453a34c1ec57a. Ping @ulrikstrid.

File: pkgs/development/coq-modules/QuickChick/default.nix [hunk 1]
```diff
@@ -30,8 +33,42 @@ mkCoqDerivation {
...
+        "substituteInPlace ${ocamlBuildFile.file} --replace \"${oldBuildLine}\" \"${newBuildLine}\"";
+
+      patchNative =
+        lib.optionalString recent
+          "substituteInPlace Makefile --replace quickChickTool.byte quickChickTool.native";
+    in
+      lib.concatStringsSep "\n" [ patchNative patchOcamlBuild ];
 
   mlPlugin = true;
   extraNativeBuildInputs = lib.optional recent coq.ocamlPackages.ocamlbuild;
```
Comment (ulrikstrid) [inline pkgs/development/coq-modules/QuickChick/default.nix:74]: A simpler fix is to change this line to:
`extraNativeBuildInputs = lib.optionals recent [ coq.ocaml coq.ocamlPackages.ocamlbuild ];`

Comment (ulrikstrid) [reply pkgs/development/coq-modules/QuickChick/default.nix:74]: This seems to work in the test repo you linked, I can push a PR to your repo.

Comment (ulrikstrid) [reply pkgs/development/coq-modules/QuickChick/default.nix:74]: Thanks for finding this and pinging me @vbgl :pray: I saw this on some OCaml package as well and think I got it fixed

**Comment by Chobbes** [comment]
> Thanks for the details. Do you have `ocamlbuild` in your path?

Yep! It's also definitely being found in the path, otherwise the call to `ocamlopt.opt` wouldn't happen.

> This used to work (and I fear your fix won’t help). `git bisect` leads to [7e20e90](https://github.com/NixOS/nixpkgs/commit/7e20e9039e7f2c41d478441d0ef453a34c1ec57a). Ping @ulrikstrid.

I have tested my fix and it has solved the problem for me. I do not know much about ocamlbuild / how ocaml interacts with nix, though, so I'm open to better solutions. It seems like @ulrikstrid might have some ideas, unfortunately I am still running into problems with their fix here: https://github.com/Chobbes/nix-quickchick-test/pull/1

The QC devs are open to adding the `-use-ocamlfind` in future versions of QuickChick, for what it's worth, and then we would only have to worry about patching newer versions (giving us a fixed set of old releases that need patching).

Of course if it's just a matter of adding some build inputs to QC instead, that would be great.

**Comment by ulrikstrid** [comment]
I'm actually a bit confused why this happens here since we don't have `strictDeps = true` (at least I can't see it) so it should still be able to see ocaml. But adding ocaml to `propagatedBuildInputs` seems to work (might work with `buildInputs` as well but I would guess it won't arrive it needs it at runtime).

**Comment by vbgl** [comment]
> Yep! It's also definitely being found in the path, otherwise the call to `ocamlopt.opt` wouldn't happen.

So try removing `ocamlbuild` from your path and you’ll see that your patch does not change anything to the failure.

**Comment by Chobbes** [comment]
> > Yep! It's also definitely being found in the path, otherwise the call to `ocamlopt.opt` wouldn't happen.
> 
> So try removing `ocamlbuild` from your path and you’ll see that your patch does not change anything to the failure.

Could you explain why you are saying this? I don't understand why you would want to do this? I have removed `ocamlbuild` from my path, and as expected QuickChick fails to build the test program because it cannot find `ocamlbuild`, not because of linker issues.

Could you elaborate on why you think my patch should do nothing? I am able to reproduce the issues I'm having on my machine, and the issues are resolved with my patch. I would like to understand what you think the problem is, and what you think the solution should be.

```
$ make clean && make                                                                                                                                                                   
rm -f Test.vo
rm -f Test.vok
rm -f Test.vos
rm -f Test.glob
coqc Test.v
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
Warning: Cannot determine user home directory, using '.' .
QuickChecking true
sh: line 1: ocamlbuild: command not found
File "./Test.v", line 3, characters 0-16:
Error: Could not compile test program


make: *** [Makefile:4: Test.vo] Error 1
```

**Comment by ulrikstrid** [comment]
@Chobbes  To keep the discussion in one place I'll anwer https://github.com/Chobbes/nix-quickchick-test/pull/1#issuecomment-1080664199 here.

The commit that @vbgl found above that apparently broke this package moves executables (like OCaml, ocamlbuild etc) to `nativeBuildInputs`, these are inputs that are supposed to be run on the machine that builds the derivation and should be the same arch. In this case `QuickChick` uses OCaml at *runtime* which means it should also be in either `buildInputs` but more likely in `propagatedBuildInputs` since we need it on the machine that will run the program. Another solution might be to add `[ ocaml ]` in the consuming program/library but that is probably not better.

The reason I did the change to begin with is for cross-compilation to work better, it also allows us to add `strictDeps = true;` in the future which should make this distinction clearer by actually enforcing this.

**Comment by ulrikstrid** [comment]
Another point here is that if you add `strictDeps = true;` I think your fix would fail and this is probably what @vbgl is getting at.

**Comment by Chobbes** [comment]
Gotcha, thanks for the explanations, that makes sense.

One concern that I have is that some projects may need `ocamlbuild` as well as `QuickChick` (this is the case for Vellvm currently, though it currently uses a special version of QC). So ideally, whatever fix gets implemented should allow a project depending on `QuickChick` to also use `ocamlbuild` to build extracted Coq code. I guess this means the `ocamlbuild` that QC uses and the project uses should be the same and be able to find extra ocaml libraries that the project relies upon too? In normal `opam` land QC and the project would use the same `ocamlbuild`, anyway.

It looks like `nixpkgs/master` has some changes in `QuickChick` relative to `21.11` that remove `ocamlbuild` from the propagated build inputs, so that might also be relevant to what we're trying to fix?

Also, I believe newer versions of QuickChick remove the `perl` dependency: https://github.com/QuickChick/QuickChick/commit/7433779e7c79c94aa46c9b8f0dbdd4348abc69ad

**Comment by ulrikstrid** [comment]
> It looks like nixpkgs/master has some changes in QuickChick relative to 21.11 that remove ocamlbuild from the propagated build inputs, so that might also be relevant to what we're trying to fix?

This is the change I described above. I think adding ocaml and ocamlbuild back to propagateBuildInputs in this particular case is the correct choice.

**Comment by Chobbes** [comment]
I see. So the problem I'm having seems to be a different problem from the `propagatedBuildInputs` issue. I'm working with 21.11, and I still have issues with linking (not with finding ocamlbuild):

```
+ /bin/ocamlopt.opt unix.cmxa QuickChick7e0c86.cmx -o QuickChick7e0c86.native
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlopen':
(.text.caml_dlopen+0x14): undefined reference to `dlopen'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlclose':
(.text.caml_dlclose+0x6): undefined reference to `dlclose'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlsym':
(.text.caml_dlsym+0x6): undefined reference to `dlsym'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_globalsym':
(.text.caml_globalsym+0xb): undefined reference to `dlsym'
/nix/store/wa59khxfvx6nf1wgdr5bjyyf9rdk23jc-binutils-2.35.2/bin/ld: /usr/lib/ocaml/libasmrun.a(unix.n.o): in function `caml_dlerror':
(.text.caml_dlerror+0x6): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
```

It looks like `ocamlbuild` is ultimately calling `ld` which is trying to find libraries in `/usr/lib/ocaml` (which does exist on my system), and maybe there's a mismatch there? So, this seems like an issue of `ocamlbuild` not being wrapped or sandboxed enough (as vgbl mentioned?), and maybe that's why it's working on NixOS, but not nix running on a normal linux system that also has `ocaml` installed?

**Comment by Chobbes** [comment]
Yeah, okay. There are actually 2 issues here :).

1. nixpkgs/master doesn't propagate `ocamlbuild`, so when you run QuickChick it explodes.
2. `ocamlbuild` may look for libraries outside of `nix`, which can be a problem if you are on a regular Linux (or presumably Mac) system with `ocaml` installed.

The issue that I have been trying to fix is actually 2, and 1 was not a problem for me because I was working with 21.11.

Issue 2 is actually caused by `ocamlbuild`. When the `-use-ocamlfind` option is used it calls `ocamlopt` with `ocamlfind ocamlopt`, making things stay in `nix` land. Without this option it uses the `-install-bin-dir` option to determine the path of the `ocaml` binaries... And somehow it's deciding to use `/bin`, which escapes nix:

https://github.com/ocaml/ocamlbuild/blob/master/src/options.ml#L259

This option is used in `find_tool` here: https://github.com/ocaml/ocamlbuild/blob/master/src/options.ml#L49

I believe `Ocamlbuild_where.bindir` defaults to `/bin`, even in `nix`, which is why I'm getting issues with my normal system's installation --- it can actually find the binaries in `/bin`, so `ocamlbuild` uses them instead of the ocaml binaries in the nix store and this causes linking issues.

`Ocamlbuild_where.bindir` is determined by:

https://github.com/ocaml/ocamlbuild/blob/master/configure.make#L92

I believe this might actually an issue with nix's `ocamlbuild` package now. It should make sure `OCAMLBUILD_BINDIR`, `OCAMLBUILD_LIBDIR` and `OCAMLBUILD_MANDIR` are all set appropriately when being built... It *seems* like it should do this:

https://github.com/NixOS/nixpkgs/blob/21.11/pkgs/development/tools/ocaml/ocamlbuild/default.nix#L26

But maybe there's an issue there, or maybe `/bin` is getting picked up somewhere else.

P.S. I've asked around and it seems like `nix build` uses linux namespaces to sandbox things, and `nix develop` doesn't. This must be why `nix build ".#brokenQC"` was working for me earlier --- the sandbox presumably hides my

**Comment by vbgl** [comment]
Is this still relevant? I think it has been solved there: #169850 & #171006.

**Comment by Chobbes** [comment]
> Is this still relevant? I think it has been solved there: #169850 & #171006.

This has not been resolved. In my previous post issue 2 (the one that this PR is actually about) has not been fixed.

**Comment by siraben** [comment]
What's the status of this?
