### ISSUE TITLE
python pysdl3: import attempts to write to nix store and the import is very slow

### ISSUE THREAD

**Issue by cromachina** [NixOS/nixpkgs#527580]
### Nixpkgs version

- Unstable (26.11)

### Describe the bug

`pysdl3` attempts to generate docs in the read-only nix store when imported and fails. This emits an error when loading and, although this doesn't stop execution, it seems to account for a significantly longer load time than using `pysdl3` from a `venv`, or the previous version in nixpkgs.

This seems to affect `pysdl3 0.9.11b1` specifically. It does not seem to happen as bad with `0.9.11b0`

### Steps to reproduce

If you are updated to 0.9.11b1, you could run the following:
```
nix-shell -p python313 python313Packages.pysdl3
python -m timeit -n 1 -r 1 'import sdl3'
```
Output:
This delay may have been caused by the doc generation and version checks, which should have been disabled.
```
Error: Failed to write docs: [Errno 30] Read-only file system: '/nix/store/pcyqqcqwj8j7q0jxjra9wy52fjx34rxf-python3.13-pysdl3-0.9.11b1/lib/python3.13/site-packages/sdl3/__doc__.py'.
1 loop, best of 1: 2.99 sec per loop
```
---
### Compared to 0.9.11b0:
```
nix-shell -p python313 python313Packages.pysdl3
python -m timeit -n 1 -r 1 'import sdl3'
```
Output:
This delay may have been caused by the version check, which should have been disabled.
```
Warning: You are using an older version of PySDL3 (current: 0.9.11b0, latest: 0.9.11b1).
1 loop, best of 1: 1.11 sec per loop
```
---
### Compared to 0.9.11b1 in a venv:
Using a nix shell file:
```nix
# shell.nix
{ pkgs ? import <nixpkgs> { } }:
(pkgs.buildFHSEnv {
  name = "python-env";
  targetPkgs = pkgs: (with pkgs; [
    python313
    freetype
  ]);
  runScript = pkgs.writeScript "init.sh" ''
    python -m venv venv
    source venv/bin/activate
    pip install pysdl3
    exec bash
  '';
}).env
```

```
nix-shell
python -m timeit -n 1 -r 1 'import sdl3'
```
Output:
```
1 loop, best of 1: 408 msec per loop
```

### Expected behaviour

Import shouldn't emit any error or warning, and it shouldn't cause a significant delay to finish importing.

### Relevant log output

```console

```

### System metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 7.0.3-zen1, NixOS, 26.05 (Yarara), 26.05.20260505.549bd84`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.7`
 - channels(root): `""`
 - nixpkgs: `/nix/store/h9wn92hv33sizprch7fcp16lfs1k3w5j-source`
```

### Notify maintainers

@jansol

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jansol** [comment]
Uuugh not this bs again. Possibly caused by https://github.com/NixOS/nixpkgs/pull/518496 not updating the doc file hashes?

**Comment by cromachina** [comment]
Wouldn't that cause a build failure? However, when inspecting doc info with an LSP like in vscode, the doc information does seem to be there, I think:

<img width="371" height="236" alt="Image" src="https://github.com/user-attachments/assets/894342aa-5a7d-4fcd-bd18-a915b1086285" />

**Comment by cromachina** [comment]
When I inspect the nix store location, the `__doc__.py` file is indeed already there.
It's possible that `__init__.py` is somehow not locating `__doc_file__` even though it's there, however the `__doc_generator__` flag should have already short circuited that. Environment issue, maybe?

Attempting to set the environment variable in code silences the write error, however it breaks the import in other ways (the import is still very slow for some reason):
```py
import os
os.environ['SDL_DOC_GENERATOR'] = '0'
import sdl3
```
The import appears to be incomplete and symbols that were there are now are missing:
```
    def render_texture(self, texture:sdl3.LP_SDL_Texture, srcrect=None, dstrect=None):
                                     ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sdl3' has no attribute 'LP_SDL_Texture'
```

**Comment by cromachina** [comment]
The auto-updating by default behavior of pysdl3 is not a nice feature, honestly 😔
I think the pysdl3 maintainer should just freeze versions and package the platform specific SDL shared objects right in the git repo, by default, then nobody has to worry about ABI mismatch, doc fetching, etc. And then all we have to do on nix is `autopatchelf` it (or make sure to override with correct the nixpkgs SDL shared object, which actually seems more finicky if the ABI slightly changes in any way).

**Comment by jansol** [comment]
@alfarelcynthesis Have you noticed this in your experiments?

**Comment by alfarelcynthesis** [comment]
> Wouldn't that cause a build failure? However, when inspecting doc info with an LSP like in vscode, the doc information does seem to be there, I think:
> <img alt="Image" width="371" height="236" src="https://private-user-images.githubusercontent.com/82557197/602321825-894342aa-5a7d-4fcd-bd18-a915b1086285.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODEwMjQ4OTAsIm5iZiI6MTc4MTAyNDU5MCwicGF0aCI6Ii84MjU1NzE5Ny82MDIzMjE4MjUtODk0MzQyYWEtNWE3ZC00ZmNkLWJkMTgtYTkxNWIxMDg2Mjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjA5VDE3MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MjVlNmJkZjg3NDQzNDNjYTBkYTgxOGViMjZiMmU0N2IyOTdhYmEwNmE4NTdkNjVhNDM1MzFiZGVhOTFiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.yKG1MuzeNoISmIzuvxQc6WbJ-DzmHHRtsElW1ro0gK0">

It wouldn't cause a build failure, it would just leave the old out-of-date docs in the build, unfortunately, which will still be mostly correct when an LS is looking at them.
Honestly not sure if the version mismatch would cause pysdl3 to try and download the newer up-to-date version, but that's one possible explanation.

> When I inspect the nix store location, the `__doc__.py` file is indeed already there. It's possible that `__init__.py` is somehow not locating `__doc_file__` even though it's there, however the `__doc_generator__` flag should have already short circuited that. Environment issue, maybe?
> 
> Attempting to set the environment variable in code silences the write error, however it breaks the import in other ways (the import is still very slow for some reason):
> 
> import os
> os.environ['SDL_DOC_GENERATOR'] = '0'
> import sdl3
> 
> The import appears to be incomplete and symbols that were there are now are missing:
> 
> ```
>     def render_texture(self, texture:sdl3.LP_SDL_Texture, srcrect=None, dstrect=None):
>                                      ^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'sdl3' has no attribute 'LP_SDL_Texture'
> ```

I would assume that this error is because the `doc.py` version is mismatched with the pysdl3 version, and the signature has changed in some way.
It's skipping the slow failing download of the new docs, but the stale docs are still wrong.

If I'm wrong about this and having the correct doc version in the build still has import delays then this'll need more investigation, but hopefully #516273 will fix this once I get around to writing the custom updater as sandro suggested.

**Comment by alfarelcynthesis** [comment]
I'll quickly PR the updated docs, that should ideally bandaid fix this current instance of this problem.
