### ISSUE TITLE
linuxPackages-libre fails on nixos-20.03

### ISSUE THREAD

**Issue by Uthar** [NixOS/nixpkgs#98764]
**Description**
Setting `boot.kernelPackages = pkgs.linuxPackages-libre` in configuration.nix makes `nixos-rebuild` fail on nixos 20.03.

**To Reproduce**
1. Set `boot.kernelPackages = pkgs.linuxPackages-libre` in configuration.nix
2. Run `nixos-rebuild build`

**Expected behavior**
Package builds without errors.

**Additional context**
Build errors:
```
../drivers/bluetooth/btmrvl_sdio.c:331:20: warning: missing terminating " character
  331 |  .firmware       = "mrvl/sdsd8977_combo_v2/*(DEBLOBBED)*/,
      |                    ^
../drivers/bluetooth/btmrvl_sdio.c:331:20: error: missing terminating " character
  331 |  .firmware       = "mrvl/sdsd8977_combo_v2/*(DEBLOBBED)*/,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/bluetooth/btmrvl_sdio.c:332:2: error: expected expression before '.' token
  332 |  .reg            = &btmrvl_reg_8977,
      |  ^
../drivers/bluetooth/btmrvl_sdio.c:349:20: warning: missing terminating " character
  349 |  .firmware       = "mrvl/sdsd8997_combo_v4/*(DEBLOBBED)*/,
      |                    ^
../drivers/bluetooth/btmrvl_sdio.c:349:20: error: missing terminating " character
  349 |  .firmware       = "mrvl/sdsd8997_combo_v4/*(DEBLOBBED)*/,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/bluetooth/btmrvl_sdio.c:350:2: error: expected expression before '.' token
  350 |  .reg            = &btmrvl_reg_8997,
      |  ^
```

Link to Hydra build: https://hydra.nixos.org/build/127861800/nixlog/1

**Notify maintainers**
@alyssais 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67-gnu, NixOS, 20.03.3021.5659cb448e9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(kpg): `"nixos-20.09-20.09alpha417.a780c60f9f7, nixpkgs-21.03pre243895.72b9660dc18"`
 - channels(root): `"nixos-20.03.3021.5659cb448e9"`
 - nixpkgs: `/home/kpg/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: linuxPackages-libre
# a list of nixos modules affected by the problem
module:
```

**Comment by Uthar** [comment]
The below override worked for me, producing these paths:
```
kernel -> /nix/store/74mkz0nmkh0jvx3yj55qrc94prlhl2bl-linux-5.4.67/bzImage
kernel-modules -> /nix/store/xag7yhlfb4ckwkgvzjsrdbv940kc9h6w-kernel-modules
```

```nix
{

boot.kernelPackages = with pkgs;
  (recurseIntoAttrs (linuxPackagesFor linux-libre.override {
    scripts = fetchsvn {
      url = "https://www.fsfla.org/svn/fsfla/software/linux-libre/releases/branches/";
      rev = "17624";
      sha256 = "0gs3mpiffny408l9kdrxpj48axarfb2fxvcw4w8zsz5wr7yig0n2";
    };
  }));

}
```

**Comment by davidak** [comment]
rebuild works on 20.09.2624.1eff582e7ea, but it does not boot (https://github.com/NixOS/nixpkgs/issues/109577)

i close this since 20.03 is not supported anymore
