### ISSUE TITLE
R package r-rgdal fails to install

### ISSUE THREAD

**Issue by idontgetoutmuch** [NixOS/nixpkgs#42911]
## Issue description

With a `shell.nix` thus

```
{ pkgs ? import <nixpkgs> {}, compiler ? "ghc822", doBenchmark ? false }:

let

f = { mkDerivation, haskell, base, foldl, Frames, fuzzyset
    , inline-r, integration, lens
    , pandoc-types, plots
    , diagrams-rasterific
    , diagrams
    , diagrams-svg
    , diagrams-contrib
    , R, random, stdenv
    , template-haskell, temporary }:
mkDerivation {
  pname = "mrp";
  version = "1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base
    diagrams
    diagrams-rasterific
    diagrams-svg
    diagrams-contrib
    (haskell.lib.dontCheck inline-r)
    foldl
    Frames
    fuzzyset
    integration
    lens
    pandoc-types
    plots
    random
    template-haskell
    temporary
  ];
  executableSystemDepends = [
    R
    pkgs.rPackages.dplyr
    pkgs.rPackages.ggmap
    pkgs.rPackages.ggplot2
    pkgs.rPackages.knitr
    pkgs.rPackages.maptools
    pkgs.rPackages.reshape2
    pkgs.rPackages.rgeos
    pkgs.rPackages.rgdal
    pkgs.rPackages.rstan
    pkgs.rPackages.zoo];
  license = stdenv.lib.licenses.bsd3;
};

haskellPackages = if compiler == "default"
  then pkgs.haskellPackages
  else pkgs.haskell.packages.${compiler};

# Fixup a few things
myHaskellPackages = haskellPackages.override {
  overrides = self: super: with pkgs.haskell.lib; {
    diagrams-rasterific = doJailbreak super.diagrams-rasterific;
    diagrams-svg = doJailbreak super.diagrams-svg;
    diagrams-contrib = doJailbreak super.diagrams-contrib;
    diagrams = doJailbreak super.diagrams;
    inline-r = dontCheck super.inline-r;
    pipes-group = doJailbreak super.pipes-group;
  };
};

variant = if doBenchmark then pkgs.haskell.lib.doBenchmark else pkgs.lib.id;

drv = variant (myHaskellPackages.callPackage f {});

in

  if pkgs.lib.inNixShell then drv.env else drv
```

and

```
nix-shell shell.nix -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable-small.tar.gz
```

I get

```
installing to /nix/store/zf472qbczmlv1hdr29gdrki2dqng06vi-r-maptools-0.9-2/library/maptools/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
no
checking gdal: linking with --libs and --dep-libs... ignoring (possibly broken) abi-depends field for packages
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
no
In file included from gdal_test.cc:1:
In file included from /nix/store/ywcqrkv8gcb1lw4gx4r9hx8vryhl33x3-gdal-2.3.0/include/gdal.h:45:
/nix/store/ywcqrkv8gcb1lw4gx4r9hx8vryhl33x3-gdal-2.3.0/include/cpl_port.h:187:6: error: Must have C++11 or newer.
#    error Must have C++11 or newer.
     ^
1 error generated.
In file included from gdal_test.cc:1:
In file included from /nix/store/ywcqrkv8gcb1lw4gx4r9hx8vryhl33x3-gdal-2.3.0/include/gdal.h:45:
/nix/store/ywcqrkv8gcb1lw4gx4r9hx8vryhl33x3-gdal-2.3.0/include/cpl_port.h:187:6: error: Must have C++11 or newer.
#    error Must have C++11 or newer.
     ^
1 error generated.
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package 'rgdal'
* removing '/nix/store/l4sni0hs997an8ck7yj5s9inba4g04a8-r-rgdal-1.2-18/library/rgdal'
builder for ‘/nix/store/yfxhh45wj4m628axw5c6vj19d5ahhkz8-r-rgdal-1.2-18.drv’ failed with exit code 1
error: build of ‘/nix/store/yfxhh45wj4m628axw5c6vj19d5ahhkz8-r-rgdal-1.2-18.drv’ failed
/nix/var/nix/profiles/default/bin/nix-shell: failed to build all dependencies
bash-3.2$ nix-shell fromZim.nix -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable-small.tar.gz
```

### Steps to reproduce

See above

## Technical details

```
bash-3.2$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.3.0, macOS 10.13.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixpkgs-18.03pre122117.14df60d0db9"`
 - channels(dom): `"nixpkgs-18.09pre142380.23f2dfd9f5a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by bcdarwin** [comment]
Builds on unstable/master/release-20.09.
