### ISSUE TITLE
broadcom_sta fails to build on kernel 6.0.0

### ISSUE THREAD

**Issue by oluceps** [NixOS/nixpkgs#194903]
### Steps To Reproduce
```
boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
```
```
kernelPackages = pkgs.linuxPackages_latest;
```

### Build log
```
[...]
error: builder for '/nix/store/703dpjfimaxcn9kkqj1kc9y44bqxvpha-broadcom-sta-6.30.223.271-6.0.drv' failed with exit code 2;
       last 10 log lines:
       >   CC [M]  /build/broadcom-sta/src/wl/sys/wl_iw.o
       >   CC [M]  /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o
       > /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c: In function 'wl_bss_roaming_done':
       > /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:2359:18: error: 'struct cfg80211_roam_info' has no member named 'bss'
       >  2359 |         roam_info.bss = bss;
       >       |                  ^
       > make[2]: *** [/nix/store/kc88pxfi83v5j71i22m86kqf8bp0s0x6-linux-6.0-dev/lib/modules/6.0.0/source/scripts/Makefile.build:249: /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o] Error 1
       > make[1]: *** [/nix/store/kc88pxfi83v5j71i22m86kqf8bp0s0x6-linux-6.0-dev/lib/modules/6.0.0/source/Makefile:1852: /build/broadcom-sta] Error 2
       > make[1]: Leaving directory '/nix/store/kc88pxfi83v5j71i22m86kqf8bp0s0x6-linux-6.0-dev/lib/modules/6.0.0/build'
       > make: *** [Makefile:161: all] Error 2
       For full logs, run 'nix log /nix/store/703dpjfimaxcn9kkqj1kc9y44bqxvpha-broadcom-sta-6.30.223.271-6.0.drv'.
error: 1 dependencies of derivation '/nix/store/z92ic6dzfcd8kjr995p1sipv56bfqr50-kernel-modules.drv' failed to build
```

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: "x86_64-linux"
 - host os: Linux 5.19.5, NixOS, 22.11 (Raccoon), 22.11.20220901.2da64a8
 - multi-user?: yes
 - sandbox: yes
 - version: nix-env (Nix) 2.11.0
 - nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```
