### PR TITLE
powertop: pull upstream fix for ncurses-6.3

### PR DESCRIPTION
**Pull request by trofi**
Without the fix build on ncurses-6.3 fails as:

    lib.cpp:586:24: error: format not a string literal and no format arguments [Werror=format-security]
      586 |         mvprintw(1, 0, notify);
          |                        ^~~~~~

### CODE REVIEW

**Comment by dtzWill** [comment]
LGTM, patch just adds `"%s",` in a few places, presumably in response to ncurses adding appropriate bits to their headers so that compilers warn on these like other format string operations.

Anyway it's an upstream patch, straightforward, change here looks done per our ways :).

---

(please let's not hold this back for this, but for lack of better place to put it: looking through their commit history, maybe we want to grab https://github.com/fenrus75/powertop/commit/33a23e7517c1b2e4e6729feb9bf90fd937d797ce as well until next release? Fixes a buffer overrun on long cmdline's which nix-land makes worse but likely aren't hitting 4096 very often...shrug)
