### PR TITLE
[20.03] pythonPackages.stem: unmarked as broken

### PR DESCRIPTION
**Pull request by paumr**
The package was marked broken but seems to work on 20.03

### CODE REVIEW

**Review by cole-h — CHANGES_REQUESTED** [review]
~~Already asked in IRC to amend the commit, but one more thing while you're touching this file:~~ Ignore me (:

File: pkgs/development/python-modules/stem/default.nix [hunk 1]
```diff
@@ -26,6 +26,5 @@ buildPythonPackage rec {
     homepage = https://stem.torproject.org/;
```
Comment (cole-h) [inline pkgs/development/python-modules/stem/default.nix:26]:
```suggestion
    homepage = "https://stem.torproject.org/";
```

Oops, didn't actually make my suggestion... lol

Comment (paumr) [reply pkgs/development/python-modules/stem/default.nix:26]: this change was already introduced in the master branch,
plus there was also a version bump.

Comment (cole-h) [reply pkgs/development/python-modules/stem/default.nix:26]: Heh, I didn't notice the base branch (thought this was against master). Sorry for the noise.

Comment (paumr) [reply pkgs/development/python-modules/stem/default.nix:26]: does this mean that this conversation can be resolved?

**Comment by drewrisinger** [comment]
suggestion: change title to ``[20.03] ...`` 
@GrahamcOfBorg build python27Packages.stem python37Packages.stem python38Packages.stem

**Comment by drewrisinger** [comment]
Best as I can tell, it fails on python3.8 due to ``platform.linux_distribution()`` being deprecated on py3.8 (see ofborg log, relevant line I found):   
```
operating system version...                          failed
module 'platform' has no attribute 'linux_distribution'
```
If you want to unbreak, you should either patch it or see if there's a new upstream version that works with py38

**Review by drewrisinger — CHANGES_REQUESTED** [review]
Should either work on py38 or be disabled on py38.

To work on py38, I suggest adding ``pythonPackages.distro`` to build, and then patching the offending line to use ``distro.linux_distribution()`` 
(e.g. via ``substituteInPlace FILE_NAME --replace "platform.linux_distribution(" "distro.linux_distribution("``)

**Comment by drewrisinger** [comment]
whoops. Looks like this is a duplicate PR of https://github.com/NixOS/nixpkgs/pull/85642. That one includes update to 1.8.0. I'd recommend taking that one instead.

**Comment by paumr** [comment]
> whoops. Looks like this is a duplicate PR of #85642. That one includes update to 1.8.0. I'd recommend taking that one instead.

Alright, thanks!
I'll close this PR in favor of #85642
