### ISSUE TITLE
hydra-unstable has compilation errors in 20.03 (no matching function for call to 'MyArgs::mkFlag()')

### ISSUE THREAD

**Issue by sylvainf911** [NixOS/nixpkgs#90079]
**Describe the bug**

The derivation `hydra-unstable` on NixOS 20.03 does not build anymore. The error is:

```
hydra-eval-jobs.cc:38:16: error: no matching function for call to 'MyArgs::mkFlag()'
   38 |         mkFlag()
```

**To Reproduce**
1. nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/70717a337f7ae4e486ba71a500367cad697e5f09.tar.gz -E '(import <nixpkgs> {}).hydra-unstable'

**Expected behavior**

The package build without error.

**Additional context**

The commit 68ab8cf78bce71a1890f28ace487230e3364ae58 has the mention `hydra-unstable: 2020-04-07 -> 2020-04-16`. But I have updated my system since and the recompilation of `hydra-unstable` worked. So I presume it is a dependency that is broken?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.03.2059.05a32d8e771 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2059.05a32d8e771"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - hydra-unstable
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
see 
https://github.com/NixOS/nixpkgs/commit/fdecd9eedab4dca3e526005b666a3bb5a14d16d6
https://github.com/NixOS/nixpkgs/pull/89297
https://github.com/NixOS/nixpkgs/pull/89805

**Comment by jonringer** [comment]
currently builds on the `release-20.03` branch, give hydra some time for the release to occur

**Comment by sylvainf911** [comment]
Thanks for pointing the PRs. I will search them next time before panicking.

Thank you.
