### PR TITLE
httping: pull upstream fix for ncurses-6.3

### PR DESCRIPTION
**Pull request by trofi**
Without the fix build on ncurses-6.3 fails as:

    nc.c:238:17: error: format not a string literal and no format arguments [-Werror=format-security]
      238 |                 wprintw(w, what);
          |                 ^~~~~~~

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg eval

**Comment by trofi** [comment]
Rebased against fresher `master` to get another chance.

**Comment by Mindavi** [comment]
Result of `nixpkgs-review pr 145944` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>httping</li>
  </ul>
</details>

I guess this works, but that github repo seems kinda strange. It's also strange that the 2.5 version is not advertised on the website...
