### ISSUE TITLE
network_cmds fails to build on unstable and master

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#168977]
This bug is very recent, within the last day or two, but affects both unstable and master. Whan I attempt to build `pkgs.darwin.network_cmds`, it first fails with this compilation error:
```
/private/tmp/nix-build-network_cmds-481.20.1.drv-0/network_cmds-481.20.1/unbound/validator/val_secalgo.c:228:8: error: incomplete definition of type 'struct DSA_SIG_st'
        dsasig->r = R;
        ~~~~~~^
```

**Comment by jwiegley** [comment]
`20220411_170044` is the last very of `unstable` that built fine for me.

**Comment by jwiegley** [comment]
Here is the commit that broke the build on my system:
```
49c51cdd516d51e3ebbb7930e5edb4174c25a0fa is the first bad commit
commit 49c51cdd516d51e3ebbb7930e5edb4174c25a0fa
Author: ajs124 <git@ajs124.de>
Date:   Wed Dec 15 17:48:19 2021 +0000

    openssl_1_0_2: drop

 .../libraries/openssl/1.0.2/darwin64-arm64.patch         | 12 ------------
 .../libraries/openssl/1.0.2/nix-ssl-cert-file.patch      | 16 ----------------
 .../openssl/1.0.2/use-etc-ssl-certs-darwin.patch         | 13 -------------
 .../libraries/openssl/1.0.2/use-etc-ssl-certs.patch      | 13 -------------
 pkgs/development/libraries/openssl/default.nix           | 14 --------------
 .../apple-source-releases/network_cmds/default.nix       |  4 ++--
 pkgs/top-level/all-packages.nix                          |  1 -
 7 files changed, 2 insertions(+), 71 deletions(-)
 delete mode 100644 pkgs/development/libraries/openssl/1.0.2/darwin64-arm64.patch
 delete mode 100644 pkgs/development/libraries/openssl/1.0.2/nix-ssl-cert-file.patch
 delete mode 100644 pkgs/development/libraries/openssl/1.0.2/use-etc-ssl-certs-darwin.patch
 delete mode 100644 pkgs/development/libraries/openssl/1.0.2/use-etc-ssl-certs.patch
```

**Comment by reckenrode** [comment]
Since it was using an old version of OpenSSL, could LibreSSL be used as a replacement? Isn’t that what Apple ships anyway?

**Comment by willcohen** [comment]
@reckenrode @jwiegley, with #170454:
```
nix-build $NIXPKGS -A darwin.network_cmds
/nix/store/kpxbfp6bcc2m4zk1zqnd89r2vzc6lhf4-network_cmds-481.20.1
```

Haven't yet rebuilt more than that, but it seems like it may generally be the fix.
