### PR TITLE
poetry: 1.4.2 -> 1.5.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://github.com/python-poetry/poetry/compare/refs/tags/1.4.2...1.5.1

Changelog: https://github.com/python-poetry/poetry/blob/refs/tags/1.5.1/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

closes https://github.com/NixOS/nixpkgs/pull/241458

### CODE REVIEW

**Review by Dessix — CHANGES_REQUESTED** [review]
Result of `nixpkgs-review pr 233393` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>poetryPlugins.poetry-plugin-up</li>
    <li>poetryPlugins.poetry-plugin-up.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>poetry</li>
    <li>poetry.dist</li>
    <li>poetryPlugins.poetry-audit-plugin</li>
    <li>poetryPlugins.poetry-audit-plugin.dist</li>
  </ul>
</details>

##### Reviewed points

- [x] changes are backward compatible
- [x] removed options are declared with `mkRemovedOptionModule`
- [x] changes that are not backward compatible are documented in release notes
- [ ] module tests succeed on ARCHITECTURE
- [x] options types are appropriate
- [x] options description is set
- [ ] options example is provided
- [x] documentation affected by the changes is updated

##### Possible improvements

Documenting how to invoke with and without plugins from a nixos configuration or flake would be helpful.

##### Comments

Fails to build on `x86_64-linux` due to plugin dependency build failures.

Failures are, ironically, due to `AttributeError: 'PyProjectTOML' object has no attribute 'file'` during the `test_e2e.py` portion of the `pytestCheckPhase`, rather than failure to actually build the plugin. May be simple incompatibility in `toml`?

Diagnosis may be complicated by apparent failure building (optional) `pandas` dependency for `python-3.10` in latest `nixpkgs` commits.

**Comment by natsukium** [comment]
The patch, #220252, seems to cause the `x86_64-darwin` build to fail.
However, without the patch, I got the same problem again.

**Comment by considerate** [comment]
I encountered a build failure the first time I built this on `x86_64-linux` but running the build again I wasn't able to reproduce the failure and instead I got a working version of `poetry`.

**Comment by Dessix** [comment]
```
error: attribute 'fetchPypi' missing

       at /home/dessix/.cache/nixpkgs-review/pr-233393-5/nixpkgs/pkgs/tools/package-management/poetry/default.nix:14:15:

           13|         version = "3.12.0";
           14|         src = self.fetchPypi {
             |               ^
```
Looks like we've got a new type of failure on the latest `nixpkgs` caused by #234043.

**Review by Dessix — APPROVED** [review]
Looks great. Let's merge it and close #241458.
