### ISSUE TITLE
Build failure: rustc

### ISSUE THREAD

**Issue by artemist** [NixOS/nixpkgs#317041]
### Steps To Reproduce

1. Build `pkgsCross.aarch64-multiplatform.buildPackages.rustc` on staging (or any other rustc where `targetPlatform` != `hostPlatform`)

This is required for cross-building any Rust package or package that depends on Rust.

### Build log
Full log at: https://gist.github.com/artemist/55b4acb21b529dabc56347decc1e8685

```
...
WARNING: The `change-id` is missing in the `config.toml`. This means that you will not be able to track the major changes mad>
NOTE: to silence this warning, add `change-id = 121754` at the top of `config.toml`
WARNING: Using a potentially old libstd. This may not behave well.
WARNING: Using a potentially old librustc. This may not behave well.
WARNING: Use `--keep-stage-std` if you want to rebuild the compiler when it changes
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building tool llvm-bitcode-linker (stage0 -> stage1, x86_64-unknown-linux-gnu)
<snip>
error[E0463]: can't find crate for `core`

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`

error: could not compile `utf8parse` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `colorchoice` (lib) due to 1 previous error
error: could not compile `once_cell` (lib) due to 1 previous error
...
```

### Additional context
This only occurs when `fastCross` is enabled. It seems to be caused by Rust 1.78.0 moving the location of `libstd.so`, `librustc_driver.so`in the unwrapped output. However, just updating the path did not fix the build in my tests.

### Notify maintainers

@Havvy @figsoda @Mic92 @tjni @winterqt @zowoq 

(for some reason i couldn't ping the github team)

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.11 (Vicuña), 24.11.20240529.ad57eef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-lixpre20240601-5312e60`
 - channels(root): `""`
 - channels(artemis): `""`
 - nixpkgs: `/nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mic92** [comment]
So this was caused by the `1.77.0 -> 1.78.0` upgrade?

**Comment by artemist** [comment]
Yes, it works fine on master with 1.77.2.

**Comment by artemist** [comment]
Seems to have been fixed in #317179
