### PR TITLE
warzone2100: fix build with vulkan-headers 1.4.350+

### PR DESCRIPTION
**Pull request by FlorianFranzen**
`warzone2100` has been failing on Hydra since the vulkan-headers 1.4.341 -> 1.4.350 bump in b3147b179a9b ([latest failed build](https://hydra.nixos.org/build/345438121)):

```
lib/ivis_opengl/gfx_api_vk.cpp:4258:95: error: 'eVkColorspaceSrgbNonlinear'
    is not a member of 'vk::ColorSpaceKHR'
```

## Backported patches:

* [Warzone2100/warzone2100#4918](https://github.com/Warzone2100/warzone2100/pull/4918): replaces the deprecated alias removed which fixes the failing build.
* [Warzone2100/warzone2100#5026](https://github.com/Warzone2100/warzone2100/pull/5026): avoids passing a null pointer and therefore fixes a runtime crash with the updated vulkan headers.

Both patches are in upstream master only, which are not part of an official release yet, so they can be dropped on the next version bump.

No backport needed as stable is still on `1.4.341.0`.

## Things done

* Built and run on x86_64-linux.
* `nixosTests.warzone2100` passes. (**note:** uses the OpenGL backend, not Vulkan)

### CODE REVIEW

File: pkgs/by-name/wa/warzone2100/package.nix [hunk 1]
```diff
@@ -57,6 +58,23 @@ stdenv.mkDerivation (finalAttrs: {
...
   };
 
+  # Build and runtime compatibility with vulkan-headers 1.4.350+, backported
+  # from upstream master. Can be dropped on the next version bump.
+  # https://github.com/Warzone2100/warzone2100/pull/4918
+  # https://github.com/Warzone2100/warzone2100/pull/5026
+  patches = [
+    (fetchpatch {
+      name = "vulkan-headers-1.4.350-drop-deprecated-colorspace-alias.patch";
+      url = "https://github.com/Warzone2100/warzone2100/commit/ac504348136e22f434fc3d7c81ec0a0605f206a8.patch";
```
Comment (fgaz) [inline pkgs/by-name/wa/warzone2100/package.nix:68]: https://github.com/Warzone2100/warzone2100/commit/ac504348136e22f434fc3d7c81ec0a0605f206a8

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Please use the merged commit here and in the other patch

**Review by fgaz — CHANGES_REQUESTED** [review]

File: pkgs/by-name/wa/warzone2100/package.nix (hunk 1 above)
Comment (FlorianFranzen) [reply pkgs/by-name/wa/warzone2100/package.nix]: Good catch, copied the wrong hashes. Fixed now!
