### ISSUE TITLE
GCC5 Build Failure [Darwin] 

### ISSUE THREAD

**Issue by lukeadams** [NixOS/nixpkgs#27889]
## Issue description
gcc5 and the dependant gfortran5 packages are failing as of 31 July
Failures: [ [gcc5](https://hydra.nixos.org/job/nixpkgs/trunk/gcc5.x86_64-darwin) [gfortran5](https://hydra.nixos.org/build/57627526#tabs-summary) ] [[hydra newly failing](https://hydra.nixos.org/eval/1380082?filter=gcc&compare=1379999&full=#tabs-now-fail)]

### Steps to reproduce
Building either package using `nix-build '<nixpkgs>' -A gcc5` or `nix-build '<nixpkgs>' -A gfortran5` fails.
## Technical details
```
../../gcc-5.4.0/libiberty/fibheap.c:151:7: warning: this function declaration is not a prototype [-Wstrict-prototypes]
../../gcc-5.4.0/libiberty/fibheap.c:220:30: error: use of undeclared identifier 'LONG_MIN'
  if (okey == key && okey != FIBHEAPKEY_MIN)
                             ^
../../gcc-5.4.0/libiberty/fibheap.c:38:24: note: expanded from macro 'FIBHEAPKEY_MIN'
#define FIBHEAPKEY_MIN  LONG_MIN
                        ^
../../gcc-5.4.0/libiberty/fibheap.c:261:36: error: use of undeclared identifier 'LONG_MIN'
  fibheap_replace_key (heap, node, FIBHEAPKEY_MIN);
                                   ^
```
* System: (MacOS 10.11.6 and MacOS 10.12.6, both nix-multiuser install)
* Nix version: (1.11.13)
* Nixpkgs version: (17.09pre-git)
* Sandboxing enabled: (relaxed)

**Comment by copumpkin** [comment]
@LnL7 has been looking into this but it seems pretty mysterious so far

**Comment by lukeadams** [comment]
```
093cc00cdd9d8cf31ecce5bc1dd3645c460a1b98 is the first bad commit
commit 093cc00cdd9d8cf31ecce5bc1dd3645c460a1b98
Author: John Ericson <John.Ericson@Obsidian.Systems>
Date:   Mon Jun 26 01:17:09 2017 -0400

    cc-wrapper: Always export environment variables for binutils

    Before, this only happened when cross compiling.

:040000 040000 d52da81f6c99fab1d1dac403d021ba5f0e7292cd 7faa156a6bb81603f41ffcf27fc0cf44a3bc0eb9 M	pkgs
```

**Comment by FRidh** [comment]
cc @Ericson2314

**Comment by LnL7** [comment]
This is also needed to fix things that depend on gcc https://github.com/NixOS/nixpkgs/commit/bf8c1251708f013ecbcf3a1c6770a175e9161170.
