### PR TITLE
ghc{822,863}Binary: fix to work w/musl again, __strdup -> strdup

### LINKED ISSUE #57238: Can no longer build GHC with Musl
GHC can no longer be built with the Musl libc because the `ghc822Binary` compiler needed to bootstrap no longer passes the install test. This prevents fully static executables from being produced with this tool chain.

I've `git bisect`ed and 0450d28a (cc @dtzWill) was the commit that introduced the regression. To reproduce:

```sh
$ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/0450d28a.tar.gz nix-build '<nixpkgs>' -A pkgsMusl.haskell.compiler.ghc822Binary --no-out-link
(....)
running install tests
[1 of 1] Compiling Main             ( main.hs, main.o )
Linking main ...
/nix/store/wvj2kzhypkkwqx6qjcghm60bz6pqlqzz-binutils-2.31.1/bin/ld: /nix/store/f0061cv30fk6d2lxrivakbwqk0fqvlgp-ghc-8.2.2-binary/lib/ghc-8.2.2/rts/libHSrts.a(Hpc.o): in function `startupHpc':

/home/ben/bin-dist-8.2.2-Linux/ghc/rts/Hpc.c:214:0: error:
     undefined reference to `__strdup'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
builder for '/nix/store/i3s9a1zpma6pscf6xdi91r4h0hvyy87a-ghc-8.2.2-binary.drv' failed with exit code 1
error: build of '/nix/store/i3s9a1zpma6pscf6xdi91r4h0hvyy87a-ghc-8.2.2-binary.drv' failed
```
The previous commit, b262be32, works:

```sh
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/b262be32.tar.gz nix-build '<nixpkgs>' -A pkgsMusl.haskell.compiler.ghc822Binary --no-out-link
(...)
running install tests
[1 of 1] Compiling Main             ( main.hs, main.o )
Linking main ...
compilation ok
/nix/store/pxd37xckl30yfky2rbj3a7bhz9fgvjkl-ghc-8.2.2-binary
```

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/57238.

Should be backported to any release branch impacted by the issue.
Which I think is just 19.03 :).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Mostly was trying to fix the binary bootstrap build,
have not thoroughly tested the resulting compilers
(particularly the many versions built from these)
are all functioning reasonably...

I think if this at least fixes `pkgsMusl.ghc` it's a win :).

### CODE REVIEW

**Comment by roberth** [comment]
Does not impact non-musl :+1: 

Non-blocking question: this seems to be the host runtime system, which will be linked into stage1. Can't stage1 use glibc and emit a musl stage2?

**Comment by dtzWill** [comment]
> Non-blocking question: this seems to be the host runtime system, which will be linked into stage1. Can't stage1 use glibc and emit a musl stage2?

I don't know enough about ghc's compilation infrastructure to say, but that seems reasonable.
Since most of what we use this for is to build the other compilers, is that different than handling across stages?

**Comment by roberth** [comment]
I really can't judge how easy or hard it is either.

**Review by roberth — APPROVED** [review]

**Review by roberth — APPROVED** [review]
