### PR TITLE
pantalaimon: add glib typelib to GI_TYPELIB_PATH

### PR DESCRIPTION
**Pull request by rrix**
## Description of changes

After upgrading from 23.11 to 24.05 my pantalaimon and pantalaimon-headless would fail to start

```
pantalaimon[520124]: Traceback (most recent call last):
pantalaimon[520124]:   File "/nix/store/696z8j4sh013k1zv0nmv7w989rksjfzc-pantalaimon-0.10.5/bin/.pantalaimon-wrapped", line 6, in <module>
pantalaimon[520124]:     from pantalaimon.main import main
pantalaimon[520124]:   File "/nix/store/696z8j4sh013k1zv0nmv7w989rksjfzc-pantalaimon-0.10.5/lib/python3.11/site-packages/pantalaimon/main.py", line 34, in <module>
ppantalaimon[520124]:   File "/nix/store/696z8j4sh013k1zv0nmv7w989rksjfzc-pantalaimon-0.10.5/lib/python3.11/site-packages/pantalaimon/ui.py", line 30, in <module>
pantalaimon[520124]:     from gi.repository import GLib
pantalaimon[520124]:   File "/nix/store/0x1rkqvaiddldc1si8wjwphz7wbny269-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
pantalaimon[520124]:     raise ImportError('cannot import name %s, '
pantalaimon[520124]: ImportError: cannot import name GLib, introspection typelib not found
systemd[1988]: pantalaimon.service: Main process exited, code=exited, status=1/FAILURE
```

This is usually managed by `wrapGAppsHook` but we only need glib typelib to make this work, so I set up a GI_TYPELIB_PATH wrapper modeled on wrappers in other nixpkgs.

This change allows pantalaimon to start and sync and have a working dbus interface.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eclairevoyant — DISMISSED** [review]
This should use `wrapGAppsNoGuiHook` + `gobject-introspection` in `nativeBuildInputs` instead. Also will need to prevent double-wrapping

EDIT: corrected

**Comment by eclairevoyant** [comment]
> idk how to do that

https://github.com/NixOS/nixpkgs/blob/bef4a000c257bace935c77cdb6f19f55fdef9501/pkgs/applications/misc/bleachbit/default.nix#L54-L58
