### PR TITLE
camset: patch to work with numpy >=2.3

### PR DESCRIPTION
**Pull request by wathiede**
Addresses runtime error:

Unable to detect what device /dev/media0 is, exiting. Traceback (most recent call last):
  File "/nix/store/vwv84rg90w91dwbim8bajz37rlvwwisf-camset-0-unstable-2023-05-20/lib/python3.13/site-packages/camset/cam_window.py", line 71, in show_frame
    pixbuf = GdkPixbuf.Pixbuf.new_from_data(frame.tostring(),
                                            ^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'tostring'

## Things done

- Built on platform:
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [X] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [ ] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

File: pkgs/by-name/ca/camset/package.nix [hunk 1]
```diff
@@ -20,6 +21,14 @@ python3Packages.buildPythonApplication {
     rev = "b813ba9b1d29f2d46fad268df67bf3615a324f3e";
     hash = "sha256-vTF3MJQi9fZZDlbEj5800H22GGWOte3+KZCpSnsSTaQ=";
   };
+  patches = [
+    # remove when https://github.com/azeam/camset/pull/30 merged
+    (fetchpatch {
+      url = "https://github.com/azeam/camset/commit/61e500c661cc6f2d5095a380be719c10c0f77c61.patch";
```
Comment (SuperSandro2000) [inline pkgs/by-name/ca/camset/package.nix]: Unmerged PRs must be vendored

Comment (wathiede) [reply pkgs/by-name/ca/camset/package.nix]: Done
