### ISSUE TITLE
Nvidia drivers fail to build with latest stable (20.09)

### ISSUE THREAD

**Issue by TLATER** [NixOS/nixpkgs#124709]
**Describe the bug**

When running kernel version 5.11 (through `linuxPackages_latest` or similar), the nvidia driver will fail to build with this:

<details>
    <summary>Build log</summary>

```
nvidia-x11> make[3]: *** [/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/source/scripts/Makefile.build:279: /build/kernel/nvidia/nv-mmap.o] Error 1
nvidia-x11> In file included from /build/kernel/common/inc/nv-pci.h:15,
nvidia-x11>                  from /build/kernel/nvidia/nv-pci.c:13:
nvidia-x11> /build/kernel/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
nvidia-x11>   119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
nvidia-x11>       |          ^~~~~~~~~~~~~~~~~~
nvidia-x11> compilation terminated.
nvidia-x11> make[3]: *** [/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/source/scripts/Makefile.build:279: /build/kernel/nvidia/nv-pci.o] Error 1
nvidia-x11> In file included from /build/kernel/nvidia/nv-i2c.c:17:
nvidia-x11> /build/kernel/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
nvidia-x11>   119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
nvidia-x11>       |          ^~~~~~~~~~~~~~~~~~
nvidia-x11> compilation terminated.
nvidia-x11> make[3]: *** [/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/source/scripts/Makefile.build:279: /build/kernel/nvidia/nv-i2c.o] Error 1
nvidia-x11> In file included from /build/kernel/nvidia/nv-procfs.c:15:
nvidia-x11> /build/kernel/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
nvidia-x11>   119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
nvidia-x11>       |          ^~~~~~~~~~~~~~~~~~
nvidia-x11> compilation terminated.
nvidia-x11> make[3]: *** [/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/source/scripts/Makefile.build:279: /build/kernel/nvidia/nv-procfs.o] Error 1
nvidia-x11> In file included from /build/kernel/nvidia/nv-cray.c:15:
nvidia-x11> /build/kernel/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
nvidia-x11>   119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
nvidia-x11>       |          ^~~~~~~~~~~~~~~~~~
nvidia-x11> compilation terminated.
nvidia-x11> make[3]: *** [/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/source/scripts/Makefile.build:279: /build/kernel/nvidia/nv-cray.o] Error 1
nvidia-x11> make[2]: *** [/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/source/Makefile:1820: /build/kernel] Error 2
nvidia-x11> make[2]: Leaving directory '/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/build'
nvidia-x11> make[1]: *** [Makefile:185: __sub-make] Error 2
nvidia-x11> make[1]: Leaving directory '/nix/store/q1f1bm027060j3ax0gvfl37bkcj3qf7q-linux-5.11.20-dev/lib/modules/5.11.20/source'
nvidia-x11> make: *** [Makefile:81: modules] Error 2
```
</details>

This is an upstream issue, quoting the [release notes of a subsequent driver](https://www.nvidia.com/download/driverResults.aspx/171392/en-us):

> Fixed a driver installation failure on Linux kernel 5.11 release candidates, where the NVIDIA kernel module failed to build with error
> "fatal error: asm/kmap_types.h: No such file or directory". 

**To Reproduce**
1. Specify the following in a `configuration.nix`:

```nix
{ pkgs, ... }: {
    nixpkgs.config.allowUnfreePredicate = pkg:
        builtins.elem (pkgs.lib.getName pkg) [
            "nvidia-x11"
            "nvidia-settings"
            "nvidia-persistenced"
        ];

    boot.kernelPackages = pkgs.linuxPackages_latest;
    services.xserver.videoDrivers = "nvidia";
}
```

2. Build the config

**Expected behavior**

Nvidia drivers shouldn't fail to build.

**Additional context**

Some people are working around this by using the unstable linux package, which made #123972 worse than it should have been.

**Notify maintainers**

- @baracoder

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.19, NixOS, 20.09.20210514.21ff930 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.05pre279012.ad47284f8b0"`
 - channels(tlater): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

(Note the channels are wrong, [see my `flake.lock` for exact details](https://github.com/TLATER/nixos-hosts/blob/master/flake.lock)).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mudrii** [comment]
I can confirm having the same issue with both  nvidia and nvidiaBeta when using 

```boot.kernelPackages = pkgs.linuxPackages_latest;```

**Comment by Kranzes** [comment]
Same here

**Comment by TLATER** [comment]
For reference, this will be fixed in 21.05, which should be released any time today, after which I believe 20.09 will be unmaintained anyway.

So if you're running into this, just upgrade to the next stable version :)

**Comment by mudrii** [comment]
tested under 21.05 and seems issue is solved

**Comment by TLATER** [comment]
Yep, can confirm as well. Closing the issue with that.
