### ISSUE TITLE
znapzend broken

### ISSUE THREAD

**Issue by Infinisil** [NixOS/nixpkgs#40516]
## Issue description
Znapzend throws an error when ran in latest master (405f9d10efc56d8f6080cf8b46d95e6774d40d4f):

```
$ znapzend
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
"slurp" is not exported by the Mojo::Util module
Can't continue after import errors at /nix/store/pxc4h5vchr0z9zqnqg4r9ladny34lpp6-znapzend-0.18.0/lib/ZnapZend.pm line 5.
BEGIN failed--compilation aborted at /nix/store/pxc4h5vchr0z9zqnqg4r9ladny34lpp6-znapzend-0.18.0/lib/ZnapZend.pm line 5.
Compilation failed in require at result/bin/znapzend line 9.
BEGIN failed--compilation aborted at result/bin/znapzend line 9.
```

This was introduced in 3c74f80e00ed6dacc2cf498ab238247e54baf77d and because @r-ryantm apparently doesn't run the most important `znapzend` command, the error wasn't caught in #39029 either.

Reverting the update of Mojolicious in the above commit makes it work again. I don't have any experience with Perl, so I'm not sure what's the best course of action to fix this.

Ping @volth @otwieracz @ryantm @fpletz

**Comment by volth** [comment]
yes, it needs exact version Mojolicious@6.46
https://github.com/oetiker/znapzend/blob/master/PERL_MODULES

**Comment by volth** [comment]
There is also a problem that Mojolicious6 has been removed from CPAN, not only from ```perl-packages.nix``` :(

http://ftp.gwdg.de/pub/languages/perl/CPAN/authors/id/S/SR/SRI/
