### PR TITLE
broadcom_sta: fix build on linux 6.1

### LINKED ISSUE #206867: broadcom_sta fails to build
### Steps To Reproduce
1. `nix-build -A linuxKernel.packages.linux_latest_libre.broadcom_sta`

### Build log
```
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1792:20: error: initialization of 'int (*)(struct wiphy *, struct net_device *, int,  u8,  bool,  const u8 *, struct key_params *)' {aka 'int (*)(struct wiphy *, struct net_device *, int,  unsigned char,  _Bool,  const unsigned char *, struct key_params *)'} from incompatible pointer type 's32 (*)(struct wiphy *, struct net_device *, u8,  bool,  const u8 *, struct key_params *)' {aka 'int (*)(struct wiphy *, struct net_device *, unsigned char,  _Bool,  const unsigned char *, struct key_params *)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
 1792 |         .add_key = wl_cfg80211_add_key,
      |                    ^~~~~~~~~~~~~~~~~~~
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1792:20: note: (near initialization for 'wl_cfg80211_ops.add_key')
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1793:20: error: initialization of 'int (*)(struct wiphy *, struct net_device *, int,  u8,  bool,  const u8 *)' {aka 'int (*)(struct wiphy *, struct net_device *, int,  unsigned char,  _Bool,  const unsigned char *)'} from incompatible pointer type 's32 (*)(struct wiphy *, struct net_device *, u8,  bool,  const u8 *)' {aka 'int (*)(struct wiphy *, struct net_device *, unsigned char,  _Bool,  const unsigned char *)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
 1793 |         .del_key = wl_cfg80211_del_key,
      |                    ^~~~~~~~~~~~~~~~~~~
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1793:20: note: (near initialization for 'wl_cfg80211_ops.del_key')
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1794:20: error: initialization of 'int (*)(struct wiphy *, struct net_device *, int,  u8,  bool,  const u8 *, void *, void (*)(void *, struct key_params *))' {aka 'int (*)(struct wiphy *, struct net_device *, int,  unsigned char,  _Bool,  const unsigned char *, void *, void (*)(void *, struct key_params *))'} from incompatible pointer type 's32 (*)(struct wiphy *, struct net_device *, u8,  bool,  const u8 *, void *, void (*)(void *, struct key_params *))' {aka 'int (*)(struct wiphy *, struct net_device *, unsigned char,  _Bool,  const unsigned char *, void *, void (*)(void *, struct key_params *))'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
 1794 |         .get_key = wl_cfg80211_get_key,
      |                    ^~~~~~~~~~~~~~~~~~~
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1794:20: note: (near initialization for 'wl_cfg80211_ops.get_key')
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1795:28: error: initialization of 'int (*)(struct wiphy *, struct net_device *, int,  u8,  bool,  bool)' {aka 'int (*)(struct wiphy *, struct net_device *, int,  unsigned char,  _Bool,  _Bool)'} from incompatible pointer type 's32 (*)(struct wiphy *, struct net_device *, u8,  bool,  bool)' {aka 'int (*)(struct wiphy *, struct net_device *, unsigned char,  _Bool,  _Bool)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
 1795 |         .set_default_key = wl_cfg80211_config_default_key,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1795:28: note: (near initialization for 'wl_cfg80211_ops.set_default_key')
cc1: some warnings being treated as errors
make[2]: *** [/nix/store/vc4xd7fz34rvr5i64j2d0w4gxhgmyqbx-linux-6.1-dev/lib/modules/6.1.0-gnu/source/scripts/Makefile.build:250: /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o] Error 1
make[1]: *** [/nix/store/vc4xd7fz34rvr5i64j2d0w4gxhgmyqbx-linux-6.1-dev/lib/modules/6.1.0-gnu/source/Makefile:1992: /build/broadcom-sta] Error 2
make[1]: Leaving directory '/nix/store/vc4xd7fz34rvr5i64j2d0w4gxhgmyqbx-linux-6.1-dev/lib/modules/6.1.0-gnu/build'
make: *** [Makefile:161: all] Error 2
error: builder for '/nix/store/pi4n8q67lpw4qgirm767cq56z3rk4xbc-broadcom-sta-6.30.223.271-6.1.drv' failed with exit code 2;
       last 10 log lines:
       > /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1794:20: note: (near initialization for 'wl_cfg80211_ops.get_key')
       > /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1795:28: error: initialization of 'int (*)(struct wiphy *, struct net_device *, int,  u8,  bool,  bool)' {aka 'int (*)(struct wiphy *, struct net_device *, int,  unsigned char,  _Bool,  _Bool)'} from incompatible pointer type 's32 (*)(struct wiphy *, struct net_device *, u8,  bool,  bool)' {aka 'int (*)(struct wiphy *, struct net_device *, unsigned char,  _Bool,  _Bool)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >  1795 |         .set_default_key = wl_cfg80211_config_default_key,
       >       |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:1795:28: note: (near initialization for 'wl_cfg80211_ops.set_default_key')
       > cc1: some warnings being treated as errors
       > make[2]: *** [/nix/store/vc4xd7fz34rvr5i64j2d0w4gxhgmyqbx-linux-6.1-dev/lib/modules/6.1.0-gnu/source/scripts/Makefile.build:250: /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o] Error 1
       > make[1]: *** [/nix/store/vc4xd7fz34rvr5i64j2d0w4gxhgmyqbx-linux-6.1-dev/lib/modules/6.1.0-gnu/source/Makefile:1992: /build/broadcom-sta] Error 2
       > make[1]: Leaving directory '/nix/store/vc4xd7fz34rvr5i64j2d0w4gxhgmyqbx-linux-6.1-dev/lib/modules/6.1.0-gnu/build'
       > make: *** [Makefile:161: all] Error 2
       For full logs, run 'nix log /nix/store/pi4n8q67lpw4qgirm767cq56z3rk4xbc-broadcom-sta-6.30.223.271-6.1.drv'.
```

### Notify maintainers

@X9VoiD maybe

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 23.05 (Stoat), 23.05.20221205.6e51c97`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-21.11pre299825.d8079260a30"`
 - nixpkgs: `/run/current-system/nixpkgs`

### PR DESCRIPTION
**Pull request by X9VoiD**
###### Description of changes

Fix build issues when building against linux 6.1

Fixes #206867

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bbigras — APPROVED** [review]
It builds. Thanks!

**Comment by NobbZ** [comment]
Added the backport label on PR-authors request.
