### PR TITLE
libxml2: 2.12.7 → 2.13.2

### PR DESCRIPTION
**Pull request by jtojnar**
## Description of changes

Supersedes https://github.com/NixOS/nixpkgs/pull/319982, https://github.com/NixOS/nixpkgs/pull/324629

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
Bisect says 25bc618215a72f681678bf58300f72b1a6f920c4 `libxml2: 2.12.7 → 2.13.2` broke `colord` build in `staging` as:

```
ERROR: Error in gtkdoc helper script:

ERROR: ['/nix/store/3bjl4a6x553igz8av394afjlb9r85p9z-gtk-doc-1.34.0/bin/gtkdoc-mkhtml', '--path=/build/colord-1.4.6/doc/api:/build/colord-1.4.6/build/doc/api', 'colord', '../colord-docs.xml'] failed with status 6
warning: failed to load external entity "../../../COPYING"
```

**Comment by jtojnar** [comment]
@trofi that sounds like an issue with the build system. Looking at the code, the path refers to `build/copying` since Meson does out-of-tree builds:

https://github.com/hughsie/colord/blob/4a5a8ac167f940d74b4ac6e3f588bd50b8b777ea/doc/api/colord-docs.xml#L107

The following appears to fix it:

```
substituteInPlace doc/api/colord-docs.xml --replace-fail "../../COPYING" "../../../COPYING"
```

But that is not upstreamable since build directory location is configurable.

Also for some reason, the warning actually shows correct relative path (one higher than used).

And it is not clear to me why it fails when there is a xinclude fallback.

**Comment by jtojnar** [comment]
Actually, might be the same as https://gitlab.gnome.org/GNOME/libxml2/-/issues/733 that affected systemd docs. We should probably backport that.

**Comment by jtojnar** [comment]
Opened new upstream issue: https://gitlab.gnome.org/GNOME/libxml2/-/issues/772

**Comment by trofi** [comment]
Looks like `librdf_raptor2` is also affected by the same 25bc618215a72f681678bf58300f72b1a6f920c4 `libxml2: 2.12.7 → 2.13.2` on `staging`:

```
$ nix build --no-link -f. -L librdf_raptor2
...
raptor2-unstable> /nix/store/2qnz8ch0m3vjgjmjy8g66ik1rrm560ki-binutils-2.42/bin/ld: libraptor2.so: undefined reference to `xmlNanoHTTPScanProxy'
raptor2-unstable> /nix/store/2qnz8ch0m3vjgjmjy8g66ik1rrm560ki-binutils-2.42/bin/ld: libraptor2.so: undefined reference to `xmlNanoHTTPClose'
raptor2-unstable> /nix/store/2qnz8ch0m3vjgjmjy8g66ik1rrm560ki-binutils-2.42/bin/ld: libraptor2.so: undefined reference to `xmlNanoHTTPReturnCode'
raptor2-unstable> /nix/store/2qnz8ch0m3vjgjmjy8g66ik1rrm560ki-binutils-2.42/bin/ld: libraptor2.so: undefined reference to `xmlNanoHTTPRead'
raptor2-unstable> /nix/store/2qnz8ch0m3vjgjmjy8g66ik1rrm560ki-binutils-2.42/bin/ld: libraptor2.so: undefined reference to `xmlNanoHTTPCleanup'
raptor2-unstable> /nix/store/2qnz8ch0m3vjgjmjy8g66ik1rrm560ki-binutils-2.42/bin/ld: libraptor2.so: undefined reference to `xmlNanoHTTPMethod'
raptor2-unstable> /nix/store/2qnz8ch0m3vjgjmjy8g66ik1rrm560ki-binutils-2.42/bin/ld: libraptor2.so: undefined reference to `xmlNanoHTTPInit'
raptor2-unstable> collect2: error: ld returned 1 exit status
raptor2-unstable> make[2]: *** [src/CMakeFiles/raptor_uri_test.dir/build.make:100: src/raptor_uri_test] Error 1
```

**Comment by nwellnhof** [comment]
```
raptor2-unstable> /build/source/src/raptor_www_libxml.c:43:3: warning: implicit declaration of function 'xmlNanoHTTPInit' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Wimplicit-function-declaration8;;]
raptor2-unstable>    43 |   xmlNanoHTTPInit();
```

You either have to build libxml2 with HTTP or legacy support or build raptor without "www" support.

**Comment by jtojnar** [comment]
Fixing libraptor in https://github.com/NixOS/nixpkgs/pull/328243

Tried to apply the patch with libxml2 fix but that breaks tests: https://gitlab.gnome.org/GNOME/libxml2/-/issues/772#note_2171538

**Comment by trofi** [comment]
`postgresql` is also affected by 25bc618215a72f681678bf58300f72b1a6f920c4 `libxml2: 2.12.7 → 2.13.2` in `staging`:

```
$ nix build --no-link -f. -L postgresql
...
postgresql>      xml                          ... FAILED      179 ms
...
postgresql> make: *** [GNUmakefile:69: check] Error 2
error: builder for '/nix/store/gvx4dp3zzq14ra5cxkfr0bh6j8jaaqax-postgresql-15.7.drv' failed with exit code 2;
```

**Comment by jtojnar** [comment]
That might be fixed by https://github.com/postgres/postgres/commit/e7192486dded0ca82824fef95eb88b4231bdd4d2
Possibly also https://github.com/postgres/postgres/commit/896cd266fd34c2dfbf06297b9f2ea89ae8e5a0b1 for future proofing.

**Comment by nwellnhof** [comment]
For Postgres, you might also need this libxml2 commit from the 2.13 branch: https://gitlab.gnome.org/GNOME/libxml2/-/commit/e30cb632e734394ddbd7bd62b57cee3586424352

There will be a 2.13.3 release next week.

**Comment by vcunat** [comment]
- [ ] libspatialite: it's missing zlib right now but mainly it's missing the libxml2 http API.
  ```
  [...]/libspatialite.so: undefined reference to `xmlNanoHTTPCleanup'
  ```
  /cc maintainers (subset for now): @dotlambda, @imincik

**Comment by imincik** [comment]
> * [x]  libspatialite: it's missing zlib right now but mainly it's missing the libxml2 http API.
>   ```
>   [...]/libspatialite.so: undefined reference to `xmlNanoHTTPCleanup'
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   /cc maintainers (subset for now): @dotlambda, @imincik
>   [[staging-next] Fix libspatialite build #330337](https://github.com/NixOS/nixpkgs/pull/330337)

Sorry, just returned from vacation. Thanks for fix.

**Comment by kirillrdy** [comment]
there is also postgis failure
 
https://github.com/NixOS/nixpkgs/pull/331166

**Comment by jtojnar** [comment]
For some reason 25bc618215a72f681678bf58300f72b1a6f920c4 is the first bad commit causing runtime issues in mysqlnd PHP extensions:

```ShellSession
$ nix-build --expr 'let pkgs = import ./. {}; in pkgs.php.withExtensions ({ all, ... }: [ all.mysqlnd ])' && result/bin/php -i | grep Warning
/nix/store/m8s2xh98lx9n30jx256qw79hfpdnx2sk-php-with-extensions-8.2.21
Warning: PHP Startup: Unable to load dynamic library '/nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so' (tried: /nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so (/nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so: undefined symbol: compress), /nix/store/qh0311v3hwbbd8mf15kv3zmz91hq4d1c-php-8.2.21/lib/php/extensions//nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so.so (/nix/store/qh0311v3hwbbd8mf15kv3zmz91hq4d1c-php-8.2.21/lib/php/extensions//nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

$ nix-build --expr 'let pkgs = import ./. {}; in pkgs.php.withExtensions ({ all, ... }: [ all.mysqli ])' && result/bin/php -i | grep Warning
/nix/store/78nn66mdmvqry6x3nv960w4rjaz6rf19-php-with-extensions-8.2.21
Warning: PHP Startup: Unable to load dynamic library '/nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so' (tried: /nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so (/nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so: undefined symbol: compress), /nix/store/qh0311v3hwbbd8mf15kv3zmz91hq4d1c-php-8.2.21/lib/php/extensions//nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so.so (/nix/store/qh0311v3hwbbd8mf15kv3zmz91hq4d1c-php-8.2.21/lib/php/extensions//nix/store/4gz4xg5g4j2i7yq1qsnq4sp63dmyl5s0-php-mysqlnd-8.2.21/lib/php/extensions/mysqlnd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/nix/store/47v522nby5yhg5dm70qb1dld0jwv29xg-php-mysqli-8.2.21/lib/php/extensions/mysqli.so' (tried: /nix/store/47v522nby5yhg5dm70qb1dld0jwv29xg-php-mysqli-8.2.21/lib/php/extensions/mysqli.so (/nix/store/47v522nby5yhg5dm70qb1dld0jwv29xg-php-mysqli-8.2.21/lib/php/extensions/mysqli.so: undefined symbol: mysqlnd_global_stats), /nix/store/qh0311v3hwbbd8mf15kv3zmz91hq4d1c-php-8.2.21/lib/php/extensions//nix/store/47v522nby5yhg5dm70qb1dld0jwv29xg-php-mysqli-8.2.21/lib/php/extensions/mysqli.so.so (/nix/store/qh0311v3hwbbd8mf15kv3zmz91hq4d1c-php-8.2.21/lib/php/extensions//nix/store/47v522nby5yhg5dm70qb1dld0jwv29xg-php-mysqli-8.2.21/lib/php/extensions/mysqli.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

cc @NixOS/php
