### ISSUE TITLE
haskellPackages.cabal-lenses fails to build in 17.09

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#36369]
## Issue description

`haskellPackages.cabal-lenses` is uninstallable in 17.09. It's a dependency of `cabal-bounds`, which is a useful command-line tool for maintaining cabal project files.

### Steps to reproduce

```
$ nix-build --no-out-link '<nixpkgs>' -A haskellPackages.cabal-lenses

Building cabal-lenses-0.7.0...
Preprocessing library cabal-lenses-0.7.0...
[ 1 of 11] Compiling Paths_cabal_lenses ( dist/build/autogen/Paths_cabal_lenses.hs, dist/build/Paths_cabal_lenses.o )
[ 2 of 11] Compiling CabalLenses.Version ( lib/CabalLenses/Version.hs, dist/build/CabalLenses/Version.o )

lib/CabalLenses/Version.hs:14:22: error:
    Variable not in scope: versionNumbers :: Version -> [Int]

lib/CabalLenses/Version.hs:14:37: error:
    • Variable not in scope: mkVersion :: [Int] -> Version
    • Perhaps you meant one of these:
        data constructor ‘Version’ (imported from Distribution.Version),
        ‘noVersion’ (imported from Distribution.Version)

lib/CabalLenses/Version.hs:21:57: error:
    • Couldn't match type ‘Maybe VersionIntervals’
                     with ‘VersionIntervals’
      Expected type: [VersionInterval] -> VersionIntervals
        Actual type: [VersionInterval] -> Maybe VersionIntervals
    • In the second argument of ‘(.)’, namely ‘mkVersionIntervals’
      In the expression: fromVersionIntervals . mkVersionIntervals
      In the expression:
        fromVersionIntervals . mkVersionIntervals $ intervals

lib/CabalLenses/Version.hs:47:28: error:
    • Variable not in scope: mkVersion :: [Integer] -> Version
    • Perhaps you meant one of these:
        data constructor ‘Version’ (imported from Distribution.Version),
        ‘noVersion’ (imported from Distribution.Version)
[ 3 of 11] Compiling CabalLenses.Utils ( lib/CabalLenses/Utils.hs, dist/build/CabalLenses/Utils.o )
[ 4 of 11] Compiling CabalLenses.Section ( lib/CabalLenses/Section.hs, dist/build/CabalLenses/Section.o )

lib/CabalLenses/Section.hs:8:1: error:
    Failed to load interface for ‘Distribution.Types.UnqualComponentName’
    Use -v to see a list of the files searched for.
[ 5 of 11] Compiling CabalLenses.PackageDescription ( lib/CabalLenses/PackageDescription.hs, dist/build/CabalLenses/PackageDescription.o )
[ 6 of 11] Compiling CabalLenses.Package ( lib/CabalLenses/Package.hs, dist/build/CabalLenses/Package.o )

lib/CabalLenses/Package.hs:10:1: error:
    Failed to load interface for
 ‘Distribution.Types.PackageName’
    Use -v to see a list of the files searched for.
[ 7 of 11] Compiling CabalLenses.CondVars ( lib/CabalLenses/CondVars.hs, dist/build/CabalLenses/CondVars.o )

lib/CabalLenses/CondVars.hs:53:11: error:

    Not in scope:
 ‘PD.unFlagName’
    Perhaps you meant
 one of these:

      data constructor
 ‘PD.FlagName’ (imported from
 Distribution.PackageDescription),
      ‘PD.flagName’ (imported from
 Distribution.PackageDescription)
    Module
 ‘Distribution.PackageDescription’ does not export ‘unFlagName’.
lib/CabalLenses/CondVars.hs:88:33: error:

    Not in scope:
 ‘PD.unFlagName’
    Perhaps you meant
 one of these:

      data constructor
 ‘PD.FlagName’ (imported from
 Distribution.PackageDescription),
      ‘PD.flagName’ (imported from
 Distribution.PackageDescription)
    Module
 ‘Distribution.PackageDescription’ does not export
 ‘unFlagName’.
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.83, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels($USER): `""`
 - channels(root): `"nixos-17.09.3129.1dcd022f01b, unstable-18.03pre126508.8ecadc12502"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
