### ISSUE TITLE
Build failure: onlyoffice-documentserver

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [NixOS/nixpkgs#536824]
### Nixpkgs version

- Stable (26.05)
- Unstable

### Steps to reproduce

```bash
nix build nixpkg/nixos-26.05#onlyoffice-documentserver
```

or

```bash
nix build nixpkgs/nixos-unstable#onlyoffice-documentserver
```

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

26.05: https://hydra.nixos.org/build/332146121
Unstable: https://hydra.nixos.org/build/332823962

### Relevant log output

```console
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x1a): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x27): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x34): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x41): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x4e): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: /build/source/Common/3dParty/v8/../v8_89/v8/out.gn/linux_64/obj/libv8.a(v8_base_without_compiler.special-case.o):(.text._ZN2v88internal18BuildSpecialAddSetEv+0x5b): more undefined references to `icu_78::UnicodeSet::add(int)' follow
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: /build/source/Common/3dParty/v8/../v8_89/v8/out.gn/linux_64/obj/libv8.a(v8_base_without_compiler.special-case.o): in function `v8::internal::BuildSpecialAddSet()':
(.text._ZN2v88internal18BuildSpecialAddSetEv+0xa4): undefined reference to `icu_78::UnicodeSet::freeze()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:311: ../../build/lib/linux_64/libdoctrenderer.so] Error 1
```

### Additional context

I bisected the change and the first bad commit for 26.05 is https://github.com/NixOS/nixpkgs/commit/4b965d7e22e3f82c9e9c77dd51bdd70679f0a904 .

So https://github.com/NixOS/nixpkgs/pull/520553 and https://github.com/NixOS/nixpkgs/pull/534248 are related.

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.33, NixOS, 26.05 (Yarara), 26.05.20260528.ec942ba`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.94.2
System type: x86_64-linux
Additional system types: aarch64-linux, i686-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/geoffrey/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/geoffrey/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/geoffrey/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/geoffrey/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/hmqgwax4s290mg1mi1g9vbabyjckr0db-lix-2.94.2/share`
 - nixpkgs: `/nix/store/lff22h6g4kvy848a7z8prfb0cgmy2hgy-source`

### Notify maintainers

@raboof 

Maybe also worth mentionning @marcin-serwin and @vcunat who made the related PRs?

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vcunat** [comment]
Note: while it's a bit unintentional (and weird that stable 26.05 will be ahead for weeks), unstable/master will get fixed by not bumping the default icu in time, so it will succeed again soon:
https://hydra.nixos.org/build/333482432

**Comment by raboof** [comment]
Ugh, this is definitely a wart in onlyoffice-documentserver. I'm embarassed I didn't notice it myself, I thought I had subscribed to hydra failures for the packages I maintain via nixpkgs-update-notify-bot , but apparently it needs an explicit nudge when packages are added (https://github.com/asymmetric/nixpkgs-update-notifier/issues/9).

I hope to PR a fix tonight.

**Comment by raboof** [comment]
> I bisected the change and the first bad commit for 26.05 is [4b965d7](https://github.com/NixOS/nixpkgs/commit/4b965d7e22e3f82c9e9c77dd51bdd70679f0a904) .
> 
> So [#520553](https://github.com/NixOS/nixpkgs/pull/520553) and [#534248](https://github.com/NixOS/nixpkgs/pull/534248) are related.

Yes, spot on.

**Comment by hatch01** [comment]
Seems that OnlyOffice is broken again: https://hydra.nixos.org/build/336776501
