### PR TITLE
lunatic: 0.13.2 -> 0.13.2-unstable-2024-03-18, fix build

### PR DESCRIPTION
**Pull request by ghpzin**
- update to latest commit
Diff: https://github.com/lunatic-solutions/lunatic/compare/v0.13.2...fc046ed65fecfdb580922c8df409881ca12b9052

- add Cargo.lock patch from `cargo update time`, fixing build with rust 1.80

---

Fixes build of `lunatic`, fails since `2024-08-15` (update to rust 1.80):
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.lunatic.x86_64-linux/all
https://hydra.nixos.org/build/293037178

Log:
```text
error[E0282]: type annotations needed for `Box<_>`
  --> /build/lunatic-0.13.2-vendor/time-0.3.20/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```

Update to `-unstable` with commit is needed, because from `v0.13.2` you can't `cargo update time` past the version that would build on rust 1.80 (because of semver versions).
Between `v0.13.2` and latest there was update to crate versions that makes it possible as is, but `time` in `Cargo.lock` is still not enough to build.
So another patch to `Cargo.lock` is needed on top of latest commit.

Tracking issue: #332957
Upstream PR with `Cargo.lock` update that would allow to drop patch (unlikely to get merged as there were no new commits upstream for 1 year):
https://github.com/lunatic-solutions/lunatic/pull/229

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ghpzin** [comment]
Saw #353827, closing according to comment inside.

**Comment by ghpzin** [comment]
Reopened as upstream merged `Cargo.lock` update.
