### PR TITLE
vtk: fix build with gdal-3.13; vtk_9_6: 9.6.0 -> 9.6.2; python3Packages.vtk: drop wslink; vtk: propagate qttools;

### LINKED ISSUE #542507: Build failure: python3Packages.vtk
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

`nix-build -A python3Packages.vtk`

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

https://hydra.nixos.org/build/337985184

### Relevant log output

```console
[ 38%] Building CXX object IO/GDAL/CMakeFiles/IOGDAL.dir/vtkGDALVectorReader.cxx.o
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx: In member function 'void vtkGDALRasterReader::vtkGDALRasterReaderInternal::ReadMetaData(const std::string&)':
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx:185:43: error: invalid conversion from 'CSLConstList' {aka 'const char* const*'} to 'char**' [-fpermissive]
  185 |     char** papszMetaData = GDALGetMetadata(this->GDALData, nullptr);
      |                            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           CSLConstList {aka const char* const*}
[ 38%] Building CXX object Domains/Microscopy/CMakeFiles/DomainsMicroscopy.dir/vtkOpenSlideReader.cxx.o
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx: In member function 'std::vector<std::__cxx11::basic_string<char> > vtkGDALRasterReader::GetDomainMetaData(const std::string&)':
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx:881:41: error: invalid conversion from 'CSLConstList' {aka 'const char* const*'} to 'char**' [-fpermissive]
  881 |   char** papszMetadata = GDALGetMetadata(this->Impl->GDALData, domain.c_str());
      |                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         CSLConstList {aka const char* const*}
```

### Additional context

Found during testing of #542357.

The failure was previously hidden by #541085 and exposed when that was fixed in #541146.

### System metadata

 - system: `"aarch64-linux"`
 - host os: `Linux 6.18.31, NixOS, 26.11 (Zokor), 26.11.20260702.6517942`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.7`
 - nixpkgs: `/home/adam/.cache/nixpkgs-review/pr-542357-1/nixpkgs`

### Notify maintainers

@qbisi 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #542757: Build failure: vtk-9.5.2
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

Include vtk-9.5.2 in your packages, rebuild

### Can Hydra reproduce this build failure?

Hydra doesn’t try to build the package.

### Link to Hydra build job

https://hydra.nixos.org/job/nixos/unstable/nixpkgs.vtk-9.5.2.x86_64-linux/all

### Relevant log output

```console
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/kp708rl5ygn75s6w1sy53jh5jyv4i3i9-VTK-9.5.2.tar.gz
source root is VTK-9.5.2
setting SOURCE_DATE_EPOCH to timestamp 1758139347 of file "VTK-9.5.2/vtkLogo.ico"
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDI>
-- The C compiler identification is GNU 15.2.0
-- The CXX compiler identification is GNU 15.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/vdaz6sk455r8sbpi7wzaf9vlz5i9yyvx-gcc-wrapper-15.2.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/vdaz6sk455r8sbpi7wzaf9vlz5i9yyvx-gcc-wrapper-15.2.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could not use git to determine source version, using version 
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE - Success
-- Performing Test vtk_have_compiler_flag_Weverything
-- Performing Test vtk_have_compiler_flag_Weverything - Failed
-- Performing Test vtk_have_compiler_flag-CXX--wd4251
-- Performing Test vtk_have_compiler_flag-CXX--wd4251 - Failed
-- Performing Test vtk_have_compiler_flag-CXX--EHsc
-- Performing Test vtk_have_compiler_flag-CXX--EHsc - Failed
CMake Deprecation Warning at CMake/vtkWrapSettings.cmake:14 (message):
  Manually specifying `VTK_PYTHON_VERSION` is deprecated as only Python3 is
  supported.
Call Stack (most recent call first):
  CMakeLists.txt:101 (include)


-- Performing Test VTK_REQUIRE_LARGE_FILE_SUPPORT
-- Performing Test VTK_REQUIRE_LARGE_FILE_SUPPORT - Success
CMake Warning (dev) at CMake/vtkModule.cmake:2624 (cmake_parse_arguments):
  The LIBRARY_NAME_SUFFIX keyword was followed by an empty string or no value
  at all.  Policy CMP0174 is not set, so cmake_parse_arguments() will unset
  the _vtk_build_LIBRARY_NAME_SUFFIX variable rather than setting it to an
  empty string.
Call Stack (most recent call first):
  CMakeLists.txt:598 (vtk_module_build)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMake/vtkModule.cmake:2624 (cmake_parse_arguments):
  The VERSION keyword was followed by an empty string or no value at all.
  Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
  _vtk_build_VERSION variable rather than setting it to an empty string.
Call Stack (most recent call first):
```

### Additional context

_No response_

### System metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.37, NixOS, 26.05 (Yarara), 26.05.20260630.95ca1e2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.94.2
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/leha44581/.config/nix/nix.conf:/nix/store/x8j2bjf320ly1mzwpaiidda8p1nmsinp-plasma-workspace-6.6.5/etc/xdg/nix/nix.conf:/nix/store/0hw4v2j63045vf2c0hb368z9ag3byaw1-kglobalacceld-6.6.5/etc/xdg/nix/nix.conf:/nix/store/9jvf866lawimzq4il3c2vjv5ikf6i6sf-baloo-6.26.0/etc/xdg/nix/nix.conf:/home/leha44581/.config/kdedefaults/nix/nix.conf:/home/leha44581/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/leha44581/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/leha44581/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/leha44581/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/leha44581/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/8irgkyajbz4wll2mny1nwln8gz4wlsis-lix-2.94.2/share`
 - nixpkgs: `/nix/store/bdn0zqq9mqdc9ccwfnamx4lax9163xr1-source`
```

### Notify maintainers

@qbisi 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by qbisi**
see also

fix build with gdal-3.13: https://gitlab.archlinux.org/archlinux/packaging/packages/vtk/-/commit/f40ada914dd594276d0c7ead63e8e33bc47105a2
do not propagate wslink: https://github.com/Kitware/wslink/pull/165#issuecomment-3769609059
propagate qttools: https://github.com/NixOS/nixpkgs/pull/536748
propagate libxcursor: https://github.com/NixOS/nixpkgs/pull/501661

some clean up before we bump vtk = vtk_9_6

nixpkgs-reviewing on my poor aarch64-linux machine.

Closes #542507 
Closes #542757

## Things done

- Built on platform:
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [x] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

File: pkgs/development/libraries/vtk/generic.nix [hunk 1]
```diff
@@ -219,6 +217,10 @@ stdenv.mkDerivation (finalAttrs: {
     libx11
     gl2ps
   ]
+  ++ lib.optionals ((lib.versionOlder finalAttrs.version "9.6.0") && stdenv.hostPlatform.isLinux) [
```
Comment (NickCao) [inline pkgs/development/libraries/vtk/generic.nix]: versionAtLeast?

Comment (qbisi) [reply pkgs/development/libraries/vtk/generic.nix]: fixed

**Comment by nixpkgs-review-gha** [comment]
## :x: `nixpkgs-review` result

Generated using [`nixpkgs-review-gha`](https://github.com/Defelo/nixpkgs-review-gha) ([`25f82fc`](https://github.com/Defelo/nixpkgs-review-gha/commit/25f82fc95ba922d5f59e31796567a510b87d7682))

Command: `nixpkgs-review pr 537721 -p python3Packages.vtk -p vtk_9_6`
Commit: [`b894a80f0e18d31b6de9cbe04c5a288161b86009`](https://github.com/NixOS/nixpkgs/commit/b894a80f0e18d31b6de9cbe04c5a288161b86009) ([subsequent changes](https://github.com/NixOS/nixpkgs/compare/b894a80f0e18d31b6de9cbe04c5a288161b86009..pull/537721/head))
Merge: [`31a42b9733a4c5d7408c5b9f9f6a70700177ed35`](https://github.com/NixOS/nixpkgs/commit/31a42b9733a4c5d7408c5b9f9f6a70700177ed35)

Triggered by @qbisi (84267544)
Logs: https://github.com/qbisi/nixpkgs-review-gha/actions/runs/29542520615/attempts/3



---
### `x86_64-linux`
<details><summary>:x: 1 package failed to build:</summary><ul>
<li>vtk_9_6</li>
</ul></details><details><summary>:white_check_mark: 1 package built:</summary><ul>
<li>python3Packages.vtk</li>
</ul></details>

---
### `aarch64-linux`
<details><summary>:x: 1 package failed to build:</summary><ul>
<li>vtk_9_6</li>
</ul></details><details><summary>:white_check_mark: 1 package built:</summary><ul>
<li>python3Packages.vtk</li>
</ul></details>

File: pkgs/development/libraries/vtk/default.nix [hunk 2]
```diff
@@ -9,10 +9,24 @@ in
...
-    version = "9.6.0";
-    sourceSha256 = "sha256-130YBpT6r9yBZXi5pTZR9nkOeZYVgRv7uRAYZho7uPI=";
+    version = "9.6.2";
+    sourceSha256 = "sha256-rtEs7BKpYJF5v2YykHAmZifKZCRKEIVqRSsqF/+wSh0=";
+    patches = [
+      (fetchpatch2 {
+        name = "gdal-3.13-const-metadata";
+        url = "https://gitlab.archlinux.org/archlinux/packaging/packages/vtk/-/raw/f40ada914dd594276d0c7ead63e8e33bc47105a2/gdal-3.13.patch";
+        hash = "sha256-tW8XbeD98jPzfWG8QVFO3gNJKYfFDcfNtjOtql2fQzw=";
+      })
```
Comment (LordGrimmauld) [inline pkgs/development/libraries/vtk/default.nix]: Why not fetch the commit from the upstream repository? https://gitlab.kitware.com/vtk/vtk/-/commit/2395603fdddc40c29efc64c632ae98225ca2a58e

File: pkgs/development/libraries/vtk/default.nix [hunk 3]
```diff
@@ -9,10 +9,24 @@ in
   vtk_9_5 = mkVtk {
     version = "9.5.2";
     sourceSha256 = "sha256-zuZLmNJw/3MC2vHvE0WN/11awey0XUdyODX399ViyYk=";
+    patches = [
+      (fetchpatch2 {
+        name = "gdal-3.13-const-metadata";
+        url = "https://gitlab.archlinux.org/archlinux/packaging/packages/vtk/-/raw/f40ada914dd594276d0c7ead63e8e33bc47105a2/gdal-3.13.patch";
+        hash = "sha256-tW8XbeD98jPzfWG8QVFO3gNJKYfFDcfNtjOtql2fQzw=";
+      })
```
Comment (LordGrimmauld) [inline pkgs/development/libraries/vtk/default.nix]: see above

**Review by LordGrimmauld — CHANGES_REQUESTED** [review]
There also seems to be a build failure of `vtk_9_6`:

```
vtk> CMake Error at /nix/store/4xbpqb1b2xkb4h8c6dzbm3yygc28bi02-python3.14-openusd-26.05/cmake/pxrTargets.cmake:42 (message):
vtk>   Some (but not all) targets in this export set were already defined.
vtk>
vtk>   Targets Defined: pegtl
vtk>
vtk>   Targets not yet defined: usd_m, boost, python, arch, tf, gf, js, trace,
vtk>   work, plug, vt, ts, ar, kind, sdf, sdr, pcp, usd, usdGeom, usdVol,
vtk>   usdMedia, usdShade, usdLux, usdProc, usdRender, usdHydra, usdRi,
vtk>   usdSemantics, usdSkel, usdUI, usdUtils, usdPhysics, usdAbc, usdDraco,
vtk>   sdrOsl, usdShaders, vdf, ef, esf, esfUsd, exec, execUsd, execGeom, execIr,
vtk>   usdValidation, usdGeomValidators, usdPhysicsValidators, usdShadeValidators,
vtk>   usdSkelValidators, usdUtilsValidators, garch, hf, hio, cameraUtil, pxOsd,
vtk>   geomUtil, glf, hgi, hgiGL, hgiInterop, hd, hdar, hdGp, hdsi, hdSt, hdx,
vtk>   hdStorm, hdEmbree, hioOpenEXR, hioAvif, usdImaging, usdImagingGL,
vtk>   usdProcImaging, usdSkelImaging, usdVolImaging, usdAppUtils, usdviewq,
vtk>   sdrGlslfx
vtk>
vtk> Call Stack (most recent call first):
vtk>   /nix/store/4xbpqb1b2xkb4h8c6dzbm3yygc28bi02-python3.14-openusd-26.05/pxrConfig.cmake:122 (include)
vtk>   CMake/vtkModule.cmake:5394 (find_package)
vtk>   IO/USD/CMakeLists.txt:4 (vtk_module_find_package)
```

Not sure what that is all about. `vtk_9_5` is fine, likely because it doesn't do `openusd` yet.

File: pkgs/development/libraries/vtk/default.nix (hunk 2 above)
Comment (qbisi) [reply pkgs/development/libraries/vtk/default.nix]: (fetchpatch2 {
        name = "gdal-3.13-const-metadata";
        url = "https://gitlab.kitware.com/vtk/vtk/-/commit/2395603fdddc40c29efc64c632ae98225ca2a58e.patch";
        hash = "";
      })
      
      this patch url is protected by Anubis, hence can not be fetched

**Comment by qbisi** [comment]
vtk_9_6 still broken due to namespace collision with openusd, vtk patched the openusd source,
https://gitlab.kitware.com/vtk/vtk/-/blob/master/.gitlab/ci/docker/fedora42/install_openusd.sh#L28-L31

see also openusd discussion
https://github.com/PixarAnimationStudios/OpenUSD/issues/3914

I will open another pr fix this

File: pkgs/development/libraries/vtk/default.nix (hunk 2 above)
Comment (LordGrimmauld) [reply pkgs/development/libraries/vtk/default.nix]: It may make sense to shoot them an email about anubis blocking nixpkgs user agent. In the meantime, vendoring the patch is probably fine. I'd always prefer an upstream patch over some arch patch, also because upstream patch will certainly fail to apply once we update, and some random downstream patch may not (though here it would)

File: pkgs/development/libraries/vtk/default.nix [hunk 4]
```diff
@@ -9,10 +8,16 @@ in
   vtk_9_5 = mkVtk {
     version = "9.5.2";
     sourceSha256 = "sha256-zuZLmNJw/3MC2vHvE0WN/11awey0XUdyODX399ViyYk=";
+    patches = [
+      ./gdal-3.13-const-metadata.patch
```
Comment (LordGrimmauld) [inline pkgs/development/libraries/vtk/default.nix]:
```suggestion
      # https://gitlab.kitware.com/vtk/vtk/-/commit/2395603fdddc40c29efc64c632ae98225ca2a58e
      # compatibility with gdal 3.13. Vendored because anubis blocks the nixpkgs fetcher
      ./gdal-3.13-const-metadata.patch
```
A comment for why this patch is here and where we got it would be nice (same for the 9.6 version)

**Review by LordGrimmauld — CHANGES_REQUESTED** [review]
Other than this, lgtm. Will merge once the comments are there.

**Comment by amarshall** [comment]
VTK also has official mirror on GitHub that could be used for reliable fetchpatch https://github.com/Kitware/VTK

**Comment by nixpkgs-review-gha** [comment]
## :x: `nixpkgs-review` result

Generated using [`nixpkgs-review-gha`](https://github.com/Defelo/nixpkgs-review-gha) ([`25f82fc`](https://github.com/Defelo/nixpkgs-review-gha/commit/25f82fc95ba922d5f59e31796567a510b87d7682))

Command: `nixpkgs-review pr 537721 -p python3Packages.vtk -p vtk_9_6`
Commit: [`45b0f92837b33825681279bde2f75a168e99058b`](https://github.com/NixOS/nixpkgs/commit/45b0f92837b33825681279bde2f75a168e99058b) ([subsequent changes](https://github.com/NixOS/nixpkgs/compare/45b0f92837b33825681279bde2f75a168e99058b..pull/537721/head))
Merge: [`bb84339050fb4ed414553a644c496fa0d4bcad42`](https://github.com/NixOS/nixpkgs/commit/bb84339050fb4ed414553a644c496fa0d4bcad42)

Triggered by @qbisi (84267544)
Logs: https://github.com/qbisi/nixpkgs-review-gha/actions/runs/29576757915/attempts/2



---
### `x86_64-linux`
<details><summary>:x: 1 package failed to build:</summary><ul>
<li>vtk_9_6</li>
</ul></details><details><summary>:white_check_mark: 1 package built:</summary><ul>
<li>python3Packages.vtk</li>
</ul></details>

---
### `aarch64-linux`
<details><summary>:x: 1 package failed to build:</summary><ul>
<li>vtk_9_6</li>
</ul></details><details><summary>:white_check_mark: 1 package built:</summary><ul>
<li>python3Packages.vtk</li>
</ul></details>

---
### `x86_64-darwin`
:white_check_mark: *No rebuilds*

---
### `aarch64-darwin` (sandbox = relaxed)
<details><summary>:x: 2 packages failed to build:</summary><ul>
<li>python3Packages.vtk</li>
<li>vtk_9_6</li>
</ul></details>

File: pkgs/by-name/pa/parmmg/package.nix
Comment (SuperSandro2000) [inline pkgs/by-name/pa/parmmg/package.nix:1]: The `vtk: propagate qttools` commit also contains some changes to vtk-full

Comment (qbisi) [reply pkgs/by-name/pa/parmmg/package.nix:1]: That's the side effect of propagating qttools, see https://github.com/NixOS/nixpkgs/pull/536748#issuecomment-4838778754

parmmg merely need vtk with mpi support only.

**Review by SuperSandro2000 — APPROVED** [review]
LGTM

File: pkgs/development/libraries/vtk/default.nix (hunk 4 above)
Comment (SuperSandro2000) [reply pkgs/development/libraries/vtk/default.nix]: The patch name is now speaking for itself, so this can be resolved.

**Comment by SuperSandro2000** [comment]
> vtk_9_6 still broken due to namespace collision with openusd, vtk patched the openusd source,

Good to know, that we only really fix vtk in this PR.

Maybe we should already merge it to fix freecad?

**Review by LordGrimmauld — APPROVED** [review]
