### PR TITLE
pyopengl: fix runtime shared library loading failure with 3.1.4

### LINKED ISSUE #76822: pyopengl: `from OpenGL import GL` throws error after version bump to 3.1.4
**Describe the bug**
`from OpenGL import GL` works in pyopengl 3.1.0, and doesn't with pyopengl 3.1.4.

**To Reproduce**
Contents of `shell.nix`, in nixpkgs root (tested with commit 53553286b65db0ffe192fe46417919e396a167ba):
```nix
with import ./default.nix {};
mkShell { buildInputs = [ (python3.withPackages (pp: with pp; [pyopengl])) ];
```

```
$ nix-shell
[nix-shell]$ python3
>>> from OpenGL import GL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Expected behavior**
There should be no error on importing `OpenGL.GL`.

**Additional context**
This breaks `friture`, and maybe other packages - although I didn't find packages in nixpkgs that use `python3Packages.pyopengl`.

Maintainer information:
```yaml
attribute: pyopengl
```

@FRidh

### PR DESCRIPTION
**Pull request by guibou**
This closes #76822.

pyopengl 3.1.4 introduced a new logic for shared library loading: it
tests a few combinations of library name and suffix (such as .so.X).

Our previous patch was just replacing the library name (e.g. 'glut') by
the full path to the nix store. This does not work anymore with pyopengl
3.1.4 new heuristic.

This commit just keep the behavior of pyopengl but adds the nix store
path to the list of tried paths.

I tested with `friture` which was failing at build time before this commit and is now building. I also tested `pyqtgraph` which was failing at runtime and is now working.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
commit msg should be:
```
pythonPackages.pyopengl: fix runtime shared library loading failure
```
otherwise LGTM

**Comment by guibou** [comment]
@jonringer done.

**Comment by jonringer** [comment]
this may want to be upstreamed

**Comment by guibou** [comment]
@jonringer I don't know what can be upstreamed here, but I'll think about it.

Do you think this is a blocker for this commit?

**Comment by jonringer** [comment]
this could be upstreamed:
```
    substituteInPlace OpenGL/platform/ctypesloader.py \
      --replace "filenames_to_try = []" "filenames_to_try = [name]"
```
from your comment it seems that they went away from this approach. I'm not sure how name is derived, but I'm assuming checking 1 additional item wouldn't hurt too much.

not a blocker, stuff like this happens all the time.

**Comment by jonringer** [comment]
It's taking a while to review because pyopengl is used by some heavy-weight packages, and my laptop I travel worth isn't super powerful.
```
[6/26/73 built (12 failed), 821 copied ...
```

**Comment by guibou** [comment]
Any update?

**Comment by jonringer** [comment]
sorry, there was a bunch of blocking issues with some downstream packages which made it hard to do a review

**Review by jonringer — APPROVED** [review]
diff LGTM

no regressions
```
[62 built (6 failed), 1 copied (513.2 MiB), 71.2 MiB DL]
error: build of '/nix/store/c9niqv7qhgh21hi2bplyy4by4fk9dagm-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/79154
12 package marked as broken and skipped:
cq-editor gazebo gazebo-headless gazeboSimulator.gazebo6 gazeboSimulator.gazebo6-headless gazeboSimulator.gazebo7 gazeboSimulator.gazebo7-headless python27Packages.runsnakerun python27Packages.squaremap python37Packages.spyder python38Packages.spyder spyder

5 package failed to build:
ib-controller python37Packages.rl-coach python38Packages.rl-coach salut_a_toi sasview

54 package built:
curaByDagoma cura_stable displaycal friture gnss-sdr gnuradio gnuradio-with-packages gqrx gr-ais gr-gsm gr-limesdr gr-nacl gr-osmosdr gr-rds grass impressive inspectrum kicad kicad-small kicad-unstable loxodo mavproxy metamorphose2 playonlinux plover.stable printrun python27Packages.binwalk python27Packages.pyopengl python27Packages.pyqtgraph python27Packages.pyspread python27Packages.robotframework-ride python27Packages.spyder python27Packages.wxPython python27Packages.wxPython_4_0 python37Packages.binwalk python37Packages.pyopengl python37Packages.pyqtgraph python37Packages.stytra python37Packages.wxPython_4_0 python38Packages.binwalk python38Packages.pyopengl python38Packages.pyqtgraph python38Packages.stytra python38Packages.wxPython_4_0 qradiolink qutebrowser run-scaled scyther soulseekqt torchat tribler video2midi winpdb xpra
```
