### ISSUE TITLE
Wpsoffice does not compile in NIXOS 20.09

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#98945]
**Describe the bug**
Including wpsoffice in `environment.systemPackages` will cause `nixos-rebuild` failed.

**To Reproduce**
1. Include wpsoffice in `environment.systemPackages`:
```
environment.systemPackages = with pkgs; [
...
wpsoffice
...
];
```
2. Run `nixos-rebuild boot`

A compilation error appears

**Expected behavior**
`nixos-rebuild boot` will succeed

**Screenshots**
Some last lines of the `nixos-rebuild boot` are
```
searching for dependencies of /nix/store/9dyzwddiqg9i2xl3wsfzlx7h7qn1aj12-wpsoffice-11.1.0.9505/opt/kingsoft/wps-office/office6/libmediacoder.so
  libQtCore.so.4 -> found: /nix/store/9dyzwddiqg9i2xl3wsfzlx7h7qn1aj12-wpsoffice-11.1.0.9505/opt/kingsoft/wps-office/office6/libQtCore.so.4
  libkso.so -> found: /nix/store/9dyzwddiqg9i2xl3wsfzlx7h7qn1aj12-wpsoffice-11.1.0.9505/opt/kingsoft/wps-office/office6/libkso.so
  libksolite.so -> found: /nix/store/9dyzwddiqg9i2xl3wsfzlx7h7qn1aj12-wpsoffice-11.1.0.9505/opt/kingsoft/wps-office/office6/libksolite.so
  libavcodec.so.57 -> not found!
  libavformat.so.57 -> not found!
  libavutil.so.55 -> not found!
  libswscale.so.4 -> not found!
  libswresample.so.2 -> not found!
  libSDL2-2.0.so.0 -> found: /nix/store/nn0kfq3b6z974i8gsjmvxxnmqqzyi6zp-SDL2-2.0.12/lib/libSDL2-2.0.so.0
  libc++abi.so.1 -> found: /nix/store/9dyzwddiqg9i2xl3wsfzlx7h7qn1aj12-wpsoffice-11.1.0.9505/opt/kingsoft/wps-office/office6/libc++abi.so.1
  libX11.so.6 -> found: /nix/store/5cgzrk1cyq1sr218xvjgw05z0jcyki92-libX11-1.6.8/lib/libX11.so.6
  libc++.so.1 -> found: /nix/store/9dyzwddiqg9i2xl3wsfzlx7h7qn1aj12-wpsoffice-11.1.0.9505/opt/kingsoft/wps-office/office6/libc++.so.1
builder for '/nix/store/6x4k1n7wzlpzq5wl19zqbach96kv5pry-wpsoffice-11.1.0.9505.drv' failed with exit code 1
cannot build derivation '/nix/store/pqmvi5q8dxamgw6ngw2mmzi6ykfbp4qh-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zfqmkxpfj0wm3f8ml31wrgklx174xlpp-nixos-system-perseus-20.09beta482.b0a587f2efc.drv': 1 dependencies couldn't be built
error: build of '/nix/store/zfqmkxpfj0wm3f8ml31wrgklx174xlpp-nixos-system-perseus-20.09beta482.b0a587f2efc.drv' failed
```

**Additional context**
I'm using the `boot.kernelPackages = pkgs.linuxPackages_latest;` to use kernel 5.8.11 (in order to use the thinkpad x1 yoga sound card)

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.11, NixOS, 20.09beta482.b0a587f2efc (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09"`
 - channels(astrojhgu): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
This should be fixed now, the change should hit the channels soon.
