### ISSUE TITLE
rtl88x2bu fails to compile with kernel 5.10, 5.11

### ISSUE THREAD

**Issue by pmahoney** [NixOS/nixpkgs#116315]
## Issue description

With this in `/etc/nixos/configuration.nix`:

```
  boot.kernelPackages = pkgs.linuxPackages_5_11;

  boot.extraModulePackages = [
    # asus usb wifi
    config.boot.kernelPackages.rtl88x2bu
  ]
```

I get compilation errors similar to https://github.com/NixOS/nixpkgs/issues/107829

## Fix

I was able to get things compiling (and WiFi working) by bumping the version and applying https://github.com/cilynx/rtl88x2bu/pull/132

```
  boot.kernelPackages = pkgs.linuxPackages_5_11;

  boot.extraModulePackages = [
    # asus usb wifi
    (config.boot.kernelPackages.rtl88x2bu.overrideAttrs (attrs: with pkgs; rec {
      name = "rtl88x2bu-${version}";
      version = "unstable-2021-01-20";
      src = fetchFromGitHub {
        owner = "cilynx";
        repo = "rtl88x2BU";
        # branch 5.6.1.6_35492.20191025_COEX20180928-6a6a @ 2021-01-20
        rev = "28b98b018a4a83059f10439b79fb5a2f98b618f6";
        sha256 = "077shn3na6spkr7qanrwmm2qyqsddxsxzbxnck3x2ijssnbbk6j3";
      };
      patches = [
        (fetchpatch {
          url = "https://github.com/cilynx/rtl88x2bu/pull/132.patch";
          sha256 = "0gbznxnwm517jsh3c1njb4qbxd9jskqviqzg545ww217q5063h2w";
        })
      ];
    }))
  ];
```

@Ralith
