### ISSUE TITLE
Nividia Drivers with Linux 5.1 are broken

### ISSUE THREAD

**Issue by ZigTag** [NixOS/nixpkgs#61165]
## Issue description

Nividia Prop drivers appears to have a missing dependancy and is unable to build correctly with the Linux 5.1 Kernel

### Steps to reproduce

sudo nix-rebuild boot --upgrade

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.13, NixOS, 19.09pre178675.24debf74ef5 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre178846.7defc47944f"`
 - channels(falcon): `"nixos-19.09pre177249.dfd8f84aef1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ZigTag** [comment]
If anyone knows how to keep nix on 5.0.13 that would be appreciated

**Comment by vcunat** [comment]
Well, you had to explicitly override kernel version (default is 4.19 on master).  So you do i the same way in configuration.nix
```
boot.kernelPackages = pkgs.linuxPackages_5_0;
```
(there are many equivalent ways)

**Comment by MicrosoftTakeover** [comment]
Here's the tail end of the build where it errors:
```
  CC [M]  /build/kernel/nvidia-uvm/uvm8_gpu_isr.o
  CC [M]  /build/kernel/nvidia-uvm/uvm8_procfs.o
  CC [M]  /build/kernel/nvidia-uvm/uvm8_va_space.o
  CC [M]  /build/kernel/nvidia-uvm/uvm8_va_space_mm.o
/build/kernel/nvidia-uvm/uvm8.c:187:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault = uvm_vm_fault_sigbus_wrapper
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/kernel/nvidia-uvm/uvm8.c:187:14: note: (near initialization for 'uvm_vm_ops_disabled.fault')
/build/kernel/nvidia-uvm/uvm8.c:525:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault        = uvm_vm_fault_wrapper,
                     ^~~~~~~~~~~~~~~~~~~~
/build/kernel/nvidia-uvm/uvm8.c:525:21: note: (near initialization for 'uvm_vm_ops_managed.fault')
/build/kernel/nvidia-uvm/uvm8.c:526:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .page_mkwrite = uvm_vm_fault_wrapper,
                     ^~~~~~~~~~~~~~~~~~~~
/build/kernel/nvidia-uvm/uvm8.c:526:21: note: (near initialization for 'uvm_vm_ops_managed.page_mkwrite')
/build/kernel/nvidia-uvm/uvm8.c:609:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .fault        = uvm_vm_fault_sigbus_wrapper,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/kernel/nvidia-uvm/uvm8.c:609:21: note: (near initialization for 'uvm_vm_ops_semaphore_pool.fault')
cc1: some warnings being treated as errors
make[3]: *** [/nix/store/pkkqci7dx8iribbxy113l0q0sgwirp3x-linux-5.1-dev/lib/modules/5.1.0/source/scripts/Makefile.build:276: /build/kernel/nvidia-uvm/uvm8.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/nix/store/pkkqci7dx8iribbxy113l0q0sgwirp3x-linux-5.1-dev/lib/modules/5.1.0/source/Makefile:1571: _module_/build/kernel] Error 2
make[2]: Leaving directory '/nix/store/pkkqci7dx8iribbxy113l0q0sgwirp3x-linux-5.1-dev/lib/modules/5.1.0/build'
make[1]: *** [Makefile:169: sub-make] Error 2
make[1]: Leaving directory '/nix/store/pkkqci7dx8iribbxy113l0q0sgwirp3x-linux-5.1-dev/lib/modules/5.1.0/source'
make: *** [Makefile:79: modules] Error 2
builder for '/nix/store/aqhsq692zhyxjd53v1ddgiqd3qhnqbi2-nvidia-x11-418.56-5.1.drv' failed with exit code 2
cannot build derivation '/nix/store/95dyl3w9dbn1wk51dbyq6kchnvbvg7zi-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3a54ihp9jxl498p8frdrgz0g83n8x2np-kernel-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hjzp48gvd33whb6q971gfj663n18zvr7-linux-5.1-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/a1p6nbizgvh3cg8az9cvh01ws3q5xmym-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/miw0i8rj5jcyzwrk28saqp3jjqgcam9i-nixos-system-nixos-workstation-19.09pre178846.7defc47944f.drv': 1 dependencies couldn't be built
error: build of '/nix/store/miw0i8rj5jcyzwrk28saqp3jjqgcam9i-nixos-system-nixos-workstation-19.09pre178846.7defc47944f.drv' failed
```

**Comment by ambrop72** [comment]
The vm_fault errors are due to: https://github.com/torvalds/linux/commit/3d3539018d2cbd12e5af4a132636ee7fd8d43ef0
After this fix there are errors due to: https://github.com/torvalds/linux/commit/fcd70cd36b9bf697122538c9e38e8cf954b2342b
I'm currently testing a fix that I made on my own.

**Comment by ambrop72** [comment]
I tried to patch this, but given the amount of patching that would be needed, I think it would be better to add driver 418.73 which works fine with kernel 5.1. It is trivial to update, I updated it locally and don't see problems.

**Comment by ambrop72** [comment]
Sorry I got confused, didn't know we were already at 418.56. We just need to update to 418.74, I'll make a PR.

**Comment by gloaming** [comment]
418.74 was added in https://github.com/NixOS/nixpkgs/pull/61164 and we are now on 430.26

Does that resolve the issue?

**Comment by vcunat** [comment]
I believe so.  `linuxPackages_5_1.nvidia_x11` builds for me now, and even the 5.2 RC as well.
