### PR TITLE
FreeBSD packages: Init at 13.1

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Have working
```sh
nix-build -A pkgsCross.x86_64-freebsd.hello
nix-build -A pkgsCross.x86_64-freebsd.zlib
nix-build -A pkgsCross.x86_64-freebsd.zstd
nix-build -A pkgsCross.x86_64-freebsd.freebsd.sys
```

~~Running out of memory as NetBSD `makeMinimal` fails to build. Weird, know what's up @matthewbauer?~~

Oh netbsd make is cached, duh, this is freebsd libc itself.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

CC @wahjava

### CODE REVIEW

File: lib/systems/examples.nix [hunk 1]
```diff
@@ -228,11 +228,26 @@ rec {
...
 
-  amd64-netbsd = {
+  x86_64-freebsd = {
+    config = "x86_64-unknown-freebsd";
+    libc = "freebsd";
+    useLLVM = true;
+  };
+
+  # Deprecate
+  amd66-netbsd = x86_64-netbsd;
```
Comment (vcunat) [inline lib/systems/examples.nix]: Should this be `amd64-netbsd`?

Comment (Ericson2314) [reply lib/systems/examples.nix]: Haha yes

File: pkgs/os-specific/bsd/freebsd/default.nix [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+, splicePackages, buildPackages
+, fetchsvn, lib, groff, mandoc, zlib, yacc, flex
+, writeText, symlinkJoin
+}:
+
+let
+  version = "12";
+
+  fetchFreeBSD = path: sha256: fetchsvn {
+    url = "https://svn.freebsd.org/base/stable/${version}/${path}";
```
Comment (wahjava) [inline pkgs/os-specific/bsd/freebsd/default.nix]: `stable` branch [may not be](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/current-stable.html) stable. You can use [one of the releng branch](https://svnweb.freebsd.org/base/releng/12.1/) to track released code. Also you might want to stick to a particular svn revision, and not HEAD

**Comment by Ericson2314** [comment]
I dropped link to this in https://forums.freebsd.org/threads/can-i-compile-a-freebsd-kernel-from-linux.64582/, a that is vaguely relevant.

**Comment by Ericson2314** [comment]
OK need to fix makefiles or bmake itself so non-default system rules `-m` propagate to recursive make---probably easiest thing to add an environment variable to bmake for this.

File: pkgs/os-specific/bsd/freebsd/default.nix (hunk 2 above)
Comment (Ericson2314) [reply pkgs/os-specific/bsd/freebsd/default.nix]: Thanks!

File: pkgs/top-level/all-packages.nix [hunk 3]
```diff
@@ -10496,6 +10490,17 @@ in
...
   };
 
+  # This is for e.g. LLVM libraries on linux.
+  gccForLibs =
+    # with gcc-7: undefined reference to `__divmoddi4'
+    if stdenv.targetPlatform.isi686
+      then gcc6.cc
+    else if stdenv.targetPlatform == stdenv.hostPlatform && targetPackages.stdenv.cc.isGNU
+	  # Can only do this is in the native case, otherwise we might get infinite
+	  # recursion if `targetPackages.stdenv.cc.cc` itself uses `gccForLibs`.
```
Comment (SuperSandro2000) [inline pkgs/top-level/all-packages.nix:10500]: Mixing tabs and spaces.

File: pkgs/os-specific/bsd/freebsd/default.nix [hunk 4]
```diff
@@ -0,0 +1,287 @@
+{ stdenv, lib, stdenvNoCC
+, pkgsBuildBuild, pkgsBuildHost, pkgsBuildTarget, pkgsHostHost, pkgsHostTarget, pkgsTargetTarget
+, buildPackages
+, bsdSetupHook, fetchsvn, fetchurl, groff, mandoc, yacc, flex
```
Comment (SuperSandro2000) [inline pkgs/os-specific/bsd/freebsd/default.nix:4]: yacc is bison now.

**Comment by alyssais** [comment]
Let's maybe change the title of this now, since NetBSD cross is already fixed?

**Comment by alyssais** [comment]
This is also going to have to target staging because of all the NetBSD rebuilds on Darwin.

File: pkgs/os-specific/bsd/netbsd/default.nix [hunk 5]
```diff
@@ -38,12 +29,12 @@ let
 
     extraPaths = [ ];
 
-    nativeBuildInputs = [
+    nativeBuildInputs = with buildPackages.netbsd; [
       bsdSetupHook netbsdSetupHook
-      makeMinimal install tsort lorder mandoc groff statHook
+      makeMinimal
+      install tsort lorder mandoc groff statHook
```
Comment (sternenseemann) [inline pkgs/os-specific/bsd/netbsd/default.nix:40]: A bit of a nitpick, but this is a bit of a scoping mess with thing explicitly coming from `buildPackages.netbsd` and stuff like `mandoc` coming from the expressions inputs (and thus implicitly from `buildPackages`).

 This is mostly about readabilty, I was a bit confused about this for half a minute.

Also applies to FreeBSD's `mkDerivation`.

File: pkgs/os-specific/bsd/netbsd/default.nix [hunk 6]
```diff
@@ -453,39 +447,35 @@ let
...
-      PATH="${buildPackages.netbsd.rpcgen}/bin:$PATH"
-    '';
-    extraPaths = [ common.src ];
+    extraPaths = with netbsd; [ common.src ];
     headersOnly = true;
     noCC = true;
-    # meta.platforms = lib.platforms.netbsd;
-    makeFlags = [ "RPCGEN_CPP=${buildPackages.gcc-unwrapped}/bin/cpp" ];
+    meta.platforms = lib.platforms.netbsd;
+    makeFlags = [ "RPCGEN_CPP=${buildPackages.stdenv.cc.cc}/bin/cpp" ];
```
Comment (sternenseemann) [inline pkgs/os-specific/bsd/netbsd/default.nix:468]: Wouldn't just `stdenv` be sufficient or correcter here? Or do buildPackages.stdenv.cc.cc and stdenv.cc.cc have the same effective hostPlatform they run on?

Comment (Ericson2314) [reply pkgs/os-specific/bsd/netbsd/default.nix:468]: At this point we don't yet have a CPP for the right stage, so we awkwardly use the previous stage's.

Comment (sternenseemann) [reply pkgs/os-specific/bsd/netbsd/default.nix:468]: I see, thanks for the clarification.

File: pkgs/os-specific/bsd/freebsd/default.nix [hunk 7]
```diff
@@ -0,0 +1,347 @@
...
+    path = "usr.bin/lorder";
+    sha256 = "07zzaxlxvlxgmj4c5wcn2m58b68j95q9qsz8x0jvjhqc7pjgyb0b";
+    noCC = true;
+    dontBuild = true;
+    installPhase = ''
+      mkdir -p "$out/bin" "$man/share/man"
+      mv "$BSDSRCDIR/${path}/lorder.sh" "$out/bin/lorder"
+      chmod +x "$out/bin/lorder"
+      mv "$BSDSRCDIR/${path}/lorder.1" "$man/share/man"
+      exit 0;
```
Comment (SuperSandro2000) [inline pkgs/os-specific/bsd/freebsd/default.nix:156]: ?

Comment (Ericson2314) [reply pkgs/os-specific/bsd/freebsd/default.nix:156]: Oh this is WIP as hell and full of old garbage and half-done rebases.

**Comment by L-as** [comment]
What is blocking this?

**Comment by Ericson2314** [comment]
I suppose we could merge soon, but it doesn't yet work. See netbsd. There are a lot of things to package before one gets to hello world.

**Comment by sash-kan** [comment]
i tried to build "hello" from this branch: https://github.com/Ericson2314/nixpkgs/tree/bsd-cross
and got an error from bmake:
```
$ nix-build . -A pkgsCross.x86_64-freebsd.hello
...
make[1]: "/nix/store/j4z7lyxrn29lzibfykg24d2plfwq1nfg-bmake-freebsd-13.0.0/share/mk/src.libnames.mk" line 701: /build/libc-freebsd-filtered-src/lib/msun: Missing or incorrect value for LIBMDIR in src.libnames.mk: lib/msun
make: "/build/libc-freebsd-filtered-src/lib/libc/Makefile" line 197: warning: "make MK_MAKE_CHECK_USE_SANDBOX=yes -B -C ../../lib/msun -V ARCH_SUBDIR" returned non-zero status
make: make: don't know how to make asctime.c. Stop
make: stopped in /build/libc-freebsd-filtered-src/lib/libc
error: builder for '/nix/store/w5z1a58lcd23miyjw5z7lrg6phplrp88-libc-x86_64-unknown-freebsd-13.0.0.drv' failed with exit code 2;
```

**Comment by sash-kan** [comment]
the problem is that the [variable `SRCTOP`](https://github.com/Ericson2314/nixpkgs/blob/0c7af40f0d3663ccf6c6bb1cf6d9ba7cb51c5c25/pkgs/os-specific/bsd/freebsd/default.nix#L518) is substituted only when calling bmake for [`path`](https://github.com/Ericson2314/nixpkgs/blob/0c7af40f0d3663ccf6c6bb1cf6d9ba7cb51c5c25/pkgs/os-specific/bsd/freebsd/default.nix#L503).
and for [`extrapaths`](https://github.com/Ericson2314/nixpkgs/blob/0c7af40f0d3663ccf6c6bb1cf6d9ba7cb51c5c25/pkgs/os-specific/bsd/freebsd/default.nix#L504-L511) it remains empty.

**Comment by Ericson2314** [comment]
@sash-kan thanks for looking into this!!

**Comment by Ericson2314** [comment]
current error:
```
rpc_scan.c: In function 'get_token':
rpc_scan.c:169:66: error: 'WUNTRACED' undeclared (first use in this function)
  169 |                                         waitpid(childpid, &stat, WUNTRACED);
      |                                                                  ^~~~~~~~~
```
I don't get this because if I go in a nix shell `WUNTRACED` is defined:
```bash
nix-shell . -A pkgsCross.x86_64-freebsd.buildPackages.freebsd.rpcgen
```
```bash
echo -e '#include <sys/wait.h>\nWUNTRACED' | $CC -E -x c - | tail
```

**Comment by Ericson2314** [comment]
current error:
```
rpc_scan.c: In function 'get_token':
rpc_scan.c:169:66: error: 'WUNTRACED' undeclared (first use in this function)
  169 |                                         waitpid(childpid, &stat, WUNTRACED);
      |                                                                  ^~~~~~~~~
```
I don't get this because if I go in a nix shell `WUNTRACED` is defined:
```bash
nix-shell . -A pkgsCross.x86_64-freebsd.buildPackages.freebsd.rpcgen
```
```bash
echo -e '#include <sys/wait.h>\nWUNTRACED' | $CC -E -x c - | tail
```

**Comment by Ericson2314** [comment]
Next problem: I think the headers need to be built separately, like NetBSD.

**Comment by Ericson2314** [comment]
I can build hello and zlib now!!!

**Comment by Ericson2314** [comment]
It's messy (e.g. need to sync changes between LLVM versions) but it works! Have at it, y'all!

**Comment by Ericson2314** [comment]
Temporary changing the target branch so we get smaller change until `staging` hits `master`.

File: pkgs/os-specific/bsd/freebsd/default.nix (hunk 7 above)
Comment (Ericson2314) [reply pkgs/os-specific/bsd/freebsd/default.nix]: Fixed.

**Comment by Ericson2314** [comment]
The kernel builds!

File: pkgs/os-specific/bsd/xargs-j.sh [hunk 8]
```diff
@@ -0,0 +1,17 @@
+#! @shell@
+
+declare -a args=()
+
+token=$1
+shift
+
+while (( $# )); do
+    if [[ "$1" = "$token" ]]; then
+		mapfile -t -O $(("${#args[@]}" + 1)) args
```
Comment (SuperSandro2000) [inline pkgs/os-specific/bsd/xargs-j.sh:10]: You are mixing tabs and spaces here

File: pkgs/os-specific/bsd/xargs-j.sh [hunk 9]
```diff
@@ -0,0 +1,17 @@
...
+    else
+        args+=("$1")
+    fi
+    shift
+done
+
+"${args[@]}"
```
Comment (SuperSandro2000) [inline pkgs/os-specific/bsd/xargs-j.sh:17]:
```suggestion
exec "${args[@]}"
```

File: pkgs/os-specific/bsd/freebsd/default.nix [hunk 10]
```diff
@@ -120,6 +120,9 @@ in lib.makeScopeWithSplicing
 
     HOST_SH = stdenv'.shell;
 
+    # Since STRIP below is the flag
+    STRIPBIN="${stdenv.cc.bintools.targetPrefix}strip";
```
Comment (SuperSandro2000) [inline pkgs/os-specific/bsd/freebsd/default.nix:124]:
```suggestion
    STRIPBIN = "${stdenv.cc.bintools.targetPrefix}strip";
```

**Comment by pbsds** [comment]
I tried building `github:Ericson2314/nixpkgs/bsd-cross#pkgsCross.x86_64-freebsd.hello` on a arch machine without sandboxing enabled, and got some _interesting_ output:

```
...
compat> rm: cannot remove '/usr/bin/ppmtopjxl': Permission denied
compat> rm: cannot remove '/usr/bin/nvidia-cuda-mps-control': Permission denied
compat> rm: cannot remove '/usr/bin/weston-simple-shm': Permission denied
compat> rm: cannot remove '/usr/bin/pamdice': Permission denied
compat> rm: cannot remove '/usr/bin/eqn2graph': Permission denied
compat> rm: cannot remove '/usr/bin/curl': Permission denied
compat> rm: cannot remove '/usr/bin/gsdj': Permission denied
...
```

It seems like it tried to clean the `/usr/bin` directory on host the machine

**Comment by SuperSandro2000** [comment]
> on a arch machine without sandboxing enabled, and got some _interesting_ output:

Is this required for *bsd's somehow because at this point we mostly ignore errors without sandboxing enabled.

File: pkgs/development/compilers/llvm/12/compiler-rt/default.nix [hunk 11]
```diff
@@ -91,6 +93,8 @@ stdenv.mkDerivation {
     ln -s $out/lib/*/clang_rt.crtend-*.o $out/lib/crtend.o
     ln -s $out/lib/*/clang_rt.crtbegin_shared-*.o $out/lib/crtbeginS.o
     ln -s $out/lib/*/clang_rt.crtend_shared-*.o $out/lib/crtendS.o
+  '' + lib.optionalString (doFakeLibgcc) ''
+    ln -s $out/lib/freebsd/libclang_rt.builtins-*.a $out/lib/libgcc.a
```
Comment (7c6f434c) [inline pkgs/development/compilers/llvm/12/compiler-rt/default.nix:97]: Hm, does that mean `doFakeLibgcc` only works on FreeBSD?

Comment (Ericson2314) [reply pkgs/development/compilers/llvm/12/compiler-rt/default.nix:97]: It is just used for FreeBSD right now. I wish we didn't have to do this but the FreeBSD Clang frontend just has these sorts of things hard-coded because that's how FreeBSD currently bootstrap things.

The larger issue is the "OS" field of the target name really has nebulous meaning (is it the syscall ABI, the libc ABI, something more? etc.) and so we get these postels law gone wrong situations of people hacking in ad-hoc special cases to get things working that just cause extra headache for something like Nixpkgs where we rather do all the combinations as uniformly as possible.

**Review by 9glenda — APPROVED** [review]

**Comment by 9glenda** [comment]
Great work

File: pkgs/os-specific/bsd/freebsd/default.nix [hunk 12]
```diff
@@ -0,0 +1,900 @@
...
+
+  install-wrapper = ''
+    set -eu
+
+    args=()
+    declare -i path_args=0
+
+    while (( $# )); do
+      if (( $# == 1 )); then
+        if (( $path_args > 1)) || [[ "$1" = */ ]]; then
```
Comment (9glenda) [inline pkgs/os-specific/bsd/freebsd/default.nix:52]: In bash the first `$` is not needed here.

Comment (9glenda) [reply pkgs/os-specific/bsd/freebsd/default.nix:52]: If this is supposed to be a posix shell script (I assume it's bash) it is not posix compliant

File: pkgs/os-specific/bsd/freebsd/default.nix [hunk 13]
```diff
@@ -0,0 +1,900 @@
...
+    postInstall = lib.optionalString (!stdenv.targetPlatform.isFreeBSD) ''
+      boot_mk=$BSDSRCDIR/tools/build/mk
+      cp $boot_mk/Makefile.boot* $out/share/mk
+      replaced_mk=$out/share/mk.orig
+      mkdir $replaced_mk
+      mv $out/share/mk/bsd.{lib,prog}.mk $replaced_mk
+      for m in bsd.{lib,prog}.mk; do
+        cp $boot_mk/$m $out/share/mk
+        substituteInPlace $out/share/mk/$m --replace '../../../share/mk' '../mk.orig'
+      done
```
Comment (9glenda) [inline pkgs/os-specific/bsd/freebsd/default.nix:214]: Generally you should double quote (`"`) variables to prevent word splitting and globbing

**Review by 9glenda — COMMENTED** [review]
I took a quick look at the shell code. It's nothing that bad just really small "mistakes"

**Comment by 9glenda** [comment]
https://github.com/Ericson2314/nixpkgs/pull/1
I implemented the changes myself and opened a PR

**Comment by Ericson2314** [comment]
OK I synced the LLVM changes across all the versions. I think this is basically ready to go!

File: lib/systems/parse.nix [hunk 14]
```diff
@@ -290,7 +290,11 @@ rec {
     # the normalized name for macOS.
     macos    = { execFormat = macho;   families = { inherit darwin; }; name = "darwin"; };
     ios      = { execFormat = macho;   families = { inherit darwin; }; };
-    freebsd  = { execFormat = elf;     families = { inherit bsd; }; };
+    # A tricky thing about FreeBSD is that there is no stable ABI across
+    # versions. That means that putting in the version as part of the
+    # config string is paramount.
+    freebsd12 = { execFormat = elf;     families = { inherit bsd; }; name = "freebsd"; version = 12; };
+    freebsd13 = { execFormat = elf;     families = { inherit bsd; }; name = "freebsd"; version = 13; };
```
Comment (sternenseemann) [inline lib/systems/parse.nix:297]: IIRC Nix's configure script makes a point of stripping version information from system doubles, so it might be impossible to get such a double as `builtins.currentSystem`.

Comment (Ericson2314) [reply lib/systems/parse.nix:297]: You and @alyssais should work that out :) I am not sure what is more correct. If what we have is more correct, that is fine with me we can worry about native compilation later! :D

**Comment by kirillrdy** [comment]
Hi, firstly thank you for all the effort that was put into this MR !

unfortunately when i try

`nix-build -A pkgsCross.x86_64-freebsd.hello`

I get 

```
building '/nix/store/ffa2r42x74j5mfsvkymj9s74w114kqyr-stdenv-linux.drv'...
remote: Enumerating objects: 91213, done.
remote: Counting objects: 100% (91213/91213), done.
remote: Compressing objects: 100% (78514/78514), done.
error: RPC failed; curl 56 OpenSSL SSL_read: error:0A000119:SSL routines::decryption failed or bad record mac, errno 0
error: 5347 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
remote: Enumerating objects: 91213, done.
remote: Counting objects: 100% (91213/91213), done.
remote: Compressing objects: 100% (78514/78514), done.
```

can someone double check that this builds for others ? just so I know if there is something with my setup

**Comment by kirillrdy** [comment]
hi, actually i found the answer,  something is broken with ssl on master, i've rebuild my nixos from previous well known configuration and now it seems to be building

**Comment by Mic92** [comment]
Is c++ known to work? I just tried cross-compiling patchelf in the patchelf repo and got this:

```
x86_64-unknown-freebsd13-ld: error: undefined symbol: _Unwind_Resume
>>> referenced by patchelf.cc:0
>>>               patchelf.o:(getElfType(std::__1::shared_ptr<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&))
>>> referenced by patchelf.cc:0
>>>               patchelf.o:(error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))
>>> referenced by new:0 (/nix/store/qbbik1n6qmmbwhc74fv9czm8qy21cmvf-libcxx-x86_64-unknown-freebsd13-12.0.1-dev/include/c++/v1/new:0)
>>>               patchelf.o:(resolveArgument(char const*))
>>> referenced 81 more times
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 9glenda** [comment]
Finally this is merged

**Comment by Ericson2314** [comment]
@Mic92 I built zstd and it worked so some C++ does, I thought.

**Comment by 9glenda** [comment]
This pr just adds cross compilation support right? Or does it also add support for building the FreeBSD kernel on FreeBSD in case you get nix running there?

**Comment by Ericson2314** [comment]
@9glenda only cross compilation support, but I did cross compile the kernel too!

**Comment by Ericson2314** [comment]
My next stop would try to be NetBSD and FreeBSD in https://github.com/cleverca22/not-os. I think just using Nix on FreeBSD will actually be harder because modern FreeBSD once to mandate that all syscalls go through the same userland libc --- either we rebuild the entire userland with Nix, or we do impurities.

**Comment by Mic92** [comment]
It seems that with certain c++ features (i.e. c++17), you need libunwind linked as well.

This is what I added for patchelf to get it working:

```
  buildInputs = [ llvmPackages.libunwind ];
  NIX_LDFLAGS = "-lunwind";
```

Probably the macOS version already has something implemented?

File: pkgs/development/compilers/llvm/10/default.nix [hunk 15]
```diff
@@ -156,7 +156,7 @@ let
         echo "-B${targetLlvmLibraries.compiler-rt}/lib" >> $out/nix-support/cc-cflags
       '' + lib.optionalString (!stdenv.targetPlatform.isWasm) ''
         echo "--unwindlib=libunwind" >> $out/nix-support/cc-cflags
-      '' + lib.optionalString (!stdenv.targetPlatform.isWasm && stdenv.targetPlatform.useLLVM or false) ''
+      '' + lib.optionalString (!stdenv.targetPlatform.isWasm && !stdenv.targetPlatform.isFreeBSD && stdenv.targetPlatform.useLLVM or false) ''
```
Comment (Ericson2314) [inline pkgs/development/compilers/llvm/10/default.nix:159]: @Mic92 I guess changes like this are adding the problem? But it also didn't work without. Hmm.

Comment (sternenseemann) [reply pkgs/development/compilers/llvm/10/default.nix:159]: Yeah, this seems wrong as we are doing ` useLLVM`

Comment (Ericson2314) [reply pkgs/development/compilers/llvm/10/default.nix:159]: Well forcing `-lunwind` is a sledgehammer I am skeptical enough, and it was causing failures even if its absense was also causing failures. I think it would be good to figure out why this was needed in the first place.
