### ISSUE TITLE
OpenSP fails to build on Darwin 10.10

### ISSUE THREAD

**Issue by wolverian** [NixOS/nixpkgs#4689]
This is unfortunate because `git` depends on it.

~~~
gcc -c -DLOCALEDIR=\"/nix/store/0p5ya14ch65mj383nadhanzyrlwwlzj9-opensp-1.5.2/share/locale\" -DLOCALE_ALIAS_PATH=\"/nix/store/0p5ya14ch65mj383nadhanzyrlwwlzj9-opensp-1.5.2/share/locale\" -DLIBDIR=\"/nix/store/0p5ya14ch65mj383nadhanzyrlwwlzj9-opensp-1.5.2/lib\" -DIN_LIBINTL -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/nix/store/0p5ya14ch65mj383nadhanzyrlwwlzj9-opensp-1.5.2/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libintl_set_relocation_prefix -Drelocate=libintl_relocate -DDEPENDS_ON_LIBICONV=1 -DHAVE_CONFIG_H -I. -I. -I.. -I/System/Library/Frameworks/CoreFoundation.framework/Headers -g -O2  langprefs.c
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/dispatch/dispatch.h:51:0,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from langprefs.c:30:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/dispatch/object.h:143:15: error: expected identifier or '(' before '^' token
 typedef void (^dispatch_block_t)(void);
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/dispatch/object.h:362:3: error: unknown type name 'dispatch_block_t'
   dispatch_block_t notification_block);
   ^
make[2]: *** [langprefs.o] Error 1
make[2]: Leaving directory `/private/var/folders/tb/fd9m19v57dl0tyvnb66wgw_h0000gn/T/nix-build-opensp-1.5.2.drv-0/OpenSP-1.5.2/intl'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/private/var/folders/tb/fd9m19v57dl0tyvnb66wgw_h0000gn/T/nix-build-opensp-1.5.2.drv-0/OpenSP-1.5.2'
make: *** [all] Error 2
builder for ‘/nix/store/47lwvadrkl0ddv9iqn42zgjxs15i31zd-opensp-1.5.2.drv’ failed with exit code 2
~~~

This is with:

~~~
% cc --version
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
% gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
% uname -a
Darwin blindsight.local 14.0.0 Darwin Kernel Version 14.0.0: Tue Sep 23 23:01:41 PDT 2014; root:xnu-2782.1.97~6/RELEASE_X86_64 x86_64
~~~

**Comment by blast-hardcheese** [comment]
+1

**Comment by blast-hardcheese** [comment]
Apparently, a workaround is to point your `NIX_PATH` at a clone of https://github.com/joelteon/nixpkgs

When I need to build something that needs OpenSP, I run:
`export NIX_PATH='nixpkgs=/Users/blast/Projects/nix/ynixpkgs'`, where ynixpkgs is an up-to-date clone of @joelteon's repo.

**Comment by gridaphobe** [comment]
@joelteon's fork has been merged into master, so this should be fixed.
