### PR TITLE
anki: 2.1.11 -> 2.1.14

### PR DESCRIPTION
**Pull request by averelld**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build anki

**Comment by mmahut** [comment]
Fails to rebuild on ``darwin``:

```In file included from /private/tmp/nix-build-qtwebengine-5.11.3.drv-0/qtwebengine-everywhere-src-5.11.3/src/3rdparty/chromium/base/mac/mac_util.mm:23:
/private/tmp/nix-build-qtwebengine-5.11.3.drv-0/qtwebengine-everywhere-src-5.11.3/src/3rdparty/chromium/base/mac/sdk_forward_declarations.h:51:3: error: redefinition of enumerator 'NSSpringLoadingHighlightEmphasized'
  NSSpringLoadingHighlightEmphasized```

**Comment by averelld** [comment]
Seems unrelated, that platform has been broken since #50379. It was merged regardless for some reason.

**Comment by mmahut** [comment]
@NixOS/darwin-maintainers do you mind having a look? If it is failing and we cannot fix it, we must exclude it.

**Review by ivan — APPROVED** [review]
Tested sync, reviews, audio playback on NixOS x86_64

**Comment by Profpatsch** [comment]
Cool, thanks.
