### PR TITLE
axis2: 1.7.9 -> 1.8.2, tomcat10: 10.0.27 -> 10.1.15, tomcat9: 9.0.75 -> 9.0.82

### PR DESCRIPTION
**Pull request by anthonyroussel**
## Description of changes

* axis2: 1.7.0 -> 1.8.2: https://github.com/apache/axis-axis2-java-core/compare/v1.7.9...v1.8.2
* tomcat10: 10.0.27 -> 10.1.15
* tomcat9: 9.0.75 -> 9.0.82
* Added NixOS test for Axis2 integration with Tomcat server

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by anthonyroussel** [comment]
@ofborg test tomcat

**Comment by trofi** [comment]
git bisect says 5b146274aef03bfc6b964d8089090d9ae050f47b `axis2: 1.7.9 -> 1.8.2` broke the `DisnixWebService` build as https://hydra.nixos.org/build/241506548:

```
    [javac] Compiling 7 source files to /build/DisnixWebService-0.10.1/bin
    [javac] /build/DisnixWebService-0.10.1/src/org/nixos/disnix/client/DisnixInterface.java:70: error: cannot find symbol
    [javac]             options.setProperty(HTTPConstants.MC_GZIP_REQUEST, Boolean.TRUE);
    [javac]                                 ^
    [javac]   symbol:   variable HTTPConstants
    [javac]   location: class DisnixInterface
```

**Comment by anthonyroussel** [comment]
> git bisect says [5b14627](https://github.com/NixOS/nixpkgs/commit/5b146274aef03bfc6b964d8089090d9ae050f47b) `axis2: 1.7.9 -> 1.8.2` broke the `DisnixWebService` build as https://hydra.nixos.org/build/241506548:
> 
> ```
>     [javac] Compiling 7 source files to /build/DisnixWebService-0.10.1/bin
>     [javac] /build/DisnixWebService-0.10.1/src/org/nixos/disnix/client/DisnixInterface.java:70: error: cannot find symbol
>     [javac]             options.setProperty(HTTPConstants.MC_GZIP_REQUEST, Boolean.TRUE);
>     [javac]                                 ^
>     [javac]   symbol:   variable HTTPConstants
>     [javac]   location: class DisnixInterface
> ```

@trofi Hello. Thanks for reporting this issue.

I've submitted an upstream patch to the DisnixWebService project to make it compatible with Axis2 1.8: https://github.com/svanderburg/DisnixWebService/pull/2
