### ISSUE TITLE
How to add further targets to rustc?

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#70238]
I am playing around with building stuff for `wasm32-unknown-unknown`. Until now I was using the https://github.com/mozilla/nixpkgs-mozilla repository, but I noticed that my experiments also work with `rustc-1.38`, so I don’t actually need nightly. I wanted to change to using nixpkgs proper, but now I get
```
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed

error: aborting due to previous error
```

With `rustup` I can do
```
rustup target add wasm32-unknown-unknown
```
but what do I have to do to get the same effect when I use `pkgs.rustPlatform.buildRustPackage`?

**Comment by TheSandwichMakr** [comment]
My impression is that the correct way is using something like `pkgs.pkgsCross.wasi32.rustc`, however you must use `pkgs.pkgsCross.wasi32.buildPackages.rustc` because wasm isn't supported in nixpkgs for rustc right now (at least I think that's why). However, that doesn't work because it's wasm32-unknown-wasi rather than wasm32-unknown-unknown (I think, it just fails on an `unwrap()`), and there's other fixes needed anyway. I have an overlay to add targets that I made before pkgsCross and just updated as I needed wasm again. I'm not sure how to convert it to the proper cross-compilation methods as wasm seems to want `rust-lld` which is included when using the included llvm, rather than the system one which is not ideal.

I also use this for building nightly, so I removed some parts. Not sure what openssl was needed for, but might as well leave it. The postUnpack may just be fixing nightly things and might even need to be removed. Emscripten can be removed, unless you want it. You may be able to build with the profiler, but I had some sort of problem at least on nightly. A lot of the preFixup is obviously unnecessary, but I smuggled out an unadulterated rust-lld when figuring out how to use it. You'll also need around 14 GiB of ram free and 12 GiB or so allocated to /tmp. 
```
  rustcStable = super.rust.packages.stable.rustc;
  rustc = (rustcStable.overrideAttrs (oldAttrs: rec {
    buildInputs = oldAttrs.buildInputs ++ [ self.pkg-config self.openssl ];
    postUnpack = ''
    ls -R $sourceRoot/src/llvm-project/compiler-rt/
    rm -r $sourceRoot/src/llvm-project/compiler-rt/
    '';
    configureFlags = let add_flags = [
      "--enable-full-tools" # something about llvm, not related to --tools
      "--enable-emscripten"
      "--release-channel=nightly"
      "--target=x86_64-unknown-linux-gnu,wasm32-unknown-unknown,asmjs-unknown-emscripten"
      "--tools=" # don't build cargo, clippy, etc. as they break stuff
    ];
    in (builtins.filter (x: !builtins.any (y: x == y) ([
      "--enable-profiler" ["--enable-profiler"]
      "--release-channel=stable"
      "--target=x86_64-unknown-linux-gnu"
                         ] ++ add_flags)) ({ configureFlags = []; } // oldAttrs).configureFlags)
    ++ add_flags;

    preFixup = ''
    # mv $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld $out/bin/
    mkdir -p $out/etc/ || true
    tar -cf $out/etc/rust-lld.tar.xz $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true
    pwd
    tar -cf ./rust-lld.tar.xz $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true

    ldd $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true
    patchelf --print-interpreter $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true


    patchelf --print-rpath $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true
    patchelf --shrink-rpath $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true
    patchelf --print-rpath $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true
    patchelf --set-rpath \$ORIGIN/../lib:$out/lib:${self.stdenv.cc.libc}/lib:${self.stdenv.cc.cc.lib}/lib $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true
    patchelf --print-rpath $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld || true
    ln -s ../lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld $out/bin/rust-lld || true
    ln -s $out/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld $out/bin/rust-lld2 || true
    '';
  })).override {
    withBundledLLVM = true; # using wasm target uses rust-lld
  };

```

I would be interested in upstreaming these changes, if they've been done appropriately. Someone would need to give me a hint on rust-lld, unless it's fine to just compile the bundled llvm when wanting wasm support. There'd also need to be a wasm32-unknown-unknown system?

**Comment by nmattia** [comment]
I also fought with this a bit recently, here's a very hacky way of enabling an `x86_64-unknown-linux-musl` target: https://github.com/NixOS/nixpkgs/compare/NixOS:0002a7d...nmattia:5d31288

I'll try to clean it up and shoehorn it in the current cross compilation framework. I just could not get it to work by not using the bundled LLVM, and @TheSandwichMakr I see you have something similar here.

**Comment by nomeata** [comment]
I wasn’t expecting this to involve the full cross compiliation machinery; as I don't want to build arbitrary nix derivation for `wasm32-unknown-unknown`, but maybe it is the right thing to do (not my area of expertise). I’ll stick to the mozilla repository for the time being, and watch this space :-)

**Comment by nomeata** [comment]
I am experimenting with an overlay like
```
        (self: super: {
          rustc = super.rustc.overrideAttrs (old: {
	    configureFlags = self.lib.lists.forEach old.configureFlags (flag:
              if self.lib.strings.hasPrefix "--target=" flag
              then flag + ",wasm32-unknown-unknown"
              else flag
            );
          });
        })
```
but direct support in `nixpkgs` would indeed be neat.

**Comment by nmattia** [comment]
FYI I just added a musl/wasm32 rustc to naersk: https://github.com/nmattia/naersk/pull/97
One of the [next steps](https://github.com/nmattia/naersk/issues/92) is to make it configurable.

**Comment by nomeata** [comment]
>EDIT: and same here, more flexibility in nixpkgs directly would be great.

I actually don't want flexibility, I just want `rustc` in nixpkgs to support `wasm32` target by default, so that I (or my contributers) don’t have to build `rust` and can get a working one from the official cache :-)

**Comment by aaronjanse** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/95542

**Comment by nomeata** [comment]
I see that @Ericson2314 did a realted PR in #95542, although it is unclear to me how I use that to build a `rustc` that supports a `wasm32` target, ideally in addition to the host target, i.e. how to replicate the hack in https://github.com/NixOS/nixpkgs/issues/70238#issuecomment-603748509 (which unsurprisingly broke at some point since then)

**Comment by kvtb** [comment]
> I am experimenting with an overlay like
> 
> ```
>         (self: super: {
>           rustc = super.rustc.overrideAttrs (old: {
> 	    configureFlags = self.lib.lists.forEach old.configureFlags (flag:
>               if self.lib.strings.hasPrefix "--target=" flag
>               then flag + ",wasm32-unknown-unknown"
>               else flag
>             );
>           });
>         })
> ```
> 
> but direct support in `nixpkgs` would indeed be neat.

How to add `nvptx64-nvidia-cuda` ?
This trick does not work, the build of `rustc` fails with
```
Copying stage2 std from stage2 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / nvptx64-nvidia-cuda)
error: The argument '--package <SPEC>' was provided more than once, but cannot be used multiple times

USAGE:
    .cargo-wrapped rustdoc --features <FEATURES>... --frozen --jobs <N> --manifest-path <PATH> --package <SPEC> --release --target <TRIPLE>... -Z <FLAG>...

For more information try --help
```

**Comment by amjoseph-nixpkgs** [comment]
I fought with this for a long time and then figured out the magic incantation:

```
nix-shell -p cargo -p pkgsCross.stm32.pkgsBuildTarget.rustc --run "cargo build --release"
```

Replace `stm32` with one of the entries in `lib/systems/examples.nix` (you may need to add `rustc.config` to that entry, or tweak it).

The two important things to note are (a) `pkgsBuildTarget` and (b) you need *both* the cargo *and* the cross-`rustc` in your `$PATH`, so you need *both* of them in your `-p` argument to `nix-shell.

The nixpkgs-built cross-`cargo` doesn't hold a reference to the cross-`rustc`.  After thinking about this a lot it makes sense and is probably the only way it can be done, but it's really not obvious.  Likewise, the native-`cargo` that nixpkgs builds has *no knowledge* of what targets are installed -- **this is totally different from how the `rustup`-`cargo` works.**  Again, doing it differently would be pretty antithetical to the "nix way", but it isn't obvious until you think about it for a bit.

All of this really should be in the nixpkgs manual somewhere.

> Related: #95542

Just to be clear, that adds custom targets to `buildRustPackage`.  It doesn't help if you want a `cargo` that can be invoked from `nix-shell`, from `bash` or from anywhere else outside of a nix derivation.

> ```
>         (self: super: {
>           rustc = super.rustc.overrideAttrs (old: {
> 	    configureFlags = self.lib.lists.forEach old.configureFlags (flag:
>               if self.lib.strings.hasPrefix "--target=" flag
>               then flag + ",wasm32-unknown-unknown"
>               else flag
>             );
>           });
>         })
> ```

I don't think this works anymore.

**Comment by amjoseph-nixpkgs** [comment]
> (a) `pkgsBuildTarget`

Aside: I wonder if it's too late to rename this to `pkgsOnBuildForTarget`, like the python expressions do.  I still stumble over this naming scheme.

**Comment by n8henrie** [comment]
I've been struggling through trying to using the nix packaging tools to build a `no_std` project for cargo's `riscv32imc-unknown-none-elf` target (toying around with <https://github.com/esp-rs/esp-wifi> for the esp32c3). I'm on an `aarch64-darwin` host.

It builds fine using a rustup-managed cargo, or if I just use oxalica to provide a devshell. It would be nice to get this working with the standard nix tooling (`buildRustPackage`) as well!

I've already added the `compiler_builtins` and such dependencies to `Cargo.toml` [as described here](https://discourse.nixos.org/t/build-rust-app-using-cargos-build-std-feature-with-naersk-fails-because-rust-src-is-missing/13161/4?u=n8henrie).

Using my attempt at the recommended cross-compile setup (and oxalica to provide a nightly with the target in question):

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    rust-overlay,
  }: let
    inherit (nixpkgs) lib;
    systems = ["aarch64-darwin" "x86_64-linux" "aarch64-linux"];
    systemClosure = attrs:
      builtins.foldl' (acc: system:
        lib.recursiveUpdate acc (attrs system)) {}
      systems;
  in
    systemClosure (
      system: let
        inherit ((builtins.fromTOML (builtins.readFile ./Cargo.toml)).package) name;
        pkgs = import nixpkgs {
          inherit system;
          overlays = [(import rust-overlay)];
        };
        pkgsCross = import nixpkgs {
          inherit system;
          crossSystem =
            nixpkgs.lib.systems.examples.riscv32-embedded
            // {
              rustc.config = "riscv32imc-unknown-none-elf";
            };
        };
        toolchain =
          (
            pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml
          )
          .overrideAttrs {auditable = false;};
        rustPlatform =
          pkgsCross.makeRustPlatform
          {
            cargo = toolchain;
            rustc = toolchain;
          };
      in {
        packages.${system} = {
          default = pkgs.callPackage ./. {inherit name rustPlatform;};
        };
      }
    );
}
```

Where my `default.nix` is

```nix
{
  rustPlatform,
  name,
}: (rustPlatform.buildRustPackage
  {
    inherit name;
    src = ./.;
    cargoLock = {
      lockFile = ./Cargo.lock;
      outputHashes = {
        "esp-wifi-0.1.0" = "sha256-EFA3JepMP1LuXCnYOL6L1x6gJF2K4coXGOIjUUrXHso=";
      };
    };
    auditable = false;
  })
```

the build fails with

```console
$ nix build
$ nix build
error: builder for '/nix/store/175n87lzbv94ggqsq7k1imiznnkva39n-http-client-riscv32-none-elf.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling atomic-waker v1.1.1
       > error[E0432]: unresolved import `core::sync::atomic::AtomicUsize`
       >   --> /private/tmp/nix-build-http-client-riscv32-none-elf.drv-0/cargo-vendor-dir/atomic-waker-1.1.1/src/lib.rs:21:5
       >    |
       > 21 | use core::sync::atomic::AtomicUsize;
       >    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AtomicUsize` in `sync::atomic`
       >
       > For more information about this error, try `rustc --explain E0432`.
       > error: could not compile `atomic-waker` (lib) due to previous error
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/175n87lzbv94ggqsq7k1imiznnkva39n-http-client-riscv32-none-elf.drv'.
```

Adding `CARGO_BUILD_RUSTFLAGS = "-Z build-std=core";` doesn't help.

I'm not sure why using `buildRustPackage` breaks things here, I assume it's something about the `build-std` issues that have been mentioned? It seems like this would probably "just work" if I could pass / override `CARGO_BUILD_TARGET` and just use the infra from oxalica. I suppose I could probably just roll my own `runCommandLocal` but that certainly doesn't seem like the "right" way.

I've omitted the rust code for brevity, as this comment is long enough as is, but happy to provide if anyone wants.

**Comment by n8henrie** [comment]
FWIW, I resolved the above `AtomicUsize` error by changing

```nix
pkgsCross = import nixpkgs {
            inherit system;
            crossSystem =
              nixpkgs.lib.systems.examples.riscv32-embedded
              // {
                rustc.config = "riscv32imc-unknown-none-elf";
              };
          };
```

to

```nix
pkgsCross = import nixpkgs {
            inherit system;
            crossSystem = {
              inherit system;
              rustc.config = "riscv32imc-unknown-none-elf";
            };
          }
```

**Comment by poelzi** [comment]
It definitely got easier packaging rust software with wasm components but still quite some pain. 

1. It is enough to include `cargo` and `rustc-wasm32` in your `buildInputs` for getting both targets compiled in one cargo environment.
2. I also got the missing `rust-lld` that is missing in nixpkgs. Since this problem arose from the dependencies I used following workaround:

```
 rust-lld = symlinkJoin {
    name = "rust-lld";
    paths = [ rustc-wasm32.llvmPackages.lld ];
    postBuild = ''
      ln -s $out/bin/lld $out/bin/rust-lld
    '';
  };
```

Include this in `nativeBuildInputs` and it worked for spyglass. I'm very confused about `rust-lld`. It is part of bootstrap rust package, but it is also *not* in the rustup toolchain. Some distros seem to ship to.
Maybe we should add in the rustc installPhase:
```
ln -s ${llvmPackages.lld}/bin/lld $out/bin/rust-lld
```
???

**Comment by Eveeifyeve** [comment]
Hey I have noticed this issue is still current in trunk which is mostly used in leptos.

**Comment by n8henrie** [comment]
It seems that cross-compiling rust from an aarch64-darwin host to any other target is currently broken by: https://github.com/NixOS/nixpkgs/issues/180771

**Comment by n8henrie** [comment]
> It builds fine using a rustup-managed cargo, or if I just use oxalica to provide a devshell. It would be nice to get this working with the standard nix tooling (buildRustPackage) as well!

Followup for anyone interested, I got a no_std embedded project compiling with just nixpkgs (no e.g. oxalica, fenix) for avr: <https://github.com/n8henrie/attiny85-relay/commit/27b29e8dfeff4b671f24d348eb253d53d1d3298f> and esp32c3: <https://github.com/n8henrie/esp32c3-rust-mqtt/commit/5f4359f382e5d575bdfd21f2cb38763bed7412d0>

The pattern I'm using ensuring to set `RUSTC_BOOTSTRAP = "1";` and:

```nix
pkgs.callPackage ./package.nix { rustPlatform = pkgs.callPackage ./rustplatform-with-src.nix { }; };
```

[rustplatform-with-src.nix](https://github.com/n8henrie/esp32c3-rust-mqtt/blob/master/rustplatform-with-src.nix)
```nix
# https://github.com/NixOS/nixpkgs/issues/393680
{
  cargo,
  makeRustPlatform,
  wrapRustcWith,
  rustc-unwrapped,
  rustPlatform,
  symlinkJoin,
}:
makeRustPlatform {
  inherit cargo;
  rustc = wrapRustcWith {
    inherit rustc-unwrapped;
    sysroot = symlinkJoin {
      name = "rust-${rustc-unwrapped.version}-sysroot-with-src";
      paths = [ rustc-unwrapped ];
      postBuild = ''
        mkdir -p $out/lib/rustlib/src/rust
        ln -s ${rustPlatform.rustLibSrc} $out/lib/rustlib/src/rust/library
      '';
    };
  };
}
```

Seems to be working well so far, though still requires the painful dance of pinning all the rust compiler inputs in `dev-dependencies` every time the compiler updates.
