### PR TITLE
llvm-stdenv: fix default stdlib

### LINKED ISSUE #28223: llvmPackages stdenv broken on master and unstable, can't find C++ headers?
## Issue description

The clang stdenv (e.g., `llvmPackages_4.stdenv`) on recent unstable channel no longer seems able to find the C++ headers when used as the stdenv for a build.

### Steps to reproduce

```
$ NIX_PATH=unstable=https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.09pre112691.abdb58e407/nixexprs.tar.xz nix-build -E "with import <unstable> {}; lzip.override { stdenv = llvmPackages_4.stdenv; }"
```

yields

```
...
build flags: SHELL=/nix/store/8v2glga3sg78wj5fmxqvf63vdxrjgy6h-bash-4.4-p12/bin/bash
c++ -DNDEBUG -O3 -c -o arg_parser.o arg_parser.cc
arg_parser.cc:20:10: fatal error: 'cstring' file not found
#include <cstring>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile:50: arg_parser.o] Error 1
```

Curiously the libcxxStdenv does work:

```
NIX_PATH=unstable=https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.09pre112691.abdb58e407/nixexprs.tar.xz nix-build -E "with import <unstable> {}; lzip.override { stdenv = llvmPackages_4.libcxxStdenv; }"
```

and just for sanity, it does work on 17.03 and usually works otherwise O:)

```
NIX_PATH=nixpkgs=https://nixos.org/channels/nixos-17.03/nixexprs.tar.xz nix-build -E "with import <nixpkgs> {}; lzip.override { inherit (llvmPackages_4) stdenv; }"
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

Fixes #28223

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by Ericson2314 — CHANGES_REQUESTED** [review]
I think https://github.com/NixOS/nixpkgs/pull/28870/files#diff-ae6d7fc8f1059168bd391972ef177c31R43 will unfortunately ensure that's defined no matter what. We'll have to special case that var taking it out of the loop.

**Comment by LnL7** [comment]
@Ericson2314 It works fine, `NIX_CXXSTDLIB_COMPILE` will be either empty or the default at that point.

```
$ nix-shell -E 'with import ./. {}; llvmPackages.stdenv.mkDerivation { name = "foo"; }' --run 'NIX_DEBUG=1 $CXX'
HARDENING: disabled flags: IGNORED_KEY
HARDENING: Is active (not completely disabled with "all" flag)
HARDENING: enabling fortify
HARDENING: enabling stackprotector
HARDENING: enabling pic
HARDENING: enabling strictoverflow
HARDENING: enabling format
HARDENING: enabling relro
HARDENING: enabling bindnow
extra flags before to /nix/store/gmb9n24q2brhd3x2z1c5zv3psy1yv4jk-clang-4.0.1/bin/clang++:
  ''
original flags to /nix/store/gmb9n24q2brhd3x2z1c5zv3psy1yv4jk-clang-4.0.1/bin/clang++:
  ''
extra flags after to /nix/store/gmb9n24q2brhd3x2z1c5zv3psy1yv4jk-clang-4.0.1/bin/clang++:
  -B/nix/store/gmb9n24q2brhd3x2z1c5zv3psy1yv4jk-clang-4.0.1/lib
  -B/nix/store/yz5vwqycca5jrgcdigxyj5776jalbvsh-glibc-2.25/lib/
  -idirafter
  /nix/store/6jyqh11wgbam661h9sqfpydan6jhsh30-glibc-2.25-dev/include
  -idirafter
  -B/nix/store/i3knpsfj710dxmpx73vbh16mhfpv4jnh-clang-wrapper-4.0.1/bin/
  -isystem
  /nix/store/dj2w6h9vyma0bvrchb8npwk6s1m62j10-gcc-6.4.0/include/c++/6.4.0
  -isystem
  /nix/store/dj2w6h9vyma0bvrchb8npwk6s1m62j10-gcc-6.4.0/include/c++/6.4.0/x86_64-unknown-linux-gnu
  -O2
  -D_FORTIFY_SOURCE=2
  -fstack-protector-strong
  --param
  ssp-buffer-size=4
  -fPIC
  -fno-strict-overflow
  -Wformat
  -Wformat-security
  -Werror=format-security
clang-4.0: error: no input files
```

**Comment by LnL7** [comment]
@Ericson2314 just finished both `afl` and `python27Packages.vowpalwabbit`, they are both ok.

**Comment by Ericson2314** [comment]
Oh my bad, I thought the export line used the salted variable. I see how it works now, but unfortunately I don't think this will work in the cross case, where that variable won't be inspected if the "host role" is not in use. For that reason we do need to stuff it directly into the salted var, but only if none of the activities input roll-based ones are defined.

**Comment by LnL7** [comment]
Yeah, I thought so. Would doing the same for the build/target variants work?

**Comment by Ericson2314** [comment]
@LnL7 I suppose, though the flags will be repeated when more the cc-wrapper takes on multiple roles. I think going straight to defining the salted var like I described is cleanest for now---I'll just look forward to the day when we can remove all `CXXSTDLIB_*`.
