### ISSUE TITLE
slic3r gui fails

### ISSUE THREAD

**Issue by josefs** [NixOS/nixpkgs#19271]
## Issue description

When I issue:

> slic3r --gui

I get the following error:

Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Can't load '/nix/store/12j8ikqfhxp27bxrd55h2900cb277fzn-perl-OpenGL-0.6703/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/auto/OpenGL/OpenGL.so' for module OpenGL: /nix/store/12j8ikqfhxp27bxrd55h2900cb277fzn-perl-OpenGL-0.6703/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/auto/OpenGL/OpenGL.so: undefined symbol: glWindowPos4dMESA at /nix/store/xcp6lrq3ynj75cqcyy7b32jgizf9jr4b-perl-5.22.2/lib/perl5/5.22.2/x86_64-linux-thread-multi/DynaLoader.pm line 193.
 at /nix/store/n73gf9sncjrv2aqj4lycd7b5qipvj3dp-slic3r-1.2.9/share/slic3r/lib/Slic3r/GUI/Plater/2DToolpaths.pm line 120.
Compilation failed in require at /nix/store/n73gf9sncjrv2aqj4lycd7b5qipvj3dp-slic3r-1.2.9/share/slic3r/lib/Slic3r/GUI/Plater/2DToolpaths.pm line 120.
BEGIN failed--compilation aborted at /nix/store/n73gf9sncjrv2aqj4lycd7b5qipvj3dp-slic3r-1.2.9/share/slic3r/lib/Slic3r/GUI/Plater/2DToolpaths.pm line 120.
Compilation failed in require at /nix/store/n73gf9sncjrv2aqj4lycd7b5qipvj3dp-slic3r-1.2.9/share/slic3r/lib/Slic3r/GUI.pm line 16.
BEGIN failed--compilation aborted at /nix/store/n73gf9sncjrv2aqj4lycd7b5qipvj3dp-slic3r-1.2.9/share/slic3r/lib/Slic3r/GUI.pm line 16.
Compilation failed in require at (eval 80) line 1.
### Steps to reproduce

See above.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  Distributor ID: Ubuntu
  Description:    Ubuntu 15.10
  Release:    15.10
  Codename:   wily
- Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.4
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  17.03pre93030.548bcd0

**Comment by timor** [comment]
I just tried out slic3r on a recent 16.09. Same problem here.

**Comment by timor** [comment]
After some digging it looks like the glWindowsPos4* symbols are missing from libGL.so, but I am not sure they are supposed to be there in the first place. However, they are required by the perl OpenGL bindings.

**Comment by timor** [comment]
Updating `perlPackages.OpenGL` to 0.70 did the trick on my machine.

**Comment by bjornfor** [comment]
Hm, I get segfault (after upgrading OpenGL to 0.70):

```
$ ./result/bin/slic3r --gui
Segmentation fault
```

**Comment by timor** [comment]
I based my modifications on this commit:  45b2a6d88299bb5671e36a4239ec0097bc149fb3

I have the branch here if you want to try: https://github.com/timor/nixpkgs/tree/slic3r-gui

Also, it seems it is not working perfectly: The print surface is not rendered.  This may  be a problem with the graphics drivers though.  As far as I can tell, I am using the free ATI drivers (haven't changed anything in configuration.nix).

**Comment by bjornfor** [comment]
@timor: Hm, your opengl bump is exactly like mine, so there must be something else.

**Comment by pjones** [comment]
I cherry picked the commit from @bjornfor and can report the same results.  Slic3r works, but it doesn't render the print surface anymore.

Can we get someone from upstream involved?

**Comment by pjones** [comment]
@bjornfor Do you need any help with this issue?  I'm still having to patch nixpkgs due to this.  Thanks.

**Comment by globin** [comment]
Pushed that commit to master and 17.03 as it definitely improves the situation

**Comment by pjones** [comment]
@globin That patch at least lets slic3r run, but it's missing the object platform.  That makes it very hard to use.  Do we need another issue to track that?
