### ISSUE TITLE
Build error in liquid-fixpoint-0.7.0.7 (haskellPackages.liquid-fixpoint)

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nixpkgs#52418]
## Issue description

The current version of haskellPackages.liquid-fixpoint in Nixpkgs is liquid-fixpoint-0.7.0.7. (This is also the latest version on Hackage.) Unfortunately, this version will not build with the current version of GHC in NixPkgs, which is 8.4.4. It did build with older versions of GHC (prior to 8.4.2, I think). This prevents the installation of `liquidhaskell`.

This has been reported [upstream](https://github.com/ucsd-progsys/liquid-fixpoint/issues/371). I have verified that the version of liquid-fixpoint in that Github repo does build with GHC 8.4.4. So I think Nixpkgs needs to either pick up this new version, or build the older version with an earlier version of GHC.

### Steps to reproduce

In NixOS, include `haskellPackages.liquidhaskell` in `environment.systemPackages` in `/etc/nixos/configuration.nix` and do `nixos-rebuild switch`.

Alternatively, just do:

```
$ nix-env -f "<nixpkgs>" -iA haskellPackages.liquidhaskell
```

The output includes the following error message.

```
src/Language/Fixpoint/Misc.hs:291:28: error:
Ambiguous occurrence ‘<>’
It could refer to either ‘Text.PrettyPrint.HughesPJ.<>’,
imported from ‘Text.PrettyPrint.HughesPJ’ at src/Language/Fixpoint/Misc.hs:34:1-64
or ‘Prelude.<>’,
imported from ‘Prelude’ at src/Language/Fixpoint/Misc.hs:41:1-40
(and originally defined in ‘GHC.Base’)
|
291 | dcolon = colon <> colon
| ^^

```
## Technical details

```
$ nix-env -f "<nixpkgs>" -qaP -A haskellPackages.liquid-fixpoint
haskellPackages.liquid-fixpoint  liquid-fixpoint-0.7.0.7
```

```
$ nix-env -qa ghc
ghc-8.4.4
```

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (1.51 MiB download, 8.12 MiB unpacked):
  /nix/store/4mdg10ca9aibxx9a8bvd6ggqp8n94c6g-bash-interactive-4.4-p23
  /nix/store/95znb1zfx800c0li97fkqd2k23cq97as-bash-interactive-4.4-p23-info
  /nix/store/97cw7bjqw3ygzg93ysjiwgw0ac4rcqmn-bash-interactive-4.4-p23-dev
  /nix/store/c9245msqhcnqk7pg0kx1ayqwmq2scxm4-nix-info
  /nix/store/d0jc8jljjrzbqf95aa57y4hm6w0lmg9p-bash-interactive-4.4-p23-doc
  /nix/store/hqh7jidzdvmvxhfq62jqzj7d109rpk1n-bash-interactive-4.4-p23-man
  /nix/store/j3z0kc1lx4mm49fcipr74yjppaypjc49-readline-7.0p5
copying path '/nix/store/d0jc8jljjrzbqf95aa57y4hm6w0lmg9p-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/95znb1zfx800c0li97fkqd2k23cq97as-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/hqh7jidzdvmvxhfq62jqzj7d109rpk1n-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/c9245msqhcnqk7pg0kx1ayqwmq2scxm4-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/j3z0kc1lx4mm49fcipr74yjppaypjc49-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/4mdg10ca9aibxx9a8bvd6ggqp8n94c6g-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/97cw7bjqw3ygzg93ysjiwgw0ac4rcqmn-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.0-2-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(amy): `"nixpkgs-19.03pre161900.61c3169a0e1"`
 - nixpkgs: `/home/amy/.nix-defexpr/channels/nixpkgs`

```

**Comment by mhwombat** [comment]
The package author plans to upload a new version to Hackage. Once that is done, I will create a pull request on nixpkgs to pick up the new version.

**Comment by FliegendeWurst** [comment]
This was fixed eventually.
