### ISSUE TITLE
calibre "get books" button fails with python error because of qt update

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#226712]
### Describe the bug
I get a traceback when clicking the "get books" button of calibre

### Steps To Reproduce
1. click the "get books" button of calibre

get 
```
calibre 6.11  embedded-python: False
Linux-5.15.104-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.104', '#1-NixOS SMP Wed Mar 22 12:31:37 UTC 2023')
Python 3.10.9
Interface language: fr
Traceback (most recent call last):
  File "/nix/store/hq1g09h90zxrm88qvjdc37pf5zc09cvx-calibre-6.11.0/lib/calibre/calibre/gui2/actions/store.py", line 49, in do_search
    return self.search()
  File "/nix/store/hq1g09h90zxrm88qvjdc37pf5zc09cvx-calibre-6.11.0/lib/calibre/calibre/gui2/actions/store.py", line 55, in search
    sd = SearchDialog(self.gui, self.gui, query)
  File "/nix/store/hq1g09h90zxrm88qvjdc37pf5zc09cvx-calibre-6.11.0/lib/calibre/calibre/gui2/store/search/search.py", line 38, in __init__
    self.setupUi(self)
  File "/nix/store/hq1g09h90zxrm88qvjdc37pf5zc09cvx-calibre-6.11.0/lib/calibre/calibre/gui2/store/search/search_ui.py", line 84, in setupUi
    self.results_view = ResultsView(parent=self.verticalLayoutWidget)
TypeError: ResultsView.__init__() got an unexpected keyword argument 'parent'
```

### Expected behavior
Search window opens

### Additional context
Reproducible on nixos-unstable  f294325aed382b66c7a188482101b0f336d1d7db as well as nixos-22.11  83607dae4e0

This is a regression (it does not happen on earlier nixos-22.11) so I bisected it down to
```
$  git bisect view --graph --oneline
* 953c6fed966 python310Packages.pyqt6: 6.4.0 -> 6.4.2
* 496dd49d1c7 python310Packages.pyqt5: 5.15.7 -> 5.15.9
* 3d142abd143 (HEAD) calibre: don't rely on sip.platform_tag
* 3d4897aec5a python310Packages.sip: 6.7.5 -> 6.7.7
```
(full log:
```
git bisect start
# status : en attente d'un commit bon et d'un commit mauvais
# bad: [3cc8b4477e175bb700022c147a59bd40e0de8161] python3.pkgs.ihatemoney: remove
git bisect bad 3cc8b4477e175bb700022c147a59bd40e0de8161
# status : en attente de bon(s) commit(s), un mauvais commit connu
# good: [0874168639713f547c05947c76124f78441ea46c] Merge pull request #206382 from NixOS/backport-206193-to-release-22.05
git bisect good 0874168639713f547c05947c76124f78441ea46c
# good: [5dc2630125007bc3d08381aebbf09ea99ff4e747] scope-lite: init at 0.2.0
git bisect good 5dc2630125007bc3d08381aebbf09ea99ff4e747
# good: [69782b499beb1f99b11f38a3d2804ac8f3532da3] Merge branch 'master' into staging-next
git bisect good 69782b499beb1f99b11f38a3d2804ac8f3532da3
# good: [4840ca34f4549cd5def4a76876e35e0e7d147fa4] Merge pull request #213626 from jamesreprise/entries-typo
git bisect good 4840ca34f4549cd5def4a76876e35e0e7d147fa4
# bad: [f1b48b2a959ad7bc5519ef9f8b827dda5dd21a6b] Merge master into staging-next
git bisect bad f1b48b2a959ad7bc5519ef9f8b827dda5dd21a6b
# good: [c0bb8d41bbc8a6e74d33fd93e114a8c8af84cb86] Merge pull request #217404 from r-ryantm/auto-update/python310Packages.google-cloud-language
git bisect good c0bb8d41bbc8a6e74d33fd93e114a8c8af84cb86
# bad: [e616d5fbec21460bbd86e16a83bfa27e55df8b01] Merge master into staging-next
git bisect bad e616d5fbec21460bbd86e16a83bfa27e55df8b01
# bad: [a0c893191f002aab86c2ee4eae389aadb0d57047] Merge pull request #211389 from r-ryantm/auto-update/python310Packages.xarray-einstats
git bisect bad a0c893191f002aab86c2ee4eae389aadb0d57047
# bad: [b90bbe1bde358bcb5c683cc1a6e7bfd3d179ec76] Merge pull request #217746 from OPNA2608/update/palemoon
git bisect bad b90bbe1bde358bcb5c683cc1a6e7bfd3d179ec76
# good: [9e0eed654c705c7cafe192a8eba1610217f70544] Merge pull request #217484 from fabaff/flask-mongoengine-inputs
git bisect good 9e0eed654c705c7cafe192a8eba1610217f70544
# bad: [03fb72201639e5274fee6d77b0d9c66e98329aba] Merge pull request #217799 from figsoda/smali
git bisect bad 03fb72201639e5274fee6d77b0d9c66e98329aba
# good: [f5dad40450d272a1ea2413f4a67ac08760649e89] Merge pull request #217627 from NickCao/singbox
git bisect good f5dad40450d272a1ea2413f4a67ac08760649e89
# good: [94dc2f4beb2457df52ba9f5ba4c4c82167d7d1b7] Merge pull request #216738 from wineee/deepin-camera
git bisect good 94dc2f4beb2457df52ba9f5ba4c4c82167d7d1b7
# bad: [21121d5c30491a50bee53709ac54292db07090b5] Merge pull request #217784 from marsam/update-chat-downladoer
git bisect bad 21121d5c30491a50bee53709ac54292db07090b5
# good: [8c1af064fb5e44fbf580c9efa140b9aad2c4c85a] python310Packages.httpx-ntlm: remove cryptography
git bisect good 8c1af064fb5e44fbf580c9efa140b9aad2c4c85a
# good: [ad6c8e2a18a6477c44b591a23233585172f0dba0] anki-bin: add mahmoudk1000 to the maintainers
git bisect good ad6c8e2a18a6477c44b591a23233585172f0dba0
# bad: [990f09363a654163d23821a0941ea3b8d2d8978b] Merge pull request #217781 from dotlambda/pyqt6-6.4.2
git bisect bad 990f09363a654163d23821a0941ea3b8d2d8978b
# good: [8076ea3f1e2877c4612a70b61e83fc253a5b087d] python310Packages.meteofrance-api: 1.1.0 -> 1.2.0
git bisect good 8076ea3f1e2877c4612a70b61e83fc253a5b087d
# good: [ee1ea62bd33c83b274b021d66d0402599d72c7e4] yosys: 0.25 -> 0.26
git bisect good ee1ea62bd33c83b274b021d66d0402599d72c7e4
# bad: [953c6fed96699dbb28de8a8a1ff5d3825af36c4e] python310Packages.pyqt6: 6.4.0 -> 6.4.2
git bisect bad 953c6fed96699dbb28de8a8a1ff5d3825af36c4e
# skip: [3d4897aec5ae0da69d5d46d61297f8f3007fa3e0] python310Packages.sip: 6.7.5 -> 6.7.7
git bisect skip 3d4897aec5ae0da69d5d46d61297f8f3007fa3e0
# good: [2308c637ef1b66ad718a5418501b196c4c3243c8] Merge pull request #217330 from ConnorBaker/fix/caffe-use-pre-cudnn8
git bisect good 2308c637ef1b66ad718a5418501b196c4c3243c8
                                                        
```

### Notify maintainers

@psub @AndersonTorres  @kilianar 

ping @dotlambda as the author of 3d142abd143906342899a02b3d4ab66a61afb0f8, which affects calibre and is in the bisect range

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.104, NixOS, 22.11 (Raccoon), 22.11.3333.83607dae4e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - channels(symphorien): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
