### ISSUE TITLE
ghdl-llvm is missing zlib at runtime

### ISSUE THREAD

**Issue by vdot0x23** [NixOS/nixpkgs#113401]
**To Reproduce**
1. Install `ghdl-llvm` and compile e.g. hello.vhdl (`ghdl -a hello.vhdl`, `ghdl -e hello_world`)
```
$ ghdl -e hello_world
/nix/store/rqfgki7ck1bxqhk3hd7wziqhahjadfbj-binutils-2.35.1/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
ghdl:error: compilation error 
```

**Expected behavior**
Succesfull compilation.

**Additional context**
Can be worked around by installing `zlib` as per https://github.com/ghdl/ghdl/issues/122

**Notify maintainers**

@lucus16

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.97, NixOS, 21.05pre270342.64b46178838 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(vdot0x23): `"pkg-21.03pre253060.a322b32e9d7"`
 - channels(root): `"nixos-21.05pre270342.64b46178838"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ghdl-llvm
# a list of nixos modules affected by the problem
module:
```

**Comment by bjornfor** [comment]
Works in NixOS 23.05:

```
$ nix-shell -p ghdl-llvm
$ ghdl -a hello.vhdl 
$ ghdl -e hello_world
$ ghdl -r hello_world
Hello world!
```

With hello.vhdl from https://gritbub-ghdl.readthedocs.io/en/latest/using/QuickStartGuide.html.

**Comment by leonschoorl** [comment]
There is a difference between installing ghdl-llvm in nixos and opening a nix-shell with that package.
In `/etc/nixos/configuration` I've got:
```nix
users.users.leon.packages = with pkg; [... ghdl-llvm]
```

Then ghdl doesn't work:
```
$ ls -l `which ghdl`
lrwxrwxrwx 1 root root 68  1 jan  1970 /etc/profiles/per-user/leon/bin/ghdl -> /nix/store/611v6fm0f6m2fcmlwnyj7c86zf8jzhq2-ghdl-llvm-3.0.0/bin/ghdl

$ ghdl -a hello.vhdl 

$ ghdl -e hello_world
/nix/store/idiaraknw071d20nlqp49s18gbvw4wa0-binutils-2.40/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
```

But if I open a nix-shell with ghdl-llvm, it does work:
```
$ nix-shell -p ghdl-llvm

[nix-shell]$ ls -l `which ghdl`
-r-xr-xr-x 1 root root 5249328 jan  1  1970 /nix/store/611v6fm0f6m2fcmlwnyj7c86zf8jzhq2-ghdl-llvm-3.0.0/bin/ghdl

[nix-shell]$ ghdl -a hello.vhdl

[nix-shell]$ ghdl -e hello_world

[nix-shell]$ ghdl -r hello_world
Hello world!
```

As you can see it uses the same binary from the store, but the environment is different somehow.


### Metadata
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.13, NixOS, 23.11 (Tapir), 23.11.4195.809cca784b9f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by leonschoorl** [comment]
The meaningful difference is these two environment variables:
```
declare -x NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu="1"
declare -x NIX_LDFLAGS="-L/nix/store/ykh8zgm27qqhfxcq77jlap5ahrplrk54-zlib-1.3/lib"
```
When I manually set those then ghdl works outside of nix-shell too.

From what I understand of it, ghdl calls out to "gcc" to link the resulting binary.
But gcc is actually a wrapper `/nix/store/i6zjqpawh725z1lyg3alglzlabnzbjx7-gcc-wrapper-12.3.0/bin/gcc`.
And that wrapper responds to the combination of those two environment vars to pass that `-L` option to the real gcc so it'll find `libz.so.1` in that directory.

**Comment by sempiternal-aurora** [comment]
Fixed by #509436
