### ISSUE TITLE
Rebuild causes sudo to be required to adjust screen brightness

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#14168]
The last two times that I've done a `sudo nix-channel --update` and `sudo nixos-rebuild-switch`, I end up in a state where I get this prompt every time I try to adjust screen brightness in Gnome 3:

> Authentication is needed to run `/nix/store/...-gnome-settings-daemon-3.18.2/libexec/gsd-backlight-helper' as the super user

It stays this way until the next time I log in, at which point I can again adjust screen brightness without root, as expected.

Version info:

```
> uname -a
Linux renzo 4.4.4 #1-NixOS SMP Thu Mar 3 23:10:04 UTC 2016 x86_64 GNU/Linux
> nixos-version
16.09pre78286.0bf8a1a (Emu)
> nix-env --version
nix-env (Nix) 1.11.2
> nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre78848.9549257"
```

**Comment by DamienCassou** [comment]
I confirm the problem

**Comment by falsifian** [comment]
I'm seeing this on release-16.09.

**Comment by olejorgenb** [comment]
Hm, I get this for 17.09 (worked in one of the beta releases) now. I haven't restarted after `nixos-rebuild switch` though.

**Comment by chris-martin** [comment]
I can't confirm whether this still happens to me anymore because, for the last few months, `nixos-rebuild switch` just causes the display manager to crash.

**Comment by teh** [comment]
@chris-martin are you using GDM? If so I think this is finally fixed here: https://github.com/NixOS/nixpkgs/issues/21439#event-1348870891 (at least until we introduce wayland).

This still seems to happen for 17.09 after a `rebuild-switch` and the workaround seems to be a reboot.

**Comment by jtojnar** [comment]
I cannot reproduce this on current unstable. Is this still happening with GNOME 3.26?

**Comment by chris-martin** [comment]
I still cannot attempt to reproduce due to https://github.com/NixOS/nixpkgs/issues/14168#issuecomment-334958454

**Comment by chris-martin** [comment]
@teh Yes, I'm using GDM. Should I try rebuilding from the unstable channel?

**Comment by jtojnar** [comment]
Yes, `switch` no longer restarts `display-manager` on unstable.

**Comment by jtojnar** [comment]
Hmm, I just came across this issue on 5b53774f89ee4288554d5f45cf58c74787e421fb

**Comment by jtojnar** [comment]
Okay, apparently the issue happens whenever gnome-settings-daemon is rebuild. The polkit policy file in system profile will point to the new derivation but GNOME will still use the old `gsd-backlight-helper`.

**Comment by jtojnar** [comment]
Apparently, GNOME Shell is using DBus to call `org.gnome.SettingsDaemon.Power.Screen` interface. The interface is provided by `${gnome3.gnome-settings-daemon}/libexec/gsd-power` but it is just a program ran by [XDG autostart](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html), not a systemd service, so it is not restarted when the service is updated. This might fix that: https://bugzilla.gnome.org/show_bug.cgi?id=758413

**Comment by danbst** [comment]
Was hit by this too.

The most straightforward way to fix that would be:
- define a common place where gnome-setting-daemon executable lives (maybe some `/run/share/gsd`?)
- patch https://github.com/GNOME/gnome-settings-daemon/blob/800116f344fdf0ce3ee7f1ab5aa9403366fd58d3/plugins/power/org.gnome.settings-daemon.plugins.power.policy.in.in#L28 to respect that directory (probably only when package is used in NixOS)
- symlink gnome-setting-daemon there in an activation script (I hope polkit can resolve symlinks)
- amend Autostart files in gnome-settings-daemon to launch stuff from that common place

If we don't want (cannot) restart gsd-power (just like don't want/cannot restart gnome-session), we should add some hacks here...

**Comment by tcosmo** [comment]
Hello,

I still have this issue going on but I am not able to confirm it happens after a `nixos-rebuild switch`.
What I experience is that from time to time, the issue starts and won't stop until reboot.

Not sure if relevant but I use 'redshift'.

My version info:

`
> uname -a
Linux cosmo-mu 4.14.85 #1-NixOS SMP Sat Dec 1 08:43:00 UTC 2018 x86_64 GNU/Linux
> nixos-version
19.03pre161545.7c73f53d836 (Koi)
> nix-env --version
nix-env (Nix) 2.1.3
> nix-instantiate --eval '<nixpkgs>' -A lib.version
"19.03pre161545.7c73f53d836"
`

**Comment by jameysharp** [comment]
@jtojnar, where was that "solution" link supposed to point? I don't understand how `multiple-outputs.sh` could be related to this issue. Did you mean https://github.com/NixOS/nixpkgs/issues/14168#issuecomment-422948774?

I was glancing through [`gsd-backlight.c`](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/master/plugins/power/gsd-backlight.c#L353) and noticed there's a feature intended for testing that seems like it would be an easy workaround for this.

I think these two steps should fix the observed symptom:

- wrap libexec/gsd-power to set `GSD_BACKLIGHT_HELPER=/run/wrappers/bin/gsd-backlight-helper`, and
- set the NixOS option `security.wrappers.gsd-backlight-helper.source = "${gnome-settings-daemon}/libexec/gsd-backlight-helper";`

This bypasses polkit, which means there's no security policy preventing someone on an inactive console from setting the backlight brightness.

How silly is this approach? I haven't actually tried it yet; should I bother?

**Comment by jtojnar** [comment]
@jameysharp Sorry for the wrong link; you got the right one.

Your approach actually sounds workable. The [helper code](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/GNOME_SETTINGS_DAEMON_3_30_2/plugins/power/gsd-backlight-helper.c) is small and quite self-contained (only linking against gudev).

**Comment by arianvp** [comment]
Gnome-settings-daemon currently has a merge request to turn it into a systemd user unit  https://gitlab.gnome.org/GNOME/gnome-settings-daemon/merge_requests/27 as part of the SystemdUser initiative.  Perhaps this will help. https://wiki.gnome.org/Initiatives/SystemdUser

**Comment by cyplo** [comment]
HI ! For the brightness control - setting `hardware.brightnessctl.enable` to true and adding my user to the `video` group helped - no admin prompt anymore.

Is this issue more broad than being about controlling the brightness now ? If so - would it help to change the title/description ? If not - is there anything else that we need to do to close it ? Thanks so much ! :)

**Comment by jtojnar** [comment]
@cyplo Ths is specifically about changing brightness in GNOME after rebuild. It will be fixed by #57620

**Comment by cyplo** [comment]
@jtojnar thank you ! :) 
If this helps as a data point - it does work for me in gnome3 after `sudo nixos-rebuild switch --upgrade` and has been every time.

**Comment by jtojnar** [comment]
@cyplo The error occurs only when gnome-settings-daemon is changed so it is possible you have not encountered it.

**Comment by pedrovelho** [comment]
Hi all I get this problem on 20.04, the backlight worked on 19.09 and after `nixos-rebuild upgrade` it stopped working. 

```sh
> sudo light -v 3 -A 10                                                                                                         
helpers.c:21: Error: could not open '/etc/light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
```

OR 

```sh
> echo "200" | sudo tee /sys/class/backlight/intel_backlight/brightness
```

But in gnome it does not respond, and as you can see I need root access to change these files. It is strange that I also noticed my username not showing up on gdm, instead I have a username box. I wonder if this might be just a group missing for my user. Any thoughts? Is this related?

```sh
> uname -a                  
Linux fox 5.4.33 #1-NixOS SMP Fri Apr 17 08:50:26 UTC 2020 x86_64 GNU/Linux
> nix-env --version
nix-env (Nix) 2.3.4
> nixos-version 
20.03.1418.5272327b81e (Markhor)
> nix-instantiate --eval '<nixpkgs>' -A lib.version       
"20.03.1418.5272327b81e"
```

thanks in advance

**Comment by pedrovelho** [comment]
I just found some stuff into journactl

```sh
Apr 22 14:17:52 fox .gsd-power-wrap[1821]: Error executing backlight helper: Child process stopped by signal 0
Apr 22 14:17:52 fox pkexec[14137]: myusername: The value for the SHELL variable was not found the /etc/shells file [USER=root] [TTY=unknown] [CWD=/home/myusername] [COMMAND=/run/current-system/sw/bin/gnome-settings-daemon/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight 713]
```

**Comment by worldofpeace** [comment]
> Hi all I get this problem on 20.03, the backlight worked on 19.09 and after `nixos-rebuild upgrade` it stopped working.
> 
> ```shell
> > sudo light -v 3 -A 10                                                                                                         
> helpers.c:21: Error: could not open '/etc/light/targets/sysfs/backlight/auto/minimum' for reading
> helpers.c:21: Error: Verify it exists with the right permissions
> ```
> 
> OR
> 
> ```shell
> > echo "200" | sudo tee /sys/class/backlight/intel_backlight/brightness
> ```

So you mean when you rebuild-ed on that one occasion adjusting screen brightness wouldn't work, and after a reboot it went away? Was this a rebuild from 19.09 -> 20.03?
What was the nixos-version of the system generation before the rebuild?
Lastly, this was in GNOME (it's not mentioned in your comment) and you mentioned a `light` command, I'm not sure how that has anything to do with GNOME. Was adjusting the brightness not working in the brightness slider in the shell?

> It is strange that I also noticed my username not showing up on gdm, instead I have a username box. I wonder if this might be just a group missing for my user. Any thoughts? Is this related?

There must be some sort of issue with accountsservice and GDM.
Perhaps you could open a separate bug for this?

**Comment by worldofpeace** [comment]
> Apr 22 14:17:52 fox pkexec[14137]: myusername: The value for the SHELL variable was not found the /etc/shells file [USER=root] [TTY=unknown] [CWD=/home/myusername] [COMMAND=/run/current-system/sw/bin/gnome-settings-daemon/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight 713]

That looks like you changed your shell maybe, and pkexec is accessing $SHELL, and that path doesn't exist anymore.

**Comment by pedrovelho** [comment]
Thanks @worldofpeace, the shell was the problem.

I was using zsh but it was not present on /etc/shells, to fix this I added to `/etc/configuration.nix`:

```sh
  users.extraUsers.adisbladis = {
    shell = pkgs.zsh;
  };    
  programs.zsh.enable = true;
```
I also found that  `users.mutableUsers = true;` so i used chsh but this is probably related to other issues I was having:

```sh
sudo chsh myuser --shell `which zsh`
```

Just to answer your previous question, I did upgrade by changing /etc/configuration.nix and channel, after I issued `sudo nix-build upgrade` to simply put.
