### PR TITLE
nodePackages: added ts-node

### PR DESCRIPTION
**Pull request by chisui**
added ts-node to nodePackages

###### Motivation for this change

ts-node is the the most used way to execute typescript files with nodejs.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Unfortunately, the node-packages has been updated since then. If you rebase and update, I'm happy to merge this.
Sorry for the trouble.

**Comment by onny** [comment]
When I try to run it, I get following error:
```
ts-node
tinternal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/index.js
- /nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/repl.js
- /nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at loadCompiler (/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/index.js:176:34)
    at create (/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/index.js:183:28)
    at register (/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/index.js:150:19)
    at main (/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/bin.js:180:42)
    at Object.<anonymous> (/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/bin.js:351:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/index.js',
    '/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/repl.js',
    '/nix/store/aa0zxgwg0llvjxknhhl7g8l5lbl8pigd-ts-node-10.4.0/lib/node_modules/ts-node/dist/bin.js'
  ]
}
```

I would like to use ts-node to probably run nocodb which I try to package in this draft pr https://github.com/NixOS/nixpkgs/pull/153749

File: pkgs/development/node-packages/node-packages.nix [hunk 1]
```diff
@@ -120864,6 +120981,39 @@ in
...
+      sources."@tsconfig/node12-1.0.9"
+      sources."@tsconfig/node14-1.0.1"
+      sources."@tsconfig/node16-1.0.2"
+      sources."acorn-8.5.0"
+      sources."acorn-walk-8.2.0"
+      sources."arg-4.1.3"
+      sources."create-require-1.1.1"
+      sources."diff-4.0.2"
+      sources."make-error-1.3.6"
+      sources."yn-3.1.1"
```
Comment (happysalada) [inline pkgs/development/node-packages/node-packages.nix]: you will need to add the peerdependencies to that list https://github.com/nocodb/nocodb/blob/master/packages/nocodb/Dockerfile#L28
typescript is defined as a peerdependency and not as a normal dependency.
I'm not sure if there is a setting to include peerdependencies in node2nix.

**Comment by onny** [comment]
@happysalada I would like to get this fixed. Do you know how I could add `ts-node` to `node-packages.json` and build it without having to regenerate everything?

**Comment by happysalada** [comment]
I don't think there is a way around regenerating everything for now (I hate as much as you do).
What I can propose is that you do it, before you go to lunch or something.
I'm happy to merge a PR as soon as I see it.

**Comment by onny** [comment]
Still does not work with `ts-node` v10.7.0:
```
$  nix-build -E 'with import /home/onny/projects/nixpkgs {}; nodePackages.ts-node' 
$ ./result/bin/ts-node 
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/util.js
- /nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at projectLocalResolveHelper (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/util.js:117:24)
    at resolveCompiler (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/configuration.js:229:22)
    at resolveAndLoadCompiler (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/configuration.js:222:26)
    at findAndReadConfig (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/configuration.js:48:28)
    at phase3 (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/bin.js:250:67)
    at bootstrap (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/bin.js:44:30)
    at main (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/bin.js:519:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/util.js',
    '/nix/store/8ym71mrcqfgm954lf07n6rljmk39glcq-ts-node-10.7.0/lib/node_modules/ts-node/dist/bin.js'
  ]
}
```

I guess the best way to solve this is to create a seperate package for `ts-node` with required patches etc.

**Comment by onny** [comment]
I was able to fix this issue thanks to the same [solution](https://github.com/NixOS/nixpkgs/pull/90326/files) here and created a follow up PR https://github.com/NixOS/nixpkgs/pull/168297
