### ISSUE TITLE
Sioyek build fails with mupdf 1.20.x

### ISSUE THREAD

**Issue by chuahou** [NixOS/nixpkgs#187823]
### Steps To Reproduce
1. build `sioyek` on current nixpkgs-unstable or master (e.g. `nix build nixpkgs#sioyek`)

### Build log
[Gist link from `nix log /nix/store/w1rjcjfx1knhf5vc94vbmg6pc221wpaz-sioyek-1.4.0.drv`](https://gist.github.com/chuahou/e54a9a8919ceed67a627f51003bf4c70), unfortunately I couldn't find a way to strip the colour codes.

The important errors appear to be
```
pdf_viewer/document.cpp: In member function 'void Document::convert_toc_tree(fz_outline*, std::vector<TocNode*>&)':
pdf_viewer/document.cpp:545:32: error: no match for 'operator==' (operand types are 'fz_location' and 'int')
  545 |                 if (root->page == -1) {
      |                     ~~~~~~~~~~ ^~ ~~
      |                           |       |
      |                           |       int
      |                           fz_location
```

```
pdf_viewer/pdf_renderer.cpp:318:125: error: cannot convert 'fz_quad*' to 'int*'
  318 |                                 int num_results = fz_search_page(mupdf_context, page, utf8_encode(req.search_term).c_str(), hitboxes, max_hits_per_page);
      |                                                                                                                             ^~~~~~~~
      |                                                                                                                             |
      |                                                                                                                             fz_quad*
```

```
pdf_viewer/document.cpp:552:52: error: cannot convert 'fz_location' to 'int' in assignment
  552 |                         current_node->page = root->page;
      |                                              ~~~~~~^~~~
      |                                                    |
      |                                                    fz_location
```

### Additional context
This was broken by `mupdf` being updated to version 1.20.3 (#184363), which also broke `zathura` (#187305, fixed in #187813). `sioyek` upstream has `mupdf` as a submodule that's set at 1.19.x but nixpkgs's derivation uses its `mupdf` package in `buildInputs` instead.

Upstream is unlikely to upgrade to `mupdf` (https://github.com/ahrm/sioyek/pull/294).

Both using the unaccepted PR to upstream to make `sioyek` compatible with 1.20.x (https://github.com/ahrm/sioyek/pull/294) and using 1.19.0 `mupdf` work, but I'm not sure what would be the best solution moving forward.

Should we
- have `sioyek` build using its `mupdf` submodule somehow, or
- apply a patch to make it compatible with mupdf 1.20.x, or
- keep a separate version of `mupdf` 1.19.0 around in nixpkgs to provide to this derivation, or
- override `mupdf` in this derivation (such as using the following)?
  ```nix
  let mupdf' = mupdf.overrideAttrs (old: rec {
    inherit (old) pname;
    version = "1.19.0";
    src = fetchurl {
      url = "https://mupdf.com/downloads/archive/${pname}-${version}-source.tar.gz";
      sha256 = "1vfyhlqq1a0k0drcggly4bgsjasmf6lmpfbdi5xcrwdbzkagrbr1";
    };
  }); in
  ```

### Notify maintainers
Notifying @podocarp as mentioned in `meta.maintainers`.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.11 (Raccoon), 22.11.20220820.13711c9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `""`
 - nixpkgs: `/nix/store/bxiy4hzvzsml5knnj0labdw6y2qgvmvj-source`
```

**Comment by NickCao** [comment]
Can we just use the vendored copy of mupdf, that's the only way supported by upstream I guess.

**Comment by chuahou** [comment]
> Can we just use the vendored copy of mupdf, that's the only way supported by upstream I guess.

I think that works the best, though I'm unsure of how that's normally done in nixpkgs. Do you perhaps know of any other packages with vendored submodule dependencies I could reference?

**Comment by NickCao** [comment]
If supported by the upstream build system, that should not require extra efforts, just set `fetchSubmodules` and all is fine. But I just noticed that is not the case for sioyek, it's just a bunch of shell scripts... Just go for the override path is easier in this case.

**Comment by chuahou** [comment]
Ah, so that's why it didn't work when I just tried with `fetchSubmodules` to see if it would. I'll look closer at Sioyek's build scripts and see if I can get it working, thanks!

**Comment by chuahou** [comment]
Ah, so that's why it didn't work when I just tried with `fetchSubmodules` to see if it would. I'll look closer at Sioyek's build scripts and see if I can get it working, thanks!
