### PR TITLE
neovim: 0.4.4 -> 0.5.0

### LINKED ISSUE #128959: neovim compiles against Lua 5.1 instead of luajit on aarch64-darwin
**Describe the bug**

I have an overlay to install neovim from a recent commit. When you use that overlay on a intel macbook neovim is compiled against luajit 2.1.0-beta3 while the same derivation on an M1 macbook compiles against Lua 5.1. I tried checking why that might be given it's the same exact overlay and luajit seems to compile just fine on aarch64 but I am afraid my nix skills weren't good enough.

**To Reproduce**

1. Install neovim with the following overlay:
```
self: super: {
  neovim-unwrapped = super.neovim-unwrapped.overrideAttrs (oldAttrs: {
    version = "master";
    src = super.fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "5aaa1a1c0473d9e9ac824201f92ec65e190beeb7";
      sha256 = "0nnw1gmfligzfkwlnbi1psz945ifqs2rpvf9ciq082l4y9abcp8m";
    };
    buildInputs = oldAttrs.buildInputs ++ [ super.tree-sitter ];
  });
}
```

2. Start neovim
3. Issue the command `:version`

On intel you will see:

```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by dbarroso
```

While on arm:

```
NVIM v0.5.0-dev
Build type: Release
Lua 5.1
Compilation:
Compiled by dbarroso
```

Main issue is that lots of nvim plugins require luajit and don't work with lua 5.1

**Expected behavior**

neovim should be compiled against luajit.

**Screenshots**

N/A

**Additional context**

**Notify maintainers**

@manveru @rvolosatovs @ma27

**Metadata**

Intel:

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.13`
 - channels(dbarroso): `"darwin, home-manager, nixpkgs-21.11pre299378.db6e089456c"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/dbarroso/.nix-defexpr/channels/nixpkgs`
 ```

Arm:

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(dbarroso): `"darwin, home-manager, nixpkgs-21.11pre299378.db6e089456c"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/dbarroso/.nix-defexpr/channels/nixpkgs
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by rvolosatovs**
###### Motivation for this change
Upstream update.
~`0.5.0` is not released yet - this branch tracks latest nightly until then.
I will be doing my best to keep this up-to-date with latest nightly.
While we're waiting for `0.5.0` to be released, we can already prepare for it in this PR.
Added a new `neovim-nightly` package, which tracks nightly https://github.com/neovim/neovim/releases/tag/nightly~

It's finally here! :tada: 
Closes https://github.com/NixOS/nixpkgs/issues/128959

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rvolosatovs** [comment]
@GrahamcOfBorg build neovim

File: pkgs/applications/editors/neovim/default.nix [hunk 1]
```diff
@@ -31,13 +32,13 @@ let
...
     pname = "neovim-unwrapped";
-    version = "0.4.4";
+    version = "0.5.0";
 
     src = fetchFromGitHub {
       owner = "neovim";
       repo = "neovim";
-      rev = "v${version}";
-      sha256 = "11zyj6jvkwas3n6w1ckj3pk6jf81z1g7ngg4smmwm7c27y2a6f2m";
+      rev = "78f0f00cd5f6f09320851e51fe61eb818e595f39";
```
Comment (SuperSandro2000) [inline pkgs/applications/editors/neovim/default.nix:40]: Please fetch a tag or change the version to unstable-XXXX-XX-XX.

Comment (rvolosatovs) [reply pkgs/applications/editors/neovim/default.nix:40]: This PR will be updated once `0.5.0` is released. `0.5.0` will be a stable release.

Comment (rvolosatovs) [reply pkgs/applications/editors/neovim/default.nix:40]: We could also maintain 2 versions of neovim and track nightly as well

**Comment by rvolosatovs** [comment]
Updated PR with this approach https://github.com/NixOS/nixpkgs/pull/110837#discussion_r564504539

**Comment by rvolosatovs** [comment]
@GrahamcOfBorg build neovim-nightly

File: pkgs/applications/editors/neovim/nightly.nix [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+        - Improve extensibility with a new plugin architecture
+      '';
+      homepage    = "https://www.neovim.io";
+      # "Contributions committed before b17d96 by authors who did not sign the
+      # Contributor License Agreement (CLA) remain under the Vim license.
+      # Contributions committed after b17d96 are licensed under Apache 2.0 unless
+      # those contributions were copied from Vim (identified in the commit logs
+      # by the vim-patch token). See LICENSE for details."
+      license = with licenses; [ asl20 vim ];
+      maintainers = with maintainers; [ rvolosatovs ];
```
Comment (rvolosatovs) [inline pkgs/applications/editors/neovim/nightly.nix:140]: Set myself as the only maintainer here, as it seems that I'm the only one interested in maintaining the nightly

File: pkgs/applications/editors/neovim/nightly.nix [hunk 3]
```diff
@@ -0,0 +1,143 @@
+{ lib, stdenv, fetchFromGitHub, cmake, gettext, msgpack, libtermkey, libiconv
```
Comment (rvolosatovs) [inline pkgs/applications/editors/neovim/nightly.nix:1]: Except for the `tree-sitter` portions this is essentially copy-paste of `default.nix`

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110837` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>neovim-nightly-unwrapped: log <a href="https://termbin.com/go51x">https://termbin.com/go51x</a></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110837` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>neovim-nightly-unwrapped</li>
</ul>
</details>

File: pkgs/top-level/all-packages.nix [hunk 4]
```diff
@@ -25292,8 +25292,16 @@ in
       luajit;
   };
 
+  neovim-nightly-unwrapped = callPackage ../applications/editors/neovim/nightly.nix {
+    lua =
+      # neovim doesn't work with luajit on aarch64: https://github.com/neovim/neovim/issues/7879
+      if stdenv.isAarch64 then lua5_1 else
+      luajit;
```
Comment (thiagokokada) [inline pkgs/top-level/all-packages.nix:25299]: This bug doesn't seem to apply anymore (it was closed quite long time ago).

**Comment by teto** [comment]
Why duplicate everything instead of an override with just treesitter ?

I am on the fence for this one. I've wanted to provide a neovim nightly in nixpkgs for a long time but was afraid it would be rejected (for valid reasons: if everyone starts packaging a pseudo-nigthly for its software, it can get out of hands). Instead I've added a flake to neovim so that one can install a true nightly via flakes see https://nixos.wiki/wiki/Neovim for doc.

As a datapoint, I hope we can release 0.5 in Ferbuary and no later than March so there is not long to wait.

**Comment by rvolosatovs** [comment]
> Why duplicate everything instead of an override with just treesitter ?
> 
> I am on the fence for this one. I've wanted to provide a neovim nightly in nixpkgs for a long time but was afraid it would be rejected (for valid reasons: if everyone starts packaging a pseudo-nigthly for its software, it can get out of hands). Instead I've added a flake to neovim so that one can install a true nightly via flakes see [nixos.wiki/wiki/Neovim](https://nixos.wiki/wiki/Neovim) for doc.
> 
> As a datapoint, I hope we can release 0.5 in Ferbuary and no later than March so there is not long to wait.

I agree as well and will revert the PR to it's original state (draft simply updating the version to `0.5.0`)

**Comment by teto** [comment]
make sure it's ready https://neovim.discourse.group/t/neovim-0-5-release-stream-7-2-21-at-16-00-utc-12-00-pm-est/654 ;)

**Comment by rvolosatovs** [comment]
Updated locally to latest nightly, but build fails with
```
  /nix/store/aigvlxh2aqjqd1wcnk1dr8cjml6dq846-binutils-2.35.1/bin/ld: /build/nvim.Naorac.ltrans27.ltrans.o: in function `node_rawquery':
  <artificial>:(.text+0x11d8): undefined reference to `ts_query_cursor_set_match_limit'
  collect2: error: ld returned 1 exit status
  make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3525: bin/nvim] Error 1
  make[1]: *** [CMakeFiles/Makefile2:3027: src/nvim/CMakeFiles/nvim.dir/all] Error 2
  make: *** [Makefile:171: all] Error 2
```

Caused by https://github.com/neovim/neovim/pull/14915 (see discussion below)

The issue is that current neovim build depends on unreleased tree-sitter functionality.
Should we patch tree-sitter? It doesn't sound like pathset would be small according to https://github.com/neovim/neovim/pull/14915#issuecomment-870423051

Otherwise, perhaps we can reach out to tree-sitter maintainters and ask if they would make a new release before Friday?

**Comment by rvolosatovs** [comment]
cc @teto

**Comment by carlocab** [comment]
I opened tree-sitter/tree-sitter#1216 to see if they might cut a new release tag.

**Comment by tomcur** [comment]
Upstream has an open PR to put the function call behind a feature guard (https://github.com/neovim/neovim/pull/14930). It builds successfully:

```
$ nix build 'github:neovim/neovim/7e8a8482e8e474b9ec45c1bd147dd0b0f4ff03af?dir=contrib'
$ ./result/bin/nvim --version
NVIM v0.5.0-dev
...
```

**Comment by rvolosatovs** [comment]
> Upstream has an open PR to put the function call behind a feature guard ([neovim/neovim#14930](https://github.com/neovim/neovim/pull/14930)). It builds successfully:
> 
> ```
> $ nix build 'github:neovim/neovim/7e8a8482e8e474b9ec45c1bd147dd0b0f4ff03af?dir=contrib'
> $ ./result/bin/nvim --version
> NVIM v0.5.0-dev
> ...
> ```

Added it in https://github.com/NixOS/nixpkgs/pull/110837/commits/4069de517152e62aa1eed82bae8894edd60ca07c

**Comment by rvolosatovs** [comment]
FYI, latest nightly with tree-sitter 0.20.0 available in my `nixos-unstable` branch https://github.com/rvolosatovs/nixpkgs/tree/nixos-unstable
In particular, this commit https://github.com/rvolosatovs/nixpkgs/commit/c17c3eb2c52f29602a0022b708e6d7c21962e440 if you want to check it out

**Comment by rvolosatovs** [comment]
@GrahamcOfBorg build neovim

File: pkgs/top-level/all-packages.nix [hunk 5]
```diff
@@ -27444,10 +27444,7 @@ in
   wrapNeovimUnstable = callPackage ../applications/editors/neovim/wrapper.nix { };
   wrapNeovim = neovim-unwrapped: lib.makeOverridable (neovimUtils.legacyWrapper neovim-unwrapped);
   neovim-unwrapped = callPackage ../applications/editors/neovim {
-    lua =
-      # neovim doesn't work with luajit on aarch64: https://github.com/neovim/neovim/issues/7879
-      if stdenv.isAarch64 then lua5_1 else
-      luajit;
+    lua = luajit;
```
Comment (gebner) [inline pkgs/top-level/all-packages.nix:27447]: Have you verified that luajit now works on aarch64?  Reading through the neovim issue, there's still people running into this bug.  Apparently it might work on some unspecified master version of luajit, but I don't know if that version is already in nixpkgs.

Comment (rvolosatovs) [reply pkgs/top-level/all-packages.nix:27447]: https://github.com/NixOS/nixpkgs/pull/110837#discussion_r564673401 @thiagokokada ?

Comment (rvolosatovs) [reply pkgs/top-level/all-packages.nix:27447]: We could potentially extract this into another PR if there are concerns, I did manage to run this on m1 mac earlier without issues, and I rely on lua heavily for configuration. I'd guess that should mean it works?

Comment (gebner) [reply pkgs/top-level/all-packages.nix:27447]: Ah, if you've tested it then that should be fine.  I just wanted to make sure that you didn't remove the override just because the neovim bug has been closed.

**Comment by fortuneteller2k** [comment]
@ofborg eval

**Review by moni-dz — APPROVED** [review]

**Review by Kranzes — APPROVED** [review]

**Comment by lovesegfault** [comment]
Testing this

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 110837` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>gnvim</li>
    <li>neovim</li>
    <li>neovim-qt</li>
    <li>neovim-qt-unwrapped</li>
    <li>neovim-remote</li>
    <li>neovim-unwrapped</li>
    <li>nvimpager</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 110837` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>gnvim</li>
    <li>neovim</li>
    <li>neovim-qt</li>
    <li>neovim-qt-unwrapped</li>
    <li>neovim-remote</li>
    <li>neovim-unwrapped</li>
    <li>nvimpager</li>
  </ul>
</details>
