### PR TITLE
mold: switch to wrapped by default

### PR DESCRIPTION
**Pull request by dpc**
Unfortunately `mold` linker has been unwrapped by default in nixpkgs for a while now, and at some point `mold-wrapped` was added to address it. This is opposite to what is typically done, so would be great to revert it.

There are two approaches that I can see:

* #461063 phase it out
* #461050 just switch, as the wrapped version probably works better for most downstream consumers anyway

## Things done

- Built on platform:
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by azahi** [comment]
I'm okay with a simple switch, we might need to add a release notes entry for this though.

**Comment by Ericson2314** [comment]
This is somewhat orthogonal, but can you make also make the srdenv adapter use the wrapped one instead of rewrapping?

**Comment by tobim** [comment]
Would be nice, but unfortunately does not work. My initial version also failed for cross. Here is what works:
```diff
diff --git c/pkgs/stdenv/adapters.nix i/pkgs/stdenv/adapters.nix
index 5878cbb81a5a..6b16f43b8de3 100644
--- c/pkgs/stdenv/adapters.nix
+++ i/pkgs/stdenv/adapters.nix
@@ -310,9 +310,13 @@ rec {
       let
         bintools = stdenv.cc.bintools.override {
           extraBuildCommands = ''
-            wrap ld.mold ${../build-support/bintools-wrapper/ld-wrapper.sh} ${pkgs.buildPackages.mold}/bin/ld.mold
-            wrap ${stdenv.cc.bintools.targetPrefix}ld.mold ${../build-support/bintools-wrapper/ld-wrapper.sh} ${pkgs.buildPackages.mold}/bin/ld.mold
-            wrap ${stdenv.cc.bintools.targetPrefix}ld ${../build-support/bintools-wrapper/ld-wrapper.sh} ${pkgs.buildPackages.mold}/bin/ld.mold
+            pushd $out/bin
+            ln -s ${pkgs.buildPackages.mold}/bin/${stdenv.cc.bintools.targetPrefix}ld.mold ${stdenv.cc.bintools.targetPrefix}ld.mold
+          '' # Pre-generated configure scripts call the linker binary without the target prefix when cross compiling.
+          + lib.optionalString (stdenv.cc.bintools.targetPrefix != "") ''
+            ln -s ${stdenv.cc.bintools.targetPrefix}ld.mold ld.mold
+          '' + ''
+            popd
           '';
         };
       in
```

Tested with:
```nix
let
  overlay = finalPkgs: prevPkgs: {
    hello = prevPkgs.hello.override {
      stdenv = finalPkgs.useMoldLinker finalPkgs.stdenv;
    };
  };
  pkgs = import ./. { overlays = [ overlay ]; };
in
{
  native = pkgs.hello;
  cross = pkgs.pkgsCross.aarch64-multiplatform.hello;
}
```

**Review by tobim — APPROVED** [review]

**Review by philiptaron — CHANGES_REQUESTED** [review]
Add release notes and I'll merge it.

**Review by philiptaron — APPROVED** [review]

**Comment by trofi** [comment]
Bisect claims it broke `evcxr` in a468b2ed92390d5bc7044101cb57cf5b13b98c86. Before it worked:

```
$ echo 42 | nix run -f. evcxr
Welcome to evcxr. For help, type :help
42
```

Now it fails as:

```
$ echo 42 | nix run -f. evcxr
Welcome to evcxr. For help, type :help
Error: Compilation failed, but no parsable errors were found. STDERR:
mold: fatal: unknown command line option: -run

STDOUT:

```
