### PR TITLE
cot: fixes for python312

### LINKED ISSUE #362127: Build failure: cot-2.2.1
cot-2.2.1 fails building on latest nixos-24.11 release branch (b681065d0919f7eb5309a93cea2cfa84dec9aa88)

## Build log

<details>

<summary>Build Log</summary>

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing pytest-check-hook
Using pytestCheckPhase
Running phase: unpackPhase
@nix {"action":"setPhase","phase":"unpackPhase"}
unpacking source archive /nix/store/z1x4gbpira9jzfj4cqy1ikr7p49s07cd-cot-2.2.1.tar.gz
source root is cot-2.2.1
setting SOURCE_DATE_EPOCH to timestamp 1575474333 of file cot-2.2.1/setup.cfg
Running phase: patchPhase
@nix {"action":"setPhase","phase":"patchPhase"}
substituteStream() in derivation python3.12-cot-2.2.1: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'setup.py')
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix {"action":"setPhase","phase":"updateAutotoolsGnuConfigScriptsPhase"}
Running phase: configurePhase
@nix {"action":"setPhase","phase":"configurePhase"}
no configure script, doing nothing
Running phase: buildPhase
@nix {"action":"setPhase","phase":"buildPhase"}
Executing setuptoolsBuildPhase
/build/cot-2.2.1/versioneer.py:418: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/build/cot-2.2.1/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 156, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/cot-2.2.1/versioneer.py", line 1476, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/build/cot-2.2.1/versioneer.py", line 1408, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/cot-2.2.1/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

</details>

## Metadata

```shell
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241025.18536bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(jan): `"nixos"`
 - channels(root): `"nix-ld, nixos, nixos2111-21.11, unstable"`
 - nixpkgs: `/etc/nixpkgs`
``` 

## Notify maintainers

@evanjs

### PR DESCRIPTION
**Pull request by con-f-use**
Closes #362127

- distutils was removed from the CPython standard library this PR adds it as regular python package
- `SafeConfigParser` used in "versioneer" was renamed to `ConfigParser`

Marked broken in #326930

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by AndersonTorres — APPROVED** [review]

**Comment by Aleksanaa** [comment]
@ofborg build python311Packages.cot python312Packages.cot

**Comment by NickCao** [comment]
You can simply delete versioneer.py and use the packaged version. See `pkgs/development/python-modules/sphinx-material/default.nix` for an example.

**Comment by con-f-use** [comment]
The rest of cot packaging is not compatible with the packaged versioneer. I don't want to go down that rabbit hole and cot upstream has not seen a commit in 5 years.

**Comment by con-f-use** [comment]
I take that back. It does work, Nick. Don't know what I did, when first I tried. If everyone is good with the new version, I'd squash my commits and we can merge.

**Comment by JohnRTitor** [comment]
@ofborg build python311Packages.cot python312Packages.cot

**Review by JohnRTitor — APPROVED** [review]
