### ISSUE TITLE
glibc doesn't cross-compile to AArch64 on 19.09

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#70406]
**Describe the bug**
Currently attempting to cross-compile `glibc` on the 19.09 branch (10e61bf5be57736035ec7a804cb0bf3d083bf2cf) fails due to warnings.

**To Reproduce**
```
$ git clone git@github.com:nixos/nixpkgs
$ git -C nixpkgs checkout 19.09-beta
$ cat >test.nix <<EOF
let
  nixpkgs = import ./nixpkgs {
    crossSystem = (import ./nixpkgs/lib).systems.examples.aarch64-multiplatform;
  };
in nixpkgs.glibc
EOF
$ nix build -f test.nix
```
This fails with:
```
nss_nisplus/nisplus-parser.c: In function '_nss_nisplus_parse_pwent':
nss_nisplus/nisplus-parser.c:90:7: error: 'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]
       strncpy (first_unused, numstr, len);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nss_nisplus/nisplus-parser.c:106:7: error: 'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]
       strncpy (first_unused, numstr, len);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [../o-iterator.mk:9: /build/build/nis/nisplus-parser.os] Error 1
make[2]: Leaving directory '/build/glibc-2.27/nis'
make[1]: *** [Makefile:215: nis/others] Error 2
make[1]: Leaving directory '/build/glibc-2.27'
make: *** [Makefile:9: all] Error 2
builder for '/nix/store/209s6slyg85z1a7mig0xw4qdbbkf9jr7-glibc-2.27-aarch64-unknown-linux-gnu.drv' failed with exit code 2
```

**Expected behavior**

`glibc` builds successfully.

**Additional context**

This appears to be a bug in glibc 2.27 which is fixed by https://sourceware.org/git/?p=glibc.git;a=commit;h=780684eb04298977bc411ebca1eadeeba4877833. Perhaps this patch should be added to the nix derivation?

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- glibc
# a list of nixos modules affected by the problem
module:
```

**Comment by bgamari** [comment]
cc @edolstra

**Comment by matthewbauer** [comment]
I thought this was fixed in https://github.com/NixOS/nixpkgs/commit/3fcc4441d7ab18d10694a3dce3c8644339bcaf9d, but it needs a backport

**Comment by jonringer** [comment]
@bgamari is this still an issue for you?

**Comment by alex-giusi-tiri** [comment]
I have this same kind of issue, but on x86_64, without cross-compiling, when using `nix-env --install --file '<nixpkgs>' --attr userPackages` (I am managing my user packages as described on [NixOS FAQ](https://nixos.wiki/wiki/FAQ#How_can_I_manage_software_with_nix-env_like_with_configuration.nix.3F)), after updating my channel to 19.09; however, even after changing back to other channels (manual link addition + --update; not --rollback), this same-hashed glibc derivation would still be tried to be built, so I am just staying on the 19.09 channel for now, for my user. I am not sure what needs glibc to be built or how to find out:

```bash
$ tail -n 16 nix-env-glibc.log;
nss_nisplus/nisplus-parser.c: In function '_nss_nisplus_parse_pwent':
nss_nisplus/nisplus-parser.c:90:7: error: 'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]
       strncpy (first_unused, numstr, len);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nss_nisplus/nisplus-parser.c:106:7: error: 'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]
       strncpy (first_unused, numstr, len);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [../o-iterator.mk:9: /build/build/nis/nisplus-parser.os] Error 1
make[2]: Leaving directory '/build/glibc-2.27/nis'
make[1]: *** [Makefile:215: nis/others] Error 2
make[1]: Leaving directory '/build/glibc-2.27'
make: *** [Makefile:9: all] Error 2
builder for '/nix/store/xkdyms6r0r1l8yvlpfbk4sd0n53r9bzz-glibc-2.27.drv' failed with exit code 2
cannot build derivation '/nix/store/87nxhb1a795av67101x8yzgvw38s5p5z-user-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/87nxhb1a795av67101x8yzgvw38s5p5z-user-packages.drv' failed
```

The rest of my system is 19.09:
```bash
$ nixos-version;
19.09.1292.e1843646b04 (Loris)
$ nixos-version --hash;
e1843646b04fb564abf6330a9432a76df3269d2f
```

[1] [NixOS FAQ](https://nixos.wiki/wiki/FAQ#How_can_I_manage_software_with_nix-env_like_with_configuration.nix.3F)
[2] [nix-env-glibc.log](https://github.com/NixOS/nixpkgs/files/3877062/nix-env-glibc.log)
[3] e1843646b04fb564abf6330a9432a76df3269d2f

**Comment by alyssais** [comment]
19.09 is no longer supported, and this appears to work on 20.09 and master, so I’m going to close this.
