### PR TITLE
python3Packages.ifcopenshell: fix build with boost 1.91

### LINKED ISSUE #562782: Build failure: python314Packages.ifcopenshell
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

build python314Packages.ifcopenshell

### Can Hydra reproduce this build failure?

Please select the Hydra Status.

### Link to Hydra build job

Hydra keeps giving 500 errors

### Relevant log output

```console
/build/source/src/ifcgeom/mapping/IfcCShapeProfileDef.cpp:59:30: error: converting to ‘boost::optional<double>’ from initializer list would use explicit constructor ‘constexpr boost::optional<T>::optional(U&&) [with U = double&; typename>
/nix/store/kfyd72dw5vfdx12rwqnd8vrivq7r947c-boost-1.91.0-dev/include/boost/optional/detail/union_optional.hpp:395:24: note: ‘constexpr boost::optional<T>::optional(U&&) [with U = double&; typename std::enable_if<std::is_constructible<T, >
  395 |     constexpr explicit optional(U&& v)
      |                        ^~~~~~~~
/build/source/src/ifcgeom/mapping/IfcCShapeProfileDef.cpp:59:30: error: converting to ‘boost::optional<double>’ from initializer list would use explicit constructor ‘constexpr boost::optional<T>::optional(U&&) [with U = double&; typename>
   59 |         return profile_helper(m4, {
      |                ~~~~~~~~~~~~~~^~~~~~
   60 |                 {{-x,-y},{f2}},
      |                 ~~~~~~~~~~~~~~~
   61 |                 {{x,-y},{f2}},
      |                 ~~~~~~~~~~~~~~
   62 |                 {{x,-y + d2}},
      |                 ~~~~~~~~~~~~~~
   63 |                 {{x - d1,-y + d2}},
      |                 ~~~~~~~~~~~~~~~~~~~
   64 |                 {{x - d1,-y + d1},{f1}},
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~
   65 |                 {{-x + d1,-y + d1},{f1}},
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~
   66 |                 {{-x + d1,y - d1},{f1}},
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~
   67 |                 {{x - d1,y - d1},{f1}},
      |                 ~~~~~~~~~~~~~~~~~~~~~~~
   68 |                 {{x - d1,y - d2}},
      |                 ~~~~~~~~~~~~~~~~~~
   69 |                 {{x,y - d2}},
      |                 ~~~~~~~~~~~~~ 
   70 |                 {{x,y},{f2}},
      |                 ~~~~~~~~~~~~~ 
   71 |                 {{-x,y},{f2}}
      |                 ~~~~~~~~~~~~~ 
   72 |         });
      |         ~~                    
/nix/store/kfyd72dw5vfdx12rwqnd8vrivq7r947c-boost-1.91.0-dev/include/boost/optional/detail/union_optional.hpp:395:24: note: ‘constexpr boost::optional<T>::optional(U&&) [with U = double&; typename std::enable_if<std::is_constructible<T, >
  395 |     constexpr explicit optional(U&& v)
```

### Additional context

_No response_

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 7.2.4, NixOS, 26.11 (Zokor), 26.11.20260908.d6524aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.95.2
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux, x86_64-v4-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: ~/.config/nix/nix.conf:/nix/store/r4av557y77ipkxirm9p27adq6f7a70lx-stylix-kde-config/nix/nix.conf:/etc/xdg/nix/nix.conf:~/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:~/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/<username>/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/i3x3d9ym1ja94vpjn14in2snyg2rpnnn-lix-2.95.2/share`
 - nixpkgs: `/nix/store/j0xsrr9a6dx6b4rf3lnzmak43ff82cs6-source`

### Notify maintainers

@imincik @autra @l0b0 @nh2 @nialov @sikmir @willcohen

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by srounce**
boost 1.91 rewrote `boost::optional` and its converting constructor is now unconditionally explicit, so the aggregate brace-init of the `radius` member in the `profile_point` structs (`src/ifcgeom/profile_helper.h`) no longer compiles. This adds a patch switching those members to `std::optional<double>`, which keeps a non-explicit converting constructor, so all call sites compile unchanged. The project builds with C++17. No fix exists upstream yet.

Fixes #562782

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [x] [Package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests) at `passthru.tests` (full pytest suite ran in checkPhase: 1348 passed)
- [ ] Ran `nixpkgs-review` on this PR.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md), [pkgs/README.md](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md) and other READMEs.
- [x] Follows the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy): patch and this PR summary authored with Claude Code (claude-fable-5), reviewed and build-tested by me.

### CODE REVIEW

**Comment by hatch01** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 563014`
Commit: `2664acf7876c5e5b8f520875345fb92f1e39939c`

---
### `x86_64-linux`
<details>
  <summary>✅ 6 packages built:</summary>
  <ul>
    <li>freecad</li>
    <li>python313Packages.ifcopenshell</li>
    <li>py3dtiles</li>
    <li>python314Packages.ifcopenshell</li>
    <li>python314Packages.py3dtiles</li>
    <li>python313Packages.py3dtiles</li>
  </ul>
</details>

**Comment by autra** [comment]
I think it would be better to iterate on https://github.com/NixOS/nixpkgs/pull/531034/changes instead of fixing this outdated version. I had trouble getting a reviewer...

**Comment by hatch01** [comment]
@autra Maybe add a "fixes:" in your PR to get more eyes on it

**Comment by autra** [comment]
@hatch01 actually, my PR doesn't compile currently. I suspect your patch may help (even though it might not be enough). So I'm backtracking on my previous comment, let's merge this one and I'll rebase. Thanks!

**Review by autra — APPROVED** [review]
Looks good!

**Review by phanirithvij — APPROVED** [review]
LGTM ran nixpkgs-review on x86_64-linux.

**Review by imincik — APPROVED** [review]
Thank you very much for fix @srounce ! Looks good to me as well.
