### ISSUE TITLE
broadcom-wl-dkms: Doesn't compile with kernel >= 5.9

### ISSUE THREAD

**Issue by bagnaram** [NixOS/nixpkgs#101040]
**Describe the bug**
In kernel versions before 5.9 there was a macro called "segment_eq". This macro was only used to implement "uaccess_kernel"  and removed with 5.9.0. Now broadcom-wl-dkms fails to build as it can't find it.

See: for patch https://bugs.archlinux.org/task/68030

**To Reproduce**

1. Enable broadcom-sta
```
boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
```

**Screenshots**
```
/build/broadcom-sta/src/wl/sys/wl_linux.c:1667:6: error: implicit declaration of function 'segment_eq' [-Werror=implicit-function-declaration]
```

**Notify maintainers**

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.8.7, NixOS, 21.03.git.d44dbf3549a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-21.03pre246543.24c9b05ac53"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mannp** [comment]
The same issue for me, did you find a fix as it is very quiet in here otherwise.

**Comment by bagnaram** [comment]
I have a fix for it: Create the file `linux-5.9.patch` and apply to the broadcom-sta package

```diff
diff --git a/src/wl/sys/wl_linux.c b/src/wl/sys/wl_linux.c
index c8c168d..39706ae 100644
--- a/src/wl/sys/wl_linux.c
+++ b/src/wl/sys/wl_linux.c
@@ -1647,9 +1647,13 @@ wl_ioctl(struct net_device *dev, struct ifreq *ifr, int cmd)
                goto done2;
        }

+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 9, 0)
+       if (uaccess_kernel())
+               buf = ioc.buf;
+#else
        if (segment_eq(get_fs(), KERNEL_DS))
                buf = ioc.buf;
-
+#endif
        else if (ioc.buf) {
                if (!(buf = (void *) MALLOC(wl->osh, MAX(ioc.len, WLC_IOCTL_MAXLEN)))) {
                        bcmerror = BCME_NORESOURCE;
```

**Comment by mannp** [comment]
Hi @bagnaram thanks for the reply and the solution :+1: 

I am not sure if 5.9 is a cutting edge kernel on nix, as am not really looking to patch things to get a working distro.

As I cannot currently get 5.8 to build either I may try your patch to at least get a working installation.

Cheers.

**Comment by bbigras** [comment]
Any progress on this?

**Comment by siraben** [comment]
I ran into this issue today when trying to set `kernelPackages = pkgs.linuxPackages_latest;` in my `configuration.nix`.

**Comment by SebastienWae** [comment]
For some reason @bagnaram's patch was on the wrong lines for me.
```diff
diff --git a/src/wl/sys/wl_linux.c b/src/wl/sys/wl_linux.c
index 0d05100..7a972b9 100644
--- a/src/wl/sys/wl_linux.c
+++ b/src/wl/sys/wl_linux.c
@@ -1643,8 +1643,13 @@ wl_ioctl(struct net_device *dev, struct ifreq *ifr, int cmd)
 		goto done2;
 	}
 
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 9, 0)
+if (uaccess_kernel())
+  buf = ioc.buf;
+#else
 	if (segment_eq(get_fs(), KERNEL_DS))
 		buf = ioc.buf;
+#endif
 
 	else if (ioc.buf) {
 		if (!(buf = (void *) MALLOC(wl->osh, MAX(ioc.len, WLC_IOCTL_MAXLEN)))) {

```
