### ISSUE TITLE
Build failure: neomutt

### ISSUE THREAD

**Issue by hraban** [NixOS/nixpkgs#232074]
### Steps To Reproduce

1. `nix run github:NixOS/nixpkgs/master#neomutt` on darwin aarch64

### Build log
see https://github.com/NixOS/nixpkgs/runs/13454777089

### Additional context

Since https://github.com/NixOS/nixpkgs/pull/231638 neomutt is broken on darwin-aarch64. See the CI output: https://github.com/NixOS/nixpkgs/runs/13454777089

Tangent: is it normal that a failing CI build wasn't marked as a failed check, but rather just ignored?

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(user): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/hnvgbhbvd5mq8fzppw22ifrcnngd3fqc-source`
```

**Comment by kciredor** [comment]
Broken on Darwin x86-64 as well.

**Comment by dbaynard** [comment]
[neomutt | MacPorts](https://ports.macports.org/port/neomutt/details/) seems to work — I can't tell whether they are running the tests, though, or not.

Here are the failing tests.

```console
Test test_editor_backspace...                   [ FAILED ]
  Case Common setup:
    editor_backspace.c:86: Check editor_buffer_get_lastchar(es) == 2... failed
    editor_backspace.c:87: Check editor_buffer_get_cursor(es) == 2... failed
Test test_editor_backward_char...               [ FAILED ]
  Case Common setup:
    editor_backward_char.c:87: Check editor_buffer_get_cursor(es) == 2... failed
Test test_editor_delete_char...                 [ FAILED ]
  Case Common setup:
    editor_delete_char.c:88: Check editor_buffer_get_lastchar(es) == 2... failed
Test test_editor_forward_char...                [ FAILED ]
  Case Common setup:
    editor_forward_char.c:88: Check editor_buffer_get_cursor(es) == 4... failed
Test test_editor_kill_eow...                    [ FAILED ]
  Case Common setup:
    editor_kill_eow.c:76: Check editor_buffer_get_lastchar(es) == 13... failed
Test test_editor_kill_word...                   [ FAILED ]
  Case Common setup:
    editor_kill_word.c:87: Check editor_buffer_get_lastchar(es) == 12... failed
    editor_kill_word.c:88: Check editor_buffer_get_cursor(es) == 6... failed
```

**Comment by MichielDerhaeg** [comment]
Latest version seems to work (20230517 currently) for me.
But because it doesn't seem to run the tests:
```
running tests
check flags: -j10 SHELL=/nix/store/ag6lcqchlfb3nsn71slrdr9c60a4gf88-bash-5.2-p15/bin/bash VERBOSE=y test
make: Nothing to be done for 'test'.
```

**Comment by kciredor** [comment]
Looking at the latest comment on the already closed issue here: https://github.com/NixOS/nixpkgs/issues/233347#issuecomment-1597549766

This issue could use some love. Neomutt is broken on MacOS and it looks like it's the derivation, not upstream.

**Comment by howarddo2208** [comment]
I can't install neomutt on MacOS with home-manager too
```
ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
Undefined symbols for architecture x86_64:
  "_fmemopen", referenced from:
      _test_mutt_convert_file_to in mutt_convert_file_to.o
      _test_mutt_convert_file_from_to in mutt_convert_file_from_to.o
      _test_mutt_rfc822_read_line in mutt_rfc822_read_line.o
ld: symbol(s) not found for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:1709: test/neomutt-test] Error 1
error: builder for '/nix/store/md05gx1j52nlb3wi8xyvrjxfwc98glma-neomutt-20230512.drv' failed with exit code 2;
       last 10 log lines:
       > ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
       > ld: warning: directory not found for option '-L/nix/store/31zl3spxz18c13kr068a49yx2w07vwbw-neomutt-20230512/lib'
       > Undefined symbols for architecture x86_64:
       >   "_fmemopen", referenced from:
       >       _test_mutt_convert_file_to in mutt_convert_file_to.o
       >       _test_mutt_convert_file_from_to in mutt_convert_file_from_to.o
       >       _test_mutt_rfc822_read_line in mutt_rfc822_read_line.o
       > ld: symbol(s) not found for architecture x86_64
       > clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       > make: *** [Makefile:1709: test/neomutt-test] Error 1
       For full logs, run 'nix-store -l /nix/store/md05gx1j52nlb3wi8xyvrjxfwc98glma-neomutt-20230512.drv'.
```

**Comment by Smaug123** [comment]
The failing tests were disabled upstream in https://github.com/neomutt/neomutt/pull/3933

**Comment by Smaug123** [comment]
(@howarddo2208 That's a different bug which you should probably raise separately.)

**Comment by ahmedelgabri** [comment]
Unfortunately, the latest fix didn't work for my Intel Mac, some tests are failing for me. [error.log](https://github.com/NixOS/nixpkgs/files/12565715/error.log)

I tested using `shell.nix` because I didn't know how to do overrides from the CLI

```nix
with import <nixpkgs>
{
  overlays = [
    (_: prev: {
      notmuch = prev.notmuch.override {
        withEmacs = false;
      };
    })
  ];
};
mkShell {
  # name = "";
  buildInputs = [
    (neomutt.override {
      enableLua = true;
    })
  ];
}

```

**Comment by wegank** [comment]
Yes, the failure on `x86_64-darwin` should be a separate bug (and could probably be fixed by putting `memstreamHook` into `nativeBuildInputs`).
