### ISSUE TITLE
[staging] xorg.xorgcffiles: 1.0.6 -> 1.0.7 broke transfig

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#135337]
On `nixpkgs` `staging` branch observed build failure of `transfig` (a build-time dependency of `ccache`):

```
$ nix-build -A transfig

warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
these derivations will be built:
  /nix/store/dgh097bssnkhig4gvh18rkly6q01qibr-transfig-3.2.4.drv
building '/nix/store/dgh097bssnkhig4gvh18rkly6q01qibr-transfig-3.2.4.drv'...
unpacking sources
unpacking source archive /nix/store/i6hv2s6lsz130b9v2bpirrcbpj6vv96g-transfig.3.2.4.tar.gz
source root is transfig.3.2.4
setting SOURCE_DATE_EPOCH to timestamp 1040319224 of file transfig.3.2.4/fig2dev/Imakefile
patching sources
applying patch /nix/store/50hh9rdf9qjgzhd1j7x5dg1lcm1w9chp-patch-fig2dev-dev-Imakefile.patch
patching file fig2dev/dev/Imakefile
applying patch /nix/store/dwa8y3649p6wivqgvdn09ga5b7502d6j-patch-fig2dev-Imakefile.patch
patching file fig2dev/Imakefile
applying patch /nix/store/nlw6s9l0zy090ilni5w1m2iq25d4yvpv-patch-transfig-Imakefile.patch
patching file transfig/Imakefile
applying patch /nix/store/3mywy351blm0a9w5sbp82aiqa6syhkh3-patch-fig2dev-fig2dev.h.patch
patching file fig2dev/fig2dev.h
applying patch /nix/store/f1fn8cwy1b43aj3kia2rwp6lpvg4nvkz-patch-fig2dev-dev-gensvg.c.patch
patching file fig2dev/dev/gensvg.c
configuring
configuring with imake: ''
imake -DUseInstalled -I/nix/store/kw7q2l24n8apgf3dfncn6hacih2rng4w-imake-1.0.8/lib/X11/config
In file included from Imakefile.c:20:2:
In file included from /nix/store/kw7q2l24n8apgf3dfncn6hacih2rng4w-imake-1.0.8/lib/X11/config/Imake.tmpl:109:2:
/nix/store/kw7q2l24n8apgf3dfncn6hacih2rng4w-imake-1.0.8/lib/X11/config/linux.cf:198:10: Warning: non-identical redefinition of XAppLoadDir
In file included from Imakefile.c:20:2:
In file included from /nix/store/kw7q2l24n8apgf3dfncn6hacih2rng4w-imake-1.0.8/lib/X11/config/Imake.tmpl:109:2:
/nix/store/kw7q2l24n8apgf3dfncn6hacih2rng4w-imake-1.0.8/lib/X11/config/linux.cf:105:11: Previous definition was here
make Makefiles
making Makefiles in fig2dev...
make[1]: Entering directory '/build/transfig.3.2.4'
Imakefile.c:20:2: Include file Imake.tmpl not found
imake: Exit code 1.
  Stop.
make[1]: *** [Makefile:998: fig2dev/Makefile] Error 1
make[1]: Leaving directory '/build/transfig.3.2.4'
make: [Makefile:1006: Makefiles] Error 2 (ignored)
make includes
including in ./fig2dev...
make[1]: Entering directory '/build/transfig.3.2.4/fig2dev'
make[1]: *** No rule to make target 'includes'.  Stop.
make[1]: Leaving directory '/build/transfig.3.2.4/fig2dev'
make: *** [Makefile:1064: includes] Error 2
builder for '/nix/store/dgh097bssnkhig4gvh18rkly6q01qibr-transfig-3.2.4.drv' failed with exit code 2
error: build of '/nix/store/dgh097bssnkhig4gvh18rkly6q01qibr-transfig-3.2.4.drv' failed
```

Bisected down to 8675ca0e947f7e847d82828e6bfd4d08822c489c `xorg.xorgcffiles: 1.0.6 -> 1.0.7` commit (/cc @TredwellGit ). The only suspected change in the package is probably a:

```diff
 #if LinuxDistribution == LinuxRedHat
-#define FSUseSyslog            YES
+# define FSUseSyslog           YES
+# define BuildRman             NO
+# define BuildHtmlManPages     NO
+# define ProjectRoot           /usr
+# define ManPath               /usr/share/man
+# define XAppLoadDir           /usr/share/X11/app-defaults
+# define ConfigDir             /usr/share/X11/config
 #endif
```

**Comment by trofi** [comment]
Confirmed by bisecting down to https://gitlab.freedesktop.org/xorg/util/cf/-/commit/d47131ed97ee491bb883c29ec0b106e8d5acfcd3 with this tiny local change:

```
--- a/pkgs/servers/x11/xorg/overrides.nix
+++ b/pkgs/servers/x11/xorg/overrides.nix
@@ -833,6 +833,8 @@ self: super:
   });

   xorgcffiles = super.xorgcffiles.overrideAttrs (attrs: {
+    src = /home/slyfox/dev/git/xorg-cf-files;
+
     postInstall = lib.optionalString stdenv.isDarwin ''
       substituteInPlace $out/lib/X11/config/darwin.cf --replace "/usr/bin/" ""
     '';
```

I wonder why `LinuxDistribution == LinuxRedHat` matches for nixpkgs.

**Comment by trofi** [comment]
It happens because https://github.com/NixOS/nixpkgs/blob/fef0331b1add4741ee60ada0dcfed9990cde157c/pkgs/servers/x11/xorg/imake.patch removes `#define LinuxRedHat     8` and breaks all future enum comparisons. I'll try to amend it.

**Comment by trofi** [comment]
https://github.com/NixOS/nixpkgs/pull/135414 fixed it for me.
