### ISSUE TITLE
yubikey-manager-qt:  NameError: name 'yubikey' is not defined

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#122575]
**Describe the bug**
Yubikey manager starts up but doesn't show any devices. The log shows:

```
qml: qrc:/qml/YubiKey.qml:267: Error: Cannot assign [undefined] to int
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:267: Error: Cannot assign [undefined] to int
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:267: Error: Cannot assign [undefined] to int
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:267: Error: Cannot assign [undefined] to int

```

**To Reproduce**

```
$ ykman-gui
qml: qrc:/qml/YubiKey.qml:267: Error: Cannot assign [undefined] to int
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:267: Error: Cannot assign [undefined] to int
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.count_devices' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:267: Error: Cannot assign [undefined] to int
```

**Expected behavior**
GUI shows devices

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: yubikey-manager-qt
# a list of nixos modules affected by the problem
module:
```

**Comment by avdv** [comment]
FTR, this is apparently caused by 1072da3e3ee2c7ec863aab18c79f5e29aa241065 which upgraded yubikey-manager from 3.1.2 to 4.x whereas yubikey-manager-qt actually depends on 3.1 since 4.x changed the API in a non backward compatible way.

**Comment by DerRockWolf** [comment]
The same (?) issue occurs in `nixos-unstable`.
I don't know since when it's broken, but it still works in `nixos-24.05`.

cc @avdv

log:
```
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 53, in <module>\n    from ykman.otp import (\n\nImportError: cannot import name '_PrepareUploadFailed' from 'ykman.otp' (/nix/store/41c6wpqh91
s5qpykn8bsrnlcyfxg2r92-python3.12-yubikey-manager-5.5.1/lib/python3.12/site-packages/ykman/otp.py)\n"                                                                                                                                         
qml: Cannot import module: yubikey (Traceback (most recent call last):                                                                                                                                                                        
                                                                                                                                                                                                                                              
  File "qrc:///py/yubikey.py", line 53, in <module>                                                                                                                                                                                           
    from ykman.otp import (                                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
ImportError: cannot import name '_PrepareUploadFailed' from 'ykman.otp' (/nix/store/41c6wpqh91s5qpykn8bsrnlcyfxg2r92-python3.12-yubikey-manager-5.5.1/lib/python3.12/site-packages/ykman/otp.py)                                              
)                                                                                                                                                                                                                                             
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"                                                                                             
qml: Function not found: 'yubikey.init' (Traceback (most recent call last):                                                                                                                                                                   
                                                                                                                                                                                                                                              
  File "<string>", line 1, in <module>                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
NameError: name 'yubikey' is not defined                                                                                                                                                                                                      
)                                                                                                                                                                                                                                             
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"                                                                                             
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):                                                                                                                                                     
                                                                                                                                                                                                                                              
  File "<string>", line 1, in <module>                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
NameError: name 'yubikey' is not defined                                                                                                                                                                                                      
)                                                                                                                                                                                                                                             
qml: qrc:/qml/YubiKey.qml:208: TypeError: Cannot read property 'success' of undefined                                                                                                                                                         
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"                                                                                             
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):                                                                                                                                                     
                                                                                                                                                                                                                                              
  File "<string>", line 1, in <module>                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
NameError: name 'yubikey' is not defined                                                                                                                                                                                                      
)
```
