### ISSUE TITLE
Recent changes break emacs-macport build

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#331583]
In the last few days (specifically, this range: https://github.com/NixOS/nixpkgs/compare/038fb464fcfa79b4f08131b07f2d8c9a6bcc4160...c3392ad349a5227f4a3464dce87bcc5046692fce, between commits `038fb464fcfa79b4f08131b07f2d8c9a6bcc4160` and `c3392ad349a5227f4a3464dce87bcc5046692fce`).

The first error in the build is this, followed by many others:
```
In file included from macappkit.m:41:
./macappkit.h:355:1: error: duplicate interface definition for class 'NSTouchBarItem'
@interface NSTouchBarItem : NSObject <NSCoding>
^
```

**Comment by jwiegley** [comment]
I will see if I can git bisect this down further, haven't tried doing that with flakes before...

**Comment by jwiegley** [comment]
Looks like I can do the `bisect` in a `nixpkgs` clone and then build at each step with:
```
nix build --override-input nixpkgs ~/Products/nixpkgs --impure .#darwinConfigurations.vulcan.pkgs.emacs29-macport
```

**Comment by jwiegley** [comment]
Still bisecting. This will not be quick.

**Comment by knl** [comment]
I don't have issues on m1/m3 macs, so it could be a failure on x86 arch. Indeed, this upgrade that runs on x86 darwin failed for me: https://github.com/knl/dotskel/pull/875

On hydra, I found this build as the first one to break: https://hydra.nixos.org/build/267539199

**Comment by jwiegley** [comment]
Hmm.. the commit mentioned in that failing build represents a merge of 694 commits. There are a lot of changes to the `darwin.stdenv` in that set.

My bisect is going slowly enough that I doubt it will finish before my upcoming vacation, so I may not have anything more precise for you until mid-August. Until then, I'll just freeze my personal nixpkgs at `038fb464fcfa79b4f08131b07f2d8c9a6bcc4160`.

**Comment by jwiegley** [comment]
My bisect did not really work out, it couldn't narrow down to the exact commits causing the problem. I guess I'm in the minority of needing this port of Emacs on Intel machines...

**Comment by jwiegley** [comment]
In case anyone else is trying to build Emacs macport for macOS, this gets it building again:
```
configureFlags = [ "CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101201" ];
```

**Comment by citrusmunch** [comment]
The above worked for me! I also wanted to share the snippet from my config since it took me (nix amateur) quite a while to figure out where to actually set those flags. Using lix and nix-darwin with flakes.

- macOS `12.7.5`
- lix `2.91.0`
- nix-darwin: `24.11.20240911.159be5d+darwin4.a0e362a`

```nix
nixpkgs.overlays = [
  (self: super: {
    emacs-macport = super.emacs-macport.overrideAttrs (oldAttrs: {
      configureFlags = oldAttrs.configureFlags
                       ++ [ "CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101201" ];
    });
  })
];
```

I don't know if this is all best practice, but I do have a working emacs installation at the moment!

**Comment by jwiegley** [comment]
@citrusmunch That's very similar to what I have in my own config:
```
emacs29MacPort = pkgs.emacs29-macport.overrideAttrs (o: {
  configureFlags = o.configureFlags ++ [
    "CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101201"
    "CFLAGS=-DMAC_OS_X_VERSION_MIN_REQUIRED=101201"
  ];
});
```
Note that I needed both `MIN` and `MAX` for this to work on both `aarch64` and `x86_64`.
