### PR TITLE
nixos/release: add proxmox LXC and VMA

### LINKED ISSUE #171989: proxmox-image fails to build with qemu 7.0
### Describe the bug
After qemu: 6.2.0 -> 7.0.0 (commit 9d733f3d4975fb3c516a2bf2bf1bc6f50781a553) proxmox-image fails to build.

### Steps To Reproduce
`nix run github:nix-community/nixos-generators -- -f proxmox -I nixpkgs=https://releases.nixos.org/nixos/unstable/nixos-22.05pre375061.c777cdf5c56/nixexprs.tar.xz`

### Expected behavior
Command should produce a vma image

### Actual behavior
Various compilation errors (copied in case others are searching for a fix)
FAILED: libblock.fa.p/vma-writer.c.o
 ../vma-writer.c:206:5: error: too few arguments to function 'aio_set_fd_handler'
../vma-writer.c:209:5: error: too few arguments to function 'aio_set_fd_handler'

### Additional context
We probably need a rebased patch from proxmox:
https://git.proxmox.com/?p=pve-qemu.git;a=history;f=debian/patches/pve/0026-PVE-Backup-add-vma-backup-format-code.patch;h=b37b17c286da3d32945fbee8ee4fd97a418a50db;hb=HEAD

### Notify maintainers
@illustris @SuperSandro2000

### PR DESCRIPTION
**Pull request by illustris**
###### Description of changes

- Fix failing build of proxmox VMA
- Add hydra builds for proxmox VMA and LXC tarball

Closes: https://github.com/NixOS/nixpkgs/issues/171989

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by illustris** [comment]
```
[illustris@illustris-thinkpad:~/src/nixpkgs/.worktree/proxmox-kvm]$ nix-build ./nixos/release.nix -A proxmoxImage
trace: warning: system.stateVersion is not set, defaulting to 22.11. Read why this matters on https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion.
/nix/store/q30abjnd0h8fvb0cvvvgqsg9y5kl2y2i-proxmox-nixos-22.11pre-git
[illustris@illustris-thinkpad:~/src/nixpkgs/.worktree/proxmox-kvm]$ nix-build ./nixos/release.nix -A proxmoxLXC
trace: warning: system.stateVersion is not set, defaulting to 22.11. Read why this matters on https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion.
/nix/store/fwvyckvy5mgzp8mwh1z7xr1h9a6vcds2-tarball
```

**Comment by Profpatsch** [comment]
I don’t know about these parts of the ecosystem, but the changes look good to me.
