### PR TITLE
linuxHeaders: 4.19.16 -> 5.5

### PR DESCRIPTION
**Pull request by orivej**
Linux has reworked its header install process in
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=59b2bd05f5f4dc62979c2e82ddd384f07e8f10bc
It has introduced `make headers` that prepares the headers in ./usr/include, and
made `make headers_install` copy the headers from there using rsync.

###### Motivation for this change

This is needed to use `bpf/xsk.h` from libbpf 0.6: https://github.com/libbpf/libbpf/pull/74#discussion_r373247285 (unless we install replacement linux headers with libbpf).

This obsoletes #77103 that expressed the need for newer linux headers.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
  - built `dpdk` with libbpf 0.6 on Linux: it failed before due to old headers
  - built `pkgsCross.gnu64.linuxHeaders` on macOS: the result looks ok
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/os-specific/linux/kernel-headers/default.nix [hunk 1]
```diff
@@ -39,12 +39,8 @@ let
     # Skip clean on darwin, case-sensitivity issues.
     buildPhase = lib.optionalString (!stdenvNoCC.buildPlatform.isDarwin) ''
       make mrproper $makeFlags
-    ''
-    # For some reason, doing `make install_headers` twice, first without
-    # INSTALL_HDR_PATH=$out then with, is neccessary to get this to work
-    # for darwin cross. @Ericson2314 has no idea why.
-    + ''
```
Comment (orivej) [inline pkgs/os-specific/linux/kernel-headers/default.nix]: Double `make install_headers` is not needed any more.

File: pkgs/os-specific/linux/kernel-headers/default.nix [hunk 2]
```diff
@@ -55,13 +51,9 @@ let
       make headers_install INSTALL_HDR_PATH=$out $makeFlags
     ''
     # Some builds (e.g. KVM) want a kernel.release.
-    + '' mkdir -p $out/include/config
-      echo "${version}-default" > $out/include/config/kernel.release
-    ''
-    # These oddly named file records the `SHELL` passed, which causes bootstrap
-    # tools run-time dependency.
     + ''
-      find "$out" -name '..install.cmd' -print0 | xargs -0 rm
```
Comment (orivej) [inline pkgs/os-specific/linux/kernel-headers/default.nix]: The new `make headers_install` copies only `.h` files.

File: pkgs/os-specific/linux/kernel-headers/no-dynamic-cc-version-check.patch [hunk 3]
```diff
@@ -1,32 +1,12 @@
-diff --git a/Makefile b/Makefile
```
Comment (orivej) [inline pkgs/os-specific/linux/kernel-headers/no-dynamic-cc-version-check.patch]: This patch may not be necessary any more, but I'm not sure.

File: pkgs/os-specific/linux/kernel-headers/no-relocs.patch [hunk 4]
```diff
@@ -1,13 +1,7 @@
...
-index fad55160dcb9..a48c8331cbb2 100644
 --- a/arch/x86/Makefile
 +++ b/arch/x86/Makefile
-@@ -239,7 +239,7 @@ ifdef CONFIG_RETPOLINE
- endif
- 
+@@ -231,3 +231,3 @@ endif
  archscripts: scripts_basic
 -	$(Q)$(MAKE) $(build)=arch/x86/tools relocs
 +	$(Q)$(MAKE) $(build)=arch/x86/tools
```
Comment (orivej) [inline pkgs/os-specific/linux/kernel-headers/no-relocs.patch]: This is still needed, otherwise compilation fails without `elf.h`.

File: pkgs/os-specific/linux/kernel-headers/default.nix [hunk 5]
```diff
@@ -16,7 +16,7 @@ let
     # We do this so we have a build->build, not build->host, C compiler.
     depsBuildBuild = [ buildPackages.stdenv.cc ];
     # `elf-header` is null when libc provides `elf.h`.
-    nativeBuildInputs = [ perl elf-header ];
+    nativeBuildInputs = [ perl rsync elf-header ];
```
Comment (orivej) [inline pkgs/os-specific/linux/kernel-headers/default.nix]: The new `make install_headers` installs the headers using rsync (to copy only `.h` files).

File: pkgs/os-specific/linux/kernel-headers/no-dynamic-cc-version-check.patch (hunk 3 above)
Comment (orivej) [reply pkgs/os-specific/linux/kernel-headers/no-dynamic-cc-version-check.patch]: I have checked that deleting this patch has no effect on the result of `pkgsCross.gnu64.linuxHeaders`, so I've deleted it.

**Comment by orivej** [comment]
I have checked that there is no difference between 5.5 and 5.5.2 (except in the value of `LINUX_VERSION_CODE` in `linux/version.h`), and in general as I understand there should be no difference across all 5.5.* series, therefore we should not update the headers from 5.5 to 5.5.x.

**Comment by thefloweringash** [comment]
This seems to break the bootstrap for aarch64:

```
$ nix-build -A hello -j1
these derivations will be built:
 [...]
building '/nix/store/d5fhzi0dvfdqcjbawv21bhs8pnifxpfl-popt-1.16.drv'...
unpacking sources
unpacking source archive /nix/store/vd3nbw7w1d7yrb89c3vj5kwk3yb8sgf1-popt-1.16.tar.gz
source root is popt-1.16
setting SOURCE_DATE_EPOCH to timestamp 1273006578 of file popt-1.16/test-poptrc
patching sources
configuring
fixing libtool script ./ltmain.sh
configure flags: --disable-static --disable-dependency-tracking --prefix=/nix/store/88izzq2bqs47q7a9q9q7ahl9yi7l6p7c-popt-1.16
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2009-11-20, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2009-11-20

uname -m = aarch64
uname -r = 4.19.68
uname -s = Linux
uname -v = #1-NixOS SMP PREEMPT Thu Jan 1 00:00:01 UTC 1970

/usr/bin/uname -p =
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              =
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.19.68
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1-NixOS SMP PREEMPT Thu Jan 1 00:00:01 UTC 1970
configure: error: cannot guess build type; you must specify one
builder for '/nix/store/d5fhzi0dvfdqcjbawv21bhs8pnifxpfl-popt-1.16.drv' failed with exit code 1
cannot build derivation '/nix/store/awz6s24220mxm03dqq3p61hn05x51mib-rsync-3.1.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jjnrjx8qazviqvlg33i5b68jd0lagkdr-linux-headers-5.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rlkn045ii7sxp91ly4whpbq3ks410kad-glibc-2.27.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zrxffnf7iydi0ahqxl91jj653p9cc9x7-stdenv-linux.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wi7kwn2hkghzf8p5ygcx008gz5h3bbj9-hello-2.10.drv': 1 dependencies couldn't be built
error: build of '/nix/store/wi7kwn2hkghzf8p5ygcx008gz5h3bbj9-hello-2.10.drv' failed
```

**Comment by orivej** [comment]
I can not reproduce this with `nix-build . -A pkgsCross.aarch64-multiplatform.hello` and I don't have access to an aarch64 machine to perform a native build. Could you save the build directory after `nix-build -A hello --keep-failed` and attach it is a tar.gz to this issue? It may also be worth to check if this update is the cause by testing it on top of master (`git checkout master; git cherry-pick -n d48e99d9122119ce1741867b5a7ea682d134f713; nix-build . -A hello`).

**Comment by thefloweringash** [comment]
I think the problem is that rsync is now being required by an earlier stage during stdenv bootstrap. `linuxHeaders` is produced at stage2, so stage2 must be able to build `rsync` and its `popt` dependency.

Starting from stage3 onwards there's a hook that updates outdated `config.guess` files, which matches the error message from `popt`'s configuration failure. Taking this hook and trivially applying it to stage2 is sufficient for me to `nix-build -A hello` on `aarch64-linux`. I also tested armv7l-linux, it was able to produce a linux headers 5.5, but glibc is currently broken so I couldn't build a full stdenv.

```diff
diff --git a/pkgs/stdenv/linux/default.nix b/pkgs/stdenv/linux/default.nix
index 60c0730dce1..cf8705bd891 100644
--- a/pkgs/stdenv/linux/default.nix
+++ b/pkgs/stdenv/linux/default.nix
@@ -255,6 +255,10 @@ in
         libc = getLibc self;
       };
     };
+    extraNativeBuildInputs = [ prevStage.patchelf ] ++
+      # Many tarballs come with obsolete config.sub/config.guess that don't recognize aarch64.
+      lib.optional (!localSystem.isx86 || localSystem.libc == "musl")
+                   prevStage.updateAutotoolsGnuConfigScriptsHook;
   })
```

(diff generated after cherry-picking onto master @ 6932a75d9c48c4587a340ceb384d83e87709d189)

**Comment by orivej** [comment]
That looks like a useful change, but since it is trivial to avoid rsync and this reduces the amount of packages needed to reach stage3, I have done just that. (I have checked that the result does not change.)

**Comment by orivej** [comment]
This update caused a few failures (not in master yet; based on [this eval diff](https://hydra.nixos.org/eval/1570866?filter=x86_64-linux&compare=1570059&full=), checkboxes for fixes):
- [ ] lockdep — error: unknown type name '__aligned_u64' — maybe it defines `__ASSEMBLY__`?
- [ ] dnsmasq — error: 'SIOCGSTAMP' undeclared — probably does not include `linux/sockios.h`
- [ ] can-utils — same as dnsmasq
- [ ] dpdk — error: 'struct xsk_umem_config' has no member named 'flags' — it assumes that if linux-headers are recent than libbpf is recent; we shall update libbpf

**Comment by vcunat** [comment]
dnsmasq was broken on master and I fixed it in 482642a73 (and 944775e0c).

**Comment by orivej** [comment]
Ok, this reached master yesterday (2020-02-19 08:18 UTC).

**Comment by orivej** [comment]
I thought that this is a good candidate for 20.03 since it defaults to Linux 5.4 and the update will allow applications to use newer kernel features; but its backport depends on backporting fixes for the packages that are broken by the update.

**Comment by Ericson2314** [comment]
Thanks @orivej for checking all the thorny cross cases!

**Comment by alyssais** [comment]
Why 5.5, and not 5.4 (LTS)?

**Comment by orivej** [comment]
See https://sourceware.org/glibc/wiki/FAQ#What_version_of_the_Linux_kernel_headers_should_be_used.3F
