### ISSUE TITLE
Boot failing since update to linux-4.8 with grsecurity

### ISSUE THREAD

**Issue by mrobbetts** [NixOS/nixpkgs#20490]
## Issue description
I updated my NixOS (w/ grsecurity) installation to latest master today, and in the process caught the kernel version bump from 4.7.10 to 4.8.8.

Since this update, the system no longer boots. I get (forgive any typing errors, this system doesn't have IPMI!):
```
<<< NixOS Stage 1 >>>

Loading module dm_mod...
modprobe: FATAL: Module dm_mod not found in directory /lib/modules/4.8.8-grsec
running udev...
starting device mapper and LVM...
waiting for device /dev/disk/by-uuid/<blah> to appear.................
Time out waiting for device  /dev/disk/by-uuid/<blah>, trying to mount anyway.
mounting /dev/disk/by-uuid/<blah> on /...
mount: mounting  /dev/disk/by-uuid/<blah> on /mnt-root/ failed: No such device

An error occurred in stage 1 of the boot process, which must mount the root filesystem on '/mnt-root' and then start stage 2.
```

Of course, selecting a previous configuration in grub works fine (thanks, NixOS!). So, let me know if there's anything you want me to try on this system.

**Comment by spacekitteh** [comment]
Can you provide your config? Specifically, kernel info, mount/partition info?

**Comment by mrobbetts** [comment]
Well, the (failing) kernel is 4.8.8 with grsecurity. I fix set some options in my `configuration.nix`:
```
        nixpkgs.config = {
...
                packageOverrides = pkgs: rec {
                        linuxPackages = pkgs.linuxPackages_latest;      # To get latest kernel.
...
                        stdenv = pkgs.stdenv // {
                                platform = pkgs.stdenv.platform // {
                                        kernelExtraConfig =
                                    ''
                                    #CONFIG_CFG80211_INTERNAL_REGDB
                                    EXPERT y
                                    CFG80211_CERTIFICATION_ONUS y
                                    ATH10K_DFS_CERTIFIED y
                                    NET_SCH_HTB y
                                    NET_SCH_CBQ y
                                    NET_SCH_PRIO y
                                    NET_SCH_MULTIQ y
                                    NET_SCH_TBF y
                                    NET_SCH_QFQ y
                                    NET_SCH_CODEL y
                                    NET_SCH_FQ_CODEL y
                                    NET_SCH_FQ y
                                    NET_SCH_INGRESS y
                                    NET_CLS_FW y
                                    NET_CLS_U32 y
                                    NET_CLS_BASIC y
                                    NET_CLS_TCINDEX y
                                    NET_EMATCH y
                                    NET_EMATCH_CMP y
                                    NET_EMATCH_NBYTE y
                                    NET_EMATCH_U32 y
                                    NET_ACT_MIRRED y
                                    '';
                                };
                        };
```

I have just one drive in this system with one partition:
```
# partx --show /dev/disk/by-id/ata-OCZ-VERTEX_YV7X29WZJ5256CAS41XX
NR START      END  SECTORS  SIZE NAME UUID
 1  2048 62533295 62531248 29.8G      25610c33-01
```

**Comment by joachifm** [comment]
The reason is that there are no modules included in the kernel output. Never seen that before. Hrm.

**Comment by spacekitteh** [comment]
Doesn't this override grsec's kernelExtraConfig, rather than merging?

``stdenv = pkgs.stdenv // {
                                platform = pkgs.stdenv.platform // {
                                        kernelExtraConfig =
                                    ''
                                    #CONFIG_CFG80211_INTERNAL_REGDB
                                    EXPERT y
                                    CFG80211_CERTIFICATION_ONUS y
                                    ATH10K_DFS_CERTIFIED y
                                    NET_SCH_HTB y
                                    NET_SCH_CBQ y
                                    NET_SCH_PRIO y
                                    NET_SCH_MULTIQ y
                                    NET_SCH_TBF y
                                    NET_SCH_QFQ y
                                    NET_SCH_CODEL y
                                    NET_SCH_FQ_CODEL y
                                    NET_SCH_FQ y
                                    NET_SCH_INGRESS y
                                    NET_CLS_FW y
                                    NET_CLS_U32 y
                                    NET_CLS_BASIC y
                                    NET_CLS_TCINDEX y
                                    NET_EMATCH y
                                    NET_EMATCH_CMP y
                                    NET_EMATCH_NBYTE y
                                    NET_EMATCH_U32 y
                                    NET_ACT_MIRRED y
                                    '';
                                };
                        };``

**Comment by mrobbetts** [comment]
@spacekitteh, does it?? Eek. I thought it would merge. If it does clobber it, what is the correct way to merge these things?

If it matters, as configured, grsec has always appeared to work (at least in terms of behaving itself properly in `paxtest` and such).

In any case, I think this part of the configuration isn't pertinent to this report -- I didn't change any configuration between the working system and the broken one, I just updated my nixpkgs repo and rebuilt.

**Comment by mrobbetts** [comment]
@joachifm, how can you tell that?? Are you able to reproduce?

**Comment by joachifm** [comment]
@mrobbetts I can tell by looking at the substitute served by the binary cache; there's nothing in there apart from the kernel image & firmware junk, the entire thing is just 12MB. According to the build log, the modules *are* built, so I've no idea what could account for this.

**Comment by joachifm** [comment]
Interesting tidbit from the log: 

> make[2]: execvp: /nix/store/mgdm9y2lhmyb74wwa42qhcl633vbwn26-bash-4.3-p46/bin/bash: Argument list too long

**Comment by joachifm** [comment]
I believe I've tracked down the issue. It occurs in `scripts/Makefile.modinst` where a list of files is passed via command line, exceeding the arglist limit. The result is that the list of modules to be installed is empty, which explains the problem we're encountering here. Why this would occur for grsecurity and not the other kernels, I've no clue, but I suspect there's a more fundamental issue somewhere.

I "fixed" the problem by patching `Makefile.modinst` to use `find -exec` to process the files. I'll probably push the patch as a temporary fix until the actual cause is identified.

**Comment by spacekitteh** [comment]
Interesting; I've had no problem with modules on grsec-4.8.7.

**Comment by joachifm** [comment]
Yeah, this makes no sense to me.

**Comment by joachifm** [comment]
But it occurs on Hydra, and I've reproduced it with two different configs on my own machine. With the patch described above, the build works and the tests pass ...

**Comment by spacekitteh** [comment]
Did it happen on hydra for 4.8.7? I think you didn't merge it for some reason?

**Comment by joachifm** [comment]
4.8.7 was botched by upstream, it didn't build at all. I don't think the fixed 4.8.7 ever had a chance to build on Hydra, due to 4.8.8 coming out almost immediately.

**Comment by spacekitteh** [comment]
Weird, considering I'm running it right now! :confounded:

**Comment by joachifm** [comment]
You're running grsecurity-3.1-4.8.7-201611102210.patch? Then you must be using a custom config that somehow circumvents the bogus module.

The error in question is

> 
/tmp/nix-build-linux-4.8.7.drv-0/linux-4.8.7/kernel/power/snapshot.c:1157:6: error: redefinition of 'clear_free_pages'
 void clear_free_pages(void)

**Comment by spacekitteh** [comment]
@joachifm i am using that patch, but i'm not using a custom kernel config.

**Comment by joachifm** [comment]
I fail to see how that could be. This bug was acknowledged as a botched merge by upstream. How are you using it exactly?

**Comment by spacekitteh** [comment]
I've non-trivially edited my configuration.nix since booting with this kernel; does `nixos-rebuild switch` save a copy of it?

**Comment by spacekitteh** [comment]
```bash [spacekitteh@spaceserv:/nix/var/nix/profiles/system-139-link/kernel-modules/lib/modules/4.8.7/kernel/kernel]$ ls
locking  rcu  sched  time  torture.ko.xz```

Should `power` be included in there?

**Comment by joachifm** [comment]
I don't think there's a loadable module named `power`. Anyway, I take it you're not using the grsecurity nixos module. How are you generally setting up grsec? Via `boot.kernelPatches` or something? What does `zgrep CONFIG_GRKERNSEC= /proc/config.gz` say?

**Comment by spacekitteh** [comment]
Setting it up like so:

```nix  security.grsecurity.enable = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;```

Hmm. `zgrep CONFIG_GRKERNSEC= /proc/config.gz` says nothing. I could have sworn I've had PaX errors since last boot...

**Comment by joachifm** [comment]
The module is designed to allow you to easily set your own grsec enabled package set. With the above setup, you're essentially overriding the grsec package set with vanilla. Now, it is supposed to fail if the selected kernel doesn't satisfy the required kernel config, so it looks like that feature doesn't work ...

**Comment by spacekitteh** [comment]
grsec definitely *was* working since adding the kernelPackages bit, hmm.

**Comment by joachifm** [comment]
The module uses `boot.kernelPackages  = mkDefault ...` which means that setting `kernelPackages` anywhere else overrides it.

**Comment by mrobbetts** [comment]
Thanks @joachifm! This works for me now.

@spacekitteh, can you not do what I'm doing? It seems to work...
```
# zgrep CONFIG_GRKERNSEC= /proc/config.gz
CONFIG_GRKERNSEC=y
```

**Comment by joachifm** [comment]
I just discovered that the modinst issue also affected the vanilla 4.8 kernel and was fixed for vanilla at f19c961b4e461da045f2e72e73701059e5117be0.
