### PR TITLE
home-assistant: 0.68.1 -> 0.69.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://www.home-assistant.io/blog/2018/05/11/release-69

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @peterhoeg

### CODE REVIEW

**Comment by peterhoeg** [comment]
Couple of things:

1. ```colorlog``` needs to be pinned at 3.1.4
2. I think we need a newer deluge as this versions spams ```ImportError: cannot import name 'FailedToReconnectException'``` when using a ```switch.deluge``` - haven't looked into it yet.

**Comment by peterhoeg** [comment]
This shuts up colorlog:

```
      colorlog = super.colorlog.overridePythonAttrs (oldAttrs: rec {
        version = "3.1.4";
        src = oldAttrs.src.override {
          inherit version;
          sha256 = "17bpp68w8fhr5az1382qh5r7m14myds414g4zbq3fzspr4wbd3a1";
        };
      });
```

**Comment by dotlambda** [comment]
`colorlog` is only used by the `check_config` script. Do you need this?
`FailedToReconnectException` seems to have been introduced in https://github.com/JohnDoee/deluge-client/commit/f9163a5df0dd169d5e4ddcb22c1ffd229efc9c0d, which happened between 1.3.0 and 1.4.0, so let's just bump the package.

**Comment by peterhoeg** [comment]
> colorlog is only used by the check_config script. Do you need this?

I don't, but I have used it - I think it makes sense to have it working to ease things for new users.

**Comment by peterhoeg** [comment]
```notify.matrix``` is broken upstream: https://github.com/home-assistant/home-assistant/issues/14397
