### ISSUE TITLE
[emacs-24.5-mac-5.9] Error building on OS X El Capitan

### ISSUE THREAD

**Issue by martinklepsch** [NixOS/nixpkgs#9329]
I just started using Nix on OS X El Capitan and besides some initial hickups/misunderstandings things are working smoothly now. :+1: 

One issue I encountered is that I cannot build emacs. I'm using Emacs installed via Homebrew Cask for now. Mostly logging this so others can find it/test it.

The full output of `nix-env -i emacs-24.5-mac-5.9` is pasted here: http://sprunge.us/gLDX

I think the relevant parts are the ones showing up when searching for `error:`. I tried with both XCode-beta and plain command line tools installed. With XCode installed I got even weirder errors resulting in things like `checking whether the C compiler works... no`.

Not sure what to do from here but if anyone has some ideas but no El Capitan installation at hand I'm happy to try.

**Comment by gridaphobe** [comment]
@pikajude can you confirm this issue? I don't have a copy of 10.11.

**Comment by dhess** [comment]
I can confirm this, including the different (but equally fatal) errors when using either the Xcode release (6.4) command-line tools, or the Xcode-beta 5 command-line tools.

**Comment by dhess** [comment]
I believe the problem is that Nix installs the OS X 10.9 SDK and command-line developer tools, but these don't work on OS X 10.11. I've created a fork that replaces these with the 10.11 tools, and this seems to fix most of the build problems I've been having with Nix on 10.11. However, there are currently other issues blocking some packages, e.g., #9707.

**Comment by gridaphobe** [comment]
Based on some of the errors, e.g.

```
/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:54:4: error: expected a type
- (nullable id)awakeAfterUsingCoder:(NSCoder *)aDecoder NS_REPLACES_RECEIVER;
   ^
```

I suspect apple is shipping a newer version of `clang` with 10.11 than we are.

**Comment by dhess** [comment]
This is fixed by making llvm-3.7 the default on OS X 10.11.

**Comment by martinklepsch** [comment]
@dhess Would you mind sharing how I can setup my nixpkgs clone to use llvm-3.7 by default? :)

**Comment by dhess** [comment]
@martinklepsch Do you have a <tt>config.nix</tt> file with a <tt>packageOverrides</tt> section? If so, just add <tt>llvmPackages = recurseIntoAttrs llvmPackages_37;</tt> to it. If not, see https://gist.github.com/dhess/476aa2342d53ffc6ff73.

**Comment by martinklepsch** [comment]
@dhess Thanks a lot! For others, there is more information on `config.nix` in the wiki: [Modifying Packages](https://nixos.org/wiki/Nix_Modifying_Packages#Overriding_Existing_Packages)

**Comment by usharf** [comment]
This helps, but also seeing this right now:

```sh
ld: framework not found CoreFoundation
```

**Comment by Nuk9** [comment]
I use https://gist.github.com/dhess/476aa2342d53ffc6ff73 and run:

   nix-env -i emacs

It seems nix is compiling everything including perl and python 2.7.10. Binary cache not working under this configuration?

**Comment by dhess** [comment]
@Nuk9 I'm assuming you're building on OS X 10.11. In that case, you'll need to use a LLVM 3.7 toolchain, and that will rebuild everything until upstream makes it the default and starts building packages with it.

**Comment by henrytill** [comment]
Could you check this again with a current clone of nixpkgs and Nix HEAD?  

Both `emacs` and `emacs24Macport` should build with 10.11.  

To install Nix HEAD:
```
git clone https://github.com/NixOS/nix
cd nix
nix-env -f release.nix -iA build.x86_64-darwin --option build-use-chroot false
```
Also, you should set
```
build-use-chroot = true
```
in `/etc/nix/nix.conf`

Instructions for working from a clone, updates, and more info on troubleshooting here: 
https://nixos.org/wiki/Nix_on_OS_X

**Comment by FRidh** [comment]
This is quite an old issue so I am closing this.
