### PR TITLE
piccata 1.0.1 -> 2.0.0

### PR DESCRIPTION
**Pull request by siriobalmelli**
###### Motivation for this change

Needed piccata working with Python3, upgraded to latest version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

NOTE:

- piccata will no longer build on python2.7; but this is EOL so not considered a problem
- nrfutil will not build ... this has been fixed and will be introduced in a later patch because it depends on this and other pull requests. See https://github.com/siriobalmelli-foss/nixpkgs/tree/upgrade/nrfutil

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/90105
2 packages failed to build:
nrfutil python27Packages.piccata

2 packages built:
python37Packages.piccata python38Packages.piccata
```

File: pkgs/development/python-modules/piccata/default.nix [hunk 1]
```diff
@@ -1,16 +1,21 @@
-{ buildPythonPackage, fetchPypi, lib, ipaddress, isPy3k }:
+{ buildPythonPackage, fetchFromGitHub, lib, ipaddress }:
 
 buildPythonPackage rec {
   pname = "piccata";
-  version = "1.0.1";
-  disabled = isPy3k;
+  version = "2.0.0";
```
Comment (jonringer) [inline pkgs/development/python-modules/piccata/default.nix:5]: actually, reading through the failures mores:
```suggestion
  version = "2.0.0";
  disabled = isPy27;
```

```
ilder for '/nix/store/1s8wmh5afdh89m3r6lxyy92jvi75xs6x-python2.7-piccata-2.0.0.drv' failed with exit code 1; last 10 log lines:
      from abc import ABC, abstractmethod
  ImportError: cannot import name ABC


  ----------------------------------------------------------------------
  Ran 1 test in 0.000s

  FAILED (errors=1)
  Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
  error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

**Comment by siriobalmelli** [comment]
> LGTM
> 
> failures are broken on target branch
> 
> ```
> https://github.com/NixOS/nixpkgs/pull/90105
> 2 packages failed to build:
> nrfutil python27Packages.piccata
> 
> 2 packages built:
> python37Packages.piccata python38Packages.piccata
> ```

Thanks for the review :)

Yes, as mentioned above:

 - piccata will no longer build on python2.7; but this is EOL so not considered a problem
 - nrfutil will not build ... this has been fixed and will be introduced in a later patch because it depends on this and other pull requests. See https://github.com/siriobalmelli-foss/nixpkgs/tree/upgrade/nrfutil

I did get nrfutil building, but there are quite a few patches required to get there.
Not sure if you'd prefer to see all patches in a single pull request, but right now I have every patch  broken out as a separate branch, and I've filed a PR for each of them:

- https://github.com/NixOS/nixpkgs/pull/90098
- https://github.com/NixOS/nixpkgs/pull/90100
- https://github.com/NixOS/nixpkgs/pull/90108

... and then once this PR and the above are merged, I would submit the remaining patches:

- https://github.com/siriobalmelli-foss/nixpkgs/commit/ab66f27b570725822000b3b00a7ef17edbb327f4
- https://github.com/siriobalmelli-foss/nixpkgs/commit/be59b2c053449a0ccaae6492b7ab529d7a8114ac

... all so I can finally fix nrfutil:

- https://github.com/siriobalmelli-foss/nixpkgs/commit/ca45b4290615ca146a6c76899e7d5e43686b5674

Again, pls let me know if you'd like to see all patches together or if I should follow the current plan.
Thanks.

**Comment by jonringer** [comment]
@siriobalmelli please apply my suggestion under the approval, so that the python2 package fails at evaluation time, instead of build time.

Otherwise LGTM

File: pkgs/development/python-modules/piccata/default.nix (hunk 1 above)
Comment (siriobalmelli) [reply pkgs/development/python-modules/piccata/default.nix:5]: Thank you, much appreciated

**Comment by jonringer** [comment]
Please follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and [manual#submitting-changes-making-patches ](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches) and squash the commits.

This can be done with:
```
git reset HEAD~2
git add -- pkgs/
git commit --amend --no-edit
git push ... ... --force
```

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 90105 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary><br>- python37Packages.piccata<br>- python38Packages.piccata</details>
