### ISSUE TITLE
zfs 2.15 fails to build with kernel 5.18.6

### ISSUE THREAD

**Issue by schwarmco** [NixOS/nixpkgs#179551]
### Steps To Reproduce
1. Tried to upgrade to NixOS 22.05 (was blocked before by zfs 2.14 not support kernel 5.18; now zfs 2.15 was backported to NixOS 22.05 - see #178830)
2. Run `nixos-rebuild` with updated channel

### Build log
The failing parts are:

```
In file included from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/string.h:253,
                 from /build/source/include/os/linux/spl/sys/strings.h:24,
                 from /build/source/module/icp/algs/edonr/edonr.c:32:
In function 'fortify_memcpy_chk',
    inlined from 'EdonRInit' at /build/source/module/icp/algs/edonr/edonr.c:491:3:
/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/fortify-string.h:328:25: error: call to '__write_overflow_field' declared with attribu>
  328 |                         __write_overflow_field(p_size_field, size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[...]

cc1: all warnings being treated as errors
make[5]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/scripts/Makefile.build:288: /build/source/module/icp/algs/edonr/edonr.o] Error 1

[...]

In file included from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/string.h:253,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/bitmap.h:11,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/cpumask.h:12,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/cpumask.h:5,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/msr.h:11,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/processor.h:22,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/timex.h:5,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/timex.h:67,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/time32.h:13,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/time.h:60,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/stat.h:19,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/module.h:13,
                 from /build/source/include/os/linux/spl/sys/atomic.h:27,
                 from /build/source/include/sys/zfs_context.h:46,
                 from /build/source/module/zfs/dsl_bookmark.c:22:
In function 'fortify_memset_chk',
    inlined from 'dsl_bookmark_set_phys' at /build/source/module/zfs/dsl_bookmark.c:384:3:
/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/fortify-string.h:242:25: error: call to '__write_overflow_field' declared with attribu>
  242 |                         __write_overflow_field(p_size_field, size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[...]

cc1: all warnings being treated as errors
make[5]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/scripts/Makefile.build:288: /build/source/module/zfs/dsl_bookmark.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/scripts/Makefile.build:550: /build/source/module/zfs] Error 2
  LD [M]  /build/source/module/zstd/zzstd.o
make[3]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/Makefile:1838: /build/source/module] Error 2
make[3]: Leaving directory '/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/build'
make[2]: *** [Makefile:55: modules-Linux] Error 2
make[2]: Leaving directory '/build/source/module'
make[1]: *** [Makefile:930: all-recursive] Error 1
make[1]: Leaving directory '/build/source'
make: *** [Makefile:791: all] Error 2
```

### Additional context
This may be a zfs problem, not a nix problem, but i am not sure about that. It may even be a "me"-problem, though i have no custom config around zfs- or kernel-versions.

### Notify maintainers
@Madouura @hmenke @jcumming @jonringer @wizeman @fpletz @globin

### Metadata
```console
[user@@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hmenke** [comment]
I can reproduce this, but there is something fishy going on. The ZFS kernel module should be built on Hydra and substituted. Why is this not happening?

**Comment by hmenke** [comment]
Looks like this is fixed in https://github.com/openzfs/zfs/pull/13575. Let's hope that the ZFS team will make a new release soon.

**Comment by schwarmco** [comment]
Thank you for finding this issue - i've searched the zfs issue tracker but didn't stumble across this one. 

Though, as you also mentioned - i thought, if Hydra is green, i'm good to go?

**Comment by mpasternacki** [comment]
Commits fixing https://github.com/openzfs/zfs/pull/13575 don't apply directly, but I managed to cherry-pick the ones that break NixOS build. I'm typing this comment from NixOS ZFS root on 5.18 now. Here's the overlay: https://gist.github.com/mpasternacki/819b7ff33c0df3f37b5687cfdeabf954

**Comment by PedroHLC** [comment]
In case you're in a rush to update, linux-zen seems to not treat all warnings as errors and don't have this issue...

**Comment by hmenke** [comment]
I've opened an issue on ZFS in the hope to speed things up a little bit: https://github.com/openzfs/zfs/issues/13622

**Comment by hmenke** [comment]
This is the configuration I am using for now. An overlay for the userspace tools is not necessary since these build without problems.

```nix
{
  boot.kernelPackages = pkgs.linuxPackages_5_18.extend (final: prev: {
    zfs = prev.zfs.overrideAttrs ({ NIX_CFLAGS_COMPILE ? [], ... }: {
      NIX_CFLAGS_COMPILE = NIX_CFLAGS_COMPILE ++ [ "-Wno-error=attribute-warning" ];
    });
  });
}
```

or if you want to patch your checkout of nixpkgs:

```patch
diff --git a/pkgs/os-specific/linux/zfs/default.nix b/pkgs/os-specific/linux/zfs/default.nix
index eec2d1ad04a..a56c92044a5 100644
--- a/pkgs/os-specific/linux/zfs/default.nix
+++ b/pkgs/os-specific/linux/zfs/default.nix
@@ -109,6 +109,8 @@ let
       # for zdb to get the rpath to libgcc_s, needed for pthread_cancel to work
       NIX_CFLAGS_LINK = "-lgcc_s";
 
+      NIX_CFLAGS_COMPILE = [ "-Wno-error=attribute-warning" ];
+
       hardeningDisable = [ "fortify" "stackprotector" "pic" ];
 
       configureFlags = [
```

**Comment by PedroHLC** [comment]
Important to note, ZFS is not alone, this was the fix in kernel-side: https://github.com/NixOS/nixpkgs/pull/175433/files

**Comment by PedroHLC** [comment]
Successfully builds with #180275 that has been merged.
