### ISSUE TITLE
Build failure: varnish (on -darwin)

### ISSUE THREAD

**Issue by katrinafyi** [NixOS/nixpkgs#495368]
### Nixpkgs version

- Unstable (26.05)

### Steps to reproduce

On at least aarch64-darwin,
```
nix build nixpkgs#varnish
```
will fail to build. (faf8bcdb3621688b360627da1715e8f7119dca31 at time of writing)

### Can Hydra reproduce this build failure?

Yes.

### Link to Hydra build job

first failure: https://hydra.nixos.org/build/318357331

### Relevant log output

```console
varnish>   CC       libvarnish_la-vsha256.lo
varnish>   CC       libvarnish_la-vss.lo
varnish>   CC       libvarnish_la-vsub.lo
varnish> vsub.c:73:6: error: call to undeclared function 'close_range'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
varnish>    73 |         if (close_range(fd, ~0U, 0) == 0)
varnish>       |             ^
varnish> 1 error generated.
varnish> make[3]: *** [Makefile:1083: libvarnish_la-vsub.lo] Error 1
varnish> make[3]: Leaving directory '/nix/var/nix/b/4mkkmd4bfv5xr4ilrz8jxjpv1v/varnish-7.7.3/lib/libvarnish'
varnish> make[2]: *** [Makefile:419: all-recursive] Error 1
varnish> make[2]: Leaving directory '/nix/var/nix/b/4mkkmd4bfv5xr4ilrz8jxjpv1v/varnish-7.7.3/lib'
varnish> make[1]: *** [Makefile:755: all-recursive] Error 1
varnish> make[1]: Leaving directory '/nix/var/nix/b/4mkkmd4bfv5xr4ilrz8jxjpv1v/varnish-7.7.3'
varnish> make: *** [Makefile:640: all] Error 2
```

### Additional context

It's probably related to https://github.com/NixOS/nixpkgs/pull/448440. The package builds fine on nixos-25.11 which doesn't have this PR.

I'm happy to try any fixes. Maybe it's as easy as adding a condition to those `ac_` overrides.

### System metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 25.2.0, macOS 26.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Lix, like Nix) 2.94.0
System type: aarch64-darwin
Additional system types: x86_64-darwin
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /Users/uqklam5/.config/nix/nix.conf:/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/gxpdrn2sw1xpymxmsrxc7c706b7higws-lix-2.94.0/share`
 - nixpkgs: `/nix/store/kkx2hzq20ggrwhy385jglnxjncg4lqck-source`

### Notify maintainers

@leona-ya @osnyx

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
