### ISSUE TITLE
Subversion perl bindings have no RPATH to find libapr-1.so.0

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#14495]
## Issue description

When `git-svn` is installed with `nix-env -iA nixos.gitSVN`, `git-svn` works fine. When `git-svn` is installed with `nix-env -f /tmp/system.nix --install --remove-all`, then `git-svn` prints an error message.

When installing with `nix-env -iA`, I get this log:

```
$ nix-env -iA nixos.gitSVN
replacing old ‘git-with-svn-2.8.0’
installing ‘git-with-svn-2.6.3’
```
So, it might be that git-with-svn-2.6.3 is fine but not `git-with-svn-2.8.0`.

### Steps to reproduce

```
$ nix-env -iA nixos.gitSVN
$ git svn clone http://svn.apache.org/repos/asf/subversion/trunk
Initialized empty Git repository in /tmp/trunk/.git/
$ rm -rf trunk
$ cat /tmp/system.nix 
with (import <nixpkgs> {}); {inherit gitSVN;}
$ nix-env -f /tmp/system.nix --install --remove-all
$ git svn clone http://svn.apache.org/repos/asf/subversion/trunk
Can't load '/nix/store/5k75ksar1mf37gqa1rdwxn04b5w47k09-subversion-1.9.3/lib/perl5/site_perl/5.22.1/x86_64-linux-thread-multi/auto/SVN/_Core/_Core.so' for module SVN::_Core: libapr-1.so.0: cannot open shared object file: No such file or directory at /nix/store/0vmf0vmzbgj1yfwy2j28jp3fysavmqvf-perl-5.22.1/lib/perl5/5.22.1/x86_64-linux-thread-multi/DynaLoader.pm line 193.
 at /nix/store/5k75ksar1mf37gqa1rdwxn04b5w47k09-subversion-1.9.3/lib/perl5/site_perl/5.22.1/x86_64-linux-thread-multi/SVN/Base.pm line 59.
BEGIN failed--compilation aborted at /nix/store/5k75ksar1mf37gqa1rdwxn04b5w47k09-subversion-1.9.3/lib/perl5/site_perl/5.22.1/x86_64-linux-thread-multi/SVN/Core.pm line 5.
Compilation failed in require at /nix/store/6wic6ifyps5y98fdbyaaqbac8i6mr4rc-git-2.8.0/lib/perl5/site_perl/5.22.1/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at /nix/store/6wic6ifyps5y98fdbyaaqbac8i6mr4rc-git-2.8.0/lib/perl5/site_perl/5.22.1/Git/SVN/Utils.pm line 6.
Compilation failed in require at /nix/store/6wic6ifyps5y98fdbyaaqbac8i6mr4rc-git-2.8.0/lib/perl5/site_perl/5.22.1/Git/SVN.pm line 32.
BEGIN failed--compilation aborted at /nix/store/6wic6ifyps5y98fdbyaaqbac8i6mr4rc-git-2.8.0/lib/perl5/site_perl/5.22.1/Git/SVN.pm line 32.
Compilation failed in require at /nix/store/6wic6ifyps5y98fdbyaaqbac8i6mr4rc-git-2.8.0/libexec/git-core/.git-svn-wrapped line 21.
BEGIN failed--compilation aborted at /nix/store/6wic6ifyps5y98fdbyaaqbac8i6mr4rc-git-2.8.0/libexec/git-core/.git-svn-wrapped line 21.
```
## Technical details

* System: NixOS: `nixos-version` = `16.09.git.cb44efc` (`channels/nixos-unstable-small`)
* Nix: `nix-env --version` = `1.11.2`
* Nixpkgs version: `16.09.git.cb44efc` (`channels/nixos-unstable-small`)

/cc @peti @the-kenny @wmertens

**Comment by domenkozar** [comment]
I think you have nixpkgs and nixos channel. One might be coming from root. So on one channel it works, on the other it doesn't.

**Comment by peti** [comment]
This is a bug in the Perl bindings generated as a part of our Subversion build. The library `/nix/store/5k75ksar1mf37gqa1rdwxn04b5w47k09-subversion-1.9.3/lib/perl5/site_perl/5.22.1/x86_64-linux-thread-multi/auto/SVN/_Core/_Core.so` depends on `libapr-1.so.0`, but it has no RPATH set that allows it to find library. Curiously enough, `libapr-1.so.0` is the only dependency with that problem: other library like `libsvn_ra_local-1.so.0` *are* found properly using a full path into the Nix store.

Cc: @edolstra and @lovek323

**Comment by DamienCassou** [comment]
@peti and it was working fine in `git-2.7.4`:

```
$ /nix/store/ijlx7dhpgbpw4gsyblv9sfpmap28hh7b-git-2.7.4/bin/git svn
...works ok...
$ /nix/store/6wic6ifyps5y98fdbyaaqbac8i6mr4rc-git-2.8.0/bin/git svn
...crashes badly...
```

**Comment by peti** [comment]
As I said, this as nothing to do with Git. It's `subversion` that provides broken Perl bindings.

**Comment by rardiol** [comment]
Ran into same problem. git bisect log of checking ldd /nix/store/\*-subversion-1.9.3/lib/perl5/site_perl/*/x86_64-linux-thread-multi/auto/SVN/_Core/_Core.so follows. there's some big binutils related changes in the middle yet.
```

git bisect start
# good: [5db2d9366bde95e76428a687e977b04f395bb094] subversion: fix hash
git bisect good 5db2d9366bde95e76428a687e977b04f395bb094
# bad: [551296a1cec0b9751ab96c420a7481e322ea127d] mendeley: 1.16 -> 1.16.1
git bisect bad 551296a1cec0b9751ab96c420a7481e322ea127d
# bad: [9ee7b3f6284649f97c0c97125848ba0f651d3a41] pythonPackages.scipy: use latest numpy version
git bisect bad 9ee7b3f6284649f97c0c97125848ba0f651d3a41
# good: [60726164055ca689f9b37e7d4529e9927ec6c3ad] jsonnet: 0.8.6 -> 0.8.7
git bisect good 60726164055ca689f9b37e7d4529e9927ec6c3ad
# bad: [dae3a7b721aeaaffabf336563182852c800a5ae0] Merge pull request #14238 from joachifm/fix-codeblocks-for-staging
git bisect bad dae3a7b721aeaaffabf336563182852c800a5ae0
# good: [a85ba820a409c84d97ca04cb02c12500927fb5e3] perl: Make 5.22 the default
git bisect good a85ba820a409c84d97ca04cb02c12500927fb5e3
# good: [54c7ef17a913fde534a22edbe5557aa24d1f4847] eclipse-plugin-checkstyle: 6.14.0 -> 6.16.0
git bisect good 54c7ef17a913fde534a22edbe5557aa24d1f4847
# bad: [6d2c7b3926ee96c1be3867238139838934602977] Merge pull request #14059 from joachifm/fix-ipxe-gcc5
git bisect bad 6d2c7b3926ee96c1be3867238139838934602977
# good: [fabbd0f0f7fdb536f56d73487aec198c24163fd0] Merge pull request #13721 from zimbatm/make-wrapper-unset
git bisect good fabbd0f0f7fdb536f56d73487aec198c24163fd0
# good: [4f5d48abf5c4e39da8636b18db1cc9bfebd14d68] thunderbird: Fix build on gcc 5
git bisect good 4f5d48abf5c4e39da8636b18db1cc9bfebd14d68
# bad: [a11a28107120612c0284a19d41b6ffb5750a65ac] go-1.4: Update binutils patch to handle i686-linux
git bisect bad a11a28107120612c0284a19d41b6ffb5750a65ac
# bad: [e9f1fa8bb020b7f1c4531a5bb35db7e1cabb3654] librdf_redland: Fix dependency on libraptor2
git bisect bad e9f1fa8bb020b7f1c4531a5bb35db7e1cabb3654
# good: [8726c6d50638fea25808e99192ed546657200d87] webkitgtk: Disable Hydra build
git bisect good 8726c6d50638fea25808e99192ed546657200d87
# bad: [89742e6b051e6ae109586bf2251b5d837295fe75] binutils: Apply upstream bug fix
git bisect bad 89742e6b051e6ae109586bf2251b5d837295fe75
# bad: [d5bb6a1f9c0c099738a37ce2e923cd71d85b5145] glibc: Enable separate debug symbols
git bisect bad d5bb6a1f9c0c099738a37ce2e923cd71d85b5145
# bad: [2040a9ac574fffd36fe20130897ccec2d5928827] stdenv-linux: Ensure binutils comes before bootstrapTools in $PATH
git bisect bad 2040a9ac574fffd36fe20130897ccec2d5928827
```
