### PR TITLE
apvlv: fix build with poppler 0.73.0

### LINKED ISSUE #54021: building apvlv on nixos-unstable fails
## Issue description
building apvlv on nixos-unstable  22b7449aacb9bd064537d230176154292a2f2fec fails with
```
In file included from /nix/store/gs5zdwrvvfk6gzl5bmdanaf27pl37zhd-gtk+3-3.24.2-dev/include/gtk-3.0/gtk/gtkapplication.h:27:0,
                 from /nix/store/gs5zdwrvvfk6gzl5bmdanaf27pl37zhd-gtk+3-3.24.2-dev/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /nix/store/gs5zdwrvvfk6gzl5bmdanaf27pl37zhd-gtk+3-3.24.2-dev/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /nix/store/gs5zdwrvvfk6gzl5bmdanaf27pl37zhd-gtk+3-3.24.2-dev/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /nix/store/gs5zdwrvvfk6gzl5bmdanaf27pl37zhd-gtk+3-3.24.2-dev/include/gtk-3.0/gtk/gtk.h:31,
                 from /build/source/src/ApvlvUtil.h:32,
                 from /build/source/src/ApvlvDoc.cc:29:
/nix/store/gs5zdwrvvfk6gzl5bmdanaf27pl37zhd-gtk+3-3.24.2-dev/include/gtk-3.0/gtk/gtkwidget.h:1144:14: note: declared here
 void         gtk_widget_override_color            (GtkWidget     *widget,
              ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 33%] Building CXX object src/CMakeFiles/apvlv.dir/ApvlvFile.cc.o
[ 40%] Building CXX object src/CMakeFiles/apvlv.dir/ApvlvPdf.cc.o
[ 46%] Building CXX object src/CMakeFiles/apvlv.dir/ApvlvInfo.cc.o
/build/source/src/ApvlvPdf.cc:32:10: fatal error: goo/gtypes.h: No such file or directory
 #include <goo/gtypes.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/apvlv.dir/build.make:128: src/CMakeFiles/apvlv.dir/ApvlvPdf.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/apvlv.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
note: keeping build directory '/tmp/nix-build-apvlv-0.1.5.drv-0'
builder for '/nix/store/dkrdlxfci7509mzxw4wyxx4f1npabbrb-apvlv-0.1.5.drv' failed with exit cod

```
### Steps to reproduce

nix-build -A apvlv ~/nixpkgs

CC @ardumont

### PR DESCRIPTION
**Pull request by erictapen**
###### Motivation for this change

closes https://github.com/NixOS/nixpkgs/issues/54021

###### Things done

Took @worldofpeace's commit and provided some more info in the commit message. 

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timokau** [comment]
Is there an upstream report about this?

**Comment by erictapen** [comment]
@timokau Yep, I noted it in the commit message, but not in the text of the PR.

https://github.com/naihe2010/apvlv/issues/28

**Comment by timokau** [comment]
Great :)

Though @worldofpeace said "That patch was mean't to be used in nixpkgs", so I'll defer to them.

**Comment by worldofpeace** [comment]
Upstream they should properly condition which header is used by the poppler version used in the build environment.

Though this patch is completely fine to have in nixpkgs.

**Comment by worldofpeace** [comment]
Thanks @erictapen for following up on this :sparkle:
