### PR TITLE
fluidsynth_1: remove at 1.1.11

### LINKED ISSUE #124624: Vulnerability roundup 102: fluidsynth-1.1.11: 1 advisory [5.5]
[search](https://search.nix.gsc.io/?q=fluidsynth&i=fosho&repos=NixOS-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=fluidsynth+in%3Apath&type=Code)

* [ ] [CVE-2021-21417](https://nvd.nist.gov/vuln/detail/CVE-2021-21417) CVSSv3=5.5 (nixos-20.09, nixos-unstable)

Scanned versions: nixos-20.09: 76ed24ceab9; nixos-unstable: ea7d4aa9b82.

Cc @cillianderoiste
Cc @lovek323

### LINKED ISSUE #141508: Get rid of now broken fluidsynth_1
`fluidsynth_1` no longer compiles with GLib 2.70:

```
In file included from /nix/store/rrmzjd6gybl8ynnlnclxmla9rvcpw0cc-glib-2.70.0-dev/include/glib-2.0/glib/deprecated/gthread.h:124,
                 from /nix/store/rrmzjd6gybl8ynnlnclxmla9rvcpw0cc-glib-2.70.0-dev/include/glib-2.0/glib.h:112,
                 from /build/source/src/utils/fluidsynth_priv.h:25,
                 from /build/source/src/drivers/fluid_jack.c:31:
/build/source/src/drivers/fluid_jack.c:103:42: error: extra brace group at end of initializer
  103 | static fluid_mutex_t last_client_mutex = G_STATIC_MUTEX_INIT;     /* Probably not necessary, but just in case drivers are created by multiple threads */
      |                                          ^~~~~~~~~~~~~~~~~~~
/build/source/src/drivers/fluid_jack.c:103:42: note: (near initialization for 'last_client_mutex')
/build/source/src/drivers/fluid_jack.c:103:42: error: extra brace group at end of initializer
  103 | static fluid_mutex_t last_client_mutex = G_STATIC_MUTEX_INIT;     /* Probably not necessary, but just in case drivers are created by multiple threads */
      |                                          ^~~~~~~~~~~~~~~~~~~
/build/source/src/drivers/fluid_jack.c:103:42: note: (near initialization for 'last_client_mutex')
In file included from /nix/store/f1r94qx7a8m8iz7fxvlq655gbawql7xf-glibc-2.33-50-dev/include/bits/thread-shared-types.h:74,
                 from /nix/store/f1r94qx7a8m8iz7fxvlq655gbawql7xf-glibc-2.33-50-dev/include/bits/pthreadtypes.h:23,
                 from /nix/store/f1r94qx7a8m8iz7fxvlq655gbawql7xf-glibc-2.33-50-dev/include/sys/types.h:227,
                 from /nix/store/f1r94qx7a8m8iz7fxvlq655gbawql7xf-glibc-2.33-50-dev/include/stdlib.h:394,
                 from /nix/store/rrmzjd6gybl8ynnlnclxmla9rvcpw0cc-glib-2.70.0-dev/include/glib-2.0/glib/gutils.h:433,
                 from /nix/store/rrmzjd6gybl8ynnlnclxmla9rvcpw0cc-glib-2.70.0-dev/include/glib-2.0/glib/gthread.h:34,
                 from /nix/store/rrmzjd6gybl8ynnlnclxmla9rvcpw0cc-glib-2.70.0-dev/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /nix/store/rrmzjd6gybl8ynnlnclxmla9rvcpw0cc-glib-2.70.0-dev/include/glib-2.0/glib.h:32,
                 from /build/source/src/utils/fluidsynth_priv.h:25,
                 from /build/source/src/drivers/fluid_jack.c:31:
/build/source/src/drivers/fluid_jack.c:103:42: error: extra brace group at end of initializer
  103 | static fluid_mutex_t last_client_mutex = G_STATIC_MUTEX_INIT;     /* Probably not necessary, but just in case drivers are created by multiple threads */
      |                                          ^~~~~~~~~~~~~~~~~~~
/build/source/src/drivers/fluid_jack.c:103:42: note: (near initialization for 'last_client_mutex')
/build/source/src/drivers/fluid_jack.c:103:42: warning: excess elements in union initializer
  103 | static fluid_mutex_t last_client_mutex = G_STATIC_MUTEX_INIT;     /* Probably not necessary, but just in case drivers are created by multiple threads */
      |                                          ^~~~~~~~~~~~~~~~~~~
/build/source/src/drivers/fluid_jack.c:103:42: note: (near initialization for 'last_client_mutex')
/build/source/src/drivers/fluid_jack.c:103:13: warning: Deprecated pre-processor symbol: replace with "g_mutex_init"
  103 | static fluid_mutex_t last_client_mutex = G_STATIC_MUTEX_INIT;     /* Probably not necessary, but just in case drivers are created by multiple threads */
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/libfluidsynth.dir/build.make:90: src/CMakeFiles/libfluidsynth.dir/drivers/fluid_jack.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:258: src/CMakeFiles/libfluidsynth.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

The failure looks patchable: We'd need to replace the use of `G_STATIC_MUTEX_INIT` in `fluid_jack.c` by an equivalent call to `g_mutex_init`. However I'm not quite confident about the right place to call it, since we need to avoid calling it twice (which is UB according to the GLib documentation) and it looks like there are two different intialization routines that'd need to initialize the lock, `new_fluid_jack_client ` and `new_fluid_jack_midi_driver`.

Therefore I think should try to make an effort to finally get rid of this vulnerable version of fluidsynth (#124624). Remaining uses:

* [x] `csound`, fixed in #141506
* [x] `lmms` (cc @cillianderoiste, @yegortimoshenko), fixed in #141512
* [x] `gzdoom` (cc @Lassulus), fixed in #141517

### PR DESCRIPTION
**Pull request by sternenseemann**
Refactor expression a bit, use pname instead of name.

Fixes #141508.
Fixes #124624.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stunkymonkey — APPROVED** [review]
LGTM
