### PR TITLE
MariaDB: 10.9.4, 10.8.6, 10.6.11, 10.5.18 and 10.4.27

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
https://mariadb.org/mariadb-10-9-4-10-8-6-10-7-7-10-6-11-10-5-18-10-4-27-and-10-3-37-now-available/

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
A lot of these are failing to build on macos (10.15 for me):

```
ld: unknown option: --as-needed
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libmariadb/CMakeFiles/auth_gssapi_client.dir/build.make:129: libmariadb/auth_gssapi_client.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:2718: libmariadb/CMakeFiles/auth_gssapi_client.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by risicle** [comment]
https://github.com/MariaDB/server/commit/70701ee4b1a9962e33a83da94aea61d7537fe9d4 ?

**Comment by risicle** [comment]
The confusing thing is that the feature test for this flag apparently works:

```
-- Performing Test have_C__Wl___as_needed
-- Performing Test have_C__Wl___as_needed - Success
```

**Comment by risicle** [comment]
Getting failures in the final link of `mariadb_109` on aarch64-linux too:

```
/nix/store/6ahp7jcb5x8b76j6jfkhzm6wwnd8za8c-binutils-2.39/bin/ld: libmariadbd.a(ha_innodb.cc.o): in function `innodb_monitor_set_option(monitor_info_t const*, mon_option_t) [clone .isra.0]':
ha_innodb.cc:(.text+0x2808): undefined reference to `__aarch64_ldset8_relax'
/nix/store/6ahp7jcb5x8b76j6jfkhzm6wwnd8za8c-binutils-2.39/bin/ld: ha_innodb.cc:(.text+0x28ac): undefined reference to `__aarch64_ldclr8_relax'
...
```

...continuing similarly for 22 pages...

**Comment by ajs124** [comment]
> [MariaDB/server@70701ee](https://github.com/MariaDB/server/commit/70701ee4b1a9962e33a83da94aea61d7537fe9d4) ?

lets give reverting that at try

**Comment by risicle** [comment]
I've tried a bit of post-patch hackery and I'm not sure it's as simple as I first thought.

**Comment by mikroskeem** [comment]
Result of `nixpkgs-review pr 200197` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>mariadb_106</li>
    <li>mariadb_108</li>
    <li>mariadb_109</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mariadb_104</li>
    <li>mariadb_105</li>
  </ul>
</details>

**Comment by ajs124** [comment]
Will merge this at the end of the week

**Comment by tricktron** [comment]
@ajs124 @uri-canva

Adding:
```nix
++ lib.optionals (stdenv.hostPlatform.isDarwin && lib.versionAtLeast version "10.6") [
        # workaround for https://jira.mariadb.org/browse/MDEV-29925
        "-Dhave_C__Wl___as_needed="
```

on line 99 fixes the build on darwin for me. I got this from the workaround mentioned in https://jira.mariadb.org/browse/MDEV-29925.

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 200197` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua54Packages.luadbi-mysql</li>
    <li>zoneminder</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>diesel-cli</li>
    <li>lua51Packages.luadbi-mysql</li>
    <li>luaPackages.luadbi-mysql (lua52Packages.luadbi-mysql)</li>
    <li>lua53Packages.luadbi-mysql</li>
    <li>luajitPackages.luadbi-mysql</li>
    <li>mariadb (mariadb_106)</li>
    <li>mariadb-embedded</li>
    <li>mariadb_104</li>
    <li>mariadb_105</li>
    <li>mariadb_108</li>
    <li>mariadb_109</li>
    <li>perl534Packages.MySQLDiff</li>
    <li>perl536Packages.MySQLDiff</li>
  </ul>
</details>

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 200197` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua54Packages.luadbi-mysql</li>
    <li>zoneminder</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>diesel-cli</li>
    <li>lua51Packages.luadbi-mysql</li>
    <li>luaPackages.luadbi-mysql (lua52Packages.luadbi-mysql)</li>
    <li>lua53Packages.luadbi-mysql</li>
    <li>luajitPackages.luadbi-mysql</li>
    <li>mariadb (mariadb_106)</li>
    <li>mariadb-embedded</li>
    <li>mariadb_104</li>
    <li>mariadb_105</li>
    <li>mariadb_108</li>
    <li>mariadb_109</li>
    <li>perl534Packages.MySQLDiff</li>
    <li>perl536Packages.MySQLDiff</li>
  </ul>
</details>

**Review by 0x4A6F — APPROVED** [review]

**Review by tricktron — APPROVED** [review]
LGTM on the darwin side.

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 200197` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>calligra</li>
    <li>lua54Packages.luadbi-mysql</li>
    <li>trojita</li>
    <li>unixODBCDrivers.mysql</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mariadb-embedded</li>
  </ul>
</details>
<details>
  <summary>58 packages built:</summary>
  <ul>
    <li>automysqlbackup</li>
    <li>cqrlog</li>
    <li>diesel-cli</li>
    <li>digikam</li>
    <li>kmymoney</li>
    <li>libsForQt5.akonadi (plasma5Packages.akonadi)</li>
    <li>libsForQt5.akonadi-calendar (plasma5Packages.akonadi-calendar)</li>
    <li>libsForQt5.akonadi-calendar-tools (plasma5Packages.akonadi-calendar-tools)</li>
    <li>libsForQt5.akonadi-contacts (plasma5Packages.akonadi-contacts)</li>
    <li>libsForQt5.akonadi-import-wizard (plasma5Packages.akonadi-import-wizard)</li>
    <li>libsForQt5.akonadi-mime (plasma5Packages.akonadi-mime)</li>
    <li>libsForQt5.akonadi-notes (plasma5Packages.akonadi-notes)</li>
    <li>libsForQt5.akonadi-search (plasma5Packages.akonadi-search)</li>
    <li>libsForQt5.akonadiconsole (plasma5Packages.akonadiconsole)</li>
    <li>libsForQt5.akregator (plasma5Packages.akregator)</li>
    <li>libsForQt5.calendarsupport (plasma5Packages.calendarsupport)</li>
    <li>libsForQt5.eventviews (plasma5Packages.eventviews)</li>
    <li>libsForQt5.incidenceeditor (plasma5Packages.incidenceeditor)</li>
    <li>libsForQt5.kaddressbook (plasma5Packages.kaddressbook)</li>
    <li>libsForQt5.kalarm (plasma5Packages.kalarm)</li>
    <li>libsForQt5.kalendar (plasma5Packages.kalendar)</li>
    <li>libsForQt5.kdepim-addons (plasma5Packages.kdepim-addons)</li>
    <li>libsForQt5.kdepim-runtime (plasma5Packages.kdepim-runtime)</li>
    <li>libsForQt5.kgpg (plasma5Packages.kgpg)</li>
    <li>libsForQt5.kmail (plasma5Packages.kmail)</li>
    <li>libsForQt5.kmail-account-wizard (plasma5Packages.kmail-account-wizard)</li>
    <li>libsForQt5.kmailtransport (plasma5Packages.kmailtransport)</li>
    <li>libsForQt5.knotes (plasma5Packages.knotes)</li>
    <li>libsForQt5.kontact (plasma5Packages.kontact)</li>
    <li>libsForQt5.korganizer (plasma5Packages.korganizer)</li>
    <li>libsForQt5.libgravatar (plasma5Packages.libgravatar)</li>
    <li>libsForQt5.libkdepim (plasma5Packages.libkdepim)</li>
    <li>libsForQt5.libksieve (plasma5Packages.libksieve)</li>
    <li>libsForQt5.mailcommon (plasma5Packages.mailcommon)</li>
    <li>libsForQt5.mailimporter (plasma5Packages.mailimporter)</li>
    <li>libsForQt5.mauikit-calendar (plasma5Packages.mauikit-calendar)</li>
    <li>libsForQt5.mbox-importer (plasma5Packages.mbox-importer)</li>
    <li>libsForQt5.messagelib (plasma5Packages.messagelib)</li>
    <li>libsForQt5.pim-data-exporter (plasma5Packages.pim-data-exporter)</li>
    <li>libsForQt5.pim-sieve-editor (plasma5Packages.pim-sieve-editor)</li>
    <li>libsForQt5.pimcommon (plasma5Packages.pimcommon)</li>
    <li>libsForQt5.zanshin (plasma5Packages.zanshin)</li>
    <li>lua51Packages.luadbi-mysql</li>
    <li>luaPackages.luadbi-mysql (lua52Packages.luadbi-mysql)</li>
    <li>lua53Packages.luadbi-mysql</li>
    <li>luajitPackages.luadbi-mysql</li>
    <li>mariadb (mariadb_106)</li>
    <li>mariadb_104</li>
    <li>mariadb_105</li>
    <li>mariadb_108</li>
    <li>mariadb_109</li>
    <li>pam_mysql</li>
    <li>perl534Packages.MySQLDiff</li>
    <li>perl536Packages.MySQLDiff</li>
    <li>snipe-it</li>
    <li>sogo</li>
    <li>sope</li>
    <li>zoneminder</li>
  </ul>
</details>
