### ISSUE TITLE
Build failure: dosbox-x

### ISSUE THREAD

**Issue by samestep** [NixOS/nixpkgs#516168]
### Nixpkgs version

- Unstable (26.05)

### Steps to reproduce

1. `nix build -A dosbox-x` on `aarch64-darwin`

### Can Hydra reproduce this build failure?

Hydra doesn’t try to build the package.

### Relevant log output

```console
render.cpp:891:37: error: use of undeclared identifier 'SCREEN_METAL'
  891 |             && (sdl.desktop.type != SCREEN_METAL)
      |                                     ^~~~~~~~~~~~
render.cpp:1379:36: error: use of undeclared identifier 'SCREEN_METAL'
 1379 |             if(sdl.desktop.type == SCREEN_METAL) return false;
      |                                    ^~~~~~~~~~~~
```

### Additional context

This build failure was introduced by #504679: that is, `dosbox-x` builds on `aarch64-darwin` at commit 4c2d21b9689d597423bec80851c37cfb88253147, and fails to build on `aarch64-darwin` at commit 0e0519fe7e4c01e7f16d95ca813818ad2105bb97 or later.

However, even though DOSBox-X builds before that PR, it does not run:

```
LOG: Early LOG Init complete
LOG: "" is not a valid value for variable: configuration tool theme.
It might now be reset to the default value:
LOG: CONFIG: Created and loaded user config file /Users/samueles/Library/Preferences/DOSBox-X 2026.01.02 Preferences
LOG: CONFIG: Loaded config file: /Users/samueles/Library/Preferences/DOSBox-X 2026.01.02 Preferences
LOG: DOSBox-X's working directory: /Users/samueles
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 2026.01.02 Commit 59915c1 (macOS ARM SDL2 64-bit)
LOG: macOS EXE path: /nix/store/6dxlxdwyiir535qhs6xf2jl5la441sy3-dosbox-x-2026.01.02/Applications/dosbox-x.app/Contents/MacOS/dosbox-x
LOG: macOS Resource path: /nix/store/6dxlxdwyiir535qhs6xf2jl5la441sy3-dosbox-x-2026.01.02/Applications/dosbox-x.app/Contents/Resources
LOG: macOS: NSTouchBar support detected in system
LOG: Prevent capture: 0
LOG: SDL: version 2.32.64, Video cocoa, Audio coreaudio
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: SDL2 reports desktop display mode 1440 x 900
LOG: The default output for the video system: opengl
LOG: WARNING: SDL2 unable to create GL context
zsh: segmentation fault  nix run nixpkgs/15c6719d8c604779cf59e03c245ea61d3d7ab69b#dosbox-x
```

The segfault was introduced by #476460: that is, DOSBox-X builds and runs on `aarch64-darwin` at commit 0c939841b97bff18cb72ab72b179c4fd63f2e2d2, and segfaults on `aarch64-darwin` at commit 6c0f6b01b1c7d58214ca9c8ccd014e2f3019cc0e or later (until the build failure).

[According to the DOSBox-X `CHANGELOG`](https://github.com/joncampbell123/dosbox-x/blob/dosbox-x-v2026.03.29/CHANGELOG#L112), version 2026.03.29 "Fixed segfault on launch of macOS builds" (this refers to joncampbell123/dosbox-x#6038), so hopefully this segfault can be ignored and just fixing the build failure should be sufficient.

### System metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 25.4.0, macOS 26.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Determinate Nix 3.19.0) 2.34.6`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/jzd9vz08h5b7s3rgxzpw28mpw4rxk2ra-source`

### Notify maintainers

@hughobrien @OPNA2608

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by OPNA2608** [comment]
Thanks for looking into this, and the PRs that bump past this issue.

The only Apple machine that I regularly use currently is a PowerMac running Linux, so package maintenance on `-darwin` is not something that I can (or really, *want* to) do. If you depend on this package, and have some resources to spare, feel free to add yourself to `meta.maintainers`.

**Comment by samestep** [comment]
Makes sense! I probably won't add myself as a maintainer since I'm not sure how far into the future I'll be using this, but I'm happy to provide macOS testing for the time being.
