### ISSUE TITLE
nixopsUnstable fails to build on nixos-unstable (66e8dceabcd)

### ISSUE THREAD

**Issue by NetaliDev** [NixOS/nixpkgs#179223]
### Steps To Reproduce
1. `nix-shell -p nixopsUnstable`

### Build log
```console
[root@ralph:~]# nix-shell -p nixopsUnstable
this derivation will be built:
  /nix/store/kyrsh82b697w77py5m89jwwxyghxwjws-nixops-with-plugins-2.0.0-pre-7220cbd.drv
building '/nix/store/kyrsh82b697w77py5m89jwwxyghxwjws-nixops-with-plugins-2.0.0-pre-7220cbd.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/0ynbnj0dnjagpgfvcvban49ggz0w2igw-nixops-7220cbd
source root is nixops-7220cbd
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file nixops-7220cbd/tests/unit/test_util.py
patching sources
Removing path dependencies
Finished removing path dependencies
Removing git dependencies
Finished removing git dependencies
installing
Running Sphinx v4.5.0
making output directory... done

Exception occurred:
  File "/build/nixops-7220cbd/nixops/state.py", line 10, in <module>
    class StateDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
The full traceback has been saved in /build/sphinx-err-go4bjf21.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
error: builder for '/nix/store/kyrsh82b697w77py5m89jwwxyghxwjws-nixops-with-plugins-2.0.0-pre-7220cbd.drv' failed with exit code 2
```
### Notify maintainers
@adisbladis @aminechikhaoui @domenkozar @edolstra @rbvermaa 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@ralph:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.11 (Raccoon), 22.11pre387779.66e8dceabcd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lunik1** [comment]
Looks like there is already a PR to address this at #178811

And fwiw I had to bisect this to fix my config, first bad commit is 11ea0e99b713744b5e76141fb26a3d4b4d16c507

**Comment by abathur** [comment]
Closing since the linked PR was merged. (Not sure why merge of the linked PR didn't close this...)
