### ISSUE TITLE
`c3d` will fail the build with gcc-11: ITK-4.13/vcl_compiler.h:123:4: error: #error "Dunno about this gcc"

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#143963]
`itk` probably will need explicit `gcc-11` support

```
$ nix-build -E 'with import <nixpkgs> {}; c3d.override { stdenv = gcc11Stdenv; }'
...
[ 13%] Building CXX object CMakeFiles/cnd_adapters.dir/adapters/ApplyNoise.cxx.o
In file included from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/vcl_limits.h:5,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkNumericTraits.h:51,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkConceptChecking.h:32,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkAtomicIntDetail.h:39,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkAtomicInt.h:38,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkTimeStamp.h:33,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkLightObject.h:23,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkObject.h:31,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkCreateObjectFunction.h:21,
                 from /nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/itkObjectFactoryBase.h:31,
                 from /build/source/itkextras/PovRayIO/itkPovRayDF3ImageIOFactory.h:20,
                 from /build/source/itkextras/PovRayIO/itkPovRayDF3ImageIOFactory.cxx:17:
/nix/store/ybg1sx19rghhz1fn84r7cmp6cjxa130z-itk-4.13.3/include/ITK-4.13/vcl_compiler.h:123:4: error: #error "Dunno about this gcc"
  123 | #  error "Dunno about this gcc"
      |    ^~~~~
```

### Notify maintainers

c3d: @bcdarwin
itk: @viric

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: c3d
```

**Comment by trofi** [comment]
Closing as INVALID.

**Comment by bcdarwin** [comment]
Incidentally, this will be resolved for `c3d` by #144272 (although other `itk4`-related compilation issues could occur until it's removed).
