### PR TITLE
krb5: Add patches to fix build with musl on 1.18

### LINKED ISSUE #83926: krb5 does not build with musl anymore
After https://github.com/NixOS/nixpkgs/pull/80599 (krb5: 1.17 -> 1.18) is merged, `krb5` doesn't build with `pkgsMusl` anymore.

The error is:

```
...
gcc -fPIC -DSHARED -DHAVE_CONFIG_H  -I../../include -I../../include  -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE  -g -O2 -Wall -Wcast-align -Wshadow -Wmissing-prototypes -Wno-format-zero-length -Woverflow -Wstrict-overflow -Wmissing-format-attribute -Wmissing-prototypes -Wreturn-type -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-variable -Wunused-value -Wunknown-pragmas -Wsign-compare -Werror=uninitialized -Wno-maybe-uninitialized -Werror=pointer-arith -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=discarded-qualifiers -Werror=implicit-int -Werror=declaration-after-statement -Werror-implicit-function-declaration -pthread  -c utf8.c -o utf8.so.o && mv -f utf8.so.o utf8.so
plugins.c:67:21: error: missing binary operator before token "("
   67 | #if ! __GLIBC_PREREQ(2, 25)
      |                     ^
make[1]: *** [Makefile:1095: plugins.so] Error 1
make[1]: *** Waiting for unfinished jobs....
fake-addrinfo.c: In function ‘my_fake_getaddrinfo’:
fake-addrinfo.c:1200:16: warning: variable ‘herr’ set but not used [-Wunused-but-set-variable]
 1200 |         int i, herr;
      |                ^~~~
make[1]: Leaving directory '/build/krb5-1.18/src/util/support'
make: *** [Makefile:888: all-recurse] Error 1
note: keeping build directory '/tmp/nix-build-libkrb5-1.18.drv-0'
builder for '/nix/store/bcn73i403brcnvhrpa2fgjn6nb2khzjb-libkrb5-1.18.drv' failed with exit code 2
error: build of '/nix/store/bcn73i403brcnvhrpa2fgjn6nb2khzjb-libkrb5-1.18.drv' failed
```

Since `krb5` is a dependency of `curl`, this affects significant number of downstream packages.

**To Reproduce**

```
$ cd nixpkgs
$ git checkout 5d33637dd940f2053724359c207c052647ce7112
$ nix-build -A pkgsMusl.libkrb5 
```

cc @r-ryantm @vcunat @nh2

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

Unbreak musl build, see https://github.com/krb5/krb5/commit/bf5953c549a6d279977df69ffe89b2ba51460eaf#r37504446

These fixes are only in `krb5` `master` so far, a release that includes them has not been made yet.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nh2** [comment]
Something is still off with the build, will look into it.

**Comment by nh2** [comment]
> Something is still off with the build, will look into it.

OK, fixed.

File: pkgs/development/libraries/kerberos/krb5.nix [hunk 1]
```diff
@@ -14,14 +14,23 @@ in
...
   src = fetchurl {
     url = "https://kerberos.org/dist/krb5/${majorVersion}/krb5-${version}.tar.gz";
     sha256 = "121c5xsy3x0i4wdkrpw62yhvji6virbh6n30ypazkp0isws3k4bk";
   };
 
+  patches = optionals stdenv.hostPlatform.isMusl [
+    # TODO: Remove with next release > 1.18
+    # Patches to fix musl build with 1.18.
+    # Not using `fetchpatch` for these for now to avoid infinite recursion
+    # errors in downstream projects (unclear if it's a nixpkgs issue so far).
```
Comment (matthewbauer) [inline pkgs/development/libraries/kerberos/krb5.nix:29]: fetchpatch is broken in bootstrapping since fetchurlBoot doesn't support it so this is probably what you're seeing.

Comment (nh2) [reply pkgs/development/libraries/kerberos/krb5.nix:29]: @matthewbauer Is `krb5` part of bootstrapping? Should I indicate this fact here?

Comment (matthewbauer) [reply pkgs/development/libraries/kerberos/krb5.nix:29]: Actually it's part of fetchurl definition here:

https://github.com/NixOS/nixpkgs/blob/cab6b019b17881f42f618dcc9fce9341f1a6df81/pkgs/top-level/all-packages.nix#L315-L363
