### PR TITLE
numcpp: init at 2.11.0

### PR DESCRIPTION
**Pull request by 70m6**
## Description of changes

https://github.com/dpilger26/NumCpp

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/development/libraries/numcpp/default.nix [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    rev = "Version_${finalAttrs.version}";
+    hash = "sha256-IAku1bcaMkawZxpQbvxcS6VX07ogw4UGo1DX2Wa8xwU=";
+  };
+
+  nativeBuildInputs = [cmake];
+
+  buildInputs = [boost];
+
+  postInstall = ''
+    sed -i s/\$\{PACKAGE_PREFIX_DIR}// $out/share/NumCpp/cmake/NumCppConfig.cmake
```
Comment (risicle) [inline pkgs/development/libraries/numcpp/default.nix:24]: For simple substitutions we tend to prefer `substituteInPlace` but it's not a major issue.

**Comment by risicle** [comment]
Did you try getting the tests running? Otherwise installation of a header-only library is little more than moving some files around and doesn't give us a great idea of whether it's broken.

(also where has this library been all my life?)

**Comment by 70m6** [comment]
After adding a `cmakeFlags = ["-DBUILD_TESTS=ON"];`
I get this error:
```
[ 80%] Building CXX object test/pytest/src/CMakeFiles/NumCppPy.dir/Rotations.cpp.o
In file included from /build/source/test/pytest/src/pybind11/pybind11/cast.h:15,
                 from /build/source/test/pytest/src/pybind11/pybind11/attr.h:14,
                 from /build/source/test/pytest/src/pybind11/pybind11/detail/class.h:12,
                 from /build/source/test/pytest/src/pybind11/pybind11/pybind11.h:13,
                 from /build/source/test/pytest/src/pybind11/pybind11/complex.h:12,
                 from /build/source/test/pytest/src/BindingsIncludes.hpp:3,
                 from /build/source/test/pytest/src/Misc.cpp:1:
In static member function 'static std::pair<const void*, const pybind11::detail::type_info*> pybind11::detail::type_caster_base<type>::src_and_type(const ityp>
    inlined from 'static pybind11::handle pybind11::detail::type_caster_base<type>::cast(const itype*, pybind11::return_value_policy, pybind11::handle) [with >
    inlined from 'static pybind11::handle pybind11::detail::type_caster_base<type>::cast(const itype&, pybind11::return_value_policy, pybind11::handle) [with >
    inlined from 'pybind11::cpp_function::initialize<pybind11::class_<std::pair<nc::NdArray<unsigned int>, nc::NdArray<unsigned int> > >::def_readonly<std::pa>
    inlined from 'static constexpr pybind11::handle pybind11::cpp_function::initialize<pybind11::class_<std::pair<nc::NdArray<unsigned int>, nc::NdArray<unsig>
/build/source/test/pytest/src/pybind11/pybind11/detail/type_caster_base.h:948:49: error: using a dangling pointer to an unnamed temporary [-Werror=dangling-po>
  948 |         return type_caster_generic::src_and_type(src, cast_type, instance_type);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/test/pytest/src/pybind11/pybind11/cast.h: In static member function 'static constexpr pybind11::handle pybind11::cpp_function::initialize<pybind>
/build/source/test/pytest/src/pybind11/pybind11/cast.h:1448:51: note: unnamed temporary defined here
 1448 |         return std::forward<Func>(f)(cast_op<Args>(std::move(std::get<Is>(argcasters)))...);
      |                                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In static member function 'static std::pair<const void*, const pybind11::detail::type_info*> pybind11::detail::type_caster_base<type>::src_and_type(const ityp>
    inlined from 'static pybind11::handle pybind11::detail::type_caster_base<type>::cast(const itype*, pybind11::return_value_policy, pybind11::handle) [with >
    inlined from 'static pybind11::handle pybind11::detail::type_caster_base<type>::cast(const itype&, pybind11::return_value_policy, pybind11::handle) [with >
    inlined from 'pybind11::cpp_function::initialize<pybind11::class_<std::pair<nc::NdArray<double>, nc::NdArray<double> > >::def_readonly<std::pair<nc::NdArr>
    inlined from 'static constexpr pybind11::handle pybind11::cpp_function::initialize<pybind11::class_<std::pair<nc::NdArray<double>, nc::NdArray<double> > >>
/build/source/test/pytest/src/pybind11/pybind11/detail/type_caster_base.h:948:49: error: using a dangling pointer to an unnamed temporary [-Werror=dangling-po>
  948 |         return type_caster_generic::src_and_type(src, cast_type, instance_type);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/test/pytest/src/pybind11/pybind11/cast.h: In static member function 'static constexpr pybind11::handle pybind11::cpp_function::initialize<pybind>
/build/source/test/pytest/src/pybind11/pybind11/cast.h:1448:51: note: unnamed temporary defined here
 1448 |         return std::forward<Func>(f)(cast_op<Args>(std::move(std::get<Is>(argcasters)))...);
      |                                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Is it possible to not report compiler warnings as errors?

**Comment by 70m6** [comment]
> Did you try getting the tests running? Otherwise installation of a header-only library is little more than moving some files around and doesn't give us a great idea of whether it's broken.
> 
> (also where has this library been all my life?)

okay, got it building all tests

File: pkgs/development/libraries/numcpp/default.nix [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+  version = "2.11.0";
+
+  src = fetchFromGitHub {
+    owner = "dpilger26";
+    repo = "NumCpp";
+    rev = "Version_${finalAttrs.version}";
+    hash = "sha256-IAku1bcaMkawZxpQbvxcS6VX07ogw4UGo1DX2Wa8xwU=";
+  };
+
+  nativeBuildInputs = [cmake gtest python3 eigen opencv];
```
Comment (risicle) [inline pkgs/development/libraries/numcpp/default.nix:26]: Inputs that are only needed for the tests should be added to `nativeCheckInputs`.

File: pkgs/development/libraries/numcpp/default.nix [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+  cmakeFlags = ["-DBUILD_ALL=ON"];
```
Comment (risicle) [inline pkgs/development/libraries/numcpp/default.nix:28]:
```suggestion
  cmakeFlags = lib.optionals finalAttrs.doCheck [
    "-DBUILD_TESTS=ON"
    "-DBUILD_MULTIPLE_TEST=ON"
  ];
```

I'm not sure there's a lot of value in building the examples, especially if they drag in huge build-time dependencies like opencv.

File: pkgs/development/libraries/numcpp/default.nix [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+
+  buildInputs = [boost];
+
+  postInstall = ''
+    substituteInPlace $out/share/NumCpp/cmake/NumCppConfig.cmake \
+      --replace "\''${PACKAGE_PREFIX_DIR}/" ""
+  '';
+
+  NIX_CFLAGS_COMPILE="-Wno-error";
+
```
Comment (risicle) [inline pkgs/development/libraries/numcpp/default.nix:38]:
```suggestion
  doCheck = true;
```

The check phase needs to be enabled for the tests to actually be run after they're built.

Comment (risicle) [reply pkgs/development/libraries/numcpp/default.nix:38]: It might be necessary to set disable for this if `stdenv.isDarwin` - I can't get the tests to build on macos 10.15:

```
/tmp/nix-build-numcpp-2.11.0.drv-0/source/test/pytest/src/Functions.cpp:2678:16: error: call to 'signbit' is ambiguous
        return signbit(inValue);
               ^~~~~~~
/tmp/nix-build-numcpp-2.11.0.drv-0/source/test/pytest/src/Functions.cpp:3733:49: note: in instantiation of function template specialization 'FunctionsInterface::signbitScalar<double>' requested here
    m.def("signbitScalar", &FunctionsInterface::signbitScalar<double>);
                                                ^
/nix/store/nq85mb7p7fwcm1cad3af02i3kdmsybii-libcxx-11.1.0-dev/include/c++/v1/math.h:329:1: note: candidate function [with _A1 = double]
signbit(_A1 __lcpp_x) _NOEXCEPT
^
/tmp/nix-build-numcpp-2.11.0.drv-0/source/include/NumCpp/Functions/signbit.hpp:46:10: note: candidate function [with dtype = double]
    bool signbit(dtype inValue) noexcept
```

:shrug:

File: pkgs/development/libraries/numcpp/default.nix (hunk 1 above)
Comment (70m6) [reply pkgs/development/libraries/numcpp/default.nix]: okay i moved to that method

File: pkgs/development/libraries/numcpp/default.nix (hunk 2 above)
Comment (70m6) [reply pkgs/development/libraries/numcpp/default.nix]: okay I moved to that

File: pkgs/development/libraries/numcpp/default.nix (hunk 3 above)
Comment (70m6) [reply pkgs/development/libraries/numcpp/default.nix]: okay now just doing tests

File: pkgs/development/libraries/numcpp/default.nix (hunk 4 above)
Comment (70m6) [reply pkgs/development/libraries/numcpp/default.nix:40]: i made it so it doesnt build if you are using darwin

File: pkgs/development/libraries/numcpp/default.nix (hunk 3 above)
Comment (risicle) [reply pkgs/development/libraries/numcpp/default.nix]: Looks like this should actually be `finalAttrs.finalPackage.doCheck` so that it automatically disables itself when cross-compiling.

File: pkgs/development/libraries/numcpp/default.nix (hunk 4 above)
Comment (risicle) [reply pkgs/development/libraries/numcpp/default.nix:40]: I think it also needs to disable tests if `stdenv.hostPlatform.isStatic` - the tests don't appear to be designed to build on a static toolchain.

Comment (70m6) [reply pkgs/development/libraries/numcpp/default.nix:40]: added that too

**Review by risicle — APPROVED** [review]
LGTM

`nixpkgs-review` happy, macos 10.15, nixos x86_64.

`pkgsStatic`, `pkgsMusl` & `pkgsCross.aarch64-multiplatform` variants build.
