### PR TITLE
Qt5 spring cleaning

### PR DESCRIPTION
**Pull request by K900**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
```
error: undefined variable 'apple_sdk_11_0'
at pkgs/top-level/all-packages.nix:22493:40
```

**Comment by vcunat** [comment]
qt5.qtbase evals now for me but won't build:
```
In file included from /private/tmp/nix-build-qtbase-5.15.8.drv-0/qtbase-9cf586d/qmake/generators/mac/pbuilder_pbx.cpp:45:
In file included from /nix/store/a2sd4amfsljdf4pxnx5i1alb1mgg1px4-apple-framework-ApplicationServices-11.0.0/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
In file included from /nix/store/1wzdsghj5nk25xbrf715izgz6z62dlsp-apple-framework-CoreServices-11.0.0/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:
In file included from /nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:60:
In file included from /nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:17:
In file included from /nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:16:
/nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1189:83: error: expected ','
    kCFURLBookmarkCreationWithSecurityScope API_AVAILABLE(macos(10.7), macCatalyst(13.0))  API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 11 ), // Mac OS X 10.7.3 and later, include information in the bookmark data which al>
                                                                                  ^
/nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1190:98: error: expected ','
    kCFURLBookmarkCreationSecurityScopeAllowOnlyReadAccess API_AVAILABLE(macos(10.7), macCatalyst(13.0)) API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 12 ), // Mac OS X 10.7.3 and later, if used with kCFURLBookmarkCreation>
                                                                                                 ^
/nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1200:85: error: expected ','
    kCFURLBookmarkResolutionWithSecurityScope API_AVAILABLE(macos(10.7), macCatalyst(13.0)) API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 10 ), // Mac OS X 10.7.3 and later, use the secure information included at creation >
                                                                                    ^
```

**Comment by K900** [comment]
Progress: it now fails in identical ways on x86_64-darwin and aarch64-darwin, which means we should be good on the SDK upgrade. The bad news is, it fails because qkvgen segfaults, and I have no idea where to even start debugging it.

**Comment by vcunat** [comment]
And I suppose it's not easy to avoid the cleaning and just fix the build?  (which regressed on darwin on the qt5 patch update)

**Comment by K900** [comment]
We'd have to rebase all the Darwin patches again, and I _really_ don't want to do that tbh. Upstream is expecting at least 10.13, we can't just keep patching things out forever.

**Comment by vcunat** [comment]
Let's exercise ofBorg at least a bit:
@ofBorg build qt5.qtbase

**Comment by K900** [comment]
Current status:
- x86_64-linux builds and runs up to Plasma bits
- aarch64-linux builds up to qtbase, rest TBD, but these changes shouldn't affect it much
- Darwin (both flavors) builds up to qttools, qtwebengine currently blocked on Mesa, waiting for @winterqt to run-test qttools

**Comment by tricktron** [comment]
I cherry-picked your three commits and the qt5: 5.15.7 -> 5.15.8 update commit onto master so that I don't have to rebuild 500 package to build qtbase.

However on my aarch64-darwin machine I always run into the following issue:
```console
WARNING: Failure to find: /private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui/qt5gui_metatypes.json
make[2]: Entering directory '/private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui'
/private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui/qvkgen_wrapper.sh vulkan/vk.xml /private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/header.LGPL vulkan/qvulkanfunctions
make[2]: *** [Makefile:2749: vulkan/qvulkanfunctions.h] Segmentation fault: 11
make[2]: *** Deleting file 'vulkan/qvulkanfunctions.h'
make[2]: Leaving directory '/private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui'
make[1]: *** [Makefile:533: sub-gui-make_first] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src'
make: *** [Makefile:54: sub-src-make_first] Error 2
note: keeping build directory '/private/tmp/nix-build-qtbase-5.15.8.drv-3'
error: builder for '/nix/store/s124k9ap6zsvyb98hbfh8d6d71g5mh5c-qtbase-5.15.8.drv' failed with exit code 2;
       last 10 log lines:
       > cd gui/ && ( test -e Makefile || /private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/bin/qmake -o Makefile /private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui/gui.pro ) && make -f Makefile
       > WARNING: Failure to find: /private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui/qt5gui_metatypes.json
       > make[2]: Entering directory '/private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui'
       > /private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui/qvkgen_wrapper.sh vulkan/vk.xml /private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/header.LGPL vulkan/qvulkanfunctions
       > make[2]: *** [Makefile:2749: vulkan/qvulkanfunctions.h] Segmentation fault: 11
       > make[2]: *** Deleting file 'vulkan/qvulkanfunctions.h'
       > make[2]: Leaving directory '/private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src/gui'
       > make[1]: *** [Makefile:533: sub-gui-make_first] Error 2
       > make[1]: Leaving directory '/private/tmp/nix-build-qtbase-5.15.8.drv-3/qtbase-9cf586d/src'
       > make: *** [Makefile:54: sub-src-make_first] Error 2
       For full logs, run 'nix log /nix/store/s124k9ap6zsvyb98hbfh8d6d71g5mh5c-qtbase-5.15.8.drv'.
```

**Comment by K900** [comment]
Disable the sandbox.

**Comment by tricktron** [comment]
@K900 

nix-build -A qt5.qtbase --keep-failed --option sandbox false leads to another error:

```console
Info: creating stash file /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/.qmake.stash

This is the Qt Open Source Edition.

You have already accepted the terms of the Open Source license.

Running configuration tests...
Checking for valid makespec... 
+ cd /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/config.tests/verifyspec && /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared warn_off console single_arch" 'QMAKE_LIBDIR += /nix/store/p1f8q6ah1g7hdqmj884jcy5g0mblmwnr-icu4c-72.1/lib /nix/store/yhfhj629lw5gga57rhwk3dxmg0z9qqb7-zlib-1.2.13/lib /nix/store/00q4lynafzzjfamfz50wkn2akw6vy3m5-libjpeg-turbo-2.1.4/lib /nix/store/dpdg4rb2lzrvwjyq5pk0266pv3d626s8-harfbuzz-5.3.1/lib /nix/store/c6awr8178hwbbclx4qx0frj14waw4x2b-openssl-3.0.7/lib' 'INCLUDEPATH += /nix/store/gv0wb22dc5c08y5hs0vlymflz3bn29iy-icu4c-72.1-dev/include /nix/store/znbipr33nxyy4qq3xzbfgs68v0p7x6iw-zlib-1.2.13-dev/include /nix/store/8hisgy94pmpikfx29idb223am7b1r9bd-libjpeg-turbo-2.1.4-dev/include /nix/store/dr0lfk9b571bicwgrhahd545n00jcgmk-harfbuzz-5.3.1-dev/include /nix/store/v68z49acirkr8m1k2nrwghyiz324p9dh-openssl-3.0.7-dev/include' /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/config.tests/verifyspec
> Info: creating stash file /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/config.tests/.qmake.stash
+ cd /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/config.tests/verifyspec && MAKEFLAGS= /nix/store/7lcwpgskn4r1fjgkfiwkyc315xc89ssl-gnumake-4.4/bin/make
> The macosx platform SDK has been changed from version  to version 13.1.
> This requires a fresh build of your project. Please wipe the build directory
> including the qmake cache in /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/config.tests/.qmake.stash
> /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/mkspecs/features/mac/sdk.mk:24: *** ^.  Stop.
Note: -docdir is not a subdirectory of -prefix.
Note: -plugindir is not a subdirectory of -prefix.
Note: -qmldir is not a subdirectory of -prefix.

ERROR: Cannot compile a minimal program. The toolchain or QMakeSpec is broken.
note: keeping build directory '/private/tmp/nix-build-qtbase-5.15.8.drv-5'
error: builder for '/nix/store/jvivqgcz3pih3xp2mizaffs1cc8fv8jg-qtbase-5.15.8.drv' failed with exit code 3;
       last 10 log lines:
       > + cd /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/config.tests/verifyspec && MAKEFLAGS= /nix/store/7lcwpgskn4r1fjgkfiwkyc315xc89ssl-gnumake-4.4/bin/make
       > > The macosx platform SDK has been changed from version  to version 13.1.
       > > This requires a fresh build of your project. Please wipe the build directory
       > > including the qmake cache in /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/config.tests/.qmake.stash
       > > /private/tmp/nix-build-qtbase-5.15.8.drv-5/qtbase-9cf586d/mkspecs/features/mac/sdk.mk:24: *** ^.  Stop.
       > Note: -docdir is not a subdirectory of -prefix.
       > Note: -plugindir is not a subdirectory of -prefix.
       > Note: -qmldir is not a subdirectory of -prefix.
       >
       > ERROR: Cannot compile a minimal program. The toolchain or QMakeSpec is broken.
       For full logs, run 'nix log /nix/store/jvivqgcz3pih3xp2mizaffs1cc8fv8jg-qtbase-5.15.8.drv'.
```

**Comment by K900** [comment]
@vcunat has hit this as well, but I can't reproduce on the community builder or on ofborg. What hardware are you running this on and what OS version? I believe the Darwin toolchains are pretty impure.

**Comment by tricktron** [comment]
M1 aarch64-darwin macos ventura 13.1.

**Comment by K900** [comment]
I'll take another look tomorrow morning, all the successful builds have been on pre-13.x so things might have broken somehow.

**Comment by winterqt** [comment]
FWIW, the builds on the community box succeeded with 13.0.1, so maybe it's just a 13.1 thing?

**Comment by K900** [comment]
Found the issue, another chunk got lost in the patch rebase...

**Comment by tricktron** [comment]
@K900 
Great. The build now works on my `aarch64-darwin` machine🎉.

**Comment by vcunat** [comment]
For me as well (on commit 69d28a482a14).

**Comment by tricktron** [comment]
@K900

https://github.com/NixOS/nixpkgs/blob/251474b8cd83dc7ca2c8120fffdc9a964cb62292/pkgs/development/libraries/qt-5/modules/qtbase.nix#L121-L126

These lines can be safely removed, e.g. it builds successfully without them. I think they are leftovers from earlier qt versions.

**Comment by vcunat** [comment]
OK, I think we should move on with this.  We can always improve later.

**Comment by risicle** [comment]
Does this mean we should be building qt programs with SDK 11 from here on?

**Comment by K900** [comment]
`libsForQt5.callPackage` should propagate it automatically.

**Comment by risicle** [comment]
I _suspect_ this broke `wireshark` on macos x86_64 (which coincidentally doesn't use `libsForQt5.callPackage`), but have no way to prove it without a massive rebuild.

Switching it to SDK 11 doesn't fix it.

**Comment by K900** [comment]
No, it's broken by libepoxy: https://hydra.nixos.org/build/205178592

**Comment by K900** [comment]
Which is a separate regression and might be crashing because of a Rosetta bug, see #209180

**Comment by risicle** [comment]
No, this is the failure on `master` now (`staging-next` having been merged a couple of hours ago) on macos 10.15:

```
In file included from /tmp/nix-build-wireshark-qt-4.0.1.drv-0/wireshark-4.0.1/wsutil/os_version_info.c:21:
In file included from /nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:60:
In file included from /nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:17:
In file included from /nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:16:
/nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1189:83: error: expected ','
    kCFURLBookmarkCreationWithSecurityScope API_AVAILABLE(macos(10.7), macCatalyst(13.0))  API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 11 ), // Mac OS X 10.7.3 and later, include information in the bookmark data which allows the same sandboxed process to access the resource after being relaunched
                                                                                  ^
/nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1190:98: error: expected ','
    kCFURLBookmarkCreationSecurityScopeAllowOnlyReadAccess API_AVAILABLE(macos(10.7), macCatalyst(13.0)) API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 12 ), // Mac OS X 10.7.3 and later, if used with kCFURLBookmarkCreationWithSecurityScope, at resolution time only read access to the resource will be granted
                                                                                                 ^
/nix/store/pijg4pkqizi263fp9l023k5a91245qf6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1200:85: error: expected ','
    kCFURLBookmarkResolutionWithSecurityScope API_AVAILABLE(macos(10.7), macCatalyst(13.0)) API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 10 ), // Mac OS X 10.7.3 and later, use the secure information included at creation time to provide the ability to access the resource in a sandboxed process.
                                                                                    
```

**Comment by K900** [comment]
If you're building on native x86_64, that may make libepoxy work, and yes, that error looks like you'll need an SDK upgrade.

**Comment by risicle** [comment]
I thought so too, but it doesn't appear to solve it :shrug: . I'm just working on the security bump  #210742 so addressing it isn't my highest priority.

**Comment by ilya-fedin** [comment]
> kCFURLBookmarkCreationWithSecurityScope API_AVAILABLE(macos(10.7), macCatalyst(13.0))  API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 11 ), // Mac OS X 10.7.3 and later, include information in the bookmark data which allows the same sandboxed process to access the resource after being relaunched

I seem to have the same errors (with other package thoug) on GitHub builders when building my NUR packages for binary cache
https://github.com/ilya-fedin/nur-repository/actions/runs/3954209355/jobs/6771316602

**Comment by K900** [comment]
Try switching it to SDK 11?

**Comment by ilya-fedin** [comment]
Isn't that what this PR does? I don't quite understand what should I do to switch otherwise as paths in the errors look like SDK 11 is already used.

**Comment by K900** [comment]
Those errors usually show up when you mix SDK versions, so maybe you're linking against SDK 10 frameworks or something. Got a link to the expression? Or is it just the default nixpkgs one?

**Comment by ilya-fedin** [comment]
Never mind, got it

**Comment by ilya-fedin** [comment]
Do I understand right that various Qt applications are broken on Darwin now? As the package I get errors for is also present in nixpkgs, so it should've been start failing in nixpkgs as well as you haven't changed it in your PR and I'm its maintainer.

**Comment by K900** [comment]
I've fixed everything I noticed during the staging cycle, but there have been some regressions unfortunately :( It specifically affects the applications that either don't use `libsForQt5.callPackage` or pass in their Darwin frameworks directly.

**Comment by ilya-fedin** [comment]
> or pass in their Darwin frameworks directly

Is there other way to pass Darwin frameworks?

**Comment by K900** [comment]
You should be able to just take `darwin` and then access individual attributes on that, but I'm not sure if this is a good idea. Ideally we'd probably have some other way of handling that...

**Comment by ilya-fedin** [comment]
> You should be able to just take `darwin` and then access individual attributes on that

But it would need to specify sdk version anyway as frameworks are in darwin.(apple_sdk|apple_sdk_11_0).frameworks?

**Comment by K900** [comment]
Sorry, `apple_sdk`, not `darwin`.

**Comment by ilya-fedin** [comment]
> Sorry, `apple_sdk`, not `darwin`.

And then libsForQt5.callPackage will give apple_sdk_11_0?

**Comment by K900** [comment]
Yep. I believe it already does.

**Comment by ilya-fedin** [comment]
That's interesting, but it seems only a few derivations doing like that and none of them are Qt derivations...

**Comment by ilya-fedin** [comment]
Something seem to be wrong with SDK 11 as it throws at me errors about various system types and constants being not defined
```
/tmp/nix-build-kotatogram-desktop-1.4.9.drv-0/source/Telegram/lib_webrtc/webrtc/mac/webrtc_media_devices_mac.mm:25:41: error: use of undeclared identifier 'AudioObjectPropertyAddress'
auto AudioOutputDevicePropertyAddress = AudioObjectPropertyAddress{
                                        ^
```

```
 /tmp/nix-build-kotatogram-desktop-1.4.9.drv-0/source/Telegram/lib_webrtc/webrtc/mac/webrtc_media_devices_mac.mm:59:18: error: use of undeclared identifier 'kAudioDeviceUnknown'
        if (deviceId == kAudioDeviceUnknown) {
                        ^
```

Isn't it possible to stay on old SDK?

**Comment by K900** [comment]
Qt upstream requires a newer SDK version now. We used to patch it to make it build with 10.12, but the recent Qt updates have raised the requirements again, and trying to backport stuff forever just isn't sustainable.

**Comment by ilya-fedin** [comment]
nixpkgs honestly has a weird workflow with the SDKs, most projects use latest SDK with MACOSX_DEPLOYMENT_TARGET being set to the needed minimum supported macOS version.

I wonder why it throws those errors at me thoguh, the code builds just fine outside of nixpkgs, using Xcode cmake generator and AppleClang. Is it possible to build using AppleClang within nixpkgs?

**Comment by K900** [comment]
I'm not really familiar with the details of Darwin stuff in nixpkgs, so I don't have the full full picture, but the reason we don't have the latest SDKs is because they're a pain to package in a way that works with the Nix sandbox.

**Comment by ilya-fedin** [comment]
Do you know where I can find someone who familiar? As I'm out of ideas how to make it build now...

**Comment by K900** [comment]
Maybe try #macos:nixos.org on Matrix. I've linked this thread there too.

**Comment by wegank** [comment]
> Something seem to be wrong with SDK 11 as it throws at me errors about various system types and constants being not defined
> 
> ```
> /tmp/nix-build-kotatogram-desktop-1.4.9.drv-0/source/Telegram/lib_webrtc/webrtc/mac/webrtc_media_devices_mac.mm:25:41: error: use of undeclared identifier 'AudioObjectPropertyAddress'
> auto AudioOutputDevicePropertyAddress = AudioObjectPropertyAddress{
>                                         ^
> ```
> 
>  ```
>  /tmp/nix-build-kotatogram-desktop-1.4.9.drv-0/source/Telegram/lib_webrtc/webrtc/mac/webrtc_media_devices_mac.mm:59:18: error: use of undeclared identifier 'kAudioDeviceUnknown'
>         if (deviceId == kAudioDeviceUnknown) {
>                         ^
> ```
> 
> Isn't it possible to choose to stay on old SDK for a package?

`sed -i "13i#import <CoreAudio/CoreAudio.h>" Telegram/lib_webrtc/webrtc/mac/webrtc_media_devices_mac.mm`

**Comment by ilya-fedin** [comment]
> sed -i "13i#import <CoreAudio/CoreAudio.h>" Telegram/lib_webrtc/webrtc/mac/webrtc_media_devices_mac.mm

:thinking: I wonder how this worked with old SDK and how this works with Xcode-based build
