### PR TITLE
patch ati-drivers for kernel 4.6

### LINKED ISSUE #18202: ati-drivers does not build with kernel 4.6
## Issue description

Two compilation errors are seen.  I have a fix at https://github.com/jerith666/nixpkgs/commit/a629947313995a1554d20a3f203fbd10b91f9afc, but I expect that it needs to be variablized to only apply these two new patches if building against a 4.6 (or greater) kernel, and I don't know how to do that.

add'l keywords: ati_unfree

### PR DESCRIPTION
**Pull request by jerith666**
###### Motivation for this change

fixes #18202
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

this uses the patch from
https://github.com/manjaro/packages-extra/commit/ddae91f2 to account
for https://github.com/torvalds/linux/commit/d4edcf0d and the patch
from https://www.virtualbox.org/ticket/15298 to account for
https://github.com/torvalds/linux/commit/09cbfeaf

### CODE REVIEW

File: pkgs/os-specific/linux/ati-drivers/default.nix [hunk 1]
```diff
@@ -1,4 +1,4 @@
-{ stdenv, fetchurl, kernel ? null, which
+{ stdenv, fetchurl, kernel ? null, linux, which
```
Comment (vcunat) [inline pkgs/os-specific/linux/ati-drivers/default.nix]: `linux`? I'm confident one should use the existing `kernel` parameter instead. That can be `null`, but that's for case when a kernel module isn't built and such patches shouldn't be needed.

Comment (jerith666) [inline pkgs/os-specific/linux/ati-drivers/default.nix]: That's what I thought too, but when I was running my build locally, `kernel` *was* `null`.  That seemed weird to me, although I don't see `kernel` being passed in explicitly where this is called (at https://github.com/jerith666/nixpkgs/blob/df9b7c1274551bc1ce0b1e71bb35e4cfbad143ae/pkgs/top-level/all-packages.nix#L11276).  But I also don't understand what args `callPackage` is expected to fill in automatically.

At any rate, here is what I get:

```
$ git diff
diff --git a/pkgs/os-specific/linux/ati-drivers/default.nix b/pkgs/os-specific/linux/ati-drivers/default.nix
index d54b0ab..621d756 100644
--- a/pkgs/os-specific/linux/ati-drivers/default.nix
+++ b/pkgs/os-specific/linux/ati-drivers/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchurl, kernel ? null, linux, which
+{ stdenv, fetchurl, kernel ? null, which
 , xorg, makeWrapper, glibc, patchelf, unzip
 , fontconfig, freetype, mesa # for fgl_glxgears
 , # Whether to build the libraries only (i.e. not the kernel module or
@@ -72,7 +72,7 @@ stdenv.mkDerivation rec {
     ./patches/15.9-mtrr.patch
     ./patches/15.9-preempt.patch
     ./patches/15.9-sep_printf.patch ]
-  ++ optionals ( (builtins.compareVersions linux.version "4.6") >= 0 )
+  ++ optionals ( (builtins.compareVersions kernel.version "4.6") >= 0 )
                [ ./patches/kernel-4.6-get_user_pages.patch
                  ./patches/kernel-4.6-page_cache_release-put_page.patch ];
 
$ nixos-rebuild build -I nixpkgs=/home/matt/git/nixos/nixpkgs
building Nix...
building the system configuration...
error: value is null while a set was expected, at /home/matt/git/nixos/nixpkgs/pkgs/os-specific/linux/ati-drivers/default.nix:75:44
(use ‘--show-trace’ to show detailed location information)
```

**Comment by jerith666** [comment]
The Travis CI failure was in building the OpenJDK docs, which seems spurious to me.

File: pkgs/os-specific/linux/ati-drivers/default.nix (hunk 1 above)
Comment (vcunat) [inline pkgs/os-specific/linux/ati-drivers/default.nix]: I expect you have a 64-bit system with `driSupport32Bit = true`: there you get 64-bit version build against the kernel **and** a 32-bit version with `libsOnly == true` (i.e. without kernel).

**Comment by jerith666** [comment]
@vcunat you're right.  Have a look at 7bc91ff instead.

**Comment by vcunat** [comment]
Looks reasonable and builds OK. I assume @jerith666 runs on it.

**Comment by vcunat** [comment]
It still won't build with 4.7, but that's a relatively new branch.

**Comment by jerith666** [comment]
@vcunat I do indeed run on this.  I guess I should've said that explicitly in the description?  I thought @domenkozar was asking for someone *else* to test it.  Anyway, thanks for the merge!

**Comment by jerith666** [comment]
I haven't looked at 4.7, it probably won't come to the top of my list for a bit yet.  :-/

**Comment by vcunat** [comment]
I see you checked the "tested execution" box; that should be enough IMHO.
