### ISSUE TITLE
gnupg: 2.1.14 fails to install on Darwin (ld: symbol(s) not found for architecture x86_64)

### ISSUE THREAD

**Issue by svend** [NixOS/nixpkgs#17617]
## Issue description

gnupg 2.1.14 fails to build on Darwin. 

### Steps to reproduce

```
$ nix-env -i gnupg
...
Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _i18n_switchto_utf8 in libcommon.a(libcommon_a-i18n.o)
      _i18n_switchback in libcommon.a(libcommon_a-i18n.o)
      _i18n_utf8 in libcommon.a(libcommon_a-i18n.o)
  "_libintl_bindtextdomain", referenced from:
      _i18n_init in libcommon.a(libcommon_a-i18n.o)
      _i18n_localegettext in libcommon.a(libcommon_a-i18n.o)
  "_libintl_gettext", referenced from:
      _my_strusage in gpgscm-main.o
      _create_pipe_and_estream in libcommon.a(libcommon_a-exechelp-posix.o)
      _gnupg_spawn_process in libcommon.a(libcommon_a-exechelp-posix.o)
      _gnupg_spawn_process_fd in libcommon.a(libcommon_a-exechelp-posix.o)
      _gnupg_wait_processes in libcommon.a(libcommon_a-exechelp-posix.o)
      _gnupg_spawn_process_detached in libcommon.a(libcommon_a-exechelp-posix.o)
      _disable_core_dumps in libcommon.a(libcommon_a-sysutils.o)
      ...
  "_libintl_setlocale", referenced from:
      _i18n_init in libcommon.a(libcommon_a-i18n.o)
      _i18n_localegettext in libcommon.a(libcommon_a-i18n.o)
  "_libintl_textdomain", referenced from:
      _i18n_init in libcommon.a(libcommon_a-i18n.o)
ld: symbol(s) not found for architecture x86_64
```

## Technical details

* System: Mac OS X 10.11.5
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre88082.f242b75"

I have also tried the nixpkgs master branch at:

* commit 9626707e2b796c04871a22a583500a45c1c436d7
* Date:   Tue Aug 9 19:21:58 2016 +0200

**Comment by svend** [comment]
Downgrading to gnupg 2.1.13 by reverting 00e8e4c2ed98ed915e54ee2ee8c402573588adee fixes the error for me.

**Comment by svend** [comment]
There is a thread about this on the gnupg-devel mailing list:

https://lists.gnupg.org/pipermail/gnupg-devel/2016-July/031362.html
