### ISSUE TITLE
PACKAGENAME: transmission 3.00 fails to build on NixOS 25.05 when enabling services.transmission

### ISSUE THREAD

**Issue by ltadeu6** [NixOS/nixpkgs#414072]
### Nixpkgs version

- Stable (25.05)

### Describe the bug

When enabling services.transmission.enable = true; in my configuration.nix on NixOS 25.05 (Warbler), the system fails to build transmission-3.00 with the following error:

/nix/store/3rg09bs1ccvgg1czgpv91ybw25fms6c8-miniupnpc-2.3.3/include/miniupnpc/upnpcommands.h:397:37: error: unknown type name 'size_t'
note: 'size_t' is defined in header '<stddef.h>'

This happens when running:

sudo nixos-rebuild switch

I also tried the following troubleshooting steps:

- Clearing possible partial builds with `nix-collect-garbage -d`, `nixos-rebuild switch --option keep-going false`, `nix-store --verify --check-contents --repair` and `sudo nix-store --gc`.
- Running `nix-shell -p transmission` → same build failure.
- Deleted old /var/lib/transmission folder as to evade issue [ GH-410761](https://github.com/NixOS/nixpkgs/issues/410761)

### Steps to reproduce

Enabling `services.transmission.enable = true`, no additional settings needed

### Expected behaviour

Build to succeed and the service to start

### Relevant log output

```console
[ 42%] Building C object libtransmission/CMakeFiles/transmission.dir/upnp.c.o
In file included from /build/source/libtransmission/upnp.c:13:
/nix/store/3rg09bs1ccvgg1czgpv91ybw25fms6c8-miniupnpc-2.3.3/include/miniupnpc/upnpcommands.h:397:37: error: unknown type name 'size_t'
  397 |                                     size_t desclen,
      |                                     ^~~~~~
/nix/store/3rg09bs1ccvgg1czgpv91ybw25fms6c8-miniupnpc-2.3.3/include/miniupnpc/upnpcommands.h:26:1: note: 'size_t' is defined in header '<stddef.h>'
```

### Additional context

The service was working before, I was messing with cuda packages and went to rebuild and upgrade with `nixos-rebuild switch --upgrade` and got the error, I then reverted everything in the configuration.nix and the error persisted, analyzing the log i found that the error was caused by transmission, disabling the service the rebuild succeeds.

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.31, NixOS, 25.05 (Warbler), 25.05.803396.8f1b52b04f2c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.3`
 - channels(root): `"nixos-25.05"`
 - nixpkgs: `/nix/store/cx77jv4ryh7hkh2r041cf9hnf9y3q2i7-nixos-25.05/nixos`

### Notify maintainers

@astsmtl 
---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ctrlaltf2** [comment]
Also breaks sunshine. Should be fixed once [miniupnpc@d691a0e8](https://github.com/miniupnp/miniupnp/commit/e263ab6f56c382e10fed31347ec68095d691a0e8) hits 25.05.

**Comment by phanirithvij** [comment]
should be fixed now, https://github.com/NixOS/nixpkgs/pull/413994

close this issue if it works.

**Comment by Orisphera** [comment]
> should be fixed now, https://github.com/NixOS/nixpkgs/pull/413994
> 
> close this issue if it works.

It still fails on my system. Also, it builds fine when importing nixpkgs in nix-shell (`nix-shell -p "(import <nixos> {}).transmission_3" --run ""`)

**Comment by phanirithvij** [comment]
you need to update your channels or flake

**Comment by FliegendeWurst** [comment]
The PR already reached 25.05-small, it should reach 25.05 soon. https://nixpk.gs/pr-tracker.html?pr=413994

**Comment by phanirithvij** [comment]
it is now in nixos-25.05, sorry for the earlier misinformation.

update your channels or flake. please reopen this issue if it still occurs.

The original commit which caused the failure is not yet in nixos-unstable, follow https://nixpk.gs/pr-tracker.html?pr=413829 if it breaks on nixos-unstable.
