### ISSUE TITLE
Darwin xz is broken in unstable

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#126617]
`xz.x86_64-darwin` is now failing, and blocking the unstable channel

https://hydra.nixos.org/build/145208114/nixlog/46

cc @NixOS/darwin-maintainers @thefloweringash

**Comment by r-burns** [comment]
Minimal reproducer:
`nix-build pkgs/stdenv/darwin/make-bootstrap-tools.nix -A test-pkgs.stdenv.__bootPackages.stdenv.__bootPackages.stdenv.__bootPackages.xz`

Bisected to https://github.com/NixOS/nixpkgs/commit/4a2698221baa64754258e8a24706b4c1aeadf59a

Relevant snippet of config.log:
```
 165   │ configure:5938: checking for clang option to accept ISO C99
 166   │ configure:6087: clang  -c -g -O2  conftest.c >&5
 167   │ conftest.c:42:10: fatal error: 'stdbool.h' file not found
 168   │ #include <stdbool.h>
 169   │          ^~~~~~~~~~~
 170   │ 1 error generated.
 171   │ configure:6087: $? = 1
```

cc @toonn

**Comment by r-burns** [comment]
Oh I see, the stdenv setup logic is wrong when stdenv's cc version doesn't match the bootstrap tools because it tries to use a nonexistent include dir. The following patch should fix it but rebuilds the world, is there a clever way we can avoid rebuilds?

```diff
--- a/pkgs/stdenv/darwin/default.nix
+++ b/pkgs/stdenv/darwin/default.nix
@@ -100,7 +100,7 @@ in rec {
       mkExtraBuildCommands = cc: ''
         rsrc="$out/resource-root"
         mkdir "$rsrc"
-        ln -s "${cc.lib or cc}/lib/clang/${cc.version}/include" "$rsrc"
+        ln -s ${cc.lib or cc}/lib/clang/*/include "$rsrc"
         ln -s "${last.pkgs."${finalLlvmPackages}".compiler-rt.out}/lib" "$rsrc/lib"
         echo "-resource-dir=$rsrc" >> $out/nix-support/cc-cflags
       '';
```

**Comment by thefloweringash** [comment]
The bootstrap files contain some version of llvm, we could make this an explicit part of the tools.

More generally, the test here is quite strict: it builds all the way to `stdenv` with new bootstrap tools but using current stdenv structure. When there are significant changes being made to the bootstrap tools that require stdenv changes this test makes it almost impossible. We've previously temporarily disabled this test to make such changes (#104013).

<details>
<summary>Explicit versions patch</summary>

```diff
diff --git a/pkgs/stdenv/darwin/default.nix b/pkgs/stdenv/darwin/default.nix
index 4ff512386e8..2831e3d52c2 100644
--- a/pkgs/stdenv/darwin/default.nix
+++ b/pkgs/stdenv/darwin/default.nix
@@ -18,6 +18,7 @@
       mkdir = fetch { file = "mkdir"; sha256 = "1m9nk90paazl93v43myv2ay68c1arz39pqr7lk5ddbgb177hgg8a"; };
       cpio = fetch { file = "cpio"; sha256 = "17pxq61yjjvyd738fy9f392hc9cfzkl612sdr9rxr3v0dgvm8y09"; };
       tarball = fetch { file = "bootstrap-tools.cpio.bz2"; sha256 = "1v2332k33akm6mrm4bj749rxnnmc2pkbgcslmd0bbkf76bz2ildy"; executable = false; };
+      llvmVersion = "11.1.0";
     }
   else
     let
@@ -32,6 +33,7 @@
       mkdir = fetch { file = "mkdir"; sha256 = "sha256-nmvMxmfcY41/60Z/E8L9u0vgePW5l30Dqw1z+Nr02Hk="; };
       cpio = fetch { file = "cpio"; sha256 = "sha256-cB36rN3NLj19Tk37Kc5bodMFMO+mCpEQkKKo0AEMkaU="; };
       tarball = fetch { file = "bootstrap-tools.cpio.bz2"; sha256 = "sha256-kh2vKmjCr/HvR06czZbxUxV5KDRxSF27M6nN3cyofRI="; executable = false; };
+      llvmVersion = "7.1.0";
     }
 }:
 
@@ -41,7 +43,7 @@ let
   inherit (localSystem) system;
 
   # Bootstrap version needs to be known to reference headers included in the bootstrap tools
-  bootstrapLlvmVersion = if localSystem.isAarch64 then "11.1.0" else "7.1.0";
+  bootstrapLlvmVersion = bootstrapFiles.llvmVersion;
 
   useAppleSDKLibs = localSystem.isAarch64;
   haveKRB5 = localSystem.isx86_64;
diff --git a/pkgs/stdenv/darwin/make-bootstrap-tools.nix b/pkgs/stdenv/darwin/make-bootstrap-tools.nix
index 08b4372a0a1..b0eb9a7600b 100644
--- a/pkgs/stdenv/darwin/make-bootstrap-tools.nix
+++ b/pkgs/stdenv/darwin/make-bootstrap-tools.nix
@@ -260,6 +260,7 @@ in rec {
     mkdir   = "${build}/on-server/mkdir";
     cpio    = "${build}/on-server/cpio";
     tarball = "${build}/on-server/bootstrap-tools.cpio.bz2";
+    llvmVersion = llvmPackages.llvm.version;
   };
 
   unpack = stdenv.mkDerivation (bootstrapFiles // {

```

</deatils>

**Comment by LnL7** [comment]
Yeah, the next bootstrap tools will depend on https://github.com/NixOS/nixpkgs/pull/126411 so it's somewhat expected that the stdenv test fails. I missed that build when testing.
