### ISSUE TITLE
pkgs.khard doesn't build on nixos-21.11

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#157676]
### Describe the bug

The khard package doesn't build anymore on the current stable channel
(nixos-21.11, commit 0f316e4). It builds fine on the master branch still.

Failed build log on Hydra:
https://hydra.nixos.org/build/165974436/nixlog/1/tail

### Steps To Reproduce

1. `cd nixpkgs; git checkout 0f316e4`
2. `nix build .#khard`
3. Observe build error (in check phase)

### "Screenshots"

```log
❯ nix build .#khard
error: builder for '/nix/store/6zyqdm6ibl6cbp3a9sgl4appp9yf7c47-khard-0.17.0.drv' failed with exit code 1;
       last 10 log lines:
       >     from .query import AnyQuery, Query
       > ImportError: cannot import name 'AnyQuery' from partially initialized module 'khard.query' (most likely due to a circular import) (/build/khard-0.17.0/khard/query.py)
       >
       >
       > ----------------------------------------------------------------------
       > Ran 256 tests in 0.714s
       >
       > FAILED (errors=1)
       > Test failed: <unittest.runner.TextTestResult run=256 errors=1 failures=0>
       > error: Test failed: <unittest.runner.TextTestResult run=256 errors=1 failures=0>
       For full logs, run 'nix log /nix/store/6zyqdm6ibl6cbp3a9sgl4appp9yf7c47-khard-0.17.0.drv'.
```

### Notify maintainers

Maintainer of the package: @matthiasbeyer

**Comment by matthiasbeyer** [comment]
I cannot find commit 21659c8 on nixos-21.11?

**Comment by pacien** [comment]
This was a copy-pasting error, sorry about that.
The commit is 0f316e4.

**Comment by matthiasbeyer** [comment]
On that commit, khard builds fine for me.

**Comment by vcunat** [comment]
On Hydra as well, on the second attempt 🤷🏽

**Comment by pacien** [comment]
I'm not sure of why it's not building on my machines, but I'll close this since
the package is now available on the public cache.
