### ISSUE TITLE
haskellPackages.reactive-banana-wx fails to build

### ISSUE THREAD

**Issue by bmueck** [NixOS/nixpkgs#47585]
## Issue description

The build of haskellPackages.reactive-banana-wx fails during compilation of tests/Distribution/MacOSX/Internal/Tests.hs because the data constructor ExecutableScopeUnknown is not in scope.

### Steps to reproduce

$ nix-env -f '<nixpkgs>' -iA 'haskellPackages.reactive-banana-wx'

This results in the following (abridged) output.

tests/Distribution/MacOSX/Internal/Tests.hs:74:51: error:
    Data constructor not in scope:
      ExecutableScopeUnknown :: ExecutableScope
   |
74 |                   , Executable "Dummy Two" "/tmp" ExecutableScopeUnknown  emptyBuildInfo ]
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^
builder for '/nix/store/5p3a09kl837nqyvgjlq9brh2sliw02yz-cabal-macosx-0.2.4.1.drv' failed with exit code 1
cannot build derivation '/nix/store/hi4yxnmvpn9j8kc07aiyfvdiajvdsmhs-reactive-banana-wx-1.1.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/hi4yxnmvpn9j8kc07aiyfvdiajvdsmhs-reactive-banana-wx-1.1.1.0.drv' failed

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-34-generic, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(bmueck): `"nixpkgs-18.09pre151052.4477cf04b67"`
 - nixpkgs: `/home/bmueck/.nix-defexpr/channels/nixpkgs`

**Comment by ElvishJerricco** [comment]
I tried to fix this up, but it seems like all the wx libraries are pretty unmaintained and broken. `wxc`, for instance, can't build with Cabal >= 2.0, and Cabal < 2.0 can't build with base >= 4.11. So there is seemingly no way at all to build `wxc` with GHC >= 8.4 until it gets fixed.

https://sourceforge.net/p/wxhaskell/bugs/112/

**Comment by peti** [comment]
This an upstream issue. They do not support recent versions of the Haskell compiler.
