### ISSUE TITLE
nox is broken

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#26392]
## Issue description

http://hydra.nixos.org/build/53887499

```
creating build/bdist.linux-x86_64/wheel/nix_nox-0.0.5.dist-info/WHEEL
installing
/build/nix-nox-0.0.5/dist /build/nix-nox-0.0.5
Traceback (most recent call last):
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/bin/.pip-wrapped", line 2, in <module>
    import sys;from pip import main
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

builder for ‘/nix/store/plq33y0pzhnnyqzb4l8v9y0ar8s4s2qw-nox-0.0.5.drv’ failed with exit code 1
```

Broken by bdd3f307397a9c2e7ed838865ec4e70f5c36c722.

**Comment by Ma27** [comment]
I can confirm that on `17.09pre108553.0011f9065a (Hummingbird)`.

**Comment by FRidh** [comment]
cc maintainer @madjar

**Comment by sjau** [comment]
same here

**Comment by nox** [comment]
In case anyone worries, I'm fine, thanks for your concern.

**Comment by FRidh** [comment]
A fix for bootstrapped-pip is in staging because its a mass-rebuild. Let's hope it won't break other stuff.

**Comment by cstrahan** [comment]
As of cd4d0c72a8, this is still failing.

**Comment by cstrahan** [comment]
Ah, never mind; user error on my part. Sorry for the noise.

If you're curious, I should have run `NIX_PATH=nixpkgs=$HOME/src/nixpkgs nix-shell  -p nox --run zsh`. The nix UI could really use some improvement.
