### PR TITLE
hasura: init at 1.2.1

### PR DESCRIPTION
**Pull request by offlinehacker**
###### About

This package is based on https://github.com/input-output-hk/cardano-explorer/tree/master/nix/nixos/graphql-engine who should also get most of the credit

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ivan @domenkozar

### CODE REVIEW

**Comment by offlinehacker** [comment]
Everything works as expected now. To test it locally:

```
nix-env -iA postgresql hasura-graphql-engine hasura-cli
mkdir -p postgres
initdb -D $PWD/hasuradb -A md5 -U root -W
postgres -D $PWD/hasuradb -k $PWD
createdb -h localhost hasura
graphql-engine --database-url=postgres://root:pass@localhost:5432/hasura serve
hasura console
```

File: pkgs/top-level/all-packages.nix [hunk 1]
```diff
@@ -15091,6 +15091,10 @@ in
 
   haka = callPackage ../tools/security/haka { };
 
+  hasura-graphql-engine = (callPackage ../servers/hasura { }).graphql-engine;
+
+  hasura-cli = (callPackage ../servers/hasura { }).cli;
```
Comment (danbst) [inline pkgs/top-level/all-packages.nix]: I'd suggest
```
inherit (callPackage ../servers/hasura { })
  hasura-cli
  hasura-graphql-engine
;
```
We already have precendents of this style in `all-packages.nix`. But sure, this is optional.

File: pkgs/servers/hasura/cli.nix [hunk 2]
```diff
@@ -0,0 +1,33 @@
+{ buildGoPackage, graphql-engine }:
+
+buildGoPackage rec {
```
[the remark this answers is not in the document]
Comment (offlinehacker) [reply pkgs/servers/hasura/cli.nix]: Version `1.0.0` does not use go modules yet, see here: https://github.com/hasura/graphql-engine/tree/v1.0.0/cli

File: pkgs/top-level/all-packages.nix (hunk 1 above)
Comment (offlinehacker) [reply pkgs/top-level/all-packages.nix]: Okay, i did suggested change

**Comment by offlinehacker** [comment]
Updated to version `1.0.0`, which was just released :)

**Comment by offlinehacker** [comment]
Can confirm version `1.0.0` working locally.

File: pkgs/servers/hasura/cli.nix (hunk 2 above)
[the remark this answers is not in the document]
Comment (danbst) [reply pkgs/servers/hasura/cli.nix]: ah yeah, I was looking at `master` and hadn't noticed it was introduced 7 days ago.

[the remark this answers is not in the document]
Comment (offlinehacker) [reply pkgs/servers/hasura/cli.nix]: We can change to `buildGoModule` on next release.

**Comment by elohmeier** [comment]
After rebasing onto master (0e6ceb8 as of writing) the build for graphql-engine fails:
```
Building library for graphql-engine-1.0.0..
...
[ 54 of 145] Compiling Hasura.HTTP      ( src-lib/Hasura/HTTP.hs, dist/build/Hasura/HTTP.o )
[ 55 of 145] Compiling Hasura.Server.CheckUpdates ( src-lib/Hasura/Server/CheckUpdates.hs, dist/build/Hasura/Server/CheckUpdates.o )
[ 56 of 145] Compiling Network.URI.Extended ( src-lib/Network/URI/Extended.hs, dist/build/Network/URI/Extended.o )

src-lib/Network/URI/Extended.hs:29:10: error:
    Duplicate instance declarations:
      instance Lift URI
        -- Defined at src-lib/Network/URI/Extended.hs:29:10
      instance [safe] Lift URI -- Defined in ‘Network.URI’
   |
29 | instance Lift URI
   |          ^^^^^^^^

builder for '/nix/store/5hb8n3ybiaffr0wjs17j4nilkasg3qqi-graphql-engine-1.0.0.drv' failed with exit code 1
```
I was able to build and run (on your branch) before rebasing successfully.

**Comment by bram209** [comment]
I would like to use this, is there anything I can do to help getting this PR merged?

**Comment by domenkozar** [comment]
@GrahamcOfBorg build hasura-cli

**Comment by domenkozar** [comment]
@offlinehacker could you rebase?

**Comment by offlinehacker** [comment]
Ok, this was quite a challenge, but was able to update to `1.1.1` and rebase package. I had learned quite a bit about haskell packaging, and also described in `default.nix` how i generated some files. It's still quite a manual process to get all the versions right, but i think (and hope) it should not break on update of haskell packages.

I can confirm that executables run, but i did not do any additional testing yet. So if someone has time it would be nice to check if everything works as expected.

**Comment by offlinehacker** [comment]
@GrahamcOfBorg build hasura-graphql-engine hasura-cli

**Comment by elohmeier** [comment]
Thanks for the updated PR, @offlinehacker. I've just tested the graphql-engine and the hasura console with a development project, everything works as expected.

**Comment by domenkozar** [comment]
I didn't have time to dig in, but those package should be coming from `haskellPackages` unless they are not on hackage. @offlinehacker did you check?

**Comment by offlinehacker** [comment]
@domenkozar the problem is hasura is quite picky about some package versions(or it does not build) and haskellPackages only have one version, so for all version constrained dependencies that require older versions, I cannot use one from haskellPackages. This also seems one of limitation of haskellPackages, as it asumes only one version of package. Regardless of that I still managed to build hasura, but is not completely automated process, as alternative would probably generate a large file with dependencies, and that's not desirable in nixpkgs, which are already polluted with large auto generated files. Also three packages used by hasura are not on hackage.

File: pkgs/servers/hasura/graphql-engine.nix [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+}:
+mkDerivation {
+  pname = "graphql-engine";
+  version = "1.0.0";
+  src = fetchgit {
+    url = "https://github.com/hasura/graphql-engine.git";
+    sha256 = "0v5fs4ma2vxs1bygp45j62jg68bk4skvnf8g9j81b6jydda18lzs";
+    rev = "ad07c06e5037f0deb83a2d3ccf1703df6cad1d35";
+    fetchSubmodules = true;
+  };
```
Comment (elohmeier) [inline pkgs/servers/hasura/graphql-engine.nix:30]:
```suggestion
mkDerivation rec {
  pname = "graphql-engine";
  version = "1.1.1";
  src = fetchgit {
    url = "https://github.com/hasura/graphql-engine.git";
    sha256 = "0v5fs4ma2vxs1bygp45j62jg68bk4skvnf8g9j81b6jydda18lzs";
    rev = "v${version}";
    fetchSubmodules = true;
  };
```

The wrong version is referenced here, I would also suggest to reference the tag so they can't differ.

**Review by elohmeier — CHANGES_REQUESTED** [review]

File: pkgs/servers/hasura/graphql-engine.nix (hunk 3 above)
Comment (offlinehacker) [reply pkgs/servers/hasura/graphql-engine.nix:30]: It is overriden in `default.nix` so it's ok, this is because it is autogenerated and wrong version is in cabal file of hasura

**Comment by offlinehacker** [comment]
Can someone please review and if have some better suggestion how to package this. I don't want to rebase again, so i want to merge or close this pull request.

File: pkgs/servers/hasura/graphql-engine.nix (hunk 3 above)
Comment (elohmeier) [reply pkgs/servers/hasura/graphql-engine.nix:30]: Ah, sorry - I've overlooked that. Thanks for the clarification.

**Review by elohmeier — APPROVED** [review]

**Comment by offlinehacker** [comment]
I will rebase and rebuild tomorrow, if everything still works let's merge.

**Comment by offlinehacker** [comment]
Updated to `1.2.1` and tested locally, everything seems to work. I will merge after @GrahamcOfBorg builds pass.

**Comment by offlinehacker** [comment]
@GrahamcOfBorg build hasura-graphql-engine hasura-cli

**Comment by hgiasac** [comment]
@offlinehacker Several things need to be changed:

- New Hasura CLI (from 1.2.0) has extension plugin that is installed into `~/.hasura/plugins/bin/hasura-cli_ext` when run `hasura-cli`. This breaking change is due to new feature of v2 migration and action plugins.

This extension binary requires `libstdc++.so.6` library.

```sh
ldd ~/.hasura/plugins/bin/hasura-cli_ext

linux-vdso.so.1 (0x00007ffd2cbeb000)
        libdl.so.2 => /nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/libdl.so.2 (0x00007f42c6e18000)
        librt.so.1 => /nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/librt.so.1 (0x00007f42c6e0e000)
        libstdc++.so.6 => not found
        libm.so.6 => /nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/libm.so.6 (0x00007f42c6cce000)
        libgcc_s.so.1 => /nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/libgcc_s.so.1 (0x00007f42c6cb4000)
        libpthread.so.0 => /nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/libpthread.so.0 (0x00007f42c6c93000)
        libc.so.6 => /nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/libc.so.6 (0x00007f42c6ad2000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib64/ld-linux-x86-64.so.2 (0x00007f42c6e1f000)
```
The CLI still works with SQL migrations, but metadata doesn't. New commands such as action generator don't work too

- From GraphQL Engine v1.2.2, Hasura team upgrade compiler to GHC 8.10.

**Comment by mrkkrp** [comment]
The packages have been removed from `nixpkgs` in 008570968ca42afa078c54cde3a3b3c650c6c3b9. :-|

**Comment by domenkozar** [comment]
That went exactly as I expected :)

**Comment by offlinehacker** [comment]
@domenkozar well it was best effort to package hasura, with what we have in nixpkgs. I was ready for other suggestions, but Haskell packaging facility in nixpkgs does not seem to be ready to package more complex packahes. In fact according to my observations also other Haskell packages in nixpkgs break many times.

**Comment by domenkozar** [comment]
My comment wasn't mean to criticize your work, quite on the contrary I think it's a shame that it didn't turn out differently.

I propose to package with haskell.nix and cachix, just as I did with https://github.com/cachix/ghcide-nix
