### ISSUE TITLE
sagemath derivation fails

### ISSUE THREAD

**Issue by jfaure** [NixOS/nixpkgs#101268]
src/lp_cdd.cpp:4:10: fatal error: setoper.h: No such file or directory

**Comment by omasanori** [comment]
Hello, @jfaure!
I have no idea what environment you use, but you might get a working SageMath by saving the following code as `shell.nix`:
```nix
{ pkgs ? import (fetchTarball
  "https://github.com/NixOS/nixpkgs/archive/9480bae337095fd24f61380bce3174fdfe926a00.tar.gz") {}
}:
pkgs.mkShell {
  buildInputs = [ pkgs.sage ];
}
```
and running `nix-shell`.

The build failure you described was fixed in https://github.com/NixOS/nixpkgs/pull/101046 but building `sage` itself is not yet recovered. Currently, some devs including myself have been trying to update SageMath to a newer version.

**Comment by collares** [comment]
Sage has been working for a while now and will be in 21.05. Please reopen if you are still having problems.
