### PR TITLE
nethogs: pull upstream fix for ncurses-6.3

### PR DESCRIPTION
**Pull request by trofi**
Without the fix build on ncurses-6.3 fails as:

    cui.cpp: In function ‘void show_ncurses(Line**, int)’:
    cui.cpp:377:73: error: format not a string literal and no format arguments [-Werror=format-security]
      377 |   mvprintw(3 + 1 + i, cols - COLUMN_WIDTH_UNIT, desc_view_mode[viewMode]);
          |                                                                         ^

### CODE REVIEW

**Comment by rycee** [comment]
Thanks!
