### PR TITLE
openmw: fix build with Qt 6.10

### LINKED ISSUE #455160: Build failure: openmw
### Nixpkgs version

- Unstable (25.11)

### Steps to reproduce

Run `nix build 'git+https://github.com/NixOS/nixpkgs?ref=nixos-unstable#openmw'` and observe the build fails.

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

https://hydra.nixos.org/build/310421985

### Relevant log output

```console
build/source/components/vfs/qtconversion.cpp: In function 'VFS::Path::Normalized VFS::Path::normalizedFromQString(QStringView)':
/build/source/components/vfs/qtconversion.cpp:19:28: error: call of overloaded 'Normalized(<brace-enclosed initializer list>)' is ambiguous
   19 |     return Normalized{ tmp };
      |                            ^
In file included from /build/source/components/vfs/qtconversion.hpp:6,
                 from /build/source/components/vfs/qtconversion.cpp:2:
/build/source/components/vfs/pathutil.hpp:144:18: note: candidate: 'VFS::Path::Normalized::Normalized(const char*)'
  144 |         explicit Normalized(const char* value)
      |                  ^~~~~~~~~~
/build/source/components/vfs/pathutil.hpp:139:18: note: candidate: 'VFS::Path::Normalized::Normalized(std::string_view)'
  139 |         explicit Normalized(std::string_view value)
      |                  ^~~~~~~~~~
/build/source/components/vfs/qtconversion.cpp: In function 'VFS::Path::Normalized VFS::Path::normalizedFromQString(QString&&)':
/build/source/components/vfs/qtconversion.cpp:25:28: error: call of overloaded 'Normalized(<brace-enclosed initializer list>)' is ambiguous
   25 |     return Normalized{ tmp };
      |                            ^
/build/source/components/vfs/pathutil.hpp:144:18: note: candidate: 'VFS::Path::Normalized::Normalized(const char*)'
  144 |         explicit Normalized(const char* value)
      |                  ^~~~~~~~~~
/build/source/components/vfs/pathutil.hpp:139:18: note: candidate: 'VFS::Path::Normalized::Normalized(std::string_view)'
  139 |         explicit Normalized(std::string_view value)
      |                  ^~~~~~~~~~
[ 47%] Building CXX object apps/essimporter/CMakeFiles/openmw-essimporter.dir/importercontext.cpp.o
[ 47%] Building CXX object apps/essimporter/CMakeFiles/openmw-essimporter.dir/converter.cpp.o
make[2]: *** [components/CMakeFiles/components_qt.dir/build.make:282: components/CMakeFiles/components_qt.dir/vfs/qtconversion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 47%] Building CXX object apps/openmw/CMakeFiles/openmw-lib.dir/mwrender/navmesh.cpp.o
[ 47%] Building CXX object apps/essimporter/CMakeFiles/openmw-essimporter.dir/convertacdt.cpp.o
[ 47%] Building CXX object apps/essimporter/CMakeFiles/openmw-essimporter.dir/convertnpcc.cpp.o
[ 47%] Building CXX object apps/essimporter/CMakeFiles/openmw-essimporter.dir/convertinventory.cpp.o
[ 47%] Building CXX object apps/openmw/CMakeFiles/openmw-lib.dir/mwrender/actorspaths.cpp.o
[ 47%] Building CXX object apps/essimporter/CMakeFiles/openmw-essimporter.dir/convertcrec.cpp.o
/build/source/components/files/qtconversion.cpp: In function 'std::filesystem::__cxx11::path Files::pathFromQString(QStringView)':
/build/source/components/files/qtconversion.cpp:21:70: error: call of overloaded 'stringToU8String(const QByteArray&)' is ambiguous
   21 |     return std::filesystem::path{ Misc::StringUtils::stringToU8String(tmp) };
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
```

### Additional context

I'm guessing this build failure is due to the bump to Qt 6.10 if that helps.

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.17.3, NixOS, 25.11 (Xantusia), 25.11.20251022.01f116e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.31.2`
 - nixpkgs: `/nix/store/sqilaxdxljyalv530z1qrd1q3nd4lyxq-source`

### Notify maintainers

@marius851000 @SigmaSquadron

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+build+failure%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Sirius902**
Resolves #455160

## Things done

- Built on platform:
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [X] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [X] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [X] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SigmaSquadron — APPROVED** [review]

**Comment by SigmaSquadron** [comment]
Alright, we can try this.
