### PR TITLE
fltk*: Bump

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Motivation for this change
Bumping fltk versions.

WIPs:
- [x] [1.3.8 was released a month ago](https://www.fltk.org/articles.php?L1782) but didn't get a tag on the GitHub repo. I'll open an issue about it
- [x] Test if it & reverse dependencies build & work on all platforms (I can test x86_64-{linux,darwin} and aarch64-linux)
- [ ] Test if any patches/workarounds can be removed

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OPNA2608** [comment]
Here's a first nixpkgs-review run:

Result of `nixpkgs-review pr 151782` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>octave-jit</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>fldigi</li>
  </ul>
</details>
<details>
  <summary>138 packages built:</summary>
  <ul>
    <li>afterstep</li>
    <li>alsa-tools</li>
    <li>bumblebee</li>
    <li>crowbar</li>
    <li>csound</li>
    <li>csound-qt</li>
    <li>cubicsdr</li>
    <li>dillo</li>
    <li>dump1090</li>
    <li>ensemble-chorus</li>
    <li>eureka-editor</li>
    <li>exrdisplay</li>
    <li>faust2csound</li>
    <li>flightgear</li>
    <li>fllog</li>
    <li>flmsg</li>
    <li>flpsed</li>
    <li>flrig</li>
    <li>fltk</li>
    <li>fltk-minimal</li>
    <li>fltk14</li>
    <li>fltk14-minimal</li>
    <li>fltrator</li>
    <li>flwrap</li>
    <li>gama</li>
    <li>giac-with-xcas</li>
    <li>giada</li>
    <li>gmsh</li>
    <li>gnss-sdr</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>ja2-stracciatella</li>
    <li>jwm-settings-manager</li>
    <li>librsb</li>
    <li>limesuite</li>
    <li>liquidwar</li>
    <li>lmms</li>
    <li>minc_widgets</li>
    <li>mup</li>
    <li>new-session-manager</li>
    <li>octave</li>
    <li>octaveFull</li>
    <li>octavePackages.arduino</li>
    <li>octavePackages.audio</li>
    <li>octavePackages.bim</li>
    <li>octavePackages.bsltl</li>
    <li>octavePackages.cgi</li>
    <li>octavePackages.communications</li>
    <li>octavePackages.control</li>
    <li>octavePackages.data-smoothing</li>
    <li>octavePackages.database</li>
    <li>octavePackages.dataframe</li>
    <li>octavePackages.dicom</li>
    <li>octavePackages.divand</li>
    <li>octavePackages.doctest</li>
    <li>octavePackages.econometrics</li>
    <li>octavePackages.financial</li>
    <li>octavePackages.fits</li>
    <li>octavePackages.fpl</li>
    <li>octavePackages.fuzzy-logic-toolkit</li>
    <li>octavePackages.ga</li>
    <li>octavePackages.general</li>
    <li>octavePackages.generate_html</li>
    <li>octavePackages.geometry</li>
    <li>octavePackages.gsl</li>
    <li>octavePackages.image</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.instrument-control</li>
    <li>octavePackages.interval</li>
    <li>octavePackages.io</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.linear-algebra</li>
    <li>octavePackages.lssa</li>
    <li>octavePackages.ltfat</li>
    <li>octavePackages.mapping</li>
    <li>octavePackages.matgeom</li>
    <li>octavePackages.miscellaneous</li>
    <li>octavePackages.msh</li>
    <li>octavePackages.mvn</li>
    <li>octavePackages.nan</li>
    <li>octavePackages.ncarray</li>
    <li>octavePackages.netcdf</li>
    <li>octavePackages.nurbs</li>
    <li>octavePackages.ocl</li>
    <li>octavePackages.octclip</li>
    <li>octavePackages.octproj</li>
    <li>octavePackages.optics</li>
    <li>octavePackages.optim</li>
    <li>octavePackages.optiminterp</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.quaternion</li>
    <li>octavePackages.queueing</li>
    <li>octavePackages.signal</li>
    <li>octavePackages.sockets</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.splines</li>
    <li>octavePackages.statistics</li>
    <li>octavePackages.stk</li>
    <li>octavePackages.strings</li>
    <li>octavePackages.struct</li>
    <li>octavePackages.symbolic</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.tsa</li>
    <li>octavePackages.video</li>
    <li>octavePackages.windows</li>
    <li>octavePackages.zeromq</li>
    <li>openems</li>
    <li>openwebrx</li>
    <li>paulstretch</li>
    <li>posterazor</li>
    <li>pothos</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.soapysdr-with-plugins</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.soapysdr-with-plugins</li>
    <li>qradiolink</li>
    <li>rakarrack</li>
    <li>rtl_433</li>
    <li>sdrangel</li>
    <li>seaview</li>
    <li>soapysdr-with-plugins</li>
    <li>solfege</li>
    <li>tigervnc</li>
    <li>urh</li>
    <li>virtualgl</li>
    <li>virtualglLib</li>
    <li>welle-io</li>
    <li>xautoclick</li>
    <li>yoshimi</li>
    <li>zynaddsubfx-fltk</li>
  </ul>
</details>

---

`fldigi` complains during configure:
> ```
> checking for fltk-config... /nix/store/ylfmx4b1hw2q3xmfh7m3qiicrhszp04g-fltk-1.4.x-2021-12-21/bin/fltk-config
> configure: WARNING: fldigi may not work with FLTK 1.4.0
> ```

And the build error:
> ```
>   CXXLD    fldigi
> /nix/store/lbxfixyw1yk099pjyaiy3xj5dl7kxm1g-binutils-2.35.2/bin/ld: /nix/store/ylfmx4b1hw2q3xmfh7m3qiicrhszp04g-fltk-1.4.x-2021-12-21/lib/libfltk.so: undefined reference to `Fl::cairo_make_current(Fl_Window*)'
> collect2: error: ld returned 1 exit status
> ```

Will look into it.

**Comment by OPNA2608** [comment]
I've taken the liberty to mark `fldigi` broken on `x86_64-darwin` and `librsb` broken on Darwin in general because those builds haven't succeeded on Hydra in quite awhile.

**Comment by OPNA2608** [comment]
Result of `nixpkgs-review pr 151782` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>octave-jit</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
  </ul>
</details>
<details>
  <summary>139 packages built:</summary>
  <ul>
    <li>afterstep</li>
    <li>alsa-tools</li>
    <li>bumblebee</li>
    <li>crowbar</li>
    <li>csound</li>
    <li>csound-qt</li>
    <li>cubicsdr</li>
    <li>dillo</li>
    <li>dump1090</li>
    <li>ensemble-chorus</li>
    <li>eureka-editor</li>
    <li>exrdisplay</li>
    <li>faust2csound</li>
    <li>fldigi</li>
    <li>flightgear</li>
    <li>fllog</li>
    <li>flmsg</li>
    <li>flpsed</li>
    <li>flrig</li>
    <li>fltk</li>
    <li>fltk-minimal</li>
    <li>fltk14</li>
    <li>fltk14-minimal</li>
    <li>fltrator</li>
    <li>flwrap</li>
    <li>gama</li>
    <li>giac-with-xcas</li>
    <li>giada</li>
    <li>gmsh</li>
    <li>gnss-sdr</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>ja2-stracciatella</li>
    <li>jwm-settings-manager</li>
    <li>librsb</li>
    <li>limesuite</li>
    <li>liquidwar</li>
    <li>lmms</li>
    <li>minc_widgets</li>
    <li>mup</li>
    <li>new-session-manager</li>
    <li>octave</li>
    <li>octaveFull</li>
    <li>octavePackages.arduino</li>
    <li>octavePackages.audio</li>
    <li>octavePackages.bim</li>
    <li>octavePackages.bsltl</li>
    <li>octavePackages.cgi</li>
    <li>octavePackages.communications</li>
    <li>octavePackages.control</li>
    <li>octavePackages.data-smoothing</li>
    <li>octavePackages.database</li>
    <li>octavePackages.dataframe</li>
    <li>octavePackages.dicom</li>
    <li>octavePackages.divand</li>
    <li>octavePackages.doctest</li>
    <li>octavePackages.econometrics</li>
    <li>octavePackages.financial</li>
    <li>octavePackages.fits</li>
    <li>octavePackages.fpl</li>
    <li>octavePackages.fuzzy-logic-toolkit</li>
    <li>octavePackages.ga</li>
    <li>octavePackages.general</li>
    <li>octavePackages.generate_html</li>
    <li>octavePackages.geometry</li>
    <li>octavePackages.gsl</li>
    <li>octavePackages.image</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.instrument-control</li>
    <li>octavePackages.interval</li>
    <li>octavePackages.io</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.linear-algebra</li>
    <li>octavePackages.lssa</li>
    <li>octavePackages.ltfat</li>
    <li>octavePackages.mapping</li>
    <li>octavePackages.matgeom</li>
    <li>octavePackages.miscellaneous</li>
    <li>octavePackages.msh</li>
    <li>octavePackages.mvn</li>
    <li>octavePackages.nan</li>
    <li>octavePackages.ncarray</li>
    <li>octavePackages.netcdf</li>
    <li>octavePackages.nurbs</li>
    <li>octavePackages.ocl</li>
    <li>octavePackages.octclip</li>
    <li>octavePackages.octproj</li>
    <li>octavePackages.optics</li>
    <li>octavePackages.optim</li>
    <li>octavePackages.optiminterp</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.quaternion</li>
    <li>octavePackages.queueing</li>
    <li>octavePackages.signal</li>
    <li>octavePackages.sockets</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.splines</li>
    <li>octavePackages.statistics</li>
    <li>octavePackages.stk</li>
    <li>octavePackages.strings</li>
    <li>octavePackages.struct</li>
    <li>octavePackages.symbolic</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.tsa</li>
    <li>octavePackages.video</li>
    <li>octavePackages.windows</li>
    <li>octavePackages.zeromq</li>
    <li>openems</li>
    <li>openwebrx</li>
    <li>paulstretch</li>
    <li>posterazor</li>
    <li>pothos</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.soapysdr-with-plugins</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.soapysdr-with-plugins</li>
    <li>qradiolink</li>
    <li>rakarrack</li>
    <li>rtl_433</li>
    <li>sdrangel</li>
    <li>seaview</li>
    <li>soapysdr-with-plugins</li>
    <li>solfege</li>
    <li>tigervnc</li>
    <li>urh</li>
    <li>virtualgl</li>
    <li>virtualglLib</li>
    <li>welle-io</li>
    <li>xautoclick</li>
    <li>yoshimi</li>
    <li>zynaddsubfx-fltk</li>
  </ul>
</details>

---

Result of `nixpkgs-review pr 151782` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>octave-jit</li>
    <li>openems</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
  </ul>
</details>
<details>
  <summary>61 packages built:</summary>
  <ul>
    <li>afterstep</li>
    <li>alsa-tools</li>
    <li>crowbar</li>
    <li>csound</li>
    <li>csound-qt</li>
    <li>cubicsdr</li>
    <li>dillo</li>
    <li>dump1090</li>
    <li>ensemble-chorus</li>
    <li>eureka-editor</li>
    <li>exrdisplay</li>
    <li>faust2csound</li>
    <li>fldigi</li>
    <li>fllog</li>
    <li>flmsg</li>
    <li>flpsed</li>
    <li>flrig</li>
    <li>fltk (fltk13)</li>
    <li>fltk-minimal (fltk13-minimal)</li>
    <li>fltk14</li>
    <li>fltk14-minimal</li>
    <li>fltrator</li>
    <li>flwrap</li>
    <li>gama</li>
    <li>giac-with-xcas</li>
    <li>giada</li>
    <li>gnss-sdr</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>jwm-settings-manager</li>
    <li>librsb</li>
    <li>limesuite</li>
    <li>liquidwar</li>
    <li>minc_widgets</li>
    <li>mup</li>
    <li>octave</li>
    <li>octavePackages.audio</li>
    <li>openwebrx</li>
    <li>paulstretch</li>
    <li>posterazor</li>
    <li>pothos</li>
    <li>python38Packages.soapysdr-with-plugins</li>
    <li>python39Packages.soapysdr-with-plugins</li>
    <li>qradiolink</li>
    <li>rakarrack</li>
    <li>rtl_433</li>
    <li>sdrangel</li>
    <li>seaview</li>
    <li>soapysdr-with-plugins</li>
    <li>solfege</li>
    <li>tigervnc</li>
    <li>urh</li>
    <li>virtualgl</li>
    <li>virtualglLib</li>
    <li>xautoclick</li>
    <li>yoshimi</li>
    <li>zynaddsubfx-fltk</li>
  </ul>
</details>

---

Result of `nixpkgs-review pr 151782` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>eureka-editor</li>
    <li>fldigi</li>
    <li>librsb</li>
    <li>octave-jit</li>
    <li>octavePackages.dicom</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>octavePackages.gsl</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.ocl</li>
    <li>octavePackages.strings</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.video</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>fltk</li>
    <li>fltk-minimal</li>
    <li>fltk14</li>
    <li>fltk14-minimal</li>
    <li>gama</li>
    <li>ja2-stracciatella</li>
    <li>minc_widgets</li>
    <li>octave</li>
    <li>octaveFull</li>
    <li>octavePackages.bsltl</li>
    <li>octavePackages.cgi</li>
    <li>octavePackages.communications</li>
    <li>octavePackages.control</li>
    <li>octavePackages.data-smoothing</li>
    <li>octavePackages.database</li>
    <li>octavePackages.dataframe</li>
    <li>octavePackages.divand</li>
    <li>octavePackages.doctest</li>
    <li>octavePackages.econometrics</li>
    <li>octavePackages.financial</li>
    <li>octavePackages.fits</li>
    <li>octavePackages.fpl</li>
    <li>octavePackages.fuzzy-logic-toolkit</li>
    <li>octavePackages.ga</li>
    <li>octavePackages.general</li>
    <li>octavePackages.generate_html</li>
    <li>octavePackages.geometry</li>
    <li>octavePackages.image</li>
    <li>octavePackages.instrument-control</li>
    <li>octavePackages.interval</li>
    <li>octavePackages.io</li>
    <li>octavePackages.linear-algebra</li>
    <li>octavePackages.lssa</li>
    <li>octavePackages.ltfat</li>
    <li>octavePackages.mapping</li>
    <li>octavePackages.matgeom</li>
    <li>octavePackages.miscellaneous</li>
    <li>octavePackages.mvn</li>
    <li>octavePackages.nan</li>
    <li>octavePackages.ncarry</li>
    <li>octavePackages.netcdf</li>
    <li>octavePackages.nurbs</li>
    <li>octavePackages.octclip</li>
    <li>octavePackages.octproj</li>
    <li>octavePackages.optics</li>
    <li>octavePackages.optim</li>
    <li>octavePackages.optiminterp</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.quaternion</li>
    <li>octavePackages.queueing</li>
    <li>octavePackages.signal</li>
    <li>octavePackages.sockets</li>
    <li>octavePackages.splines</li>
    <li>octavePackages.statistics</li>
    <li>octavePackages.stk</li>
    <li>octavePackages.struct</li>
    <li>octavePackages.symbolic</li>
    <li>octavePackages.tsa</li>
    <li>octavePackages.windows</li>
    <li>octavePackages.zeromq</li>
  </ul>
</details>

octavePackages failures look unrelated?
Screenshot_macOS_2021-12-23_15:08:08
Screenshot_macOS_2021-12-23_15:08:34

---

Ran afew reverse dependencies (x86_64-linux) and test binaries (x86_64-darwin), seems to work fine. Will try to find the time & check on patch/workarounds progress upstream, otherwise ready for review.

**Comment by KarlJoad** [comment]
From an Octave Packages perspective, if they build the same as they did before, then that means all the packages are still passing all the tests that they are supposed to. I have no issue with this. Looks good to me.

With all the rebuilding done for Octave, it might be prudent to ping @doronbehar, as he is primary maintainer of Octave.

> octavePackages failures look unrelated?

I don't have a Mac to test those on, nor did I know how to cross-platform build when I originally wrote these packages, so no testing was done on/for Darwin. If they have failed for nearly a year, then that is something I should look into, but it will be some time before I can to that (probably not until June-ish). Marking it as broken is likely the most prudent move. Thanks.

**Review by ravenjoad — APPROVED** [review]
From an Octave Packages perspective, if they build the same as they did before, then that means all the packages are still passing all the tests that they are supposed to. I have no issue with this. Looks good to me.

With all the rebuilding done for Octave, it might be prudent to ping @doronbehar, as he is primary maintainer of Octave.

>octavePackages failures look unrelated?

I don't have a Mac to test those on, nor did I know how to cross-platform build when I originally wrote these packages, so no testing was done on/for Darwin. If they have failed for nearly a year, then that is something I should look into, but it will be some time before I can to that (probably not until June-ish). Marking it as broken is likely the most prudent move. Thanks.

**Comment by doronbehar** [comment]
> Result of `nixpkgs-review pr 151782` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 9 packages marked as broken and skipped:
> 6 packages failed to build:
> 
>     * octavePackages.gsl
> 
>     * octavePackages.level-set
> 
>     * octavePackages.ocl
> 
>     * octavePackages.strings
> 
>     * octavePackages.tisean
> 
>     * octavePackages.video

Perhaps we should set these as broken on darwin? Whether it's due to this PR or not..

**Comment by KarlJoad** [comment]
That makes the most sense right now. I don't know where the problem is, and I will not be able to fix it for quite some time.
I am good with marking them as broken.

**Comment by OPNA2608** [comment]
I've verified locally that all failing octave packages also fail identically on master & marked them broken on Darwin.

**Review by ravenjoad — APPROVED** [review]
Perfect. Thanks for marking these packages as broken. I hope to have time to look into this in the future.

**Review by doronbehar — APPROVED** [review]
