### PR TITLE
amdgpu-pro: 16.50 -> 16.60

### PR DESCRIPTION
**Pull request by corngood**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by corngood** [comment]
So far I've only tested this on linux-4.8.13 and Xorg-1.18.4.  Things to test:

- Boots on
  - [x] R9 290
  - [ ] Polaris
- [x] KMS
- [x] Xorg
- [x] x64 GL (glxgears)
- [ ] x86 GL
- [ ] x64 Vulkan
- [ ] x86 Vulkan
- [ ] x64 OpenCL
- [ ] x86 OpenCL
- [ ] x64 VDPAU **FAILED
- [ ] x86 VDPAU

**Comment by vcunat** [comment]
BTW, do you know anything about support for xorg-server-1.19.x?

**Comment by corngood** [comment]
@vcunat There is none, unfortunately.  We'll have to roll it back or wait for AMD.

**Comment by vcunat** [comment]
Well, we have `fglrxCompat` mechanism to force 1.17, so adding something like `amdgpuCompat` would be easy.

**Comment by plchldr** [comment]
I had to use Linux 4.4 because 4.8 has been removed. And it didn't quite work, so here's a log dump: [http://pastebin.com/qnzZwiXE](http://pastebin.com/qnzZwiXE)
BTW I tried the amdgpu and ati drivers and they too fail, no idea why ..

**Comment by corngood** [comment]
@plchldr thanks.  I'll see about patching this for 4.9.

**Comment by corngood** [comment]
@vcunat Thanks.  I generalised `fglrxCompat` to `abiCompat`, and used it for both drivers.  I know xorg is still 1.18 in this branch, but it should now survive an update.  BTW I couldn't actually build fglrx for either linux 4.4 or 4.9 due to compile errors in the kernel module.

@plchldr I applied a patch someone sent me for the arch driver.  It'll probably clean it up a bit, but it's very simple, and it now builds on 4.9.6.  I get a KMS switch on tty, but X crashes in the dri driver: http://ix.io/1RrB.

**Comment by vcunat** [comment]
Well, either the fglrx users have older kernels or there isn't anyone interested enough anymore.

**Comment by plchldr** [comment]
@corngood Do you want me to try again? If so you'd need to commit the 2nd patch.

**Comment by corngood** [comment]
@plchldr shit, my mistake.  I'll update that when I get home.

**Comment by plchldr** [comment]
[http://pastebin.com/aS3gLxnm](http://pastebin.com/aS3gLxnm)
The monitor shows slowly changing colors, which I've only seen after messing around with CRU (EDID overrides) under Windows.

**Comment by corngood** [comment]
@plchldr Well I've never seen anything like that.  Someone on Arch said he needed to set `amdgpu.dc=0` in kernel flags to get tty, but he still had the same crash in Xorg.

I'm thinking it's something like an incompatibility between the amdgpu-pro libdrm and linux-4.9 drm syscalls?

**Comment by corngood** [comment]
@plchldr My next step is to roll back the kernel to 4.8.  I'm expecting it to work, but I haven't tested that change in isolation.

**Comment by vcunat** [comment]
A new libdrm was released ~2 days ago, if that could be related.  I plan to stage it soon.

**Comment by corngood** [comment]
@plchldr I've updated it so it will use 4.8 (as long as you don't override kernelPackages in your config).  Could you give it a shot?  GL and vulkan are working ok for me.

@vcunat I reverted the change that removed 4.8, and set kernelPackages in the driver module.  What do you think of this approach?

**Comment by vcunat** [comment]
@corngood: there's a security problem &ndash; 4.8 isn't supported upstream anymore, and it will probably become vulnerable within weeks.  If it isn't vulnerable already and someone adds support for 4.9 soon, it might be a simple short-term solution.

Longer-term possibility: take kernel patches e.g. from [Ubuntu 16.10](http://packages.ubuntu.com/yakkety/linux-generic), as it's to be supported until July.

**Comment by abbradar** [comment]
I've looked through AMDGPU-PRO as I've touched graphics drivers lately and was interested how things are on AMD side. I noticed that Vulkan ICDs contain paths like `/opt/amdgpu-pro/lib/i386-linux-gnu/amdvlk32.so`. Those should probably be patched (not sure how it works like this).

**Comment by corngood** [comment]
@vcunat AMD has been updating this driver a several times a year, so hopefully the next release will support newer kernels.  Also if by some miracle they get merged upstream this may become userspace only.

@abbradar `postFixup` is patching the manifests to nix store paths, and doing some really sketchy replacement of `/usr/lib/` paths in string literals.  The module creates `/run/lib` (in the activation script) for this purpose.  I should actually go and verify this is still needed with 16.60.

**Comment by abbradar** [comment]
Oh, I got it now -- it replaces the string in `icd64` but not in `icd32` for 64-bit version. Maybe you want to remove the other one? Just a passerby remark though -- feel free to ignore ~_^.

**Comment by corngood** [comment]
@abbradar yeah I believe the reverse is also true for the 32 bit library.  It doesn't break anything, but it causes warnings in loader debug, so I'll remove the manifests for the other arch when I get around to testing i686.

**Comment by plchldr** [comment]
[http://pastebin.com/FbF31y6t](http://pastebin.com/FbF31y6t)
I don't really see a change, still just alternating colors.
Compiling Linux 4.8 took quite a while .. is it even necessary though? amdgpu-pro-16.50 works fine with Linux 4.4.
BTW the next release is supposed to land [in about 2 months](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/vulkan/927837-radv-now-supports-vulkan-1-0-39-s-vk_khr_get_physical_device_properties2?p=927938#post927938) and [is aimed at Linux 4.8](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/amd-linux/927510-amdgpu-pro-16-60-released?p=927561#post927561) (???)

**Comment by corngood** [comment]
@plchldr There are no custom kernel configs, so it's just compiling it because it's not in the cache any more.  If we did merge this it would get cached again.

You mentioned trying this driver with 4.4 and it didn't work, right?

I really don't know what's going on with your colours, or all the EDID errors.  I've talked to some Arch and Gentoo people about this driver, and I haven't heard of anything like that, but I'm not sure if any of them have Polaris.

Do you have another display you can test?  Other than that, maybe make sure the firmware it's loading is actually symlinked to amdgpu-pro and not just the upstream one?

**Comment by plchldr** [comment]
Sadly I only have this one monitor (QNIX2710). I guess the problem here is that it lacks a "scaler" and relies on the GPU doing the job, which will hopefully allow me to use Freesync soon like on Windows .. I guess this might indeed be a problem with the monitor and not with Polaris.

**Comment by corngood** [comment]
So I gave this a try on linux-4.4, and the module builds, but I get:

```
amdkcl: exports duplicate symbol drm_atomic_helper_duplicate_state (owned by drm_kms_helper)
```

I'm sure that particular problem could be fixed, but I don't really think it's worth putting effort into.

**Comment by corngood** [comment]
I got a fix from the guy who originally did the linux-4.9 patch.  Turns out it was just a small typo.  I was ready to give up, but luckily he wasn't.

So this should now work on either 4.8 or 4.9.  Kernel rollback is gone.

@plchldr I kind of doubt this will fix your problems, but let me know if you get a chance to try it.

@vcunat Any thoughts on the abiCompat thing?

**Comment by corngood** [comment]
Oh, I also added a patch to fix the remaining warnings and enabled `-Werror` in the hopes that it will catch more upstream breakage.  This is virtually guaranteed to need more work with each kernel release.

**Comment by vcunat** [comment]
`abiCompat` seems very good to me :-) I'm just about to test xorg-server-1.19.1 this week.

**Comment by corngood** [comment]
Ok, well I'm happy with this now, so I removed WIP.

I've tested with linux 4.8 and 4.9.  4.10 will probably require more patches, but I can coordinate that with other distros.  I'll also make sure to test it after Xorg 1.19 goes in.

**Comment by plchldr** [comment]
Alright, is there some easy way to keep 16.50 and still get updates for unstable?

**Comment by corngood** [comment]
@plchldr You should be able to take the old default.nix and `callPackage` it from your `packageOverrides`, or revert the 16.60 change in git and rebase on unstable if you already have a git repo for your nixpkgs.

Did you try last version I posted with linux 4.9?  Maybe we can still get it working.

**Comment by plchldr** [comment]
I tried, but there was no change. I'm not too interested in this particular release and assume the problem was introduced upstream anyway .. so thanks for the tip! That much I should be able to do.

**Comment by ninegua** [comment]
I'm having problem using this with an AMD RX 470 card on 64-bit Linux. Here is what I did:

1. add `services.xserver.videoDrivers = [ "amdgpu-pro" "modesetting" ];` to `/etc/nixos/configurations.nix`.

2. rebuild nixos:
```
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --update
nixos-rebuild switch -I nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs
```
However I get a kernel panic after reboot, right at the point where kernel tries to load amdgpu module. Did I do something wrong? Do I need to blacklist some kernel module or something? Any help is greatly appreciated!

**Comment by corngood** [comment]
@ninegua Well that's not good.  I tested with a bunch of different kernels and I never had a panic.  Do you have any kernel related things in your config?

I have:

```
boot.kernelPackages = pkgs.linuxPackages_latest;
```

Which should use 4.9.something.  However, I don't think the module even compiles against 4.4 (the default last time I checked).

Were you using amdgpu-pro before this update?

**Comment by ninegua** [comment]
@corngood Thanks for the quick reply . This is a new computer I'm building, so this is first time I am trying to get amdgpu-pro working. I'll try the `kernelPackages` thing.

Meanwhile, here is [a photo](http://thev.net/download/P2070181.JPG) showing the trace, see if you can spot anything wrong.

**Comment by corngood** [comment]
@ninegua Hmm, I see a reference to 4.9.8 in there.  I haven't tested that specific version yet, it looks like you are already on a '_latest' kernel.  Could you share your configuration.nix (minus any personal info)?

**Comment by ninegua** [comment]
Here is my full `configurations.nix`:

```
{ config, pkgs, ... }:
{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];
  boot.loader.gummiboot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.supportedFilesystems = [ "cifs" "exfat" "vfat" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  networking.hostName = "agent001"; # Define your hostname.
  time.timeZone = "US/Pacific";
  environment.systemPackages = with pkgs; [
    curl wget pciutils lm_sensors which inetutils psmisc
  ];
  services.openssh.enable = true;
  services.xserver.enable = true;
  services.xserver.videoDrivers = [ "amdgpu-pro" "modesetting" ];
  system.stateVersion = "16.09";
  nixpkgs.config.allowUnfree = true;
}

```

**Comment by corngood** [comment]
@ninegua Ok, looks like the `kernelPackages` is unnecessary.  It's been the default since late January.  I'm going to test 4.9.8 now.

**Comment by ninegua** [comment]
@corngood which kernel were you on? How do you fix a particular kernel version when rebuilding nixos?

**Comment by corngood** [comment]
@ninegua I was on 4.9.6.  You can't really fix a specific version, I was just out of date by a couple of weeks.  You can pick between the packages in nixpkgs, which right now include 4.4, 4.9, etc.

I just updated to latest master, which should be close to what you're using, and tested it with 4.9.8.  Everything seems to be working fine for me, but I'm using a 290...

Can you see if you can get a full text log from one of your boots where it crashed?  You can use `journalctl -b -1` to get the previous boot, etc.  When does it crash exactly?  It should go:

1. Stage 1
2. Stage 2
3. KMS transition (tty goes high res)
4. Xorg startup

I'm guessing it's either at 3 or 4, but if you see the tty go high res before the crash, then it would be 4.

The only real difference in my config is that I just have the one `videoDriver` (no modesetting), but that shouldn't make a difference.

**Comment by corngood** [comment]
tty looks high res in your photo, but I'm still curious if you actually see it change modes and if it crashes immediately on the mode change.

**Comment by ninegua** [comment]
@corngood It is actually crashing while loading display-manager. Here is part of the log:

```
Feb 07 19:38:42 agent001 display-manager[1370]: (II) LoadModule: "modesetting"
Feb 07 19:38:42 agent001 display-manager[1370]: (II) Loading /nix/store/dwijal6cqxp3d1nhfkvy3rrl5wqpkrb7-amdgpu-pro-16.60-4.9.8/lib/xorg/mod
Feb 07 19:38:42 agent001 display-manager[1370]: (II) Module modesetting: vendor="X.Org Foundation"
Feb 07 19:38:42 agent001 display-manager[1370]:         compiled for 1.18.4, module version = 1.18.4
Feb 07 19:38:42 agent001 display-manager[1370]:         Module class: X.Org Video Driver
Feb 07 19:38:42 agent001 display-manager[1370]:         ABI class: X.Org Video Driver, version 20.0
Feb 07 19:38:42 agent001 display-manager[1370]: (II) LoadModule: "amdgpu"
Feb 07 19:38:42 agent001 display-manager[1370]: (II) Loading /nix/store/dwijal6cqxp3d1nhfkvy3rrl5wqpkrb7-amdgpu-pro-16.60-4.9.8/lib/xorg/mod
Feb 07 19:38:42 agent001 display-manager[1370]: (II) Module amdgpu: vendor="X.Org Foundation"
Feb 07 19:38:42 agent001 display-manager[1370]:         compiled for 1.18.4, module version = 1.2.99
Feb 07 19:38:42 agent001 display-manager[1370]:         Module class: X.Org Video Driver
Feb 07 19:38:42 agent001 display-manager[1370]:         ABI class: X.Org Video Driver, version 20.0
Feb 07 19:38:42 agent001 display-manager[1370]: (II) modesetting: Driver for Modesetting Kernel Drivers: kms
Feb 07 19:38:42 agent001 display-manager[1370]: (II) AMDGPU: Driver for AMD Radeon:
Feb 07 19:38:42 agent001 display-manager[1370]:         All GPUs supported by the amdgpu kernel driver
Feb 07 19:38:42 agent001 dhcpcd[1378]: enp7s0: waiting for carrier
Feb 07 19:38:42 agent001 kernel: IPv6: ADDRCONF(NETDEV_UP): enp6s0: link is not ready
Feb 07 19:38:42 agent001 kernel: IPv6: ADDRCONF(NETDEV_UP): enp7s0: link is not ready
Feb 07 19:38:42 agent001 display-manager[1370]: (II) modeset(0): using drv /dev/dri/card0
Feb 07 19:38:42 agent001 display-manager[1370]: (II) [KMS] Kernel modesetting enabled.
Feb 07 19:38:42 agent001 display-manager[1370]: (II) AMDGPU(G0): ShareFD: disabled
Feb 07 19:38:42 agent001 display-manager[1370]: (DB) AMDGPU(G0): open fd=11
Feb 07 19:38:42 agent001 display-manager[1370]: (II) modeset(0): display fd=14 render fd=14
Feb 07 19:38:42 agent001 kernel: vgaarb: device changed decodes: PCI:0000:03:00.0,olddecodes=io+mem,decodes=none:owns=none
Feb 07 19:38:42 agent001 display-manager[1370]: (II) modeset(0): Creating default Display subsection in Screen section
Feb 07 19:38:42 agent001 display-manager[1370]:         "Screen-modesetting[0]" for depth/fbbpp 24/32
Feb 07 19:38:42 agent001 display-manager[1370]: (==) modeset(0): Depth 24, (==) framebuffer bpp 32
Feb 07 19:38:42 agent001 display-manager[1370]: (==) modeset(0): RGB weight 888
Feb 07 19:38:42 agent001 display-manager[1370]: (==) modeset(0): Default visual is TrueColor
Feb 07 19:38:42 agent001 display-manager[1370]: (II) Loading sub module "glamoregl"
Feb 07 19:38:42 agent001 display-manager[1370]: (II) LoadModule: "glamoregl"
Feb 07 19:38:42 agent001 display-manager[1370]: (II) Loading /nix/store/dwijal6cqxp3d1nhfkvy3rrl5wqpkrb7-amdgpu-pro-16.60-4.9.8/lib/xorg/mod
Feb 07 19:38:42 agent001 display-manager[1370]: (II) Module glamoregl: vendor="X.Org Foundation"
Feb 07 19:38:42 agent001 display-manager[1370]:         compiled for 1.18.4, module version = 1.0.0
Feb 07 19:38:42 agent001 kernel: BUG: unable to handle kernel NULL pointer dereference at 00000000000000a8
Feb 07 19:38:42 agent001 kernel: IP: [<ffffffffc09a3d60>] amdttm_pool_populate+0x110/0x5e0 [amdttm]
```

**Comment by corngood** [comment]
Could you try with only "amdgpu-pro" in your videoDriver list (i.e. remove modesetting) and paste the entire log on pastebin or something?  There's something weird going on with the drivers there.

**Comment by ninegua** [comment]
@corngood Indeed! It waws `modesetting` that is causing the crash. Without it, the machines boots fine, but still, fails to start the graphics system. Here is a link to the error log http://pastebin.com/kLCenHy3

`lspci|grep -i amd` shows the device:

```
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480] (rev cf)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device aaf0
```

**Comment by ninegua** [comment]
BTW, a side question, @corngood do you think it makes sense to retain necessary headers (e.g., OpenCL) from the `amdgpu-pro` build? Or do I have to go through my own installation of the AMD SDK to get it?

**Comment by corngood** [comment]
@ninegua You shouldn't need anything from amdgpu-pro to target OpenCL.  I would look at some of the apps in nixpkgs that use opencl to see how they get the headers/libs.

As for your xorg log, I've never seen `(EE) No devices detected.` before.  Do you have more than one gpu?

Also to double check, you have exactly `services.xserver.videoDrivers = [ "amdgpu-pro" ];`?

I have to call it a night, but you can always play with the open source drivers by using "amdgpu" instead of "amdgpu-pro".  They are pretty decent these days.

**Comment by ninegua** [comment]
@corngood mystery solved! I had to use a jump to disable the onboard VGA in order to get the AMD graphics card working. @corngood thanks a lot for the help, and for being patient with me here!

On the other hand, OpenCL doesn't work. Somehow there is a default `/run/opengl-driver/lib/libOpenCL.so.1`, which (I presume is from Mesa?) doesn't work. I also tried the `libOpenCL.so.1` from amdgpu-pro, as well as the one from AMDAPP-SDK 3.0 downloaded from AMD site. Neither works. Oh well, guess there is more homework for me to do.

**Comment by ninegua** [comment]
Ok, an update on the OpenCL stuff if anyone is interested:

1. It turns out that I need to properly set `OPENCL_VENDOR_PATH` environment variable in order for OpenCL programs to work. Under this directory there must be a `amdocl64.icd` file containing a single line of text that reads `llibamdocl64.so`. 

2. Also, I had to use both the `libOpenCL.so` and `libamdocl64.so` from `amdgpu-pro` installation, the binaries from AMD APP SDK do not seem to work for me. 

3. Likely it also requires having X running, which would have loaded `amdgpu-pro` drivers.

Anyway, I'm happy to report success, that is, until my other RX 470 cards arrive at the door tomorrow :-) I'm going to try multiple GPU setup, and see how far I can push the system.

**Comment by vcunat** [comment]
For reference, master now switched to xorg-server-1.19.1 by default, since 3348905cdecf.

**Comment by corngood** [comment]
@vcunat thanks for the heads up.  I just checked, and all is well on master.  Next up, making this survive linux-4.10.

**Comment by vcunat** [comment]
Well, 4.9 will remain the default kernel for several months at least, so I suppose there won't be so much hurry.

**Comment by ninegua** [comment]
Looks like the build process is broken in both the latest nixos and nixpkgs unstable channel. Here is what I got:

```
building path(s) ‘/nix/store/kvd6j2vbnx36dvk7hxq1mxv8n0qxci1f-amdgpu-pro-16.60-379184.tar.xz’
 85 47.9M   85 40.8M    0     0  2879k      0  0:00:17  0:00:14  0:00:03 4727k
trying https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-16.60-379184.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 47.9M  100 47.9M    0     0  3004k      0  0:00:16  0:00:16 --:--:-- 4903k

fetching path ‘/nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev’...
  6  115M    6 7206k    0     0  4018k      0  0:00:29  0:00:01  0:00:28 4073k
*** Downloading ‘https://cache.nixos.org/nar/1crw3610bf0jcrqxn15aqqfp3pxp0y7hng8xirwn6cjjcak9ys77.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.3M  100 12.3M    0     0  2190k      0  0:00:05  0:00:05 --:--:-- 2535k

100  115M  100  115M    0     0  6279k      0  0:00:18  0:00:18 --:--:-- 7269k
building path(s) ‘/nix/store/pca8ak053rzpb6rfzyncwrvim77msj53-amdgpu-pro-16.60-4.10.1’
unpacking sources
unpacking source archive /nix/store/kvd6j2vbnx36dvk7hxq1mxv8n0qxci1f-amdgpu-pro-16.60-379184.tar.xz
source root is amdgpu-pro-16.60-379184
../amdgpu-pro-dkms_16.60-379184_all.deb
...
/tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root
configuring
no configure script, doing nothing
building
/tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184 /tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root
patching script interpreter paths in pre-build.sh
pre-build.sh: interpreter directive changed from "/bin/bash" to "/nix/store/010yd8jls8w4vcnql4zhjbnyp2yay5pl-bash-4.4-p5/bin/bash"
/tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root
make flags: SHELL=/nix/store/010yd8jls8w4vcnql4zhjbnyp2yay5pl-bash-4.4-p5/bin/bash -C /nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev/lib/modules/4.10.1/build modules M=/tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184   
make: Entering directory '/nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev/lib/modules/4.10.1/build'
  CC [M]  /tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184/amd/amdgpu/amdgpu_drv.o
In file included from /tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184/amd/amdgpu/../backport/include/kcl/kcl_amdgpu.h:5:0,
                 from /tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184/amd/amdgpu/../backport/backport.h:5,
                 from <command-line>:0:
/tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184/amd/amdgpu/amdgpu.h:37:25: fatal error: linux/fence.h: No such file or directory
compilation terminated.
make[4]: *** [/nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev/lib/modules/4.10.1/source/scripts/Makefile.build:295: /tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184/amd/amdgpu/amdgpu_drv.o] Error 1
make[3]: *** [/nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev/lib/modules/4.10.1/source/scripts/Makefile.build:553: /tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184/amd/amdgpu] Error 2
make[2]: *** [/nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev/lib/modules/4.10.1/source/Makefile:1490: _module_/tmp/nix-build-amdgpu-pro-16.60-4.10.1.drv-0/amdgpu-pro-16.60-379184/root/usr/src/amdgpu-pro-16.60-379184] Error 2
make[1]: *** [Makefile:150: sub-make] Error 2
make: *** [Makefile:24: __sub-make] Error 2
make: Leaving directory '/nix/store/h2kvglvlj17ih6spjw7ay9l3m9l8nkgp-linux-4.10.1-dev/lib/modules/4.10.1/build'
builder for ‘/nix/store/c0kjivx1m7zq1kshis90kwkc3nvd7xks-amdgpu-pro-16.60-4.10.1.drv’ failed with exit code 2
error: build of ‘/nix/store/c0kjivx1m7zq1kshis90kwkc3nvd7xks-amdgpu-pro-16.60-4.10.1.drv’ failed
```
Any idea on how to fix this?

**Comment by corngood** [comment]
Looks like it's going to need updating to compile against Linux 4.10.  For now you should use 4.9.  Is it still the default?

I did manage to get it to compile with 4.10-rc7 at one point, but I had stability problems and didn't have time to investigate them.

**Comment by ninegua** [comment]
@corngood What is the best practice to pin my nixos (or nixpkgs) channel to a particular version, such as kernel 4.9?

**Comment by corngood** [comment]
@ninegua It looks like 4.9 is still the default in master.  Do you have anything in your config that would override that, such as `boot.kernelPackages = pkgs.linuxPackages_latest`?

If so, just remove it.  If not, maybe post your config?

We could add something to the amdgpu-pro module to set 4.9 as the default kernel, but that wouldn't help if it's overridden.  We could also add an assert for > 4.9 until we get it fixed.  Then you'd at least get a more helpful error.

**Comment by ninegua** [comment]
Ah yes, I had that line in my `configuration.nix`. After commenting it out, it is building with kernel 4.9 with success. Thank you @corngood

**Comment by vcunat** [comment]
Our policy is to use the latest longterm kernel as the default; I think 4.9 branch will stay so for months.
