### PR TITLE
deluge: fix generic launcher without setuptools

### PR DESCRIPTION
**Pull request by dniku**
Upstream change: https://github.com/deluge-torrent/deluge/pull/501

Deluge’s generic `deluge` launcher uses `pkg_resources` to discover UI entry points. Although `standard-pkg-resources` provides the `pkg_resources` module, resolving those entry points also checks Deluge’s package metadata and fails because the `setuptools` distribution is unavailable at runtime.

Backport the upstream change to use `importlib.metadata` for UI entry-point discovery. Keep `standard-pkg-resources` because Deluge’s plugin manager still uses `pkg_resources`.

The failure can be reproduced on the unmodified base revision:

```console
$ nix shell 'github:NixOS/nixpkgs/19a567c178bebc336d60d8da5dedea44bbe4f730#deluge-gtk' \
    --command deluge --version
...
pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by the application
```

With this change, the generic launcher works:

```console
$ nix shell .#deluge-gtk --command deluge --version
.deluge-wrapped 2.2.0
...
```

Assisted by OpenAI Codex (gpt-5.6-sol-xhigh).

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [x] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [x] Follows the [automation/AI policy].

Both affected packages build, and all five launchers handle `--version` successfully:

```console
$ nix build .#deluged .#deluge-gtk
$ nix run .#deluged -- --version
$ nix run .#deluge-gtk -- --version
$ nix shell .#deluge-gtk --command deluge --version
$ nix shell .#deluge-gtk --command deluge-web --version
$ nix shell .#deluge-gtk --command deluge-console --version
```

`nixpkgs-review` successfully built both affected packages:

```console
$ nixpkgs-review rev HEAD \
    --branch 19a567c178bebc336d60d8da5dedea44bbe4f730 \
    --package deluged \
    --package deluge-gtk \
    --no-shell
--------- Report for 'x86_64-linux' ---------
2 packages built:
deluge-gtk deluged
```

The existing integration test was also attempted:

```console
$ nix build .#deluged.tests.deluge
```

It fails independently during daemon startup because PyOpenSSL 26 removed `OpenSSL.crypto.X509Req`:

```console
Unable to start deluged: module 'OpenSSL.crypto' has no attribute 'X509Req'
```

That failure is addressed separately by https://github.com/NixOS/nixpkgs/pull/548035. The NixOS and package-test checkboxes are therefore left unchecked here.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

**Review by a-peirogon — APPROVED** [review]
LGTM, ui_entry.py fix from deluge-torrent/deluge#501

**Comment by dniku** [comment]
Hmm I just discovered https://github.com/NixOS/nixpkgs/issues/540545. Seems a different workaround is already merged in https://github.com/NixOS/nixpkgs/pull/546761 ?

**Comment by a-peirogon** [comment]
> Hmm I just discovered #540545. Seems a different workaround is already merged in #546761 ?

Right, #546761 fixed the pluginmanagerbase.py issue from #540545. This one's separate: ui_entry.py still checks for the setuptools distribution itself, even with pkg_resources available. Different bug, still needed.

File: pkgs/applications/networking/p2p/deluge/default.nix [hunk 1]
```diff
@@ -30,6 +31,14 @@ let
         hash = "sha256-ubonK1ukKq8caU5sKWKKuBbMGnAKN7rAiqy1JXFgas0=";
       };
 
+      patches = [
+        (fetchpatch {
+          name = "deluge-use-importlib-for-ui-entrypoints.patch";
+          url = "https://github.com/deluge-torrent/deluge/commit/1a031d00094d4613667bcaadae57b548b7e1413b.patch";
+          hash = "sha256-KfACbRs1yVr5PsRrXLp/RD8YT3Ow71bvuPZyKMDRmOA=";
+        })
+      ];
```
Comment (Sigmanificient) [inline pkgs/applications/networking/p2p/deluge/default.nix:40]: This commit comes from a pull request, please vendor the patch and add a comment on top of the patch path!

**Review by Sigmanificient — CHANGES_REQUESTED** [review]

**Comment by googleson78** [comment]
I tried to use this branch but I'm still getting 
```
pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by the application
```

Am I doing something wrong here?

File: pkgs/applications/networking/p2p/deluge/default.nix (hunk 1 above)
Comment (dniku) [reply pkgs/applications/networking/p2p/deluge/default.nix:36]: Done.

**Comment by dniku** [comment]
@googleson78 could you clarify how exactly you can reproduce the error?
