### ISSUE TITLE
"stack --nix" can't link postgresql-simple in recent versions of Nixpkgs

### ISSUE THREAD

**Issue by rvl** [NixOS/nixpkgs#17575]
## Issue description

Since updating to a later version of nixos-unstable channel, I'm getting the following error when building a Haskell project with `stack --nix`.

```
nixtest-0.1.0.0: build
Preprocessing executable 'nixtest' for nixtest-0.1.0.0...
[1 of 1] Compiling Main             ( Main.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.24.0.0/build/nixtest/nixtest-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux-nix/Cabal-1.24.0.0/build/nixtest/nixtest ...
/nix/store/6c5ybxas7kfkkzc6yfkad1szs58agbgl-postgresql-9.5.3/lib/libpq.a(fe-secure-openssl.o): In function `SSLerrmessage':
(.text+0x38): undefined reference to `ERR_reason_error_string'
<snip>
/nix/store/6c5ybxas7kfkkzc6yfkad1szs58agbgl-postgresql-9.5.3/lib/libpq.a(fe-secure-openssl.o): In function `PQsslAttribute':
(.text+0x1d44): undefined reference to `SSL_CIPHER_get_name'
collect2: error: ld returned 1 exit status
`cc' failed in phase `Linker'. (Exit code: 1)

--  While building package nixtest-0.1.0.0 using:
      /home/rodney/config/.stack/setup-exe-cache/x86_64-linux-nix/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.24.0.0 build exe:nixtest --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

A git bisect found that it would not build after commit 2814494 (binutils: 2.26 -> 2.26.1).

### Steps to reproduce

1. Setup a stack/nix project which uses postgresql-simple using the files below.
2. Run `stack build`
3. Try changing `pkgsBad` to `pkgsGood` and build again.

#### `Main.hs`
```
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Database.PostgreSQL.Simple
import Control.Monad

main :: IO ()
main = void $ connectPostgreSQL "dbname='postgres'"
```

#### `nixtest.cabal`
```
name:                nixtest
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/rvl/nixtest#readme
license:             BSD3
license-file:        LICENSE
author:              Rodney Lorrimar
maintainer:          dev@rodney.id.au
copyright:           2016 Rodney Lorrimar
category:            Web
build-type:          Simple
cabal-version:       >=1.10

executable nixtest
  main-is:             Main.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5, postgresql-simple
```

#### `stack.yaml`
```
resolver: nightly-2016-08-02
packages: ['.']
extra-deps: []
flags: {}
extra-package-dbs: []
nix:
  enable: true
  shell-file: shell.nix
```

#### `shell.nix`
```
let
  basePkgs = import <nixpkgs> {};
  pkgsGood = import (basePkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "2ef1c6bbbbd3d04f59f15384530af0009eb08167";
    sha256 = "0jma25v5yzfcy0d9zckmlvbwhj1r0aa7jyqpgg4nandy3lsbjrlw";
  }) {};
  pkgsBad = import (basePkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "20f009d56df9a0e5f224761ba48aa4142564753e";
    sha256 = "1y9w534aj7dbvgdggaaxs2xxf3hmh7xmyg73n230wrcbyq7yixlg";
  }) {};

in

with pkgsBad;

{ ghc ? haskell.compiler.ghc801 }:

haskell.lib.buildStackProject {
  inherit ghc;
  name = "nixtest";
  buildInputs = [
    zlib
    postgresql
    postgresql.lib
    postgresql.out
    openssl.dev
    openssl.out
  ];
}
```

## Technical details

* System: NixOS: 16.09.git.2ef1c6b (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09.git.2ef1c6b"

**Comment by vcunat** [comment]
The bisect confuses me, but our `openssl` does *not* ship with static libraries. I can't see any changes around that during the last several months, and those missing symbols certainly belong to openssl.

/cc @peti who understands haskell packaging much better.

**Comment by rvl** [comment]
The bisect confused me as well, for the same reason.

The two nixpkgs revisions shown above are nixos-unstable channel releases from hydra. The bisect narrowed it down to good: e7c8c09, 00e8e4c   bad: 2814494.

As to the cause, I can only speculate. Maybe GHC 8.0.1 is incompatible with binutils 2.26.1.

**Comment by vcunat** [comment]
It seems more likely that some `ld` change now makes pgsql require linking against a few openssl symbols.

**Comment by rvl** [comment]
I noticed that the build succeeds when stack is not used, set up according to the instructions in the [Nixpkgs Manual](https://nixos.org/nixpkgs/manual/#how-to-build-a-stand-alone-project).

Here is a gist containing the two configurations: https://gist.github.com/rvl/568cfe42ce13b026b9d2355c6e328e3f

**Comment by peti** [comment]
I'm not sure what is causing this issue and I don't know enough about Stack to debug it, I'm afraid.

**Comment by rvl** [comment]
Thanks for checking. I noticed there have been some recent PRs in this area, so checked out revision 04e4c49 and retested. It works now! :sunflower: I have also been able to drop the library output extensions from `buildInputs`.

**Comment by teh** [comment]
Just for reference, I think the issue is that for libpq we have `librarySystemDepends = [ postgresql ]` but after the output split that should be `librarySystemDepends = [ postgresql.lib ]`.

Maybe we should fix this via `overrideCabal` in `configuration-common.nix` ?

**Comment by domenkozar** [comment]
Also see https://github.com/NixOS/nixpkgs/issues/17722
