### PR TITLE
lirc: 0.10.1 -> 0.10.2

### LINKED ISSUE #200566: lirc: plugin ftdi is missing (pkg-config in depsBuildBuild)
### Describe the bug

In nixos-unstable (2022-11-10) the package lirc do not build the ftdi plugin. This plugin is availabe in nixos-22.05.

### Analysis

This issue was introduced with https://github.com/NixOS/nixpkgs/pull/190212, which moved package `pkg-config` from `nativeBuildInputs` to `depsBuildBuild`.
This move renamed the environment variable form `PKG_CONFIG_PATH` to `PKG_CONFIG_PATH_FOR_BUILD` and therefor the program `pkg-config` fails to find package `libftdi1` during configure phase:

```
checking for libftdi1 >= 1.0... no
```

Side note: Do we have a general problem with `pkg-config` in `depsBuildBuild`?

### Expected behavior

The lirc ftdi plugin is available.

### Solving attempts

Moving `pkg-config` from `depsBuildBuild` back to `nativeBuildInputs`, raises following error:

```
python-pkg/lirc/_client.c:1:10: fatal error: Python.h: No such file or directory
    1 | #include <Python.h>
      |          ^~~~~~~~~~
```

The move does not raise an error with lirc version 0.10.2, which is currently available as PR https://github.com/NixOS/nixpkgs/pull/200558.

### Notify maintainers

@SuperSandro2000 , @pSub

### PR DESCRIPTION
**Pull request by ck3d**
###### Description of changes

update to latest version of LIRC and fix #200566

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ck3d** [comment]
Result of `nixpkgs-review pr 200558` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>audacious</li>
    <li>audacious-plugins</li>
    <li>cadence</li>
    <li>dvdstyler</li>
    <li>fbida</li>
    <li>fgallery</li>
    <li>geeqie</li>
    <li>gjay</li>
    <li>kodi (kodiPackages.kodi)</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiPackages.a4ksubtitles</li>
    <li>kodiPackages.archive_tool</li>
    <li>kodiPackages.iagl</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.invidious</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.kodi-platform</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.netflix</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>lirc (python310Packages.lirc)</li>
    <li>paprefs</li>
    <li>pulseaudioFull</li>
    <li>python39Packages.lirc</li>
    <li>rhythmbox</li>
    <li>rosegarden</li>
    <li>xine-ui</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
is #200566 a blocker for this?

**Comment by ck3d** [comment]
I can prepare a fix for #200566 based on this PR, which will move `pkg-config` from `depsBuildBuild` to `nativeBuildInputs`.

**Comment by SuperSandro2000** [comment]
That would be great

**Comment by ck3d** [comment]
Added commit to fix #200566

**Review by pSub — APPROVED** [review]
