### ISSUE TITLE
rtl8821cu does not build on nixos-22.11

### ISSUE THREAD

**Issue by mabl** [NixOS/nixpkgs#225404]
## Issue description

`rtl8821cu` does not build on nixos-22.11 using `linuxPackages_latest`.

```
/build/source/os_dep/osdep_service.c: In function 'rtw_random32':
/build/source/os_dep/osdep_service.c:2918:16: error: implicit declaration of function 'prandom_u32'; did you mean 'get_random_u32'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]
 2918 |         return prandom_u32();
      |                ^~~~~~~~~~~
      |                get_random_u32
/build/source/os_dep/linux/os_intfs.c: In function 'rtw_os_ndev_register':
/build/source/os_dep/linux/os_intfs.c:2151:9: error: too many arguments to function 'netif_napi_add'
 2151 |         netif_napi_add(ndev, &adapter->napi, rtw_recv_napi_poll, RTL_NAPI_WEIGHT);
      |         ^~~~~~~~~~~~~~
In file included from /build/source/include/osdep_service_linux.h:31,
                 from /build/source/include/osdep_service.h:54,
                 from /build/source/include/drv_types.h:27,
                 from /build/source/os_dep/linux/os_intfs.c:17:
/nix/store/knb2aims9l1jp7n9l75fjb54sd0h0ckf-linux-6.2.10-dev/lib/modules/6.2.10/source/include/linux/netdevice.h:2588:1: note: declared here
 2588 | netif_napi_add(struct net_device *dev, struct napi_struct *napi,
      | ^~~~~~~~~~~~~~
make[2]: *** [/nix/store/knb2aims9l1jp7n9l75fjb54sd0h0ckf-linux-6.2.10-dev/lib/modules/6.2.10/source/scripts/Makefile.build:252: /build/source/os_dep/linux/os_intfs.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[2]: *** [/nix/store/knb2aims9l1jp7n9l75fjb54sd0h0ckf-linux-6.2.10-dev/lib/modules/6.2.10/source/scripts/Makefile.build:252: /build/source/os_dep/osdep_service.o] Error 1
make[1]: *** [/nix/store/knb2aims9l1jp7n9l75fjb54sd0h0ckf-linux-6.2.10-dev/lib/modules/6.2.10/source/Makefile:2021: /build/source] Error 2
make[1]: Leaving directory '/nix/store/knb2aims9l1jp7n9l75fjb54sd0h0ckf-linux-6.2.10-dev/lib/modules/6.2.10/build'
make: *** [Makefile:2498: modules] Error 2
error: builder for '/nix/store/ifciy7nzm2g04s3mnpvmp7hvqf5v5fam-rtl8821cu-6.2.10-unstable-2022-05-07.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/pn0yc47bslwil1b0yw8myp49cy18x0xs-kernel-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yjr2cik6x6n65j04ngqfq91wqycs0i0r-linux-6.2.10-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fld14988sd0pry76riwzpcgl34f569j7-nixos-system-xxx-22.11.3567.0040164e473.drv' failed to build
```

### Steps to reproduce

```
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.extraModulePackages = [ config.boot.kernelPackages.rtl8821cu ];
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9, NixOS, 22.11 (Raccoon), 22.11.3567.0040164e473`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by surfaceflinger** [comment]
While it doesn't build, have you checked if your adapter works without this module? (Especially if you began using your OS installation before 6.2 release). Support for USB devices in rtw88 was merged into Linux 6.2.

However I'm not sure if rtw88 supports EJECTing these weird adapters which act as a USB drive with a driver installer so try doing this too: https://github.com/surfaceflinger/nixos-config/blob/master/nixos/hosts/blahaj/default.nix#L52

(ofc make sure vendor/product id match whatever you have in lsusb :))

**Comment by mabl** [comment]
Hi [surfaceflinger](https://github.com/surfaceflinger),

yes, the default Linux kernel worked somewhat but is unstable and reported some failure to load eeprom data. As a result, I think that the regulatory locations are not properly set and some wireless channels were not detected.

I solved the issue by building against an older `linuxPackage` instead of `linuxPackages_latest`, which is fine for my current application. So feel free to close this issue if you feel that this is best.

**Comment by datsfilipe** [comment]
It still doesn't build in NixOS 24.05.

**Comment by datsfilipe** [comment]
It (`rtl8821cu`) still doesn't build on latest kernel versions, Idk why. I'm using `linuxPackages_6_6` in order to use it.

`rtw88_8821cu` on latest kernel version seems too unstable. Got to see a lot of errors using `jornalctl -fe`, e.g.: `rtw88 timed out to flush queue 2` or something like that. The connection goes on and off too frequently to be able to use. I couldn't find a fix for my case at least.

**Comment by surfaceflinger** [comment]
22.11 is ofc not supported anymore.

It should now build against 6.12 and older kernels across all supported NixOS channels
