### PR TITLE
whois: fix build with Clang

### LINKED ISSUE #260552: Build failure: whois (on Darwin)
### Steps To Reproduce

1. build `whois` on darwin on nixos-unstable

### Build log

See https://hydra.nixos.org/build/237625043/nixlog/1

Relevant bit:

```
./utils.h:62:7: error: 'malloc' attribute takes no arguments
void *MALLOC_FREE NONNULL do_nofail(void *ptr, const char *file, const int line)
      ^
./utils.h:20:37: note: expanded from macro 'MALLOC_FREE'
# define MALLOC_FREE __attribute__((malloc(free)))
```

### Additional context

Failing due to https://github.com/NixOS/nixpkgs/pull/259969

Appears to be due to [this upstream change](https://github.com/rfc1036/whois/compare/v5.5.18...v5.5.19#diff-a00a459441a1c86324aacc5bdbb53461d439d2af337849915891aa3dc281936e). Though it’s not clear to me why it appears that `__GNUC__` is defined when using clang.

### Notify maintainers

@fpletz 

### Metadata

Hydra, can replicate locally.

### PR DESCRIPTION
**Pull request by marsam**
## Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/260552
cc: @amarshall 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/tools/networking/whois/clang.patch [hunk 1]
```diff
@@ -0,0 +1,11 @@
+--- a/utils.h
++++ b/utils.h
+@@ -15,7 +15,7 @@
+ #endif
+ 
+ /* Portability macros */
+-#ifdef __GNUC__
++#if defined __GNUC__ && ! defined __clang__
```
Comment (kirillrdy) [inline pkgs/tools/networking/whois/clang.patch:8]: since it's one liner, is it possible to convert to `substituteInplace` ?

**Review by amarshall — APPROVED** [review]
Thanks! Successfully tested build and basic functionality on x86_64-darwin.

But why is it that clang is also `__GNUC__`? Is it some sort of awful compatibility thing like how everything is `User-Agent: Mozilla`?
