### ISSUE TITLE
nixpkgs#cemu fails building

### ISSUE THREAD

**Issue by cid-chan** [NixOS/nixpkgs#188193]
### Describe the bug
See title

### Steps To Reproduce
```nix
{
  inputs.nixpkgs.url = "github:nixpkgs/nixos/b9fd420fa535fd254c6f1f26df770b32a9dc98b4";

  outputs =
    { self, nixpkgs }:
    {
      packages.x86_64-linux.default = nixpkgs.legacyPackages.x86_64-linux.cemu;
    };
}
```

Fails compilation on x86_64-linux with
```
CEmu> /nix/store/zgvxnf9047rdd8g8kq2zxxm9k6kfqf8b-binutils-2.38/bin/ld: /nix/store/rqfa4jigjlb3s59g9i5554sjqdr53w8z-qtbase-5.15.3/lib/libQt5Core.so: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
CEmu> /nix/store/zgvxnf9047rdd8g8kq2zxxm9k6kfqf8b-binutils-2.38/bin/ld: /nix/store/rqfa4jigjlb3s59g9i5554sjqdr53w8z-qtbase-5.15.3/lib/libQt5Widgets.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
CEmu> /nix/store/zgvxnf9047rdd8g8kq2zxxm9k6kfqf8b-binutils-2.38/bin/ld: /nix/store/rqfa4jigjlb3s59g9i5554sjqdr53w8z-qtbase-5.15.3/lib/libQt5Core.so: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
CEmu> collect2: error: ld returned 1 exit status
CEmu> make: *** [Makefile:507: CEmu] Error 
```

### Expected behavior
It should build. Or it should be marked as broken.

### Notify maintainers
@luc65r 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.16, NixOS, 22.11 (Raccoon), 22.11.20220816.762b003`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/run/current-system/sw/nixpkgs`
```

**Comment by delroth** [comment]
Would it make sense to use the opportunity and rename it to `cemu-ti` along the way (to deconflict with https://github.com/cemu-project/Cemu which could be `cemu-wiiu`)? It seems to me that nobody is currently relying on this to work for their nix configurations since it stopped properly building 4 months ago (I don't even think it builds in 22.05?).
