### ISSUE TITLE
iosevka-comfy no longer builds after upgrade to 0.3.1

### ISSUE THREAD

**Issue by vlaci** [NixOS/nixpkgs#185633]
### Steps To Reproduce
1. check out latest nixos-unstable (f44884060cb94240efbe55620f38a8ec8d9af601)
2. build *iosevka-comfy.comfy* using `nix build .#iosevka-comfy.comfy` or `nix-build . -A iosevka-comfy.comfy`

### Build log
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/8k7893693wqpnfi8s0c9bv8mh2kjicxz-iosevka-15.5.2.tar.gz
source root is Iosevka-15.5.2
setting SOURCE_DATE_EPOCH to timestamp 1656159437 of file Iosevka-15.5.2/verdafile.js
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building

Error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/build/Iosevka-15.5.2/font-src/index' imported from /nix/store/b90gfjqlcsrm566fj601im22gbd8685j-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js
Did you mean to import /build/Iosevka-15.5.2/font-src/index.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at process.<anonymous> (/nix/store/b90gfjqlcsrm566fj601im22gbd8685j-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js:17:52) {
  code: 'ERR_MODULE_NOT_FOUND'
}
    at ChildProcess.<anonymous> (/nix/store/b90gfjqlcsrm566fj601im22gbd8685j-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:400:28)
    at emit (internal/child_process.js:935:14)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

### Additional context
It was working up until #181633 got merged

### Notify maintainers
@nagy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.58, NixOS, 22.11 (Raccoon), 22.11.20220804.10db1c5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `""`
 - channels(vlaci): `""`
 - nixpkgs: `/nix/store/gkwgfc8mhn9p5n529dy1pgvzcvxf1qbl-source`
```

**Comment by nagy** [comment]
I am aware of the issue, but it was not caused by my PR, because it is building with the merge commit of the PR:

```sh
$ nix-build https://github.com/NixOS/nixpkgs/archive/0d440c18119406feb8a32cd5ec2ff0b83fc9104b.tar.gz -A iosevka-comfy.comfy
/nix/store/zilmqq5132fv26lib5c26gljc12q1n6q-iosevka-comfy-0.3.1
```

The problem was introduced with commit https://github.com/NixOS/nixpkgs/pull/185101/commits/d763334cb3744e02db3dfe92af8a802b7de6bf27 from PR https://github.com/NixOS/nixpkgs/pull/185101 , which is an unrelated node-packages update. If I revert that commit, it builds again.

You can also see this in Hydra https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.iosevka-comfy.comfy.x86_64-linux as there is on working build with version "0.3.1" and then it broke.

**Comment by nagy** [comment]
For anybody who wants to have a quick workaround for this, wherever you use `iosevka-comfy` place a "let" block before that like so:

```nix
let
  # until https://github.com/NixOS/nixpkgs/issues/185633 is fixed
  iosevka-comfy = (import (pkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "0d440c18119406feb8a32cd5ec2ff0b83fc9104b";
    sha256 = "sha256-Fw6zRNBonu9wwVSQ0Cj9zHliw6yChMQPf3GPQFJZ4us=";
  }) { }).iosevka-comfy;
in
# ...
```

**Comment by vlaci** [comment]
Thank you and sorry for the accusation!

**Comment by DamienCassou** [comment]
CCing @TredwellGit @SuperSandro2000 @winterqt as they worked on https://github.com/NixOS/nixpkgs/pull/185101.

**Comment by montchr** [comment]
FWIW, this also affects any other Iosevka custom build made via `iosevka.override` -- `iosevka-comfy` is just one such popular custom build. So I believe this would affect anyone else with their own builds, not only users of `iosevka-comfy`.

**Comment by pinpox** [comment]
> FWIW, this also affects any other Iosevka custom build made via `iosevka.override` (I ran into it in my own builds too) -- `iosevka-comfy` is just one such popular custom build. So I believe this would affect anyone else with their own builds, not only users of `iosevka-comfy`.

I can confirm this.  More info here https://github.com/NixOS/nixpkgs/pull/185824#issuecomment-1210287028

**Comment by nagy** [comment]
With the recent merge of https://github.com/NixOS/nixpkgs/pull/185824 this now builds for me on master.
