### ISSUE TITLE
pythonPackages.systemd is broken

### ISSUE THREAD

**Issue by mbrgm** [NixOS/nixpkgs#26402]
## Issue description

Building `pythonPackages.systemd` fails with multiple errors of this kind. I traced the error down to a specific commit using `git bisect`.

```
In file included from /nix/store/4l1q9zgym35y70nkk7jw6hvlq9x8a4hb-systemd-233-dev/include/systemd/sd-messages.h:23:0,
                 from systemd/id128.c:23:
systemd/id128-constants.h:84:46: error: incompatible type for argument 3 of 'add_id'
 add_id(m, "SD_MESSAGE_DNSSEC_DOWNGRADE_STR", SD_MESSAGE_DNSSEC_DOWNGRADE_STR) JOINER
                                              ^
systemd/id128.c:101:12: note: expected 'sd_id128_t {aka union sd_id128}' but argument is of type 'char *'
 static int add_id(PyObject *module, const char* name, sd_id128_t id) {
            ^
error: command 'gcc' failed with exit status 1
```

### Steps to reproduce

- checkout dfebb66f657240e5448a98d9efc90d4c66825274
- `nix-build -A pythonPackages.systemd`

## Technical details

* System: Arch Linux, Kernel 4.11.2-1-ARCH
* Nix version: 1.11.9
* Nixpkgs version: 17.09pre-git
* Sandboxing enabled: yes

CC @Mic92

**Comment by Mic92** [comment]
the package needs an upgrade and python2 is deprecated.

**Comment by Mic92** [comment]
was already in master: https://github.com/NixOS/nixpkgs/pull/26386

**Comment by mbrgm** [comment]
Ah sorry didn't see that.
