### ISSUE TITLE
Build failure: hyprmagnifier

### ISSUE THREAD

**Issue by MithicSpirit** [NixOS/nixpkgs#544208]
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

1. Be on latest master (after #543773 merge)
2. `nix-build -A hyprmagnifier`

### Can Hydra reproduce this build failure?

Hydra is currently rebuilding this package.

### Relevant log output

```console
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/16fk62lj489kgvzaaqynzbbg118r2j7d-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/share/doc/hyprmagnifier -DCMAKE_INSTALL_INFODIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/share/man -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/include -DCMAKE_INSTALL_SBINDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16/lib -DCMAKE_STRIP=/nix/store/adcz0m6qq2flmshdf0zz2xwjr5zbq1gr-gcc-wrapper-15.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/adcz0m6qq2flmshdf0zz2xwjr5zbq1gr-gcc-wrapper-15.3.0/bin/ranlib -DCMAKE_AR=/nix/store/adcz0m6qq2flmshdf0zz2xwjr5zbq1gr-gcc-wrapper-15.3.0/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/803hk9h905g8zyjmlgnbsii2dlgrnawd-hyprmagnifier-0.0.1-unstable-2025-05-16
-- The C compiler identification is GNU 15.3.0
-- The CXX compiler identification is GNU 15.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/adcz0m6qq2flmshdf0zz2xwjr5zbq1gr-gcc-wrapper-15.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/adcz0m6qq2flmshdf0zz2xwjr5zbq1gr-gcc-wrapper-15.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring hyprmagnifier!
bash: line 1: git: command not found
bash: line 1: git: command not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found PkgConfig: /nix/store/swljvs2gz4mcb1avyjzb0cc2qrbslmbb-pkg-config-wrapper-0.29.2/bin/pkg-config (found version "0.29.2")
-- Checking for modules 'wayland-client;wayland-protocols;xkbcommon;cairo;pango;pangocairo;libjpeg;hyprutils>=0.2.0;hyprwayland-scanner>=0.4.0'
--   Found wayland-client, version 1.26.0
--   Found wayland-protocols, version 1.49
--   Found xkbcommon, version 1.13.2
--   Found cairo, version 1.18.4
--   Found pango, version 1.57.1
--   Found pangocairo, version 1.57.1
--   Found libjpeg, version 3.1.4.1
--   Found hyprutils, version 0.14.0
--   Found hyprwayland-scanner, version 0.4.6
Package xdmcp was not found in the pkg-config search path.
Perhaps you should add the directory containing `xdmcp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xdmcp', required by 'xcb', not found
Package xdmcp was not found in the pkg-config search path.
Perhaps you should add the directory containing `xdmcp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xdmcp', required by 'xcb', not found
Package xdmcp was not found in the pkg-config search path.
Perhaps you should add the directory containing `xdmcp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xdmcp', required by 'xcb', not found
Package xdmcp was not found in the pkg-config search path.
Perhaps you should add the directory containing `xdmcp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xdmcp', required by 'xcb', not found
-- Found wayland-protocols at //nix/store/ibb371psgjd6bccrqvfrjv49bpvm6jdm-wayland-protocols-1.49/share/wayland-protocols
-- Found wayland-scanner at //nix/store/1gqf6ahx7qbzaparrkz0q6dzdfw7bkli-wayland-scanner-1.26.0/share/wayland
-- Configuring done (1.4s)
-- Generating done (0.0s)
[33mCMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_DOCDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_INFODIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_LOCALEDIR
    CMAKE_INSTALL_MANDIR
    CMAKE_INSTALL_SBINDIR

[0m
-- Build files have been written to: /build/source/build
cmake: enabled parallel building
cmake: enabled parallel installing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: -j8 SHELL=/nix/store/c9mv5v53f7vy3wd00ah0f77k509mzmn7-bash-5.3p15/bin/bash
[ 20%] [1m[34mGenerating /build/source/protocols/cursor-shape-v1.cpp, /build/source/protocols/cursor-shape-v1.hpp[0m
[ 28%] [1m[34mGenerating /build/source/protocols/tablet-v2.cpp, /build/source/protocols/tablet-v2.hpp[0m
[ 20%] [1m[34mGenerating /build/source/protocols/fractional-scale-v1.cpp, /build/source/protocols/fractional-scale-v1.hpp[0m
[ 20%] [1m[34mGenerating /build/source/protocols/viewporter.cpp, /build/source/protocols/viewporter.hpp[0m
[ 28%] [1m[34mGenerating /build/source/protocols/linux-dmabuf-v1.cpp, /build/source/protocols/linux-dmabuf-v1.hpp[0m
[ 32%] [1m[34mGenerating /build/source/protocols/wlr-layer-shell-unstable-v1.cpp, /build/source/protocols/wlr-layer-shell-unstable-v1.hpp[0m
[ 32%] [1m[34mGenerating /build/source/protocols/wayland.cpp, /build/source/protocols/wayland.hpp[0m
[ 32%] [1m[34mGenerating /build/source/protocols/xdg-shell.cpp, /build/source/protocols/xdg-shell.hpp[0m
[ 36%] [1m[34mGenerating /build/source/protocols/wlr-screencopy-unstable-v1.cpp, /build/source/protocols/wlr-screencopy-unstable-v1.hpp[0m
[ 48%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/src/hyprmagnifier.cpp.o[0m
[ 48%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/wlr-layer-shell-unstable-v1.cpp.o[0m
[ 48%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/src/debug/Log.cpp.o[0m
[ 56%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/src/helpers/PoolBuffer.cpp.o[0m
[ 56%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/src/helpers/Monitor.cpp.o[0m
[ 64%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/wayland.cpp.o[0m
[ 64%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/src/helpers/LayerSurface.cpp.o[0m
[ 68%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/src/main.cpp.o[0m
[ 72%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/wlr-screencopy-unstable-v1.cpp.o[0m
[ 76%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/linux-dmabuf-v1.cpp.o[0m
[ 80%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/fractional-scale-v1.cpp.o[0m
[ 84%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/viewporter.cpp.o[0m
[ 88%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/xdg-shell.cpp.o[0m
[ 92%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/cursor-shape-v1.cpp.o[0m
[ 96%] [32mBuilding CXX object CMakeFiles/hyprmagnifier.dir/protocols/tablet-v2.cpp.o[0m
[100%] [1m[32mLinking CXX executable hyprmagnifier[0m
/nix/store/b01rwyg0ii5v8r50yrikcs5af64x0v0q-binutils-2.46/bin/ld.bfd: /nix/store/ksxbisg367mxj09qlaz2dps4zh22qnzn-hyprutils-0.14.0/lib/libhyprutils.so: undefined reference to `std::__cow_string::__cow_string(char const*)@GLIBCXX_3.4.35'
/nix/store/b01rwyg0ii5v8r50yrikcs5af64x0v0q-binutils-2.46/bin/ld.bfd: /nix/store/ksxbisg367mxj09qlaz2dps4zh22qnzn-hyprutils-0.14.0/lib/libhyprutils.so: undefined reference to `std::__cow_string::~__cow_string()@GLIBCXX_3.4.35'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/hyprmagnifier.dir/build.make:399: hyprmagnifier] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/hyprmagnifier.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

### Additional context

Broke in #543773. Can be fixed by updating it to `gcc16Stdenv` and adding the patch below. However, the project appears abandoned (no commits since its inception one year ago) and also fails to build on regular distros (tested on Arch). As such, it may be better to just mark the package as broken until upstream fixes things.
```diff
diff --git a/src/hyprmagnifier.hpp b/src/hyprmagnifier.hpp
index 385130e..eb7edbe 100644
--- a/src/hyprmagnifier.hpp
+++ b/src/hyprmagnifier.hpp
@@ -1,5 +1,7 @@
 #pragma once
 
+#include <mutex>
+
 #include "defines.hpp"
 #include "helpers/LayerSurface.hpp"
 #include "helpers/PoolBuffer.hpp"
```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.38, NixOS, 26.11 (Zokor), 26.11.20260719.241313f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.35.1`
 - nixpkgs: `/nix/store/7j1q60m17gf95k3s0gk2qvjqygnp1q36-source`

### Notify maintainers

@MatthewCroughan

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MatthewCroughan** [comment]
This program looks like it's not being maintained anymore on github, so it's possible we should just be removing it from Nixpkgs.

**Comment by MatthewCroughan** [comment]
There is https://github.com/SIMULATAN/hyprmag in case you're looking for an alternative.

**Comment by MatthewCroughan** [comment]
@MithicSpirit I would appreciate if you could make a PR to:
1. Remove hyprmagnifier from Nixpkgs due to lack of maintenance
2. A PR adding hyprmag as a package

I will review and merge both, otherwise I'll eventually do this myself but I'm low on time ATM.

**Comment by samiser** [comment]
@MatthewCroughan I created the PR (#544497)

@MithicSpirit feel free to add yourself as maintainer also if you'd like :)
