### PR TITLE
mplayer: unstable-2022-02-03 -> 1.5

### PR DESCRIPTION
**Pull request by Conni2461**
## Description of changes

mplayer 1.5 was release on 2022-02-27

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/applications/video/mplayer/default.nix [hunk 1]
```diff
@@ -70,12 +70,11 @@ in
...
   pname = "mplayer";
-  version = "unstable-2022-02-03";
+  version = "1.5";
 
-  src = fetchsvn {
-    url = "svn://svn.mplayerhq.hu/mplayer/trunk";
-    rev = "38331";
-    sha256 = "1vpic8i6zvg0zsy50vhm45ysqag561bpn9jycfbvvwl9ji7l55zi";
+  src = fetchurl {
+    url = "http://www.mplayerhq.hu/MPlayer/releases/MPlayer-${version}.tar.xz";
```
Comment (kirillrdy) [inline pkgs/applications/video/mplayer/default.nix:76]:
```suggestion
    url = "https://mplayerhq.hu/MPlayer/releases/MPlayer-${version}.tar.xz";
```

just mimicking url from their homepage

File: pkgs/applications/video/mplayer/default.nix [hunk 2]
```diff
@@ -1,4 +1,4 @@
-{ config, lib, stdenv, fetchurl, fetchsvn, pkg-config, freetype, yasm, ffmpeg_4
+{ config, lib, stdenv, fetchurl, pkg-config, freetype, yasm, ffmpeg_4
```
Comment (kirillrdy) [inline pkgs/applications/video/mplayer/default.nix:1]: according to http://www.mplayerhq.hu/design7/news.html

compatible with ffmpeg 5

Comment (Conni2461) [reply pkgs/applications/video/mplayer/default.nix:1]: we would need to introduce a patch to fix this. it should compile with 5.0 but it doesnt with 5.1.4 because of the following error

```
av_helpers.c: In function 'mp_msp_av_log_callback':
av_helpers.c:54:32: error: 'const struct AVCodec' has no member named 'decode'
   54 |                     if(s->codec->decode)
      |                                ^~
av_helpers.c:57:32: error: 'const struct AVCodec' has no member named 'decode'
   57 |                     if(s->codec->decode)
```

it seems like this decode function was removed (or moved, not sure yet) here: https://github.com/FFmpeg/FFmpeg/commit/20f972701806be20a77f808db332d9489343bb78#diff-e2ffbd866f8196aea62dcc198390f6f5778c4fd3d0e53e5ca35d57fee2305d94L315-L328

i'll check if there is a patch available to fix this issue

Comment (Conni2461) [reply pkgs/applications/video/mplayer/default.nix:1]: i am fine with doing it here: compile error was fixed here svn://svn.mplayerhq.hu/mplayer/trunk@38361 i tried it and it seems to work

**Comment by kirillrdy** [comment]
Apologies this got forgotten,  if you are still interested we can try finish this.

**Comment by kirillrdy** [comment]
Ah I see mplayer has been updated to 1.5 already
