### PR TITLE
superTuxKart: Fix aarch64-linux build

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Motivation for this change
ZHF: #122042
Failing Hydra build: https://hydra.nixos.org/build/141595056

The final linking against our system `angelscript` errors out on aarch64-linux. There was already a line in `cmakeFlags` that explicitly disabled the use of system angelscript, but it was explicitly re-enabled with a second line further down.

```
[100%] Linking CXX executable bin/supertuxkart
/nix/store/ppvq7f8cx4q4c7xjhp7ghs7pb5i8j7z9-binutils-2.35.1/bin/ld: /nix/store/2y9qxxkib7dhk9967qwj4ffd1v2snr5r-angelscript-2.35.0/lib/libangelscript.so: undefined reference to `CallSystemFunctionNative(asCContext*, asCScriptFunction*, void*, unsigned int*, void*, unsigned long&, void*)'
collect2: error: ld returned 1 exit status
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/games/super-tux-kart/default.nix [hunk 1]
```diff
@@ -100,15 +104,13 @@ stdenv.mkDerivation rec {
...
-    angelscript
   ];
 
   cmakeFlags = [
     "-DBUILD_RECORDER=OFF" # libopenglrecorder is not in nixpkgs
-    "-DUSE_SYSTEM_ANGELSCRIPT=OFF" # doesn't work with 2.31.2 or 2.32.0
+    "-DUSE_SYSTEM_ANGELSCRIPT=OFF" # doesn't work with our 2.35.0 on aarch64-linux
     "-DCHECK_ASSETS=OFF"
     "-DUSE_SYSTEM_WIIUSE=ON"
-    "-DUSE_SYSTEM_ANGELSCRIPT=ON"
```
Comment (jonringer) [inline pkgs/games/super-tux-kart/default.nix:111]: this is also removing for x86, should we just use a `optionals stdenv.isAarch64` to opt-out of the cmake flags?

Comment (OPNA2608) [reply pkgs/games/super-tux-kart/default.nix:111]: Hope it's better now.

**Comment by OPNA2608** [comment]
Result of `nixpkgs-review pr 122082` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>superTuxKart</li>
  </ul>
</details>

Result of `nixpkgs-review pr 122082` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>superTuxKart</li>
  </ul>
</details>

Haven't verified if the second one actually runs because I don't have a display connected to my RPi, but it builds now.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 122082 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>superTuxKart</li>  </ul></details>
