### ISSUE TITLE
rustPackages.clippy fails to compile: can't find crate fmt_macros

### ISSUE THREAD

**Issue by curiousleo** [NixOS/nixpkgs#77358]
**Describe the bug**

`nix-build . -A rustPackages.clippy` fails on `master` since e82fae1a39a808fd541f556f9ff12ad314c18e44 with this error:

```
   Compiling clippy_lints v0.0.212 (/build/rustc-1.40.0-src/src/tools/clippy/clippy_lints)
error[E0463]: can't find crate for `fmt_macros`
  --> src/tools/clippy/clippy_lints/src/lib.rs:20:1
   |
20 | extern crate fmt_macros;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**To Reproduce**
1. Check out any commit between e82fae1a39a808fd541f556f9ff12ad314c18e44 and `master`
2. `nix-build . -A rustPackages.clippy`
3. Observe the compilation failure pasted above.

**Expected behavior**
`nix-build . -A rustPackages.clippy` should succeed.

**Additional context**
I discovered this build failure in the context of https://github.com/NixOS/nixpkgs/pull/77327.

**Metadata**

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.93, NixOS, 19.09.1778.db3e8325a9b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-19.09.1778.db3e8325a9b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by curiousleo** [comment]
https://github.com/rust-lang/rust-clippy/issues/4651 points to https://github.com/rust-lang/rust/pull/64823 being the root cause of this type of error - it looks like we'll need to pull in the `rustc-dev` component somehow and build clippy against that.

**Comment by curiousleo** [comment]
https://github.com/rust-lang/rust/pull/64823 was reverted in https://github.com/rust-lang/rust/pull/65342 due to https://github.com/rust-lang/rust/issues/65335 ...

**Comment by curiousleo** [comment]
... and then re-applied with some changes: https://github.com/rust-lang/rust/pull/65474.

**Comment by curiousleo** [comment]
... and then in https://github.com/rust-lang/rust/pull/67469, `rustc-dev` (on which `clippy_lints` depends) was removed from the default set of components shipped with Rust nightly.

**Comment by curiousleo** [comment]
On the clippy side, this PR (re-)introduced the `extern crate` declarations that lead to the compilation error (though this is probably just a symptom, not the cause): https://github.com/rust-lang/rust-clippy/pull/3189

**Comment by curiousleo** [comment]
(_Very_ tangentially related: https://guix.gnu.org/blog/2018/bootstrapping-rust/, https://github.com/thepowersgang/mrustc)

**Comment by curiousleo** [comment]
There may be an alternative way of building clippy: together with rustc, via `--tools=clippy` in https://github.com/rust-lang/rust/blob/1.40.0/src/bootstrap/configure.py#L157, which is forwarded to the install script here: https://github.com/rust-lang/rust/blob/1.40.0/src/bootstrap/install.rs#L160

**Comment by Mic92** [comment]
How does upstream build clippy?

**Comment by mati865** [comment]
> How does upstream build clippy?

By enabling [this](https://github.com/rust-lang/rust/blob/2d8d559bbecf6272eb41f8a800e319238aa9d621/config.toml.example#L195) option.

**Comment by curiousleo** [comment]
> How does upstream build clippy?

Good question :) Looking into this, I filed https://github.com/rust-lang/rust-clippy/issues/5037.

clippy is referenced from the rust repository as a submodule.
- https://github.com/rust-lang/rust/blob/1.40.0/.gitmodules#L19-L21
- https://github.com/rust-lang/rust/tree/1.40.0/src/tools

The commit at which clippy is pinned in rust 1.40 is https://github.com/rust-lang/rust-clippy/commit/c8e3cfbdd997839c771ca32c7ac860fe95149a04. Interestingly, that commit actually [failed CI](https://travis-ci.com/rust-lang/rust-clippy/jobs/250265253), though I can't tell why.

**Comment by curiousleo** [comment]
> > How does upstream build clippy?
> 
> By enabling [this option](https://github.com/rust-lang/rust/blob/2d8d559bbecf6272eb41f8a800e319238aa9d621/config.toml.example#L195).

Alternatively, as per my [suggestion above](https://github.com/NixOS/nixpkgs/issues/77358#issuecomment-572511207): setting the [`tools` option](https://github.com/rust-lang/rust/blob/2d8d559bbecf6272eb41f8a800e319238aa9d621/config.toml.example#L199).

**Comment by curiousleo** [comment]
@mati865, do you happen to know the entry point (a script or CI configuration) that is used to _release_ Rust (as opposed to building Rust for testing purposes)?

**Comment by mati865** [comment]
@curiousleo `tools` option is the list of the tools that will be built *if* `extended` option (which I linked above) is enabled.

Clippy is using unstable compiler API and thus is not meant to be built separately (stable and beta compilers will throw an error about unstable features unless unsupported hack is applied). AFAIK Clippy releases are done manually.

**Comment by curiousleo** [comment]
> @curiousleo `tools` option is the list of the tools that will be built if `extended` option (which I linked above) is enabled.

Awesome, I missed that! I don't think the way the comments are phrased make this unambiguous. Okay, I'll see if I can get this to work using `--extended`.

> Clippy is using unstable compiler API and thus is not meant to be built separately (stable and beta compilers will throw an error about unstable features unless unsupported hack is applied). AFAIK Clippy releases are done manually.

Good to know. Thanks!

**Comment by curiousleo** [comment]
I've managed to build `clippy` by adding `--enable-extended` and `--tools=clippy` to the rustc build arguments. That could be one way of getting clippy built.

Currently testing whether https://github.com/NixOS/nixpkgs/pull/77529 simply fixes this issue.

**Comment by curiousleo** [comment]
I can confirm that #77529 allows `nix-build . -A clippy` to go through without an error.

I'll leave this issue open until #77529 is in `master`.

**Comment by curiousleo** [comment]
#77529 will land in `master` as part of #77739: https://github.com/NixOS/nixpkgs/pull/77739/files#diff-fb2bc02945c6ee61a9ea9fd6aeddd789.

**Comment by curiousleo** [comment]
https://github.com/NixOS/nixpkgs/pull/77739 has been merged, and `nix-build . -A clippy` now succeeds on `master`. Closing.
