### ISSUE TITLE
Build failure: Linux Kernel 6.12

### ISSUE THREAD

**Issue by TheNightmanCodeth** [NixOS/nixpkgs#351302]
### Steps To Reproduce

1. Build linux kernel 6.12.0 on aarch64-linux 

### Build log

```
> /nix/store/wj7hxrvf8jqipkdry7x6ii1ds1ry2hd5-binutils-2.43.1/bin/ld: warning: -z relro ignored
> /nix/store/wj7hxrvf8jqipkdry7x6ii1ds1ry2hd5-binutils-2.43.1/bin/ld: Unexpected GOT/PLT entries detected!
> /nix/store/wj7hxrvf8jqipkdry7x6ii1ds1ry2hd5-binutils-2.43.1/bin/ld: Unexpected run-time procedure linkages detected!
> /nix/store/wj7hxrvf8jqipkdry7x6ii1ds1ry2hd5-binutils-2.43.1/bin/ld: drivers/gpu/drm/drm_panic.o: in function `drm_panic_qr_init':
> /build/source/build/../drivers/gpu/drm/drm_panic.c:678:(.init.text+0x9c): undefined reference to `zlib_deflate_workspacesize'
> make[2]: *** [../scripts/Makefile.vmlinux:34: vmlinux] Error 1
> make[1]: *** [/build/source/Makefile:1166: vmlinux] Error 2
> make: *** [../Makefile:224: __sub-make] Error 2
```

### Additional context

I'm not entirely sure what's going on here. I'm running on aarch64-linux using a custom kernel tree so it may well be my config that is the issue. However, after some light digging I noticed that `buildLinux` (somewhere along the way) is enabling DRM_PANIC if kernel version is >= 6.12. That combined with the fact that the same config builds fine on 6.11 and lower leads me to believe this may be a larger issue.

### Metadata

 - system: `"aarch64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11.20241023.2768c7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TheNightmanCodeth** [comment]
@K900 sorry to bother, I saw you on the blame for [this comment](https://github.com/NixOS/nixpkgs/blob/6d320a908ecce9cbf285dcdea64d0744bd1fe75e/pkgs/os-specific/linux/kernel/common-config.nix#L505) and wondered if you might have some insight?

**Comment by K900** [comment]
This is an -rc bug. That's ... kind of expected.

**Comment by TheNightmanCodeth** [comment]
I understand, was just curious if you had seen anything like this or knew what might be causing it. 

In that case, should I close the issue?

**Comment by TheNightmanCodeth** [comment]
@K900 My apologies, you are correct. This [patch](https://lore.kernel.org/all/20241003230734.653717-1-ojeda@kernel.org) is missing from the tree I'm building
