### ISSUE TITLE
pkgsMusl.netbsd.install failing on staging-next

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#195986]
### Steps To Reproduce
1. build `pkgsMusl.netbsd.install` from staging-next

### Build log
```
In file included from /build/cvs-export/usr.sbin/mtree/getid.c:81:
/build/cvs-export/usr.sbin/mtree/extern.h:43:10: fatal error: fts.h: No such file or directory
   43 | #include <fts.h>
      |          ^~~~~~~
compilation terminated.
*** [getid.o] Error code 1
```

CC @alyssais @Ericson2314 

Not sure where it broke, or what is the correct approach here, add self.fts to buildInputs? Should it use fts.h from netbsd fts always or only on musl?

**Comment by r-burns** [comment]
Bisected to dcf7a5ec3dac6a53ce1a27e0806bd93309b9d053

**Comment by alyssais** [comment]
Looks like we should add back the fts input, with a comment saying to
check pkgsMusl.netbsd.install before removing it again?

**Comment by yu-re-ka** [comment]
@alyssais I have implemented that in https://github.com/NixOS/nixpkgs/pull/196260
