### PR TITLE
Staging next

### LINKED ISSUE #137060: Rust crate 'clap' does not compile with the packaged rustc version
### Describe the bug
The rust crate 'clap' does not compile with the outdated rust version (`1.53.0`) in nixpkgs, due to the use of a 'unstable' feature, which has been stabilized in `1.54.0`. A ton of rust packages rely on this crate for argument parsing, and it's currently stopping me from updating `rpg-cli`.

### Steps To Reproduce
1. `nix shell nixpkgs#cargo nixpkgs#gcc`
2. `git clone https://github.com/clap-rs/clap && cd clap`
3. `cargo build`

### Expected behavior
It should compile.

### Screenshots
```
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

### Additional context
https://github.com/rust-lang/rust/issues/78835

### Notify maintainers
Maintainers seem to be: @madjar @cstrahan @globin and @Havvy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13-xanmod1-cacule, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `""`
 - channels(nix): `""`
 - nixpkgs: `/nix/store/lmaa13qwmmam5npnfmkn78pfk9akzxf8-wm91hzc8akq56pcygclif1131sh3l1al-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: rustc
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by vcunat**
Another iteration is here ([docs](https://nixos.org/manual/nixpkgs/stable/#submitting-changes-staging-next-branch)): https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents (soon)

Fixes #137060

### CODE REVIEW

**Comment by vcunat** [comment]
I won't have much time for this in the next few days, but let me open it anyway, so others have opportunity to look into the errors.  The oldest missing merges are two weeks old, which sounds not too short.

**Comment by happysalada** [comment]
There is an inkscape faillure on x86_64-darwin, but the logs are truncated https://hydra.nixos.org/build/150411382/log
There is a qtmultimedia failure, but the logs are truncated as well https://hydra.nixos.org/build/150411176/log
I'm not sure what those are building exactly (if it's inkscape or inkscape with extensions), I'll start with inkscape locally and see what I can find.

**Comment by happysalada** [comment]
Here is another failure for backports-entry-points-selectable
https://hydra.nixos.org/build/150608595/nixlog/1

**Comment by sternenseemann** [comment]
> Here is another failure for backports-entry-points-selectable
> https://hydra.nixos.org/build/150608595/nixlog/1

I'd propose we merge #123573 into staging-next, then. We only need it for a single package, so can easily get rid of it. The `pytest-randomly` update is not too risky as it only has three direct reverse deps at the moment (mlrose, fonttools and httplib2).

**Comment by SuperSandro2000** [comment]
> > Here is another failure for backports-entry-points-selectable
> > [hydra.nixos.org/build/150608595/nixlog/1](https://hydra.nixos.org/build/150608595/nixlog/1)
> 
> I'd propose we merge #123573 into staging-next, then. We only need it for a single package, so can easily get rid of it. The `pytest-randomly` update is not too risky as it only has three direct reverse deps at the moment (mlrose, fonttools and httplib2).

I just decided that we are doing this if the 3 packages build. Not worth spending time on a package we remove in a week anyway.

**Comment by sternenseemann** [comment]
> I just decided that we are doing this if the 3 packages build. Not worth spending time on a package we remove in a week anyway.

I tested them earlier on a merge base of staging and master (x86_64-linux) which seemed fine. I'll rebase the PR to staging-next then.

**Comment by happysalada** [comment]
After an only 9h local build, I found the inkscape error
```
> libtool: link: clang -dynamiclib -Wl,-flat_namespace -Wl,-undefined -Wl,suppress -o .libs/liblqr-1.0.dylib  .libs/lqr_gradient.o .libs/lqr_rwindow.o .libs/lqr_energy.o .libs/lqr_cursor.o .libs/lqr_carver.o .libs/lqr_carver_list.o .libs/lqr_carver_bias.o .libs/lqr_carver_rigmask.o .libs/lqr_vmap.o .libs/lqr_vmap_list.o .libs/lqr_progress.o   -L/nix/store/hklsvd1i69hh7piqjg1677wdd5811zyc-glib-2.68.3/lib -lglib-2.0 -lm  -O2   -install_name  /nix/store/jd865s86wrigljc8dz3bsdpn60vvl9xg-liblqr-1-0.4.2/lib/liblqr-1.0.dylib -compatibility_version 4 -current_version 4.2 -Wl,-single_module
       > ld: file not found: /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon for architecture x86_64
       > clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
       > make[2]: *** [Makefile:357: liblqr-1.la] Error 1
       > make[2]: Leaving directory '/private/tmp/nix-build-liblqr-1-0.4.2.drv-0/source/lqr'
       > make[1]: *** [Makefile:332: all-recursive] Error 1
       > make[1]: Leaving directory '/private/tmp/nix-build-liblqr-1-0.4.2.drv-0/source'
       > make: *** [Makefile:242: all] Error 2
       For full logs, run 'nix log /nix/store/44arhqagymk43czci79lv1l856wb9z26-liblqr-1-0.4.2.drv'.
error: 1 dependencies of derivation '/nix/store/jmkl2c0w2knjfri1d84aaxwg91cbql4m-imagemagick-7.1.0-4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3d213idp2wi06g1gh01jmab4wxdqsngz-inkscape-1.1.drv' failed to build
```
I'm having a look at how to fix that derivation locally.

**Comment by happysalada** [comment]
I created a pull request for the fix
https://github.com/NixOS/nixpkgs/pull/135630
I'm still trying to build the two first failures, it's just taking a while on my machine.
That PR covers the first failure I encountered.

**Comment by happysalada** [comment]
I build qtmultimedia-5.12.10 without a problem after that. So the build fail must have been due to the liblqr-1 failure

**Comment by r-burns** [comment]
Someone with commit permissions, please revert e4ade0952aed4ab76a40a4c9265d6e25e3ea93a2 and note that it broke gstreamer-bad due to the missing pkg-config .pc file. https://github.com/NixOS/nixpkgs/pull/131986#issuecomment-906676370

**Comment by happysalada** [comment]
I've got a PR about a hydra failure if anyone is interested https://github.com/NixOS/nixpkgs/pull/136642

**Comment by r-burns** [comment]
python pandas failure can be fixed by bumping to 1.3.2, needs https://github.com/pandas-dev/pandas/pull/36131 and other bugfixes

**Comment by mweinelt** [comment]
> python pandas failure can be fixed by bumping to 1.3.2, needs [pandas-dev/pandas#36131](https://github.com/pandas-dev/pandas/pull/36131) and other bugfixes

Already in staging with alot of other python bumps.

**Comment by mweinelt** [comment]
> > python pandas failure can be fixed by bumping to 1.3.2, needs [pandas-dev/pandas#36131](https://github.com/pandas-dev/pandas/pull/36131) and other bugfixes
> 
> Already in staging with alot of other python bumps.

And for those who didn't follow the discussion on matrix: Merged a rebased version of python-unstable to fix (among other things) pandas.

**Comment by yu-re-ka** [comment]
matrix-synapse tests are failing: https://termbin.com/k5fs

**Comment by mweinelt** [comment]
The cause is not visible from the tracebacks, ccing @Ma27 @sumnerevans.

**Comment by Ma27** [comment]
No idea either, I guess I'm just going to run a git-bisect.

**Comment by yu-re-ka** [comment]
> No idea either, I guess I'm just going to run a git-bisect.

Are you working on this? Otherwise I would try to fix it.

**Comment by Ma27** [comment]
> Are you working on this? Otherwise I would try to fix it.

I started a `git bisect` attempt yesterday that didn't work out very well since I had to `git bisect skip` *a lot of* revisions due to eval errors or unrelated build failures. Also, updating to 1.42.0rc2 didn't fix the problem either.

If you want to take over that'd be fairly nice since I don't have the time currently to *also* look into this :)

**Comment by yu-re-ka** [comment]
The culprit is a7d01b6c8451db1651796ceb962728436f80d88d

**Comment by mweinelt** [comment]
I explicitly didn't upgrade to 2.0.6, so as to not break canonicaljson. The issue with 2.0.6 was reported here: https://github.com/matrix-org/python-canonicaljson/issues/36. No feedback.

**Comment by yu-re-ka** [comment]
Probably 2.0.6 was just one sample and 2.0.x is all broken

**Comment by mweinelt** [comment]
https://github.com/matrix-org/synapse/blob/v1.41.1/synapse/python_dependencies.py#L52

Then this should be taken to the upstream.

**Comment by yu-re-ka** [comment]
Okay, can we revert frozendict to 1.2 until upstream has fixed the issue? Or does something else need frozendict 2.x?

**Comment by mweinelt** [comment]
> Probably 2.0.6 was just one sample and 2.0.x is all broken

FWIW: Keeping frozendict on 2.0.5 fixed canonicaljson, but it broke matrix-synapse.

**Comment by vcunat** [comment]
- [ ] huge aarch64-darwin regression: https://github.com/NixOS/nixpkgs/pull/123420#issuecomment-918031324

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by vcunat** [comment]
Is anyone aware of another blocker?  https://hydra.nixos.org/eval/1704286?compare=1704246

There's still quite a lot regressions from `python3.pkgs` updates, and quite a fraction of *-darwin builds haven't finished yet (quarter of x86, most of aarch64)... but I think it might be all OK-ish to merge, as this iteration has been quite long already.  _I can fixup that mass issue from my previous comment._

**Comment by SuperSandro2000** [comment]
I will fix all the python3Packages.google-* failures after this is merged to master. Will be probably multiple commits and updates. Same for everything maintained by the openstack team. But nothing that should block this PR any longer.

Please keep in mind that we did a mass python update with hundreds of updates. There will be some regressions and they will probably be fixed in the next days on master or at latest when the next nixos-unstable bump is and peoples config fails to build. The python ecosystem only has a limited amount of people and we simply cannot maintain all packages.
