### PR TITLE
python3Packages.scikit-fmm: fix build on Python 3.12+

### PR DESCRIPTION
**Pull request by ConnorBaker**
## Description of changes

Applies work-in-progress patches from a development branch to fix the build on Python 3.12+ by switching the build system to Meson.

Fixes:

- https://hydra.nixos.org/build/260955687

ZHF: #309482

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 314704` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.fipy</li>
    <li>python311Packages.fipy.dist</li>
    <li>python312Packages.fipy</li>
    <li>python312Packages.fipy.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.scikit-fmm</li>
    <li>python311Packages.scikit-fmm.dist</li>
    <li>python312Packages.scikit-fmm</li>
    <li>python312Packages.scikit-fmm.dist</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 314704` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.fipy</li>
    <li>python311Packages.fipy.dist</li>
    <li>python312Packages.fipy</li>
    <li>python312Packages.fipy.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.scikit-fmm</li>
    <li>python311Packages.scikit-fmm.dist</li>
    <li>python312Packages.scikit-fmm</li>
    <li>python312Packages.scikit-fmm.dist</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 314704` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.fipy</li>
    <li>python311Packages.fipy.dist</li>
    <li>python312Packages.fipy</li>
    <li>python312Packages.fipy.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.scikit-fmm</li>
    <li>python311Packages.scikit-fmm.dist</li>
    <li>python312Packages.scikit-fmm</li>
    <li>python312Packages.scikit-fmm.dist</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.fipy</li>
    <li>python311Packages.fipy.dist</li>
    <li>python312Packages.fipy</li>
    <li>python312Packages.fipy.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.scikit-fmm</li>
    <li>python311Packages.scikit-fmm.dist</li>
    <li>python312Packages.scikit-fmm</li>
    <li>python312Packages.scikit-fmm.dist</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
The `fipy` failures appear unrelated:

```console
error: builder for '/nix/store/kwxjkl0851p161y9h5i6v89n7kaivhc5-python3.12-fipy-3.4.4.drv' failed with exit code 1;
       last 10 log lines:
       >     return get_versions()["version"]
       >            ^^^^^^^^^^^^^^
       >   File "/build/source/versioneer.py", line 1412, in get_versions
       >     cfg = get_config_from_root(root)
       >           ^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/build/source/versioneer.py", line 342, in get_config_from_root
       >     parser = configparser.SafeConfigParser()
       >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       > AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
       > /nix/store/awyrbj9n0di7b7dx1w7w98iyk4i3k9pn-stdenv-linux/setup: line 1579: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/kwxjkl0851p161y9h5i6v89n7kaivhc5-python3.12-fipy-3.4.4.drv'.
error: builder for '/nix/store/c3pgkryarhdxg4lvrxc9g3wb604dhjbr-python3.11-fipy-3.4.4.drv' failed with exit code 1;
       last 10 log lines:
       >        2.2          2.5       ]
       >
       >
       > ----------------------------------------------------------------------
       > Ran 361 tests in 12.245s
       >
       > FAILED (failures=1)
       > !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
       > Skipped 83 doctest examples because the `tvtk` package cannot be imported
       > !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
       For full logs, run 'nix log /nix/store/c3pgkryarhdxg4lvrxc9g3wb604dhjbr-python3.11-fipy-3.4.4.drv'.
```

**Review by GaetanLepage — APPROVED** [review]
LGTM

File: pkgs/development/python-modules/scikit-fmm/default.nix [hunk 1]
```diff
@@ -1,22 +1,52 @@
...
     hash = "sha256-14ccR/ggdyq6kvJWUe8U5NJ96M45PArjwCqzxuJCPAs=";
   };
 
-  propagatedBuildInputs = [ numpy ];
+  # TODO: Remove these patches after another stable release is made.
+  # For now, these allow us to build with Python 3.12+ by switching to Meson
+  # and off the deprecated distutils.
+  patches = [
+    (fetchpatch {
+      name = "first try at Meson build";
```
Comment (SuperSandro2000) [inline pkgs/development/python-modules/scikit-fmm/default.nix:26]: Not sure if we should replace the spaces by dashes or if that is done automatically

**Review by SuperSandro2000 — APPROVED** [review]

File: pkgs/development/python-modules/scikit-fmm/default.nix (hunk 1 above)
Comment (risicle) [reply pkgs/development/python-modules/scikit-fmm/default.nix:26]: Yeah ideally this would be `first-try-at-meson-build.patch`

**Comment by risicle** [comment]
Otherwise WFM macos 12 x86_64 & nixos x86_64

File: pkgs/development/python-modules/scikit-fmm/default.nix (hunk 1 above)
Comment (ConnorBaker) [reply pkgs/development/python-modules/scikit-fmm/default.nix]: Resolved in the latest -- I changed them all to be lowercase and use dashes.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
fipy still fails to build but this PR is a step in the right direction never the less.
