### ISSUE TITLE
`vscode-extensions.matklad.rust-analyzer` broken on `aarch64-darwin` due to `keytar` dependency missing framework build inputs

### ISSUE THREAD

**Issue by mstone** [NixOS/nixpkgs#152285]
### Describe the bug
`vscode-extensions.matklad.rust-analyzer` has been broken on `aarch64-darwin` since #147373 with build log failures that look like (excerpting from <https://hydra.nixos.org/build/161724798/nixlog/2>):

```
...
../src/keytar_mac.cc:1:10: fatal error: 'Security/Security.h' file not found
#include <Security/Security.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [keytar.target.mk:129: Release/obj.target/keytar/src/keytar_mac.o] Error 1
```

Another patch #149120, fixed a related issue but did not fix the keytar dependency on Darwin.

Fortunately, adding the necessary frameworks as conditional-on-darwin nativeBuildInputs in a manner similar to the way that `lib secret` is added by #149120 fixes things here too.

(PR incoming once I finish writing it up.)

### Notify maintainers
@bkchr, @mweinelt (and @oxalica as a courtesy, though I know she has recently stepped down from maintaining the vscode extension)
