### PR TITLE
opencv: 3.3.1 -> 3.4.0

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

https://github.com/opencv/opencv/wiki/ChangeLog#version34

The upgraded `ogre-1.10.10` is a dependency of the optional `ovis` module of `opencv-3.4.0`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Please fix build of `ogrepaged`.

**Comment by basvandijk** [comment]
@orivej thanks for the heads-up, I should've checked that. I've patched ogrepaged to build with ogre-1.10.

**Comment by orivej** [comment]
Thanks! Could you also fix the build of `mygui` with `ogre`: `nix-build -E '(import ./. { }).mygui.override { withOgre = true; }'`). (It is needed by `rigsofrods` and `stuntrally`.)

**Comment by basvandijk** [comment]
I pushed a few other fixes. Looking at `mygui` now...

**Comment by basvandijk** [comment]
@orivej I kept the old `ogre-1.9` around so that `mygui`, `rigsofrods` and `stuntrally` keep building.

**Review by orivej — APPROVED** [review]
I have added fixes for `opendungeons` and `rigsofrods`, this seems ready now.

**Review by orivej — CHANGES_REQUESTED** [review]
It's not ready yet because it breaks `digikam`:
```
[ 68%] Linking CXX shared library libdigikamgui.so                                                                                               
../libs/facesengine/CMakeFiles/digikamfacesenginedatabase_src.dir/recognition-opencv-lbph/opencvlbphfacerecognizer.cpp.o: In function `Digikam::O
penCVLBPHFaceRecognizer::recognize(cv::Mat const&)':                                                                                             
opencvlbphfacerecognizer.cpp:(.text+0x181): undefined reference to `cv::face::FaceRecognizer::predict(cv::_InputArray const&, int&, double&) cons
t'                                                                                                                                               
../libs/facesengine/CMakeFiles/digikamfacesenginedatabase_src.dir/recognition-opencv-lbph/facerec_borrowed.cpp.o: In function `Digikam::LBPHFaceR
ecognizer::create(int, int, int, int, double, Digikam::LBPHFaceRecognizer::PredictionStatistics)':                                               
facerec_borrowed.cpp:(.text+0x6399): undefined reference to `vtable for cv::face::FaceRecognizer'                                                
facerec_borrowed.cpp:(.text+0x6551): undefined reference to `vtable for cv::face::FaceRecognizer'                                                
```

**Comment by basvandijk** [comment]
@orivej thanks for the fixes and the heads-up for digikam. 

Fortunately digikam [released version 5.8.0 a few hours ago with support for opencv-3.4.0](https://raw.githubusercontent.com/KDE/digikam/v5.8.0/project/NEWS.5.8.0). I pushed an upgrade patch.

**Comment by basvandijk** [comment]
Note that `nix-shell -p nox --run "nox-review pr 33225"` now returns successfully.

**Comment by orivej** [comment]
Thank you!
