### PR TITLE
jnettop: pull pending upstream inclusion fix for ncurses-6.3

### PR DESCRIPTION
**Pull request by trofi**
Without the fix build on ncurses-6.3 fails as:

    jcursesdisplay.c:111:17: error: format not a string literal and no format arguments [-Werror=format-security]
      111 |                 mvprintw(2, 0, statusMessage);
          |                 ^~~~~~~~

### CODE REVIEW

**Review by teto — APPROVED** [review]
tested with nixpkgs-review
