### ISSUE TITLE
duplicity-0.6.25 doesn't compile

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7076]
Citing from http://hydra.cryp.to/build/675785/nixlog/1/raw:

    creating build/temp.linux-x86_64-2.7/duplicity
    gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/nix/store/pbi1lgank10fy0xpjckbdpgacqw34dsz-python-2.7.9/include/python2.7 -c duplicity/_librsyncmodule.c -o build/temp.linux-x86_64-2.7/duplicity/_librsyncmodule.o
    duplicity/_librsyncmodule.c: In function '_librsync_new_sigmaker':
    duplicity/_librsyncmodule.c:71:38: error: 'RS_DEFAULT_STRONG_LEN' undeclared (first use in this function)
                                  (size_t)RS_DEFAULT_STRONG_LEN);
                                          ^
    duplicity/_librsyncmodule.c:71:38: note: each undeclared identifier is reported only once for each function it appears in
    duplicity/_librsyncmodule.c:71:30: error: too few arguments to function 'rs_sig_begin'
                                  (size_t)RS_DEFAULT_STRONG_LEN);
                                  ^
    In file included from duplicity/_librsyncmodule.c:26:0:
    /nix/store/vfvpja9mmbz2bsy1mvpkbbx1as9i9j2f-librsync-1.0.0/include/librsync.h:370:11: note: declared here
     rs_job_t *rs_sig_begin(size_t new_block_len,
               ^
    error: command 'gcc' failed with exit status 1

**Comment by peti** [comment]
The build used to work fine in 230182f. Not sure what broke it. I tried `git bisect`, but the result I got isn't helpful because it points to a dependency of the package being broken.

**Comment by wkennington** [comment]
https://bugs.launchpad.net/duplicity/+bug/1416344

**Comment by wkennington** [comment]
Fixed via 0ff1fcf1f111b0044f5d14db494aa1c1b0b2c517
