### PR TITLE
cups-filters: fix the build with poppler-0.67.0

### LINKED ISSUE #44282: cups-filters: broken build from poppler_utils update
## Issue description
cups-filters fails to build on recent master (333a6646a8b9475bce8905c76855d2aa4d0a7411)

Reverting the recent poppler_utils update (7d016502d88a89bebb2fd8728a5bb40702a7feba) resolves the problem, and cups-filters builds properly again. This was PR #43915. 

### Steps to reproduce
Failure: `nix-build -A cups-filters`
```
  CC       gstoraster-gstoraster.o
  CC       mupdftoraster-mupdftoraster.o
  CC       foomatic_rip-foomaticrip.o
  CC       foomatic_rip-options.o
  CC       foomatic_rip-pdf.o
  CC       foomatic_rip-postscript.o
  CC       foomatic_rip-process.o
  CC       foomatic_rip-renderer.o
filter/pdf.cxx: In function 'int pdf_fill_form(pdf_t*, opt_t*)':
filter/pdf.cxx:740:44: error: invalid conversion from 'const GooString*' to 'GooString*' [-fpermissive]
             field_name = ff->getPartialName();
                          ~~~~~~~~~~~~~~~~~~^~
make[1]: *** [Makefile:3937: bannertopdf-pdf.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/cups-filters-1.20.4'
make: *** [Makefile:1975: all] Error 2
builder for '/nix/store/bshxw2d6zg5cw134nv5zch9favrn7gqp-cups-filters-1.20.4.drv' failed with exit code 2
error: build of '/nix/store/bshxw2d6zg5cw134nv5zch9favrn7gqp-cups-filters-1.20.4.drv' failed
```
Success: `git revert 7d016502d88a89bebb2fd8728a5bb40702a7feba && nix-build -A cups_filters`
## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.58, NixOS, 18.09.git.f134990 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-17.09pre104936.b0d07aa894"`
 - channels(calvertvl): `""`
 - nixpkgs: `/home/calvertvl/repos/nixpkgs`

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Apply the patch from https://github.com/OpenPrinting/cups-filters/pull/51 to fix the build of cups-filter originally broken by 7d016502d88a89bebb2fd8728a5bb40702a7feba.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

closes #44282

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build cups-filters system-config-printer

**Comment by xeji** [comment]
hash mismatch of the patch.

**Comment by kalbasit** [comment]
@xeji I fixed the hash, please rebuild.

**Comment by xeji** [comment]
That was fast :smiley:
@GrahamcOfBorg build cups-filters system-config-printer
