### ISSUE TITLE
whipper execution fails with ImportError

### ISSUE THREAD

**Issue by antonmosich** [NixOS/nixpkgs#312306]
### Describe the bug
When trying to launch whipper it instead fails with the following trace:
```
Traceback (most recent call last):
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/bin/.whipper-wrapped", line 6, in <module>
    from whipper.command.main import main
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/command/main.py", line 11, in <module>
    from whipper.command import cd, offset, drive, image, accurip, mblookup
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/command/cd.py", line 28, in <module>
    from whipper.common import (
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/common/program.py", line 30, in <module>
    from whipper.common import accurip, checksum, common, mbngs, path
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/common/checksum.py", line 28, in <module>
    from whipper.extern.task import task as etask
  File "/nix/store/r6gsikgg3xr5zkp8mqw5x469q09lam3f-whipper-0.10.0/lib/python3.11/site-packages/whipper/extern/task/task.py", line 24, in <module>
    from gi.repository import GLib as GLib
  File "/nix/store/9njwgmbs7jlpsrnnr731k2vv5xqghqr4-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GLib, introspection typelib not found
```

### Steps To Reproduce
1. `nix run nixpkgs#whipper -- --version` or any equivalent way of running the whipper program

### Expected behavior
Clearly, I expect the program to execute without an error.

### Additional context
I bisected the error and the bug was introduced in ba69532efcec53e3f6243837b364174ad9d840a6 which bumped `gobject-introspection`.

### Notify maintainers
@emilazy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(anton): `""`
 - nixpkgs: `/nix/store/0qd773b63yg8435w8hpm13zqz7iipcbs-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/316717
