### ISSUE TITLE
`haskellPackages.hlibsass` is unusable

### ISSUE THREAD

**Issue by Fresheyeball** [NixOS/nixpkgs#38253]
## Issue description
It does not build. 
```
/tmp/nix-build-hlibsass-0.1.6.1.drv-0/hlibsass-0.1.6.1/dist/build/libHShlibsass-0.1.6.1-2MNBVN1xUUtApNgmcK96rT-ghc8.2.2.so: undefined reference to `sass_resolve_file'
/tmp/nix-build-hlibsass-0.1.6.1.drv-0/hlibsass-0.1.6.1/dist/build/libHShlibsass-0.1.6.1-2MNBVN1xUUtApNgmcK96rT-ghc8.2.2.so: undefined reference to `sass_option_get_plugin_path'
```

### Steps to reproduce

```bash
$ cd nixpkgs
$ nix-build . -A haskellPackages.hlibsass
```

## Resolution 

I was able to get past this by editing `... libsass/default.nix` and setting the version to `3.4.3`. This is not a real fix, as we probably dont want to downgrade this package, but use the right version in `hackage-packages.nix`. 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.65, NixOS, 17.09.2182.7f6f0c49f0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(isaac): `"nixos-17.09.3200.f4f3e19eac8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
Possibly an upstream issue, see https://github.com/jakubfijalkowski/hlibsass/issues/3

**Comment by Radvendii** [comment]
They say that issue got fixed in version 0.1.5.0, and we're still having issues with version 0.1.6.1.

Presumably that means it's a different issue, right?

**Comment by jtojnar** [comment]
@Radvendii yes, I merely pointed out that a similar issue appeared in the past. It should be reported upstream again.

**Comment by jakubfijalkowski** [comment]
The problem is with version combination. Unfortuanately, hLibsass version must strictly follow libsass version. Version 0.1.6.1 won't work with LibSass 3.5.x, you need to ugrade to hLibSass 0.1.7.0 or downgrade LibSass to 3.4.3 (as you have done).

I've answered the issue on my repo with a [more detailed story](https://github.com/jakubfijalkowski/hlibsass/issues/9#issuecomment-391963092). Also, in the [hLibsass README](https://github.com/jakubfijalkowski/hlibsass#hlibsass-and-libsass-version), there's a compatibility list.

I don't know Nix nor NixOs (unfortunately) but I will try to assist with the fix.

**Comment by jtojnar** [comment]
Right, the last time upstream hlibsass was lagging behind. This time, upstream is already fixed but since we base our Haskell packages on LTS Haskell, the update did not come here yet.

The proper temporary solution would be creating a downgraded copy of the `libsass` package, `libsass_0_4_3`, and then adding the following to `pkgs/development/haskell-modules/configuration-common.nix`:

```nix
  hlibsass = super.hlibsass.override {
    libsass = pkgs.libsass_0_4_3;
  };
```

Or inline:

```nix
  # hlibsass 0.1.6 requires libsass 3.4
  hlibsass = dontCheck (super.hlibsass.override {
    libsass = pkgs.libsass.overrideAttrs (attrs: rec {
      name = "libsass-${version}";
      version = "3.4.9";
      src = pkgs.fetchurl {
        url = "https://github.com/sass/libsass/archive/${version}.tar.gz";
        sha256 = "0f4mj91zzdzah7fxkdg3dnrimk9ip7czl4g26f32zgifz1nrqgjs";
      };
      patchPhase = ''
        export LIBSASS_VERSION=${version}
      '';
    });
  });

```

----

Interestingly, we also have `hlibsass_0_1_7_0` package but it is not listed in `pkgs/development/haskell-modules/configuration-hackage2nix.yaml`, no idea where that comes from.

Even weirder, `haskellPackages.hlibsass` builds for me now, even though it is still 3.5.4 and 0.1.6.1.

**Comment by ryantm** [comment]
It builds now and it is 0.1.7.0, so I think this should be closed.
