### ISSUE TITLE
scenebuilder: "Could  not find or load main class com.oracle.javafx.scenebuilder.app.SceneBuilderApp"

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#238902]
### Describe the bug

On current master, unstable and 23.05 HEADs, the `scenebuilder` package can be built but not started.

### Steps To Reproduce
1. `nix run nixpkgs#scenebuilder`
2. See error:
   ```text
   Error: Could not find or load main class com.oracle.javafx.scenebuilder.app.SceneBuilderApp
   Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
   ```

### Expected behavior

Scenebuilder starts succesfully

### Additional context

A `git bisect` with `--first-parent` identified a `staging-next` merge from 2023-02-15 as the problem. (#216499; 30e272bc047dfa347315e9fe9bcb10a9cf1e0865)

```
30e272bc047dfa347315e9fe9bcb10a9cf1e0865 is the first bad commit
commit 30e272bc047dfa347315e9fe9bcb10a9cf1e0865
Merge: 5d1eee6cf04 1af0d67ebe1
Author: Vladimír Čunát <v@cunat.cz>
Date:   Sun Feb 26 10:11:50 2023 +0100

    Merge #216499: staging-next 2023-02-15
```

I started a more detailed bisection already though it is estimated on 8 steps, which in my experience take 6+ hours each on my hardware.

### Notify maintainers

* @wirew0rm

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.11 (Tapir), 23.11.20230617.04af42f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0pre20230619_3910430`
 - channels(nmelzer): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by wirew0rm** [comment]
I can reproduce and have a rough idea what the problem is. It looks like javafx is missing. This used to be part of the jdk (<v8), was then factored out into a separate openjfx dependency in JDK9, but many distributions including nix built jdk versions that manually patched openjfx into openjdk to not have to change the packaging of older javafx applications that expect it to be part of the jdk.
As an additional complication, we cannot just use javafx from maven central because it contains binary libraries linked against e.g. gtk that would have to be patchelfed.

I'll have a look later, let me know if you find out anything in the meantime or if you have any questions.

**Comment by wirew0rm** [comment]
@NobbZ found the change that broke scenebuilder (and also scenic-view) and added a PR to fix them. Feel free to test and review.
