### ISSUE TITLE
pidgin-sipe fails to build in nixpkgs-unstable

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#196257]
### Steps To Reproduce
1. `git checkout nixpkgs-unstable`  # tested at 31d567846255e122846548255101980162bbf641
2. `nix-build -A pidgin-sipe`

### Build log
```
In file included from /nix/store/dahsdlclq07r1zf1a44n43ay0r7jdg8k-pidgin-2.14.10/include/libpurple/dbus-server.h:54,
                 from purple-dbus.h:33,
                 from purple-dbus-bindings.c:29:
/nix/store/dahsdlclq07r1zf1a44n43ay0r7jdg8k-pidgin-2.14.10/include/libpurple/dbus-bindings.h:32:10: fatal error: dbus/dbus-glib-lowlevel.h: No such file or directory
   32 | #include <dbus/dbus-glib-lowlevel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Additional context
* pidgin-sipe builds fine in nixos-22.05.
* pidgin-sipe doesn't seem well maintained -- very little activity in https://sourceforge.net/projects/sipe/ AFAICT. I'm not sure what the alternatives are.

### Notify maintainers

There's no listed maintainers for pidgin-sipe (nor pidgin).

**Comment by bjornfor** [comment]
* I tried bisecting, but hit some staging/mass-rebuilds so I aborted.
* I tried adding `dbus-glib` to buildInputs, but ./configure seems to ignore it.

**Comment by bjornfor** [comment]
> I tried adding dbus-glib to buildInputs, but ./configure seems to ignore it.

Checking for dbus-glib only done if telepathy-glib is available. (It is not in nixpkgs-unstable.)

**Comment by daymien** [comment]
In **22.05** nix log pidgin-sipe`
...
checking for DBUS... no
...`

In **unstable** nix log pidgin-sipe`
...
checking for DBUS... no
...`

Not sure how to disable dbus dependency for nix build pkgs/applications/networking/instant-messengers/pidgin-plugins/sipe/default.nix

**Comment by daymien** [comment]
Update. I created a [PR](https://github.com/NixOS/nixpkgs/pull/206428) where pidgin-sipe is compiled without dbus.

**Comment by daymien** [comment]
#206428

**Comment by bjornfor** [comment]
Fixed on master and release-22.11 thanks to https://github.com/NixOS/nixpkgs/pull/206428 and its backport PR. Thanks @daymien!
