### PR TITLE
mapnik: 3.1.0 -> unstable-2022-04-14

### PR DESCRIPTION
**Pull request by erictapen**
###### Motivation for this change

Mapnik is currently broken, so I don't see any other choice than to use current master. I also bumped python-mapnik to latest master and fixed the build.

It required some minor patches, that I'm willing to maintain for future releases.

###### Things done

```
    mapnik: 3.1.0 -> unstable-2021-11-02
    
    - use CMake. I just didn't got it to work with SCons.
    - patch cmake to find harfbuzz
    - prefetch catch2 for enabling tests
    - add myself as maintainer
    - build mapnik-config with scons, as it isn't build by cmake
    - use python3 exclusively
    - build with harfbuzz-icu
    - change license to lgpl21Plus
```

```
    python3Packages.python-mapnik: unstable-2020-02-24 -> unstable-2020-09-08
    
    Also:
    
    - use libxml2 for xml parsing
    - use newest boost
    - patch to find libmapnik{json,wkt}.a
    - fix license
    - add myself as maintainer
```

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Does
```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index ee2d656c8bc..7026b0da1a8 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -18490,7 +18490,14 @@ with pkgs;

   opencl-clang = callPackage ../development/libraries/opencl-clang { };

-  mapnik = callPackage ../development/libraries/mapnik { };
+  mapnik = callPackage ../development/libraries/mapnik {
+    gdal = gdal.override {
+      libgeotiff = libgeotiff.override { proj = proj_7; };
+      libspatialite = libspatialite.override { proj = proj_7; };
+      proj = proj_7;
+    };
+    proj = proj_7;
+  };

   marisa = callPackage ../development/libraries/marisa {};

```
not do the trick? It might at least lead to problems when using other packages that depend on PROJ 8.

**Comment by erictapen** [comment]
@dotlambda Mh, sounds like an easy fix. python-mapnik builds with that.

I guess my changes make sense whenever a new mapnik version comes out. Until then I'd try your fix.

**Review by SuperSandro2000 — APPROVED** [review]

File: pkgs/development/libraries/mapnik/cmake-harfbuzz.patch [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+-    message(STATUS "Found harfbuzz native cmake")
+-    list(APPEND MAPNIK_OPTIONAL_LIBS harfbuzz::harfbuzz)
+-else()
+-    # we use our "own" FindHarfBuzz. See https://github.com/mapnik/mapnik/pull/4191#issuecomment-874728157 for more details
+-    message(STATUS "Fallback to FindHarfBuzz")
+-    mapnik_find_package(HarfBuzz ${HARFBUZZ_MIN_VERSION} REQUIRED COMPONENTS ICU)
+-    list(APPEND MAPNIK_OPTIONAL_LIBS HarfBuzz::HarfBuzz HarfBuzz::ICU)
+-endif()
++pkg_check_modules(harfbuzz REQUIRED IMPORTED_TARGET harfbuzz)
++list(APPEND MAPNIK_OPTIONAL_LIBS PkgConfig::harfbuzz)
```
Comment (mathisloge) [inline pkgs/development/libraries/mapnik/cmake-harfbuzz.patch:21]: With https://github.com/mapnik/mapnik/pull/4270 merged, you can pass `CMAKE_DISABLE_FIND_PACKAGE_harfbuzz=OFF` to the configure call to disable the `find_packge(harfbuzz)` and force pkg-config therefore. So the patch can be removed after that

Comment (erictapen) [reply pkgs/development/libraries/mapnik/cmake-harfbuzz.patch:21]: That's nice!
Any chance we'd get a new mapnik release anytime soon? Using master in Nixpkgs is usually only done for special cases, e.g. when the last stable release is broken/unsecure.

Comment (mathisloge) [reply pkgs/development/libraries/mapnik/cmake-harfbuzz.patch:21]: Good question. I don't really know which plans @artemp has regarding mapnik 4.0.0. I've just started contributing first things to mapnik like the CMake build and windows support.

Comment (mathisloge) [reply pkgs/development/libraries/mapnik/cmake-harfbuzz.patch:21]: merged. Patch could be removed

**Comment by dotlambda** [comment]
Does it make sense to apply the python-mapnik bump anyway?
Also https://github.com/NixOS/nixpkgs/pull/144544 breaks mapnik, so it might make sense to apply this patch after all.

**Comment by erictapen** [comment]
@dotlambda Sure, I'll open a separate PR!

**Comment by erictapen** [comment]
@dotlambda 
Looked a bit into it and unfortunately python-mapnik needs mapnik master. Their include file layout seems to have changed in many places.
Do you need the bump for anything specific?

**Comment by dotlambda** [comment]
> Do you need the bump for anything specific?

No. Let's just wait for the next official mapnik release.

File: pkgs/development/python-modules/python-mapnik/default.nix [hunk 2]
```diff
@@ -17,37 +19,42 @@
...
+  version = "unstable-2020-09-08";
 
   src = fetchFromGitHub {
     owner = "mapnik";
     repo = "python-mapnik";
-    rev = "7da019cf9eb12af8f8aa88b7d75789dfcd1e901b";
-    sha256 = "0snn7q7w1ab90311q8wgd1z64kw1svm5w831q0xd6glqhah86qc8";
+    rev = "a2c2a86eec954b42d7f00093da03807d0834b1b4";
+    sha256 = "sha256-GwDdrutJOHtW7pIWiUAiu1xucmRvp7YFYB3YSCrDsrY=";
+    fetchSubmodules = true;
```
Comment (SuperSandro2000) [inline pkgs/development/python-modules/python-mapnik/default.nix:35]: Maybe add a comment that this is only used for the test data.

Comment (erictapen) [reply pkgs/development/python-modules/python-mapnik/default.nix:36]: Done :+1:

**Comment by vcunat** [comment]
Perhaps reconsider, in light of PR https://github.com/NixOS/nixpkgs/pull/180578

**Comment by dotlambda** [comment]
> Perhaps reconsider, in light of PR #180578

In fact, mapnik's tests fail in #179406, so we need the mapnik upgrade.
I tried applying a60e669 there but mapnik fails to build with
```
/build/source/benchmark/src/test_png_encoding2.cpp:6:10: error: 'shared_ptr' in namespace 'std' does not name a template type
    6 |     std::shared_ptr<mapnik::image_rgba8> im_;
      |          ^~~~~~~~~~
/build/source/benchmark/src/test_png_encoding2.cpp:3:1: note: 'std::shared_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
    2 | #include "compare_images.hpp"
  +++ |+#include <memory>
    3 |
/build/source/benchmark/src/test_png_encoding2.cpp: In constructor 'test::test(const mapnik::parameters&)':
/build/source/benchmark/src/test_png_encoding2.cpp:16:9: error: 'im_' was not declared in this scope
   16 |         im_ = std::make_shared<mapnik::image_rgba8>(reader->width(),reader->height());
      |         ^~~
/build/source/benchmark/src/test_png_encoding2.cpp:16:20: error: 'make_shared' is not a member of 'std'
   16 |         im_ = std::make_shared<mapnik::image_rgba8>(reader->width(),reader->height());
      |                    ^~~~~~~~~~~
/build/source/benchmark/src/test_png_encoding2.cpp:16:20: note: 'std::make_shared' is defined in header '<memory>'; did you forget to '#include <memory>'?
/build/source/benchmark/src/test_png_encoding2.cpp:16:51: error: expected primary-expression before '>' token
   16 |         im_ = std::make_shared<mapnik::image_rgba8>(reader->width(),reader->height());
      |                                                   ^
/build/source/benchmark/src/test_png_encoding2.cpp: In member function 'virtual bool test::validate() const':
/build/source/benchmark/src/test_png_encoding2.cpp:23:31: error: 'im_' was not declared in this scope
   23 |         mapnik::save_to_file(*im_,actual, "png8:m=h:z=1");
      |                               ^~~
/build/source/benchmark/src/test_png_encoding2.cpp: In member function 'virtual bool test::operator()() const':
/build/source/benchmark/src/test_png_encoding2.cpp:31:43: error: 'im_' was not declared in this scope
   31 |             out = mapnik::save_to_string(*im_,"png8:m=h:z=1");
      |                                           ^~~
make[2]: *** [benchmark/CMakeFiles/mapnik-benchmark-test_png_encoding2.dir/build.make:76: benchmark/CMakeFiles/mapnik-benchmark-test_png_encoding2.dir/src/test_png_encoding2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1509: benchmark/CMakeFiles/mapnik-benchmark-test_png_encoding2.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by vcunat** [comment]
Well, that sounds easy to fix, as it hints:
```
note: 'std::shared_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
```

**Comment by erictapen** [comment]
I just rebased on latest nixpkgs master and bumped to latest mapnik master.

File: pkgs/development/python-modules/python-mapnik/default.nix [hunk 3]
```diff
@@ -60,16 +68,32 @@ buildPythonPackage rec {
...
 
   propagatedBuildInputs = [ pillow pycairo ];
 
-  pythonImportsCheck = [ "mapnik" ];
+  configureFlags = [
+    "XMLPARSER=libxml2"
+  ];
+
+  disabled = isPyPy;
+  doCheck = false; # doesn't find needed test data files
```
[the remark this answers is not in the document]
Comment (erictapen) [reply pkgs/development/python-modules/python-mapnik/default.nix]: The current reason why the tests fail is that one of them segfaults. I clarified the message. `fetchSubmodules` is unnecesseray then, I disabled it.

File: pkgs/development/python-modules/python-mapnik/default.nix [hunk 4]
```diff
@@ -60,16 +68,32 @@ buildPythonPackage rec {
...
+  preBuild = ''
+    export BOOST_PYTHON_LIB="boost_python${"${lib.versions.major python.version}${lib.versions.minor python.version}"}"
+    export BOOST_THREAD_LIB="boost_thread"
+    export BOOST_SYSTEM_LIB="boost_system"
+    export PYCAIRO=true
+    export XMLPARSER=libxml2
+  '';
+
+  # pythonImportsCheck = [ "mapnik" ];
```
[the remark this answers is not in the document]
Comment (erictapen) [reply pkgs/development/python-modules/python-mapnik/default.nix]: Not sure why I introduced it, but the current reason is that it just fails. It also fails when I try to import the module by hand. It looks like the necessary files don't get installed. Not sure how to proceed here.

**Comment by SuperSandro2000** [comment]
I think we should squash the commits together.

**Comment by erictapen** [comment]
@SuperSandro2000 I wanted to wait with that until it is mergeable, so the development of the PR remains observable.

**Comment by dotlambda** [comment]
I fixed the import by using the same version of PROJ for mapnik and python-mapnik.
Python-mapnik's tests are still failing and I lack the time to fix them.

File: pkgs/development/python-modules/python-mapnik/default.nix (hunk 2 above)
Comment (vcunat) [reply pkgs/development/python-modules/python-mapnik/default.nix:37]: The hash doesn't match.  You surely need to update it when switching `fetchSubmodules`.

**Comment by erictapen** [comment]
@dotlambda This is great news, thanks a lot! I was almost ready to give up, as I'm having a hard time remembering what I did back then.

How about we just disable the tests for now and do it some other time? I'll squash the commits then so this can be reviewed again.

**Comment by dotlambda** [comment]
> How about we just disable the tests for now and do it some other time? I'll squash the commits then so this can be reviewed again.

Okay, sounds good.

File: pkgs/development/libraries/mapnik/default.nix [hunk 5]
```diff
@@ -1,22 +1,41 @@
...
+, libxml2
+, proj
+, python3
+, sqlite
+, zlib
+, catch2
+, scons
+
+  # supply a postgresql package to enable the PostGIS input plugin
 , postgresql ? null
```
Comment (SuperSandro2000) [inline pkgs/development/libraries/mapnik/default.nix:26]: Please use a boolean to enable this.

File: pkgs/development/libraries/mapnik/default.nix [hunk 6]
```diff
@@ -28,84 +47,67 @@ in stdenv.mkDerivation rec {
...
+    libtiff
+    libwebp
+    proj
+    python3
+    sqlite
+    zlib
+    libxml2
 
     # optional inputs
     postgresql
```
Comment (SuperSandro2000) [inline pkgs/development/libraries/mapnik/default.nix:85]: optional inputs should be gated behind a lib.optional(s).

File: pkgs/development/libraries/mapnik/default.nix [hunk 7]
```diff
@@ -28,84 +47,67 @@ in stdenv.mkDerivation rec {
...
+    # Would require qt otherwise.
+    "-DBUILD_DEMO_VIEWER=OFF"
+  ];
 
-  preConfigure = ''
-    patchShebangs ./configure
+  # mapnik-config is currently not build with CMake. So we use the SCons for this one.
+  preBuild = ''
+    cd ..
+    # We don't put scons into nativeBuildInputs, as we build the remainder of the project with cmake.
```
Comment (SuperSandro2000) [inline pkgs/development/libraries/mapnik/default.nix:96]: This breaks splicing and tho cross compile. Does scon not have a flag to disable it hooks?

File: pkgs/development/libraries/mapnik/default.nix (hunk 5 above)
Comment (dotlambda) [reply pkgs/development/libraries/mapnik/default.nix:26]: We can just get rid of the option not to use postgresql.

**Comment by dotlambda** [comment]
@erictapen Please squash if the changes look good to you. I suggest we move the last two commits to a separate PR targeting staging.

File: pkgs/development/libraries/mapnik/default.nix (hunk 5 above)
Comment (SuperSandro2000) [reply pkgs/development/libraries/mapnik/default.nix]: also fine for me

File: pkgs/development/libraries/mapnik/default.nix [hunk 8]
```diff
@@ -28,84 +45,64 @@ in stdenv.mkDerivation rec {
...
+    # Would require qt otherwise.
+    "-DBUILD_DEMO_VIEWER=OFF"
+  ];
 
-  preConfigure = ''
-    patchShebangs ./configure
+  # mapnik-config is currently not build with CMake. So we use the SCons for this one.
+  preBuild = ''
+    cd ..
+    ${scons}/bin/scons utils/mapnik-config
```
[the remark this answers is not in the document]
Comment (erictapen) [reply pkgs/development/libraries/mapnik/default.nix:92]: Yeah that breaks the build, as stdenv tries to build everything with scons then. I amended the comment to clarify that.

[the remark this answers is not in the document]
Comment (erictapen) [reply pkgs/development/libraries/mapnik/default.nix:94]: Looks like the solution, but can't we just merge this and then put these changes on top (via staging)? Seems like a rather unproblematic occurence of non-idiomatic code to me.

[the remark this answers is not in the document]
Comment (dotlambda) [reply pkgs/development/libraries/mapnik/default.nix:94]: We could also use `buildPackages.scons` and avoid `nativeBuildInputs`.

**Review by dotlambda — CHANGES_REQUESTED** [review]
The radioboat commit shouldn't be here.

**Comment by erictapen** [comment]
@dotlambda Right, don't know how that slipped in.

File: pkgs/development/libraries/mapnik/default.nix (hunk 8 above)
[the remark this answers is not in the document]
Comment (erictapen) [reply pkgs/development/libraries/mapnik/default.nix]: Good point about `buildPackages`, I included that.

**Comment by dotlambda** [comment]
included in https://github.com/NixOS/nixpkgs/pull/179406
