### ISSUE TITLE
can't recompile xmonad.

### ISSUE THREAD

**Issue by user-b** [NixOS/nixpkgs#133455]
Hello and sorry to ask such a minor thing. Basically I can't recompile xmonad. As I haven't tried doing this in a very long time, I can't say if it stoped working when I switched my nixos config to flakes, when stack broke at some point and I stopped using it or after updating to 21.05 (I think it's maybe the last one). I tried many recipies spread over the internet, but still I can't get it to work and also I can't find any oficial/recent/working docs to start from scratch. Sorry for the spam if I missed something.

Error: 
```
xmonad.hs:1:1: error:
    Could not load module ‘XMonad’
    It is a member of the hidden package ‘xmonad-0.15’.
    You can run ‘:set -package xmonad’ to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | import XMonad
  | ^^^^^^^^^^^^^
```

Config:
```
    windowManager.xmonad = {
      enable = true;
      enableContribAndExtras = true;
    };
     displayManager.defaultSession = "none+xmonad";
```

Adding ghc and haskellPackages.xmonad to environment.systemPackages seems to have no effect on this.

**Comment by sternenseemann** [comment]
> Adding ghc and haskellPackages.xmonad to environment.systemPackages seems to have no effect on this.

The error message seems to indicate that the dependency package is available, but GHC is not told (via the `-package` flag) to use it. I'm have no clue about xmonad and especially xmonad recompilation (does this even work on NixOS?), but hopefuly this helps you in debugging?

**Comment by sternenseemann** [comment]
cc @Lassulus @xaverdh @ivanbrennan (NixOS module maintainers)

**Comment by xaverdh** [comment]
Most of the options in `services.xserver.windowManager.xmonad` like `enableContribAndExtras` and `extraPackages` are only relevant if you also use `services.xserver.windowManager.xmonad.config` and put your xmonad configuration into the *.nix file like that.
If you do the old-school recompile xmonad-in-your-home-directory approach (like you would in any other linux distro), then you don't need these options. You will only need `enable = true`.

**Comment by xaverdh** [comment]
Now that I think of it, we should probably make  `environment.systemPackages` complain loudly if you put a haskell library there. Maybe point people to `ghcWithPackages` as well..

**Comment by user-b** [comment]
Thanks. I'm not using services.xserver.windowManager.xmonad.config. Also I'm not executing ghci from the command line, I'm just trying to recompile with the "modMask + Q" shortcut xmonad provides. I can run `xmonad --recompile` instead but it's the same story. How should I tell ghc which packages to use with this method? Not even `xmonad` gets loaded although it seems to be available as @sternenseemann pointed out.

Running `nix-shell -p 'haskellPackages.ghcWithPackages (ps: with ps; [ xmonad xmonad-contrib ])' --run ghci` yields:

```
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

at «string»:1:13:

1| with import <nixpkgs> { }; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (haskellPackages.ghcWithPackages (ps: with ps; [ xmonad xmonad-contrib ])) ]; } ""
             |~

```

**Comment by xaverdh** [comment]
Your `NIX_PATH` is probably not set correctly then, but that's a separate issue.
Can you try to add something like `( pkgs.haskellPackages.ghcWithPackages (ps: with ps; [ xmonad xmonad-contrib ]) )` to your `environment.systemPackages` list and see if that allows you to use "modMask + Q" (after rebuilding your config, and restarting your system)?

**Comment by user-b** [comment]
Sorry but It didn't work. Maybe It's time to start from 0 with a fresh nixos install, nobody else seems to have this issue.

**Comment by sternenseemann** [comment]
I would rather assume that `xmonad --recompile` is just not very widely used by NixOS users.

**Comment by user-b** [comment]
I think most (all?) tutorials/blogs/discussion I read were about using xmonad that way. I just tried the other way (with services.xserver.windowManager.xmonad.config) but after switching (& rebooting) it complains with the same errors while loading ~/.xmonad/xmonad.hs. It's not supposed to be trying to read that file I think? Removing the file just causes another error.

**Comment by user-b** [comment]
Well, the new configuration only took effect after running `systemctl restart display-manager`. Even rebooting a few times before doing this didn't work  for some reason.

Closing this issue. Thanks for the answers.

**Comment by user-b** [comment]
Well, the new configuration only took effect after running systemctl restart display-manager. Even rebooting a few times before doing this didn't work for some reason.

Closing this issue. Thanks for the answers.
