### ISSUE TITLE
gtk{2,3}-x11 fails to build on Darwin

### ISSUE THREAD

**Issue by smaret** [NixOS/nixpkgs#54424]
## Issue description

gtk+-2.24.32 fails to build on Darwin with the following error message:

```
gdkapplaunchcontext-x11.c:29:10: fatal error: 'gio/gdesktopappinfo.h' file not found
#include <gio/gdesktopappinfo.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [Makefile:843: gdkapplaunchcontext-x11.lo] Error 1
[...]
builder for '/nix/store/zikf8wwzs8q5rdgydkr31qjlnsgy8wnf-gtk+-2.24.32.drv' failed with exit code 2
```

### Steps to reproduce

```
nix-build -A gtk2-x11
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(smaret): `"nixos-19.03pre161883.e85c1f58680, nixpkgs-19.03pre160749.3a393eecafb"`
 - nixpkgs: `/nix/store/ky1klzpsz7dx098rv7j5zahnkhdlicfq-master.tar.gz`

**Comment by hedning** [comment]
Probably caused by https://github.com/NixOS/nixpkgs/pull/54007. First failure happened with [this diff](https://hydra.nixos.org/api/scmdiff?rev1=5e6ae9b6a51a1ab4a182b23f5bc883e4ae7f6692&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&branch=&rev2=eebeb363dadae5b62b312016b4bae400fe2b3a25&type=git).

**Comment by hedning** [comment]
So glib on darwin no longer provides the header. I'm guessing we should switch from `gtk{2,3}-x11` to `gtk{2,3}` as many places as possible, hopefully that's possible now.

**Comment by hedning** [comment]
Some more info at #54428

**Comment by smaret** [comment]
It builds on `staging`. Is there a fix in this branch?

**Comment by matthewbauer** [comment]
gtk{2,3}-x11 is pretty much required in lots of places without extensive patching (fatal error: 'gdk/gdkx.h' file not found)
