### ISSUE TITLE
Build failure: pkgsCuda.ceres-solver

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#560909]
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

`nix-build -A pkgsCuda.ceres-solver`

### Can Hydra reproduce this build failure?

Hydra doesn’t try to build the package.

### Relevant log output

```console
In file included from /nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/SuiteSparseQR.hpp:23,
                 from /build/ceres-solver-2.2.0/internal/ceres/suitesparse.h:46,
                 from /build/ceres-solver-2.2.0/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:45:
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:937:39: error: 'cublasHandle_t' does not name a type
  937 |         #define CHOLMOD_CUBLAS_HANDLE cublasHandle_t
      |                                       ^~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:947:5: note: in expansion of macro 'CHOLMOD_CUBLAS_HANDLE'
  947 |     CHOLMOD_CUBLAS_HANDLE cublasHandle ;
      |     ^~~~~~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:938:39: error: 'cudaStream_t' does not name a type
  938 |         #define CHOLMOD_CUDASTREAM    cudaStream_t
      |                                       ^~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:950:5: note: in expansion of macro 'CHOLMOD_CUDASTREAM'
  950 |     CHOLMOD_CUDASTREAM  gpuStream [CHOLMOD_HOST_SUPERNODE_BUFFERS] ;
      |     ^~~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:939:39: error: 'cudaEvent_t' does not name a type
  939 |         #define CHOLMOD_CUDAEVENT     cudaEvent_t
      |                                       ^~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:952:5: note: in expansion of macro 'CHOLMOD_CUDAEVENT'
  952 |     CHOLMOD_CUDAEVENT   cublasEventPotrf [3] ;
      |     ^~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:939:39: error: 'cudaEvent_t' does not name a type
  939 |         #define CHOLMOD_CUDAEVENT     cudaEvent_t
      |                                       ^~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:953:5: note: in expansion of macro 'CHOLMOD_CUDAEVENT'
  953 |     CHOLMOD_CUDAEVENT   updateCKernelsComplete ;
      |     ^~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:939:39: error: 'cudaEvent_t' does not name a type
  939 |         #define CHOLMOD_CUDAEVENT     cudaEvent_t
      |                                       ^~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:954:5: note: in expansion of macro 'CHOLMOD_CUDAEVENT'
  954 |     CHOLMOD_CUDAEVENT   updateCBuffersFree [CHOLMOD_HOST_SUPERNODE_BUFFERS] ;
      |     ^~~~~~~~~~~~~~~~~
make[2]: *** [internal/ceres/CMakeFiles/ceres_internal.dir/build.make:1241: internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_sparse_normal_cholesky_solver.cc.o] Error 1
make[2]: *** [internal/ceres/CMakeFiles/ceres_internal.dir/build.make:1031: internal/ceres/CMakeFiles/ceres_internal.dir/covariance_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:324: internal/ceres/CMakeFiles/ceres_internal.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### Additional context

Seems to be broken by https://github.com/NixOS/nixpkgs/pull/503891

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.48, NixOS, 26.11 (Zokor), 26.11.20260826.9fbb54b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.8`

### Notify maintainers

@giogadi 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wegank** [comment]
Maybe this could help? https://github.com/ConnorBaker/nixpkgs/commit/31a5f15104bd51babc9a41fbe313a163dcf9b495

**Comment by amarshall** [comment]
Indeed that fixes build cc @ConnorBaker.
