### ISSUE TITLE
Build failure: mba6x_bl

### ISSUE THREAD

**Issue by DanielSiepmann** [NixOS/nixpkgs#237574]
### Steps To Reproduce

1. build mba6x_bl

E.g. via nixos-hardware on a MacBook Air: https://github.com/NixOS/nixos-hardware/blob/master/apple/macbook-air/6/default.nix#L7

### Build log

```
building '/nix/store/0hc9jb2sh9897c9y0d1dmlzgjwfqv7wp-etc.drv'...
  CC [M]  /build/source/mba6x_bl.o
/build/source/mba6x_bl.c: In function 'platform_probe':
/build/source/mba6x_bl.c:325:9: error: implicit declaration of function 'acpi_video_set_dmi_backlight_type'; did you mean 'acpi_video_get_backlight_type'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]
  325 |         acpi_video_set_dmi_backlight_type(acpi_backlight_vendor);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         acpi_video_get_backlight_type
cc1: some warnings being treated as errors
make[2]: *** [/nix/store/gdcczw6d8ycjvnn8hz2k6a8yainkbwsd-linux-6.1.32-dev/lib/modules/6.1.32/source/scripts/Makefile.build:250: /build/source/mba6x_bl.o] Error 1
make[1]: *** [/nix/store/gdcczw6d8ycjvnn8hz2k6a8yainkbwsd-linux-6.1.32-dev/lib/modules/6.1.32/source/Makefile:2012: /build/source] Error 2
make: *** [Makefile:8: all] Error 2
error: builder for '/nix/store/4sw603dvhcfjcvcwqma74rkb6qzcycss-mba6x_bl-unstable-2016-12-08.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/nkbzc0ic61dsl36dmyz60a6m57yg5r3g-kernel-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h25k46fbm3j04f0vj9z885k251n7609n-linux-6.1.32-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cicgd5p9sz2ma956ycz5jw11kncbwp5v-nixos-system-hikari-23.11pre492895.a64b73e07d4.drv' failed to build
```

### Additional context

This issue occurs since kernel 6.1, it works fine with 5.15.

Related file: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/mba6x_bl/default.nix

I'm not sure if this is still necessary with newer Kernels. I'll open another issue within https://github.com/NixOS/nixos-hardware/ and cross-reference both.

I'm not a Linux or Kernel expert, just an end user that encountered the issue during upgrading NixOS.

### Notify maintainers

@simonvandel

And the following due to touching the file last: @NickCao

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.32, NixOS, 23.11 (Tapir), 23.11pre492895.a64b73e07d4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos, nixos-hardware, phps"`
 - channels(daniels): `"home-manager, nixpkgs, phps"`
 - nixpkgs: `/home/daniels/.nix-defexpr/channels/nixpkgs`
```

**Comment by t4ccer** [comment]
Caused by https://patchwork.kernel.org/project/dri-devel/patch/20220712193910.439171-26-hdegoede@redhat.com/
