### PR TITLE
smemstat: pull pending upstream inclusion fix for ncurses-6.3

### PR DESCRIPTION
**Pull request by trofi**
Without the fix build on ncurses-6.3 fails as:

    smemstat.c:348:33: error: format not a string literal and no format arguments [-Werror=format-security]
      348 |         (void)mvprintw(cury, 0, buf);
          |                                 ^~~

### CODE REVIEW

**Review by r-burns — APPROVED** [review]
Patch and updated homepage LGTM

Result of `nixpkgs-review pr 144929` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>smemstat</li>
  </ul>
</details>
