### ISSUE TITLE
Build failure: qelectrotech

### ISSUE THREAD

**Issue by Merikei** [NixOS/nixpkgs#532690]
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

Attempt to build locally or in Hydra (error same in both)

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

https://hydra.nixos.org/build/328807323

### Relevant log output

```console
[ 80%] Building CXX object CMakeFiles/qelectrotech.dir/sources/TerminalStrip/ui/terminalstripeditor.cpp.o
In file included from /build/source/sources/TerminalStrip/ui/terminalstripeditor.cpp:19:
/build/source/build/qelectrotech_autogen/include/ui_terminalstripeditor.h:29:10: fatal error: kcolorcombo.h: No such file or directory
   29 | #include "kcolorcombo.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/qelectrotech.dir/build.make:24727: CMakeFiles/qelectrotech.dir/sources/TerminalStrip/ui/terminalstripeditor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/qelectrotech.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Additional context

Broken by https://github.com/NixOS/nixpkgs/pull/513691

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.92, NixOS, 25.11 (Xantusia), 25.11.20260608.e820eb4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.93.4
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/merikei/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/merikei/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/merikei/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/merikei/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/merikei/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/yjcffnriqddwdmd4488fzxxw77b0i93m-gnome-settings-daemon-49.1/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/jg51azacksxdmvwwyjv66kjkmxj918fl-lix-2.93.4/share`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/149h1h9bpd4vnl0rnm4s3dm7mh5pgv6q-source`

### Notify maintainers

@yvesf

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GraysonTinker** [comment]
Needs `kdePackages.kwidgetsaddons.dev`

**Comment by Merikei** [comment]
Thanks for the pointer!
But adding `kdePackages` to the inputs and
`kdePackages.kwidgetsaddons` to `buildInputs` (which a few other packages do) does not change the error
Adding `kdePackages.kwidgetsaddons.dev` to `buildInputs` also does not change the error.

I think because QET requires KF5 and the other packages using `kdePackages.kwidgetsaddons` are Qt6?

**Comment by Merikei** [comment]
(keeping `kdePackages` added to the inputs and)
adding `kdePackages.plasma5support` to `buildInputs` (both with and without `kdePackages.kwidgetsaddons` or `kdePackages.kwidgetsaddons.dev`)
results in
```
Error: detected mismatched Qt dependencies:
    /nix/store/wzvm2pvf98a71v0scgfhmi01lqcxahfr-qtbase-6.11.0
    /nix/store/r5n68l3iwrlzfl9vcpdig8ynrh96pzja-qtbase-5.15.18-dev
```

(the description “Support components for porting from KF5/Qt5 to KF6/Qt6” didn't sound that likely to work, but figured it was worth a go)
