### ISSUE TITLE
Can't reproduce a Hydra build

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#14866]
## Issue description

I observe a different behaviour between NixOS system (from the official VirtualBox image) and Hydra build:
http://hydra.nixos.org/build/34731828
The hydra build fails whereas build in my NixOS instance succeeds (with and without chroot enabled). According to the Hydra logs, the build fails with missing compiledata.h file which is generated by an invocation of a shell script:
https://github.com/root-mirror/root/blob/9afb00d699e7a1c32a72d15070db50d8b6bf33cf/build/unix/compiledata.sh
which is unconditionally called from here:
https://github.com/root-mirror/root/blob/9afb00d699e7a1c32a72d15070db50d8b6bf33cf/cmake/modules/RootConfiguration.cmake#L611-L615
I imagine that the problem might be with the shebang of the shell script and I have a hunch that a simple
```
    substituteInPlace build/unix/compiledata.sh \
      --replace "/usr/bin/env bash" "${stdenv.shell}"
```
could potentially fix the Hydra build. But it is really discouraging to try submitting PR's blindly without knowing why I get this different behaviour.
Any ideas why the issue happens at all?
### Steps to reproduce

Run
```
bash <(curl http://hydra.nixos.org/build/34731828/reproduce)
```
The build should succeed despite it failing on Hydra.

## Technical details

* System: 
16.03.616.4ac4b35 (Emu)
* Nix version: 
nix-env (Nix) 1.11.2
* Nixpkgs version: 
"16.03.616.4ac4b35"

**Comment by vcunat** [comment]
That looks like a parallel-make issue &ndash; attempting to use the generated header before it gets created.

**Comment by veprbl** [comment]
I don’t think so. The header is generated at the moment of cmake call which strictly precedes make -j ...

**Comment by veprbl** [comment]
In Hydra logs:
```
-- Performing Test found_stdexpstringview - Failed
-- Configuring done
WARNING: Target "clang" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "clang-format" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /tmp/nix-build-root-6.04.16.drv-0/root-6.04.16/build
```
From local builds:
```
-- Performing Test found_stdexpstringview - Failed
Running /tmp/nix-build-root-6.04.16.drv-1/root-6.04.16/build/unix/compiledata.sh
Making include/compiledata.h
-- Configuring done
WARNING: Target "clang" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "clang-format" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /tmp/nix-build-root-6.04.16.drv-1/root-6.04.16/build
```
"Running ..." and "Making ..." are output of the shell script.

**Comment by vcunat** [comment]
I do get problems when compiling it locally:
```
[  1%] Building C object core/clib/CMakeFiles/Clib.dir/src/strlcpy.c.o
/tmp/nix-build-root-6.04.16.drv-0/root-6.04.16/core/clib/src/strlcpy.c:19:54: fatal error: RConfig.h: No such file or directory
compilation terminated.
core/clib/CMakeFiles/Clib.dir/build.make:62: recipe for target 'core/clib/CMakeFiles/Clib.dir/src/strlcpy.c.o' failed
```

**Comment by vcunat** [comment]
Hmm, I actually get the same error when running with `--cores 1` (after a rather long time, on `[ 44% ]`).

**Comment by veprbl** [comment]
By the same you mean "Rconfig.h" one or "compiledata.h"?

**Comment by vcunat** [comment]
"Rconfig.h". Maybe the situation has changed since the referenced Hydra build... I was trying these two builds on master c4626ad.

**Comment by veprbl** [comment]
When I'm building c4626ad354ea1e7568d2ec8388871153925e7012 I get a following error:
```
Scanning dependencies of target Clib
[ 44%] Building C object core/clib/CMakeFiles/Clib.dir/src/detach.c.o
/tmp/nix-build-root-6.04.16.drv-1/root-6.04.16/core/clib/src/detach.c:28:23: fatal error: mmprivate.h: No such file or directory
compilation terminated.
core/clib/CMakeFiles/Clib.dir/build.make:62: recipe for target 'core/clib/CMakeFiles/Clib.dir/src/detach.c.o' failed
make[2]: *** [core/clib/CMakeFiles/Clib.dir/src/detach.c.o] Error 1
CMakeFiles/Makefile2:10512: recipe for target 'core/clib/CMakeFiles/Clib.dir/all' failed
make[1]: *** [core/clib/CMakeFiles/Clib.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/ljk4dsck82xi29ss3x1sr1q6msn7b1dn-root-6.04.16.drv’ failed with exit code 2
error: build of ‘/nix/store/ljk4dsck82xi29ss3x1sr1q6msn7b1dn-root-6.04.16.drv’ failed
```
This one can't find "mmprivate.h". I used git bisect to determine that the build was broken by 491f7f017c4dd247413d3367d4733541c797d9ea.

**Comment by veprbl** [comment]
I think my initial guess in the OP was correct.
Looking at #6227 it seems that /usr/bin/env may not be present in chroot on some of NixOS versions. I don't know what Hydra has, but my system does have /usr/bin/env in chroot.

**Comment by vcunat** [comment]
NixOS systems do have it, but it isn't present during chrooted builds IIRC.

**Comment by veprbl** [comment]
I just discovered that nix-build wasn't using chroot all this time even though I thought I asked it to do so:
```
nix-build --option build-use-chroot true -A root
```
I was able to enable it only through system-wide configuration in /etc/nixos/configuration.nix
Why ```--option build-use-chroot true``` doesn't work?

**Comment by vcunat** [comment]
I'm not sure. Maybe you need to setup `build-sandbox-paths` as well.

The "chroot" strings are deprecated, really, and should be replaced by "sandbox". The old aliases are supposed to work, unless I've made a mistake when implementing that.

**Comment by veprbl** [comment]
So the problem is that settings will not propagate to nix-daemon. This behaviour certainly doesn't hurt security, but nix should probably produce some warnings so that the user don't get confused.

**Comment by vcunat** [comment]
It's unfortunate that even mistyped options just get silently ignored. I at least modified the PR template not to suggest passing that `--option`, as most use nix-daemon, I think.
