### PR TITLE
Webpack-cli: init at 3.1.2

### PR DESCRIPTION
**Pull request by P-E-Meunier**
###### Motivation for this change
Webpack-cli is a useful tool to produce WASM code. It relies on webpack, another Node package, which for some reason does not work on its own and wanted to download webpack-cli in my home.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by P-E-Meunier** [comment]
And by the way, we should have a better way to merge the outputs of node2nix than downloading all of NPM.

**Comment by P-E-Meunier** [comment]
Ok, I've merged my changes once again (using node2nix), but it'd be really cool if this could be merged pretty soon, so that I don't have to run this process again.

**Comment by ln-nl** [comment]
> which for some reason does not work on its own and wanted to download webpack-cli in my home

@P-E-Meunier still doesn't work for me with your PR:

`sudo nixos-rebuild switch -I nixpkgs=.`

<details>
  <summary>`$ webpack-cli`</summary>
  <p>
```
/nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/bin/cli.js:235
				throw err;
				^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/bin/convert-argv.js:7:24)
    at Module._compile (/nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at yargs.parse (/nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/bin/cli.js:232:14)
    at Object.parse (/nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/bin/cli.js:210:8
    at Object.<anonymous> (/nix/store/iky8gjl0034w13q04kf5v24a370h5ys7-node-webpack-cli-3.2.1/lib/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
  <details>

<details>
  <summary>`$ webpack`</summary>
  <p>
```
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): no
You need to install 'webpack-cli' to use webpack via CLI.
You can also install the CLI manually.
```
  <details>

**Comment by ln-nl** [comment]
Thank you!
