### PR TITLE
xone: fix build on kernel 6.3

### LINKED ISSUE #231958: Build failure: xone
### Steps To Reproduce

1. build *xone*

### Build log

```
error: builder for '/nix/store/hicl4zc0sy06b9asv2a6hsrji3pj4vp6-xone-0.3.drv' failed with exit code 2;
       last 10 log lines:
       >   CC [M]  /build/source/transport/mt76.o
       >   LD [M]  /build/source/xone-dongle.o
       >   CC [M]  /build/source/bus/bus.o
       > /build/source/bus/bus.c:91:19: error: initialization of 'int (*)(const struct device *, struct kobj_uevent_env *)' from incompatible pointer type 'int (*)(struct device *, struct kobj_uevent_env *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >    91 |         .uevent = gip_client_uevent,
       >       |                   ^~~~~~~~~~~~~~~~~
       > /build/source/bus/bus.c:91:19: note: (near initialization for 'gip_client_type.uevent')
       > cc1: some warnings being treated as errors
       > make[1]: *** [/nix/store/q69zf8bq13qcl56gs6npij9vsraqnlfd-linux-6.3.1-dev/lib/modules/6.3.1-xanmod1/source/scripts/Makefile.build:252: /build/source/bus/bus.o] Error 1
       > make: *** [/nix/store/q69zf8bq13qcl56gs6npij9vsraqnlfd-linux-6.3.1-dev/lib/modules/6.3.1-xanmod1/source/Makefile:2180: /build/source] Error 2
       For full logs, run 'nix log /nix/store/hicl4zc0sy06b9asv2a6hsrji3pj4vp6-xone-0.3.drv'.
error: 1 dependencies of derivation '/nix/store/kjvmzz14ghb0mr4pylw74mjfrf1hw44n-kernel-modules.drv' failed to build
```

### Notify maintainers

@rhysmdnz

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.12-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230506.897876e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/etc/nix/flake-channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by Raroh73**
###### Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/231958

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/233222
