### PR TITLE
broadcom_sta: fix build on linux 6.0

### LINKED ISSUE #194903: broadcom_sta fails to build on kernel 6.0.0
### Steps To Reproduce
```
boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
```
```
kernelPackages = pkgs.linuxPackages_latest;
```

### Build log
```
[...]
error: builder for '/nix/store/703dpjfimaxcn9kkqj1kc9y44bqxvpha-broadcom-sta-6.30.223.271-6.0.drv' failed with exit code 2;
       last 10 log lines:
       >   CC [M]  /build/broadcom-sta/src/wl/sys/wl_iw.o
       >   CC [M]  /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o
       > /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c: In function 'wl_bss_roaming_done':
       > /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:2359:18: error: 'struct cfg80211_roam_info' has no member named 'bss'
       >  2359 |         roam_info.bss = bss;
       >       |                  ^
       > make[2]: *** [/nix/store/kc88pxfi83v5j71i22m86kqf8bp0s0x6-linux-6.0-dev/lib/modules/6.0.0/source/scripts/Makefile.build:249: /build/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.o] Error 1
       > make[1]: *** [/nix/store/kc88pxfi83v5j71i22m86kqf8bp0s0x6-linux-6.0-dev/lib/modules/6.0.0/source/Makefile:1852: /build/broadcom-sta] Error 2
       > make[1]: Leaving directory '/nix/store/kc88pxfi83v5j71i22m86kqf8bp0s0x6-linux-6.0-dev/lib/modules/6.0.0/build'
       > make: *** [Makefile:161: all] Error 2
       For full logs, run 'nix log /nix/store/703dpjfimaxcn9kkqj1kc9y44bqxvpha-broadcom-sta-6.30.223.271-6.0.drv'.
error: 1 dependencies of derivation '/nix/store/z92ic6dzfcd8kjr995p1sipv56bfqr50-kernel-modules.drv' failed to build
```

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: "x86_64-linux"
 - host os: Linux 5.19.5, NixOS, 22.11 (Raccoon), 22.11.20220901.2da64a8
 - multi-user?: yes
 - sandbox: yes
 - version: nix-env (Nix) 2.11.0
 - nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

### PR DESCRIPTION
**Pull request by X9VoiD**
Fix build issues when building against linux 6.0

Fixes #194903

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by oluceps — APPROVED** [review]

**Comment by X9VoiD** [comment]
Gonna ping @teto, just in case you weren't aware of the issue and/or this PR.

###### did not mean to bother, no rush.

**Comment by teto** [comment]
@X9VoiD did you write the pedantic fix yourself ?
Looks ok, I can't test since I dont have a machine with broadcom_sta anymore (so no need to ping me for future PRs xD).  @oluceps if you can test feel free to merge. If you dont have the rights, I will do it.

**Review by teto — APPROVED** [review]

**Comment by oluceps** [comment]
> @X9VoiD did you write the pedantic fix yourself ?
> Looks ok, I can't test since I dont have a machine with broadcom_sta anymore (so no need to ping me for future PRs xD).  @oluceps if you can test feel free to merge. If you dont have the rights, I will do it.

I've tested it on my machine with Broadcom_sta and it works fine, I think it's ready to merge.

**Comment by X9VoiD** [comment]
Yeah, and it's kinda annoying since the pedantic patch makes it so i also have to update it when future patches causes a conflict. If there's a way to disable the pedantic stuff then I'm up for it.
