### PR TITLE
gnomeExtensions.arc-menu: 33.2 -> 33

### PR DESCRIPTION
**Pull request by dkabot**
###### Motivation for this change
Development version 33.2 does not work with current GNOME 3.34, giving the following error: `TypeError: ExtensionSystem.connect is not a function`
Using the stable version 33 (which is more recent, despite the number) resolves this, and makes the extension usable once again.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
Duplicate of #70533, I was also confused on the versioning.

**Comment by worldofpeace** [comment]
> Ah, sorry I missed that; I'll try to be more careful in the future.
> Thanks for merging the other one!

Yeah, this does happen sometimes. But right, it did get merged one way or another :smile:
