### ISSUE TITLE
mirage-im: not working

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#211066]
### Describe the bug
`pkgs.mirage-im` was working in 22.05 but in 22.11 not anymore. The package itself does not seem to have been changed, so there must be a dependency update problem.

### Steps To Reproduce

```
 nix-shell -p mirage-im --run mirage
! 11:04:12 | QSystemTrayIcon::setVisible: No Icon set
~ 11:04:20 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 181, in <module>\n    BRIDGE = QMLBridge()\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 52, in __init__\n    from .backend import Backend\n\n  File \"qrc:/src/backend/backend.py\", line 28, in <module>\n    from .matrix_client import MatrixClient\n\n  File \"qrc:/src/backend/matrix_client.py\", line 42, in <module>\n    from .html_markdown import HTML_PROCESSOR as HTML\n\n  File \"qrc:/src/backend/html_markdown.py\", line 21, in <module>\n    class MarkdownInlineGrammar(mistune.InlineGrammar):\n\nAttributeError: module 'mistune' has no attribute 'InlineGrammar'\n"
! 11:04:20 | Unhandled PyOtherSide error: Cannot import module: backend.qml_bridge (Traceback (most recent call last):

  File "qrc:/src/backend/qml_bridge.py", line 181, in <module>
    BRIDGE = QMLBridge()

  File "qrc:/src/backend/qml_bridge.py", line 52, in __init__
    from .backend import Backend

  File "qrc:/src/backend/backend.py", line 28, in <module>
    from .matrix_client import MatrixClient

  File "qrc:/src/backend/matrix_client.py", line 42, in <module>
    from .html_markdown import HTML_PROCESSOR as HTML

  File "qrc:/src/backend/html_markdown.py", line 21, in <module>
    class MarkdownInlineGrammar(mistune.InlineGrammar):

AttributeError: module 'mistune' has no attribute 'InlineGrammar'
)
~ 11:04:20 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'BRIDGE' is not defined\n"
! 11:04:20 | Unhandled PyOtherSide error: Function not found: 'BRIDGE.call_backend_coro' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'BRIDGE' is not defined
)
```
The mirage window shows a loading symbol to the end of time.

### Screenshot

![image](https://user-images.githubusercontent.com/839693/212654677-7b0f83f5-9850-4fbf-bfbc-e59427dac41f.png)

### Expected behavior
Package is working

### Notify maintainers

@colemickens 
@AndersonTorres

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.86, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/hv5x852p5rzgzknmy5qkdcr7h39plqyv-7nj8by2g3m8ygqbb17gi31igkfhjayw8-source`
```

**Comment by colemickens** [comment]
Smells like the QML cache issue. Trying clearing out mirage/qml related looking things under `~/.cache`.

**Comment by symphorien** [comment]
The qml issue resulted in a segfault iirc. This just looks like dependencies were updated, and since mirage has been unmaintained upstream for more than a year, it broke. Maybe mirage should be removed from nixpkgs.

**Comment by colemickens** [comment]
>Maybe mirage should be removed from nixpkgs.

no argument from me.

**Comment by AndersonTorres** [comment]
Since mirage is now abandonware, it should be removed.
