### ISSUE TITLE
Build failure: libskk

### ISSUE THREAD

**Issue by turtton** [NixOS/nixpkgs#368530]
## Steps To Reproduce

1. build *libskk* on `nixpkgs-unstable`

## Build log

<details>

<summary>Build Log</summary>

```
candidate-list.c: In function 'skk_candidate_list_get_type':
/nix/store/y8fxzs8srzd6d74a85zbpssjr8wkj9q4-glib-2.82.1-dev/include/glib-2.0/glib/gmessages.h:671:16: error: returning 'void *' from a function with return type 'gboolean' {aka 'int'} makes integer from pointer without a cast [-Wint-conversion]
  671 |         return (val); \
      |
```

</details>

## Additional context

I tried to detect root cause using `git bisect` and git showed 880ce64860235b645eaed12c0ebbc8f13b7eea5a, but I could not unserstand the relation of this commit.

<details>

<summary>Tried commands</summary>

```shell
git clone --shallow-since "2024/12/17" --branch nixpkgs-unstable git@github.com:NixOS/nixpkgs.git libskk-search
cd libskk-search
git bisect start
git bisect bad
git bisect good 4989a246d7a390a859852baddb1013f825435cee
nix-build . -A libskk
...
```

Also I used `nix-tree` to search dependencies
`nix run nixpkgs#nix-tree -- --derivation /nix/store/wkrkfk8kcxbsq16mlyfazmsgjkw8kycj-libskk-1.0.5.drv`
</details>

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63-xanmod1, NixOS, 25.05 (Warbler), 25.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@yadokani389 @midchildan @natsukium 

Original maintainer account(yuriaisaka) looks removed from github

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
