### PR TITLE
linuxPackages_latest.broadcom_sta: add patch to compile on Kernel 6.12

### LINKED ISSUE #359375: Build failure: linuxPackages_latest.broadcom_sta
## Steps To Reproduce

1. build `linuxPackages_latest.broadcom_sta`

## Build log

<details>

<summary>Build Log</summary>

```
Running phase: configurePhase
no configure script, doing nothing
Running phase: buildPhase
build flags: SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash KBASE=/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1
KBUILD_NOPEDANTIC=1 make -C /nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/build M=`pwd`
make[1]: Entering directory '/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/build'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  CC [M]  /build/broadcom-sta/src/shared/linux_osl.o
  CC [M]  /build/broadcom-sta/src/wl/sys/wl_linux.o
/build/broadcom-sta/src/wl/sys/wl_linux.c:59:10: fatal error: asm/unaligned.h: No such file or directory
   59 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/source/scripts/Makefile.build:229: /build/broadcom-sta/src/wl/sys/wl_linux.o] Error 1
make[2]: *** [/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/source/Makefile:1936: /build/broadcom-sta] Error 2
make[1]: *** [/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/source/Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/build'
make: *** [Makefile:173: all] Error 2
error: builder for '/nix/store/w2wqw6ra75saj7f78n94zg8gk68lwyk1-broadcom-sta-6.30.223.271-6.12.1.drv' failed with exit code 2;
       last 25 log lines:
       > patching file src/wl/sys/wl_iw.c
       > applying patch /nix/store/6xlyf3j0nv4ai7771hf0kbwsvdjl6hmb-source/wl-kmod-026_kernel_6.10_fix_empty_body_in_if_warning.patch
       > patching file src/wl/sys/wl_linux.c
       > applying patch /nix/store/6xlyf3j0nv4ai7771hf0kbwsvdjl6hmb-source/wl-kmod-027_wpa_supplicant-2.11_add_max_scan_ie_len.patch
       > patching file src/wl/sys/wl_cfg80211_hybrid.c
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > build flags: SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash KBASE=/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1
       > KBUILD_NOPEDANTIC=1 make -C /nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/build M=`pwd`
       > make[1]: Entering directory '/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/build'
       > CFG80211 API is prefered for this kernel version
       > Using CFG80211 API
       >   CC [M]  /build/broadcom-sta/src/shared/linux_osl.o
       >   CC [M]  /build/broadcom-sta/src/wl/sys/wl_linux.o
       > /build/broadcom-sta/src/wl/sys/wl_linux.c:59:10: fatal error: asm/unaligned.h: No such file or directory
       >    59 | #include <asm/unaligned.h>
       >       |          ^~~~~~~~~~~~~~~~~
       > compilation terminated.
       > make[3]: *** [/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/source/scripts/Makefile.build:229: /build/broadcom-sta/src/wl/sys/wl_linux.o] Error 1
       > make[2]: *** [/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/source/Makefile:1936: /build/broadcom-sta] Error 2
       > make[1]: *** [/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/source/Makefile:224: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/69rmkmic4ifh9xbv6m23cxa8kp7l0328-linux-6.12.1-dev/lib/modules/6.12.1/build'
       > make: *** [Makefile:173: all] Error 2
       For full logs, run 'nix log /nix/store/w2wqw6ra75saj7f78n94zg8gk68lwyk1-broadcom-sta-6.30.223.271-6.12.1.drv'.
```

</details>

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.0, NixOS, 25.05 (Warbler), 25.05.20241119.23e89b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/run/current-system/nixpkgs`

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by j0hax**
Commit 5f60d5f6bbc1, part of Kernel 6.12, moves asm/unaligned.h to linux/unaligned.h. As a result we use a trivial patch from Manjaro which simply switches the include path if compiling for 6.12.

Closes #359375.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/os-specific/linux/broadcom-sta/default.nix [hunk 1]
```diff
@@ -66,7 +76,9 @@ stdenv.mkDerivation {
 
   nativeBuildInputs = kernel.moduleBuildDependencies;
 
-  patches = map (patch: "${rpmFusionPatches}/${patch}") patchset;
+  patches = map (patch: "${rpmFusionPatches}/${patch}") patchset ++ [
+    "${manjaro-patches}/017-linux612.patch"
```
Comment (dotlambda) [inline pkgs/os-specific/linux/broadcom-sta/default.nix:80]: Why not use `fetchpatch2` with https://gitlab.manjaro.org/packages/extra/broadcom-wl-dkms/-/raw/9675acde490a9cbc5eb93aacafc1295e0658a77c/017-linux612.patch ?

Comment (j0hax) [reply pkgs/os-specific/linux/broadcom-sta/default.nix]: Good idea. I also changed the URL from Manjaro's repository to a primary source (a Gist posted by the patch author).

**Review by dotlambda — APPROVED** [review]

**Comment by dotlambda** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359484`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.broadcom_sta</li>
    <li>linuxPackages_5_4_hardened.broadcom_sta</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 18 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.broadcom_sta</li>
    <li>linuxPackages_5_10_hardened.broadcom_sta (linuxKernel.packages.linux_5_10_hardened.broadcom_sta)</li>
    <li>linuxKernel.packages.linux_5_15.broadcom_sta</li>
    <li>linuxPackages_5_15_hardened.broadcom_sta (linuxKernel.packages.linux_5_15_hardened.broadcom_sta)</li>
    <li>linuxKernel.packages.linux_5_4.broadcom_sta</li>
    <li>linuxKernel.packages.linux_6_1.broadcom_sta</li>
    <li>linuxKernel.packages.linux_6_11.broadcom_sta</li>
    <li>linuxPackages_6_11_hardened.broadcom_sta (linuxKernel.packages.linux_6_11_hardened.broadcom_sta)</li>
    <li>linuxPackages_latest.broadcom_sta (linuxKernel.packages.linux_6_12.broadcom_sta)</li>
    <li>linuxPackages_6_1_hardened.broadcom_sta (linuxKernel.packages.linux_6_1_hardened.broadcom_sta)</li>
    <li>linuxPackages.broadcom_sta (linuxKernel.packages.linux_6_6.broadcom_sta)</li>
    <li>linuxPackages_hardened.broadcom_sta (linuxPackages_6_6_hardened.broadcom_sta)</li>
    <li>linuxPackages_latest-libre.broadcom_sta (linuxKernel.packages.linux_latest_libre.broadcom_sta)</li>
    <li>linuxPackages-libre.broadcom_sta (linuxKernel.packages.linux_libre.broadcom_sta)</li>
    <li>linuxPackages_lqx.broadcom_sta (linuxKernel.packages.linux_lqx.broadcom_sta)</li>
    <li>linuxPackages_xanmod.broadcom_sta (linuxKernel.packages.linux_xanmod.broadcom_sta)</li>
    <li>linuxPackages_xanmod_latest.broadcom_sta (linuxKernel.packages.linux_xanmod_latest.broadcom_sta ,linuxPackages_xanmod_stable.broadcom_sta)</li>
    <li>linuxPackages_zen.broadcom_sta (linuxKernel.packages.linux_zen.broadcom_sta)</li>
  </ul>
</details>
