### ISSUE TITLE
Broadcom-STA failed to build on linux kernel > 4.9 & nixos 17.03

### ISSUE THREAD

**Issue by Shamash2014** [NixOS/nixpkgs#27607]
## Issue description

Broadcom-sta wifi driver failed to build on linux kernel > 4.9

### Steps to reproduce

Just run `nixos-rebuid switch`, here is detailed stack trace: 
```
make[1]: Entering directory '/nix/store/qidc6n9jvfzz9jik83m2dv88b7zx76yl-linux-4.12.2-dev/lib/modules/4.12.2/build'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /tmp/nix-build-broadcom-sta-6.30.223.271-4.12.2.drv-0/broadcom-sta/built-in.o
  CC [M]  /tmp/nix-build-broadcom-sta-6.30.223.271-4.12.2.drv-0/broadcom-sta/src/shared/linux_osl.o
  CC [M]  /tmp/nix-build-virtualbox-modules-5.1.18-4.12.2.drv-0/virtualbox-5.1.18-modsrc/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /tmp/nix-build-virtualbox-modules-5.1.18-4.12.2.drv-0/virtualbox-5.1.18-modsrc/vboxdrv/SUPDrv.o
  CC [M]  /tmp/nix-build-broadcom-sta-6.30.223.271-4.12.2.drv-0/broadcom-sta/src/wl/sys/wl_linux.o
/tmp/nix-build-broadcom-sta-6.30.223.271-4.12.2.drv-0/broadcom-sta/src/wl/sys/wl_linux.c: In function 'wl_monitor':
/tmp/nix-build-broadcom-sta-6.30.223.271-4.12.2.drv-0/broadcom-sta/src/wl/sys/wl_linux.c:2920:10: error: 'struct net_device' has no member named 'last_rx'
  skb->dev->last_rx = jiffies;
          ^
make[4]: *** [/nix/store/qidc6n9jvfzz9jik83m2dv88b7zx76yl-linux-4.12.2-dev/lib/modules/4.12.2/source/scripts/Makefile.build:303: /tmp/nix-build-broadcom-sta-6.30.223.271-4.12.2.drv-0/broadcom-sta/src/wl/sys/wl_linux.o] Error 1
make[3]: *** [/nix/store/qidc6n9jvfzz9jik83m2dv88b7zx76yl-linux-4.12.2-dev/lib/modules/4.12.2/source/Makefile:1512: _module_/tmp/nix-build-broadcom-sta-6.30.223.271-4.12.2.drv-0/broadcom-sta] Error 2
make[2]: *** [Makefile:152: sub-make] Error 2
make[1]: *** [Makefile:24: __sub-make] Error 2
make[1]: Leaving directory '/nix/store/qidc6n9jvfzz9jik83m2dv88b7zx76yl-linux-4.12.2-dev/lib/modules/4.12.2/build'
make: *** [Makefile:161: all] Error 2
```

Hardware configuration line:

```
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  nix.maxJobs = lib.mkDefault 8;
}

```

## Technical details

* System: NixOS: `17.03.1584.48ecdcf598 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.11`
* Nixpkgs version: `17.03.1584.48ecdcf598`
* Sandboxing enabled: true

**Comment by Mic92** [comment]
Probably requires some backports from master like daf674491eab3e68a653308ba36f5e5005fd58a7 and c71233f12cb976b259e88ee4300687df26e5377d

**Comment by fpletz** [comment]
Fixed by backporting those two commits and testing build.
