### ISSUE TITLE
pkgsi686Linux.kexectools 2.0.20 fails to build

### ISSUE THREAD

**Issue by tadeokondrak** [NixOS/nixpkgs#68501]
The build for pkgsi686Linux.kexectools (a dependency of Wine) broke after 5abfb98d50f7ea6a5a15ed0373320e10d2d1c41b:

```c
kexec/arch/i386/kexec-x86.c:39:22: error: 'multiboot2_x86_probe' undeclared here (not in a function); did you mean 'multiboot_x86_probe'?
  { "multiboot2-x86", multiboot2_x86_probe, multiboot2_x86_load,
                      ^~~~~~~~~~~~~~~~~~~~
                      multiboot_x86_probe
kexec/arch/i386/kexec-x86.c:39:44: error: 'multiboot2_x86_load' undeclared here (not in a function); did you mean 'multiboot_x86_load'?
  { "multiboot2-x86", multiboot2_x86_probe, multiboot2_x86_load,
                                            ^~~~~~~~~~~~~~~~~~~
                                            multiboot_x86_load
kexec/arch/i386/kexec-x86.c:40:4: error: 'multiboot2_x86_usage' undeclared here (not in a function); did you mean 'multiboot_x86_usage'?
    multiboot2_x86_usage },
    ^~~~~~~~~~~~~~~~~~~~
    multiboot_x86_usage
```

Maintainer information:
```yaml
attribute: kexectools
```

**Comment by tadeokondrak** [comment]
I missed #68380
