### ISSUE TITLE
spoolman: fails to serve assets

### ISSUE THREAD

**Issue by Nothing4You** [NixOS/nixpkgs#556848]
### Nixpkgs version

- Stable (26.05)

### Describe the bug

Installing the spoolman service with default configuration simply fails to load.
Requests to paths under `/assets/` fail 

### Steps to reproduce

1. `services.spoolman.enable = true;`
2. Attempt to load http://127.0.0.1:7912/

### Expected behaviour

Spoolman loads normally

### Relevant log output

```console
uvicorn.access             INFO     127.0.0.1:43418 - "GET / HTTP/1.1" 200
uvicorn.access             INFO     127.0.0.1:43418 - "GET /config.js HTTP/1.1" 200
uvicorn.access             INFO     127.0.0.1:43434 - "GET /assets/index-CfEY3xBo.js HTTP/1.1" 500
uvicorn.error              ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "/nix/store/v10vgzfnr9rbqf97b0i3z27b0swa8y1p-python3.12-uvicorn-0.40.0/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 416, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/v10vgzfnr9rbqf97b0i3z27b0swa8y1p-python3.12-uvicorn-0.40.0/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/z8l5pykzwr1kmrh03p1y627r0g5gn1mk-python3.12-fastapi-0.136.3/lib/python3.12/site-packages/fastapi/applications.py", line 1159, in __call__
    await super().__call__(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/applications.py", line 90, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 29, in __call__
    await responder(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 130, in __call__
    await super().__call__(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 46, in __call__
    await self.app(scope, receive, self.send_with_compression)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/nix/store/z8l5pykzwr1kmrh03p1y627r0g5gn1mk-python3.12-fastapi-0.136.3/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/routing.py", line 660, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/routing.py", line 680, in app
    await route.handle(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/routing.py", line 448, in handle
    await self.app(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/staticfiles.py", line 98, in __call__
    response = await self.get_response(path, scope)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/staticfiles.py", line 132, in get_response
    return self.file_response(full_path, stat_result, scope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wrwxc5nysd7pwkh9h3ar16f4b5a28xdw-python3.12-spoolman-0.23.1/runpath/spoolman/client.py", line 62, in file_response
    response = FileResponse(full_path, status_code=status_code, stat_result=stat_result, method=method)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FileResponse.__init__() got an unexpected keyword argument 'method'
```

### Additional context

It seems like this is caused by #524412, which has breaking changes, like https://github.com/Kludex/starlette/pull/3147.
`starlette` is an indirect dependency via `fastapi`, but it's also directly used in `spoolman` code, despite not being explicitly defined.
According to the upstream PR for starlette, the argument was never used in the first place and had been deprecated for a long time.
`spoolman` has since updated its dependencies in [v0.24.0](https://github.com/Donkie/Spoolman/releases/tag/v0.24.0), the specific commit fixing this issue is https://github.com/Donkie/Spoolman/commit/d9fd44eab95b6dc6c6ded6b6ff69063437dc0735.

The update to a newer spoolman version (#550183) is blocked by a different dependency issue, [`inline-snapshot`](https://github.com/NixOS/nixpkgs/issues/550183#issuecomment-5294351499).

If updating spoolman directly is not achievable short term, it would help to at least backport part of the spoolman commit changing the python code to stop passing the deprecated `method` parameter.

### System metadata

 - system: `"aarch64-linux"`
 - host os: `Linux 6.18.46, NixOS, 26.05 (Yarara), 26.05.20260825.f4f6986`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.8`
 - nixpkgs: `/nix/store/pspa3balgpvp6p7vfm8f9yqvmi5gsfyc-source`

### Notify maintainers

@MayNiklas @pinpox

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
