### PR TITLE
libplacebo: fix building with shaderc 2020.2

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

This fixes a regression introduced by #94049.

>     builder for '/nix/store/86lrf5m4vy9r4hbwm6r95ljv6w0pwi4d-libplacebo-2.72.0.drv' failed with exit code 1; last 10 log lines:
>       build flags: -j128 -l128
>       [42/44] Compiling C++ object 'src/25a6634@@placebo@sha/glsl_glslang.cc.o's_gen.c.o'
>       FAILED: src/25a6634@@placebo@sha/glsl_glslang.cc.o
>       g++ -Isrc/25a6634@@placebo@sha -Isrc -I../src -I../src/include -I../src/include/dummy -I../subprojects/xtalloc/include -I../subprojects/bstr/include -I/nix/store/81iy20n5rhvcm18ha289anygpgq5qyjc-lcms2-2.11-dev/include -I/nix/store/riw48ysh0rhkf2fck7m1iiany4rif2mv-vulkan-headers-1.2.141.0/include -I/nix/store/psda85jw38cxzqp6fa59vrdipz67h6bk-epoxy-1.5.4-dev/include -I/usr/include/glslang -I/nix/store/my4bdsgi308bq216gkhfwnwnk35yhszn-libplacebo-2.72.0/include/glslang -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -Wundef -Wshadow -Wparentheses -Wpointer-arith -fvisibility=hidden -fPIC -pthread -MD -MQ 'src/25a6634@@placebo@sha/glsl_glslang.cc.o' -MF 'src/25a6634@@placebo@sha/glsl_glslang.cc.o.d' -o 'src/25a6634@@placebo@sha/glsl_glslang.cc.o' -c ../src/glsl/glslang.cc
>       ../src/glsl/glslang.cc:229:1: error: cannot convert '<brace-enclosed initializer list>' to 'int' in initialization
>         229 | };
>             | ^

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 100818` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>celluloid (gnome-mpv)</li>
    <li>curseradio</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>libplacebo</li>
    <li>minitube</li>
    <li>mpc-qt</li>
    <li>mpv (mpv-with-scripts)</li>
    <li>mpv-unwrapped</li>
    <li>mpvScripts.mpris</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>python37Packages.mpv</li>
    <li>python38Packages.mpv</li>
    <li>qimgv</li>
    <li>shaderc</li>
    <li>somafm-cli</li>
    <li>sublime-music</li>
    <li>tuijam</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 100818` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>celluloid (gnome-mpv)</li>
    <li>curseradio</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>libplacebo</li>
    <li>minitube</li>
    <li>mpc-qt</li>
    <li>mpv (mpv-with-scripts)</li>
    <li>mpv-unwrapped</li>
    <li>mpvScripts.mpris</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>python37Packages.mpv</li>
    <li>python38Packages.mpv</li>
    <li>qimgv</li>
    <li>somafm-cli</li>
    <li>sublime-music</li>
    <li>tuijam</li>
  </ul>
</details>

**Review by primeos — APPROVED** [review]
Interesting, seems like shaderc/glslang updates can cause quite a mess... :o (not sure if we reverted glslang or they broke their API again to revert the original breakage...)

Anyway, thanks for the fix! :heart:
