### PR TITLE
zeroad: 0.0.23b -> 0.0.24b

### PR DESCRIPTION
**Pull request by nagy**
###### Motivation for this change
This unbreaks and updates the game but it depends on #114030 .
More on why that patch to spidermonkey is needed can be read here: 
https://wildfiregames.com/forum/topic/33893-spidermonkey-68-78-upgrade/

Once that PR has been merged, I will unmark the draft status of this. Any automatic build will likely fail but that should resolve once that has been merged.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114031` at abeb2bc5 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zeroad</li>
  </ul>
</details>

File: pkgs/games/0ad/data.nix [hunk 1]
```diff
@@ -6,11 +6,13 @@ stdenv.mkDerivation rec {
...
     url = "http://releases.wildfiregames.com/0ad-${version}-alpha-unix-data.tar.xz";
-    sha256 = "04x7729hk6zw1xj3n4s4lvaviijsnbjf5rhzvjxlr5fygvg4l6z1";
+    sha256 = "0nnpzn0l2sw7z9bwgg6vacip6blahxsk6m90znvl7hb3mak5b6lj";
   };
 
+  sourceRoot = ".";
+
   installPhase = ''
-    rm binaries/data/tools/fontbuilder/fonts/*.txt
+    rm -f binaries/data/tools/fontbuilder/fonts/*.txt
```
Comment (SuperSandro2000) [inline pkgs/games/0ad/data.nix:15]: Please remove the -f or the line if it no longer applies.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]

**Review by chvp — CHANGES_REQUESTED** [review]
I had to add a `sourceRoot = ".";` to `0ad/data.nix` to make this work. Also, did you check whether this version of 0ad builds with gcc10? The stdenv was set to gcc9 manually when the default changed because 0.0.23 didn't with build with 10, but I would assume that that isn't the case for 0.0.24.

**Comment by nagy** [comment]
> I had to add a `sourceRoot = ".";` to `0ad/data.nix` to make this work.
What do you mean? This is added in line 12 of the file.

> Also, did you check whether this version of 0ad builds with gcc10? The stdenv was set to gcc9 manually when the default changed because 0.0.23 didn't with build with 10, but I would assume that that isn't the case for 0.0.24.
I did not. But once the spidermonkey PR is merged I have to review this again, then i will test gcc10.

**Comment by chvp** [comment]
> What do you mean? This is added in line 12 of the file.

Oh, I'm blind apparently. Sorry about the noise.

**Comment by mfsch** [comment]
There’s also a slightly newer release "Alpha 24b" on the [download page](https://releases.wildfiregames.com/). I couldn’t find any info on what has been changed with respect to the first "Alpha 24" release, but it’s probably a good idea to update to the latest version.

Also, when I wrote my own derivation for this new Alpha, I had to change `wxGTK` to `wxGTK31` since I got an error that only wxWidgets >= 3.0 was supported, but apparently it is working with v2.8 for you?

Finally, is it a good idea to remove the patch for the minor version check? From what I understand, that would mean that any update of `spidermonkey_78` to a version != 78.6 would break the 0 A.D. build.

**Comment by nagy** [comment]
> Also, when I wrote my own derivation for this new Alpha, I had to change `wxGTK` to `wxGTK31` since I got an error that only wxWidgets >= 3.0 was supported, but apparently it is working with v2.8 for you?

I was able to get the game started. I did not test much further than that. Do you get a compilation error ?

> Finally, is it a good idea to remove the patch for the minor version check? From what I understand, that would mean that any update of `spidermonkey_78` to a version != 78.6 would break the 0 A.D. build.

I have something prepared for that.

**Comment by chvp** [comment]
I played two games last night using this pull request, so I did not have problems with wxGTK.

**Comment by nagy** [comment]
> There’s also a slightly newer release "Alpha 24b" on the [download page](https://releases.wildfiregames.com/). I couldn’t find any info on what has been changed with respect to the first "Alpha 24" release, but it’s probably a good idea to update to the latest version.
 
This here is the change between the two versions: https://github.com/0ad/0ad/compare/A24...A24b
Looks mostly like language updates but it should not hurt to update to that.

File: pkgs/games/0ad/data.nix (hunk 1 above)
Comment (SuperSandro2000) [reply pkgs/games/0ad/data.nix:15]:
```suggestion
    rm binaries/data/tools/fontbuilder/fonts/*.txt
```

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]

**Comment by nagy** [comment]
The spidermonkey PR has since been merged (into staging). However it is not the exact same version that 0ad requires. Therefore I had to put in a little workaround to that. We are now building a new derivation of spidermonkey with a patched `src` attribute. Without this, we get compilation errors.

0ad also ships with this version of spidermonkey, however I would prefer the current way of doing it over building the shipped version of spidermonkey, because this way we do not need to redeclare all of spidermonkeys dependencies in this derivation.

Because spidermonkey has still not arrived in master, any automatic build will fail again. I am however removing the draft status of this, since the problem should resolve once it hits master.

File: pkgs/games/0ad/game.nix [hunk 2]
```diff
@@ -1,65 +1,65 @@
...
 
   NIX_CFLAGS_COMPILE = toString [
     "-I${xorgproto}/include/X11"
     "-I${libX11.dev}/include/X11"
     "-I${libXcursor.dev}/include/X11"
     "-I${SDL2}/include/SDL2"
-  ];
-
-  patches = [
-    ./rootdir_env.patch
```
Comment (chvp) [inline pkgs/games/0ad/game.nix:37]: You should probably also remove this file from the repository if the patch isn't necessary anymore.

File: pkgs/games/0ad/game.nix [hunk 3]
```diff
@@ -1,65 +1,65 @@
...
 
-assert withEditor -> wxGTK != null;
-
+# You can find more instructions on how to build 0ad here:
+#    https://trac.wildfiregames.com/wiki/BuildInstructions
+
+let
+  # the game requires a special version 78.6.0 of spidermonkey, otherwise
+  # we get compilation errors. We override the src attribute of spidermonkey_78
+  # in order to reuse that declartion, while giving it a different source input.
```
Comment (chvp) [inline pkgs/games/0ad/game.nix:15]: I wonder if this is the correct solution. The second patch in the derivation for 0.0.23b removed the minor version check, so maybe that's the correct solution here as well.

**Review by chvp — CHANGES_REQUESTED** [review]

File: pkgs/games/0ad/game.nix (hunk 3 above)
Comment (nagy) [reply pkgs/games/0ad/game.nix:15]: No, i tried to remove that check already and it gives a compilation error.

File: pkgs/games/0ad/game.nix (hunk 2 above)
Comment (nagy) [reply pkgs/games/0ad/game.nix:37]: You are right. Thank you.

**Comment by mfsch** [comment]
> > Also, when I wrote my own derivation for this new Alpha, I had to change `wxGTK` to `wxGTK31` since I got an error that only wxWidgets >= 3.0 was supported, but apparently it is working with v2.8 for you?
> 
> I was able to get the game started. I did not test much further than that. Do you get a compilation error ?

I just saw that this is done in `all-packages.nix`.

File: pkgs/games/0ad/game.nix (hunk 3 above)
Comment (mfsch) [reply pkgs/games/0ad/game.nix:15]: The [Fedora patch](https://src.fedoraproject.org/rpms/0ad/raw/26dc1657f6e3c0ad9f1180ca38cd79b933ef0c8b/f/0ad-mozjs-incompatible.patch) contains two changes – if you remove the second change, which seems no longer necessary, and perhaps fix the line numbers to `@@ -81,19 +81,6 @@` it does apply. But I tend to agree that your solution of overriding the `spidermonkey_78` version is better, since 78.6 is the version that is tested.

**Comment by chvp** [comment]
The spidermonkey change necessary for this PR was merged to master a few hours ago.

**Comment by chvp** [comment]
I was able to fix the build error by adding the following patch to the spidermonkey_78_6 derivation: https://github.com/chvp/nixpkgs/blob/a1a03554af1186669a645609e25a9476f267280b/pkgs/games/0ad/spidermonkey-cargo-toml.patch

**Comment by nagy** [comment]
@chvp thanks for the patch. I can happily apply it, but i would also like to understand why this is only needed for the `78.6.0` version and not the `78.8.0` one. Do you happen to know why ?

**Comment by chvp** [comment]
The `branch`, `tag` or `rev` uniqueness requirement was added in cargo 1.50 (which was also part of this staging cycle, AFAICT): https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-150-2021-02-11
The tarball for 78.8.0 contains a compliant Cargo.toml, the tarball for 78.6.0 doesn't.

**Comment by nagy** [comment]
Updated. It builds for me locally as well.

**Review by chvp — APPROVED** [review]
Started a game using this exact patch, and I've played at least 10 games using some version of this patch over the past few weeks.

File: pkgs/games/0ad/game.nix [hunk 4]
```diff
@@ -1,65 +1,68 @@
...
   src = fetchurl {
     url = "http://releases.wildfiregames.com/0ad-${version}-alpha-unix-build.tar.xz";
-    sha256 = "0draa53xg69i5qhqym85658m45xhwkbiimaldj4sr3703rjgggq1";
+    sha256 = "1a1py45hkh2cswi09vbf9chikgxdv9xplsmg6sv6xhdznv4j6p1j";
   };
 
   nativeBuildInputs = [ python2 perl pkg-config ];
 
   buildInputs = [
-    spidermonkey_38 boost icu libxml2 libpng libjpeg
```
[the remark this answers is not in the document]
Comment (nagy) [reply pkgs/games/0ad/game.nix:23]: https://github.com/NixOS/nixpkgs/pull/117092
