### PR TITLE
postgresqlPackages.timescaledb_toolkit 1.14.0 -> 1.16.0

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

simple extension update

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 231265` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>postgresql11JitPackages.timescaledb_toolkit</li>
    <li>postgresql11Packages.timescaledb_toolkit</li>
    <li>postgresqlJitPackages.timescaledb_toolkit (postgresql14JitPackages.timescaledb_toolkit)</li>
    <li>postgresql14Packages.timescaledb_toolkit</li>
    <li>postgresql15JitPackages.timescaledb_toolkit</li>
    <li>postgresql15Packages.timescaledb_toolkit</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>postgresql12JitPackages.timescaledb_toolkit</li>
    <li>postgresql12Packages.timescaledb_toolkit</li>
    <li>postgresql13JitPackages.timescaledb_toolkit</li>
    <li>postgresql13Packages.timescaledb_toolkit</li>
  </ul>
</details>

**Comment by happysalada** [comment]
I've tried building timescaledb_toolkit for pg15 and 14 in the same nixshell given to me by the nixpkgs-review and I can confirm that they both built, the failures seem to be a result of the multiple builds at the same time.

**Comment by happysalada** [comment]
I'm going to merge as I don't think this is a big deal.
Feel free to let me know though if you think I you feel I'm rushing things.

**Comment by 06kellyjac** [comment]
There's lots of failures on darwin:

https://zh.fail/failed/by-maintainer/typetetris.html

**Comment by happysalada** [comment]
indeed those are failing, I didn't expect this dependency to be used much on darwin, but I could be wrong.
The error is ` ld: symbol(s) not found for architecture x86_64`
I have never been able to figure out this error.
Do you prefer to revert this change ?

**Comment by 06kellyjac** [comment]
Yeah same for aarch64. The upstream repo say they regularly check it on darwin but I don't see any evidence of that.

Personally I don't mind either way between marking broken on darwin or reverting (as long as `1.14.0` still builds fine on darwin)

Might also be worth reaching out to upstream to work out why this is happening?

**Comment by typetetris** [comment]
I doubt 1.14.0 would build on those platforms, if 1.16.0 doesn't build.

As those aren't cross compilations (which pgrx doesn't really support yet), I really don't know what is going wrong.

Maybe something is wrong with pgx-pg-sys and it's bindgen usage ... but I really don't know.

`nix build nixpkgs#legacyPackages.x86_64-darwin.postgresql_15` downloads postgresql_15 darwin build for me and
its headers seem to mention the symbols, which are reported as missing in the error message.

Someone with more darwin knowledge and a darwin machine might be able to debug this?

**Comment by happysalada** [comment]
PR to mark it broken on darwin https://github.com/NixOS/nixpkgs/pull/234087
(that would be my opinion. I'm on darwin, so I'm very much on the darwin bandwagon, but it doesn't seem to make much sense here as this is something that would be run on a server most likely).
