### ISSUE TITLE
postgresqlPackages.age fails to build: error: void value not ignored as it ought to be

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#142427]
Hydra also sees the failure: https://hydra.nixos.org/build/155845961

```
src/backend/catalog/ag_graph.c:67:15: error: void value not ignored as it ought to be
   67 |     graph_oid = CatalogTupleInsert(ag_graph, tuple);
      |               ^
```

Probably an API drift of the dependency?

### Notify maintainers

None.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: postgresqlPackages.age
```

**Comment by trofi** [comment]
Bisected regression down to 5870dfba88f173dc1e5487483ba0477dedc0ca45 `postgresql: use postgresql_13 instead of postgresql_11`..

- postgresql11Packages.age: succeeds
- postgresql12Packages.age: fails
- postgresql13Packages.age: fails

**Comment by trofi** [comment]
Closing as INVALID
