### ISSUE TITLE
Build failure: whois (on Darwin)

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#260552]
### Steps To Reproduce

1. build `whois` on darwin on nixos-unstable

### Build log

See https://hydra.nixos.org/build/237625043/nixlog/1

Relevant bit:

```
./utils.h:62:7: error: 'malloc' attribute takes no arguments
void *MALLOC_FREE NONNULL do_nofail(void *ptr, const char *file, const int line)
      ^
./utils.h:20:37: note: expanded from macro 'MALLOC_FREE'
# define MALLOC_FREE __attribute__((malloc(free)))
```

### Additional context

Failing due to https://github.com/NixOS/nixpkgs/pull/259969

Appears to be due to [this upstream change](https://github.com/rfc1036/whois/compare/v5.5.18...v5.5.19#diff-a00a459441a1c86324aacc5bdbb53461d439d2af337849915891aa3dc281936e). Though it’s not clear to me why it appears that `__GNUC__` is defined when using clang.

### Notify maintainers

@fpletz 

### Metadata

Hydra, can replicate locally.

**Comment by montchr** [comment]
I am also encountering this same build failure.

**Comment by mirkolenz** [comment]
Also happened to me with the package `mkpasswd` on `x86_64-darwin`. The Hydra job is also failing: https://hydra.nixos.org/job/nixpkgs/trunk/mkpasswd.x86_64-darwin
