### ISSUE TITLE
ati-drivers does not build with kernel 4.6

### ISSUE THREAD

**Issue by jerith666** [NixOS/nixpkgs#18202]
## Issue description

Two compilation errors are seen.  I have a fix at https://github.com/jerith666/nixpkgs/commit/a629947313995a1554d20a3f203fbd10b91f9afc, but I expect that it needs to be variablized to only apply these two new patches if building against a 4.6 (or greater) kernel, and I don't know how to do that.

add'l keywords: ati_unfree

**Comment by jerith666** [comment]
Compiler output:

```
/tmp/nix-build-ati-drivers-15.12-4.6.7.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c:3245:11: error: too many arguments to function 'get_user_pages'
     ret = get_user_pages(current, current->mm, vaddr, page_cnt, 0, 0, (struct page **)page_list, NULL);
           ^
In file included from /nix/store/jkp1xn8ma57pi0jzfblf4fmfi9nbbjlp-linux-4.6.7-dev/lib/modules/4.6.7/source/include/linux/scatterlist.h:7:0,
                 from /nix/store/jkp1xn8ma57pi0jzfblf4fmfi9nbbjlp-linux-4.6.7-dev/lib/modules/4.6.7/source/include/linux/dmapool.h:14,
                 from /nix/store/jkp1xn8ma57pi0jzfblf4fmfi9nbbjlp-linux-4.6.7-dev/lib/modules/4.6.7/source/include/linux/pci.h:1242,
                 from /tmp/nix-build-ati-drivers-15.12-4.6.7.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c:119:
/nix/store/jkp1xn8ma57pi0jzfblf4fmfi9nbbjlp-linux-4.6.7-dev/lib/modules/4.6.7/source/include/linux/mm.h:1266:6: note: declared here
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
/tmp/nix-build-ati-drivers-15.12-4.6.7.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c: In function 'KCL_UnlockUserPages':
/tmp/nix-build-ati-drivers-15.12-4.6.7.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c:3256:9: error: implicit declaration of function 'page_cache_release' [-Werror=implicit-function-declaration]
         page_cache_release((struct page*)page_list[i]);
         ^
```

**Comment by vcunat** [comment]
You can add a simple conditional, e.g. similar to https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/perf.nix#L19

**Comment by jerith666** [comment]
Excellent, thanks for the pointer!  Reworked and created a pull req.
