### PR TITLE
python310Packages.onlykey-solo-python: fix compatibility with fido2 1.1.3

### LINKED ISSUE #253127: onlykey-cli crashing due to new fido2 version not supported by onlykey-solo-python package
### Describe the bug
I tried to run `onlykey-cli` and it crashes on commands like `onlykey-cli credential ls`

### Steps To Reproduce
1. `nix shell nixpkgs#onlykey-cli`
2. `onlykey-cli credential ls`
3. 
```shell
PIN: 
Traceback (most recent call last):
  File "/nix/store/3akrqg5nnkwlfsffw92j7m4v5apiwiv0-onlykey-cli-1.2.9/bin/.onlykey-cli-wrapped", line 9, in <module>
    sys.exit(main())
    
    ...
    
  File "/nix/store/vywnxqfbry5cwmkfhlklmp8rk5cc1nnd-python3.10-onlykey-solo-python-0.0.32/lib/python3.10/site-packages/solo/devices/base.py", line 116, in cred_mgmt
    token = client.client_pin.get_pin_token(pin)
AttributeError: 'Fido2Client' object has no attribute 'client_pin'

```

### Expected behavior
The program works as intended

### Screenshots
Example of error is in "Steps To Reproduce"

### Additional context
https://github.com/NixOS/nixpkgs/blob/aa8aa7e2ea35ce655297e8322dc82bf77a31d04b/pkgs/development/python-modules/onlykey-solo-python/default.nix#L24-L34
I noticed that `onlykey-solo-python` python package in nixpkgs is patched to work with `fido2` package newer than 0.9.3 but it seems that at some point the compatibility broke again. Maybe new patch is needed or `fido2` package should be locked to the version that patch supports.

### Notify maintainers

@dotlambda @mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.49, NixOS, 23.11 (Tapir), 23.11.20230830.e7f38be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by kalbasit**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

Use @Lgmrszd 's upstream fix.

fixes #253127

### CODE REVIEW

**Review by NickCao — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354382`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>onlykey-agent</li>
    <li>onlykey-agent.dist</li>
    <li>onlykey-cli</li>
    <li>onlykey-cli.dist</li>
    <li>python311Packages.onlykey-solo-python</li>
    <li>python311Packages.onlykey-solo-python.dist</li>
    <li>python312Packages.onlykey-solo-python</li>
    <li>python312Packages.onlykey-solo-python.dist</li>
  </ul>
</details>
