### PR TITLE
yosys-synlig: 2023-11-28 -> 2024-03-13

### PR DESCRIPTION
**Pull request by hzeller**
This includes a workaround to yosys API changes since 0.36

Preparation to make it possible to upgrade Yosys #297531

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hzeller** [comment]
This should help at least Yosys 0.36 -> 0.37 compatibility (for this there was a patch before, but that is not changed upstream in synlig).
If there is another change needed for 0.37 -> 0.38 then at least this will be a good starting point.

**Comment by hzeller** [comment]
ok, confirmed, that synlig will still not work with 0.38. Will file an synlig issue.

**Comment by risicle** [comment]
Fails to build on macos 12 x86_64:

```
clang++  -I/nix/store/q3k0yck17pcnynp9icjj10nr6mxg0wfp-yosys-0.38/share/yosys/include -I/private/tmp/nix-build-yosys-synlig-2024-03-13.drv-0/source/third_party/yosys_mod/ -D_YOSYS_ -DYOSYS_ENABLE_PLUGINS -pthread -I/nix/store/96vql7hrr4bvigis64idfpaj50xiga17-capnproto-1.0.2/include -I/nix/store/r8gdnp73v673lklnh10m5p9k1w7br4a9-s>
/private/tmp/nix-build-yosys-synlig-2024-03-13.drv-0/source/frontends/systemverilog/uhdm_common_frontend.cc:180:9: error: too few arguments to function call, expected 23, have 22
        );
        ^

```
