### PR TITLE
jbofihe: fix build with gcc14, modernize

### PR DESCRIPTION
**Pull request by ghpzin**
jbofihe: fix build with gcc14

- add patch fixing gcc14 errors:
`implicit-int`:
```
rpc_tab.c:1:8: error: type defaults to 'int' in declaration of
'elide_trace_reduce' [-Wimplicit-int]
    1 | extern elide_trace_reduce(int, int);
      |        ^~~~~~~~~~~~~~~~~~
rpc_tab.c:2:8: error: type defaults to 'int' in declaration of
'elide_trace_shift' [-Wimplicit-int]
    2 | extern elide_trace_shift(int,int);
      |        ^~~~~~~~~~~~~~~~~
rpc_tab.c:3:8: error: type defaults to 'int' in declaration of
'report_trace_shift' [-Wimplicit-int]
    3 | extern report_trace_shift(int);
      |        ^~~~~~~~~~~~~~~~~~
rpc_tab.c:4:8: error: type defaults to 'int' in declaration of
'report_trace_reduce' [-Wimplicit-int]
    4 | extern report_trace_reduce(int, int);
      |        ^~~~~~~~~~~~~~~~~~~
rpc_tab.c:5:8: error: type defaults to 'int' in declaration of
'report_trace_error' [-Wimplicit-int]
    5 | extern report_trace_error(short *yyss, short *yyssp);
      |        ^~~~~~~~~~~~~~~~~~
```

`implicit-function-declaration`:
```
parse.tab.c: In function 'yyparse':
parse.tab.c:1148:16: error: implicit declaration of function 'yylex'
[-Wimplicit-function-declaration]
 1148 |       yychar = yylex ();
      |                ^~~~~

parse.tab.c:1595:7: error: implicit declaration of function 'yyerror';
did you mean 'yyerrok'? [-Wimplicit-function-declaration]
 1595 |       yyerror (YY_("syntax error"));
      |       ^~~~~~~
      |       yyerrok

n2d.c: In function 'main':
n2d.c:1529:12: error: implicit declaration of function 'yyparse'
[-Wimplicit-function-declaration]
 1529 |   result = yyparse();
      |            ^~~~~~~
```
---

jbofihe: modernize

- replace `rec` with `finalAttrs`
- remove `with lib;` from `meta`

---

Fixes build failure of `jbofihe` since update to GCC 14 in #356812:
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.jbofihe.x86_64-linux
https://hydra.nixos.org/build/293018015

Log:
```text
rpc_tab.c:1:8: error: type defaults to 'int' in declaration of 'elide_trace_reduce' [-Wimplicit-int]
    1 | extern elide_trace_reduce(int, int);
      |        ^~~~~~~~~~~~~~~~~~
rpc_tab.c:2:8: error: type defaults to 'int' in declaration of 'elide_trace_shift' [-Wimplicit-int]
    2 | extern elide_trace_shift(int,int);
      |        ^~~~~~~~~~~~~~~~~
rpc_tab.c:3:8: error: type defaults to 'int' in declaration of 'report_trace_shift' [-Wimplicit-int]
    3 | extern report_trace_shift(int);
      |        ^~~~~~~~~~~~~~~~~~
rpc_tab.c:4:8: error: type defaults to 'int' in declaration of 'report_trace_reduce' [-Wimplicit-int]
    4 | extern report_trace_reduce(int, int);
      |        ^~~~~~~~~~~~~~~~~~~
rpc_tab.c:5:8: error: type defaults to 'int' in declaration of 'report_trace_error' [-Wimplicit-int]
    5 | extern report_trace_error(short *yyss, short *yyssp);
      |        ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:54: rpc_tab.o] Error 1
```

After applying first part of the patch, error becomes:
```text
parse.tab.c: In function 'yyparse':
parse.tab.c:1148:16: error: implicit declaration of function 'yylex' [-Wimplicit-function-declaration]
 1148 |       yychar = yylex ();
      |                ^~~~~
parse.tab.c:1595:7: error: implicit declaration of function 'yyerror'; did you mean 'yyerrok'? [-Wimplicit-function-declaration]
 1595 |       yyerror (YY_("syntax error"));
      |       ^~~~~~~
      |       yyerrok
make[1]: *** [<builtin>: parse.tab.o] Error 1
make[1]: Leaving directory '/build/source/dfasyn'
make: *** [Makefile:148: dfasyn/dfasyn] Error 2
```

After fixing declarations of `yylex` and `yyerror`:
```text
n2d.c: In function 'main':
n2d.c:1529:12: error: implicit declaration of function 'yyparse' [-Wimplicit-function-declaration]
 1529 |   result = yyparse();
      |            ^~~~~~~
make[1]: *** [<builtin>: n2d.o] Error 1
make[1]: Leaving directory '/build/source/dfasyn'
make: *** [Makefile:148: dfasyn/dfasyn] Error 2
```
With full patch (`yyparse` declaration on top of other things) builds fine.

Tracking issue: #388196 

Made PR upstream with fixes (unlikely to get merged, last commit was 4 years ago): https://github.com/lojban/jbofihe/pull/19

---

Checked that it runs with test output from repo README (appears to work as intended):
```text
echo "mi klama le zarci" | ./result/bin/jbofihe -x -b

[ ( mi                )            << klama  >> ( le
[ ( I, me             ) [is, does] << go-ing >> ( the
[ ( klama1 (go-er(s)) )            <<        >> ( klama2 (destination(s))
1 2                   2            3         3  4

zarci            ) ]
trading place(s) ) ]
                 ) ]
                 4 1
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ghpzin** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 395240`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>jbofihe</li>
  </ul>
</details>

**Review by Sigmanificient — APPROVED** [review]
