### PR TITLE
onnxruntime: fix cuda build

### LINKED ISSUE #546608: Build failure: firefox -> onnxruntime
### Nixpkgs version

- Stable (26.05)

### Steps to reproduce

build with cuda support

### Can Hydra reproduce this build failure?

No, Hydra cannot reproduce this build failure.

### Link to Hydra build job

_No response_

### Relevant log output

```console
first build

┃          nix log /nix/store/0x9zpfqd7ili9n4fhskx99cdicap5zbs-cuda12.9-cudnn-frontend-1.25.0.drv
┣━ Dependency Graph:
┃                         ┌─ ⏵ cuda12.9-cudnn-frontend-1.25.0 (configurePhase)
┃                      ┌─ ⏸️ onnxruntime-1.27.1
┃                   ┌─ ⏸️ firefox-unwrapped-153.0
┃                ┌─ ⏸️ firefox-153.0



second build

chromium-unwrapped> [38233/56386] CXX obj/content/browser/browser/push_messaging_router.o
onnxruntime> make[1]: *** [CMakeFiles/Makefile2:1508: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
onnxruntime> make: *** [Makefile:146: all] Error 2
error: Cannot build '/nix/store/q7g5fw4dh579mzggpkdbgvf8gz0bq488-onnxruntime-1.27.1.drv'.
       Reason: builder failed with exit code 2.
       Output paths:
         /nix/store/2ylsvy3ks7cbx1qjbjwhyxizz4nx7w62-onnxruntime-1.27.1-debug
         /nix/store/6ppkbra2rjbjvvb6jrl1lpz8qzafkz7z-onnxruntime-1.27.1-dist
         /nix/store/h583qb7lr4jaaxq0fhaqr01ifnqcdwin-onnxruntime-1.27.1-dev
         /nix/store/m0dbz47gr5vnqhqafyygpnxs0ssisl8r-onnxruntime-1.27.1
       Last 25 log lines:
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/bert/tensorrt_fused_multihead_attention/fused_multihead_attention_v2_fp16_96_32_kernel.sm80.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/bert/tensorrt_fused_multihead_attention/fused_multihead_attention_v2_fp16_96_64_kernel.sm70.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/bert/tensorrt_fused_multihead_attention/fused_multihead_attention_v2_fp16_96_64_kernel.sm75.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/bert/tensorrt_fused_multihead_attention/fused_multihead_attention_v2_fp16_96_64_kernel.sm80.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/bert/tensorrt_fused_multihead_attention/fused_multihead_attention_v2_fp16_96_64_kernel.sm86.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/bert/transformer_common.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/distributed_expand.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/distributed_matmul.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/distributed_reduce.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/distributed_reshape.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/distributed_slice.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/distributed_squeeze.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/distributed_unsqueeze.cc.o
       > [ 88%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/ipc_utils.cc.o
       > [ 89%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/nccl_kernels.cc.o
       > [ 89%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/sharded_moe.cc.o
       > In file included from /build/source/onnxruntime/contrib_ops/cuda/collective/sharded_moe.cc:10:
       > /build/source/onnxruntime/contrib_ops/cuda/collective/sharded_moe.h:6:10: fatal error: contrib_ops/cuda/moe/ft_moe/moe_kernel.h: No such file or directory
       >     6 | #include "contrib_ops/cuda/moe/ft_moe/moe_kernel.h"
       >       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > compilation terminated.
       > make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:5365: CMakeFiles/onnxruntime_providers_cuda.dir/build/source/onnxruntime/contrib_ops/cuda/collective/sharded_moe.cc.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:1508: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
       > make: *** [Makefile:146: all] Error 2
       For full logs, run:
         nix log /nix/store/q7g5fw4dh579mzggpkdbgvf8gz0bq488-onnxruntime-1.27.1.drv
error: Cannot build '/nix/store/izd81765j7k559mfb7sa35a1p534x952-firefox-unwrapped-153.0.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/dh53idqv7zm1gkjw7xgld2m855z8rwyx-firefox-unwrapped-153.0-debug
         /nix/store/g4v2mlbgs219msxw4r6y9cqrk5g8a0xg-firefox-unwrapped-153.0
         /nix/store/mkk61i35qi475j9m6y4lhlg7yhwfhab5-firefox-unwrapped-153.0-symbols
error: Build failed due to failed dependency
error: Cannot build '/nix/store/s0b22j26nczsi2qbx0knkv2gkwz30jv2-firefox-153.0.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/7d6lsjmri23ppr95vic3kv29risj9zjd-firefox-153.0
error: Cannot build '/nix/store/875qfrdd3f2m2bddc5cm1sbg083zma4r-home-manager-path.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/6a8rzhk3fffb8dkyzhfnkk22271jxbd4-home-manager-path
error: Cannot build '/nix/store/bm42yahzbqfi6afp5pg63m2jgrniwgps-hm_fontconfigconf.d10hmfonts.conf.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/3ajl958hh2v6k98fs9rqj7v7v0qp6ssj-hm_fontconfigconf.d10hmfonts.conf
error: Cannot build '/nix/store/r3sdckikghd7cn9pmxy3almk74mhax3x-home-manager-generation.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/cbd9cy7cpvlm2w2520zgdpcha7x8sfdn-home-manager-generation
error: Cannot build '/nix/store/xfk9ydyz65360rwa0xifha9zrylpasd7-user-environment.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/6ipm50wj8ss3mbvz03vsh9cg8cx0apd5-user-environment
error: Cannot build '/nix/store/j13n0wd5nirig3x3z8kb7sd1xwz1ls1b-etc.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/dbnqr8ybn5ix64lw6wawi9l12izfz02m-etc
error: Cannot build '/nix/store/4x3spssjxzvd498hjwpvgf6gxi09mwsl-unit-home-manager-ozumr.service.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/zv9wrzxkwrd69ay0c4kysdvi5l1g2sh9-unit-home-manager-ozumr.service
error: Cannot build '/nix/store/vpywixczfsa62y1a075naz5kz9h9d6zc-activate.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/rngr2lix4434a67xacmpwhmbw28li6vd-activate
error: Cannot build '/nix/store/wz4ijkzgxpxaq3kijig9dz32l9dvlrm8-nixos-system-nixosHome-26.05.20260726.8623c4c.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/21ig8f8dy6w3zg3w6pvv6qqnabmdrw4h-nixos-system-nixosHome-26.05.20260726.8623c4c
┏━ 12 Errors:
Error:
   0: Failed to build configuration                                                                                        1: Command exited with status ExitStatus(Exited(1))
                                                                  Location:
   crates/nh-core/src/command.rs:892
┏━ 12 Errors:
 ⋮
┃        > /build/source/onnxruntime/contrib_ops/cuda/collective/sharded_moe.h:6:10: fatal error: contrib_ops/cuda/moe/ft_moe/moe_kernel.h: No such file or directory
┃        >     6 | #include "contrib_ops/cuda/moe/ft_moe/moe_kernel.h"
┃        >       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
┃        > compilation terminated.
┃        > make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:5365: CMakeFiles/onnxruntime_providers_cu…
┃        > make[2]: *** Waiting for unfinished jobs....
┃        > make[1]: *** [CMakeFiles/Makefile2:1508: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
┃        > make: *** [Makefile:146: all] Error 2
┃        For full logs, run:
┃          nix log /nix/store/q7g5fw4dh579mzggpkdbgvf8gz0bq488-onnxruntime-1.27.1.drv
┣━ Dependency Graph:
┃                            ┌─ ⏵ onnxruntime-1.27.1 (buildPhase) ⏱ 4h49m24s (∅ 6h12m38s)
```

### Additional context

trying to build firefox today twice, first time its failed at onnxruntime -> cuda12.9-cudnn-frontend-1.25.0 step; Fix already merged https://nixpk.gs/pr-tracker.html?pr=545542 create overlay with same fix of a problem build again for now it again failed because 
```
onnxruntime/contrib_ops/cuda/collective/sharded_moe.h:6:10: fatal error:
  contrib_ops/cuda/moe/ft_moe/moe_kernel.h: No such file or directory
```

for now i will add second overlay with disable ncclSupport to avoid fail 
final: prev: {
  onnxruntime = prev.onnxruntime.override { ncclSupport = false; };
}

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.36, NixOS, 26.05 (Yarara), 26.05.20260622.3426825`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.7`
 - nixpkgs: `/nix/store/6qwyfa76h4na0qq07rk359l3dk9ajkrh-source`

### Notify maintainers

@ck3d 
@puffnfresh 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Build currently fails when `cudaSupport` is on.

```
In file included from /build/source/onnxruntime/contrib_ops/cuda/collective/sharded_moe.cc:10:
/build/source/onnxruntime/contrib_ops/cuda/collective/sharded_moe.h:6:10: fatal error: contrib_ops/cuda/moe/ft_moe/moe_kernel.h: No such file or directory
    6 | #include "contrib_ops/cuda/moe/ft_moe/moe_kernel.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This regression was caused by https://github.com/microsoft/onnxruntime/pull/28467.
Fix submitted upstream: https://github.com/microsoft/onnxruntime/pull/31139.

Fixes #546608.
Supersedes #546053.

cc @NixOS/cuda-maintainers 

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [ ] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [ ] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 547077 --extra-nixpkgs-config '{ allowUnfree = true; cudaSupport = true; }' --package onnxruntime`
Commit: `af4e7bf6a0e55dd832fc5fd4393738a36e190379`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>onnxruntime</li>
  </ul>
</details>

File: pkgs/by-name/on/onnxruntime/package.nix [hunk 1]
```diff
@@ -131,6 +132,15 @@ effectiveStdenv.mkDerivation (finalAttrs: {
     # https://github.com/microsoft/onnxruntime/issues/9155
     # Patch adapted from https://gitlab.alpinelinux.org/alpine/aports/-/raw/462dfe0eb4b66948fe48de44545cc22bb64fdf9f/community/onnxruntime/0001-Remove-MATH_NO_EXCEPT-macro.patch
     ./remove-MATH_NO_EXCEPT-macro.patch
+  ]
+  ++ lib.optionals cudaSupport [
+    # Drop the orphaned ShardedMoE CUDA contrib op, whose ft_moe backend was removed upstream
+    # Fix submitted upstream: https://github.com/microsoft/onnxruntime/pull/31139
+    (fetchpatch {
+      name = "drop-orphaned-sharded-moe";
+      url = "https://github.com/GaetanLepage/onnxruntime/commit/e59fb53dd761638670f0b369003e6c9e08070591.patch";
```
Comment (NickCao) [inline pkgs/by-name/on/onnxruntime/package.nix]: I think it's currently recommended to vendor unmerged patches.

**Review by NickCao — APPROVED** [review]

File: pkgs/by-name/on/onnxruntime/package.nix [hunk 2]
```diff
@@ -131,6 +131,11 @@ effectiveStdenv.mkDerivation (finalAttrs: {
     # https://github.com/microsoft/onnxruntime/issues/9155
     # Patch adapted from https://gitlab.alpinelinux.org/alpine/aports/-/raw/462dfe0eb4b66948fe48de44545cc22bb64fdf9f/community/onnxruntime/0001-Remove-MATH_NO_EXCEPT-macro.patch
     ./remove-MATH_NO_EXCEPT-macro.patch
+  ]
+  ++ lib.optionals cudaSupport [
```
Comment (SuperSandro2000) [inline pkgs/by-name/on/onnxruntime/package.nix:135]: That patch should have been unconditional to quickly notice when it no longer applies

Comment (ConnorBaker) [reply pkgs/by-name/on/onnxruntime/package.nix:135]: It’s also equally fair to argue that it shouldn’t because it causes rebuilds for unaffected platforms.

Comment (GaetanLepage) [reply pkgs/by-name/on/onnxruntime/package.nix:135]: I agree with Connor. The CUDA CI should have been responsible for catching it.

Comment (SuperSandro2000) [reply pkgs/by-name/on/onnxruntime/package.nix:135]: It might be fine here but for eg: Darwin only patches we do not do it as otherwise it is very easy for someone on Linux to break the package for Darwin.

Comment (ConnorBaker) [reply pkgs/by-name/on/onnxruntime/package.nix:135]: Both systems have the benefit of being built by upstream Hydra. We do not. We have the worst of both worlds; our changes can cause rebuilds for other platforms which penalize us with incredibly expensive rebuilds and a slow merge via staging.
