### PR TITLE
vscode-extensions.matklad.rust-analyzer: fix #152285 on aarch64-darwin

### LINKED ISSUE #152285: `vscode-extensions.matklad.rust-analyzer` broken on `aarch64-darwin` due to `keytar` dependency missing framework build inputs
### Describe the bug
`vscode-extensions.matklad.rust-analyzer` has been broken on `aarch64-darwin` since #147373 with build log failures that look like (excerpting from <https://hydra.nixos.org/build/161724798/nixlog/2>):

```
...
../src/keytar_mac.cc:1:10: fatal error: 'Security/Security.h' file not found
#include <Security/Security.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [keytar.target.mk:129: Release/obj.target/keytar/src/keytar_mac.o] Error 1
```

Another patch #149120, fixed a related issue but did not fix the keytar dependency on Darwin.

Fortunately, adding the necessary frameworks as conditional-on-darwin nativeBuildInputs in a manner similar to the way that `lib secret` is added by #149120 fixes things here too.

(PR incoming once I finish writing it up.)

### Notify maintainers
@bkchr, @mweinelt (and @oxalica as a courtesy, though I know she has recently stepped down from maintaining the vscode extension)

### PR DESCRIPTION
**Pull request by mstone**
The rust-analyzer vscode extension depends on vsce which depends on keytar
which needs the AppKit and Security frameworks on Darwin.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]

File: pkgs/misc/vscode-extensions/rust-analyzer/default.nix [hunk 1]
```diff
@@ -8,6 +8,8 @@
 , esbuild
 , pkg-config
 , libsecret
+, stdenv
+, darwin
```
Comment (SuperSandro2000) [inline pkgs/misc/vscode-extensions/rust-analyzer/default.nix:12]: darwin should like pkgs not be used as an input.
