### PR TITLE
zfs: fix build with Linux >=5.18

### LINKED ISSUE #179551: zfs 2.15 fails to build with kernel 5.18.6
### Steps To Reproduce
1. Tried to upgrade to NixOS 22.05 (was blocked before by zfs 2.14 not support kernel 5.18; now zfs 2.15 was backported to NixOS 22.05 - see #178830)
2. Run `nixos-rebuild` with updated channel

### Build log
The failing parts are:

```
In file included from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/string.h:253,
                 from /build/source/include/os/linux/spl/sys/strings.h:24,
                 from /build/source/module/icp/algs/edonr/edonr.c:32:
In function 'fortify_memcpy_chk',
    inlined from 'EdonRInit' at /build/source/module/icp/algs/edonr/edonr.c:491:3:
/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/fortify-string.h:328:25: error: call to '__write_overflow_field' declared with attribu>
  328 |                         __write_overflow_field(p_size_field, size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[...]

cc1: all warnings being treated as errors
make[5]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/scripts/Makefile.build:288: /build/source/module/icp/algs/edonr/edonr.o] Error 1

[...]

In file included from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/string.h:253,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/bitmap.h:11,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/cpumask.h:12,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/cpumask.h:5,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/msr.h:11,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/processor.h:22,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/arch/x86/include/asm/timex.h:5,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/timex.h:67,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/time32.h:13,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/time.h:60,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/stat.h:19,
                 from /nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/module.h:13,
                 from /build/source/include/os/linux/spl/sys/atomic.h:27,
                 from /build/source/include/sys/zfs_context.h:46,
                 from /build/source/module/zfs/dsl_bookmark.c:22:
In function 'fortify_memset_chk',
    inlined from 'dsl_bookmark_set_phys' at /build/source/module/zfs/dsl_bookmark.c:384:3:
/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/include/linux/fortify-string.h:242:25: error: call to '__write_overflow_field' declared with attribu>
  242 |                         __write_overflow_field(p_size_field, size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[...]

cc1: all warnings being treated as errors
make[5]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/scripts/Makefile.build:288: /build/source/module/zfs/dsl_bookmark.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/scripts/Makefile.build:550: /build/source/module/zfs] Error 2
  LD [M]  /build/source/module/zstd/zzstd.o
make[3]: *** [/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/source/Makefile:1838: /build/source/module] Error 2
make[3]: Leaving directory '/nix/store/ihdv194y3fw10zgazid0v3fldhl12vvk-linux-5.18.6-dev/lib/modules/5.18.6/build'
make[2]: *** [Makefile:55: modules-Linux] Error 2
make[2]: Leaving directory '/build/source/module'
make[1]: *** [Makefile:930: all-recursive] Error 1
make[1]: Leaving directory '/build/source'
make: *** [Makefile:791: all] Error 2
```

### Additional context
This may be a zfs problem, not a nix problem, but i am not sure about that. It may even be a "me"-problem, though i have no custom config around zfs- or kernel-versions.

### Notify maintainers
@Madouura @hmenke @jcumming @jonringer @wizeman @fpletz @globin

### Metadata
```console
[user@@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by hmenke**
###### Description of changes

Fixes #179551

To make it possible to build ZFS 2.1.5 against Linux 5.18 we have to disable
this specific error condition.  Judging from this comment [1] on the ZFS issue
tracker, upstream doesn't compile with -Werror at all, so it is safe to disable
turning this warning into an error.

[1] https://github.com/openzfs/zfs/issues/13622#issuecomment-1175311028

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hmenke** [comment]
So maybe the fix I propose is not even necessary anymore. Has the staging iteration containing that fix already landed? Then we should also backport #175433 to staging-22.05 otherwise this will remain broken on stable NixOS.

**Comment by PedroHLC** [comment]
> So maybe the fix I propose is not even necessary anymore. Has the staging iteration containing that fix already landed? Then we should also backport #175433 to staging-22.05 otherwise this will remain broken on stable NixOS.

Looks like you figured it out, we have it in staging, while it's missing in 22.05.

**Comment by hmenke** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/180275
