### ISSUE TITLE
redoc-cli: crashes with MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by simonzkl** [NixOS/nixpkgs#272217]
### Describe the bug

The `redoc-cli` package doesn't work at runtime. Most likely broken by the move to `buildNpmPackage` in #254851

```
node:internal/modules/cjs/loader:1080
  throw err;
  ^
Error: Cannot find module '/nix/store/faa5zlf9daza1qqwxrfhjylvp03804z5-redoc-cli-0.13.21/lib/node_modules/redoc-cli/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v18.18.2
```

There doesn't seem to be an `index.js` and the derivation completely skips the build phase `dontNpmBuild = true;`.

### Steps To Reproduce
1. nix run nixpkgs#redoc-cli -- --help

### Expected behavior
It shouldn't crash while trying to load modules.

### Additional context
This affects both Linux and Darwin.

### Notify maintainers

@veehaitch @dotlambda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/7g8wbm1z6948x0qma4hzkkb9a3xys76w-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
> the derivation completely skips the build phase `dontNpmBuild = true;`

That's because https://github.com/Redocly/redoc/blob/redoc-cli/cli/package.json doesn't have any `scripts`.

I guess that `tsc` should be run in the `buildPhase`. Feel free to make that change in a PR. I don't think anyone else is currently maintaining the package.

**Comment by simonzkl** [comment]
Marked as broken and replaced with redocly-cli in https://github.com/NixOS/nixpkgs/pull/272320.
