### PR TITLE
onlyoffice-documentserver: use icu78

### LINKED ISSUE #536824: Build failure: onlyoffice-documentserver
### Nixpkgs version

- Stable (26.05)
- Unstable

### Steps to reproduce

```bash
nix build nixpkg/nixos-26.05#onlyoffice-documentserver
```

or

```bash
nix build nixpkgs/nixos-unstable#onlyoffice-documentserver
```

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

26.05: https://hydra.nixos.org/build/332146121
Unstable: https://hydra.nixos.org/build/332823962

### Relevant log output

```console
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x1a): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x27): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x34): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x41): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: (.text._ZN2v88internal18BuildSpecialAddSetEv+0x4e): undefined reference to `icu_78::UnicodeSet::add(int)'
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: /build/source/Common/3dParty/v8/../v8_89/v8/out.gn/linux_64/obj/libv8.a(v8_base_without_compiler.special-case.o):(.text._ZN2v88internal18BuildSpecialAddSetEv+0x5b): more undefined references to `icu_78::UnicodeSet::add(int)' follow
/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46/bin/ld.bfd: /build/source/Common/3dParty/v8/../v8_89/v8/out.gn/linux_64/obj/libv8.a(v8_base_without_compiler.special-case.o): in function `v8::internal::BuildSpecialAddSet()':
(.text._ZN2v88internal18BuildSpecialAddSetEv+0xa4): undefined reference to `icu_78::UnicodeSet::freeze()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:311: ../../build/lib/linux_64/libdoctrenderer.so] Error 1
```

### Additional context

I bisected the change and the first bad commit for 26.05 is https://github.com/NixOS/nixpkgs/commit/4b965d7e22e3f82c9e9c77dd51bdd70679f0a904 .

So https://github.com/NixOS/nixpkgs/pull/520553 and https://github.com/NixOS/nixpkgs/pull/534248 are related.

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.33, NixOS, 26.05 (Yarara), 26.05.20260528.ec942ba`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.94.2
System type: x86_64-linux
Additional system types: aarch64-linux, i686-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/geoffrey/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/geoffrey/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/geoffrey/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/geoffrey/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/hmqgwax4s290mg1mi1g9vbabyjckr0db-lix-2.94.2/share`
 - nixpkgs: `/nix/store/lff22h6g4kvy848a7z8prfb0cgmy2hgy-source`

### Notify maintainers

@raboof 

Maybe also worth mentionning @marcin-serwin and @vcunat who made the related PRs?

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by raboof**
This is needed so that doctrenderer uses the same version of icu as the nodejs.libv8 . This is a little scary because it's a different version of icu than boost is built with, but seems to work out in practice. After #520553 this should ideally be in sync again.

Fixes #536824

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [ ] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [ ] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

**Comment by timhae** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 537160`
Commit: `f9f60a4608798c2bf37208562dbdcf2ddfa59e61`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>onlyoffice-documentserver</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>onlyoffice-documentserver</li>
  </ul>
</details>

**Comment by vcunat** [comment]
Beware that on the current staging-next https://github.com/NixOS/nixpkgs/pull/535855 nodejs uses icu 77 again 🤕   So after this merges, I expect we revert it on staging-next.

**Comment by raboof** [comment]
> Beware that on the current staging-next #535855 nodejs uses icu 77 again 🤕 So after this merges, I expect we revert it on staging-next.

Ah, I hadn't seen that, thanks ;) . So after merging this to master, I'd wait for master to be merged into staging-next again, and then PR the revert to that? (probably I'd revert only the first two changes and keep the last one in case we want to override icu again in the future)

**Comment by hatch01** [comment]
As OnlyOffice DocServer is broken again in NixOS-unstable, it is probably time for a revert PR!

**Comment by vcunat** [comment]
We forgot that the problem has been backported to 26.05, too, e.g.:
https://hydra.nixos.org/job/nixos/release-26.05/nixpkgs.onlyoffice-documentserver.x86_64-linux
