### PR TITLE
deepin.deepin-wm: use vala-0.42 to avoid compilation errors

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

The package does not compile with vala >= 0.44

Wanted for #68361

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
> This patch fixes this [linuxdeepin/deepin-wm#49](https://github.com/linuxdeepin/deepin-wm/pull/49).
> Can we update it?

We already have the latest version of the package, in which this patch has already been integrated (upstream). It still does not compile with vala 0.44.

**Comment by worldofpeace** [comment]
We'll merge this for now, it seems they fix things like this upstream promptly.

**Comment by worldofpeace** [comment]
backported in f7e407e0caebfb140498bd959150379d6192f482
