### PR TITLE
build-support/cc-wrapper: revert "pass in non-existent --sysroot= to …

### LINKED ISSUE #214124: opencv 4.7.0 in nixpkgs master has link errors
### Describe the bug

Hi, I created a minimal demonstrator for my problem:
https://github.com/tfc/whiteboard-opencv/tree/without-aruco (not main branch but `without-aruco`, to also build with nixos 22.11)

This minimal C++ app includes and links against opencv4.

Building this flake using `nix build` works just fine and the resulting app works.
Running `nix develop` and then doing `mkdir build && cd build && cmake .. && make` results in link errors:

```sh
... many others omitted ...
nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_core.so.4.7.0: undefined reference to `omp_get_max_threads@OMP_1.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_videoio.so.4.7.0: undefined reference to `gst_caps_set_simple'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_core.so.4.7.0: undefined reference to `clCreateCommandQueue@OPENCL_1.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_dnn.so.4.7.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RemoveLast()'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_videoio.so.4.7.0: undefined reference to `avcodec_get_context_defaults3@LIBAVCODEC_58'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/DisplayImage.dir/build.make:107: DisplayImage] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/DisplayImage.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

With nixpkgs on 22.11, both nix build and nix develop work.

### Steps To Reproduce

1. check out reproducer repo
2. Run `nix build`, works
3. Enter nix shell using `nix develop` and run: `mkdir build && cd build && cmake .. && make`, get mentioned error messages
4. Change flake input to nixpkgs 22.11
5. Repeat step 1 & 2 and see that they work

### Expected behavior

I would expect to not get these linker errors after upgrading to nixpkgs master

### Notify maintainers

@mdaiter @basvandijk 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-21.11.tar.gz, nixos-21.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### LINKED ISSUE #214282: llvmPackages_15: missing libffi.so.8 at runtime
### Steps To Reproduce
1. trying to build `https://github.com/ziglang/zig.git` from source
2. `mkdir build && cd build`
3. `cmake ..`
4. `make install`

```nix
with import <nixpkgs> {};

pkgs.mkShell {
  nativeBuildInputs = with pkgs; [
    cmake
    gdb
    libxml2
    ninja
    qemu
    wasmtime
    zlib
  ] ++ (with llvmPackages_15; [
    clang
    clang-unwrapped
    lld
    llvm
  ]);

  hardeningDisable = [ "all" ];
}
```

### Build log
```
[nix-shell:~/src/zig/build]$ cmake ..
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/1y8i61anhs9hh1g5x3zw2fvdbivwixzg-gcc-wrapper-11.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/1y8i61anhs9hh1g5x3zw2fvdbivwixzg-gcc-wrapper-11.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.11.0-dev.1465+d64dd75e3
-- Found llvm: -lLLVM-15;-lrt;-ldl;-lm;-lz;-ltinfo;-lxml2 (Required is at least version "15") 
-- Found clang: /nix/store/yws5gcxdm5sdq5wrldh2bj47vb0i0nv8-clang-15.0.7-lib/lib/libclang-cpp.so.15 (Required is at least version "15") 
-- Found lld: /nix/store/nzacynck36m2fkl4p8m7m4jx78dcg7hs-lld-15.0.7-lib/lib/liblldMinGW.a;/nix/store/nzacynck36m2fkl4p8m7m4jx78dcg7hs-lld-15.0.7-lib/lib/liblldELF.a;/nix/store/nzacynck36m2fkl4p8m7m4jx78dcg7hs-lld-15.0.7-lib/lib/liblldCOFF.a;/nix/store/nzacynck36m2fkl4p8m7m4jx78dcg7hs-lld-15.0.7-lib/lib/liblldWasm.a;/nix/store/nzacynck36m2fkl4p8m7m4jx78dcg7hs-lld-15.0.7-lib/lib/liblldMachO.a;/nix/store/nzacynck36m2fkl4p8m7m4jx78dcg7hs-lld-15.0.7-lib/lib/liblldCommon.a (Required is at least version "15") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/meghan/src/zig/build

[nix-shell:~/src/zig/build]$ make install
[  5%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_llvm.cpp.o
[ 10%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_llvm-ar.cpp.o
[ 15%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang.cpp.o
[ 20%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang_driver.cpp.o
[ 25%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang_cc1_main.cpp.o
[ 30%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang_cc1as_main.cpp.o
[ 35%] Building CXX object CMakeFiles/zigcpp.dir/src/windows_sdk.cpp.o
[ 40%] Linking CXX static library zigcpp/libzigcpp.a
[ 40%] Built target zigcpp
[ 45%] Building C object CMakeFiles/zig-wasm2c.dir/stage1/wasm2c.c.o
[ 50%] Linking C executable zig-wasm2c
[ 50%] Built target zig-wasm2c
[ 55%] Converting /home/meghan/src/zig/stage1/zig1.wasm to /home/meghan/src/zig/build/zig1.c
[ 60%] Building C object CMakeFiles/zig1.dir/zig1.c.o
[ 65%] Building C object CMakeFiles/zig1.dir/stage1/wasi.c.o
[ 70%] Linking C executable zig1
[ 70%] Built target zig1
[ 75%] Running zig1.wasm to produce /home/meghan/src/zig/build/zig2.c
[ 80%] Running zig1.wasm to produce /home/meghan/src/zig/build/compiler_rt.c
[ 85%] Building C object CMakeFiles/zig2.dir/zig2.c.o
/home/meghan/src/zig/build/zig2.c: In function ‘crypto_blake3_Output_chainingValue’:
/home/meghan/src/zig/build/zig2.c:2576006: warning: ‘crypto_blake3_CompressGeneric_compress’ reading 64 bytes from a region of size 32 [-Wstringop-overread]
2576006 |  t11 = crypto_blake3_CompressGeneric_compress(t2, t4, t6, t8, t10);
        | 
/home/meghan/src/zig/build/zig2.c:2576006: note: referencing argument 2 of type ‘const zig_u32 * const’ {aka ‘const unsigned int * const’}
/home/meghan/src/zig/build/zig2.c:2736956: note: in a call to function ‘crypto_blake3_CompressGeneric_compress’
2736956 | static zig_T_tuple_7b_5b16_5du32_7d_60048 crypto_blake3_CompressGeneric_compress(zig_u32 const a0[zig_const_arr zig_as_u64(8)], zig_u32 const a1[zig_const_arr zig_as_u64(16)], zig_u32 const a2, zig_u64 const a3, zig_u8 const a4) {
        | 
/home/meghan/src/zig/build/zig2.c: In function ‘crypto_blake3_ChunkState_update’:
/home/meghan/src/zig/build/zig2.c:2576184: warning: ‘crypto_blake3_CompressGeneric_compress’ reading 64 bytes from a region of size 32 [-Wstringop-overread]
2576184 |     t27 = crypto_blake3_CompressGeneric_compress(t17, t11, zig_as_u32(64), t4, t26);
        | 
/home/meghan/src/zig/build/zig2.c:2576184: note: referencing argument 2 of type ‘const zig_u32 * const’ {aka ‘const unsigned int * const’}
/home/meghan/src/zig/build/zig2.c:2736956: note: in a call to function ‘crypto_blake3_CompressGeneric_compress’
2736956 | static zig_T_tuple_7b_5b16_5du32_7d_60048 crypto_blake3_CompressGeneric_compress(zig_u32 const a0[zig_const_arr zig_as_u64(8)], zig_u32 const a1[zig_const_arr zig_as_u64(16)], zig_u32 const a2, zig_u64 const a3, zig_u8 const a4) {
        | 
/home/meghan/src/zig/build/zig2.c: In function ‘crypto_blake3_Output_rootOutputBytes’:
/home/meghan/src/zig/build/zig2.c:2576339: warning: ‘crypto_blake3_CompressGeneric_compress’ reading 64 bytes from a region of size 32 [-Wstringop-overread]
2576339 |    t19 = crypto_blake3_CompressGeneric_compress(t9, t11, t13, t18, t17);
        | 
/home/meghan/src/zig/build/zig2.c:2576339: note: referencing argument 2 of type ‘const zig_u32 * const’ {aka ‘const unsigned int * const’}
/home/meghan/src/zig/build/zig2.c:2736956: note: in a call to function ‘crypto_blake3_CompressGeneric_compress’
2736956 | static zig_T_tuple_7b_5b16_5du32_7d_60048 crypto_blake3_CompressGeneric_compress(zig_u32 const a0[zig_const_arr zig_as_u64(8)], zig_u32 const a1[zig_const_arr zig_as_u64(16)], zig_u32 const a2, zig_u64 const a3, zig_u8 const a4) {
        | 
[ 90%] Building C object CMakeFiles/zig2.dir/compiler_rt.c.o
[ 95%] Linking CXX executable zig2
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libffi.so.8, needed by /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_prep_cif@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_sint16@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_float@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_sint32@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_sint64@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_pointer@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_sint8@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_call@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_void@LIBFFI_BASE_8.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/vzcrnrflmclrh1780f9fh7dr164pisbg-llvm-15.0.7-lib/lib/libLLVM-15.so: undefined reference to `ffi_type_double@LIBFFI_BASE_8.0'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/zig2.dir/build.make:975: zig2] Error 1
make[1]: *** [CMakeFiles/Makefile2:170: CMakeFiles/zig2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[meghan@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 22.05 (Quokka), 22.05.4498.5cb48ea3c19`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
[meghan@nixos:~]$ nix-instantiate -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz --eval -E '(import <nixpkgs> {}).lib.version'
"23.05pre-git"
```

### LINKED ISSUE #215260: lld_14 with clang_14 cannot use libstdc++.so.6: cannot open shared object file: No such file or directory
### Describe the bug
llvm-tblgen can not find libstdc++.so.6. 

```
FAILED: include/llvm/IR/Attributes.inc <llvm-project>/llvm-project/build/include/llvm/IR/Attributes.inc 
cd <llvm-project>/llvm-project/build && <llvm-project>/llvm-project/build/bin/llvm-tblgen -gen-attrs -I <llvm-project>/llvm-project/llvm/include/llvm/IR -I<llvm-project>/llvm-project/build/include -I<llvm-project>/llvm-project/llvm/include <llvm-project>/llvm-project/llvm/include/llvm/IR/Attributes.td --write-if-changed -o include/llvm/IR/Attributes.inc -d include/llvm/IR/Attributes.inc.d
<llvm-project>/llvm-project/build/bin/llvm-tblgen: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Confirmed that g++/clang++ can generate correct minimal C++ binary (with libstdc++), but recently llvm-tblgen breaks.

### Steps To Reproduce
1. Use recent nixpkgs/nixos-unstable
2. build the llvm-project

LLVM Revision: d768b97424f9e1a0aae45440a18b99f21c4027ce

Flags:

```console

LLVM=~llvm-project

llvm_base="$LLVM"
build_mode="Debug"
build_dir="build"
build_base="${llvm_base}/${build_dir}"
llvm_enable_projects="clang;mlir"


cmake -DBUILD_SHARED_LIBS:STRING=On \
-DCMAKE_BUILD_TYPE:STRING=${build_mode} \
-DLLVM_APPEND_VC_REV:STRING=Off \
-DLLVM_ENABLE_LLD:STRING=On \
-DLLVM_ENABLE_PROJECTS:STRING="${llvm_enable_projects}" \
-DLLVM_LINK_LLVM_DYLIB:STRING=Off \
-DLLVM_OPTIMIZED_TABLEGEN=Off \
-DLLVM_CCACHE_BUILD:BOOL=FALSE \
-DLLVM_USE_SPLIT_DWARF=On \
-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
-DCMAKE_C_COMPILER:FILEPATH=${CC:-"gcc"} \
-DCMAKE_CXX_COMPILER:FILEPATH=${CXX:-"g++"} \
-S${llvm_base}/llvm \
-B${build_base} -G Ninja \
-DLLVM_TARGETS_TO_BUILD="host;RISCV;"

```

### Expected behavior
Compile LLVM successfully as before

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9, NixOS, 23.05 (Stoat), 23.05.20230206.5a350a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by trofi**
…untangle from libc"

This reverts commit 8c80bd08b7e39229947d55104d1871f5066437d9 ("build-support/cc-wrapper: pass in non-existent --sysroot= to untangle from libc").

This change was good in spirit: we caught a few genuine problems with `scons` based packages (`godot`, `fluxus`) and unexpected `-idirafter` includes in various boot loadres (`ipxe`, wimboot`):

    https://github.com/NixOS/nixpkgs/pull/210004#issuecomment-1407162693

Unfortunately `--sysroot=` also has a negative impact on libary search order for DT_NEEDED libraries and RUNPATHs of linked libraries. This unexpectedly broke `dmd`, `d-seams`, `llvmPackages_rocm.compiler-rt`).

An interesting case of unexpected breakage is `usbmuxd2` where the bug exposed incomplete library move on `libstdc++fs` in `gcc`.

The library breakage is very non-intuitive (on top of already unusual layout of `cc-wrapper` driver). Let's revert this change for now.

Once it lands we can undo `--sysroot=/` workarounds merged for `staging-next`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Validated that `wimboot dmd ubootTools ipxe mesa` still build after the reverts.

**Comment by amjoseph-nixpkgs** [comment]
Did anybody review this PR before it was merged?

**Comment by trofi** [comment]
`staging-next` started accumulating a bunch of failures caused by the blanket `--sysroot=` as you might have noticed in series of the reverts. To prevent further data I merged it faster into `staging`. Original change certainly did more than originally intended.

**Comment by amjoseph-nixpkgs** [comment]
Do you also need to revert

- https://github.com/NixOS/nixpkgs/pull/209153

?

If not, the comment it added needs to be updated.  It is no longer correct.

**Comment by amjoseph-nixpkgs** [comment]
https://github.com/NixOS/nixpkgs/blob/585af06acc9b5c082c91d42d7373b1d5dca42687/pkgs/development/compilers/gcc/builder.sh#L207-L208

**Comment by trofi** [comment]
I would say the change does not hurt if we are to allow any other value or `--sysroot=` and still expect gcc libraries to be found. I'm also fine with reverting it. But the comment could be better in any case, yes.

**Comment by trofi** [comment]
Proposed full revert as https://github.com/NixOS/nixpkgs/pull/213929
