### PR TITLE
dosbox-x: 2026.03.29 -> 2026.05.02

### LINKED ISSUE #516168: Build failure: dosbox-x
### Nixpkgs version

- Unstable (26.05)

### Steps to reproduce

1. `nix build -A dosbox-x` on `aarch64-darwin`

### Can Hydra reproduce this build failure?

Hydra doesn’t try to build the package.

### Link to Hydra build job

_No response_

### Relevant log output

```console
render.cpp:891:37: error: use of undeclared identifier 'SCREEN_METAL'
  891 |             && (sdl.desktop.type != SCREEN_METAL)
      |                                     ^~~~~~~~~~~~
render.cpp:1379:36: error: use of undeclared identifier 'SCREEN_METAL'
 1379 |             if(sdl.desktop.type == SCREEN_METAL) return false;
      |                                    ^~~~~~~~~~~~
```

### Additional context

This build failure was introduced by #504679: that is, `dosbox-x` builds on `aarch64-darwin` at commit 4c2d21b9689d597423bec80851c37cfb88253147, and fails to build on `aarch64-darwin` at commit 0e0519fe7e4c01e7f16d95ca813818ad2105bb97 or later.

However, even though DOSBox-X builds before that PR, it does not run:

```
LOG: Early LOG Init complete
LOG: "" is not a valid value for variable: configuration tool theme.
It might now be reset to the default value:
LOG: CONFIG: Created and loaded user config file /Users/samueles/Library/Preferences/DOSBox-X 2026.01.02 Preferences
LOG: CONFIG: Loaded config file: /Users/samueles/Library/Preferences/DOSBox-X 2026.01.02 Preferences
LOG: DOSBox-X's working directory: /Users/samueles
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 2026.01.02 Commit 59915c1 (macOS ARM SDL2 64-bit)
LOG: macOS EXE path: /nix/store/6dxlxdwyiir535qhs6xf2jl5la441sy3-dosbox-x-2026.01.02/Applications/dosbox-x.app/Contents/MacOS/dosbox-x
LOG: macOS Resource path: /nix/store/6dxlxdwyiir535qhs6xf2jl5la441sy3-dosbox-x-2026.01.02/Applications/dosbox-x.app/Contents/Resources
LOG: macOS: NSTouchBar support detected in system
LOG: Prevent capture: 0
LOG: SDL: version 2.32.64, Video cocoa, Audio coreaudio
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: SDL2 reports desktop display mode 1440 x 900
LOG: The default output for the video system: opengl
LOG: WARNING: SDL2 unable to create GL context
zsh: segmentation fault  nix run nixpkgs/15c6719d8c604779cf59e03c245ea61d3d7ab69b#dosbox-x
```

The segfault was introduced by #476460: that is, DOSBox-X builds and runs on `aarch64-darwin` at commit 0c939841b97bff18cb72ab72b179c4fd63f2e2d2, and segfaults on `aarch64-darwin` at commit 6c0f6b01b1c7d58214ca9c8ccd014e2f3019cc0e or later (until the build failure).

[According to the DOSBox-X `CHANGELOG`](https://github.com/joncampbell123/dosbox-x/blob/dosbox-x-v2026.03.29/CHANGELOG#L112), version 2026.03.29 "Fixed segfault on launch of macOS builds" (this refers to joncampbell123/dosbox-x#6038), so hopefully this segfault can be ignored and just fixing the build failure should be sufficient.

### System metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 25.4.0, macOS 26.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Determinate Nix 3.19.0) 2.34.6`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/jzd9vz08h5b7s3rgxzpw28mpw4rxk2ra-source`

### Notify maintainers

@hughobrien @OPNA2608

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by samestep**
https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2026.05.02

Fixes #516168 via joncampbell123/dosbox-x#6185.

See also https://github.com/NixOS/nixpkgs/pull/515929#discussion_r3178594838: should this package's `updateScript` be configured to avoid the main-osfree branch?

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

**Comment by OPNA2608** [comment]
> should this package's `updateScript` be configured to avoid the main-osfree branch?

That would be nice, yes.

I'm noticing that this doesn't *have* a `passthru.updateScript`… If you would be so kind and add:

```diff
diff --git a/pkgs/by-name/do/dosbox-x/package.nix b/pkgs/by-name/do/dosbox-x/package.nix
index 11e401c74bee..752eef136871 100644
--- a/pkgs/by-name/do/dosbox-x/package.nix
+++ b/pkgs/by-name/do/dosbox-x/package.nix
@@ -2,6 +2,7 @@
   lib,
   stdenv,
   fetchFromGitHub,
+  gitUpdater,
   alsa-lib,
   autoreconfHook,
   ffmpeg,
@@ -110,10 +111,16 @@ stdenv.mkDerivation (finalAttrs: {
       makeWrapper $out/Applications/dosbox-x.app/Contents/MacOS/dosbox-x $out/bin/dosbox-x
     '';
 
-  passthru.tests.version = testers.testVersion {
-    package = finalAttrs.finalPackage;
-    # Version output on stderr, program returns status code 1
-    command = "${lib.getExe finalAttrs.finalPackage} -version 2>&1 || true";
+  passthru = {
+    tests.version = testers.testVersion {
+      package = finalAttrs.finalPackage;
+      # Version output on stderr, program returns status code 1
+      command = "${lib.getExe finalAttrs.finalPackage} -version 2>&1 || true";
+    };
+    updateScript = gitUpdater {
+      rev-prefix = "dosbox-x-v";
+      ignoredVersions = "-osfree$";
+    };
   };
 
   meta = {
```

That should take care of such releases.

**Comment by samestep** [comment]
@OPNA2608 I'll leave this PR as-is to just include the version bump and let you put that `updateScript` in a separate PR.

**Review by OPNA2608 — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 516201`
Commit: `d7fa4082513619f5d503b38970fe660d60b635e2`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>dosbox-x</li>
  </ul>
</details>

---

Works for my projects.

Image

Image

LGTM.

**Comment by OPNA2608** [comment]
> I'll […] let you put that `updateScript` in a separate PR.

#516271
