### PR TITLE
fwupd: 1.9.25 -> 1.9.26

### PR DESCRIPTION
**Pull request by GaetanLepage**
Changelog: https://github.com/fwupd/fwupd/releases/tag/1.9.26

- **fwupd: format**
- **fwupd: 1.9.25 -> 1.9.26**

cc @R-VdP

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by r-vdp** [comment]
@GaetanLepage is there a reason to have this as draft?

I'm working on the 2.0.1 bump, I've got it to compile, but there's still some work left to get the tests to work. So it would probably be good to get this in in the meantime.

Thanks for your help in keeping this package up to date!

**Comment by GaetanLepage** [comment]
> @GaetanLepage is there a reason to have this as draft?
> 
> I'm working on the 2.0.1 bump, I've got it to compile, but there's still some work left to get the tests to work. So it would probably be good to get this in in the meantime.
> 
> Thanks for your help in keeping this package up to date!

I was originally working on the 2.0.1 bump but couldn't get it to build, so I opened this in the meantime.
Let me see if it builds...

**Comment by r-vdp** [comment]
Maybe we can collaborate on a single branch for the 2.0.1 bump, to avoid doing the same work twice. I'm a bit busy today, but I'll try to push what I have to a branch here. It compiles, we just need to fix the tests.

**Comment by GaetanLepage** [comment]
Oh right, this one fails with:
```
FAILED: src/libfwupdengine.so.p/fu-engine.c.o
gcc -Isrc/libfwupdengine.so.p -Isrc -I../src -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplugin -I/nix/store/maafv8cgs6ykcgpq6pyh4wcx901mr6zf-libarchive-3.7.4-de>
../src/fu-engine.c: In function 'fu_engine_load_metadata_store':
../src/fu-engine.c:4018:41: error: 'SOURCE_VERSION' undeclared (first use in this function); did you mean 'JSON_VERSION'?
 4018 |         xb_builder_append_guid(builder, SOURCE_VERSION);
      |                                         ^~~~~~~~~~~~~~
      |                                         JSON_VERSION
compilation terminated due to -Wfatal-errors.
```

**Comment by GaetanLepage** [comment]
> Oh right, this one fails with:
> 
> ```
> FAILED: src/libfwupdengine.so.p/fu-engine.c.o
> gcc -Isrc/libfwupdengine.so.p -Isrc -I../src -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplugin -I/nix/store/maafv8cgs6ykcgpq6pyh4wcx901mr6zf-libarchive-3.7.4-de>
> ../src/fu-engine.c: In function 'fu_engine_load_metadata_store':
> ../src/fu-engine.c:4018:41: error: 'SOURCE_VERSION' undeclared (first use in this function); did you mean 'JSON_VERSION'?
>  4018 |         xb_builder_append_guid(builder, SOURCE_VERSION);
>       |                                         ^~~~~~~~~~~~~~
>       |                                         JSON_VERSION
> compilation terminated due to -Wfatal-errors.
> ```

I bisected it to this change: https://github.com/fwupd/fwupd/pull/7797/files

**Comment by r-vdp** [comment]
> Oh right, this one fails with:
> 
> ```
> FAILED: src/libfwupdengine.so.p/fu-engine.c.o
> gcc -Isrc/libfwupdengine.so.p -Isrc -I../src -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplugin -I/nix/store/maafv8cgs6ykcgpq6pyh4wcx901mr6zf-libarchive-3.7.4-de>
> ../src/fu-engine.c: In function 'fu_engine_load_metadata_store':
> ../src/fu-engine.c:4018:41: error: 'SOURCE_VERSION' undeclared (first use in this function); did you mean 'JSON_VERSION'?
>  4018 |         xb_builder_append_guid(builder, SOURCE_VERSION);
>       |                                         ^~~~~~~~~~~~~~
>       |                                         JSON_VERSION
> compilation terminated due to -Wfatal-errors.
> ```

Ah, I had the same error on 2.0.0. It's a missing `#ifdef`, they fixed it in 2.0.0. IIRC, a workaround without patching is to add git to nativeBuildInputs.

**Comment by GaetanLepage** [comment]
> > Oh right, this one fails with:
> > ```
> > FAILED: src/libfwupdengine.so.p/fu-engine.c.o
> > gcc -Isrc/libfwupdengine.so.p -Isrc -I../src -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplugin -I/nix/store/maafv8cgs6ykcgpq6pyh4wcx901mr6zf-libarchive-3.7.4-de>
> > ../src/fu-engine.c: In function 'fu_engine_load_metadata_store':
> > ../src/fu-engine.c:4018:41: error: 'SOURCE_VERSION' undeclared (first use in this function); did you mean 'JSON_VERSION'?
> >  4018 |         xb_builder_append_guid(builder, SOURCE_VERSION);
> >       |                                         ^~~~~~~~~~~~~~
> >       |                                         JSON_VERSION
> > compilation terminated due to -Wfatal-errors.
> > ```
> 
> Ah, I had the same error on 2.0.0. It's a missing `#ifdef`, they fixed it in 2.0.0. IIRC, a workaround without patching is to add git to nativeBuildInputs.

Ok, let's just skip to 2.0.0 then.
Can you create a PR ? I didn't go very far personally.

**Comment by r-vdp** [comment]
I meant 2.0.1, 2.0.0 had the same error.

Yeah, I'll clean up the branch and push it, probably tonight or tomorrow.

**Comment by GaetanLepage** [comment]
> I meant 2.0.1, 2.0.0 had the same error.
> 
> Yeah, I'll clean up the branch and push it, probably tonight or tomorrow.

Any news @r-vdp ? (no pressure)

**Comment by r-vdp** [comment]
> > I meant 2.0.1, 2.0.0 had the same error.
> > 
> > Yeah, I'll clean up the branch and push it, probably tonight or tomorrow.
> 
> Any news @r-vdp ? (no pressure)

Yeah, I've got the unit tests to work, now it's just the VM test that remains. I think some things changed about install destinations and there's some config files that are not ending up in the right location anymore.

After that I'll need to do some cleanup, check whether all dependencies are still required, etc.

I'll make a draft PR when I'm back behind my laptop, in case you want to have a look already.

**Comment by GaetanLepage** [comment]
> Yeah, I've got the unit tests to work, now it's just the VM test that remains. I think some things changed about install destinations and there's some config files that are not ending up in the right location anymore.
> 
> After that I'll need to do some cleanup, check whether all dependencies are still required, etc.

Great !

> I'll make a draft PR when I'm back behind my laptop, in case you want to have a look already.

Sure no worry. Be sure to ping me when you create it. I will help at least with the rebuilds.

**Comment by r-vdp** [comment]
#351772
