### PR TITLE
lkrg: init at 0.9.5

### PR DESCRIPTION
**Pull request by chivay**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Please squash commits into one

**Comment by chivay** [comment]
@onny Squashed and upgraded to 0.9.5

**Comment by onny** [comment]
@ofborg build lkrg

**Comment by chivay** [comment]
Result of `nixpkgs-review pr 159830` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.lkrg</li>
    <li>linuxKernel.packages.linux_4_14.lkrg</li>
    <li>linuxKernel.packages.linux_4_14_hardened.lkrg</li>
    <li>linuxKernel.packages.linux_4_19.lkrg</li>
    <li>linuxKernel.packages.linux_4_19_hardened.lkrg</li>
    <li>linuxKernel.packages.linux_4_9.lkrg</li>
    <li>linuxKernel.packages.linux_5_4.lkrg</li>
    <li>linuxPackages_4_14_hardened.lkrg</li>
    <li>linuxPackages_4_19_hardened.lkrg</li>
    <li>linuxPackages_hardkernel_latest.lkrg</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.lkrg</li>
    <li>linuxPackages_5_10_hardened.lkrg (linuxKernel.packages.linux_5_10_hardened.lkrg)</li>
    <li>linuxPackages.lkrg (linuxKernel.packages.linux_5_15.lkrg)</li>
    <li>linuxPackages_hardened.lkrg (linuxPackages_5_15_hardened.lkrg)</li>
    <li>linuxKernel.packages.linux_5_19.lkrg</li>
    <li>linuxKernel.packages.linux_5_19_hardened.lkrg</li>
    <li>linuxPackages_latest.lkrg (linuxKernel.packages.linux_6_0.lkrg)</li>
    <li>linuxPackages_latest-libre.lkrg (linuxKernel.packages.linux_latest_libre.lkrg)</li>
    <li>linuxPackages-libre.lkrg (linuxKernel.packages.linux_libre.lkrg)</li>
    <li>linuxPackages_lqx.lkrg (linuxKernel.packages.linux_lqx.lkrg)</li>
    <li>linuxPackages_testing_bcachefs.lkrg (linuxKernel.packages.linux_testing_bcachefs.lkrg)</li>
    <li>linuxPackages_xanmod.lkrg (linuxKernel.packages.linux_xanmod.lkrg)</li>
    <li>linuxPackages_xanmod_latest.lkrg (linuxKernel.packages.linux_xanmod_latest.lkrg)</li>
    <li>linuxPackages_xanmod_stable.lkrg (linuxKernel.packages.linux_xanmod_stable.lkrg)</li>
    <li>linuxPackages_xanmod_tt.lkrg (linuxKernel.packages.linux_xanmod_tt.lkrg)</li>
    <li>linuxPackages_zen.lkrg (linuxKernel.packages.linux_zen.lkrg)</li>
  </ul>
</details>

**Comment by solardiz** [comment]
BTW, why this versions range? -

```
  broken = kernel.kernelOlder "5.10" || kernel.kernelAtLeast "6.1";
```

I am aware of LKRG 0.9.5 being broken on the upcoming Linux 6.1 (already fixed in LKRG git), but LKRG should work fine on kernels below 5.10 (starting with RHEL7's "3.10" branch).

**Comment by chivay** [comment]
Seems like the kernels are missing a Kconfig switch. Same error with 5.4

```
$ nix build .#linuxKernel.packages.linux_4_14.lkrg
error: builder for '/nix/store/pwkjy1ibvd7b9kv9sgxd5da8x7z5hwpb-lkrg-0.9.5-4.14.295.drv' failed with exit code 2;
       last 10 log lines:
       > In file included from /build/source/src/modules/ksyms/p_resolve_ksym.c:19:
       > /build/source/src/modules/ksyms/../../p_lkrg_main.h:422:3: error: #error "LKRG requires CONFIG_KALLSYMS_ALL"
       >   422 |  #error "LKRG requires CONFIG_KALLSYMS_ALL"
       >       |   ^~~~~
       > make[4]: *** [/nix/store/m3qa4170lqp4c237vdd4m502vzhri7sm-linux-4.14.295-dev/lib/modules/4.14.295/source/scripts/Makefile.build:330: /build/source/src/modules/ksyms/p_resolve_ksym.o] Error 1
       > make[3]: *** [/nix/store/m3qa4170lqp4c237vdd4m502vzhri7sm-linux-4.14.295-dev/lib/modules/4.14.295/source/Makefile:1556: _module_/build/source] Error 2
       > make[2]: *** [Makefile:146: sub-make] Error 2
       > make[1]: *** [Makefile:24: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/m3qa4170lqp4c237vdd4m502vzhri7sm-linux-4.14.295-dev/lib/modules/4.14.295/build'
       > make: *** [Makefile:99: all] Error 2
       For full logs, run 'nix log /nix/store/pwkjy1ibvd7b9kv9sgxd5da8x7z5hwpb-lkrg-0.9.5-4.14.295.drv'.
```

**Comment by solardiz** [comment]
@chivay OK, then restricting to 5.10+ makes sense for NixOS kernels. Thanks.

**Review by patryk4815 — APPROVED** [review]

**Review by BonusPlay — APPROVED** [review]

**Comment by patryk4815** [comment]
@ofborg build linuxPackages.lkrg linuxKernel.packages.hardkernel_4_14.lkrg linuxKernel.packages.linux_4_14.lkrg linuxKernel.packages.linux_4_14_hardened.lkrg linuxKernel.packages.linux_4_19.lkrg linuxKernel.packages.linux_4_19_hardened.lkrg linuxKernel.packages.linux_4_4.lkrg linuxKernel.packages.linux_4_9.lkrg linuxKernel.packages.linux_5_10.lkrg linuxKernel.packages.linux_5_10_hardened.lkrg linuxKernel.packages.linux_5_15.lkrg linuxKernel.packages.linux_5_15_hardened.lkrg linuxKernel.packages.linux_5_16.lkrg linuxKernel.packages.linux_5_17.lkrg linuxKernel.packages.linux_5_18.lkrg linuxKernel.packages.linux_5_18_hardened.lkrg linuxKernel.packages.linux_5_19.lkrg linuxKernel.packages.linux_5_19_hardened.lkrg linuxKernel.packages.linux_5_4.lkrg linuxKernel.packages.linux_5_4_hardened.lkrg linuxKernel.packages.linux_6_0.lkrg linuxKernel.packages.linux_6_0_hardened.lkrg linuxKernel.packages.linux_hardened.lkrg linuxKernel.packages.linux_latest_libre.lkrg linuxKernel.packages.linux_libre.lkrg linuxKernel.packages.linux_lqx.lkrg linuxKernel.packages.linux_rpi1.lkrg linuxKernel.packages.linux_rpi2.lkrg linuxKernel.packages.linux_rpi3.lkrg linuxKernel.packages.linux_rpi4.lkrg linuxKernel.packages.linux_rt_5_10.lkrg linuxKernel.packages.linux_rt_5_4.lkrg linuxKernel.packages.linux_testing.lkrg linuxKernel.packages.linux_testing_bcachefs.lkrg linuxKernel.packages.linux_xanmod.lkrg linuxKernel.packages.linux_xanmod_latest.lkrg linuxKernel.packages.linux_xanmod_stable.lkrg linuxKernel.packages.linux_xanmod_tt.lkrg linuxKernel.packages.linux_zen.lkrg

**Comment by patryk4815** [comment]
@chivay I see there one problem on `ofborg` with `linuxKernel.packages.linux_rt_5_10.lkrg`:
Logs here: https://logs.nix.ci/?key=nixos/nixpkgs.159830&attempt_id=a1a87ac0-e150-4674-853b-63202e3052ab
```
In file included from /build/source/src/modules/ksyms/p_resolve_ksym.c:19:
/build/source/src/modules/ksyms/../../p_lkrg_main.h:438:3: error: #error "LKRG does not support RT kernels (PREEMPT_RT is enabled)"
  438 |  #error "LKRG does not support RT kernels (PREEMPT_RT is enabled)"
      |   ^~~~~
  CC [M]  /build/source/src/modules/database/p_database.o
make[3]: *** [/nix/store/vy02sj1y4lq6k4a9l5pbqbdc7lkbilnd-linux-5.10.152-rt75-dev/lib/modules/5.10.152-rt75/source/scripts/Makefile.build:286: /build/source/src/modules/ksyms/p_resolve_ksym.o] Error 1
make[2]: *** [/nix/store/vy02sj1y4lq6k4a9l5pbqbdc7lkbilnd-linux-5.10.152-rt75-dev/lib/modules/5.10.152-rt75/source/Makefile:1837: /build/source] Error 2
make[1]: *** [/nix/store/vy02sj1y4lq6k4a9l5pbqbdc7lkbilnd-linux-5.10.152-rt75-dev/lib/modules/5.10.152-rt75/source/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/nix/store/vy02sj1y4lq6k4a9l5pbqbdc7lkbilnd-linux-5.10.152-rt75-dev/lib/modules/5.10.152-rt75/build'
```

File: pkgs/os-specific/linux/lkrg/default.nix [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  '';
+
+  meta = with lib; {
+    description = "LKRG Linux Kernel module";
+    longDescription = "LKRG performs runtime integrity checking of the Linux kernel and detection of security vulnerability exploits against the kernel.";
+    homepage = "https://lkrg.org/";
+    license = licenses.gpl2Only;
+    maintainers = with maintainers; [ chivay ];
+    platforms = platforms.linux;
+    broken = kernel.kernelOlder "5.10" || kernel.kernelAtLeast "6.1";
```
Comment (patryk4815) [inline pkgs/os-specific/linux/lkrg/default.nix:42]:
```suggestion
    broken = kernel.kernelOlder "5.10"
      || kernel.kernelAtLeast "6.1"
      || ((kernel.structuredExtraConfig ? PREEMPT_RT) && kernel.structuredExtraConfig.PREEMPT_RT == lib.kernel.yes);  // LKRG does not support RT kernels
```

File: pkgs/os-specific/linux/lkrg/default.nix [hunk 2]
```diff
@@ -0,0 +1,44 @@
+{ lib, stdenv, fetchFromGitHub, kernel }:
```
Comment (patryk4815) [inline pkgs/os-specific/linux/lkrg/default.nix:1]:
```suggestion
{ lib
, stdenv
, fetchFromGitHub
, kernel
}:
```

**Comment by patryk4815** [comment]
And there is another problem with latest kernel `6.0.7` only on aarch64 (amd64 compiling fine):
Logs: https://logs.nix.ci/?key=nixos/nixpkgs.159830&attempt_id=c92b4bfb-b8bc-4493-9031-ff59e75a357d
```
       >   CC [M]  /build/source/src/modules/exploit_detection/p_exploit_detection.o
       > /build/source/src/modules/exploit_detection/p_exploit_detection.c: In function 'p_ed_enforce_pcfi':
       > /build/source/src/modules/exploit_detection/p_exploit_detection.c:1651:22: error: storage size of 'p_frame' isn't known
       >  1651 |    struct stackframe p_frame;
       >       |                      ^~~~~~~
       > /build/source/src/modules/exploit_detection/p_exploit_detection.c:1651:22: warning: unused variable 'p_frame' [-Wunused-variable]
       > make[2]: *** [/nix/store/7rzvz643i32l5syilv6l45gv7jdvf26l-linux-6.0.7-dev/lib/modules/6.0.7-gnu/source/scripts/Makefile.build:249: /build/source/src/modules/exploit_detection/p_exploit_detection.o] Error 1
       > make[1]: *** [/nix/store/7rzvz643i32l5syilv6l45gv7jdvf26l-linux-6.0.7-dev/lib/modules/6.0.7-gnu/source/Makefile:1852: /build/source] Error 2
       > make[1]: Leaving directory '/nix/store/7rzvz643i32l5syilv6l45gv7jdvf26l-linux-6.0.7-dev/lib/modules/6.0.7-gnu/build'
       > make: *** [Makefile:99: all] Error 2
       For full logs, run 'nix log /nix/store/631gvmmdyj0w4xigkspxflpmp00nz18w-lkrg-0.9.5-6.0.7.drv'.
```

**Comment by patryk4815** [comment]
And there is another problem with latest kernel `6.0.7` only on aarch64 (amd64 compiling fine):
Logs: https://logs.nix.ci/?key=nixos/nixpkgs.159830&attempt_id=c92b4bfb-b8bc-4493-9031-ff59e75a357d
```
       >   CC [M]  /build/source/src/modules/exploit_detection/p_exploit_detection.o
       > /build/source/src/modules/exploit_detection/p_exploit_detection.c: In function 'p_ed_enforce_pcfi':
       > /build/source/src/modules/exploit_detection/p_exploit_detection.c:1651:22: error: storage size of 'p_frame' isn't known
       >  1651 |    struct stackframe p_frame;
       >       |                      ^~~~~~~
       > /build/source/src/modules/exploit_detection/p_exploit_detection.c:1651:22: warning: unused variable 'p_frame' [-Wunused-variable]
       > make[2]: *** [/nix/store/7rzvz643i32l5syilv6l45gv7jdvf26l-linux-6.0.7-dev/lib/modules/6.0.7-gnu/source/scripts/Makefile.build:249: /build/source/src/modules/exploit_detection/p_exploit_detection.o] Error 1
       > make[1]: *** [/nix/store/7rzvz643i32l5syilv6l45gv7jdvf26l-linux-6.0.7-dev/lib/modules/6.0.7-gnu/source/Makefile:1852: /build/source] Error 2
       > make[1]: Leaving directory '/nix/store/7rzvz643i32l5syilv6l45gv7jdvf26l-linux-6.0.7-dev/lib/modules/6.0.7-gnu/build'
       > make: *** [Makefile:99: all] Error 2
       For full logs, run 'nix log /nix/store/631gvmmdyj0w4xigkspxflpmp00nz18w-lkrg-0.9.5-6.0.7.drv'.
```
cc: @solardiz

File: pkgs/os-specific/linux/lkrg/default.nix [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+  pname = "lkrg";
+  version = "0.9.5";
+
+  src = fetchFromGitHub {
+    owner = "lkrg-org";
+    repo = "lkrg";
+    rev = "v${version}";
+    sha256 = "sha256-+yIKkTvfVbLnFBoXSKGebB1A8KqpaRmsLh8SsNuI9Dc=";
+  };
+
```
Comment (patryk4815) [inline pkgs/os-specific/linux/lkrg/default.nix:14]: patches = [
    (fetchpatch {
      name = "fix-aarch64.patch";
      url = "https://github.com/lkrg-org/lkrg/commit/a4e5c00f13f7081b346bc3736e4c035e3d17d3f7.patch";
      sha256 = "1hmn85x8h7r331l5laqljk4xbhbaz5bwjdhzkjay95iz4wgpwlad";
    })
  ];

**Comment by patryk4815** [comment]
@ofborg build linuxPackages.lkrg linuxKernel.packages.hardkernel_4_14.lkrg linuxKernel.packages.linux_4_14.lkrg linuxKernel.packages.linux_4_14_hardened.lkrg linuxKernel.packages.linux_4_19.lkrg linuxKernel.packages.linux_4_19_hardened.lkrg linuxKernel.packages.linux_4_4.lkrg linuxKernel.packages.linux_4_9.lkrg linuxKernel.packages.linux_5_10.lkrg linuxKernel.packages.linux_5_10_hardened.lkrg linuxKernel.packages.linux_5_15.lkrg linuxKernel.packages.linux_5_15_hardened.lkrg linuxKernel.packages.linux_5_16.lkrg linuxKernel.packages.linux_5_17.lkrg linuxKernel.packages.linux_5_18.lkrg linuxKernel.packages.linux_5_18_hardened.lkrg linuxKernel.packages.linux_5_19.lkrg linuxKernel.packages.linux_5_19_hardened.lkrg linuxKernel.packages.linux_5_4.lkrg linuxKernel.packages.linux_5_4_hardened.lkrg linuxKernel.packages.linux_6_0.lkrg linuxKernel.packages.linux_6_0_hardened.lkrg linuxKernel.packages.linux_hardened.lkrg linuxKernel.packages.linux_latest_libre.lkrg linuxKernel.packages.linux_libre.lkrg linuxKernel.packages.linux_lqx.lkrg linuxKernel.packages.linux_rpi1.lkrg linuxKernel.packages.linux_rpi2.lkrg linuxKernel.packages.linux_rpi3.lkrg linuxKernel.packages.linux_rpi4.lkrg linuxKernel.packages.linux_rt_5_10.lkrg linuxKernel.packages.linux_rt_5_4.lkrg linuxKernel.packages.linux_testing.lkrg linuxKernel.packages.linux_testing_bcachefs.lkrg linuxKernel.packages.linux_xanmod.lkrg linuxKernel.packages.linux_xanmod_latest.lkrg linuxKernel.packages.linux_xanmod_stable.lkrg linuxKernel.packages.linux_xanmod_tt.lkrg linuxKernel.packages.linux_zen.lkrg

**Comment by patryk4815** [comment]
LGTM :) ofborg now builds correctly :)

**Review by msm-code — APPROVED** [review]
LGTM :+1: Looking forward to seeing it merged.

**Comment by solardiz** [comment]
Thank you all for getting this merged!
We'd like to link to the NixOS package from the LKRG homepage. Do we link to https://github.com/NixOS/nixpkgs/tree/master/pkgs/os-specific/linux/lkrg or is there a more appropriate URL?

**Comment by onny** [comment]
You could also link to https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=lkrg

**Comment by solardiz** [comment]
@onny Thank you, link added.
