### ISSUE TITLE
Installation of iterm2 fails with "ld: unknown option: -isysroot"

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#35412]
## Issue description
Installation of iterm2 fails. The errors are
```
ld: unknown option: -isysroot
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld failed with exit code 1

** BUILD FAILED **


The following build commands failed:
	Ld build/Deployment/image_decoder normal x86_64
(1 failure)
make: *** [Makefile:35: Deployment] Error 65
builder for ‘/nix/store/wayzykp0ikjlkbgw6ad0sc40ydmjklg1-iterm2-3.0.14.drv’ failed with exit code 2
error: build of ‘/nix/store/wayzykp0ikjlkbgw6ad0sc40ydmjklg1-iterm2-3.0.14.drv’ failed
```

### Steps to reproduce
nix-env -i iterm2

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(avorobiev): `"nixpkgs-18.03pre129189.c2fbd472a4e"`
 - nixpkgs: `/Users/avorobiev/.nix-defexpr/channels/nixpkgs`

**Comment by matthewbauer** [comment]
I've looked into it and it looks like we are going to need at least 10.12 SDK for iTerm2 to compile. Tracking with #37403

**Comment by strager** [comment]
I fixed this in #58517. Can you confirm that iTerm 2 now builds?

**Comment by arximboldi** [comment]
For me it fails with a different error:
```
CompileC build/iTerm2.build/Deployment/iTerm2Shared.build/Objects-normal/x86_64/PTYWindow.o sources/PTYWindow.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DNS_BLOCK_ASSERTIONS=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.8 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -iquote /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/iTerm2Shared-generated-files.hmap -I/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/iTerm2Shared-own-target-headers.hmap -I/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/iTerm2Shared-all-target-headers.hmap -iquote /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/iTerm2Shared-project-headers.hmap -I/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/Deployment/include -I/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/DerivedSources/x86_64 -I/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/DerivedSources -Wall -F/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/Deployment -F/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source -F/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/ColorPicker -F/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/ThirdParty -include /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/SharedPrecompiledHeaders/iTerm2-cauyqklpsqkfbgaxhoswxydlxwbf/iTerm2.pch -MMD -MT dependencies -MF /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/Objects-normal/x86_64/PTYWindow.d --serialize-diagnostics /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/Objects-normal/x86_64/PTYWindow.dia -c /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow.m -o /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/build/iTerm2.build/Deployment/iTerm2Shared.build/Objects-normal/x86_64/PTYWindow.o
/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow.m:114:18: error: '_delegate' is unavailable
        return ![_delegate anyFullScreen];
                 ^
In module 'AppKit' imported from /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:196:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate;
                         ^
/var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow.m:121:10: error: '_delegate' is unavailable
    if ([_delegate anyFullScreen]) {
         ^
In module 'AppKit' imported from /var/folders/wm/2rdmshp12cd574j22psq7lm00000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:196:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate;
                         ^
2 errors generated.
```

**Comment by hlolli** [comment]
I get similar error
```
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:33:58: error: '_delegate' is unavailable
    [[iTermController sharedInstance] setCurrentTerminal:_delegate];
                                                         ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:48:58: error: '_delegate' is unavailable
                                              inTerminal:_delegate
                                                         ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:55:13: error: '_delegate' is unavailable
    return [_delegate tabForSession:session];
            ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:71:58: error: '_delegate' is unavailable
                                              inTerminal:_delegate
                                                         ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:78:13: error: '_delegate' is unavailable
    return [_delegate tabForSession:session];
            ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:84:13: error: '_delegate' is unavailable
    return [_delegate tabs];
            ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:98:14: error: '_delegate' is unavailable
    return [[_delegate tabs] count];
             ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:102:13: error: '_delegate' is unavailable
    return [_delegate tabs][anIndex];
            ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:106:6: error: '_delegate' is unavailable
    [_delegate insertInTabs:replacementTab atIndex:anIndex];
     ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:107:6: error: '_delegate' is unavailable
    [_delegate closeTab:[_delegate tabs][anIndex + 1]];
     ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:107:26: error: '_delegate' is unavailable
    [_delegate closeTab:[_delegate tabs][anIndex + 1]];
                         ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:111:6: error: '_delegate' is unavailable
    [_delegate insertTab:tab atIndex:anIndex];
     ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:115:22: error: '_delegate' is unavailable
    NSArray *tabs = [_delegate tabs];
                     ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:116:6: error: '_delegate' is unavailable
    [_delegate closeTab:tabs[anIndex]];
     ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:121:13: error: '_delegate' is unavailable
    return [_delegate currentTab];
            ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
/var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/PTYWindow+Scripting.m:125:13: error: '_delegate' is unavailable
    return [_delegate currentSession];
            ^
In module 'AppKit' imported from /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/nix-build-iterm2-3.0.14.drv-0/source/sources/ProfileTableView.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:189:26: note: declaration uses __weak, but ARC is disabled
    __weak id            _delegate APPKIT_IVAR;
                         ^
16 errors generated.
```

**Comment by sikmir** [comment]
iterm2 build is still broken. I've tried with latest 3.3.11beta1.

**Comment by hexagonal-sun** [comment]
I think may have been fixed with  #58517?

**Comment by sikmir** [comment]
Still broken (iterm2-3.3.9):
```
/var/folders/wf/qxrs82v946n91pb5s71n3dy80000gp/T/nix-build-iterm2-3.3.9.drv-0/source/sources/DVRDecoder.m:235:34: error: expected ';' after top level declarator
static BOOL NS_WARN_UNUSED_RESULT SafeIncr(int summand, int addend, int *sum) {
                                 ^
                                 ;
...
/var/folders/wf/qxrs82v946n91pb5s71n3dy80000gp/T/nix-build-iterm2-3.3.9.drv-0/source/sources/DVRDecoder.m:313:1: error: missing '@end'
^
...
1 warning and 2 errors generated.
...

** BUILD FAILED **
```

**Comment by arkivm** [comment]
Works with `3.4.22` (test on both x86-64-darwin and aarch64-darwin). Mark as fixed?

**Comment by sikmir** [comment]
Fixed with https://github.com/NixOS/nixpkgs/pull/160417
