### ISSUE TITLE
VirtualBox is broken on master

### ISSUE THREAD

**Issue by rasendubi** [NixOS/nixpkgs#23257]
```
Checking for Qt5: 
  ** qt5 not found!
```

Also reproduced by Hydra: http://hydra.nixos.org/build/49488315.

The issue was introduced by https://github.com/NixOS/nixpkgs/commit/6542ea7f3102dcde476b102cb5cb7fb99f75e852 (https://github.com/NixOS/nixpkgs/pull/23239).

/cc @ttuegel 

### Steps to reproduce
```sh
nix-build -A virtualbox
```

## Technical details

* System: NixOS: 17.03.git.1aa77d0519 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 17.03.git.8def08a56c

**Comment by rasendubi** [comment]
examining configure.log, the interesting part is:
```
***** Checking Qt5 *****
(Qt5 from pkg-config)
compiling the following source file:
#include <QtGlobal>
extern "C" int main(void)
{
#if QT_VERSION >= 0x050302
  return 0;
#else
  return 1;
#endif
}
using the following command line:
g++  -fPIC -g -O -Wall -o /tmp/nix-build-virtualbox-5.1.14.drv-0/VirtualBox-5.1.14/.tmp_out /tmp/nix-build-virtualbox-5.1.14.drv-0/VirtualBox-5.1.14/.tmp_src.cc "-L/nix/store/rg4d03j01pa1vawgcvk7jcp4ba6aa61a-qtbase-5.7.1/lib -L/nix/store/rg4d03j01pa1vawgcvk7jcp4ba6aa61a-qtbase-5.7.1/lib -lQt5Core -lpthread -I/nix/store/5n6bpwng4cdh0fwmk1dq8vxwciddpmc5-qtbase-5.7.1-dev/include/QtCore -I/nix/store/5n6bpwng4cdh0fwmk1dq8vxwciddpmc5-qtbase-5.7.1-dev/include"
In file included from /nix/store/5n6bpwng4cdh0fwmk1dq8vxwciddpmc5-qtbase-5.7.1-dev/include/QtCore/qglobal.h:83:0,
                 from /nix/store/5n6bpwng4cdh0fwmk1dq8vxwciddpmc5-qtbase-5.7.1-dev/include/QtCore/QtGlobal:1,
                 from /tmp/nix-build-virtualbox-5.1.14.drv-0/VirtualBox-5.1.14/.tmp_src.cc:1:
/nix/store/5n6bpwng4cdh0fwmk1dq8vxwciddpmc5-qtbase-5.7.1-dev/include/QtCore/qcompilerdetection.h:562:6: error: #error Qt requires a C++11 compiler and yours does not seem to be that.
 #    error Qt requires a C++11 compiler and yours does not seem to be that.
      ^
```

**Comment by rasendubi** [comment]
Patched virtualvox configure to include `-std=c++11`:
```diff
diff --git a/pkgs/applications/virtualization/virtualbox/default.nix b/pkgs/applications/virtualization/virtualbox/default.nix
index 7512ddb6b0..14121660fa 100644
--- a/pkgs/applications/virtualization/virtualbox/default.nix
+++ b/pkgs/applications/virtualization/virtualbox/default.nix
@@ -66,6 +66,7 @@ in stdenv.mkDerivation {
     set -x
     sed -e 's@MKISOFS --version@MKISOFS -version@' \
         -e 's@PYTHONDIR=.*@PYTHONDIR=${if pythonBindings then python else ""}@' \
+        -e 's@CXX_FLAGS="\(.*\)"@CXX_FLAGS="-std=c++11 \1"@' \
         ${optionalString (!headless) ''
         -e 's@TOOLQT5BIN=.*@TOOLQT5BIN="${getDev qt5.qtbase}/bin"@' \
         ''} -i configure
```

Waiting for build to pass.

**Comment by rasendubi** [comment]
Build passed. Opened https://github.com/NixOS/nixpkgs/pull/23258

**Comment by bjornfor** [comment]
#23258 is merged, closing.
