### ISSUE TITLE
pyopengl: from OpenGL import GL throws error after version bump to 3.1.6

### ISSUE THREAD

**Issue by soooch** [NixOS/nixpkgs#217275]
### Describe the bug
`from OpenGL import GL` works in pyopengl 3.1.5, and doesn't with pyopengl 3.1.6.

### Steps To Reproduce
Contents of shell.nix, in nixpkgs root
```nix
with import ./default.nix {};
mkShell { buildInputs = [ (python3.withPackages (pp: with pp; [pyopengl])) ];
```
```console
$ python
Python 3.10.9 (main, Dec  6 2022, 18:44:57) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenGL import GL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/30c9s100xj1gj2zhnd60sv68b68hiwv8-python3-3.10.9-env/lib/python3.10/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/nix/store/30c9s100xj1gj2zhnd60sv68b68hiwv8-python3-3.10.9-env/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/nix/store/30c9s100xj1gj2zhnd60sv68b68hiwv8-python3-3.10.9-env/lib/python3.10/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/nix/store/30c9s100xj1gj2zhnd60sv68b68hiwv8-python3-3.10.9-env/lib/python3.10/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

### Expected behavior
There should be no error on importing `OpenGL.GL`.

### Additional context
This has happened before: https://github.com/NixOS/nixpkgs/issues/76822.
For me this breaks pyqtgraph

### Notify maintainers
@mweinelt

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.10, NixOS, 22.11 (Raccoon), 22.11.2483.49efda9011e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by soooch** [comment]
I don't have much experience with Nix, so I'm not sure if adding a test case for this is possible. If it is, I think it may be worthwhile to do so, given we've seen this issue twice.
