### PR TITLE
bundler: 2.2.24 -> 2.3.6

### LINKED ISSUE #150677: Vulnerability roundup 109: bundler-2.2.24: 1 advisory [7.3]
[search](https://search.nix.gsc.io/?q=bundler&i=fosho&repos=NixOS-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bundler+in%3Apath&type=Code)

* [ ] [CVE-2021-43809](https://nvd.nist.gov/vuln/detail/CVE-2021-43809) CVSSv3=7.3 (nixos-21.11, nixos-unstable)

### CVE-2021-43809

`Bundler` is a package for managing application dependencies in Ruby. In `bundler` versions before 2.2.33, when working with untrusted and apparently harmless `Gemfile`'s, it is not expected that they lead to execution of external code, unless that's explicit in the ruby code inside the `Gemfile` itself. However, if the `Gemfile` includes `gem` entries that use the `git` option with invalid, but seemingly harmless, values with a leading dash, this can be false. To handle dependencies that come from a Git repository instead of a registry, Bundler uses various commands, such as `git clone`. These commands are being constructed using user input (e.g. the repository URL). When building the commands, Bundler versions before 2.2.33 correctly avoid Command Injection vulnerabilities by passing an array of arguments instead of a command string. However, there is the possibility that a user input starts with a dash (`-`) and is therefore treated as an optional argument instead of a positional one. This can lead to Code Execution because some of the commands have options that can be leveraged to run arbitrary executables. Since this value comes from the `Gemfile` file, it can contain any character, including a leading dash. To exploit this vulnerability, an attacker has to craft a directory containing a `Gemfile` file that declares a dependency that is located in a Git repository. This dependency has to have a Git URL in the form of `-u./payload`. This URL will be used to construct a Git clone command but will be interpreted as the upload-pack argument. Then this directory needs to be shared with the victim, who then needs to run a command that evaluates the Gemfile, such as `bundle lock`, inside. This vulnerability can lead to Arbitrary Code Execution, which could potentially lead to the takeover of the system. However, the exploitability is very low, because it requires a lot of user interaction. Bundler 2.2.33 has patched this problem by inserting `--` as an argument before any positional arguments to those Git commands that were affected by this issue. Regardless of whether users can upgrade or not, they should review any untrustred `Gemfile`'s before running any `bundler` commands that may read them, since they can contain arbitrary ruby code.

-----
Scanned versions: nixos-21.11: 573095944e7; nixos-unstable: b0bf5f888d3.

### PR DESCRIPTION
**Pull request by FliegendeWurst**
###### Motivation for this change
Fix #150677

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
- [x] Tested basic functionality of all binary files: `bundler --help` works
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
~~Shouldn't we bump to version `2.22.33` (or any newer patch version) instead to avoid introducing regressions in stable release :thinking: ?~~

Sorry, this is pointing to `master`.

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/d2n3qffxd5niadqwbkv1ab1l2908pa3d-ruby2.7.5-language_detector-0.1.2.drv' failed with exit code 1; last 10 log lines:
  hint: 
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint:         git branch -m <name>
  Initialized empty Git repository in /private/tmp/nix-build-ruby2.7.5-language_detector-0.1.2.drv-0/language_detector-8910279/.git/
  installing
  buildFlags:
  Traceback (most recent call last):
  /nix/store/xpccsnlq8w8xnhmqsi8b9r37s995zyff-nix-bundle-install.rb:121:in `<main>': undefined method `with_build_args' for #<Bundler::RubygemsIntegration:0x00007fcbac181288> (NoMethodError)
```

preventing build of `anystyle-cli`

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/qvq8p9xzs9b0913aam3qvxfm8790g33f-ruby2.7.5-metasploit-framework-6.1.25.drv' failed with exit code 1; last 10 log lines:
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint:      git branch -m <name>
  Initialized empty Git repository in /private/tmp/nix-build-ruby2.7.5-metasploit-framework-6.1.25.drv-0/metasploit-framework-4a1ba0f/.git/
  installing
  buildFlags:
  fatal: Needed a single revision
  Traceback (most recent call last):
  /nix/store/xpccsnlq8w8xnhmqsi8b9r37s995zyff-nix-bundle-install.rb:121:in `<main>': undefined method `with_build_args' for #<Bundler::RubygemsIntegration:0x00007fb525871338> (NoMethodError)
```

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/xkpmir5bdf2kasx12jihskny5ff1vm9h-ruby2.7.5-vagrant-2.2.19.drv' failed with exit code 1; last 10 log lines:
  source root is vagrant-2.2.19
  setting SOURCE_DATE_EPOCH to timestamp 1636146944 of file vagrant-2.2.19/website/vercel.json
  patching sources
  configuring
  no configure script, doing nothing
  building
  installing
  buildFlags:
  Traceback (most recent call last):
  /nix/store/xpccsnlq8w8xnhmqsi8b9r37s995zyff-nix-bundle-install.rb:121:in `<main>': undefined method `with_build_args' for #<Bundler::RubygemsIntegration:0x00007fc39c8b2588> (NoMethodError)
```

preventing build of `vagrant`

**Comment by FliegendeWurst** [comment]
Fixed all three issues (caused by https://github.com/rubygems/rubygems/pull/5007).

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 156850` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>libsForQt512.kde-gtk-config</li>
    <li>libsForQt514.kde-gtk-config</li>
    <li>libvmi</li>
    <li>qemu_xen</li>
    <li>qemu_xen-light</li>
    <li>qemu_xen_4_10</li>
    <li>qemu_xen_4_10-light</li>
    <li>qubes-core-vchan-xen</li>
    <li>xen</li>
    <li>xen-light</li>
    <li>xen-slim</li>
    <li>xenPackages.xen-light</li>
    <li>xenPackages.xen-slim</li>
    <li>xenPackages.xen-vanilla</li>
    <li>xenPackages.xen_4_10-light</li>
    <li>xenPackages.xen_4_10-slim</li>
    <li>xenPackages.xen_4_10-vanilla</li>
    <li>xen_4_10</li>
    <li>xen_4_10-light</li>
    <li>xen_4_10-slim</li>
  </ul>
</details>
<details>
  <summary>54 packages failed to build:</summary>
  <ul>
    <li>arcan.xarcan</li>
    <li>blightmud-tts</li>
    <li>btrbk</li>
    <li>cewl</li>
    <li>chromium</li>
    <li>compactor</li>
    <li>credslayer</li>
    <li>dasher</li>
    <li>ddar</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>fast-cli</li>
    <li>gitaly</li>
    <li>gitlab</li>
    <li>gitlab-ee</li>
    <li>haka</li>
    <li>hfinger</li>
    <li>mastodon</li>
    <li>mikutter</li>
    <li>mkvtoolnix</li>
    <li>mpdcron</li>
    <li>oni2</li>
    <li>orca</li>
    <li>ostinato</li>
    <li>pantheon.elementary-session-settings</li>
    <li>puppeteer-cli</li>
    <li>python310Packages.gruut</li>
    <li>python310Packages.phonemizer</li>
    <li>python310Packages.pyshark</li>
    <li>python39Packages.pyshark</li>
    <li>redmine</li>
    <li>reveal-md</li>
    <li>sharedown</li>
    <li>showoff</li>
    <li>stellar-core</li>
    <li>termshark</li>
    <li>tts</li>
    <li>ungoogled-chromium</li>
    <li>vulnix</li>
    <li>warzone2100</li>
    <li>weechat</li>
    <li>weechat-unwrapped</li>
    <li>wifite2</li>
    <li>wireshark (wireshark-qt)</li>
    <li>wireshark-cli</li>
    <li>wpscan</li>
    <li>wsjtx</li>
    <li>xcode-install</li>
    <li>xcpretty</li>
    <li>yarn2nix</li>
    <li>yosys-bluespec</li>
    <li>zerotierone</li>
    <li>zsteg</li>
    <li>zyn-fusion (zynaddsubfx)</li>
  </ul>
</details>
<details>
  <summary>206 packages built:</summary>
  <ul>
    <li>_3llo</li>
    <li>actionlint</li>
    <li>alttab</li>
    <li>anystyle-cli</li>
    <li>arcan.all-wrapped</li>
    <li>arcan.arcan</li>
    <li>arcan.arcan-wrapped</li>
    <li>arcan.durden-wrapped</li>
    <li>espeak (arcan.espeak ,espeak-ng)</li>
    <li>arcan.pipeworld-wrapped</li>
    <li>arcan.prio-wrapped</li>
    <li>asciidoctor</li>
    <li>asciidoctor-with-extensions</li>
    <li>asmrepl</li>
    <li>astroid</li>
    <li>atinout</li>
    <li>automirror</li>
    <li>awesome (awesome-4-0)</li>
    <li>bat-extras.batgrep</li>
    <li>bitbucket-server-cli</li>
    <li>blogc</li>
    <li>bluespec</li>
    <li>bpftrace (linuxKernel.packages.hardkernel_4_14.bpftrace ,linuxKernel.packages.linux_4_14.bpftrace ,linuxKernel.packages.linux_4_14_hardened.bpftrace ,linuxKernel.packages.linux_4_19.bpftrace ,linuxKernel.packages.linux_4_19_hardened.bpftrace ,linuxKernel.packages.linux_4_4.bpftrace ,linuxKernel.packages.linux_4_9.bpftrace ,linuxKernel.packages.linux_5_10.bpftrace ,linuxKernel.packages.linux_5_10_hardened.bpftrace ,linuxKernel.packages.linux_5_15.bpftrace ,linuxKernel.packages.linux_5_15_hardened.bpftrace ,linuxKernel.packages.linux_5_16.bpftrace ,linuxKernel.packages.linux_5_4.bpftrace ,linuxKernel.packages.linux_5_4_hardened.bpftrace ,linuxKernel.packages.linux_hardened.bpftrace ,linuxKernel.packages.linux_latest_libre.bpftrace ,linuxKernel.packages.linux_libre.bpftrace ,linuxKernel.packages.linux_lqx.bpftrace ,linuxKernel.packages.linux_testing_bcachefs.bpftrace ,linuxKernel.packages.linux_xanmod.bpftrace ,linuxKernel.packages.linux_zen.bpftrace ,linuxPackages-libre.bpftrace ,linuxPackages.bpftrace ,linuxPackages_4_14_hardened.bpftrace ,linuxPackages_4_19_hardened.bpftrace ,linuxPackages_5_10_hardened.bpftrace ,linuxPackages_5_15_hardened.bpftrace ,linuxPackages_5_4_hardened.bpftrace ,linuxPackages_hardened.bpftrace ,linuxPackages_hardkernel_latest.bpftrace ,linuxPackages_latest-libre.bpftrace ,linuxPackages_latest.bpftrace ,linuxPackages_lqx.bpftrace ,linuxPackages_testing_bcachefs.bpftrace ,linuxPackages_xanmod.bpftrace ,linuxPackages_zen.bpftrace)</li>
    <li>brakeman</li>
    <li>bundix</li>
    <li>bundler</li>
    <li>bundler-audit</li>
    <li>bupstash</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>cadre</li>
    <li>cargo-update</li>
    <li>castget</li>
    <li>cbor-diag</li>
    <li>ccache</li>
    <li>ccacheStdenv</li>
    <li>ccacheWrapper</li>
    <li>cddl</li>
    <li>chefdk</li>
    <li>cinnamon.mint-themes</li>
    <li>code-server</li>
    <li>colorls</li>
    <li>compass</li>
    <li>corundum</li>
    <li>cpcfs</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>cucumber</li>
    <li>danger-gitlab</li>
    <li>dep2nix</li>
    <li>direwolf</li>
    <li>docker-sync</li>
    <li>doing</li>
    <li>drake</li>
    <li>drbd</li>
    <li>ejabberd</li>
    <li>ejson</li>
    <li>elixir_ls</li>
    <li>elm-github-install</li>
    <li>esh</li>
    <li>fastlane</li>
    <li>flock</li>
    <li>fluentd</li>
    <li>foreman</li>
    <li>fpm</li>
    <li>fusuma</li>
    <li>geteltorito</li>
    <li>git-fame</li>
    <li>git-lfs</li>
    <li>github-backup</li>
    <li>github-changelog-generator</li>
    <li>gitlab-triage</li>
    <li>gnvim</li>
    <li>go2nix</li>
    <li>gollum</li>
    <li>google-chrome</li>
    <li>google-chrome-beta</li>
    <li>google-chrome-dev</li>
    <li>gruut (python39Packages.gruut)</li>
    <li>gruut-ipa (python39Packages.gruut-ipa)</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.neuron</li>
    <li>haskellPackages.nvfetcher</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>haste-client</li>
    <li>hiera-eyaml</li>
    <li>homesick</li>
    <li>html-proofer</li>
    <li>httplz</li>
    <li>hue-cli</li>
    <li>image_optim</li>
    <li>ipcalc</li>
    <li>iruby</li>
    <li>jekyll</li>
    <li>jsduck</li>
    <li>jsonnet</li>
    <li>keepassxc</li>
    <li>kramdown-asciidoc</li>
    <li>krane</li>
    <li>ledger-web</li>
    <li>libsForQt5.kde-gtk-config (libsForQt515.kde-gtk-config ,plasma5Packages.kde-gtk-config)</li>
    <li>licensee</li>
    <li>linux-router</li>
    <li>linux-router-without-wifi</li>
    <li>lolcat</li>
    <li>lvmsync</li>
    <li>mailcatcher</li>
    <li>maphosts</li>
    <li>matter-compiler</li>
    <li>mdcat</li>
    <li>mdl</li>
    <li>metasploit</li>
    <li>mkvtoolnix-cli</li>
    <li>mob</li>
    <li>mpvScripts.convert</li>
    <li>mruby</li>
    <li>neovim-qt</li>
    <li>neovim-remote</li>
    <li>neuron-notes</li>
    <li>newsboat</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>numix-gtk-theme</li>
    <li>nux</li>
    <li>nvfetcher</li>
    <li>nvimpager</li>
    <li>ocf-resource-agents</li>
    <li>ocserv</li>
    <li>one_gadget</li>
    <li>openvscode-server</li>
    <li>openwebrx</li>
    <li>overcommit</li>
    <li>oxidized</li>
    <li>papertrail</li>
    <li>pgsync</li>
    <li>pistol</li>
    <li>plausible</li>
    <li>pleroma</li>
    <li>polar</li>
    <li>prefetch-yarn-deps</li>
    <li>procodile</li>
    <li>pry</li>
    <li>pt</li>
    <li>puppet-bolt</li>
    <li>puppet-lint</li>
    <li>pws</li>
    <li>python310Packages.gruut-ipa</li>
    <li>python39Packages.phonemizer</li>
    <li>r10k</li>
    <li>rake</li>
    <li>reckon</li>
    <li>redis-dump</li>
    <li>reposurgeon</li>
    <li>riemann-dash</li>
    <li>riemann-tools</li>
    <li>ripgrep</li>
    <li>ripgrep-all</li>
    <li>rnp</li>
    <li>ronn</li>
    <li>roundup</li>
    <li>ruby-zoom</li>
    <li>rubyPackages.atk (rubyPackages_2_7.atk)</li>
    <li>rubyPackages.gdk_pixbuf2 (rubyPackages_2_7.gdk_pixbuf2)</li>
    <li>rubyPackages.gtk2 (rubyPackages_2_7.gtk2)</li>
    <li>rubyPackages.sassc (rubyPackages_2_7.sassc)</li>
    <li>rubyPackages_3_0.atk</li>
    <li>rubyPackages_3_0.gdk_pixbuf2</li>
    <li>rubyPackages_3_0.gtk2</li>
    <li>rubyPackages_3_0.sassc</li>
    <li>rubyPackages_3_1.atk</li>
    <li>rubyPackages_3_1.gdk_pixbuf2</li>
    <li>rubyPackages_3_1.gtk2</li>
    <li>rubyPackages_3_1.sassc</li>
    <li>rufo</li>
    <li>sass</li>
    <li>scss-lint</li>
    <li>sensu</li>
    <li>spacevim</li>
    <li>sparkleshare</li>
    <li>speechd</li>
    <li>sqlint</li>
    <li>styx</li>
    <li>sycl-info</li>
    <li>t</li>
    <li>tapview</li>
    <li>taskjuggler</li>
    <li>td</li>
    <li>teamocil</li>
    <li>terraform-landscape</li>
    <li>terraforming</li>
    <li>timetrap</li>
    <li>timewarrior</li>
    <li>travis</li>
    <li>tree-from-tags</li>
    <li>twurl</li>
    <li>uniscribe</li>
    <li>update-nix-fetchgit</li>
    <li>vagrant</li>
    <li>vgo2nix</li>
    <li>vimPlugins.command-t</li>
    <li>vpsfree-client</li>
    <li>vscode-extensions.asciidoctor.asciidoctor-vscode</li>
    <li>watson-ruby</li>
    <li>wayback_machine_downloader</li>
    <li>webcat</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Not sure why so many packages were rebuild, maybe a bug on nixpkgs-review :thinking: ?

**Comment by FliegendeWurst** [comment]
nixpkgs-review:

```
2 packages marked as broken and skipped:
libsForQt512.kde-gtk-config libsForQt514.kde-gtk-config

10 packages skipped:
burpsuite chromium chromiumBeta chromiumDev fast-cli oni2 puppeteer-cli reveal-md sharedown ungoogled-chromium

7 packages failed to build:
blightmud-tts ddar mpdcron python310Packages.gruut python310Packages.phonemizer showoff vulnix

242 packages built:
_3llo actionlint alttab anystyle-cli arcan.all-wrapped arcan.arcan arcan.arcan-wrapped arcan.durden-wrapped arcan.espeak arcan.pipeworld-wrapped arcan.prio-wrapped arcan.xarcan asciidoctor asciidoctor-with-extensions asmrepl astroid atinout automi
rror awesome bat-extras.batgrep bitbucket-server-cli blogc bluespec bpftrace brakeman btrbk bundix bundler bundler-audit bupstash cabal2nix cached-nix-shell cadre cargo-update castget cbor-diag ccache ccacheStdenv ccacheWrapper cddl cewl chefdk ci
nnamon.mint-themes code-server colorls compactor compass corundum cpcfs crate2nix credslayer crystal2nix cucumber danger-gitlab dasher dep2nix direwolf discourse discourseAllPlugins docker-sync doing drake drbd ejabberd ejson elixir_ls elm-github-
install esh fastlane flock fluentd foreman fpm fusuma geteltorito git-fame git-lfs gitaly github-backup github-changelog-generator gitlab gitlab-ee gitlab-triage gnvim go2nix gollum google-chrome google-chrome-beta google-chrome-dev gruut gruut-ip
a haka haste-client hfinger hiera-eyaml homesick html-proofer httplz hue-cli image_optim ipcalc iruby jekyll jsduck jsonnet keepassxc kramdown-asciidoc krane ledger-web libsForQt5.kde-gtk-config licensee linux-router linux-router-without-wifi lolc
at lvmsync mailcatcher maphosts mastodon matter-compiler mdcat mdl metasploit mikutter mkvtoolnix mkvtoolnix-cli mob mpvScripts.convert mruby neovim neovim-qt neovim-remote neuron-notes newsboat nix-prefetch-git nix-prefetch-scripts nix-update-sou
rce numix-gtk-theme nux nvfetcher nvimpager ocf-resource-agents ocserv one_gadget openvscode-server openwebrx orca ostinato overcommit oxidized pantheon.elementary-session-settings papertrail pgsync pistol plausible pleroma polar prefetch-yarn-dep
s procodile pry pt puppet-bolt puppet-lint pws python310Packages.gruut-ipa python310Packages.pyshark python39Packages.phonemizer python39Packages.pyshark r10k rake reckon redis-dump redmine reposurgeon riemann-dash riemann-tools ripgrep ripgrep-all rnp ronn roundup ruby-zo
om rubyPackages.atk rubyPackages.gdk_pixbuf2 rubyPackages.gtk2 rubyPackages.sassc rubyPackages_3_0.atk rubyPackages_3_0.gdk_pixbuf2 rubyPackages_3_0.gtk2 rubyPackages_3_0.sassc rubyPackages_3_1.atk rubyPackages_3_1.gdk_pixbuf2 rubyPackages_3_1.gtk
2 rubyPackages_3_1.sassc rufo sass scss-lint sensu spacevim sparkleshare speechd sqlint stellar-core styx sycl-info t tapview taskjuggler td teamocil termshark terraform-landscape terraforming timetrap timewarrior travis tree-from-tags tts twurl u
niscribe update-nix-fetchgit vagrant vgo2nix vimPlugins.command-t vpsfree-client vscode-extensions.asciidoctor.asciidoctor-vscode warzone2100 watson-ruby wayback_machine_downloader webcat weechat weechat-unwrapped wifite2 wireshark wireshark-cli w
pscan wsjtx xcode-install xcpretty yarn2nix yosys-bluespec zerotierone zsteg zyn-fusion
```

Build failures are unrelated to this update (= same on master).

**Comment by thiagokokada** [comment]
> nixpkgs-review:

This looks much more sane than my output. Let me try again.

**Comment by thiagokokada** [comment]
> preventing build of `anystyle-cli`
> preventing build of `metasploit`
> preventing build of `vagrant`

@ofborg anystyle-cli metasploit vagrant

**Comment by thiagokokada** [comment]
> preventing build of `anystyle-cli`
> preventing build of `metasploit`
> preventing build of `vagrant`

@ofborg build anystyle-cli metasploit vagrant

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 156850` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>anystyle-cli</li>
<li>metasploit</li>
<li>vagrant</li>
</ul>
</details>
