### PR TITLE
rustc: 1.67.1 -> 1.68.1

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

https://github.com/rust-lang/rust/blob/master/RELEASES.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by figsoda — CHANGES_REQUESTED** [review]
Some hashes would probably need to be updated, see https://github.com/NixOS/nixpkgs/pull/217084

> [Cargo will introduce a change that will break our FODs for packages that use Git dependencies.](https://github.com/rust-lang/cargo/pull/11414)

**Comment by RaitoBezarius** [comment]
> Some hashes would probably need to be updated, see #217084
> 
> > [Cargo will introduce a change that will break our FODs for packages that use Git dependencies.](https://github.com/rust-lang/cargo/pull/11414)

Making a draft until I figure out all these FODs.

**Comment by figsoda** [comment]
There was a treewide hash change like this and @danieldk had a [script](https://github.com/NixOS/nixpkgs/pull/122016#issuecomment-841804693), maybe this will help speeding up the process

We can also merge https://github.com/NixOS/nixpkgs/pull/217084 before this and convert all the hashes to `cargoLock`, but this will require people to come to a consensus, which is not the case right not: https://github.com/NixOS/nixpkgs/pull/217084#issuecomment-1456894554

**Comment by yu-re-ka** [comment]
If we can somehow extract the Cargo.lock files from each package, we can determine if it needs updating based on if it has any git dependencies

**Comment by winterqt** [comment]
> If we can somehow extract the Cargo.lock files from each package, we can determine if it needs updating based on if it has any git dependencies

Steal my logic from #217084 for that, it should work for 99% of packages.

**Comment by RaitoBezarius** [comment]
I will not have time to perform the treewide before maybe this weekend or more days, so anyone who really want to have this change can go ahead. I'm also in favor of waiting a proper resolution for #217084 (e.g. a merge).

**Comment by RaitoBezarius** [comment]
> Could we enable fresh stabilized [sparse-registry](https://github.com/rust-lang/cargo/pull/11224/) for `fetchCargoTarball`? This can dramatically improve the fetching speed if we need a treewide hash update anyway.

Do you see this in this PR?

**Comment by oxalica** [comment]
> > Could we enable fresh stabilized [sparse-registry](https://github.com/rust-lang/cargo/pull/11224/) for `fetchCargoTarball`? This can dramatically improve the fetching speed if we need a treewide hash update anyway.
> 
> Do you see this in this PR?

No? I mean:
```diff
diff --git a/pkgs/build-support/rust/fetch-cargo-tarball/default.nix b/pkgs/build-support/rust/fetch-cargo-tarball/default.nix
index 36ab9316974..6c4f8e3053a 100644
--- a/pkgs/build-support/rust/fetch-cargo-tarball/default.nix
+++ b/pkgs/build-support/rust/fetch-cargo-tarball/default.nix
@@ -62,8 +62,13 @@ in stdenv.mkDerivation ({
     export CARGO_HOME=$(mktemp -d cargo-home.XXX)
     CARGO_CONFIG=$(mktemp cargo-config.XXXX)
 
-    if [[ -n "$NIX_CRATES_INDEX" ]]; then
     cat >$CARGO_HOME/config.toml <<EOF
+    [registries.crates-io]
+    protocol = 'sparse'
+    EOF
+
+    if [[ -n "$NIX_CRATES_INDEX" ]]; then
+    cat >>$CARGO_HOME/config.toml <<EOF
     [source.crates-io]
     replace-with = 'mirror'
     [source.mirror]
```

For `nix build -f . cargo-asm.cargoDeps -vL --rebuild`, sparse registry reduces building (fetching) time from 119.5s to 14.3s for me, which is about 8x speed.

**Comment by figsoda** [comment]
or we can set the environment variable `CARGO_REGISTRIES_CRATES_IO_PROTOCOL`

**Comment by zowoq** [comment]
> or we can set the environment variable `CARGO_REGISTRIES_CRATES_IO_PROTOCOL`

Opened a PR for this: https://github.com/NixOS/nixpkgs/pull/222444

**Comment by RaitoBezarius** [comment]
Upgrading.

**Comment by RaitoBezarius** [comment]
> Should we make it one commit?

Can do, but would only do it at "premerge-time" (just in case, we need to go back on the previous commit or something).

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/blob/4efa8434580af72e69bbe52c6bc37a90e9880cbc/pkgs/development/compilers/rust/1_68.nix#L10

`rustfmt` doesn't build, it will block `firefox` via `rust-bindgen`.

```
error: linking with `/nix/store/rj91g41smpmp92xvhx6rjxz6878bn2b4-gcc-wrapper-12.2.0/bin/cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/nix/store/gr0a596ki6sg8hhfn45zp1mm6z2ngfmw-rustc-1.68.1/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/rlhcbj4s8aa485k25c5czh2j85n7s15k-cargo-1.68.1/bin:/nix/store/gr0a5>
  = note: /nix/store/nydwzhllkq0a21dny69zdjczh6v275lb-binutils-2.40/bin/ld: cannot find -lLLVM-15: No such file or directory
          collect2: error: ld returned 1 exit status


error: could not compile `rustfmt-nightly` due to previous error
warning: build failed, waiting for other jobs to finish...
error: linking with `/nix/store/rj91g41smpmp92xvhx6rjxz6878bn2b4-gcc-wrapper-12.2.0/bin/cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/nix/store/gr0a596ki6sg8hhfn45zp1mm6z2ngfmw-rustc-1.68.1/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/rlhcbj4s8aa485k25c5czh2j85n7s15k-cargo-1.68.1/bin:/nix/store/gr0a5>
  = note: /nix/store/nydwzhllkq0a21dny69zdjczh6v275lb-binutils-2.40/bin/ld: cannot find -lLLVM-15: No such file or directory
          collect2: error: ld returned 1 exit status
```

**Comment by yu-re-ka** [comment]
Built firefox on x86_64-linux

**Comment by yu-re-ka** [comment]
@ofborg build fd

**Comment by yu-re-ka** [comment]
Built thunderbird on aarch64-linux

**Review by yu-re-ka — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
Should we add release notes for this upgrade?

**Comment by RaitoBezarius** [comment]
> > > Could we enable fresh stabilized [sparse-registry](https://github.com/rust-lang/cargo/pull/11224/) for `fetchCargoTarball`? This can dramatically improve the fetching speed if we need a treewide hash update anyway.
> > 
> > 
> > Do you see this in this PR?
> 
> No? I mean:
> 
> ```diff
> diff --git a/pkgs/build-support/rust/fetch-cargo-tarball/default.nix b/pkgs/build-support/rust/fetch-cargo-tarball/default.nix
> index 36ab9316974..6c4f8e3053a 100644
> --- a/pkgs/build-support/rust/fetch-cargo-tarball/default.nix
> +++ b/pkgs/build-support/rust/fetch-cargo-tarball/default.nix
> @@ -62,8 +62,13 @@ in stdenv.mkDerivation ({
>      export CARGO_HOME=$(mktemp -d cargo-home.XXX)
>      CARGO_CONFIG=$(mktemp cargo-config.XXXX)
>  
> -    if [[ -n "$NIX_CRATES_INDEX" ]]; then
>      cat >$CARGO_HOME/config.toml <<EOF
> +    [registries.crates-io]
> +    protocol = 'sparse'
> +    EOF
> +
> +    if [[ -n "$NIX_CRATES_INDEX" ]]; then
> +    cat >>$CARGO_HOME/config.toml <<EOF
>      [source.crates-io]
>      replace-with = 'mirror'
>      [source.mirror]
> ```
> 
> For `nix build -f . cargo-asm.cargoDeps -vL --rebuild`, sparse registry reduces building (fetching) time from 119.5s to 14.3s for me, which is about 8x speed.

Apologies, I meant: do you think I should do this change in this PR? I apologize if it has been taken aggressively. (English language barrier yadayada).

**Comment by oxalica** [comment]
> I meant: do you think I should do this change in this PR?

I mean, yes. You can cherry pick the smaller env var patch from #222444. It also causes no rebuild since it affects only FODs.

**Comment by RaitoBezarius** [comment]
> > I meant: do you think I should do this change in this PR?
> 
> I mean, yes. You can cherry pick the smaller env var patch from #222444. It also causes no rebuild since it affects only FODs.

Done, thank you and sorry again for realizing too late I misunderstood your message.

**Comment by vcunat** [comment]
Reproducible ICE is interesting?  https://hydra.nixos.org/build/214913529

**Comment by amjoseph-nixpkgs** [comment]
`rustc` can no longer be cross compiled (`build!=host`) as of this commit according to `git bisect`.

When building the `rustc`'s vendored libraries, they are unable to find `std::`, which I find quite baffling.  Any ideas?

Below is a sampling of the error messages (there are hundreds like this) from `nix build -f . -L pkgsCross.aarch64-multiplatform.rustc`:

```
rustc-aarch64-unknown-linux-gnu> error[E0463]: can't find crate for `std`
rustc-aarch64-unknown-linux-gnu>  --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:1:5
rustc-aarch64-unknown-linux-gnu>   |
rustc-aarch64-unknown-linux-gnu> 1 | use std::env;
rustc-aarch64-unknown-linux-gnu>   |     ^^^ can't find crate
rustc-aarch64-unknown-linux-gnu> error[E0463]: can't find crate for `std`
rustc-aarch64-unknown-linux-gnu>  --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:2:5
rustc-aarch64-unknown-linux-gnu>   |
rustc-aarch64-unknown-linux-gnu> 2 | use std::process::Command;
rustc-aarch64-unknown-linux-gnu>   |     ^^^ can't find crate
rustc-aarch64-unknown-linux-gnu> error[E0463]: can't find crate for `std`
rustc-aarch64-unknown-linux-gnu>  --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:3:5
rustc-aarch64-unknown-linux-gnu>   |
rustc-aarch64-unknown-linux-gnu> 3 | use std::str::{self, FromStr};
rustc-aarch64-unknown-linux-gnu>   |     ^^^ can't find crate
rustc-aarch64-unknown-linux-gnu> error: cannot find macro `println` in this scope
rustc-aarch64-unknown-linux-gnu>   --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:38:9
rustc-aarch64-unknown-linux-gnu>    |
rustc-aarch64-unknown-linux-gnu> 38 |         println!("cargo:rustc-cfg=no_btreemap_retain");
rustc-aarch64-unknown-linux-gnu>    |         ^^^^^^^
rustc-aarch64-unknown-linux-gnu> error: cannot find macro `println` in this scope
rustc-aarch64-unknown-linux-gnu>   --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:32:9
rustc-aarch64-unknown-linux-gnu>    |
rustc-aarch64-unknown-linux-gnu> 32 |         println!("cargo:rustc-cfg=no_btreemap_remove_entry");
rustc-aarch64-unknown-linux-gnu>    |         ^^^^^^^
rustc-aarch64-unknown-linux-gnu> error: cannot find macro `println` in this scope
rustc-aarch64-unknown-linux-gnu>   --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:26:9
rustc-aarch64-unknown-linux-gnu>    |
rustc-aarch64-unknown-linux-gnu> 26 |         println!("cargo:rustc-cfg=no_btreemap_get_key_value");
rustc-aarch64-unknown-linux-gnu>    |         ^^^^^^^
rustc-aarch64-unknown-linux-gnu> error: cannot find macro `println` in this scope
rustc-aarch64-unknown-linux-gnu>   --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:14:13
rustc-aarch64-unknown-linux-gnu>    |
rustc-aarch64-unknown-linux-gnu> 14 |             println!("cargo:rustc-cfg=limb_width_32");
rustc-aarch64-unknown-linux-gnu>    |             ^^^^^^^
rustc-aarch64-unknown-linux-gnu> error: cannot find macro `println` in this scope
rustc-aarch64-unknown-linux-gnu>   --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:11:13
rustc-aarch64-unknown-linux-gnu>    |
rustc-aarch64-unknown-linux-gnu> 11 |             println!("cargo:rustc-cfg=limb_width_64");
rustc-aarch64-unknown-linux-gnu>    |             ^^^^^^^
rustc-aarch64-unknown-linux-gnu> error[E0531]: cannot find tuple struct or tuple variant `Some` in this scope
rustc-aarch64-unknown-linux-gnu>   --> /build/rustc-1.68.0-src/vendor/serde_json/build.rs:19:9
rustc-aarch64-unknown-linux-gnu>    |
rustc-aarch64-unknown-linux-gnu> 19 |         Some(minor) => minor,
rustc-aarch64-unknown-linux-gnu>    |         ^^^^ not found in this scope
```

**Comment by lblasc** [comment]
Binaries generated by crate2nix (buildRustCrate) are much bigger after the last staging iteration, most likely do to rust bump (still checking), debug and release are affected.

I've tested on some internal crate.

Commit before merge `bf839a4b2031557eb43e77d39d343b7ecc84c692`:
```
150M    result/bin
```
After merge:
```
1.2G    result/bin
```

**Comment by RaitoBezarius** [comment]
Can you try by disabling auditable? (cargo-auditable)

**Comment by figsoda** [comment]
`buildRustCrate` doesn't have an auditable option

**Comment by lblasc** [comment]
It is not connected with rust version bump, after reverting to a 1.67.1 on master binaries are still much bigger.

**Comment by amjoseph-nixpkgs** [comment]
@Iblasc, unless you are 100% sure that it was this PR that caused your problem, you need to open a new issue for your problem (you can reference it here).  Otherwise the discussion keeps getting moved from one PR to another, pinging the wrong people.

> I've tested on some internal crate.

Please post a complete reproducer in the new issue when you open it.

Note: before https://github.com/NixOS/nixpkgs/pull/210843 `buildRustCrate` was unconditionally stripping all builds, including `debug` builds.  That was fixed by https://github.com/NixOS/nixpkgs/pull/210843.  Maybe you're doing a debug build?  If so, either switch to doing a release build or else strip manually.

**Comment by dzmitry-lahoda** [comment]
Interesting, it worked all with git deps before this PR. What was reason? 
All reasonably big projects work with git deps. And why to break what was warking before? would be awesome there would be warning before breaking people using working nix.

**Comment by dzmitry-lahoda** [comment]
sorry, thank you for hard work

https://opencollective.com/nixos/contributions/678610
