### PR TITLE
akonadi: Fixes build

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change
Fixes: https://github.com/NixOS/nixpkgs/issues/34032

@peterhoeg @adisbladis 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
Why do you escape " (double quote) inside an '' (2 single quotes)?

**Comment by bkchr** [comment]
Without I get the following error:
```<command-line>:0:86: error: 'mysqld' was not declared in this scope
/tmp/nix-build-akonadi-17.12.1.drv-0/akonadi-17.12.1/src/server/storage/dbconfigmysql.cpp:104:33: note: in expansion of macro 'NIXPKGS_MYSQL_MYSQLD'
     mMysqldPath = QLatin1String(NIXPKGS_MYSQL_MYSQLD);
```

**Comment by adisbladis** [comment]
Builds fine! Thanks 👍

**Comment by orivej** [comment]
I know this is not the first change that replaces `NIX_CFLAGS_COMPILE` with `CXXFLAGS`, but I have not yet seen an explanation why this is the right change. Since when and why did `NIX_CFLAGS_COMPILE` stop working?

**Comment by bkchr** [comment]
@orivej that is a good question! Maybe we should bissect to find the commit that caused the problem.

**Comment by bkchr** [comment]
I'm doing a `git bisect` now and hopefully that gives us an answer.

**Comment by bkchr** [comment]
Okay, finished. Git bisect says that the following commit is the first failing: https://github.com/NixOS/nixpkgs/commit/75d2a7dc4dd0dc084cbc1b47dc7f6b69566ee35c

After looking at the commit, I assume that the following line could be the problem?
https://github.com/NixOS/nixpkgs/commit/75d2a7dc4dd0dc084cbc1b47dc7f6b69566ee35c#diff-e846a595b53da93fc388a23603f424d2R17

@adisbladis @ttuegel

**Comment by ttuegel** [comment]
*sigh* I fixed that, and then I rebased, and for some reason Git ate my corrections. This happens practically every time I try to rebase; I probably just don't grok Git. I will open a new PR with the correction.
