### PR TITLE
staging-next 2022-08-16

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- important job(s): [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
- jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/185426

### CODE REVIEW

**Comment by zowoq** [comment]
https://hydra.nixos.org/build/187572594

I can't reproduce the test failure in `go_1_17.aarch64-linux`, could someone please restart it?

**Comment by tjni** [comment]
I hope https://github.com/NixOS/nixpkgs/pull/186580 fixes a couple hundred failures due to `orjson`.

**Comment by fabianhjr** [comment]
Highlights:

```
875d77ca0328df20cb4db308b29ef77bb25749d8 lib/systems: Add staticLibrary and library staticLibrary includes common extensions for static libraries library is a new common attribute that includes both shared and static extensions
90bb9606027b06cbbf4933b8936d8ba21bdc59d9 gperftools: 2.9.1 -> 2.10
26fcb83b996b0c9d3dcb0d662a4b848f5edf3890 openexr: 2.5.7 -> 2.5.8
// Meson 0.61.2 → 0.63.1
e442c9084ba66e37a63c79ece5c27537778f5f50 meson: 0.63.0 → 0.63.1
e474134ea0b474c29a9644b2fa09b35fabc060fb meson: 0.62.2 → 0.63.0
a4a300dfffa7f3fff348d22dda3ddd5abcfa62a2 meson: 0.61.2 → 0.62.2
afb4471ac3fcddbcd73e47eb397f309416caf6a5 gjs: 1.72.1 -> 1.72.2
a8c50530fc5d9ea950bd8bb0120a4b77c5dac2ce systemd: Enable oomd by default
b2db8358f9125efbc56887740c3d90c58e6e77bb python310Packages.orjson: 3.7.8 -> 3.7.12
e760223faa7d65cb0294edd44bde757e2be89b35 iproute: 5.18.0 -> 5.19.0
3cc71806a96286c4037688c8910a8bd4abedba4e slang: 2.3.2 -> 2.3.3
ad0cd6e56a9a469edfbc77242b0bac8783e8e9b4 cryptsetup: 2.4.3 -> 2.5.0 (#186249)
c20092f87855c6f92f1bad20203b2631a6a97b6f git: 2.37.1 -> 2.37.2
69f3e761d69f25d097f24e4a573a0b8aaf85c58c harfbuzz: 5.0.1 -> 5.1.0
19adc3341cf3adfdbd408646aedbf8e62ce3eece treewide: migrate to pythonPackages.unittestCheckHook
e8fbb38a51380fe6e56351b5750dddcccff79c4c pythonPackages.unittestCheckHook: init
51c62063e366d14e4353c85f22adb085330b9684 cargoSetupHook: set crt-static
0a9c3640d319a284095bbd53214c92d7a99c1c2a rustc: set crt-static flag
fb7811bf03398ced5cada7476e089a417db5c962 rustc: use autoPatchelfHook for bootstrap binaries
123cb930b3dee4d56a1924d1c33699c7b329af44 evcxr: 0.12.0 -> 0.13.0
46f98c157dceb3c6004388e7a92766c211e28ac8 tzdata: 2022a -> 2022b
e8d794e3197d64ed5e999d2c63e6efdda6ee3b57 libjpeg: 2.1.3 -> 2.1.4
af21e11d3f2618b848969c4f888a392f24580c19 llvmPackages_latest: 13 -> 14
59dd915c110fad911067c18aaffb53ac75b99015 rustc: 1.62.1 -> 1.63.0
d9972a62eb33f8f5f69bb223f298c53f3e2af84c rubygems: 3.2.26 -> 3.3.20
619489a2b9eeb18c326c5fee6fc43a91b449a329 python310Packages.ddt: 1.5.0 -> 1.6.0
6d980c0d8b9e9de643e5a153ef55d013e8746ecb postgresql_10: 10.21 -> 10.22
d1213d3dc8ade1eaa7c369b6c9628393ab2e2842 postgresql_11: 11.16 -> 11.17
2793fbe755d72d1cc5fa236d0d3764e3367a284b postgresql_12: 12.11 -> 12.12
4059636757ad2bdc9dcaac3e529cc7006d6ad50e postgresql_13: 13.7 -> 13.8
c9aa86be1159c8a3ac949387dc8c505383c443d4 postgresql_14: 14.4 -> 14.5
8c63b2f4f3fa67bfe0f87175bf9428ba0c709c26 python310Packages.setuptools-rust: 1.4.1 -> 1.5.0
ba541afca3eaec1424035843807d4a683f5cae11 nftables: 1.0.4 -> 1.0.5
8dd1594d04bd0e208241ce44c78109f3b2a10cb1 gamescope: rename libseat to seatd
54a173c0c1b67783b4ae09f309330b9746e1e548 gpgme: 1.17.1 -> 1.18.0
9be211b6a7ff658426fe9a12515663387b7b9c62 gst_all_1: 1.20.1 -> 1.20.3, fix CVE-2022-(192[0-5]|2122)
7659f31d69e512e19e1242c79f73227b69e2b8c5 systemd: 251.3 -> 251.4
1253ce601393f6ee2d05f7831d614ef3eb2f4974 libnftnl: 1.2.2 -> 1.2.3
fc5ade9c4c0d102471fc0a746b5dc2ffd1a8e929 python3Packages.sphinx-autodoc-typehints: 1.19.1 -> 1.19.2
8f9fefa98be860c3997c375eec6719f987438c92 python3Packages.sphinx: 5.0.2 -> 5.1.1
a42db97eb7cad4ec7df7ed9dc5e50131ad12db0f vim: 9.0.0135 -> 9.0.0180 and replace inactive maintainer
9ea219186dc0ddc0e538ded443a4072e50078159 apparmor: 3.0.4 -> 3.0.7
3bb4b724b46a46af0fb04946b8f9d150f1c8eb4d python310Packages.pybind11: 2.9.2 -> 2.10.0
e1a75d080ee2a9e6c6e144e8ccca0d7a76c7ed1c libtirpc: 1.2.7-rc4 -> 1.3.3, fix CVE-2021-46828
e3d4450eff5e6a7044311fbd3d7e162b2d68289c libwebp: 1.2.3 -> 1.2.4
ff3cb21db78a9de3babe3b09d15d2d6259f11e64 python3Packages.sqlalchemy: 1.4.39 -> 1.4.40
d56d587e855d762dab920a5a537ee317c066952b zlib: add fixed patch for CVE-2022-37434
597b9502cbb8bdacb3bfc8d401ed310871685dfc gnu-efi: 3.0.14 -> 3.0.15
4ed8247e1bf59829a4c2d68748900b0fe35a5a58 Vulkan: 1.3.211.0 -> 1.3.216.0
c9c802dfd8de386698ce97fde995fcca0cf14e9e gnutls: 3.7.6 -> 3.7.7, fix CVE-2022-2509
717e7bd2919620e06e3c97154216d68c28276c0b tree-sitter: strip only debug info by default
f0eb20ae862586a44d6473c2a5bcff82badf2dfe libgpg-error: 1.42 -> 1.45 (#185541)
b3b672d5a16a0e99dc112b9f65436555b11c3ab7 setup-hooks/separate-debug-info.sh: don't inhibit strip hook
a6daffb11876769af3f079a37516c1832048b9ea gcc: factor out $linkLib64toLib, move it from bash to nix
dfba0bf93b716a72b107fd182e01e5ba859dc013 gcc: do not create lib64->lib links on mips64n32
cbc80ff32b7c827f6a780688f251a6d592a873d5 gcc: add linkLib32toLib to create lib32->lib links
b1b8f456a15561ed92a1ee35f290741b8a7b8b96 libevdev: 1.12.1 -> 1.13.0
4eb32471e07342a43d9c0f11a387fa525e7e0a4c libjxl: split outputs
ff630bdc67ac5135ecd679c96fe51395dca5467e liblqr1: split outputs
2aefcbcab39bff7713e7ab16c174a821868d7931 speexdsp: 1.2.0 -> 1.2.1
b408d0f602b63057c7d4b3c60d5de2afa113ca89 pulseaudio: 15.0 -> 16.1
1f241270bff7a041c0eeb92ce03d3d0691805526 pciutils: 3.7.0 -> 3.8.0
8e8bd9977b2b54e20497915065f2c4dea3f7be22 libvpx: 1.11.0 -> 1.12.0
4697faa87a6d74b9f72a2ea222ba8ad15e0a89f6 libidn: 1.38 -> 1.41
e6927bd8553da91c8ba5140eb4318aa0a5575890 inetutils: 2.2 -> 2.3
a3cb00e4b2eb44ec2cf2463cd109cf872b7a8582 isocodes: 4.9.0 -> 4.11.0
e580321b984df7929e851f5e4ea3b515dd9df913 gsm: 1.0.19 -> 1.0.20
8d276aceaf7c9c08eedb009f47f8c0a217b33d8c ninja: 1.10.2 -> 1.11.0
```

**Comment by vcunat** [comment]
- [ ] `libreoffice*` builds have issues due to gpgme update.  `configure.ac` detection fails, apparently due to the check mixing C and C++ incorrectly.  But when I force-skipp that, I end up with linker errors during build anyway, e.g.:
  ```
  docpasswordhelper.cxx:(.text+0x2c74): undefined reference to `GpgME::initializeLibrary()'
  ```
  maintainers: @7c6f434c

**Comment by fabianhjr** [comment]
`libgccjit` fails during install:

```
make[1]: Leaving directory '/build/build'
/nix/store/zm90lg93qmzbvld6jdk00ny9nwn7nm2r-builder.sh: line 261: type: install_name_tool: not found
post-installation fixup
/nix/store/l29cpaj3l5wp8yr6gvmgccb9rdddv80p-libgccjit-11.3.0 /build/build
/build/build
/nix/store/1y9r8l6ksdcx1n6360vk8bvssipmpcq0-bootstrap-stage3-stdenv-linux/setup: line 106: pushd: no other directory
```

https://hydra.nixos.org/build/187702907/nixlog/1

**Comment by tjni** [comment]
Created #187531 to fix `python3Packages.bitstring`.

**Comment by vcunat** [comment]
- [ ] `libgccjit` regressed by PR #184908.  @trofi: perhaps you have an idea what's wrong?

**Comment by trofi** [comment]
`libgccjit` does not provide `lib` output and `pushd $lib` fails. Working on a fix. Should only affect `libgccjit`.

**Comment by vcunat** [comment]
`gnome-books` [broke](https://hydra.nixos.org/build/188046577) after meson update, similarly to https://gitlab.gnome.org/Archive/gnome-books/-/merge_requests/62 &ndash; but now the upstream project seems officially dead/archived.  @jtojnar: so we remove the package from nixpkgs?

**Comment by fabianhjr** [comment]
> `gnome-books` [broke](https://hydra.nixos.org/build/188046577) after meson update, similarly to https://gitlab.gnome.org/Archive/gnome-books/-/merge_requests/62 – but now the upstream project seems officially dead/archived. @jtojnar: so we remove the package from nixpkgs?

I would be inclined to patch it for now and opening a separate issue or pr for removal. (Or leaving a comment / warning about deprecation in the package)

**Comment by vcunat** [comment]
Well, anyone can suggest patches; I just didn't expect people to be interested in working on it, given the upstream state.  (The link was about an older meson update.)

**Comment by fabianhjr** [comment]
Ah, I misunderstood; then no upstream patch is available? Please disregard my previous message.

**Comment by jtojnar** [comment]
Right, no upstream patch. We should mark it broken and eventually remove.

**Comment by vcunat** [comment]
For people who want to help, _now_ is a relatively good moment to look at regressions, though there aren't really many (and some get covered in PR #187778):
https://hydra.nixos.org/eval/1777342?compare=1777343#tabs-now-fail
