### ISSUE TITLE
mitmproxy uninstallable in NixOS 20.09

### ISSUE THREAD

**Issue by tesujimath** [NixOS/nixpkgs#103992]
**Describe the bug**
Since upgrading to NixOS 20.09, I cannot install mitmproxy.

**To Reproduce**
With the nixos-20.09 channel
```
$ nix-channel --list
nixos-20.09 https://nixos.org/channels/nixos-20.09

$ nix-shell -p mitmproxy
```

**Expected behavior**
Package is installed.

**Screenshots**
Package fails to install.  Tail of output is as follows:
```
=========================== short test summary info ============================
FAILED test/mitmproxy/net/test_tcp.py::TestSSLUpstreamCertVerificationWBadHostname::test_mode_none_should_pass_without_sni
FAILED test/mitmproxy/net/test_tcp.py::TestSSLUpstreamCertVerificationWValidCertChain::test_mode_strict_w_pemfile_should_pass
FAILED test/mitmproxy/net/test_tcp.py::TestSSLUpstreamCertVerificationWValidCertChain::test_mode_strict_w_confdir_should_pass
FAILED test/mitmproxy/proxy/test_server.py::TestHTTPSUpstreamServerVerificationWTrustedCert::test_verification_w_confdir
FAILED test/mitmproxy/proxy/test_server.py::TestHTTPSUpstreamServerVerificationWTrustedCert::test_verification_w_pemfile
= 5 failed, 1484 passed, 1 deselected, 2 xfailed, 103 warnings in 93.92s (0:01:33) =
builder for '/nix/store/p2pw9y8jsdyll8c1rvsm2wq0yfdk08gn-python3.8-mitmproxy-5.2.drv' failed with exit code 1
error: build of '/nix/store/p2pw9y8jsdyll8c1rvsm2wq0yfdk08gn-python3.8-mitmproxy-5.2.drv' failed
```

**Additional context**

**Notify maintainers**
@fpletz @kamilchm

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
aji$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/wpfm6lk7dyiafvwa6n3s9dk62yv9h5sk-nix-info
copying path '/nix/store/wpfm6lk7dyiafvwa6n3s9dk62yv9h5sk-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09beta1346.05334ad7852 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(sjg): `"nixos-20.09-20.09.1819.f41c0fc7d8e, nixpkgs-21.03pre251181.dd1b7e377f6"`
 - channels(root): `"nixos-20.09beta1346.05334ad7852"`
 - nixpkgs: `/home/sjg/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by divanorama** [comment]
Have same failures in unstable channel
```
E               mitmproxy.exceptions.InvalidCertificateException: Certificate verification error for example.mitmproxy.org: self signed certificate (errno: 18, depth: 0)

mitmproxy/net/tcp.py:399: InvalidCertificateException
_ TestHTTPSUpstreamServerVerificationWTrustedCert.test_verification_w_confdir __

...
>           assert "Cannot validate hostname, SNI missing." in str(c.ssl_verification_error)
E           AssertionError: assert 'Cannot validate hostname, SNI missing.' in 'Certificate verification error for None: self signed certificate (errno: 18, depth: 0)'
E            +  where 'Certificate verification error for None: self signed certificate (errno: 18, depth: 0)' = str(InvalidCertificateException('Certificate verification error for None: self signed certificate (errno: 18, depth: 0)'))
E            +    where InvalidCertificateException('Certificate verification error for None: self signed certificate (errno: 18, depth: 0)') = <mitmproxy.net.tcp.TCPClient object at 0x7fffe4149d00>.ssl_verification_error

test/mitmproxy/net/test_tcp.py:303: AssertionError
_ TestSSLUpstreamCertVerificationWValidCertChain.test_mode_strict_w_pemfile_should_pass _
...
>       raise exception_type(errors)
E       OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

/nix/store/6nc0npzz9sxqczgxx6vy87x9wnm4gfxl-python3.8-pyOpenSSL-19.1.0/lib/python3.8/site-packages/OpenSSL/_util.py:54: Error

During handling of the above exception, another exception occurred:

self = <test.mitmproxy.net.test_tcp.TestSSLUpstreamCertVerificationWValidCertChain object at 0x7fffe435ad00>
tdata = <mitmproxy.utils.data.Data object at 0x7fffe435ad90>

    def test_mode_strict_w_confdir_should_pass(self, tdata):
        c = tcp.TCPClient(("127.0.0.1", self.port))
        with c.connect():
>           c.convert_to_tls(
                sni="example.mitmproxy.org",
                verify=SSL.VERIFY_PEER,
                ca_path=cdata.path("data/verificationcerts/")
            )

test/mitmproxy/net/test_tcp.py:344:
```

**Comment by divanorama** [comment]
git bisect points to c2526545844bdbb8347f9d9169a77728bf2bdd73 for when it broke in master, which is a merge commit so will try bisecting further

**Comment by divanorama** [comment]
following the branch bisect points at 39447e15915566daf53104409fa74d3f0c92f73b which just bumps openssl 1.1.1.g->1.1.1h
Not very clear from Changelog https://www.openssl.org/news/changelog.html#openssl-111 what could be the cause, could be
> Certificates with explicit curve parameters are now disallowed in verification chains if the X509_V_FLAG_X509_STRICT flag is used.

**Comment by divanorama** [comment]
https://github.com/mitmproxy/mitmproxy/blob/e9ab1debeaa770b2d32336c8e451fd5cd77b976a/test/mitmproxy/net/test_tcp.py#L317
https://github.com/mitmproxy/mitmproxy/tree/master/test/mitmproxy/net/data/verificationcerts
all certs seem to be rsa rather than elliptic curve (checked via openssl x509 -text -noout -in ...), so probably some other openssl change

**Comment by divanorama** [comment]
https://github.com/openssl/openssl/issues/1418 looks more promising, and likely mitmproxy needs some fixes in tests

**Comment by divanorama** [comment]
mitmproxy has a fix in https://github.com/mitmproxy/mitmproxy/pull/4255 which is part of 5.3.0 https://github.com/mitmproxy/mitmproxy/releases
