### PR TITLE
python3Packages.sqlobject: remove paste from dependencies

### PR DESCRIPTION
**Pull request by dotlambda**
@SuperSandro2000 This breaks mediagoblin.

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [x] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

**Comment by dotlambda** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 538451`
Commit: `963522383e6bfda226e3e7f5da125a1a10f90dfc`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>blink-qt</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python313Packages.sqlobject</li>
    <li>python314Packages.sqlobject</li>
  </ul>
</details>


---
<details>
<summary>blink-qt</summary>
<pre>  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 938, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 759, in exec_module
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 491, in _call_with_frames_removed
  File &quot;/nix/store/0rsm1cp7q05s606vsp5jamjadxw2ikcq-blink-qt-6.0.4/lib/python3.14/site-packages/blink/__init__.py&quot;, line 17, in &lt;module&gt;
    from sipsimple.application import SIPApplication
  File &quot;/nix/store/hgd8dp2cpjq7jhs8ikhv808b0x56g6na-python3.14-python3-sipsimple-5.3.3.2/lib/python3.14/site-packages/sipsimple/application.py&quot;, line 27, in &lt;module&gt;
    from sipsimple.account import AccountManager
  File &quot;/nix/store/hgd8dp2cpjq7jhs8ikhv808b0x56g6na-python3.14-python3-sipsimple-5.3.3.2/lib/python3.14/site-packages/sipsimple/account/__init__.py&quot;, line 27, in &lt;module&gt;
    from sipsimple.account.xcap import XCAPManager
  File &quot;/nix/store/hgd8dp2cpjq7jhs8ikhv808b0x56g6na-python3.14-python3-sipsimple-5.3.3.2/lib/python3.14/site-packages/sipsimple/account/xcap/__init__.py&quot;, line 17, in &lt;module&gt;
    from xcaplib.green import XCAPClient
  File &quot;/nix/store/8y151s809xr7gama4bnpj2ly12k5l53p-python3.14-xcaplib-2.0.2-unstable-2026-01-23/lib/python3.14/site-packages/xcaplib/green.py&quot;, line 2, in &lt;module&gt;
    from eventlib.green import socket, ssl, httplib, urllib2
  File &quot;/nix/store/81blbfndj6qh68pbnjpwh7dspdbvlq5q-python3.14-python3-eventlib-0.3.1/lib/python3.14/site-packages/eventlib/green/urllib2.py&quot;, line 29, in &lt;module&gt;
    from eventlib.green.urllib import (unwrap, unquote, splittype, splithost, quote,
         addinfourl, splitport, splitquery,
         splitattr, ftpwrapper, noheaders, splituser, splitpasswd, splitvalue)
  File &quot;/nix/store/81blbfndj6qh68pbnjpwh7dspdbvlq5q-python3.14-python3-eventlib-0.3.1/lib/python3.14/site-packages/eventlib/green/urllib.py&quot;, line 10, in &lt;module&gt;
    from urllib.request import( __all__, __version__, MAXFTPCACHE, ftpcache, ftpwrapper, _noheaders, noheaders, proxy_bypass, addinfourl, url2pathname, getproxies)
ImportError: cannot import name &#x27;MAXFTPCACHE&#x27; from &#x27;urllib.request&#x27; (/nix/store/jxyrvv4gbpnp3ap5iy7wxwl1sg4x2x88-python3-3.14.6/lib/python3.14/urllib/request.py)</pre>
</details>

File: pkgs/development/python-modules/paste/default.nix [hunk 1]
```diff
@@ -45,6 +45,7 @@ buildPythonPackage rec {
   pythonNamespaces = [ "paste" ];
 
   meta = {
+    broken = lib.versionAtLeast setuptools.version "82"; # https://github.com/pasteorg/paste/pull/105
```
Comment (SuperSandro2000) [inline pkgs/development/python-modules/paste/default.nix]: Why not use setuptools_80 instead?

Comment (dotlambda) [reply pkgs/development/python-modules/paste/default.nix]: cause that can't be propagated

**Comment by phanirithvij** [comment]
I'll open a new PR for blink-qt to staging-next based on top of this pr.

File: pkgs/development/python-modules/paste/default.nix (hunk 1 above)
Comment (SuperSandro2000) [reply pkgs/development/python-modules/paste/default.nix]: I don't think we need that even 

```
 ➜ rg setuptools
tox.ini
7:    setuptools

setup.py
12:from setuptools import setup, find_packages
58:        'setuptools',  # pkg_resources

docs/developer-features.txt
54:  serve using the Setuptools ``pkg_resources`` resource API.

docs/news.txt
99:* Update setup.py to work with setuptools 50.1.0+
```

Comment (SuperSandro2000) [reply pkgs/development/python-modules/paste/default.nix]: Oh, we need pkg_resources, not setuptools ...

**Review by phanirithvij — APPROVED** [review]

File: pkgs/development/python-modules/paste/default.nix (hunk 1 above)
Comment (dotlambda) [reply pkgs/development/python-modules/paste/default.nix]: If you really care about mediagoblin you can use overrideScope to pin setuptools to setuptools_80 but that will make mediagoblin very expensive to build

**Comment by SuperSandro2000** [comment]
Mediagoblin should work again with #538703 . I cannot fully test it end to end due to missing build capacity to test things on staging-next.

**Comment by vcunat** [comment]
As staging-next merged to master now, I don't expect you want to target it anymore.

**Comment by mdaniels5757** [comment]
Dropped commit 1ddad703aec13b69ea475c4eb2e6316caf239fe0, as it's redundant to the already-merged e1a93c635e02c2cb4573ba305564cb3b56e9798b.

**Comment by mdaniels5757** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 538451`
Commit: `3baf5a75f47bbf66a50a7b83c7fae2d91ca2ec48`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>blink-qt</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python313Packages.sqlobject</li>
    <li>python314Packages.sqlobject</li>
  </ul>
</details>


---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>blink-qt</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python313Packages.sqlobject</li>
    <li>python314Packages.sqlobject</li>
  </ul>
</details>


---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python313Packages.sqlobject</li>
    <li>python314Packages.sqlobject</li>
  </ul>
</details>

**Review by mdaniels5757 — APPROVED** [review]
`blink-qt` is failing because `python3Packages.otr` is: https://hydra.nixos.org/build/338797018
