### ISSUE TITLE
Calligra office build fails on unstable branch

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#137794]
```
[ 28%] Linking CXX shared library libkotext.so
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: CMakeFiles/kotext.dir/styles/KoCharacterStyle.cpp.o: in function `KoCharacterStyle::Private::calculateFontYStretch(QString const&)':
KoCharacterStyle.cpp:(.text+0x833c): undefined reference to `FcPatternBuild'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x8367): undefined reference to `FcFontMatch'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x83a1): undefined reference to `FcPatternGetString'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x83fd): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x8405): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x854a): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x8552): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x8567): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x85a7): undefined reference to `FcPatternGetString'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x85c9): undefined reference to `FcPatternGetInteger'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x86b3): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x86bb): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x8764): undefined reference to `FcPatternDestroy'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: KoCharacterStyle.cpp:(.text+0x876c): undefined reference to `FcPatternDestroy'
collect2: error: ld returned 1 exit status
make[2]: *** [libs/text/CMakeFiles/kotext.dir/build.make:1759: libs/text/libkotext.so.17.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:10270: libs/text/CMakeFiles/kotext.dir/all] Error 2
```

Seems like some dependency versions diverged?

**Comment by trofi** [comment]
Hydra agrees it started failing in `master` in August: https://hydra.nixos.org/build/154262190.

Cc @Phreedom @ebzzry @zraexy 

Missing `FcPatternDestroy` sounds like a `fontconfig` underlinking. Trying to bisect.

**Comment by trofi** [comment]
Was not able to get to exact commit and got a bunch:

  There are only 'skip'ped commits left to test.
  The first bad commit could be any of:
  80a81926499ab966d5e15b8de1263540bf619149 (patch tweak, unlikely)
  ad874fdff11b38a9898e299b52dbce45a0587d3e (output tweak, maybe?)
  19a4317dd043adcc08445919134884ff46968c79 (patch tweak, unlikely)
  3198bfe23b2535ad7cd3d8078dc72d03f724560a (kde-frameworks upgrade, likely)

**Comment by trofi** [comment]
https://github.com/KDE/calligra/commit/62f510702ef9c34ac50f8d8601a4290ab558464c probably fixed it upstream.

**Comment by trofi** [comment]
Let's try to fix it with https://github.com/NixOS/nixpkgs/pull/139565
