### PR TITLE
darwin.Libsystem: fix build on 10.13.2

### PR DESCRIPTION
**Pull request by orivej**
###### Motivation for this change

Darwin stdenv does not build on macOS 10.13.2 with the error:
```
Undefined symbols for architecture x86_64:
  "_host_zone_info", referenced from:
     -reexported_symbols_list command line option
ld: symbol(s) not found for architecture x86_64
```

You can check with `nix-build --no-out-link -A darwin.Libsystem --check`.

###### Things done

I have checked that this fixes stdenv, but I have not rebuilt everything to see if this breaks anything.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LnL7** [comment]
Hmm, I thought I fixed this in staging.

**Comment by LnL7** [comment]
Looks like I forgot to merge https://github.com/NixOS/nixpkgs/pull/31907

**Comment by orivej** [comment]
[This](0419452113ebb135907257bb063cb690a4de0b52) commit says that it fixes 10.13, so I think that our patch fixes just 10.13.2.

**Comment by LnL7** [comment]
It could be 10.13.2 specific, the machine I tested with is also running the beta because of the kernel bug.

**Review by LnL7 — APPROVED** [review]
