### PR TITLE
godot: avoid builtin libraries where possible

### PR DESCRIPTION
**Pull request by corngood**
This tries to use as much from nixpkgs as possible.  It should help reduce build times, centralise dependencies, and avoid issues with library conflicts like:

https://github.com/godotengine/godot/pull/104893#issuecomment-3308472172

TODO:

- [x] fix 4.5 build failure
- [x] decide what to do about "System-provided icu4c or harfbuzz cause known issues for GDExtension (see github.com/godotengine/godot/issues/91401 and github.com/godotengine/godot/issues/100301)."

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [x] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [x] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by superherointj** [comment]
This is gold! Thanks for the amazing upkeep work you do!

**Comment by corngood** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 444063`
Commit: `612d5801e2e47925d538ab99689aba0e057aa53d`

---
### `x86_64-linux`
<details>
  <summary>:x: 11 packages failed to build:</summary>
  <ul>
    <li>find-billy</li>
    <li>godot (godotPackages.godot, godotPackages_4.godot, godotPackages_4_5.godot, godot_4, godot_4_5)</li>
    <li>godot-mono (godotPackages.godot-mono, godotPackages_4.godot-mono, godotPackages_4_5.godot-mono, godot_4-mono, godot_4_5-mono)</li>
    <li>godot-mono.debug (godotPackages.godot-mono.debug, godotPackages_4.godot-mono.debug, godotPackages_4_5.godot-mono.debug, godot_4-mono.debug, godot_4_5-mono.debug)</li>
    <li>godot-mono.man (godotPackages.godot-mono.man, godotPackages_4.godot-mono.man, godotPackages_4_5.godot-mono.man, godot_4-mono.man, godot_4_5-mono.man)</li>
    <li>godot.debug (godotPackages.godot.debug, godotPackages_4.godot.debug, godotPackages_4_5.godot.debug, godot_4.debug, godot_4_5.debug)</li>
    <li>godot.man (godotPackages.godot.man, godotPackages_4.godot.man, godotPackages_4_5.godot.man, godot_4.man, godot_4_5.man)</li>
    <li>godotPackages.export-template (godotPackages_4.export-template, godotPackages_4_5.export-template)</li>
    <li>godotPackages.export-template-mono (godotPackages_4.export-template-mono, godotPackages_4_5.export-template-mono)</li>
    <li>godotPackages.export-template-mono.debug (godotPackages_4.export-template-mono.debug, godotPackages_4_5.export-template-mono.debug)</li>
    <li>godotPackages.export-template.debug (godotPackages_4.export-template.debug, godotPackages_4_5.export-template.debug)</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 23 packages built:</summary>
  <ul>
    <li>arrow</li>
    <li>godotPackages_4_3.export-template</li>
    <li>godotPackages_4_3.export-template-mono</li>
    <li>godotPackages_4_3.export-template-mono.debug</li>
    <li>godotPackages_4_3.export-template.debug</li>
    <li>godot_4_3 (godotPackages_4_3.godot)</li>
    <li>godot_4_3-mono (godotPackages_4_3.godot-mono)</li>
    <li>godot_4_3-mono.debug (godotPackages_4_3.godot-mono.debug)</li>
    <li>godot_4_3-mono.man (godotPackages_4_3.godot-mono.man)</li>
    <li>godot_4_3.debug (godotPackages_4_3.godot.debug)</li>
    <li>godot_4_3.man (godotPackages_4_3.godot.man)</li>
    <li>godotPackages_4_4.export-template</li>
    <li>godotPackages_4_4.export-template-mono</li>
    <li>godotPackages_4_4.export-template-mono.debug</li>
    <li>godotPackages_4_4.export-template.debug</li>
    <li>godot_4_4 (godotPackages_4_4.godot)</li>
    <li>godot_4_4-mono (godotPackages_4_4.godot-mono)</li>
    <li>godot_4_4-mono.debug (godotPackages_4_4.godot-mono.debug)</li>
    <li>godot_4_4-mono.man (godotPackages_4_4.godot-mono.man)</li>
    <li>godot_4_4.debug (godotPackages_4_4.godot.debug)</li>
    <li>godot_4_4.man (godotPackages_4_4.godot.man)</li>
    <li>opengamepadui</li>
    <li>pixelorama</li>
  </ul>
</details>

---
<details>
<summary>Error logs: `x86_64-linux`</summary>
<details>
<summary>godot</summary>
<pre>Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwMath.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwMemPool.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwPostEffect.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRaster.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRenderer.cpp ...
Linking Static Library bin/obj/modules/libmodule_fbx.linuxbsd.editor.x86_64.a ...
Ranlib Library bin/obj/modules/libmodule_fbx.linuxbsd.editor.x86_64.a ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRle.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwShape.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwStroke.cpp ...
Compiling thirdparty/thorvg/src/loaders/external_webp/tvgWebpLoader.cpp ...
Compiling thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.cpp ...
Compiling modules/theora/register_types.cpp ...
thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.cpp:24:10: fatal error: turbojpeg.h: No such file or directory
   24 | #include &lt;turbojpeg.h&gt;
      |          ^~~~~~~~~~~~~
compilation terminated.
scons: *** [bin/obj/thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.linuxbsd.editor.x86_64.o] Error 1
scons: building terminated because of errors.
INFO: Time elapsed: 00:00:17.94</pre>
</details>
<details>
<summary>godotPackages.export-template</summary>
<pre>Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwImage.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwMath.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwMemPool.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwPostEffect.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRaster.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRenderer.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRle.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwShape.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwStroke.cpp ...
Compiling thirdparty/thorvg/src/loaders/external_webp/tvgWebpLoader.cpp ...
Compiling thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.cpp ...
Compiling modules/theora/register_types.cpp ...
Compiling modules/theora/video_stream_theora.cpp ...
thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.cpp:24:10: fatal error: turbojpeg.h: No such file or directory
   24 | #include &lt;turbojpeg.h&gt;
      |          ^~~~~~~~~~~~~
compilation terminated.
scons: *** [bin/obj/thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.linuxbsd.template_release.x86_64.o] Error 1
scons: building terminated because of errors.
INFO: Time elapsed: 00:00:47.37</pre>
</details>
<details>
<summary>godotPackages.export-template-mono</summary>
<pre>Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwMath.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwMemPool.cpp ...
Linking Static Library bin/obj/modules/libmodule_fbx.linuxbsd.template_release.x86_64.a ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwPostEffect.cpp ...
Ranlib Library bin/obj/modules/libmodule_fbx.linuxbsd.template_release.x86_64.a ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRaster.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRenderer.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwRle.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwShape.cpp ...
Compiling thirdparty/thorvg/src/renderer/sw_engine/tvgSwStroke.cpp ...
Compiling thirdparty/thorvg/src/loaders/external_webp/tvgWebpLoader.cpp ...
Compiling thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.cpp ...
thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.cpp:24:10: fatal error: turbojpeg.h: No such file or directory
   24 | #include &lt;turbojpeg.h&gt;
      |          ^~~~~~~~~~~~~
compilation terminated.
Compiling modules/theora/register_types.cpp ...
scons: *** [bin/obj/thirdparty/thorvg/src/loaders/external_jpg/tvgJpgLoader.linuxbsd.template_release.x86_64.o] Error 1
scons: building terminated because of errors.
INFO: Time elapsed: 00:00:19.77</pre>
</details>
</details>

**Comment by corngood** [comment]
I've been sitting on this since 4.4, and it looks like it needs a bit more work on 4.5.

**Comment by corngood** [comment]
I'm a bit worried about:

> System-provided icu4c or harfbuzz cause known issues for GDExtension

I'm not sure if this is going to be a practical problem with how things are linked in nixpkgs.  Maybe I'll try to make a test for it.

**Comment by corngood** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 444063`
Commit: `af0d5f6ea992d47b544c87d78393b92e59ae1fbc`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 34 packages built:</summary>
  <ul>
    <li>arrow</li>
    <li>find-billy</li>
    <li>godot (godotPackages.godot, godotPackages_4.godot, godotPackages_4_5.godot, godot_4, godot_4_5)</li>
    <li>godot-mono (godotPackages.godot-mono, godotPackages_4.godot-mono, godotPackages_4_5.godot-mono, godot_4-mono, godot_4_5-mono)</li>
    <li>godot-mono.debug (godotPackages.godot-mono.debug, godotPackages_4.godot-mono.debug, godotPackages_4_5.godot-mono.debug, godot_4-mono.debug, godot_4_5-mono.debug)</li>
    <li>godot-mono.man (godotPackages.godot-mono.man, godotPackages_4.godot-mono.man, godotPackages_4_5.godot-mono.man, godot_4-mono.man, godot_4_5-mono.man)</li>
    <li>godot.debug (godotPackages.godot.debug, godotPackages_4.godot.debug, godotPackages_4_5.godot.debug, godot_4.debug, godot_4_5.debug)</li>
    <li>godot.man (godotPackages.godot.man, godotPackages_4.godot.man, godotPackages_4_5.godot.man, godot_4.man, godot_4_5.man)</li>
    <li>godotPackages.export-template (godotPackages_4.export-template, godotPackages_4_5.export-template)</li>
    <li>godotPackages.export-template-mono (godotPackages_4.export-template-mono, godotPackages_4_5.export-template-mono)</li>
    <li>godotPackages.export-template-mono.debug (godotPackages_4.export-template-mono.debug, godotPackages_4_5.export-template-mono.debug)</li>
    <li>godotPackages.export-template.debug (godotPackages_4.export-template.debug, godotPackages_4_5.export-template.debug)</li>
    <li>godotPackages_4_3.export-template</li>
    <li>godotPackages_4_3.export-template-mono</li>
    <li>godotPackages_4_3.export-template-mono.debug</li>
    <li>godotPackages_4_3.export-template.debug</li>
    <li>godot_4_3 (godotPackages_4_3.godot)</li>
    <li>godot_4_3-mono (godotPackages_4_3.godot-mono)</li>
    <li>godot_4_3-mono.debug (godotPackages_4_3.godot-mono.debug)</li>
    <li>godot_4_3-mono.man (godotPackages_4_3.godot-mono.man)</li>
    <li>godot_4_3.debug (godotPackages_4_3.godot.debug)</li>
    <li>godot_4_3.man (godotPackages_4_3.godot.man)</li>
    <li>godotPackages_4_4.export-template</li>
    <li>godotPackages_4_4.export-template-mono</li>
    <li>godotPackages_4_4.export-template-mono.debug</li>
    <li>godotPackages_4_4.export-template.debug</li>
    <li>godot_4_4 (godotPackages_4_4.godot)</li>
    <li>godot_4_4-mono (godotPackages_4_4.godot-mono)</li>
    <li>godot_4_4-mono.debug (godotPackages_4_4.godot-mono.debug)</li>
    <li>godot_4_4-mono.man (godotPackages_4_4.godot-mono.man)</li>
    <li>godot_4_4.debug (godotPackages_4_4.godot.debug)</li>
    <li>godot_4_4.man (godotPackages_4_4.godot.man)</li>
    <li>opengamepadui</li>
    <li>pixelorama</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@corngood Can you rebase?

**Comment by superherointj** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 444063`
Commit: `b21494c0c5716d29bc908fffb4292677e799715b`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 35 packages built:</summary>
  <ul>
    <li>arrow</li>
    <li>find-billy</li>
    <li>godot</li>
    <li>godot-mono</li>
    <li>godot-mono.debug</li>
    <li>godot-mono.man</li>
    <li>godot.debug</li>
    <li>godot.man</li>
    <li>godotPackages.export-template</li>
    <li>godotPackages.export-template-mono</li>
    <li>godotPackages.export-template-mono.debug</li>
    <li>godotPackages.export-template.debug</li>
    <li>godotPackages_4_3.export-template</li>
    <li>godotPackages_4_3.export-template-mono</li>
    <li>godotPackages_4_3.export-template-mono.debug</li>
    <li>godotPackages_4_3.export-template.debug</li>
    <li>godotPackages_4_3.godot</li>
    <li>godotPackages_4_3.godot-mono</li>
    <li>godotPackages_4_3.godot-mono.debug</li>
    <li>godotPackages_4_3.godot-mono.man</li>
    <li>godotPackages_4_3.godot.debug</li>
    <li>godotPackages_4_3.godot.man</li>
    <li>godotPackages_4_4.export-template</li>
    <li>godotPackages_4_4.export-template-mono</li>
    <li>godotPackages_4_4.export-template-mono.debug</li>
    <li>godotPackages_4_4.export-template.debug</li>
    <li>godotPackages_4_4.godot</li>
    <li>godotPackages_4_4.godot-mono</li>
    <li>godotPackages_4_4.godot-mono.debug</li>
    <li>godotPackages_4_4.godot-mono.man</li>
    <li>godotPackages_4_4.godot.debug</li>
    <li>godotPackages_4_4.godot.man</li>
    <li>nixpkgs-manual</li>
    <li>opengamepadui</li>
    <li>pixelorama</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@corngood When executing Godot 4.5 (non-mono), I get the following error message:

image

I think, it may be related to the `mbedtls` change.

**Review by superherointj — APPROVED** [review]
Since `mbedtls` error also shows up in master.
And I'm not aware of another issue.
LGTM.
