### ISSUE TITLE
Agda doesn't build in master

### ISSUE THREAD

**Issue by livnev** [NixOS/nixpkgs#57746]
## Issue description

`haskellPackages.Agda` fails to build in `master`, though it works in `18.09`. Presumably related to the ghc version, so this is an issue related to but not the same as #53396 

### Steps to reproduce

```
~ » nix-env -f "<nixpkgs>" -iA haskellPackages.Agda                                                                         lev@dellian
installing 'Agda-2.5.4.2'
these derivations will be built:
  /nix/store/14ssivmx384whwr5902vas0pin6d066x-Agda-2.5.4.2.drv
building '/nix/store/14ssivmx384whwr5902vas0pin6d066x-Agda-2.5.4.2.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/klw6m24v8w3jbwym2w8gvg7p72pn8qlr-ghc-8.6.4.
unpacking sources
unpacking source archive /nix/store/7d86sgv4my21v3424l1c7vy6jvm3bid1-Agda-2.5.4.2.tar.gz
source root is Agda-2.5.4.2
setting SOURCE_DATE_EPOCH to timestamp 1540830739 of file Agda-2.5.4.2/stack-8.4.4.yaml
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-Agda-2.5.4.2.drv-0/setup-package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-Agda-2.5.4.2.drv-0/Main.o )

Setup.hs:23:56: error:
    • Couldn't match type ‘Distribution.System.Platform -> String’
                     with ‘[Char]’
      Expected type: String
        Actual type: Distribution.System.Platform -> String
    • Probable cause: ‘exeExtension’ is applied to too few arguments
      In the second argument of ‘(<.>)’, namely ‘exeExtension’
      In the second argument of ‘(</>)’, namely ‘"agda" <.> exeExtension’
      In the second argument of ‘(</>)’, namely
        ‘"agda" </> "agda" <.> exeExtension’
   |
23 |       agda   = buildDir info </> "agda" </> "agda" <.> exeExtension
   |                                                        ^^^^^^^^^^^^
builder for '/nix/store/14ssivmx384whwr5902vas0pin6d066x-Agda-2.5.4.2.drv' failed with exit code 1
error: build of '/nix/store/14ssivmx384whwr5902vas0pin6d066x-Agda-2.5.4.2.drv' failed
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-3-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(lev): `"nixpkgs-19.09pre172680.92ec809473e"`
 - nixpkgs: `/home/lev/.nix-defexpr/channels/nixpkgs`

**Comment by dredozubov** [comment]
same on `https://nixos.org/channels/nixpkgs-19.03-darwin`

**Comment by dredozubov** [comment]
It appears it's a duplicate of https://github.com/NixOS/nixpkgs/issues/55964

**Comment by laMudri** [comment]
With Agda 2.6.0 released today ([tested on GHC 8.6.4](https://github.com/agda/agda/blob/master/Agda.cabal#L40)), this should fix itself when the next Hackage update happens.

**Comment by phile314** [comment]
For me it builds on current master ( dd641f7 ), this appears to be fixed.

**Comment by taojang** [comment]
I run into the same issue. But I've found a workaround using overlay.

```
cat ~/.config/nixpkgs/overlays/agdastdlib.nix                                              ~
self: super: 
{
  AgdaStdlib = super.AgdaStdlib.override {
    agda = super.agda.override {
      Agda = self.haskell.packages.ghc844.Agda;
    };
  };
}
```

Then I can install both agda and agda-stdlib
```
nix-env -f "<nixpkgs>" -iA haskell.packages.ghc844.Agda
nix-env -f "<nixpkgs>" -iA AgdaStdlib

**Comment by taojang** [comment]
There are still issues with above method, I ended up with this:

```
cat .config/nixpkgs/overlays/agda.nix                                                      ~
let
  nixpkgs = builtins.fetchTarball rec {
    url = "https://github.com/NIXOS/nixpkgs/archive/c89b2de425db938a06a418a11f792ca1ab7ea9ff.tar.gz";
    sha256 = "1qmbxh0b84pgj9qxs4ajqp534mb8dw263pkl8cmhyxq1fvvzr0dn";
  };

  pkgs = import nixpkgs {};
  nixexpr = pkgs.fetchgit {
    url = "https://github.com/srdqty/nix-agda-with-packages";
    rev = "f109205c74490f7e5308d39c3beab8ba86253eab";
    sha256 = "1fsjxy7i2l7px43hgz1vyzbqmvlgclajiirp0fgpi2wzv6m3vzha";
  };
  nix-agda = import nixexpr {
    Agda = pkgs.haskellPackages.Agda;
    fetchgit = pkgs.fetchgit;
    ghcWithPackages = pkgs.haskellPackages.ghcWithPackages;
    glibcLocales = pkgs.glibcLocales;
    makeWrapper = pkgs.makeWrapper;
    stdenv = pkgs.stdenv;
    symlinkJoin = pkgs.symlinkJoin;
  };
  agdaPackages = [nix-agda.agdaPackages.agda-stdlib];
in

self: super:
{
  agda-env = (nix-agda.agdaWithPackages (pkgs: with pkgs; agdaPackages)).overrideAttrs(old: {
    name = "agda-env";
  });
}
```

**Comment by Infinisil** [comment]
Works on 18.09, doesn't work on 19.03, works on 19.09, works on master

I think with 19.09 right around the corner we can close this as wontfix for 19.03

**Comment by ulysses4ever** [comment]
I'm a Nix newbie. I have this very problem on Ubuntu 18.04.1 doing
```
nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.Agda])"
```
Is it supposed to work at this point or not? More sophisticated scripts as the one shown copuple comments above looks scary to me. I'd prefer something simpler...

**Comment by turion** [comment]
@ulysses4ever yes, this is supposed to work so far. What are you trying to achieve?

**Comment by ulysses4ever** [comment]
@turion I'm trying to get Agda on my machine.

Now I have another problem, actually:
```
$ nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.Agda])"
these derivations will be built:
  /nix/store/nbzbrpwcmjnyskaap3l4dam0hl4y4dqr-ghc-8.6.5-with-packages.drv
these paths will be fetched (0.02 MiB download, 0.07 MiB unpacked):
  /nix/store/39zv57d49r1ni3j37i3y0853hl9636a1-hook
  /nix/store/npsin1jlnzs5sqxpsv2mk5gbnm4hk4kr-stdenv-linux
  /nix/store/qs2d0qdz2qn07f3llrb5hcnbwf68s67l-hook
  /nix/store/scfjsk8iyf17aw3bs159mrrxq5gfhrf1-lndir-1.0.3
copying path '/nix/store/qs2d0qdz2qn07f3llrb5hcnbwf68s67l-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/scfjsk8iyf17aw3bs159mrrxq5gfhrf1-lndir-1.0.3' from 'https://cache.nixos.org'...
copying path '/nix/store/39zv57d49r1ni3j37i3y0853hl9636a1-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/npsin1jlnzs5sqxpsv2mk5gbnm4hk4kr-stdenv-linux' from 'https://cache.nixos.org'...
error: getting attributes of path '/nix/store/81ikflgpwzgjk8b5vmvg9gaw9mbkc86k-compress-man-pages.sh': No such file or directory
```
