### ISSUE TITLE
Linux 5.15 is not building

### ISSUE THREAD

**Issue by alexdewar** [NixOS/nixpkgs#144894]
I'm currently getting this compile error:
```
/build/source/core/rtw_br_ext.c:20:11: fatal error: net/ipx.h: No such file or directory
   20 |  #include <net/ipx.h>
      |           ^~~~~~~~~~~
compilation terminated.
  CC [M]  /build/source/core/rtw_odm.o
make[2]: *** [/nix/store/d18kiynsgvbcs4sgnm3722y8jn7mkws6-linux-5.15-dev/lib/modules/5.15.0/source/scripts/Makefile.build:277: /build/source/core/rtw_br_ext.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by Ma27** [comment]
When filing bugs, please adhere to the issue template, in this case https://github.com/NixOS/nixpkgs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md !

For me, `linuxPackages_latest.kernel` on b405a8b2d45 results in `/nix/store/3hh5wqk530bfpj9gls8qvhnqmxh5pm2p-linux-5.15`, so the kernel itself doesn't seem to be the problem. I'm happy to help, but I'd need a proper bugreport for that.

**Comment by prusnak** [comment]
> #include <net/ipx.h>

IPX was removed from 5.15 - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/net?id=6c9b40844751ea30c72f7a2f92f4d704bc6b2927

**Comment by andersk** [comment]
There is no `rtw_br_ext.c` in the upstream kernel source. It looks like you are building a third-party kernel module, probably `linuxPackages_latest.rtl8188eus-aircrack`, as would have been clear from the full context of the error if you had included it:

```
/build/source/core/rtw_br_ext.c:20:11: fatal error: net/ipx.h: No such file or directory
   20 |  #include <net/ipx.h>
      |           ^~~~~~~~~~~
compilation terminated.
make[2]: *** [/nix/store/hagl7b1dyi3y7m16vxdhcxargc4ddqyl-linux-5.15-dev/lib/modules/5.15.0/source/scripts/Makefile.build:277: /build/source/core/rtw_br_ext.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/nix/store/hagl7b1dyi3y7m16vxdhcxargc4ddqyl-linux-5.15-dev/lib/modules/5.15.0/source/Makefile:1868: /build/source] Error 2
make[1]: Leaving directory '/nix/store/hagl7b1dyi3y7m16vxdhcxargc4ddqyl-linux-5.15-dev/lib/modules/5.15.0/build'
make: *** [Makefile:2062: modules] Error 2
builder for '/nix/store/3cffq01hyd5c1h2kwklc322sgi81y7mi-rtl8188eus-aircrack-5.15-unstable-2021-05-04.drv' failed with exit code 2
error: build of '/nix/store/3cffq01hyd5c1h2kwklc322sgi81y7mi-rtl8188eus-aircrack-5.15-unstable-2021-05-04.drv' failed
```

This module was marked broken in #144858. It will need a patch for kernel 5.15 compatibility.

**Comment by IvarWithoutBones** [comment]
https://github.com/tomaspinho/rtl8821ce/issues/244 could be related as well.

**Comment by alexdewar** [comment]
Apologies for the shoddy bug report. @andersk you're right that it's not actually the kernel package that's at fault here. In my case it's actually ``linuxPackages_latest.rtl88x2bu`` that's at fault.

**Comment by andersk** [comment]
That one was fixed in #144861.
