### PR TITLE
ddd: 3.3.12 -> 3.4.0

### PR DESCRIPTION
**Pull request by emilytrau**
## Description of changes

First major release since 2009. 

<details><summary>Changelog</summary>
<p>

```
DDD-3.4.0
=========
New maintainers: 
Michael Eager <eager@eagercon.com> and Stefan Eickeler <mail@eickeler.de>

Changes in DDD-3.4.0
====================

Build issues
------------
Fix Ubuntu compilation errors.
Fix GCC warnings.
Update to current flex & bison.
Use Liberation fonts instead of Adobe fonts.
Clean up font usage.
Build method simplified and improved.
Update icons
Switched from DynArray and VarArray to std::vector
Clean up generation of icons.
Regenerate documentation with current texinfo.
Remove PostScript and EPS files.
Remove DVI docs.  
Remove unused, obsolete, or irrelevelant files.
Update logo to DDD-3.4.
Simplify generation of distribution tarball.
Generate derived files in build directory, not source directory.
Add etc/prereq to check for prerequisites.
Reorganize files into subdirectories.
Remove Lesstif, use Motif.
Add additional documentation: FONTS.
Use autoconf-2.71.
Use "make dist" to create distribution tarball.
Cleanup generation of graphics.

Bug fixes
---------
Bug #25109, All-registers display doesn't work.
Bug #33172: DDD has problems parsing Temporary breakpoints.
Bug #58191: Improper handling of GDB's extended-prompt setting
Bug #46725: Source Code View stops displaying at german umlaut
Bug: fixed plotting of arrays using gnuplot
Bug: unusable data status displays disabled, warnings fixed.
Bug #29815: ddd SVN fails to compile on Ubuntu lucid.
Bug #30862: gcc 4.4.4 needs #include <cstdio.h> in cstrclass.C
Bug #33960: strclass.C:1546: error: ‘EOF’ was not declared in this scope.
Bug #25109: All-registers display doesn't work.
Bug: Error disassembling code.
Bug: case-insensitive sorting of filenames.
Bug: DDD fails compile with Xt 1.2.0.
Fix build failure on OSX 10.9 DP6.
Infinite VSL recursion fixed for rednil theme
Fixed "no such file or directory" for File->Open_Soure
Fix regex escape warning
Fixed abort signal at inference of gdb and program output
Fix invalid signal handler signature
Suppress bogus stringop-overflow warning
Fixed startup bug without active window 
Fixed progress bar for variable parsing
Bug #40701: layout.C: 2 * bad if test
Bug #41649: Unable to run bashdb via ddd
Bug #50747: Add support for GDB's ProcessRecord
Bug #34882: dbx debugger mouseover "Run" command causes 100% CPU usage
Bug #55842: Current execution marker doesn't move when step command 
Bug #29717: DDD with remake
Bug: remake problem with empty command line 
SR #110812: Recognize GDB question with "(y or [n])"
Bug #746806 from Red Hat Bugzilla: DDD does't honor the --args parameter when executed from the commandline

Enhancements
------------
Workaround for UTF-8 - the source code is internally converted to latin1 
Cursor follows the scrollbar in source window to improve usage of mouse wheel.
Add display of STL data types based on gdb pretty-printers.
Interface for Gnuplot fixed and updated to current version of Gnuplot
Speed of doubleclick reduced
Switched to hex as default for memory examination
Support mouse wheel in panner widget and data display.
Height restriction of 1000 pixels for DataDisplay and SourceView removed
Size of dialog boxes increased
Speed up parsing of variables
Command-line options fixed and documentation updated
Popup error dialog boxes for missing source code deactivated
Panner data display adapted to motif design and improved handling of mouse wheel
```

</p>
</details> 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by samueltardieu — APPROVED** [review]

**Comment by samueltardieu** [comment]
Result of `nixpkgs-review pr 297360` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ddd</li>
  </ul>
</details>

**Comment by emilytrau** [comment]
Updated for the `3.4.1` release :+1:

**Comment by samueltardieu** [comment]
Result of `nixpkgs-review pr 297360` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>ddd</li>
  </ul>
</details>

**Comment by samueltardieu** [comment]
Fails to build for me:

```
ddd> fonts.C:60:10: fatal error: fontconfig/fontconfig.h: No such file or directory
ddd>    60 | #include <fontconfig/fontconfig.h>
```

**Comment by emilytrau** [comment]
While `3.4.1` is building  on `x64_64-darwin` I seem to be having stability issues at runtime. Would it be alright if I reverted to `3.4.0` and got this merged? @samueltardieu

**Comment by samueltardieu** [comment]
> While `3.4.1` is building on `x64_64-darwin` I seem to be having stability issues at runtime. Would it be alright if I reverted to `3.4.0` and got this merged? @samueltardieu

As far as I can see, nobody is using ddd 3.3.12 on Darwin since it was not packaged. Would not that be bad for x86_64 users not to have the latest version just because Darwin users might see some instabilities? Would not it be better if it could be reported upstream by those users?

**Comment by emilytrau** [comment]
We can follow up with a PR for a `3.4.0` -> `3.4.1` bump.
