### ISSUE TITLE
19.09 Keras 2.2.4 is not compatible with Tensorflow 1.14 due to multi-gpu

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#72799]
**Describe the bug**

On 19.09, the packaged versions for Keras and Tensorflow are: 2.2.4 and 1.14.

This results in a bug:

```py
import tensorflow as tf
import numpy as np
from keras.applications.resnet50 import ResNet50
from keras.utils import multi_gpu_model

num_samples = 1000
height = 224
width = 224
num_classes = 10

model = ResNet50(
    weights=None,
    input_shape=(height, width, 3),
    classes=num_classes)

gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
parallel_model = multi_gpu_model(model, gpus=2)
```

Which results in an error: 
`AttributeError: '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string'`

This error has been reported upstream:

* https://github.com/tensorflow/tensorflow/issues/30728
* https://github.com/keras-team/keras/issues/13057

The only tensorflow version that works with 2.2.5 and 2.2.4 is tensorflow 1.13.

So we can rollback to tensorflow 1.13, or backport Keras 2.3.0 to 19.09.

**To Reproduce**

1. Checkout the latest 19.09 branch commit
2. Use tensorflow and keras together

**Expected behavior**

No attribute error.

**Comment by CMCDragonkai** [comment]
I tested with Keras 2.3.1, and the error no longer occurs. I suggest backporting Keras 2.3.1 to 19.09.

**Comment by FRidh** [comment]
That most likely means exchanging one bug for another. If you as a user cannot work with a specific version then as a user pick another version.

**Comment by CMCDragonkai** [comment]
What kind of bug do you think we are trading for? I'll be running a full test of ml system soon with 2.3.1 and report back.

**Comment by BEEugene** [comment]
This bug may also appear 

`Traceback (most recent call last):
  File "/home/e.baraboshkin/Evgeny/ML/Segmentation/code/train_segm_model.py", line 123, in <module>
    model = Model_gpu().keras_multi_nets_alloc(model)
  File "/home/e.baraboshkin/Evgeny/ML/Segmentation/code/Fresh_seg_models/helpers/device.py", line 49, in keras_multi_nets_alloc
    model = multi_gpu_model(model, gpus=G)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/multi_gpu_utils.py", line 230, in multi_gpu_model
    outputs = model(inputs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 583, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 740, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/normalization.py", line 185, in call
    epsilon=self.epsilon)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2309, in normalize_batch_in_training
    if not _has_nchw_support() and list(reduction_axes) == [0, 2, 3]:
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 521, in _has_nchw_support
    explicitly_on_cpu = _is_current_explicit_device('cpu')
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 490, in _is_current_explicit_device
    device = _get_current_tf_device()
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 470, in _get_current_tf_device
    g._apply_device_functions(op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 4393, in _apply_device_functions
    device_string = device_spec.string_merge(op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 142, in string_merge
    return self.function.shortcut_string_merge(node_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/device.py", line 163, in shortcut_string_merge
    result = self.__call__(node_def).to_string()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/device.py", line 130, in __call__
    current_device = DeviceSpec.from_string(node_def.device or "")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/device_spec.py", line 138, in from_string
    return cls(*cls._string_to_components(spec))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/device_spec.py", line 301, in _string_to_components
    splits = [x.split(":") for x in spec.split("/")]
AttributeError: 'DeviceSpecV1' object has no attribute 'split'
`

**Comment by CMCDragonkai** [comment]
I've done a full test. And 2.3.1 is what works.

I suggest backporting Keras 2.3.1 to 19.09.

**Comment by CMCDragonkai** [comment]
@FRidh

**Comment by CMCDragonkai** [comment]
@FRidh Are you happy with me creating a MR for 19.09 backporting 2.3.1?

**Comment by FRidh** [comment]
I am not a maintainer of Keras and simply state that in stable we typically do not increment major and minor versions as a policy. There are exceptions if there is a good case for it.

**Comment by CMCDragonkai** [comment]
@FRidh I'm making a claim that the 19.09 Keras version is incorrect and does not work because it doesn't match the upgraded Tensorflow version. So a essentially a bug in nixpkgs should be fixed. Is that not a good case for backporting such a version?

**Comment by CMCDragonkai** [comment]
Hmm I don't care about this anymore.
