### PR TITLE
elixir_1_14: init at 1.14.0

### PR DESCRIPTION
**Pull request by shanesveller**
Followed the example of #148619 since everything included still seems pertinent. However, some included packages do not build successfully on 1.14.0 yet, so I skipped the default (`elixir`) version change for purposes of this PR. Please let me know if the desired flow is instead to wait for such projects to become 1.14-compatible on their own.

###### Description of changes

https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/
https://hexdocs.pm/elixir/1.14.0/changelog.html

###### Things done

Extras:

- [ ] ~Default `elixir` version 1.13 -> 1.14~
- [X] Removed unsupported 1.9 per https://hexdocs.pm/elixir/1.14.0/compatibility-and-deprecations.html

Defaults:

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/development/beam-modules/default.nix [hunk 1]
```diff
@@ -44,27 +44,27 @@ let
       # BEAM-based languages.
       elixir = elixir_1_13;
 
-      elixir_1_13 = lib'.callElixir ../interpreters/elixir/1.13.nix {
+      elixir_1_14 = lib'.callElixir ../interpreters/elixir/1.14.nix {
```
Comment (superherointj) [inline pkgs/development/beam-modules/default.nix:47]: Look how the diff ended up. Maybe instead of adding to the top could add to the bottom.

**Review by DianaOlympos — APPROVED** [review]

**Comment by DianaOlympos** [comment]
Which packages break with 1.14?

**Comment by shanesveller** [comment]
> Which packages break with 1.14?

Sure, sorry for not including that info in the top post.

With this additional change:
```diff
diff --git a/pkgs/development/beam-modules/default.nix b/pkgs/development/beam-modules/default.nix
index 068e1da3313..66300e6bb2c 100644
--- a/pkgs/development/beam-modules/default.nix
+++ b/pkgs/development/beam-modules/default.nix
@@ -42,7 +42,7 @@ let
       elvis-erlang = callPackage ./elvis-erlang { };
 
       # BEAM-based languages.
-      elixir = elixir_1_13;
+      elixir = elixir_1_14;
 
       elixir_1_14 = lib'.callElixir ../interpreters/elixir/1.14.nix {
         inherit erlang;
```

I see compiler failures in `prometheus_ex` Hex package like so:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/0bcxv9k5qyfib5r8jh4shkc250laj5ar-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
[33mwarning: [0muse Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3

Compiling 19 files (.ex)

== Compilation error in file lib/prometheus/buckets.ex ==
** (UndefinedFunctionError) function Kernel.Utils.defdelegate/2 is undefined or private. Did you mean:

      * defdelegate_all/3
      * defdelegate_each/2

    (elixir 1.14.0) Kernel.Utils.defdelegate({:new, [line: 18], [{:arg, [line: 18], nil}]}, [])
    lib/prometheus/buckets.ex:18: (module)
```

And this fails the build for `pleroma` based on `nixpkgs-review rev HEAD` on x86_64-linux.

**Comment by DianaOlympos** [comment]
Thanks! Will have a look

That make me think we also need to fix the UTF8 problem, i keep having it.

**Comment by mveytsman** [comment]
FWIW plemora is depending on their own [fork](https://git.pleroma.social/pleroma/elixir-libraries/prometheus.ex/) of `prometheus_ex`. The mainline repo compiles fine in Elixir 1.14.0. 

I tried pinging someone what I think is a maintainer of the fork here: https://github.com/deadtrickster/prometheus.ex/issues/48

**Comment by bhankas** [comment]
Can we just patch it to use mainline until upstream fixes it?

File: pkgs/development/interpreters/elixir/1.14.nix [hunk 2]
```diff
@@ -0,0 +1,10 @@
+{ mkDerivation }:
+
+# How to obtain `sha256`:
+# nix-prefetch-url --unpack https://github.com/elixir-lang/elixir/archive/v${version}.tar.gz
```
Comment (SuperSandro2000) [inline pkgs/development/interpreters/elixir/1.14.nix:4]:
```suggestion
```
This is already in the contributing guide

Comment (shanesveller) [reply pkgs/development/interpreters/elixir/1.14.nix]: Thanks for the review! Removed in the version committed as b73e0e96e3bf9644dbbf1bb4bc26aa2c87cf50e0

**Comment by happysalada** [comment]
Nice to see you around here @shanesveller (I enjoyed quite enjoyed your blog when I was doing elixir)! Thank you for the contribution!

I think this is fine to merge to make the update available to everyone.

Regarding the UTF8 problem, I've never found how to fix it with nix as well. We are doing exactly what you pointed @cw789 but it seems it's not enough.
However I don't think the compilation error is a UTF8 problem here, it looks like the dependency is using an old alias for a function (defdelegate) and it should be a matter of updating the dependency. Hopefully the maintainer answers and we update the main elixir version in nixpkgs.

(let me know of course if you disagree).

**Comment by DianaOlympos** [comment]
Nah iirc there was a glibc patch a few years ago that broke it all and we need to patch it a bit. I have something somewhere. I never had time to dive in.

File: pkgs/development/interpreters/elixir/1.14.nix (hunk 2 above)
Comment (SuperSandro2000) [reply pkgs/development/interpreters/elixir/1.14.nix]: > PS: There are probably more of this comments across the code base from me - should I remove them all?

If the download link is not obvious then we can keep it but for github downloads at least we do not require them.

**Comment by datafoo** [comment]
Thank for the work. I have a question/suggestion.

If this contribution had been split into 2 commits and 2 pull requests such as:

- elixir_1_14: init at 1.14.0
- elixir_1_9: remove following end of support

Would that have allowed to backport the first commit/PR to `release-22.05`?

**Comment by happysalada** [comment]
it would have indeed made the backport easier, we can think about that for next time! Thank you for your input on this.
