### ISSUE TITLE
geckodriver is broken on master

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#35301]
## Issue description
```
error[E0277]: the trait bound `*mut core::ops::Fn() + 'static: core::marker::Sync` is not satisfied in `core::fmt::Arguments<'static>`
   --> /build/geckodriver-0.19.1-vendor/slog/src/ser.rs:228:6
    |
228 | impl SyncSerialize for fmt::Arguments<'static> {}
    |      ^^^^^^^^^^^^^ `*mut core::ops::Fn() + 'static` cannot be shared between threads safely
    |
    = help: within `core::fmt::Arguments<'static>`, the trait `core::marker::Sync` is not implemented for `*mut core::ops::Fn() + 'static`
    = note: required because it appears within the type `core::marker::PhantomData<*mut core::ops::Fn() + 'static>`
    = note: required because it appears within the type `core::fmt::Void`
    = note: required because it appears within the type `&'static core::fmt::Void`
    = note: required because it appears within the type `core::fmt::ArgumentV1<'static>`
    = note: required because it appears within the type `[core::fmt::ArgumentV1<'static>]`
    = note: required because it appears within the type `&'static [core::fmt::ArgumentV1<'static>]`
    = note: required because it appears within the type `core::fmt::Arguments<'static>`

error: aborting due to previous error

error: Could not compile `slog`.
```

### Steps to reproduce
`nix-build -A geckodriver`

/cc maintainer @jraygauthier

**Comment by Synthetica9** [comment]
This broke with the update `rust: 1.22.1 -> 1.24.0`

```
f61e8d98ff7fbb049ddeea33742bb4b840dafbfa is the first bad commit
commit f61e8d98ff7fbb049ddeea33742bb4b840dafbfa
Author: Jörg Thalheim <Mic92@users.noreply.github.com>
Date:   Tue Feb 20 09:59:26 2018 +0000

     rust: 1.22.1 -> 1.24.0

:040000 040000 521ca4d4146d24dc66877b6c99db34af34f622aa 1aaab27b45ccc7c60d8c11f6e7f6e3ace93743ee M   pkgs
bisect run success
```

Found with `git bisect run nix-build . -A geckodriver`

**Comment by jraygauthier** [comment]
I think the easy road will be to revert to the binary version until Mozilla update its package. See <https://github.com/mozilla/geckodriver/releases>. Alternatives would be to patch 0.19.1 version or use a non official version from mozilla central which no longer uses the problematic `slog` crate..

**Comment by dotlambda** [comment]
@jraygauthier Do you know which commit on their side removed the slog dependency? Can we maybe use that commit as a patch?

**Comment by matthiasbeyer** [comment]
Just wanted to file this issue. Nice that it is already in progress! :heart:

**Comment by dotlambda** [comment]
@matthiasbeyer As you are proficient in Rust, maybe you can find out which patch to apply?

**Comment by matthiasbeyer** [comment]
I could, but unfortunately I'm not on my computer over the weekend (vacation) ... so if this can wait until monday, I can try. But as this breaks master I'd suggest you try yourself... if you can't find the right patch, I guess rolling back to the last version which worked should do the job short-term.

**Comment by dotlambda** [comment]
Found it: https://bugzilla.mozilla.org/show_bug.cgi?id=1436830
Sadly, this cannot be applied as is, some manual work seems to be needed.

**Comment by mguentner** [comment]
See referenced PR

**Comment by noloader** [comment]
An FYI... It looks like version 21 (https://github.com/mozilla/geckodriver/archive/v0.21.0. tar.gz) compiles as expected. versions 16-20 have compile problems. I did not try version 15 of the driver.

Unfortunately, version 21 breaks in another way:

```
   Compiling miniz_oxide v0.2.1
error: `impl Trait` in argument position is experimental (see issue #34511)
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.2.1/src/deflate/core.rs:2030:20
     |
2030 |     callback_func: impl FnMut(&[u8]) -> bool,
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `miniz_oxide`.
warning: build failed, waiting for other jobs to finish...
```

Man this language blows. I'll never understand the "let's embrace bleeding edge" because things mostly don't work...
