### ISSUE TITLE
libchop build failing

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#23418]
I'm trying to fix libchop for #23253.
The build started failing with commit f803270b7e: specifically a single unit test fails:
```
FAIL: utils/block-server (exit: 1)
==================================
[...]
++ chop_fail_if '!' chop-block-server -a 127.0.0.1 -p 7696 ,,block-server.db '&'
++ eval '!' chop-block-server -a 127.0.0.1 -p 7696 ,,block-server.db '&'
++ echo 'failure condition `!' chop-block-server -a 127.0.0.1 -p 7696 ,,block-server.db '&'\'' is true'
failure condition `! chop-block-server -a 127.0.0.1 -p 7696 ,,block-server.db &' is true
[...]
```

It's almost surely due to some incompatible change in bash 4.4 but I haven't figured it out yet.

Also, after commit 919a1435da, build fails with
```
In file included from chop.c:545:0:
class-lookup.c:115:1: error: conflicting types for 'chop_lookup_class_entry'
 chop_lookup_class_entry (register const char *str, register size_t len)
 ^
chop.c:542:1: note: previous declaration of 'chop_lookup_class_entry' was here
 chop_lookup_class_entry (const char *str, unsigned int len);

```

cc @viric

**Comment by rnhmjoj** [comment]
I patched it to work with gperf 3.1 and temporarily disabled the tests failing. Still no idea why.
