### ISSUE TITLE
lirc: plugin ftdi is missing (pkg-config in depsBuildBuild)

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#200566]
### Describe the bug

In nixos-unstable (2022-11-10) the package lirc do not build the ftdi plugin. This plugin is availabe in nixos-22.05.

### Analysis

This issue was introduced with https://github.com/NixOS/nixpkgs/pull/190212, which moved package `pkg-config` from `nativeBuildInputs` to `depsBuildBuild`.
This move renamed the environment variable form `PKG_CONFIG_PATH` to `PKG_CONFIG_PATH_FOR_BUILD` and therefor the program `pkg-config` fails to find package `libftdi1` during configure phase:

```
checking for libftdi1 >= 1.0... no
```

Side note: Do we have a general problem with `pkg-config` in `depsBuildBuild`?

### Expected behavior

The lirc ftdi plugin is available.

### Solving attempts

Moving `pkg-config` from `depsBuildBuild` back to `nativeBuildInputs`, raises following error:

```
python-pkg/lirc/_client.c:1:10: fatal error: Python.h: No such file or directory
    1 | #include <Python.h>
      |          ^~~~~~~~~~
```

The move does not raise an error with lirc version 0.10.2, which is currently available as PR https://github.com/NixOS/nixpkgs/pull/200558.

### Notify maintainers

@SuperSandro2000 , @pSub

**Comment by SuperSandro2000** [comment]
ping @Artturin

**Comment by Artturin** [comment]
pkg-config in both depsBuildBuild and nativeBuildInputs are not mutually exclusive

> The move does not raise an error with lirc version 0.10.2, which is currently available as PR #200558.

In this case pkg-config should probably only be in nativeBuildInputs as it sounds like needing it in depsBuildBuild was a bug (because libftdi1 is in buildInputs instead of nativeBuildInputs).
