### ISSUE TITLE
antimony fails to build

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#42811]
## Issue description

```
[ 98%] Building CXX object app/CMakeFiles/antimony.dir/antimony_autogen/mocs_compilation.cpp.o
In file included from /nix/store/rsa1rsd6c6szy0dmi61599b33aqiy269-python3-3.6.5/include/python3.6m/pytime.h:6:0,
                 from /nix/store/rsa1rsd6c6szy0dmi61599b33aqiy269-python3-3.6.5/include/python3.6m/Python.h:68,
                 from /tmp/nix-build-antimony-0.9.3.drv-0/source/build/app/antimony_autogen/424LE5FWXF/../../../../app/viewport/render/instance.h:3,
                 from /tmp/nix-build-antimony-0.9.3.drv-0/source/build/app/antimony_autogen/424LE5FWXF/moc_instance.cpp:9,
                 from /tmp/nix-build-antimony-0.9.3.drv-0/source/build/app/antimony_autogen/mocs_compilation.cpp:3:
/nix/store/rsa1rsd6c6szy0dmi61599b33aqiy269-python3-3.6.5/include/python3.6m/object.h:448:23: error: expected unqualified-id before ';' token
     PyType_Slot *slots; /* terminated by slot==0. */
                       ^
make[2]: *** [app/CMakeFiles/antimony.dir/build.make:981: app/CMakeFiles/antimony.dir/antimony_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:277: app/CMakeFiles/antimony.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
builder for '/nix/store/6rdi6nwzv5c27hc2grbncny6w6j9khni-antimony-0.9.3.drv' failed with exit code 2
error: build of '/nix/store/6rdi6nwzv5c27hc2grbncny6w6j9khni-antimony-0.9.3.drv' failed
```

### Steps to reproduce

`nix-env -iA nixos.antimony`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.14, NixOS, 18.09pre142796.4b649a99d84 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre142796.4b649a99d84"`
 - channels(turion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by turion** [comment]
@bendlas @rzetterberg @ryantm any ideas?

**Comment by ryantm** [comment]
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.antimony.x86_64-linux

Something in this diff broke it: https://hydra.nixos.org/api/scmdiff?rev1=55f2889baeb98a650d19948e2db9c01ae7f94edf&type=git&branch=&rev2=f0d6411c22d91723fef3f935adf35c7884a4dc76&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git

**Comment by bendlas** [comment]
I've bisected this back to https://github.com/NixOS/nixpkgs/commit/75e78eda1fd85ac7306acfe597eb5f55b7f60a55

@ttuegel can you speak as to how we can fix this?

While bisecting, I've noticed that even before this build failure started happening, startup stopped working with not finding `xcb` ... bisecting that one, now.

**Comment by bendlas** [comment]
Unfortunately, just using cmake 3.10 doesn't work either: https://gist.github.com/bendlas/63fb1554c78083efb471c3a3da236007

**Comment by ttuegel** [comment]
> @ttuegel can you speak as to how we can fix this?

I'm sorry, I have no clue.

**Comment by hartcw** [comment]
I had this same compile error with python, but on a different project.
The reason there was that the project used Qt, and Qt headers #define "slots" to something else.

This fixed it for me:

    #ifdef slots
    #undef slots
    #endif
   
    #include <Python.h>

**Comment by bendlas** [comment]
Thanks for finding out about this and pinging! @hartcw 
Indeed, this seems to have been noticed and fixed upstream: https://github.com/mkeeter/antimony/issues/189

Has anybody tried building against current git?

**Comment by bendlas** [comment]
... aaand we also have the fix already https://github.com/NixOS/nixpkgs/pull/46486
Thanks! @rnhmjoj
