### ISSUE TITLE
golangci-lint does not build on darwin-x86_64 - undefined symbols

### ISSUE THREAD

**Issue by wlcx** [NixOS/nixpkgs#168984]
golangci-lint on unstable does not build on darwin-x86_64. This seems to have been caused by #166801 which switched the go version from 1.17 to 1.18 (to fix another (runtime) bug!)

See hydra: https://hydra.nixos.org/job/nixpkgs/trunk/golangci-lint.x86_64-darwin

```
/nix/store/gynxiihx8rd89nid1ma8pmj9b3nd3kzz-go-1.18.1/share/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "_SecTrustEvaluateWithError", referenced from:
      _crypto/x509/internal/macos.x509_SecTrustEvaluateWithError_trampoline.abi0 in go.o
  "_utimensat", referenced from:
      _syscall.libc_utimensat_trampoline.abi0 in go.o
ld: symbol(s) not found for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

FYI (sorry to ping but not really sure who else I would ask)
@Arriven @siraben - author/merger of #166801
@Mic92 - arbitrary maintainer

```console
❯ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixpkgs-22.05pre344086.568e0bc498e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Arriven** [comment]
I think the issue is related to this commit in upstream go https://github.com/golang/go/commit/6027b2183d9a63a11f92d392fd2296e7b88402fc
Also upstream issue for which that commit was introduced https://github.com/golang/go/issues/49616

**Comment by zowoq** [comment]
The stdenv we use for `x86_64-darwin` is too old, currently it's 10.12. It failed to build in https://github.com/NixOS/nixpkgs/pull/166801, it should have been marked as broken then. e.g.

https://github.com/NixOS/nixpkgs/blob/385450ef639c222cb09399de024b42a9c217dd02/pkgs/tools/misc/dsq/default.nix#L56-L58

**Comment by Arriven** [comment]
@zowoq I'm a bit new to nixos, is that `broken` declaration used just for the documentation purposes or it may force `nixos-rebuild` to build the derivation locally if conditions are met?

**Comment by eqyiel** [comment]
@Arriven if you need it to build locally in the meantime you can create an overlay like this

```nix
self: super: {
  golangci-lint = super.golangci-lint.override ({
    # Override https://github.com/NixOS/nixpkgs/pull/166801 which changed this
    # to buildGo118Module because it does not build on Darwin.
    buildGoModule = super.buildGoModule;
  });
}
```

And if you're using `nixos-rebuild`, you can configure `nixpkgs.overlays = [ (import /path/to/this/file.nix) ];` or inline it like 

```nix
nixpkgs.overlays = [ 
  (self: super: { 
    # ...
  })
];
```

**Comment by sagikazarmark** [comment]
Unfortunately golangci-lint breaks with Go 1.18 projects if it's built with 1.17 at the moment, so this only works if you run it in a 1.17 project.

**Comment by burdiyan** [comment]
Are there any plans to update Apple SDK on x86_64-darwin? I've been dealing with a lot of pain recently using Nix on Darwin because of that.

**Comment by sagikazarmark** [comment]
There is an open issue about updating the SDK: #101229

You can try the above comment for changing the Go version back to 1.17.

An alternative is using a prebuilt version of golangci-lint. For example: https://github.com/sagikazarmark/go-bin-flake

(Note: it's not a very nice solution, but works for the moment)
