### PR TITLE
mwprocapture: fix compile on new GCC and new linux kernel

### PR DESCRIPTION
**Pull request by djahandarie**
###### Description of changes

I couldn't upgrade to NixOS 22.05 due to this broken driver, so this PR fixes mwprocapture to build on NixOS 22.05.

Namely:
* replaces references to deprecated `pci_set_dma_mask` with `dma_set_mask` so it builds on Linux 5.15.
* add `-Wno-error=implicit-fallthrough` so it builds on whatever new version of GCC nixpkgs was switched to (it warns on implicit fallthrough which breaks the build).

I have provided pci.patch to Magewall (the vendor) so maybe they will release a new drvier version that includes the change, but we should probably not wait on that.

@pwetzel @MP2E 
 
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by pwetzel — APPROVED** [review]
I'm sorry you haven't gotten any attention on this @djahandarie. I had checked for a new driver version from the vendor when 22.05 was getting close and assumed that since there wasn't one we were good to go. Bad assumption.

I was able to build a machine against your branch and my Pro Capture HDMI card worked. This package had a patch attached to it a long time ago for similar reasons when the vendor lagged, approach here makes sense to me. Backporting to 22.05 would be good.

**Comment by djahandarie** [comment]
Thanks @pwetzel ! I did finally get a response back from Magewell saying they updated their driver, so maybe we can get away with fewer patches, haven't checked yet.

**Comment by pwetzel** [comment]
I looked as I was reviewing and it still wasn't up. Like you said, hard to decide to wait when you don't know when they're going to deliver. And I doubt that they would fix the fall through stuff so we'd still need your flags line. 

I'm not a committer but it would make sense to me to ship this solution for 22.05 and update master with the vendor solution for later versions.

**Comment by Artturin** [comment]
after rebasing on master and unmarking the package as broken 
`nix build ".#linuxPackages_latest.mwprocapture" --impure` fails

```
mwprocapture> /build/ProCaptureForLinux_4236/src/sources/avstream/alsa.c:697:13: error: implicit declaration of function 'snd_dma_continuous_data' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]
mwprocapture>   697 |             snd_dma_continuous_data(GFP_KERNEL),
mwprocapture>       |             ^~~~~~~~~~~~~~~~~~~~~~~
```
