### ISSUE TITLE
Build failure: xone kernel driver

### ISSUE THREAD

**Issue by BeiNacht** [NixOS/nixpkgs#342775]
### Steps To Reproduce

1. hardware.xone.enable = true; or  extraModulePackages = with config.boot.kernelPackages; [ xone ];
2. build with linuxPackages_latest aka 6.11

### Build log

```
error: builder for '/nix/store/dllnn5cbz3ssaj1p5n1928n2c28z6a8c-xone-0.3-unstable-2024-03-16.drv' failed with exit code 2;
       last 10 log lines:
       >   CC [M]  /build/source/bus/bus.o
       > /build/source/bus/bus.c:125:18: error: initialization of 'int (*)(struct device *, const struct device_driver *)' from incompatible pointer type 'int (*)(struct device *, struct device_driver *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >   125 |         .match = gip_bus_match,
       >       |                  ^~~~~~~~~~~~~
       > /build/source/bus/bus.c:125:18: note: (near initialization for 'gip_bus_type.match')
       > cc1: some warnings being treated as errors
       > make[2]: *** [/nix/store/1781j66py0gf7mynqhh0wavdpvgrry4y-linux-6.11-dev/lib/modules/6.11.0/source/scripts/Makefile.build:244: /build/source/bus/bus.o] Error 1
       > make[1]: *** [/nix/store/1781j66py0gf7mynqhh0wavdpvgrry4y-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:1926: /build/source] Error 2
       > make: *** [/nix/store/1781j66py0gf7mynqhh0wavdpvgrry4y-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:224: __sub-make] Error 2
       > make: Leaving directory '/nix/store/1781j66py0gf7mynqhh0wavdpvgrry4y-linux-6.11-dev/lib/modules/6.11.0/build'
       For full logs, run 'nix log /nix/store/dllnn5cbz3ssaj1p5n1928n2c28z6a8c-xone-0.3-unstable-2024-03-16.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-virtualbox-modules-7.0.18-6.11.drv-2/build': Directory not empty
error: 1 dependencies of derivation '/nix/store/0bhcgcdkjy315mj0jgja8lv0d3qc07zb-linux-6.11-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xhmz6h4w34q34yx4c3d6qrhmrp926yvb-nixos-system-desktop-24.05.20240916.086b448.drv' failed to build
```

### Additional context

The Issue seems to be known. There is already a PR in the xone Repo for this build error https://github.com/medusalix/xone/pull/48

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.10, NixOS, 24.05 (Uakari), 24.05.20240916.086b448`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/store/qkzr5clkyq7j6n43qs5ff73in6c3wacv-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Raroh73** [comment]
I made PR that fixes it: https://github.com/NixOS/nixpkgs/pull/342528.

**Comment by JohnRTitor** [comment]
Closed in #342528

Will be available in both unstable and stable release once channels update.
