### ISSUE TITLE
pycurl fails to build on nixos-unstable

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#59757]
## Issue description

```
=================================== FAILURES ===================================
_________________ MemoryMgmtTest.test_readfunction_collection __________________

self = <tests.memory_mgmt_test.MemoryMgmtTest testMethod=test_readfunction_collection>

    def test_readfunction_collection(self):
>       self.check_callback(pycurl.READFUNCTION)

tests/memory_mgmt_test.py:246:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/util.py:192: in decorated
    return fn(*args, **kwargs)
tests/memory_mgmt_test.py:285: in check_callback
    self.assertTrue(new_object_count in (object_count, object_count-1))
E   AssertionError: False is not true
=============================== warnings summary ===============================
/nix/store/9jy4g0b040s7b0x2jncr3ra09jygk65l-python3.7-bottle-0.12.16/lib/python3.7/site-packages/bottle.py:87
  /nix/store/9jy4g0b040s7b0x2jncr3ra09jygk65l-python3.7-bottle-0.12.16/lib/python3.7/site-packages/bottle.py:87: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping as DictMixin

tests/setopt_lifecycle_test.py:19
  /build/pycurl-7.43.0.2/tests/setopt_lifecycle_test.py:19: PytestWarning: cannot collect test class 'TestString' because it has a __new__ constructor
    class TestString(str):

tests/memory_mgmt_test.py::MemoryMgmtTest::test_form_bufferptr_memory_leak_gh267
  /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:320: DeprecationWarning: Please use assertTrue instead.
    self.assert_(after_object_count <= before_object_count + 1000, 'Grew from %d to %d objects' % (before_object_count, after_object_count))

tests/memory_mgmt_test.py::MemoryMgmtTest::test_postfields_unicode_memory_leak_gh252
  /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:300: DeprecationWarning: Please use assertTrue instead.
    self.assert_(after_object_count <= before_object_count + 1000, 'Grew from %d to %d objects' % (before_object_count, after_object_count))

tests/setopt_test.py::SetoptTest::test_set_httpheader_none
  /build/pycurl-7.43.0.2/tests/setopt_test.py:75: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b('foo'), io.getvalue())

tests/setopt_test.py::SetoptTest::test_set_httpheader_none
  /build/pycurl-7.43.0.2/tests/setopt_test.py:81: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b(''), io.getvalue())

tests/setopt_test.py::SetoptTest::test_unset_httpheader
  /build/pycurl-7.43.0.2/tests/setopt_test.py:61: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b('foo'), io.getvalue())

tests/setopt_test.py::SetoptTest::test_unset_httpheader
  /build/pycurl-7.43.0.2/tests/setopt_test.py:67: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(util.b(''), io.getvalue())

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===Flaky Test Report===

test_getinfo passed 1 out of the required 1 times. Success!
test_getinfo_times passed 1 out of the required 1 times. Success!
test_cyclic_gc passed 1 out of the required 1 times. Success!
test_debugfunction_collection passed 1 out of the required 1 times. Success!
test_form_bufferptr_memory_leak_gh267 passed 1 out of the required 1 times. Success!
test_headerfunction_collection passed 1 out of the required 1 times. Success!
test_headerfunction_refcounting passed 1 out of the required 1 times. Success!
test_ioctlfunction_collection passed 1 out of the required 1 times. Success!
test_multi_collection passed 1 out of the required 1 times. Success!
test_multi_cycle passed 1 out of the required 1 times. Success!
test_opensocketfunction_collection passed 1 out of the required 1 times. Success!
test_postfields_unicode_memory_leak_gh252 passed 1 out of the required 1 times. Success!
test_progressfunction_collection failed (2 runs remaining out of 3).
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:249>, <TracebackEntry /build/pycurl-7.43.0.2/tests/util.py:192>, <TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:285>]
test_progressfunction_collection passed 1 out of the required 1 times. Success!
test_readdata_refcounting passed 1 out of the required 1 times. Success!
test_readfunction_collection failed (2 runs remaining out of 3).
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:246>, <TracebackEntry /build/pycurl-7.43.0.2/tests/util.py:192>, <TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:285>]
test_readfunction_collection failed (1 runs remaining out of 3).
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:246>, <TracebackEntry /build/pycurl-7.43.0.2/tests/util.py:192>, <TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:285>]
test_readfunction_collection failed; it passed 0 out of the required 1 times.
        <class 'AssertionError'>
        False is not true
        [<TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:246>, <TracebackEntry /build/pycurl-7.43.0.2/tests/util.py:192>, <TracebackEntry /build/pycurl-7.43.0.2/tests/memory_mgmt_test.py:285>]
test_readfunction_refcounting passed 1 out of the required 1 times. Success!
test_refcounting_bug_in_reset passed 1 out of the required 1 times. Success!
test_reference_counting passed 1 out of the required 1 times. Success!
test_seekfunction_collection passed 1 out of the required 1 times. Success!
test_share_collection passed 1 out of the required 1 times. Success!
test_share_cycle passed 1 out of the required 1 times. Success!
test_writedata_refcounting passed 1 out of the required 1 times. Success!
test_writefunction_collection passed 1 out of the required 1 times. Success!
test_writefunction_refcounting passed 1 out of the required 1 times. Success!
test_writeheader_refcounting passed 1 out of the required 1 times. Success!
test_xferinfofunction_collection passed 1 out of the required 1 times. Success!
test_curl_ref passed 1 out of the required 1 times. Success!
test_opensocketfunction_collection passed 1 out of the required 1 times. Success!
test_seekfunction_collection passed 1 out of the required 1 times. Success!
test_multi_socket_select passed 1 out of the required 1 times. Success!
test_pause_via_call passed 1 out of the required 1 times. Success!
test_pause_via_return passed 1 out of the required 1 times. Success!
test_post_byte_buffer passed 1 out of the required 1 times. Success!
test_post_fields_with_ampersand passed 1 out of the required 1 times. Success!
test_post_file passed 1 out of the required 1 times. Success!
test_post_list_of_list_of_lists passed 1 out of the required 1 times. Success!
test_post_list_of_tuple_of_tuples passed 1 out of the required 1 times. Success!
test_post_multiple_fields passed 1 out of the required 1 times. Success!
test_post_single_field passed 1 out of the required 1 times. Success!
test_post_tuple_of_lists_of_tuples passed 1 out of the required 1 times. Success!
test_post_tuple_of_tuple_of_lists passed 1 out of the required 1 times. Success!
test_post_tuple_of_tuples_of_tuples passed 1 out of the required 1 times. Success!
test_post_unicode_buffer passed 1 out of the required 1 times. Success!
test_post_with_null_byte passed 1 out of the required 1 times. Success!

===End Flaky Test Report===
= 1 failed, 375 passed, 9 skipped, 11 deselected, 8 warnings in 19.84 seconds ==
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 47296)
Traceback (most recent call last):
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/nix/store/lmwk7mg8y79m3izdxdlckdn385x7jgl7-python3-3.7.3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
part1part2
note: keeping build directory '/tmp/nix-build-python3.7-pycurl-7.43.0.2.drv-1'
builder for '/nix/store/1p8754s04chk6sjjb943z8878sd26mks-python3.7-pycurl-7.43.0.2.drv' failed with exit code 1
error: build of '/nix/store/1p8754s04chk6sjjb943z8878sd26mks-python3.7-pycurl-7.43.0.2.drv' failed

```

### Steps to reproduce

run `nix-build -A python3Packages.pycurl ~/nixpkgs`

there is no listed maintainer but a blame shows @adisbladis and @FRidh activity on it.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0, NixOS, 19.09.git.1faecef (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(teto): `""`
 - channels(root): `""`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by teto** [comment]
Meanwhile, for those with the problem, you can skip the tests via
```
        pycurl = pythonsuper.pycurl.overrideAttrs (oa: {
          doCheck = false;
          installCheckPhase = false;
        });

```

**Comment by adisbladis** [comment]
And interestingly enough `python35Packages.pycurl` works fine.

**Comment by FRidh** [comment]
Haven't checked the channel but builds fine on master so closing.

**Comment by memberbetty** [comment]
@FRidh  It does not work in the 18.09 channel.
