### PR TITLE
linuxPackages.rtl8821ce: fix build on 6.14

### PR DESCRIPTION
**Pull request by cything**
Patch from https://github.com/tomaspinho/rtl8821ce/pull/360
Without this, fails to build on 6.14 with following error:
```
rtl8821ce> os_dep/linux/ioctl_cfg80211.c:9621:25: error: initialization of 'int (*)(struct wiphy *, struct wireless_dev *, unsigned int,  int *)' from incompatible pointer type 'int (*)(struct wiphy *, struct wireless_dev *, int *)' [8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Wincompatible-pointer-types8;;]
rtl8821ce>  9621 |         .get_tx_power = cfg80211_rtw_get_txpower,
rtl8821ce>       |                         ^~~~~~~~~~~~~~~~~~~~~~~~
```
Not sure if we should wait for upstream to merge this PR, but this package currently fails to build on `nixos-unstable`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Defelo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review-gha`](https://github.com/Defelo/nixpkgs-review-gha)

Command: `nixpkgs-review pr 394419`

Logs: https://github.com/Defelo/nixpkgs-review-gha/actions/runs/14156200877

<details><summary>Download packages from cache:</summary><ul>
<li><details><summary><code>x86_64-linux</code></summary>

```shell
nix-store -r --add-root nixpkgs-pr-394419-x86_64-linux \
  --option binary-caches 'https://cache.nixos.org/ https://attic.defelo.de/nixpkgs' \
  --option trusted-public-keys '
  cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  nixpkgs:xeaAWa3crK09hMmFiygBeRmLq3hUjUShgaAwYVUEtw0=
  ' \
  /nix/store/vwqlcwcivx3gh8lpnjycgkxk34irbib8-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/vq749lr5crcf1yv9vg5938z2dvsfzp9s-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/dh2qb2zspkrvl05z2n89fbdj25zr4503-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/fsr9gm520mn2wirar25rq2hrnp38m857-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/0q2807880a8cv1khag1s8cvrjaxq8sjg-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/kgi262lqy3mc7awrfhg0a86v3pa29jhz-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/vawyn97rb3jcbnwwqxzn9n2psvmjdakp-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/k04ddc8ifqjdviclmd3mv37wxnxhrjn9-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/sc7v0v6yvwhgx2iv8xw3sdrg2yg6ss9c-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/pg2bajsr2izhs389wiidngij84q6q1pi-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/2snfzs4130yphxfl129rgd5047ajfnar-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/s3f9l6ik0xv63f5vg32apfm7ndj7cv84-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/izsk825nlxkq6isj5xw45r9i98jb3cx6-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/s7pa9cmwmnjb89vz4akhhjrz36dvayhq-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/vlncdsma5n6nf4xs42n1c7mf6wsywz28-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/hz9msp935r7l4n8hyvjpivad53bwgfx3-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/gjcshxhjbqnnngbjy3mm4d6qiay0p7j1-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/7mx2kc9bk99c10f2s212sp7al75jqwq4-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/06zf7b38jdbq2psprb8nfwwjy835cs1p-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/2n25hv1r0y3zc45sypb7hr6ca03v1nrp-rtl8821ce-0-unstable-2025-03-12 \
  /nix/store/lz2bjkhl5i9rd5j9nrsr018g4f87anm6-rtl8821ce-0-unstable-2025-03-12
```
</details></li>
</ul></details>


---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.rtl8821ce</li>
    <li>linuxPackages_5_4_hardened.rtl8821ce</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 21 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.rtl8821ce</li>
    <li>linuxPackages_5_10_hardened.rtl8821ce (linuxKernel.packages.linux_5_10_hardened.rtl8821ce)</li>
    <li>linuxKernel.packages.linux_5_15.rtl8821ce</li>
    <li>linuxPackages_5_15_hardened.rtl8821ce (linuxKernel.packages.linux_5_15_hardened.rtl8821ce)</li>
    <li>linuxKernel.packages.linux_5_4.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_1.rtl8821ce</li>
    <li>linuxPackages.rtl8821ce (linuxKernel.packages.linux_6_12.rtl8821ce)</li>
    <li>linuxPackages_hardened.rtl8821ce (linuxPackages_6_12_hardened.rtl8821ce)</li>
    <li>linuxKernel.packages.linux_6_13.rtl8821ce</li>
    <li>linuxPackages_6_13_hardened.rtl8821ce (linuxKernel.packages.linux_6_13_hardened.rtl8821ce)</li>
    <li>linuxPackages_latest.rtl8821ce (linuxKernel.packages.linux_6_14.rtl8821ce)</li>
    <li>linuxPackages_6_1_hardened.rtl8821ce (linuxKernel.packages.linux_6_1_hardened.rtl8821ce)</li>
    <li>linuxKernel.packages.linux_6_6.rtl8821ce</li>
    <li>linuxPackages_6_6_hardened.rtl8821ce (linuxKernel.packages.linux_6_6_hardened.rtl8821ce)</li>
    <li>linuxPackages_ham.rtl8821ce (linuxKernel.packages.linux_ham.rtl8821ce)</li>
    <li>linuxPackages_latest-libre.rtl8821ce (linuxKernel.packages.linux_latest_libre.rtl8821ce)</li>
    <li>linuxPackages-libre.rtl8821ce (linuxKernel.packages.linux_libre.rtl8821ce)</li>
    <li>linuxPackages_lqx.rtl8821ce (linuxKernel.packages.linux_lqx.rtl8821ce)</li>
    <li>linuxPackages_xanmod.rtl8821ce (linuxKernel.packages.linux_xanmod.rtl8821ce)</li>
    <li>linuxPackages_xanmod_latest.rtl8821ce (linuxKernel.packages.linux_xanmod_latest.rtl8821ce, linuxPackages_xanmod_stable.rtl8821ce)</li>
    <li>linuxPackages_zen.rtl8821ce (linuxKernel.packages.linux_zen.rtl8821ce)</li>
  </ul>
</details>


---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 42 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_10_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_15.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_15_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_4.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_4_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_1.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_12.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_12_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_13.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_13_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_14.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_1_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_6.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_6_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_ham.rtl8821ce</li>
    <li>linuxKernel.packages.linux_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8821ce</li>
    <li>linuxKernel.packages.linux_libre.rtl8821ce</li>
    <li>linuxKernel.packages.linux_lqx.rtl8821ce</li>
    <li>linuxKernel.packages.linux_xanmod.rtl8821ce</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl8821ce</li>
    <li>linuxKernel.packages.linux_xanmod_stable.rtl8821ce</li>
    <li>linuxKernel.packages.linux_zen.rtl8821ce</li>
    <li>linuxPackages-libre.rtl8821ce</li>
    <li>linuxPackages.rtl8821ce</li>
    <li>linuxPackages_5_10_hardened.rtl8821ce</li>
    <li>linuxPackages_5_15_hardened.rtl8821ce</li>
    <li>linuxPackages_5_4_hardened.rtl8821ce</li>
    <li>linuxPackages_6_12_hardened.rtl8821ce</li>
    <li>linuxPackages_6_13_hardened.rtl8821ce</li>
    <li>linuxPackages_6_1_hardened.rtl8821ce</li>
    <li>linuxPackages_6_6_hardened.rtl8821ce</li>
    <li>linuxPackages_ham.rtl8821ce</li>
    <li>linuxPackages_hardened.rtl8821ce</li>
    <li>linuxPackages_latest-libre.rtl8821ce</li>
    <li>linuxPackages_latest.rtl8821ce</li>
    <li>linuxPackages_lqx.rtl8821ce</li>
    <li>linuxPackages_xanmod.rtl8821ce</li>
    <li>linuxPackages_xanmod_latest.rtl8821ce</li>
    <li>linuxPackages_xanmod_stable.rtl8821ce</li>
    <li>linuxPackages_zen.rtl8821ce</li>
  </ul>
</details>

**Review by Defelo — APPROVED** [review]

**Review by GaetanLepage — APPROVED** [review]
