### PR TITLE
gitin: 0.2.3 -> 0.2.5

### PR DESCRIPTION
**Pull request by sternenseemann**
Get rid of a dependency to the insecure libgit2 version.

Would appreciate testing did a sanity check, but don't use this tool myself.

Ref: https://github.com/isacikgoz/gitin/issues/71

---

Patch to build with latest libgit2 (0.2.5 usually requires 1.0.x). This
is not too bad since we need to patch the go.mod anyways since it
insists on cloning and patch libgit2 locally for some kind of static
build.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by ethancedwards8** [comment]
Result of `nixpkgs-review pr 124356` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitin</li>
  </ul>
</details>

**Comment by Artturin** [comment]
```
       > vendor/github.com/libgit2/git2go/v31/Build_system_dynamic.go:11:3: error: #error "Invalid libgit2 version; this git2go supports libgit2 between v1.1.0 and v1.1.0"
       >    11 | # error "Invalid libgit2 version; this git2go supports libgit2 between v1.1.0 and v1.1.0"
       >       |   ^~~~~
```

**Comment by sternenseemann** [comment]
Yeah, would need to adjust the patch again. In general I'd prefer to drop `gitin` completely. It depends on a precise `libgit2` version at all times and doesn't seem to be maintained actively at the moment (last commit in april).

**Comment by Artturin** [comment]
Pinging the maintainer @kimat

**Comment by kimat** [comment]
I agree with @sternenseemann , removing the package altogether makes much sense.
