### ISSUE TITLE
bluej: fails to launch with NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by foliant755** [NixOS/nixpkgs#537798]
### Nixpkgs version

- Stable (26.05)

### Describe the bug

`bluej` (5.5.0) builds successfully but exits immediately on launch. It is wrapped with `openjdk21.override { enableJavaFX = true; }`, but the resulting JDK does not actually provide the `javafx.*` modules, so `bluej.Boot` cannot load `javafx.application.Application`.

Same failure mode as scenebuilder in #238902 — another JavaFX app broken by the `enableJavaFX` JDK merge not landing the JavaFX modules.

`${openjdk}/bin/java --list-modules | grep javafx` on the wrapped JDK returns nothing: the merged JDK contains no `javafx.*` modules at all.

### Steps to reproduce

```
$ nix run nixpkgs#bluej
WARNING: Unknown module: javafx.graphics specified to --add-opens
WARNING: Unknown module: javafx.graphics specified to --add-opens
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at bluej.Boot.main(Boot.java:169)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	... 10 more
```

The `Unknown module: javafx.graphics` warnings already show that the wrapper's `--add-opens javafx.graphics/...` flags reference a module absent from the JDK.

### Expected behaviour

The BlueJ window opens.

### Relevant log output

```console

```

### Root cause

On Linux, `openjfx21` produces the "modular-sdk" intermediate layout, not a
runnable SDK:

- `modules/javafx.<name>/` — exploded classes, but **no `module-info.class`**,
  so unusable on `--module-path`;
- `modules_libs/javafx.<name>/` — the native libraries;
- plus `modules_src`, `modules_conf`, `modules_legal`, `make`.

This layout is only meant to be merged into a JDK via `enableJavaFX`, and that
merge does not result in the `javafx.*` modules being present in the built JDK's
module set — hence the runtime failure.

### Workaround

Loading JavaFX via the classpath (unnamed module) from `openjfx21`'s `modules/`,
with natives via `-Djava.library.path` pointing at `modules_libs/`, makes BlueJ
start (it then prints the benign `Unsupported JavaFX configuration: classes were
loaded from 'unnamed module'` warning). So the proper fix is likely either to
make the `enableJavaFX` merge actually bundle the modules, or to have `bluej`
consume JavaFX as separate modules/classpath directly.

Reproduces on nixos-26.05 and unstable.

_Note: root-cause analysis and wording assisted by an AI tool; all commands were run and verified by me on the affected system._

### System metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.18.37, NixOS, 26.05 (Yarara), 26.05.20260630.95ca1e2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.7`
 - nixpkgs: `/nix/store/bdn0zqq9mqdc9ccwfnamx4lax9163xr1-source`

### Notify maintainers

@weirdrock
---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
