### PR TITLE
use botan3 in more places

### PR DESCRIPTION
**Pull request by thillux**
## Description of changes

Botan 3.x is the current major version of Botan. Botan 2.x is mostly addressed with bug fixes and minor features these days. As with OpenSSL 1.1.x -> 3.x, try to switch over packages to Botan where possible.

Build successfull/change made in this PR:
* keepassxc
* corectrl
* rehex

Currently not possible:
* https://github.com/rnpgp/rnp main already supports botan3, no version with botan3 support released
* monotone will likely never support botan3
* softhsm currently does not support botan3, see e.g. https://github.com/opendnssec/SoftHSMv2/issues/719
* qownnotes currently does not work with botan3 https://github.com/pbek/QOwnNotes/issues/2786
* biboumi does not support botan3, even in upstream git

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thillux** [comment]
* https://github.com/rnpgp/rnp main already supports botan3
* monotone will likely never support botan3
* softhsm currently does not support botan3
* qownnotes currently does not work with botan3

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by thillux** [comment]
Result of `nixpkgs-review pr 298670` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>corectrl</li>
    <li>keepassxc</li>
    <li>rehex</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
botan3 doesn't seem to work on darwin and keepassxc and rehex where before working on darwin...

```
/nix/store/ks5yv6c2ym66axghjyirnqd4vs5943zq-Libsystem-1238.60.2/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
typedef CCCryptorStatus CCRNGStatus;
        ^
src/lib/rng/system_rng/system_rng.cpp:162:70: error: use of undeclared identifier 'kCCSuccess'
         if(::CCRandomGenerateBytes(output.data(), output.size()) != kCCSuccess) {
                                                                     ^
2 errors generated.
make: *** [Makefile:1061: build/obj/lib/rng_system_rng.o] Error 1
error: builder for '/nix/store/0bqayysm495lh4jjr2br9vb9alywrh96-botan-3.3.0.drv' failed with exit code 2;
```

Maybe new SKD?

**Comment by reckenrode** [comment]
The missing type and symbol should exist, but they’re defined in `CommonCrypto/CommonCryptoError.h`. The version of `CommonCrypto/CommonRandom.h` in the 10.12 SDK does not include that header automatically, but newer versions do (starting in 10.14 as far as I can tell). Assuming botan3 otherwise builds with the 10.12 SDK, it should be possible to patch `src/lib/rng/system_rng/system_rng.cpp` to include the required header.

**Comment by thillux** [comment]
@SuperSandro2000 @reckenrode I added a patch for botan3 which should fix your error. I can't reproduce with my MacOS SDK.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg build botan3 corectrl keepassxc rehex
