### PR TITLE
Fixed `dm-haiku` and `flax` builds

### PR DESCRIPTION
**Pull request by ndl**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
Is dm-haiku still broken after https://github.com/NixOS/nixpkgs/pull/168325?

**Comment by ndl** [comment]
Yes, I believe it was still (or newly?) broken sometime after that change and before `bazel` update.

Leaving the link to the bug you've created @ upstream here as I believe it's unrelated to `bazel` 
 update for `jaxlib` and is a separate issue: https://github.com/deepmind/dm-haiku/issues/373

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 168545` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python310Packages.dm-haiku</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>python39Packages.dm-haiku</li>
    <li>python39Packages.elegy</li>
    <li>python39Packages.flax</li>
    <li>python39Packages.optax</li>
    <li>python39Packages.treex</li>
  </ul>
</details>

**Comment by samuela** [comment]
Huh python310.dm-haiku is failing but python39Packages.dm-haiku seems to work... not sure why that would be. Here's the error:
```
error: builder for '/nix/store/q7d62w8ifxdglklw5l992rc4nsx3vn5f-python3.10-dm-haiku-0.0.6.drv' failed with exit code 1;
       last 10 log lines:
       > FAILED haiku/_src/conv_test.py::ConvTest::test_connect_conv_padding_function_same0
       > FAILED haiku/_src/rms_norm_test.py::RMSNormTest::test_simple_case_with_scale
       > FAILED haiku/_src/conv_test.py::ConvTest::test_connect_conv_padding_function_valid2
       > FAILED haiku/_src/rms_norm_test.py::RMSNormTest::test_slice_axis - AttributeE...
       > FAILED haiku/_src/rms_norm_test.py::RMSNormTest::test_zero_inputs - Attribute...
       > FAILED haiku/_src/rms_norm_test.py::RMSNormTest::test_invalid_axis_ListString
       > FAILED haiku/_src/rms_norm_test.py::RMSNormTest::test_invalid_axis_String - A...
       > FAILED haiku/_src/rms_norm_test.py::RMSNormTest::test_simple_case - Attribute...
       > FAILED haiku/_src/integration/float64_test.py::Float64Test::test_float64_ConvND
       > ==== 13 failed, 2168 passed, 53 skipped, 723 warnings in 154.62s (0:02:34) =====
```
Full log: https://gist.github.com/samuela/98a8e60cf06f76fd514014cfa2fc12b8

**Comment by ndl** [comment]
One of the issues seem to be `AttributeError: module 'collections' has no attribute 'Iterable'` - which checks out as in Python 3.10 it was moved indeed (https://github.com/soravux/scoop/issues/94).

Looks like `dm-haiku` is just not yet adapted to work with Python 3.10?

**Comment by samuela** [comment]
@ndl Ah ok, that makes sense. Would you mind marking dm-haiku as disabled on python 3.10 then? we might as well address that while we're fixing the builds.

**Comment by ndl** [comment]
> Would you mind marking dm-haiku as disabled on python 3.10 then?

SG! I don't have access to the PC with the repo in the next couple of days, so if you need it fixed sooner - feel free to clone / patch / submit yourselves, otherwise I'll add it after 19th April.

**Comment by samuela** [comment]
> SG! I don't have access to the PC with the repo in the next couple of days, so if you need it fixed sooner - feel free to clone / patch / submit yourselves, otherwise I'll add it after 19th April.

Ok, thanks for the heads up! I say we just merge it as is then, and we can address that stuff in the future. Have fun on vacation!
