### PR TITLE
aseprite: 1.3.7 -> 1.3.13

### LINKED ISSUE #352484: Update request: aseprite 1.3.7 → 1.3.9.1
- Package name: aseprite
- Latest released version: [1.3.9.1](https://github.com/aseprite/aseprite/releases/tag/v1.3.9.1)

- Current version on the unstable channel: 1.3.7
- Current version on the stable/release channel: 1.3.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@orivej

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by liberodark**
Diff : https://github.com/aseprite/aseprite/compare/v1.3.7...v1.3.13
Changelog : https://github.com/aseprite/aseprite/releases/tag/v1.3.13
Fix: https://github.com/NixOS/nixpkgs/issues/352484

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by starrymohannad** [comment]
when will this be added :P

**Comment by alikindsys** [comment]
is this still being worked on? are there any blocking problems to get this out of a draft?

**Comment by liberodark** [comment]
> is this still being worked on? are there any blocking problems to get this out of a draft?

Hi,

Yes, I'm having trouble finalizing the compilation.

Best Regards

**Comment by rummik** [comment]
> > is this still being worked on? are there any blocking problems to get this out of a draft?
> 
> Hi,
> 
> Yes, I'm having trouble finalizing the compilation.
> 
> ```
> FAILED: src/app/CMakeFiles/app-lib.dir/commands/cmd_show.cpp.o 
> /nix/store/f16xdvddql4q386incjvxcys4g4dcavj-clang-wrapper-19.1.7/bin/clang++ -DCLIP_ENABLE_IMAGE=1 -DENABLE_DATA_RECOVERY -DENABLE_NEWS -DENABLE_SAVE -DENABLE_SCRIPTING -DENABLE_WEBSOCKET -DFMT_SHARED -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DIXWEBSOCKET_USE_ZLIB -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_CLIP -DLAF_WITH_REGION -DLIBARCHIVE_STATIC -DLUA_FLOORN2I=F2Ifloor -DLUA_USE_LINUX=1 -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_UNIX -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/build/source/third_party/TinyEXIF -I/nix/store/dkljk9vsk9yf5r8x53ph3yfppag8ix56-pixman-0.44.2/include/pixman-1 -I/build/source/third_party/simpleini -I/build/source/src/observable -I/nix/store/qhjihbfx6pvj6yarz4dz145k4q7k0p17-freetype-2.13.3-dev/include/freetype2 -I/nix/store/639h6486i8n15i4ijsvjk3cdsnp7kx5r-harfbuzz-10.2.0-dev/include/harfbuzz -I/build/source/build/src/app -I/build/source/third_party/lua -I/build/source/third_party/IXWebSocket -I/build/source/laf -I/build/source/build/laf -I/build/source/src -I/build/source/src/doc/.. -I/nix/store/2jbf4jk9vs7v71navv10wm7jmg1dqkx7-skia-aseprite-m102-861e4743af -I/build/source/src/fixmath/.. -I/build/source/third_party/cityhash/src -I/build/source/src/dio/.. -I/build/source/src/observable/. -I/build/source/third_party/json11 -I/build/source/third_party/libarchive/libarchive -I/build/source/third_party/tinyexpr -I/build/source/third_party/qoi -Wall -Wno-switch -Wimplicit-fallthrough -O3 -DNDEBUG -std=c++17   -Wno-sign-compare -MD -MT src/app/CMakeFiles/app-lib.dir/commands/cmd_show.cpp.o -MF src/app/CMakeFiles/app-lib.dir/commands/cmd_show.cpp.o.d -o src/app/CMakeFiles/app-lib.dir/commands/cmd_show.cpp.o -c /build/source/src/app/commands/cmd_show.cpp
> /build/source/src/app/commands/cmd_show.cpp:150:26: error: no member named 'ShowBrushPreviewInPreview' in 'app::gen::CommandId'
>   150 |     : Command(CommandId::ShowBrushPreviewInPreview(), CmdUIOnlyFlag)
> ```
> 
> Best Regards

I think I had solved this particular problem when I was preparing code for a PR before seeing this existing one.  IIRC the solution was to unpack the translation strings in a way that didn't remove the existing English strings.

**Comment by liberodark** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 377614`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>aseprite</li>
  </ul>
</details>

**Comment by liberodark** [comment]
Have see issue when try to change language that not work in 1.3.7 that work.

**Comment by liberodark** [comment]
> > Have see issue when try to change language that not work in 1.3.7 that work.
> 
> Oh. Looks like it's caused by symlinking the translations

Yep i think too
But have no check why at this time.

File: pkgs/by-name/as/aseprite/package.nix [hunk 1]
```diff
@@ -33,15 +33,37 @@
...
+  ];
+
+  sourceRoot = "aseprite-source";
+
+  postUnpack = ''
+    # Link additional translations. Note: Although there's an English
+    # translation in the strings repo, it might not be up-to-date with the
+    # existing file, so it's important to not clobber the existing file when
+    # bringing in the translations.
+    cp --symbolic-link --no-clobber $PWD/aseprite-strings/* ./aseprite-source/data/strings
```
Comment (rummik) [inline pkgs/by-name/as/aseprite/package.nix:65]: Removing `--symbolic-link` here should fix translations.  May also want to update the comment since it's being copied rather than linked

**Comment by liberodark** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 377614`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>aseprite</li>
  </ul>
</details>

File: pkgs/by-name/as/aseprite/package.nix [hunk 2]
```diff
@@ -33,15 +33,37 @@
...
-    rev = "v" + finalAttrs.version;
-    fetchSubmodules = true;
-    hash = "sha256-75kYJXmyags0cW2D5Ksq1uUrFSCAkFOdmn7Ya/6jLXc=";
-  };
+  srcs = [
+    (fetchFromGitHub {
+      name = "aseprite-source";
+      owner = "aseprite";
+      repo = "aseprite";
+      rev = "v${finalAttrs.version}";
```
Comment (GaetanLepage) [inline pkgs/by-name/as/aseprite/package.nix:43]:
```suggestion
      tag = "v${finalAttrs.version}";
```

File: pkgs/by-name/as/aseprite/package.nix [hunk 3]
```diff
@@ -33,15 +33,37 @@
...
+    (fetchFromGitHub {
+      name = "aseprite-strings";
+      owner = "aseprite";
+      repo = "strings";
+      rev = "7b0af61dec1d98242d7eb2e9cab835d442d21235";
+      hash = "sha256-8OwwHCFP55pwLjk5O+a36hDZf9uX3P7cNliJM5SZdAg=";
+    })
+  ];
+
+  sourceRoot = "aseprite-source";
```
Comment (GaetanLepage) [inline pkgs/by-name/as/aseprite/package.nix:58]:
```suggestion
  sourceRoot = "${src.name}/aseprite-source";
```
Not 100% sure about this.

File: pkgs/by-name/as/aseprite/package.nix [hunk 4]
```diff
@@ -75,33 +97,14 @@ clangStdenv.mkDerivation (finalAttrs: {
...
-        hash = "sha256-GyCCxbhgf0vST20EH/+KkNLrF+U9Xzgpxlao8s925PQ=";
-      };
-    in
-    ''
-      sed -i src/ver/CMakeLists.txt -e "s-set(VERSION \".*\")-set(VERSION \"$version\")-"
-      rm -rf data/strings
-      cp -r ${strings} data/strings
-    '';
+  postPatch = ''
+    sed -i src/ver/CMakeLists.txt -e "s-set(VERSION \".*\")-set(VERSION \"$version\")-"
```
Comment (GaetanLepage) [inline pkgs/by-name/as/aseprite/package.nix:106]: Can we use `substituteInPlace` for this?

File: pkgs/by-name/as/aseprite/package.nix [hunk 5]
```diff
@@ -116,15 +119,16 @@ clangStdenv.mkDerivation (finalAttrs: {
     "-DUSE_SHARED_LIBPNG=ON"
     "-DUSE_SHARED_LIBWEBP=ON"
     "-DUSE_SHARED_PIXMAN=ON"
-    "-DUSE_SHARED_TINYXML=ON"
+    #"-DUSE_SHARED_TINYXML=ON"
```
Comment (GaetanLepage) [inline pkgs/by-name/as/aseprite/package.nix:122]: Have you forgotten to remove this completely?

Comment (liberodark) [reply pkgs/by-name/as/aseprite/package.nix:122]: Not sure for now.

Comment (GaetanLepage) [reply pkgs/by-name/as/aseprite/package.nix:122]: Then, maybe mark this PR as a draft then.

**Review by GaetanLepage — APPROVED** [review]
LGTM
