### PR TITLE
pythonPackages.aioesphomeapi: 2.0.1 -> 2.2.0

### PR DESCRIPTION
**Pull request by WilliButz**
###### Motivation for this change
The old version is incompatible with the currently packaged version of home-assistant:
```
Unable to import esphome: cannot import name 'HomeassistantServiceCall' from 'aioesphomeapi'
```
https://github.com/esphome/aioesphomeapi/commits/v2.2.0
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [x] tested with personal esphome setup

### CODE REVIEW

**Comment by lheckemann** [comment]
This is marked as broken based on the protobuf version, so it doesn't want to build in isolation, but `nix-build -E 'with import ./. {}; home-assistant.override {extraComponents = ["esphome"];}'` seems to work.

**Comment by WilliButz** [comment]
backported in e0f36e768b4099de4affc4a03c2a00f35b3e54fb
