### PR TITLE
various cross and gobject-introspection fixes

### PR DESCRIPTION
**Pull request by Artturin**
remove unnecessary preInstall

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/development/libraries/gdk-pixbuf/default.nix [hunk 1]
```diff
@@ -108,9 +107,9 @@ stdenv.mkDerivation rec {
           install_name_tool -change @rpath/libgdk_pixbuf-2.0.0.dylib $out/lib/libgdk_pixbuf-2.0.0.dylib $f
           mv $f ''${f%.dylib}.so
       done
-    '' + lib.optionalString (stdenv.hostPlatform == stdenv.buildPlatform) ''
+    '' + ''
       # We need to install 'loaders.cache' in lib/gdk-pixbuf-2.0/2.10.0/
-      $dev/bin/gdk-pixbuf-query-loaders --update-cache
+      ${stdenv.hostPlatform.emulator buildPackages} $dev/bin/gdk-pixbuf-query-loaders --update-cache
```
Comment (Artturin) [inline pkgs/development/libraries/gdk-pixbuf/default.nix:112]: this will be bash on build == host and a emulator otherwise

gobject-introspection already brings in the emulator to the closure

**Comment by Mindavi** [comment]
Can we now start setting strictDeps on these too or do you want to defer that?

**Review by Mindavi — APPROVED** [review]
Diff looks good to me. We should take care to not remove the flags in packages where it's not enabled by default, if there are any that don't enable it by default.

**Comment by Artturin** [comment]
> Can we now start setting strictDeps on these too or do you want to defer that?

lets do it in a separate pr

i use a command like this to generate the list of attrs and then i input that in to diffing
`git diff --name-only HEAD HEAD~6 | rev | cut -d '/' -f 2 | rev > attrlist`

File: pkgs/development/libraries/json-glib/default.nix [hunk 2]
```diff
@@ -37,22 +36,26 @@ stdenv.mkDerivation rec {
...
     glib
   ];
 
-  mesonFlags = lib.optionals (!withIntrospection) [
-    "-Dintrospection=disabled"
-    # gi-docgen relies on introspection data
-    "-Dgtk_doc=disabled"
-  ];
+  postPatch = ''
+    substituteInPlace doc/meson.build \
```
Comment (jtojnar) [inline pkgs/development/libraries/json-glib/default.nix:55]: Add TODO comment here as well

File: pkgs/development/libraries/atk/default.nix [hunk 3]
```diff
@@ -39,15 +39,13 @@ stdenv.mkDerivation rec {
     fixDarwinDylibNames
   ];
 
+  buildInputs = [ gobject-introspection ];
```
Comment (jtojnar) [inline pkgs/development/libraries/atk/default.nix:42]: Why add this to `buildInputs`? It should not be a runtime dependency.

Comment (Mindavi) [reply pkgs/development/libraries/atk/default.nix:42]: libgirepository can be used at runtime, right?

Comment (jtojnar) [reply pkgs/development/libraries/atk/default.nix:42]: Yes, but ATK should not depend on `libgirepository`.

Comment (Mindavi) [reply pkgs/development/libraries/atk/default.nix:42]: Then it shouldn't be in buildInputs :)

Comment (Mindavi) [reply pkgs/development/libraries/atk/default.nix:42]: For some reason it then does require it at runtime, or the meson file is wrong.

Comment (jtojnar) [reply pkgs/development/libraries/atk/default.nix:42]: Perhaps it needs `native=True` here: https://github.com/mesonbuild/meson/blob/16ed82a62f535475b0eff6acc2d7c34c5265c16f/mesonbuild/modules/gnome.py#L772

**Comment by Artturin** [comment]
draft because im still working on this

File: pkgs/development/libraries/atk/default.nix (hunk 3 above)
Comment (Artturin) [reply pkgs/development/libraries/atk/default.nix:42]: i applied

```diff
diff --git a/pkgs/development/tools/build-managers/meson/default.nix b/pkgs/development/tools/build-managers/meson/default.nix
index f62bb22314d..b46f918b9c3 100644
--- a/pkgs/development/tools/build-managers/meson/default.nix
+++ b/pkgs/development/tools/build-managers/meson/default.nix
@@ -71,6 +71,11 @@ python3.pkgs.buildPythonApplication rec {
     ./fix-gtkdoc-when-using-multiple-apple-frameworks.patch
   ];
 
+  postPatch = ''
+    substituteInPlace mesonbuild/modules/gnome.py \
+      --replace "(state, 'gobject-introspection-1.0')" "(state, 'gobject-introspection-1.0', native = True)"
+  '';
+
   setupHook = ./setup-hook.sh;
 
   # Meson included tests since 0.45, however they fail in Nixpkgs because they
```

to meson because of some projects using the wrong gi when build == host != target and gobject-introspection was in buildInputs

that fixed them

gobject-introspection still has to be in buildInputs

otherwise

```
json-glib-aarch64-unknown-linux-gnu> /nix/store/s9m5ww62bsyx0jzylndxicvkmdn7x5bj-aarch64-unknown-linux-gnu-binutils-2.38/bin/aarch64-unknown-linux-gnu-ld: skipping incompatible /nix/store/c79djpxhga419drlbf6v850pvpjfqsgl-gobject-introspection-wrapped-1.72.0/lib/libgirepository-1.0.so when searching for -lgirepository-1.0
json-glib-aarch64-unknown-linux-gnu> /nix/store/s9m5ww62bsyx0jzylndxicvkmdn7x5bj-aarch64-unknown-linux-gnu-binutils-2.38/bin/aarch64-unknown-linux-gnu-ld: cannot find -lgirepository-1.0: No such file or directory
json-glib-aarch64-unknown-linux-gnu> /nix/store/s9m5ww62bsyx0jzylndxicvkmdn7x5bj-aarch64-unknown-linux-gnu-binutils-2.38/bin/aarch64-unknown-linux-gnu-ld: skipping incompatible /nix/store/c79djpxhga419drlbf6v850pvpjfqsgl-gobject-introspection-wrapped-1.72.0/lib/libgirepository-1.0.so when searching for -lgirepository-1.0
```

when gi is in buildInputs

```
⋮ 245│/nix/store/s9m5ww62bsyx0jzylndxicvkmdn7x5bj-aarch64-unknown-linux-gnu-binutils-2.38/bin/aarch64-unknown-linux-gnu-ld: skipping incompatibl
e /nix/store/c79djpxhga419drlbf6v850pvpjfqsgl-gobject-introspection-wrapped-1.72.0/lib/libgirepository-1.0.so when searching for -lgirepository-1.0
```

File: pkgs/development/libraries/tracker/default.nix [hunk 4]
```diff
@@ -50,11 +56,8 @@ stdenv.mkDerivation rec {
     gobject-introspection
     docbook-xsl-nons
     docbook_xml_dtd_45
-    python3 # for data-generators
-    systemd # used for checks to install systemd user service
-    dbus # used for checks and pkg-config to install dbus service/s
-  ] ++ checkInputs; # gi is in the main meson.build and checked regardless of
-                    # whether tests are enabled
+    (buildPackages.python3.withPackages (p: [ p.pygobject3 ]))
```
Comment (Artturin) [inline pkgs/development/libraries/tracker/default.nix:59]: can be switched to use pythonForBuild once https://github.com/NixOS/nixpkgs/pull/177888 is merged

**Review by SuperSandro2000 — COMMENTED** [review]
Can we set strictDeps to prevent regressions?

File: pkgs/development/libraries/atk/default.nix (hunk 3 above)
Comment (jtojnar) [reply pkgs/development/libraries/atk/default.nix:46]: But [`libgirepostiory`](https://gi.readthedocs.io/en/latest/writingbindings/libgirepository.html), as I understand it, is for runtime loading of typelibs. I still do not see any reason for libraries just providing typelibs to need it – it should only be necessary for stuff like `pygobject`.

File: pkgs/development/libraries/libical/default.nix [hunk 5]
```diff
@@ -37,22 +36,21 @@ stdenv.mkDerivation rec {
...
-  ] ++ lib.optionals withIntrospection [
-    gobject-introspection
-    vala
   ] ++ lib.optionals stdenv.isDarwin [
     fixDarwinDylibNames
   ];
   installCheckInputs = [
     # running libical-glib tests
-    (python3.withPackages (pkgs: with pkgs; [
+    (buildPackages.python3.withPackages (pkgs: with pkgs; [
```
Comment (Artturin) [inline pkgs/development/libraries/libical/default.nix:53]: same as tracker

**Comment by Artturin** [comment]
> Can we set strictDeps to prevent regressions?

First fix then https://github.com/NixOS/nixpkgs/pull/177538#issuecomment-1154264286

**Comment by Artturin** [comment]
Many meson projects are looking for gir, vapi, and gtk-doc wrong
See https://gitlab.gnome.org/GNOME/libgudev/-/merge_requests/27 for how to fix it

File: pkgs/tools/networking/networkmanager/default.nix [hunk 6]
```diff
@@ -61,7 +64,8 @@ stdenv.mkDerivation rec {
     sha256 = "sha256-nP/SrcaGUTFt8tL4oJ4XF7sdDC6jic/HIaAQnbmzWCY=";
   };
 
-  outputs = [ "out" "dev" "devdoc" "man" "doc" ];
+  outputs = [ "out" "dev" ]
+    ++ lib.optionals (stdenv.buildPlatform == stdenv.hostPlatform) [ "devdoc" "man" "doc" ];
```
Comment (jtojnar) [inline pkgs/tools/networking/networkmanager/default.nix:68]: Are the man pages not cross buildable either?

File: pkgs/tools/networking/networkmanager/default.nix [hunk 7]
```diff
@@ -140,10 +146,15 @@ stdenv.mkDerivation rec {
     newt
     libsoup
     jansson
+    dbus
```
Comment (jtojnar) [inline pkgs/tools/networking/networkmanager/default.nix:149]: Add a comment that this is only used for getting service installation directory paths from the pkg-config, since libdbus should not really be needed.

File: pkgs/tools/networking/networkmanager/default.nix (hunk 6 above)
Comment (Artturin) [reply pkgs/tools/networking/networkmanager/default.nix:68]: This patch will be needed https://github.com/void-linux/void-packages/blob/master/srcpkgs/NetworkManager/patches/no-gtk-doc.patch

Though I can just copy the outputs from the native package to the new one

File: pkgs/development/libraries/gdk-pixbuf/default.nix [hunk 8]
```diff
@@ -108,9 +105,9 @@ stdenv.mkDerivation rec {
...
```
Comment (Mindavi) [inline pkgs/development/libraries/gdk-pixbuf/default.nix:110]: Meh, too bad we have to do this :(

File: pkgs/development/libraries/libgudev/default.nix [hunk 9]
```diff
@@ -22,6 +22,15 @@ stdenv.mkDerivation rec {
     sha256 = "1al6nr492nzbm8ql02xhzwci2kwb1advnkaky3j9636jf08v41hd";
   };
 
+  patches = [
+    # https://gitlab.gnome.org/GNOME/libgudev/-/merge_requests/27
```
Comment (Mindavi) [inline pkgs/development/libraries/libgudev/default.nix:26]: Could use some love 😉

File: pkgs/development/libraries/librdf/raptor2.nix [hunk 10]
```diff
@@ -1,26 +1,28 @@
-{ lib, stdenv, fetchurl, libxml2, libxslt }:
+{ lib, stdenv, libxml2, libxslt, pkg-config, cmake, fetchFromGitHub, perl, bison, flex, fetchpatch }:
 
 stdenv.mkDerivation rec {
   pname = "raptor2";
-  version = "2.0.15";
+  version = "unstable-2022-06-06";
```
Comment (Mindavi) [inline pkgs/development/libraries/librdf/raptor2.nix:5]: Great that you managed to fix this too!

File: pkgs/development/libraries/opencv/4.x.nix [hunk 11]
```diff
@@ -291,11 +292,15 @@ stdenv.mkDerivation {
...
+    "-DProtobuf_PROTOC_EXECUTABLE=${lib.getExe buildPackages.protobuf}"
     "-DPROTOBUF_UPDATE_FILES=ON"
     "-DOPENCV_ENABLE_NONFREE=${printEnabled enableUnfree}"
     "-DBUILD_TESTS=OFF"
     "-DBUILD_PERF_TESTS=OFF"
     "-DBUILD_DOCS=${printEnabled enableDocs}"
+    # "OpenCV disables pkg-config to avoid using of host libraries. Consider using PKG_CONFIG_LIBDIR to specify target SYSROOT"
+    # but we have proper separation of build and host libs :), fixes cross
+    "-DOPENCV_ENABLE_PKG_CONFIG=ON"
     (opencvFlag "IPP" enableIpp)
```
Comment (Mindavi) [inline pkgs/development/libraries/opencv/4.x.nix:304]: Woo!

**Review by Mindavi — APPROVED** [review]
One question and mostly some random comments and thoughts. Thanks for moving this forward! Also nice that we can get rid of gi in buildInputs in a few packages.

**Comment by Mindavi** [comment]
Btw, haven't tested building this, might do that but I don't have that much time right now. We'll see.

File: pkgs/development/libraries/gobject-introspection/wrapper.nix [hunk 12]
```diff
@@ -7,9 +7,13 @@
 
 # to build, run
 # `nix build ".#pkgsCross.aarch64-multiplatform.buildPackages.gobject-introspection"`
-gobject-introspection-unwrapped.overrideAttrs (_previousAttrs: {
+gobject-introspection-unwrapped.overrideAttrs (previousAttrs: {
   pname = "gobject-introspection-wrapped";
-  postFixup = ''
+  depsTargetTargetPropagated = [ gobject-introspection-unwrapped ];
```
[the remark this answers is not in the document]
Comment (Mindavi) [reply pkgs/development/libraries/gobject-introspection/wrapper.nix:12]: Ahhh, then it's quite important to get that working too for the full experience. But fine if we defer that, doesn't make sense to do it in this pr

[the remark this answers is not in the document]
Comment (jtojnar) [reply pkgs/development/libraries/gobject-introspection/wrapper.nix:12]: Last time I checked, the meson build was still incomplete but feel free to try it.

File: pkgs/development/libraries/gobject-introspection/default.nix [hunk 13]
```diff
@@ -27,7 +27,7 @@
 # it may be worth thinking about using multiple derivation outputs
 # In that case its about 6MB which could be separated
 
-stdenv.mkDerivation rec {
+stdenv.mkDerivation (finalAttrs: {
```
[the remark this answers is not in the document]
Comment (Artturin) [reply pkgs/development/libraries/gobject-introspection/default.nix:30]: see postFixup

File: pkgs/development/libraries/gobject-introspection/wrapper.nix (hunk 12 above)
[the remark this answers is not in the document]
Comment (Artturin) [reply pkgs/development/libraries/gobject-introspection/wrapper.nix:12]: > Last time I checked, the meson build was still incomplete but feel free to try it.

at least arch uses the meson builds for both

[the remark this answers is not in the document]
Comment (Artturin) [reply pkgs/development/libraries/gobject-introspection/wrapper.nix:12]: also, we will need this for `build == host == target` when `strictDeps = true` if we do not add gobject-introspection to buildInputs

``
  depsBuildBuild = [
    pkg-config
  ];
```

File: pkgs/development/libraries/gobject-introspection/default.nix [hunk 14]
```diff
@@ -120,11 +124,21 @@ stdenv.mkDerivation rec {
     rm $out/lib/libregress-1.0${stdenv.targetPlatform.extensions.sharedLibrary}
   '';
 
+  # when cross-compiling and using the wrapper then when a package looks up the g_ir_X
+  # variable with pkg-config they'll get the host version which can't be run
+  # switch the variables to use g_ir_X from path instead of an absolute path
+  postFixup = lib.optionalString (!lib.hasSuffix "wrapped" finalAttrs.pname) ''
```
[the remark this answers is not in the document]
Comment (Artturin) [reply pkgs/development/libraries/gobject-introspection/default.nix:130]: i think it is fine the way it is

File: pkgs/development/libraries/gobject-introspection/setup-hook.sh [hunk 15]
```diff
@@ -10,7 +10,7 @@ make_gobject_introspection_find_gir_files() {
     fi
 }
 
-addEnvHooks "$hostOffset" make_gobject_introspection_find_gir_files
+addEnvHooks "$targetOffset" make_gobject_introspection_find_gir_files
```
[the remark this answers is not in the document]
Comment (Artturin) [reply pkgs/development/libraries/gobject-introspection/setup-hook.sh:13]: @Ericson2314 also had it in his PR https://github.com/NixOS/nixpkgs/pull/88222/files#diff-c0d47b1d6e8a614ceb2b7083f7ebc37d288cbfc1fac81ec83ccde8a94718eb8c

File: pkgs/development/libraries/libgudev/default.nix (hunk 9 above)
Comment (Artturin) [reply pkgs/development/libraries/libgudev/default.nix:26]: done and updated patch

Comment (Artturin) [reply pkgs/development/libraries/libgudev/default.nix:26]: done

File: pkgs/development/libraries/gobject-introspection/wrapper.nix (hunk 12 above)
[the remark this answers is not in the document]
Comment (Artturin) [reply pkgs/development/libraries/gobject-introspection/wrapper.nix:12]: btw this is the error with wich the freedesktop modem related packages fail with when not using meson

```
libqmi-aarch64-unknown-linux-gnu> /build/libqmi-1.30.8/src/libqmi-glib/tmp-introspect2d8e4td2/.libs/Qmi-1.0: error while loading shared libraries: libqmi-glib.so.5: cannot open shared object file: No such file or directory
libqmi-aarch64-unknown-linux-gnu> Command '['/nix/store/wr4mjr9gadvwz6c88fgz4ldzn21sxkpz-qemu-7.0.0/bin/qemu-aarch64', '/build/libqmi-1.30.8/src/libqmi-glib/tmp-introspect2d8e4td2/.libs/Qmi-1.0', '--introspect-dump=/build/libqmi-1.30.8/src/libqmi-glib/tmp-introspect2d8e4td2/functions.txt,/build/libqmi-1.30.8/src/libqmi-glib/tmp-introspect2d8e4td2/dump.xml']' returned non-zero exit status 127.
libqmi-aarch64-unknown-linux-gnu> make[4]: *** [/nix/store/jwpcacx8sd4vj0ckk5wxrzn2iwcpp35s-gobject-introspection-aarch64-unknown-linux-gnu-1.72.0-dev/share/gobject-introspection-1.0/Makefile.introspection:156: Qmi-1.0.gir] Error 1
```

File: pkgs/development/libraries/gobject-introspection/default.nix (hunk 14 above)
[the remark this answers is not in the document]
Comment (Mindavi) [reply pkgs/development/libraries/gobject-introspection/default.nix:130]: let's leave it then

**Comment by SuperSandro2000** [comment]
> list of files in which strictDeps will be enabled in separate PRs

Yes, please. This PR is getting quite big.

File: pkgs/development/python-modules/pygobject/3.nix [hunk 16]
```diff
@@ -37,8 +42,9 @@ buildPythonPackage rec {
   ];
 
   buildInputs = [
-    glib
+    # # .so files link to these
```
Comment (SuperSandro2000) [inline pkgs/development/python-modules/pygobject/3.nix:45]:
```suggestion
    # .so files link to these
```

**Comment by Mindavi** [comment]
Hey Artturin, can we get this in soon rather than piling up stuff? I don't think it's very convenient to keep adding things, we can always iterate on this later on, right?

Especially the more leafy fixes are fine to add later, IMO.

Also cc @Ericson2314 who may be interested in this.

**Review by MatthewCroughan — APPROVED** [review]
This fixes quite a lot of issues for me personally when trying to cross-compile for riscv64, so I'd really love to see this merged.

**Comment by Artturin** [comment]
Modemmanager (a dep of networkmanager) should be fixed before merge

I'll do it tomorrow as I was on vacation for 3 days

**Comment by Artturin** [comment]
Also strictDeps gobject-introspection native will be broken due to not propagating itself to buildInputs while in nativeBuildInputs when not specified in buildInputs

**Comment by Artturin** [comment]
reverted the propagation 

original commits can be found in https://github.com/Artturin/nixpkgs/tree/fixcross3-backup

**Comment by Artturin** [comment]
this flake built
```
{
  description = "cross-compile the sd-image-aarch64 on x86_64-linux to aarch64-multiplatform";
  inputs = {
    #nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixpkgs.url = "/home/artturin/nixgits/my-nixpkgs/.worktree/1";
  };

  outputs = { self, nixpkgs }: {

    nixosConfigurations.cross-vm = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ({ pkgs, lib, modulesPath, ... }: {
          nixpkgs = {
            crossSystem = lib.systems.examples.aarch64-multiplatform;
          };

          imports = [ (modulesPath + "/installer/sd-card/sd-image-aarch64.nix") ];

          users.mutableUsers = false;
          users.users.root = {
            password = "root";
          };
          users.users.user = {
            password = "user";
            isNormalUser = true;
            extraGroups = [ "wheel" ];
          };
          system.stateVersion = "22.05";
        })
      ];
    };

    packages.x86_64-linux.default = self.nixosConfigurations.cross-vm.config.system.build.sdImage;
    packages.x86_64-linux.vm = self.nixosConfigurations.cross-vm.config.system.build.vm;
    apps.x86_64-linux.vm = {
      type = "app";
      program = "${self.defaultPackage.x86_64-linux}/bin/run-nixos-vm-cross";
    };
  };
}
```

**Comment by trofi** [comment]
Bisect claims that `gtk2` broke after a83d2f7c918a5badab204d57d8620adb926e618b `gobject-introspection: cross improvements`:

```
$ nix build -f. gtk2 -L
...
(lost logs will update in a ~hour)
```

**Comment by Artturin** [comment]
`gtk+> make[4]: *** No rule to make target 'g-ir-scanner', needed by 'Gtk-2.0.gir'.  Stop.`

**Comment by Artturin** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/181413

**Comment by trofi** [comment]
Bisect claims 10362d728084d8810f6af2f8588b172e092b01e6 `librdf_raptor2: 2.0.15 -> unstable-2022-06-06` boroke a bunch of packages in `staging-next`. All have the same symptom: underlinked `liblrdf.so` library is not usable by it's final depends:

Broken packages are `non`, `tony`, `rascal`, `hydrogen`, `guitarix`. Example failure:

```
$ nix build -f. non -L
...
non-unstable> /nix/store/ydvvnn6mi99kyp9an1gnrcga1dr5v5x0-binutils-2.38/bin/ld: /nix/store/1kkgkg3irmk78pk6c96154fns1k5133g-lrdf-0.6.1/lib/liblrdf.so: undefined reference to `xsltNewSecurityPrefs'
non-unstable> /nix/store/ydvvnn6mi99kyp9an1gnrcga1dr5v5x0-binutils-2.38/bin/ld: /nix/store/1kkgkg3irmk78pk6c96154fns1k5133g-lrdf-0.6.1/lib/liblrdf.so: undefined reference to `xmlXPathNewContext'
```

I think `lrdf` library is linked incorrectly and is missing some `xml` library.

The simplest way to trigger the bug earlier is to add an `LDFLAGS = "-Wl,--no-undefined"` hack locally:

```
$ nix build --impure --expr 'with import ./.{}; lrdf.overrideAttrs (oa: { LDFLAGS = "-Wl,--no-undefined"; })' -L
...
lrdf> libtool: link: gcc -shared  -fPIC -DPIC  .libs/lrdf.o .libs/lrdf_multi.o .libs/md5.o   -L/nix/store/28xxhxqb97j48yj4ivvl0c6kih9l2r52-raptor2-unstable-2022-06-06/lib -lraptor2  -g -g -O2 -g -O2 -Wl,--no-undefined   -Wl,-soname -Wl,liblrdf.so.2 -o .libs/liblrdf.so.2.0.0
lrdf> /nix/store/ydvvnn6mi99kyp9an1gnrcga1dr5v5x0-binutils-2.38/bin/ld: /nix/store/28xxhxqb97j48yj4ivvl0c6kih9l2r52-raptor2-unstable-2022-06-06/lib/libraptor2.a(raptor_sax2.c.o): in function `raptor_sax2_parse_chunk':
lrdf> (.text+0x511): undefined reference to `xmlParseChunk'
lrdf> /nix/store/ydvvnn6mi99kyp9an1gnrcga1dr5v5x0-binutils-2.38/bin/ld: (.text+0x55d): undefined reference to `xmlCreatePushParserCtxt'
lrdf> /nix/store/ydvvnn6mi99kyp9an1gnrcga1dr5v5x0-binutils-2.38/bin/ld: (.text+0x589): undefined reference to `xmlCtxtUseOptions'
```

**Comment by trofi** [comment]
> Bisect claims [10362d7](https://github.com/NixOS/nixpkgs/commit/10362d728084d8810f6af2f8588b172e092b01e6) `librdf_raptor2: 2.0.15 -> unstable-2022-06-06` boroke a bunch of packages in `staging-next`. All have the same symptom: underlinked `liblrdf.so` library is not usable by it's final depends:

> I think `lrdf` library is linked incorrectly and is missing some `xml` library.

Possible fix (or workaround) is to enable shared libs by default. Proposed as: https://github.com/NixOS/nixpkgs/pull/182727
