### ISSUE TITLE
wlx-overlay-s: does not build (?)

### ISSUE THREAD

**Issue by c-x-berger** [NixOS/nixpkgs#406898]
### Nixpkgs version

- Stable (24.11)

### Describe the bug

`wlx-overlay-s` does not build on NixOS 24.11. This seems to be due to an older version of rustc that doesn't support `&mut` in `const` functions.

### Steps to reproduce

Try adding `pkgs.wlx-overlay-s` to `environment.systemPackages` and see build failure

### Expected behaviour

package should build

### Relevant log output

```console
error: builder for '/nix/store/mhqr7m4vi642p9p4a0lcj8p3y3j73fln-wlx-overlay-s-25.4.2.drv' failed with exit code 101;
       last 25 log lines:
       >    --> src/gui/canvas/mod.rs:180:27
       >     |
       > 180 |     pub const fn data_mut(&mut self) -> &mut D {
       >     |                           ^^^^^^^^^
       >     |
       >     = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
       >
       > error[E0658]: mutable references are not allowed in constant functions
       >    --> src/gui/canvas/mod.rs:180:41
       >     |
       > 180 |     pub const fn data_mut(&mut self) -> &mut D {
       >     |                                         ^^^^^^
       >     |
       >     = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
       >
       > error[E0658]: mutable references are not allowed in constant functions
       >    --> src/gui/canvas/mod.rs:181:9
       >     |
       > 181 |         &mut self.data.data
       >     |         ^^^^^^^^^^^^^^^^^^^
       >     |
       >     = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
       >
       > For more information about this error, try `rustc --explain E0658`.
       > error: could not compile `wlx-overlay-s` (bin "wlx-overlay-s") due to 9 previous errors
       For full logs, run 'nix log /nix/store/mhqr7m4vi642p9p4a0lcj8p3y3j73fln-wlx-overlay-s-25.4.2.drv'.
```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.14.5, NixOS, 24.11 (Vicuna), 24.11.20250511.a39ed32`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.14`
 - nixpkgs: `/nix/store/sz6hhgiffszv5v700si1857l4ssd4w5b-source`

### Notify maintainers

@Scrumplex 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by c-x-berger** [comment]
I think this was broken in #398193 - you can see a similar build failure [in the test output](https://github.com/NixOS/nixpkgs/pull/398193/checks?check_run_id=40797698072)
