### PR TITLE
Fix hydra on release-17.09 by upgrading: 2017-09-14 -> 2017-10-26

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

Currently `hydra` fails to build on `release-17.09` because `nixUnstable` got upgraded:

```
$ nix-build -A hydra
these derivations will be built:
  /nix/store/xii3bpaz4cfc5hgzk0iwqa8gr2x4in8c-hydra-2017-09-14.drv
building path(s) ‘/nix/store/al2c699sjrrsm6kpqklmlvm2siynqpm1-hydra-2017-09-14’
...
hydra-eval-jobs.cc:13:26: fatal error: common-opts.hh: No such file or directory
 #include "common-opts.hh"
                          ^
compilation terminated.
```

This is fixed by cherry-picking 286faa28341e53a8152e5170f8c57b26ea66378b on `release-17.09` which upgrades hydra to the latest HEAD which can build against the latest `nixUnstable` (https://github.com/NixOS/hydra/commit/2cdc84f34f4de647dd89c5ef503782a3a48ff623). 

@orivej ping.

###### Things done

`nix-build nixos/tests/hydra.nix` succeeds.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Thank you. Release maintainers don't like cherry picks without the reference to the original commit (`git cherry-pick -x`), so I had to add it.

**Comment by LnL7** [comment]
I think we should add hydra to the release job.

**Comment by basvandijk** [comment]
@orivej TIL about `cherry-pick -x`. Thanks.
