### ISSUE TITLE
Rust crate 'clap' does not compile with the packaged rustc version

### ISSUE THREAD

**Issue by legendofmiracles** [NixOS/nixpkgs#137060]
### Describe the bug
The rust crate 'clap' does not compile with the outdated rust version (`1.53.0`) in nixpkgs, due to the use of a 'unstable' feature, which has been stabilized in `1.54.0`. A ton of rust packages rely on this crate for argument parsing, and it's currently stopping me from updating `rpg-cli`.

### Steps To Reproduce
1. `nix shell nixpkgs#cargo nixpkgs#gcc`
2. `git clone https://github.com/clap-rs/clap && cd clap`
3. `cargo build`

### Expected behavior
It should compile.

### Screenshots
```
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

### Additional context
https://github.com/rust-lang/rust/issues/78835

### Notify maintainers
Maintainers seem to be: @madjar @cstrahan @globin and @Havvy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13-xanmod1-cacule, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `""`
 - channels(nix): `""`
 - nixpkgs: `/nix/store/lmaa13qwmmam5npnfmkn78pfk9akzxf8-wm91hzc8akq56pcygclif1131sh3l1al-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: rustc
# a list of nixos modules affected by the problem
module:
```

**Comment by figsoda** [comment]
it is stuck in staging, https://github.com/NixOS/nixpkgs/pull/132031 was merged a month ago
