### ISSUE TITLE
kodiPlain.aarch64-linux failing to build on aarch64 on master and release-18.09

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#57733]
kodiPlain.aarch64-linux is failing to build on master and release-18.09. This is a problem because new users trying NixOS on their Raspberry Pis won't be able to install Kodi.

**Comment by tomfitzhenry** [comment]
https://hydra.nixos.org/build/89032524 was the first failing build on release-18.09. The changes since the last successful build are all JDK/JRE related: https://paste.debian.net/1073300/

[kodiPlain's build error](https://hydra.nixos.org/build/89032524/nixlog/1) suggests a problem with Freetype:

    build/video/video.a(Teletext.cpp.o):Teletext.cpp:function CTeletextDecoder::EndDecoder(): error: undefined reference to 'FTC_Manager_Done'
    build/video/video.a(Teletext.cpp.o):Teletext.cpp:function CTeletextDecoder::RenderCharIntern(TextRenderInfo_t*, int, TextPageAttr_t*, int, int): error: undefined reference to 'FTC_SBitCache_Lookup'

and I see that from that log file that cmake has managed to grab freetype from the JRE (unexpected!):

    -- Found FreeType: /nix/store/3vslpb5ksghr02vb58vvpv2c3hv1ig32-adoptopenjdk-jre-hotspot-bin-11.0.2/lib/libfreetype.so (found version "22.0.16") 

Compare that to [kodiPlain's last successful build log](https://hydra.nixos.org/build/88979570/log), in which cmake found freetype from freetype (as expected):

    -- Found FreeType: /nix/store/p14jcjs9ij0jfd9pgyq7gxpdl8k1kgj1-freetype-2.9/lib/libfreetype.so (found version "22.0.16")

**Comment by tomfitzhenry** [comment]
OpenJDK 11.0.1 did not contain libfreetype, but OpenJDK 11.0.2 does contain libfreetype:

    $ for i in *.tar.gz; do echo $i; tar tf $i | grep -i freetype; done
    OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.1_13.tar.gz
    OpenJDK11U-jre_aarch64_linux_hotspot_11.0.2_7.tar.gz
    jdk-11.0.2+7-jre/lib/libfreetype.so
    jdk-11.0.2+7-jre/legal/java.desktop/freetype.md
    OpenJDK11U-jre_x64_linux_hotspot_11.0.2_9.tar.gz
    jdk-11.0.2+9-jre/legal/java.desktop/freetype.md
    jdk-11.0.2+9-jre/lib/libfreetype.so

... so of the two aforementioned changes ( https://paste.debian.net/1073300/ ), the upgrade to 11.0.2 likely triggered this: commit ef02c63ba159b1e7d65db192e4078a951d107107 .

**Comment by tomfitzhenry** [comment]
https://github.com/NixOS/nixpkgs/pull/57750 has been merged to master, and now kodiPlain.aarch64-linux is building ( https://i.imgur.com/l8v9d7k.png ). Woo!

```
-- Found FreeType: /nix/store/ys7dzg01swqh04bw8786s17hr1lw08zf-freetype-2.9.1/lib/libfreetype.so (found version "22.1.16")
```

Let's get this in 18.09 and 19.03

**Comment by flokli** [comment]
With https://github.com/NixOS/nixpkgs/pull/58411 and https://github.com/NixOS/nixpkgs/pull/58412 being merged, this can be closed :-)
