### PR TITLE
Emacs macport version fix

### LINKED ISSUE #20682: emacs25Macport cannot use AppKit
## Issue description

It looks like emacs is not able to use Appkit for some reason. Here is the relevant logs:

```
checking AppKit/AppKit.h usability... no
checking AppKit/AppKit.h presence... yes
configure: WARNING: AppKit/AppKit.h: present but cannot be compiled
configure: WARNING: AppKit/AppKit.h:     check for missing prerequisite headers?
configure: WARNING: AppKit/AppKit.h: see the Autoconf documentation
configure: WARNING: AppKit/AppKit.h:     section "Present But Cannot Be Compiled"
configure: WARNING: AppKit/AppKit.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to bug-gnu-emacs@gnu.org ##
configure: WARNING:     ## ------------------------------------ ##
checking for AppKit/AppKit.h... no
configure: error: The include files (AppKit/AppKit.h etc) that
are required for a Nextstep build are missing or cannot be compiled.
```

```
$ nix-shell --pure --run "echo '#import <AppKit/AppKit.h>' | cc -x objective-c-header -" -p stdenv.cc darwin.apple_sdk.frameworks.AppKit
In file included from <stdin>:1:
In file included from /nix/store/6zrda57fmgvn9yjpqfv0lm97vabma0f5-apple-framework-AppKit/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:
In file included from /nix/store/7f0bbz6lclkbmgr44n74kqkwq37p4dq5-apple-framework-Foundation/Library/Frameworks/Foundation.framework/Headers/Foundation.h:141:
In file included from /nix/store/7f0bbz6lclkbmgr44n74kqkwq37p4dq5-apple-framework-Foundation/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:7:
In file included from /nix/store/2qbqqy62d750c2gcq2pp94skqwapdg9n-apple-framework-ApplicationServices/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
In file included from /nix/store/y5v7lnz3fiksjha0bij50zdbalvykqmc-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CoreText.h:27:
In file included from /nix/store/y5v7lnz3fiksjha0bij50zdbalvykqmc-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:22:
In file included from /nix/store/y5v7lnz3fiksjha0bij50zdbalvykqmc-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:21:
/nix/store/y5v7lnz3fiksjha0bij50zdbalvykqmc-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CTLine.h:22:10: fatal error: 'CoreFoundation/CFAttributedString.h' file not found
#include <CoreFoundation/CFAttributedString.h>
         ^
1 error generated.
```

It looks like Foundation framework is busted. This is lowPrio so I don't think there is Hydra logs.

nixpkgs commit: b69f568
nix version: 1.11.4

cc @copumpkin

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This sets MAC_OS_X_VERSION_MIN_REQUIRED=1090 to get the emacs25macport working again. This should also be needed for emacs24macport.

Also: update to emacs-mac 6.1.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Previously emacs-macport was giving the error:

- AppKit/AppKit.h: present but cannot be compiled
- Carbon/Carbon.h: present but cannot be compiled

This adds "MAC_OS_X_VERSION_MIN_REQUIRED=1090" to CFLAGS to allow them
to compile with the new 10.10 headers.

Fixes #20682.

### CODE REVIEW

**Comment by acowley** [comment]
Unless I'm misreading, `-DMAC_OS_X_VERSION_MAX_ALLOWED=1090` is still there despite what the log message says.

That said, the change does get past the referenced error.

**Comment by matthewbauer** [comment]
Sorry about that. I had that commit originally but it got overwritten.

**Comment by acowley** [comment]
To be clear, the change here seems to work for me, but I want to make sure it is the entire intended change since the diagnosed problem is that we have 10.10 headers, but the expression still includes the `-DMAC_OS_X_VERSION_MAX_ALLOWED=1090` flag.

It looks like that flag isn't hurting anything at the moment, so I'm fine with merging, but maybe we should bump it just on principle?

**Comment by matthewbauer** [comment]
@acowley The reason we need it is because of some 10.9 specific things that emacs-mac is using. You can try compiling ```src/macappkit.m``` without the defines to see what I mean. It should be completely harmless.

**Comment by matthewbauer** [comment]
Would it be okay to get rid of the "lowPrio" for these two derivations?

**Comment by acowley** [comment]
I hope this can be merged soon. I had a frustrating time bringing a computer up to date today because the `emacs25Macport` hydra serves up doesn't have a working `.app`. Things seem to build fine, but what you end up with is broken. These commits are crucial to un-frustrating things!

**Comment by matthewbauer** [comment]
@acowley AFAICT, emacs25Macport isn't in Hydra (lowPrio). Could you be looking at the regular "emacs" (which also provides a .app)?

**Comment by acowley** [comment]
Hm, the path in the store definitely said mac, and it was during an update from 24 that I hit this, and the result definitely did not have an .app.

**Comment by LnL7** [comment]
looks like like emacs24 is still broken, this also does not build on sierra https://gist.github.com/LnL7/dda8973b7deac7cbe0ee9d30505d54d6

**Comment by LnL7** [comment]
let me check if it's just during the build.

**Comment by LnL7** [comment]
The resulting build seems to work. What's the reason we also have a build for emacs24, is that important?

**Comment by acowley** [comment]
If 25 works and 24 doesn't, we should split the PR. I do think 24 matters, but some emacs is better than no emacs!

File: pkgs/applications/editors/emacs/macport-25.1.nix [hunk 1]
```diff
@@ -48,7 +48,7 @@ stdenv.mkDerivation rec {
     "--enable-mac-app=$$out/Applications"
   ];
 
-  CFLAGS = "-O3 -DMAC_OS_X_VERSION_MAX_ALLOWED=1090";
+  CFLAGS = "-O3 -DMAC_OS_X_VERSION_MAX_ALLOWED=1090 -DMAC_OS_X_VERSION_MIN_REQUIRED=1090";
```
Comment (LnL7) [inline pkgs/applications/editors/emacs/macport-25.1.nix]: This looks a little strange, do we need both?

Comment (matthewbauer) [inline pkgs/applications/editors/emacs/macport-25.1.nix]: Well we can't have MAC_OS_X_VERSION_MAX_ALLOWED without MAC_OS_X_VERSION_MIN_REQUIRED because max allowed can't be less than min required. Why MAC_OS_X_VERSION_MAX_ALLOWED is necessary is unclear but it seems to fail without it.

Comment (matthewbauer) [inline pkgs/applications/editors/emacs/macport-25.1.nix]: I would say to just merge this now. If you can merge #20536 after this, it should fix emacs24Macport as well

**Comment by matthewbauer** [comment]
> If 25 works and 24 doesn't, we should split the PR. I do think 24 matters, but some emacs is better than no emacs!

Well this change is definitely needed for 24 even though other things are broken. #20536 seems to fix 24.
