### PR TITLE
gitAndTools.gitui: 0.5.0 -> 0.7.0

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/jakubroztocil/httpie/releases/tag/2.2.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
> https://github.com/jakubroztocil/httpie/releases/tag/2.2.0

This might a case of copy/paste gone bad.

Unfortunately this does not seem to build for me:

```
   Compiling gitui v0.7.0 (/build/source)
error[E0723]: heap allocations are not allowed in const fn
   --> src/components/help.rs:163:19
    |
163 |             cmds: vec![],
    |                   ^^^^^^
    |
    = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
    = help: add `#![feature(const_fn)]` to the crate attributes to enable
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0723`.
error: could not compile `gitui`.

To learn more, run the command again with --verbose.
builder for '/nix/store/aq60gpp2zbipd5fq2ijbvrz4c9qqff7s-gitui-0.7.0.drv' failed with exit code 101
```

**Comment by Ma27** [comment]
The change doesn't compile for me on `x86_64-linux`:

```
gitui>    Compiling gitui v0.7.0 (/build/source)
gitui> error[E0723]: heap allocations are not allowed in const fn
gitui>    --> src/components/help.rs:163:19
gitui>     |
gitui> 163 |             cmds: vec![],
gitui>     |                   ^^^^^^
gitui>     |
gitui>     = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
gitui>     = help: add `#![feature(const_fn)]` to the crate attributes to enable
gitui>     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
gitui> error: aborting due to previous error
gitui> For more information about this error, try `rustc --explain E0723`.
gitui> error: could not compile `gitui`.
gitui> To learn more, run the command again with --verbose.
builder for '/nix/store/aq60gpp2zbipd5fq2ijbvrz4c9qqff7s-gitui-0.7.0.drv' failed with exit code 101
[1 built (1 failed)]
error: build of '/nix/store/aq60gpp2zbipd5fq2ijbvrz4c9qqff7s-gitui-0.7.0.drv' failed

```

**Comment by marsam** [comment]
I guess it depends on https://github.com/NixOS/nixpkgs/pull/89576
IIUC you could still build with rustc 1.43.0:
```diff
--- i/pkgs/applications/version-management/git-and-tools/gitui/default.nix
+++ w/pkgs/applications/version-management/git-and-tools/gitui/default.nix
@@ -15,6 +15,11 @@ rustPlatform.buildRustPackage rec {
 
   buildInputs = stdenv.lib.optionals stdenv.isDarwin [ libiconv Security ];
 
+  postPatch = ''
+    substituteInPlace src/components/help.rs \
+      --replace "cmds: vec![]" "cmds: Vec::new()"
+  '';
+
   meta = with stdenv.lib; {
     description = "Blazing fast terminal-ui for git written in rust";
     homepage = "https://github.com/extrawurst/gitui";
```

**Comment by bhipple** [comment]
@GrahamcOfBorg build gitAndTools.gitui

**Comment by marsam** [comment]
superseded by https://github.com/NixOS/nixpkgs/pull/93313/
