### ISSUE TITLE
libplacebo-2.72.2 fails to build due to glslang / path issue

### ISSUE THREAD

**Issue by jboyens** [NixOS/nixpkgs#108723]
**Describe the bug**
libplacebo-2.72.2 fails to build due to missing glslang header file

**To Reproduce**
1. Check out rev `f6f4e1f7be19dab2700385fe7b4f3d20a95a55bd`
2. Attempt to build libplacebo (dep. of mpv / mpv-with-scripts)
3. Recieve the below error message

```
builder for '/nix/store/169s5i8v24bmi25dpg7wkd2v3yxdkdcn-libplacebo-2.72.2.drv' failed with exit code 1; last 10 log lines:
  build flags: -j12 -l12
  [23/44] Compiling C++ object src/libplacebo.so.72.p/glsl_glslang.cc.ols_gen.c.o
  FAILED: src/libplacebo.so.72.p/glsl_glslang.cc.o
  g++ -Isrc/libplacebo.so.72.p -Isrc -I../src -I../src/include -I../src/include/dummy -I../subprojects/xtalloc/include -I../subprojects/bstr/include -I/nix/store/zdw72aaz9zf2q4rqg3qdrha320mnddz5-lcms2-2.11-dev/include -I/nix/store/n3d8q3h7qdmx2zy2yxwn8zxjx6l9rsh0-vulkan-loader-1.2.162.0-dev/include -I/nix/store/azwvk8yg6n4pwjbhfgajfywrmj4vhx8f-epoxy-1.5.4-dev/include -I/usr/include/glslang -I/nix/store/50fq4bhc10fxsy5h47d908rr0yi1yyz5-libplacebo-2.72.2/include/glslang -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++11 -Wundef -Wshadow -Wparentheses -Wpointer-arith -fvisibility=hidden -fPIC -pthread -MD -MQ src/libplacebo.so.72.p/glsl_glslang.cc.o -MF src/libplacebo.so.72.p/glsl_glslang.cc.o.d -o src/libplacebo.so.72.p/glsl_glslang.cc.o -c ../src/glsl/glslang.cc
  ../src/glsl/glslang.cc:29:10: fatal error: SPIRV/GlslangToSpv.h: No such file or directory
     29 | #include <SPIRV/GlslangToSpv.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  [34/44] Compiling C object src/libplacebo.so.72.p/vulkan_context.c.o[K
  ninja: build stopped: subcommand failed.
```

**Notify maintainers**
@primeos @tadeokondrak 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.4, NixOS, 21.03.20210104.4a55ebe (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - nixpkgs: `/nix/store/j0mfic9x0i9pyhdixag6885wigky0dzx-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module:
```

**Comment by primeos** [comment]
Thanks for the report!
This is a regression from 31bd59648f93f511429585f4345bd073137fdcbd. Seems like `glslang` broke something [again](https://github.com/KhronosGroup/glslang/issues/1959)... :o I didn't find any existing upstream issues/patches so far.

**Comment by baloo** [comment]
Because glslang bumped from 8.13 to 11.1, so the include path changes from:
```
/nix/store/jg092gfgx0qw7j17wg8m6dd0qyknrvhd-glslang-8.13.3743/include/SPIRV
```
to:
```
/nix/store/cf1xbgkmqm19888pcvk8l1bmg1m18vlw-glslang-11.1.0/include/glslang/SPIRV
```

Note: glslang/SPIRV includes also works on 8.13:
```
/nix/store/jg092gfgx0qw7j17wg8m6dd0qyknrvhd-glslang-8.13.3743/include/glslang/SPIRV
```

**Comment by primeos** [comment]
@baloo thanks, I missed that change (only checked that the file didn't move in the source repo :o).

~~If someone is interested and has time: Feel free to submit a PR. It's getting late here and I cannot handle it before tomorrow.~~ (I wrote this while the notification came :D)
