### ISSUE TITLE
lyx-2.3.0 broken by qt update

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#42124]
`lyx` no longer compiles after b785d4813e5d0f428b9563b3cea7cc6953fc24db (https://github.com/NixOS/nixpkgs/pull/41095).

~~~
GuiDocument.cpp:1246:17: error: invalid use of incomplete type 'class QButtonGroup'
   packageGroup->addButton(neverRB);
                 ^~~~~~~~~
In file included from /nix/store/adva1h8g45c67ljjanpbzl1i835fwpg5-qtbase-5.11.0-dev/include/QtWidgets/qcheckbox.h:44:0,
                 from /nix/store/adva1h8g45c67ljjanpbzl1i835fwpg5-qtbase-5.11.0-dev/include/QtWidgets/QCheckBox:1,
                 from ui_BulletsUi.h:14,
                 from BulletsModule.h:15,
                 from GuiDocument.h:17,
                 from GuiDocument.cpp:14:
/nix/store/adva1h8g45c67ljjanpbzl1i835fwpg5-qtbase-5.11.0-dev/include/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
  CXX      GuiFontExample.o
  CXX      GuiFontLoader.o
make[6]: *** [Makefile:1009: GuiDocument.o] Error 1
~~~

**Comment by yegortimoshenko** [comment]
Would be fixed by a patch similar to https://git.archlinux.org/svntogit/community.git/plain/trunk/010-qt-5.11.patch?h=packages/virtualbox.

**Comment by bkchr** [comment]
I'm already on it, pr will follow in some minutes :)
