### PR TITLE
gnutls-kdh: fix build

### LINKED ISSUE #72123: gnutls-kdh-1.0.drv doesn't build
**Describe the bug**

See the [attached log](https://github.com/NixOS/nixpkgs/files/3776432/build.log); the relevant issue seems to be here:

```text
aes-padlock.c:96:29: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                             ^~~~
                             key_size
aes-padlock.c:96:45: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                                             ^~~~
                                             key_size
aes-padlock.c:97:22: error: 'struct aes_ctx' has no member named 'rounds'
   pce->ks.rounds = nc.rounds;
                      ^
```

Most of [my configuration](https://gitlab.com/victor-engmark/root/blob/b586ec1cf0606b9c558061b81020fde0b44533d2/configuration.nix) is online verbatim.

**To Reproduce**
1. `sudo nixos-rebuild switch --upgrade`

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.78, NixOS, 20.03pre196725.94500c93dc2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre198214.4cd2cb43fb3"`
 - channels(username): `"nixpkgs-20.03pre193309.c4196cca9ac"`
 - nixpkgs: `/home/username/.nix-defexpr/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes #72123

gnutls-kdh doesn't build with nettle 3.5.1, this pretty much reverts the bump for gnutls-kdh only

also fixes lutris build

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
also made an upstream issue https://github.com/arpa2/gnutls-kdh/issues/2 but the last commit was 3 years ago

**Comment by c0bw3b** [comment]
Indeed, I'm not sure it's worth maintaining an old `nettle` if upstream is never going to update.

About `lutris` : the Dolphin emulator already depends on `mbedtls` and I don't why it would need this old gnutls fork. @abbradar and @Chiiruno may provide some insight here

**Comment by jonringer** [comment]
I'm almost more than okay removing gnutls-kdh from lutris

**Comment by jonringer** [comment]
closing in favor of #72280
