### PR TITLE
tensorflow: 1.15.2 -> 1.15.3 

### PR DESCRIPTION
**Pull request by avdv**
#### Motivation for this change

tensorflow 1.15.3 was released.

~The first commit fixes the build for opt-einsum (see PR #93107), but I also wanted to check whether tensorflow builds.~

Actually, my main motivation for this is that I want to upgrade bazel to 3.4.1, but they removed the `--incompatible_disable_deprecated_attr_params` command line flag, which is used by dm-sonnet. So I tried to upgrade dm-sonnet, hoping that they would not need this flag anymore. But that did not work because it depends on tensorflow and tensorflow did not build because of the broken test in opt-einsum.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/development/python-modules/opt-einsum/test-value_error.diff [hunk 1]
```diff
@@ -0,0 +1,13 @@
+diff --git a/opt_einsum/tests/test_input.py b/opt_einsum/tests/test_input.py
+index e5c1677..54ea059 100644
+--- a/opt_einsum/tests/test_input.py
++++ b/opt_einsum/tests/test_input.py
+@@ -34,7 +34,7 @@ def test_type_errors():
+         contract("", 0, out='test')
+ 
+     # order parameter must be a valid order
+-    with pytest.raises(TypeError):
++    with pytest.raises(ValueError):
```
Comment (jonringer) [inline pkgs/development/python-modules/opt-einsum/test-value_error.diff:10]: I don't feel like this is a nixpkgs-specific issue, is there a way to upstream it?

Comment (avdv) [reply pkgs/development/python-modules/opt-einsum/test-value_error.diff:10]: I have created an issue upstream: https://github.com/dgasmith/opt_einsum/issues/147

**Comment by ajs124** [comment]
Tensorflow doesn't seem to build for me with python 3.7 or 3.6, did it build for you when you opened this PR?

**Comment by jonringer** [comment]
seems to fail with:
```
tensorflow/python/lib/core/bfloat16.cc:607:25: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction' {aka 'void (*)(char**, const long int*, const long int*, void*)'}
tensorflow/python/lib/core/bfloat16.cc:645:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [8], <unresolved overloaded function type>, const std>
  645 |                       compare_types)) {
```
With how often tensorflow_1 breaks. It's largely amazing to me that it ever builds.

**Comment by matthewbauer** [comment]
I'm skeptical you can get tensorflow 1.15 to work with anything but bazel 0.26 - see https://github.com/tensorflow/tensorflow/blob/v1.15.3/configure.py#L52-L53.

Is tensorflow 1 still being actively used in the community? I was hoping we could fix tensorflow 2 derivations, then remove the tensorflow 1 stuff.

**Comment by jonringer** [comment]
looks like the older bazel packages were restored, it should be able to call bazel with the older versions.

**Comment by CMCDragonkai** [comment]
We are still using TF 1.x. Please keep it around, I hope to find a revision that works.

**Comment by ajs124** [comment]
> Is tensorflow 1 still being actively used in the community?

There are still projects that haven't migrated, e.g. https://github.com/photoprism/photoprism/issues/222

**Comment by avdv** [comment]
> Tensorflow doesn't seem to build for me with python 3.7 or 3.6, did it build for you when you opened this PR?

I started this PR before leaving for vacation and I just got back. I can't really remember, but I think it did not finish successfully.

> I'm skeptical you can get tensorflow 1.15 to work with anything but bazel 0.26 - see [tensorflow/tensorflow:configure.py@`v1.15.3`#L52-L53](https://github.com/tensorflow/tensorflow/blob/v1.15.3/configure.py?rgh-link-date=2020-08-20T01%3A15%3A28Z#L52-L53).

I am not trying to build tensorflow with an updated bazel version, it's just that dm-sonnet is build with bazel 3 and tensorflow needs to be build as a dependency. I don't fully understand why. :thinking:

**Comment by avdv** [comment]
> seems to fail with:
> 
> ```
> tensorflow/python/lib/core/bfloat16.cc:607:25: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction' {aka 'void (*)(char**, const long int*, const long int*, void*)'}
> tensorflow/python/lib/core/bfloat16.cc:645:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [8], <unresolved overloaded function type>, const std>
>   645 |                       compare_types)) {
> ```
> 
> With how often tensorflow_1 breaks. It's largely amazing to me that it ever builds.

Apparently, this is caused by an ABI change of numpy 1.19.0 - see https://github.com/tensorflow/tensorflow/issues/40688

**Comment by avdv** [comment]
This PR should unblocked by #98083

**Comment by avdv** [comment]
Since #98083 has been merged, this is ready to review.

**Comment by avdv** [comment]
Tensorflow is already at 1.15.4
