### PR TITLE
linux_zen: 5.18.0-zen1 -> 5.18.1-zen1, disable WERROR

### LINKED ISSUE #175879: linuxPackages_zen.kernel: fails to build since update to 5.18.0-zen1
The Zen kernel is failing to build for me since the update to 5.18, and so I thought I'd open an issue since I can't seem to find any existing info about it.

**Bisected to https://github.com/NixOS/nixpkgs/commit/208fd4f17325cf506eea151e3614ae2081fa8b6c.**

### Steps To Reproduce

```sh
$ nix build github:NixOS/nixpkgs/208fd4f17325cf506eea151e3614ae2081fa8b6c#linuxPackages_zen.kernel -L
```

### Build Log

```
../drivers/i2c/busses/i2c-nct6775.c: In function 'nct6775_access':
../drivers/i2c/busses/i2c-nct6775.c:221:39: error: this statement may fall through [-Werror=implicit-fallthrough=]
  221 |                         tmp_data.byte = data->byte;
      |                         ~~~~~~~~~~~~~~^~~~~~~~~~~~
../drivers/i2c/busses/i2c-nct6775.c:222:17: note: here
  222 |                 case I2C_SMBUS_BYTE:
      |                 ^~~~
cc1: all warnings being treated as errors
make[3]: *** [../scripts/Makefile.build:288: drivers/i2c/busses/i2c-nct6775.o] Error 1
make[2]: *** [../scripts/Makefile.build:550: drivers/i2c/busses] Error 2
make[1]: *** [../scripts/Makefile.build:550: drivers/i2c] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### Notify maintainers

@Atemu @andresilva 

### Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 5.17.7-zen1, NixOS, 22.05 (Quokka), 22.05.20220518.48037fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `""`
 - channels(alex): `""`
 - nixpkgs: `/run/current-system/nixpkgs`

### PR DESCRIPTION
**Pull request by InternetUnexplorer**
###### Description of changes

This updates the ZEN kernel to 5.18.1-zen1, [released on 2022-05-30](https://github.com/zen-kernel/zen-kernel/releases/tag/v5.18.1-zen1).

This also disables WERROR, which is necessary until #175433 reaches master (which disables it for all kernels).

Closes #175879.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by InternetUnexplorer** [comment]
The original intent was just to disable WERROR, but I figured I'd bump the version while I was at it since there was a new release available. In hindsight, I'm not sure if the version bump should wait for the mainline kernel to be updated to 5.18.1 first, if that's the case just let me know and I can change it back :).

**Comment by InternetUnexplorer** [comment]
<details>
<summary>Output of nixpkgs-review rev HEAD</summary>

```
35 packages marked as broken and skipped:
linuxKernel.packages.linux_zen.akvcam linuxKernel.packages.linux_zen.bbswitch linuxKernel.packages.linux_zen.dddvb linuxKernel.packages.linux_zen.dpdk linuxKernel.packages.linux_zen.dpdk-kmods linuxKernel.packages.linux_zen.ena linuxKernel.packages.linux_zen.facetimehd linuxKernel.packages.linux_zen.intel-speed-select linuxKernel.packages.linux_zen.ixgbevf linuxKernel.packages.linux_zen.kvdo linuxKernel.packages.linux_zen.lttng-modules linuxKernel.packages.linux_zen.mxu11x0 linuxKernel.packages.linux_zen.ndiswrapper linuxKernel.packages.linux_zen.nvidia_x11_legacy340 linuxKernel.packages.linux_zen.nvidiabl linuxKernel.packages.linux_zen.openafs linuxKernel.packages.linux_zen.openafs_1_9 linuxKernel.packages.linux_zen.phc-intel linuxKernel.packages.linux_zen.r8125 linuxKernel.packages.linux_zen.r8168 linuxKernel.packages.linux_zen.rtl8188eus-aircrack linuxKernel.packages.linux_zen.rtl8189es linuxKernel.packages.linux_zen.rtl8192eu linuxKernel.packages.linux_zen.rtl8723bs linuxKernel.packages.linux_zen.rtl8812au linuxKernel.packages.linux_zen.rtl8821ce linuxKernel.packages.linux_zen.rtl88xxau-aircrack linuxKernel.packages.linux_zen.sch_cake linuxKernel.packages.linux_zen.tbs linuxKernel.packages.linux_zen.virtualbox linuxKernel.packages.linux_zen.virtualboxGuestAdditions linuxKernel.packages.linux_zen.vmware linuxKernel.packages.linux_zen.xmm7360-pci linuxKernel.packages.linux_zen.zfs linuxKernel.packages.linux_zen.zfsUnstable

6 packages failed to build:
linuxKernel.packages.linux_zen.broadcom_sta linuxKernel.packages.linux_zen.evdi linuxKernel.packages.linux_zen.mwprocapture linuxKernel.packages.linux_zen.nvidia_x11_legacy390 linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta linuxKernel.packages.linux_zen.rtl8814au

57 packages built:
linuxKernel.kernels.linux_zen linuxKernel.packages.linux_zen.acpi_call linuxKernel.packages.linux_zen.apfs linuxKernel.packages.linux_zen.asus-ec-sensors linuxKernel.packages.linux_zen.asus-wmi-sensors linuxKernel.packages.linux_zen.batman_adv linuxKernel.packages.linux_zen.can-isotp linuxKernel.packages.linux_zen.chipsec linuxKernel.packages.linux_zen.cpupower linuxKernel.packages.linux_zen.cryptodev linuxKernel.packages.linux_zen.ddcci-driver linuxKernel.packages.linux_zen.digimend linuxKernel.packages.linux_zen.fwts-efi-runtime linuxKernel.packages.linux_zen.gcadapter-oc-kmod linuxKernel.packages.linux_zen.hid-nintendo linuxKernel.packages.linux_zen.hyperv-daemons linuxKernel.packages.linux_zen.isgx linuxKernel.packages.linux_zen.it87 linuxKernel.packages.linux_zen.jool linuxKernel.packages.linux_zen.kvmfr linuxKernel.packages.linux_zen.liquidtux linuxKernel.packages.linux_zen.mba6x_bl linuxKernel.packages.linux_zen.mbp2018-bridge-drv linuxKernel.packages.linux_zen.netatop linuxKernel.packages.linux_zen.new-lg4ff linuxKernel.packages.linux_zen.nvidia_x11 linuxKernel.packages.linux_zen.nvidia_x11_beta linuxKernel.packages.linux_zen.nvidia_x11_legacy470 linuxKernel.packages.linux_zen.openrazer linuxKernel.packages.linux_zen.perf linuxKernel.packages.linux_zen.ply linuxKernel.packages.linux_zen.rr-zen_workaround linuxKernel.packages.linux_zen.rtl8821au linuxKernel.packages.linux_zen.rtl8821cu linuxKernel.packages.linux_zen.rtl88x2bu linuxKernel.packages.linux_zen.rtlwifi_new linuxKernel.packages.linux_zen.sysdig linuxKernel.packages.linux_zen.system76 linuxKernel.packages.linux_zen.system76-acpi linuxKernel.packages.linux_zen.system76-io linuxKernel.packages.linux_zen.systemtap linuxKernel.packages.linux_zen.tmon linuxKernel.packages.linux_zen.tp_smapi linuxKernel.packages.linux_zen.turbostat linuxKernel.packages.linux_zen.tuxedo-keyboard linuxKernel.packages.linux_zen.usbip linuxKernel.packages.linux_zen.v4l2loopback linuxKernel.packages.linux_zen.v86d linuxKernel.packages.linux_zen.veikk-linux-driver linuxKernel.packages.linux_zen.vendor-reset linuxKernel.packages.linux_zen.vhba linuxKernel.packages.linux_zen.virtio_vmmci linuxKernel.packages.linux_zen.vmm_clock linuxKernel.packages.linux_zen.x86_energy_perf_policy linuxKernel.packages.linux_zen.xone linuxKernel.packages.linux_zen.xpadneo linuxKernel.packages.linux_zen.zenpower
```
</details>

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 176194` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>74 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_zen.akvcam</li>
    <li>linuxKernel.packages.linux_zen.bbswitch</li>
    <li>linuxKernel.packages.linux_zen.dddvb</li>
    <li>linuxKernel.packages.linux_zen.dpdk</li>
    <li>linuxKernel.packages.linux_zen.dpdk-kmods</li>
    <li>linuxKernel.packages.linux_zen.ena</li>
    <li>linuxKernel.packages.linux_zen.facetimehd</li>
    <li>linuxKernel.packages.linux_zen.intel-speed-select</li>
    <li>linuxKernel.packages.linux_zen.ixgbevf</li>
    <li>linuxKernel.packages.linux_zen.kvdo</li>
    <li>linuxKernel.packages.linux_zen.lttng-modules</li>
    <li>linuxKernel.packages.linux_zen.mxu11x0</li>
    <li>linuxKernel.packages.linux_zen.ndiswrapper</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_zen.nvidiabl</li>
    <li>linuxKernel.packages.linux_zen.openafs</li>
    <li>linuxKernel.packages.linux_zen.openafs_1_8</li>
    <li>linuxKernel.packages.linux_zen.openafs_1_9</li>
    <li>linuxKernel.packages.linux_zen.phc-intel</li>
    <li>linuxKernel.packages.linux_zen.r8125</li>
    <li>linuxKernel.packages.linux_zen.r8168</li>
    <li>linuxKernel.packages.linux_zen.rtl8188eus-aircrack</li>
    <li>linuxKernel.packages.linux_zen.rtl8189es</li>
    <li>linuxKernel.packages.linux_zen.rtl8192eu</li>
    <li>linuxKernel.packages.linux_zen.rtl8723bs</li>
    <li>linuxKernel.packages.linux_zen.rtl8812au</li>
    <li>linuxKernel.packages.linux_zen.rtl8821ce</li>
    <li>linuxKernel.packages.linux_zen.rtl88xxau-aircrack</li>
    <li>linuxKernel.packages.linux_zen.sch_cake</li>
    <li>linuxKernel.packages.linux_zen.tbs</li>
    <li>linuxKernel.packages.linux_zen.virtualbox</li>
    <li>linuxKernel.packages.linux_zen.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_zen.vmware</li>
    <li>linuxKernel.packages.linux_zen.xmm7360-pci</li>
    <li>linuxKernel.packages.linux_zen.zfs</li>
    <li>linuxKernel.packages.linux_zen.zfsStable</li>
    <li>linuxKernel.packages.linux_zen.zfsUnstable</li>
    <li>linuxPackages_zen.akvcam</li>
    <li>linuxPackages_zen.bbswitch</li>
    <li>linuxPackages_zen.dddvb</li>
    <li>linuxPackages_zen.dpdk</li>
    <li>linuxPackages_zen.dpdk-kmods</li>
    <li>linuxPackages_zen.ena</li>
    <li>linuxPackages_zen.facetimehd</li>
    <li>linuxPackages_zen.intel-speed-select</li>
    <li>linuxPackages_zen.ixgbevf</li>
    <li>linuxPackages_zen.kvdo</li>
    <li>linuxPackages_zen.lttng-modules</li>
    <li>linuxPackages_zen.mxu11x0</li>
    <li>linuxPackages_zen.ndiswrapper</li>
    <li>linuxPackages_zen.nvidia_x11_legacy340</li>
    <li>linuxPackages_zen.nvidiabl</li>
    <li>linuxPackages_zen.openafs</li>
    <li>linuxPackages_zen.openafs_1_8</li>
    <li>linuxPackages_zen.openafs_1_9</li>
    <li>linuxPackages_zen.phc-intel</li>
    <li>linuxPackages_zen.r8125</li>
    <li>linuxPackages_zen.r8168</li>
    <li>linuxPackages_zen.rtl8188eus-aircrack</li>
    <li>linuxPackages_zen.rtl8189es</li>
    <li>linuxPackages_zen.rtl8192eu</li>
    <li>linuxPackages_zen.rtl8723bs</li>
    <li>linuxPackages_zen.rtl8812au</li>
    <li>linuxPackages_zen.rtl8821ce</li>
    <li>linuxPackages_zen.rtl88xxau-aircrack</li>
    <li>linuxPackages_zen.sch_cake</li>
    <li>linuxPackages_zen.tbs</li>
    <li>linuxPackages_zen.virtualbox</li>
    <li>linuxPackages_zen.virtualboxGuestAdditions</li>
    <li>linuxPackages_zen.vmware</li>
    <li>linuxPackages_zen.xmm7360-pci</li>
    <li>linuxPackages_zen.zfs</li>
    <li>linuxPackages_zen.zfsStable</li>
    <li>linuxPackages_zen.zfsUnstable</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_zen.broadcom_sta (linuxKernel.packages.linux_zen.broadcom_sta)</li>
    <li>linuxPackages_zen.evdi (linuxKernel.packages.linux_zen.evdi)</li>
    <li>linuxPackages_zen.mwprocapture (linuxKernel.packages.linux_zen.mwprocapture)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390 (linuxKernel.packages.linux_zen.nvidia_x11_legacy390)</li>
    <li>linuxPackages_zen.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_zen.rtl8814au (linuxKernel.packages.linux_zen.rtl8814au)</li>
  </ul>
</details>
<details>
  <summary>57 packages built:</summary>
  <ul>
    <li>linuxPackages_zen.kernel (linuxKernel.kernels.linux_zen)</li>
    <li>linuxPackages_zen.acpi_call (linuxKernel.packages.linux_zen.acpi_call)</li>
    <li>linuxPackages_zen.apfs (linuxKernel.packages.linux_zen.apfs)</li>
    <li>linuxPackages_zen.asus-ec-sensors (linuxKernel.packages.linux_zen.asus-ec-sensors)</li>
    <li>linuxPackages_zen.asus-wmi-sensors (linuxKernel.packages.linux_zen.asus-wmi-sensors)</li>
    <li>linuxPackages_zen.batman_adv (linuxKernel.packages.linux_zen.batman_adv)</li>
    <li>linuxPackages_zen.can-isotp (linuxKernel.packages.linux_zen.can-isotp)</li>
    <li>linuxPackages_zen.chipsec (linuxKernel.packages.linux_zen.chipsec)</li>
    <li>linuxPackages_zen.cpupower (linuxKernel.packages.linux_zen.cpupower)</li>
    <li>linuxPackages_zen.cryptodev (linuxKernel.packages.linux_zen.cryptodev)</li>
    <li>linuxPackages_zen.ddcci-driver (linuxKernel.packages.linux_zen.ddcci-driver)</li>
    <li>linuxPackages_zen.digimend (linuxKernel.packages.linux_zen.digimend)</li>
    <li>linuxPackages_zen.fwts-efi-runtime (linuxKernel.packages.linux_zen.fwts-efi-runtime)</li>
    <li>linuxPackages_zen.gcadapter-oc-kmod (linuxKernel.packages.linux_zen.gcadapter-oc-kmod)</li>
    <li>linuxPackages_zen.hid-nintendo (linuxKernel.packages.linux_zen.hid-nintendo)</li>
    <li>linuxPackages_zen.hyperv-daemons (linuxKernel.packages.linux_zen.hyperv-daemons)</li>
    <li>linuxPackages_zen.isgx (linuxKernel.packages.linux_zen.isgx)</li>
    <li>linuxPackages_zen.it87 (linuxKernel.packages.linux_zen.it87)</li>
    <li>linuxPackages_zen.jool (linuxKernel.packages.linux_zen.jool)</li>
    <li>linuxPackages_zen.kvmfr (linuxKernel.packages.linux_zen.kvmfr)</li>
    <li>linuxPackages_zen.liquidtux (linuxKernel.packages.linux_zen.liquidtux)</li>
    <li>linuxPackages_zen.mba6x_bl (linuxKernel.packages.linux_zen.mba6x_bl)</li>
    <li>linuxPackages_zen.mbp2018-bridge-drv (linuxKernel.packages.linux_zen.mbp2018-bridge-drv)</li>
    <li>linuxPackages_zen.netatop (linuxKernel.packages.linux_zen.netatop)</li>
    <li>linuxPackages_zen.new-lg4ff (linuxKernel.packages.linux_zen.new-lg4ff)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11)</li>
    <li>linuxPackages_zen.nvidia_x11_beta (linuxKernel.packages.linux_zen.nvidia_x11_beta)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.openrazer (linuxKernel.packages.linux_zen.openrazer)</li>
    <li>linuxPackages_zen.perf (linuxKernel.packages.linux_zen.perf)</li>
    <li>linuxPackages_zen.ply (linuxKernel.packages.linux_zen.ply)</li>
    <li>linuxPackages_zen.rr-zen_workaround (linuxKernel.packages.linux_zen.rr-zen_workaround)</li>
    <li>linuxPackages_zen.rtl8821au (linuxKernel.packages.linux_zen.rtl8821au)</li>
    <li>linuxPackages_zen.rtl8821cu (linuxKernel.packages.linux_zen.rtl8821cu)</li>
    <li>linuxPackages_zen.rtl88x2bu (linuxKernel.packages.linux_zen.rtl88x2bu)</li>
    <li>linuxPackages_zen.rtw88 (linuxPackages_zen.rtlwifi_new)</li>
    <li>linuxPackages_zen.sysdig (linuxKernel.packages.linux_zen.sysdig)</li>
    <li>linuxPackages_zen.system76 (linuxKernel.packages.linux_zen.system76)</li>
    <li>linuxPackages_zen.system76-acpi (linuxKernel.packages.linux_zen.system76-acpi)</li>
    <li>linuxPackages_zen.system76-io (linuxKernel.packages.linux_zen.system76-io)</li>
    <li>linuxPackages_zen.systemtap (linuxKernel.packages.linux_zen.systemtap)</li>
    <li>linuxPackages_zen.tmon (linuxKernel.packages.linux_zen.tmon)</li>
    <li>linuxPackages_zen.tp_smapi (linuxKernel.packages.linux_zen.tp_smapi)</li>
    <li>linuxPackages_zen.turbostat (linuxKernel.packages.linux_zen.turbostat)</li>
    <li>linuxPackages_zen.tuxedo-keyboard (linuxKernel.packages.linux_zen.tuxedo-keyboard)</li>
    <li>linuxPackages_zen.usbip (linuxKernel.packages.linux_zen.usbip)</li>
    <li>linuxPackages_zen.v4l2loopback (linuxKernel.packages.linux_zen.v4l2loopback)</li>
    <li>linuxPackages_zen.v86d (linuxKernel.packages.linux_zen.v86d)</li>
    <li>linuxPackages_zen.veikk-linux-driver (linuxKernel.packages.linux_zen.veikk-linux-driver)</li>
    <li>linuxPackages_zen.vendor-reset (linuxKernel.packages.linux_zen.vendor-reset)</li>
    <li>linuxPackages_zen.vhba (linuxKernel.packages.linux_zen.vhba)</li>
    <li>linuxPackages_zen.virtio_vmmci (linuxKernel.packages.linux_zen.virtio_vmmci)</li>
    <li>linuxPackages_zen.vmm_clock (linuxKernel.packages.linux_zen.vmm_clock)</li>
    <li>linuxPackages_zen.x86_energy_perf_policy (linuxKernel.packages.linux_zen.x86_energy_perf_policy)</li>
    <li>linuxPackages_zen.xone (linuxKernel.packages.linux_zen.xone)</li>
    <li>linuxPackages_zen.xpadneo (linuxKernel.packages.linux_zen.xpadneo)</li>
    <li>linuxPackages_zen.zenpower (linuxKernel.packages.linux_zen.zenpower)</li>
  </ul>
</details>

**Review by trofi — APPROVED** [review]

**Review by Atemu — APPROVED** [review]
Can't test right now but diff LGTM.
