### PR TITLE
mongodb-6_0: add patch to fix broken build

### PR DESCRIPTION
**Pull request by f2k1de**
## Description of changes
fixes broken build on master for mongodb 6.0:

```
In file included from src/mongo/db/query/analyze_regex.cpp:34:
src/mongo/util/ctype.h:75:15: error: found ‘:’ in nested-name-specifier, expected ‘::’
   75 | enum ClassBit : uint16_t {
      |               ^
      |               ::
src/mongo/util/ctype.h:75:6: error: ‘ClassBit’ has not been declared
   75 | enum ClassBit : uint16_t {
      |      ^~~~~~~~
src/mongo/util/ctype.h:75:26: error: expected unqualified-id before ‘{’ token
   75 | enum ClassBit : uint16_t {
      |                          ^
src/mongo/util/ctype.h:91:11: error: ‘uint16_t’ does not name a type
   91 | constexpr uint16_t calculateClassBits(unsigned char c) {
      |           ^~~~~~~~
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/servers/nosql/mongodb/6.0.nix [hunk 1]
```diff
@@ -9,6 +9,7 @@ buildMongoDB {
   version = "6.0.13";
   sha256 = "sha256-BD3XrTdv4sCa3h37o1A2s3/R0R8zHiR59a4pY0RxLGU=";
   patches = [
+    ./fix-gcc-13-ctype-6_0.patch
```
Comment (drupol) [inline pkgs/servers/nosql/mongodb/6.0.nix:12]: Each patch in nixpkgs applied to the upstream source should be documented. Out-of-tree patches, fetched using `fetchpatch`, are preferred.

In each patch comment, please explain the purpose of the patch and link to the relevant upstream issue if possible. If the patch has been merged upstream but is not yet part of the released version, please note the version number or date in the comment such that a future maintainer updating the nix expression will know whether the patch has been incorporated upstream and can thus be removed from nixpkgs.

Furthermore, please use a _stable_ URL for the patch. Rather than, for example, linking to a GitHub pull request of the form `https://github.com/owner/repo/pull/pr_number.patch`, which would change every time a commit is added or the PR is force-pushed, link to a specific commit patch in the form `https://github.com/owner/repo/commit/sha.patch`.

Here are two good examples of patch comments:

```nix
mkDerivation {
  …

  patches = [
    # Ensure RStudio compiles against R 4.0.0.
    # Should be removed next 1.2.X RStudio update or possibly 1.3.X.
    (fetchpatch {
      url = "https://github.com/rstudio/rstudio/commit/3fb2397c2f208bb8ace0bbaf269481ccb96b5b20.patch";
      sha256 = "0qpgjy6aash0fc0xbns42cwpj3nsw49nkbzwyq8az01xwg81g0f3";
    })
  ];
}
```

```nix
mkDerivation {
  …

  patches = [
    # Allow building with bison 3.7
    # PR at https://github.com/GoldenCheetah/GoldenCheetah/pull/3590
    (fetchpatch {
      url = "https://github.com/GoldenCheetah/GoldenCheetah/commit/e1f42f8b3340eb4695ad73be764332e75b7bce90.patch";
      sha256 = "1h0y9vfji5jngqcpzxna5nnawxs77i1lrj44w8a72j0ah0sznivb";
    })
  ];
}
```

**Review by drupol — DISMISSED** [review]

File: pkgs/servers/nosql/mongodb/6.0.nix (hunk 1 above)
Comment (f2k1de) [reply pkgs/servers/nosql/mongodb/6.0.nix:12]: Have you had a look on any of the other patches in MongoDB?

Comment (drupol) [reply pkgs/servers/nosql/mongodb/6.0.nix:12]: Are you trying to tell me that the reason why you don't want to do it is because it was not done correctly somewhere else?

Comment (f2k1de) [reply pkgs/servers/nosql/mongodb/6.0.nix:14]: You can get an comment in the .nix that explains what the patch is doing. 
But I really dont get the point using an additional fetchpatch with an url to github (where then always an connection to github must be opened) instead of including it locally in the repo like all the other patched.
Reminder that mongo is not free software and has to be build every time instead of downloading it from cache.nixos.org.

This patch affects just the 6.0 version (since this commit https://github.com/NixOS/nixpkgs/commit/f29d66a77f6f5de17158037eef7e52b4f555ce77), hence it is included in the 6.0.nix file.

File: pkgs/servers/nosql/mongodb/6.0.nix [hunk 2]
```diff
@@ -9,6 +9,10 @@ buildMongoDB {
   version = "6.0.13";
   sha256 = "sha256-BD3XrTdv4sCa3h37o1A2s3/R0R8zHiR59a4pY0RxLGU=";
   patches = [
+    # Patches a bug that it couldn't build MongoDB 6.0 on gcc 13 because a include in ctype.h was missing
+    # PR at https://github.com/NixOS/nixpkgs/pull/293556
```
Comment (SuperSandro2000) [inline pkgs/servers/nosql/mongodb/6.0.nix:13]:
```suggestion
```
having a link that points to this PR is not that useful

File: pkgs/servers/nosql/mongodb/6.0.nix (hunk 1 above)
Comment (SuperSandro2000) [reply pkgs/servers/nosql/mongodb/6.0.nix:14]: I mean, is there an upstream commit we can fetch or not?

Comment (f2k1de) [reply pkgs/servers/nosql/mongodb/6.0.nix:14]: No there isn't. I built the patch based on an error message / suggestion that got thown while building the software.

File: pkgs/servers/nosql/mongodb/6.0.nix (hunk 2 above)
Comment (f2k1de) [reply pkgs/servers/nosql/mongodb/6.0.nix:13]: Then I don't get the point why @drupol was suggesting that?

Comment (drupol) [reply pkgs/servers/nosql/mongodb/6.0.nix:13]: Having a comment on top of a patch is often required when introducing a patch. I guess a link to the PR means that the patch should be removed at the next bump?

Comment (f2k1de) [reply pkgs/servers/nosql/mongodb/6.0.nix:13]: When we will package the next version 7.0 it will go into into a different file called 7.0.nix. This means that presumably this patch will be used for the 6.0 for so long as the 6.0 gets deprecated

Comment (SuperSandro2000) [reply pkgs/servers/nosql/mongodb/6.0.nix:13]: We want to link an *upstream* if possible. Linking this PR where we introduced it, is pointless here.

File: pkgs/servers/nosql/mongodb/6.0.nix (hunk 1 above)
Comment (SuperSandro2000) [reply pkgs/servers/nosql/mongodb/6.0.nix:14]: Then we can't fetchpatch something.

Comment (f2k1de) [reply pkgs/servers/nosql/mongodb/6.0.nix:14]: right. Thats why it is just the file in the repo next to the 6.0.nix

File: pkgs/servers/nosql/mongodb/6.0.nix (hunk 2 above)
Comment (f2k1de) [reply pkgs/servers/nosql/mongodb/6.0.nix:13]: There is no upstream patch. The patchfile is based on this terminal output when building the currently broken software on master.
grafik

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by friedow** [comment]
Thanks so much for fixing this! This bugged me for weeks and I couldn't fix it because of the long build/debug cycles on mongodb. Really, this made my day :heart:.
