### ISSUE TITLE
python2.7-powerline wants pygit2 0.23 which requires libgit2 0.23.x 

### ISSUE THREAD

**Issue by Azulinho** [NixOS/nixpkgs#15985]
## Issue description

python2.7-powerline won't build with error:

```
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/nix/store/89v0gq67zsy9vlrxm5ms89s5jf02ibhy-python-2.7.11/include/python2.7 -c src/treebuilder.c -o build/temp.linux-x86_64-2.7/src/treebuilder.o
In file included from src/utils.h:34:0,
                 from src/treebuilder.c:32:
src/types.h:36:2: error: #error You need a compatible libgit2 version (v0.23.x)
 #error You need a compatible libgit2 version (v0.23.x)
  ^
error: command 'gcc' failed with exit status 1
builder for ‘/nix/store/lzs99vnjr1haihbnbdgbl34fsswppd4w-python2.7-pygit2-0.23.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/84jr9k9c95b716q9zpjcnpry6sgblln9-python2.7-powerline-2.1.4.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/84jr9k9c95b716q9zpjcnpry6sgblln9-python2.7-powerline-2.1.4.drv’ failed
```

### Steps to reproduce

```
git clone https://github.com/NixOS/nixpkgs
cd nixpkgs
nix-env --show-trace -f $PWD -i python2.7-powerline
```

## Technical details
```
nixos-version
16.03.886.0068260 (Emu)

nix-env --version
nix-env (Nix) 1.11.2

nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.03.886.0068260"
```

**Comment by FRidh** [comment]
I just tested the build on 16.03 and it builds.
