### ISSUE TITLE
grpc fails to cross build on armv7

### ISSUE THREAD

**Issue by tusj** [NixOS/nixpkgs#198699]
### Steps To Reproduce
nix build nixpkgs#pkgsCross.armv7l-hf-multiplatform.grpc fails to build since 6aa094d7535caee5d6726b3da29799d307e40604.
The commit is an update of protobuf from 3.19 to 3.21.

Partial build log:
```console
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
   12 | #error This file was generated by a newer version of protoc which is
      |  ^~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
   13 | #error incompatible with your Protocol Buffer headers. Please update
      |  ^~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.h:14:2: error: #error your headers.
   14 | #error your headers.
      |  ^~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:10844:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
10844 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
      |                                       ^~~~~~~~~~~~~~~~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:11065:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
11065 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
      |                                       ^~~~~~~~~~~~~~~~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:11245:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
11245 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
      |                                       ^~~~~~~~~~~~~~~~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:11437:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
11437 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
      |                                       ^~~~~~~~~~~~~~~~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:11616:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
11616 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
      |                                       ^~~~~~~~~~~~~~~~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:11808:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
11808 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
      |                                       ^~~~~~~~~~~~~~~~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:12012:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
12012 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
      |                                       ^~~~~~~~~~~~~~~~~~~
/build/source/build/gens/src/proto/grpc/channelz/channelz.pb.cc:12212:39: error: 'CopyWithSourceCheck' is not a member of 'google::protobuf::Message'
12212 |     ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
```

### Notify maintainers
@mweinelt 
@LnL7
@marsam 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.05 (Quokka), 22.05.3767.6107f97012a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1``
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by squalus** [comment]
The x86_64-linux -> aarch64-linux cross build works for me on master @ d40fea9aeb8.

 `nix-build -A pkgsCross.aarch64-multiplatform.grpc`

**Comment by tusj** [comment]
@squalus I have updated the title to reflect that the failing build is on armv7. The error logs seems to indicate that there is a version incompatibility between protoc and grpc. However, I find it strange that it is only an issue for armv7.
