### PR TITLE
openmw: fix build on GCC 14

### LINKED ISSUE #370061: Build failure: openmw
## Steps To Reproduce

1. Build `openmw` for nixpkgs master (currently e3971d53ab8229477aca688b45a94d8c4babf5d8) using the following.

`nix build 'github:nixos/nixpkgs?rev=e3971d53ab8229477aca688b45a94d8c4babf5d8#openmw'`

## Build log

Had to upload to hastebin due to `Comment is too long (maximum is 65536 characters)`.

https://hastebin.com/share/uxumuridaw.bash

## Additional context

Currently in the process of `git bisect`-ing to find out when this issue was introduced. I think this was probably due to a compiler upgrade at some point and the `algorithm` header was included by chance but now it isn't. I noticed the `algorithm` header is included explicitly in openmw master but not in the release the nix package is currently based on so I suspect using a newer version of the openmw source would probably work.

https://github.com/OpenMW/openmw/blob/6ac0880cf367de07a1c7a8218a94f31c13902f12/components/bsa/bsa_file.cpp#L29

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.11, NixOS, 25.05 (Warbler), 25.05.20241219.d70bd19`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/8fwsiv0hd7nw1brkvka0jf1frk3m7qkr-source`
```

## Notify maintainers

@abbradar @marius851000

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SigmaSquadron**
Fixes #370061

This patch cannot be upstreamed because OpenMW does not maintain stable releases of the engine, only the in-development `master` branch.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 370126"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] No release notes: Change is minor.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SigmaSquadron** [comment]
This patch cannot be upstreamed because OpenMW does not maintain stable releases of the engine, only the in-development `master` branch.

**Comment by SigmaSquadron** [comment]
cc @marius851000. It seems like you haven't joined the NixOS org?

**Comment by SigmaSquadron** [comment]
cc @Sirius902 for testing.

**Comment by Sirius902** [comment]
> cc @marius851000. It seems like you haven't joined the NixOS org?
> 
> cc @Sirius902 for testing.

`nix run 'github:SigmaSquadron/nixpkgs?ref=push-xqlpmvsuovsw#openmw'` seems to build without issue on `x86_64-linux` and the game works fine, thanks!

**Comment by SigmaSquadron** [comment]
`portmod-rust` fails due to #332957

```console
error[E0282]: type annotations needed for `Box<_>`
  --> /build/portmod-rust-2.6.2-vendor.tar.gz/time/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

---

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 370126`

### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>portmod</li>
    <li>portmod.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>openmw</li>
  </ul>
</details>
