### PR TITLE
ncurses: revived clang patch

### PR DESCRIPTION
**Pull request by taku0**
This patch was introduced by 3e8344d334d42824ac3061a919ac15b19a1bf21d (#3661, Aug 17), then deleted by 0a32eab91e7a547325958da2581933a98095d50c (staging branch, Oct 5). I cannot bootstrap from staging branch on Darwin without this patch. I have no idea why the patch was deleted.

See also #2986.

Tested on OS X 10.11, staging branch with #10621 applied.

### CODE REVIEW

**Comment by pikajude** [comment]
@taku0 This change is in master. Do you need it in staging specifically?

**Comment by taku0** [comment]
@pikajude 
The patch is deleted in staging branch after it was introduced to master. If the staging branch is merged into the master, the patch will be deleted, results in build failure on Darwin. This pull request revives the patch in staging branch. Why does 0a32eab91e7a547325958da2581933a98095d50c delete the patch? I could not build the package on OS X 10.11 on the staging branch nor on the master branch merged with the staging branch.

**Comment by vcunat** [comment]
@pikajude: ping again.

**Comment by vcunat** [comment]
I guess there's no use waiting for a response.

**Comment by pipping** [comment]
Even though I already commented on commit f56a319e3ef1518274026d3350dfdca956a7ac1e, I'm not sure if anyone's seen it. This patch is what keeps ncurses 6.0 from compiling on darwin (macOS 10.11.6). It's rather obvious if you look at http://hydra.nixos.org/build/37537876/nixlog/1/raw. Vanilla 6.0 compiles fine.

**Comment by taku0** [comment]
The patch was intended to fix compilation errors. If Clang can compile ncurses 6.0 without the patch, please delete the patch.

**Comment by vcunat** [comment]
I have seen it and will switch darwin to 6.0 soon, based on your report (I'm unable to test directly).

**Comment by taku0** [comment]
ncueses 5 is available again for GHC (#17023). We may need to apply the patch only for 5.

**Comment by vcunat** [comment]
@taku0: for darwin it was available before, as you could see in f56a319e3ef15.
