### ISSUE TITLE
proxmox-image fails to build with qemu 7.0

### ISSUE THREAD

**Issue by alan-strohm** [NixOS/nixpkgs#171989]
### Describe the bug
After qemu: 6.2.0 -> 7.0.0 (commit 9d733f3d4975fb3c516a2bf2bf1bc6f50781a553) proxmox-image fails to build.

### Steps To Reproduce
`nix run github:nix-community/nixos-generators -- -f proxmox -I nixpkgs=https://releases.nixos.org/nixos/unstable/nixos-22.05pre375061.c777cdf5c56/nixexprs.tar.xz`

### Expected behavior
Command should produce a vma image

### Actual behavior
Various compilation errors (copied in case others are searching for a fix)
FAILED: libblock.fa.p/vma-writer.c.o
 ../vma-writer.c:206:5: error: too few arguments to function 'aio_set_fd_handler'
../vma-writer.c:209:5: error: too few arguments to function 'aio_set_fd_handler'

### Additional context
We probably need a rebased patch from proxmox:
https://git.proxmox.com/?p=pve-qemu.git;a=history;f=debian/patches/pve/0026-PVE-Backup-add-vma-backup-format-code.patch;h=b37b17c286da3d32945fbee8ee4fd97a418a50db;hb=HEAD

### Notify maintainers
@illustris @SuperSandro2000

**Comment by illustris** [comment]
https://github.com/qemu/qemu/commit/826cc32423d

This is what's causing the issue. I tried the easy solution of just passing `NULL` for `io_poll_ready` in both `aio_set_fd_handler` calls added by the patch. The qemu build succeeds, but the qemu process segfaults when building the VMA. I'll have to take a proper look at this tomorrow.
