### ISSUE TITLE
opencv 4.7.0 in nixpkgs master has link errors 

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#214124]
### Describe the bug

Hi, I created a minimal demonstrator for my problem:
https://github.com/tfc/whiteboard-opencv/tree/without-aruco (not main branch but `without-aruco`, to also build with nixos 22.11)

This minimal C++ app includes and links against opencv4.

Building this flake using `nix build` works just fine and the resulting app works.
Running `nix develop` and then doing `mkdir build && cd build && cmake .. && make` results in link errors:

```sh
... many others omitted ...
nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_core.so.4.7.0: undefined reference to `omp_get_max_threads@OMP_1.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_videoio.so.4.7.0: undefined reference to `gst_caps_set_simple'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_core.so.4.7.0: undefined reference to `clCreateCommandQueue@OPENCL_1.0'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_dnn.so.4.7.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RemoveLast()'
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/g8lrv5d3ixb2gmyhl14wkb6jl7wnqadc-opencv-4.7.0/lib/libopencv_videoio.so.4.7.0: undefined reference to `avcodec_get_context_defaults3@LIBAVCODEC_58'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/DisplayImage.dir/build.make:107: DisplayImage] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/DisplayImage.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

With nixpkgs on 22.11, both nix build and nix develop work.

### Steps To Reproduce

1. check out reproducer repo
2. Run `nix build`, works
3. Enter nix shell using `nix develop` and run: `mkdir build && cd build && cmake .. && make`, get mentioned error messages
4. Change flake input to nixpkgs 22.11
5. Repeat step 1 & 2 and see that they work

### Expected behavior

I would expect to not get these linker errors after upgrading to nixpkgs master

### Notify maintainers

@mdaiter @basvandijk 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-21.11.tar.gz, nixos-21.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by gbtb** [comment]
Hi :wave: Could you try building your flake with nixpkgs from the staging branch ? There are some changes that I've made to this package which are not yet merged into master https://github.com/NixOS/nixpkgs/blob/staging/pkgs/development/libraries/opencv/4.x.nix, maybe it'll help.
Also, I'm not very knowledgeable how c++ linking/compiling works, but from the look of this error messages it seems that dependencies of opencv - such as openmp, gstreamer, opencl, etc are missing from the environment. What if you add them explicitly, probably through opencv4.buildInputs ?
P. S. Maintainers listed for this package seems to be not active anymore (they've never responded me from the last october till today)

**Comment by tfc** [comment]
I just bisected nixpkgs: The commit [8c80bd08b7e39229947d55104d1871f5066437d9](https://github.com/NixOS/nixpkgs/commit/8c80bd08b7e39229947d55104d1871f5066437d9) breaks it for me.

I am trying staging now following your suggestion and will report back.

**Comment by tfc** [comment]
> Also, I'm not very knowledgeable how c++ linking/compiling works, but from the look of this error messages it seems that dependencies of opencv - such as openmp, gstreamer, opencl, etc are missing from the environment. What if you add them explicitly, probably through opencv4.buildInputs?

With dynamic linking, this should never be necessary. If it works with explicit linking against these deps, I would still consider this a bug.

**Comment by trofi** [comment]
> I just finished bisecting nixpkgs: The commit [8c80bd08b7e39229947d55104d1871f5066437d9](https://github.com/NixOS/nixpkgs/commit/8c80bd08b7e39229947d55104d1871f5066437d9) breaks it for me. @trofi do you have any insights on that?
> 
> I am trying staging now following your suggestion and will report back.

Yeah, my apologies for the breakage. That change was reverted for a very similar reason in https://github.com/NixOS/nixpkgs/pull/213185 and is in `staging-next` now. Can you try that one instead? That hopefully should not be too many rebuilds on you.

**Comment by tfc** [comment]
Oh yes, thank you for pointing me to that, I try that branch.

**Comment by tfc** [comment]
It's already all in the binary cache, so that was quick. This resolved my problem, thank you!
