### ISSUE TITLE
pyopengl: `from OpenGL import GL` throws error after version bump to 3.1.4

### ISSUE THREAD

**Issue by laikq** [NixOS/nixpkgs#76822]
**Describe the bug**
`from OpenGL import GL` works in pyopengl 3.1.0, and doesn't with pyopengl 3.1.4.

**To Reproduce**
Contents of `shell.nix`, in nixpkgs root (tested with commit 53553286b65db0ffe192fe46417919e396a167ba):
```nix
with import ./default.nix {};
mkShell { buildInputs = [ (python3.withPackages (pp: with pp; [pyopengl])) ];
```

```
$ nix-shell
[nix-shell]$ python3
>>> from OpenGL import GL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/nix/store/0jhwxaynxvz7alnwb2pib4980k55q3l4-python3-3.7.5-env/lib/python3.7/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Expected behavior**
There should be no error on importing `OpenGL.GL`.

**Additional context**
This breaks `friture`, and maybe other packages - although I didn't find packages in nixpkgs that use `python3Packages.pyopengl`.

Maintainer information:
```yaml
attribute: pyopengl
```

@FRidh

**Comment by gnidorah** [comment]
same with python2:
```
Python 2.7.17 (default, Oct 19 2019, 18:58:51) 
[GCC 9.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenGL import GL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/c0kn3cb123s25g5g0k71398iz5jcd816-python-2.7.17-env/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/nix/store/c0kn3cb123s25g5g0k71398iz5jcd816-python-2.7.17-env/lib/python2.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/nix/store/c0kn3cb123s25g5g0k71398iz5jcd816-python-2.7.17-env/lib/python2.7/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/nix/store/c0kn3cb123s25g5g0k71398iz5jcd816-python-2.7.17-env/lib/python2.7/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Comment by nyarla** [comment]
Hi,

I found the reason about this bug is triggered by PyOpenGL's `OpenGL/platform/ctypesloader.py` was changed.

On 3.1.0, `OpenGL/platform/ctypesloader.py` is used the filename of share library by argument `{name}` if absolute path, but on 3.1.4 is only used the `lib/{name}.so` filename. It's (maybe) changed  at this commit:

* [Try to load DLL versions 9->0 directly (including via preload) rather than introspecting ld cache](https://bazaar.launchpad.net/~mcfletch/pyopengl/trunk/revision/1011#OpenGL/platform/ctypesloader.py)

So [currently nixpkgs definition](https://github.com/NixOS/nixpkgs/blob/c5720f531bfdc408c23972a5685d5edf1a8267ea/pkgs/development/python-modules/pyopengl/default.nix) of PyOpenGL is just replaced `{name}` parameter to `/nix/store/...` path, however on 3.1.4 should patch the another way.

**Comment by guibou** [comment]
Thank you all for the report and for looking at the issue. I submitted a PR based on @nyarla suggestions.
