### PR TITLE
hardening flags: add `FORTIFY_SOURCE=3` support

### PR DESCRIPTION
**Pull request by risicle**
###### Description of changes

https://developers.redhat.com/articles/2022/09/17/gccs-new-fortification-level

GCC 12 makes available the new `-D_FORTIFY_SOURCE=3` mode, which significantly improves coverage over the existing protections. Other distributions have reportedly already enabled the flag universally with few problems. It would be nice to be ready to enable this flag once we've switched to GCC 12 as our default compiler.

The problem in doing this however is that the existing hardening flag mechanisms are based around flags being purely boolean and independent - we've never had to handle flags with multiple modes before.

After a lot of thought, what I've done here is to introduce a new flag, `fortify3`. `fortify` continues to mean `FORTIFY_SOURCE=2` mode - its behaviour remains unchanged for backwards compatibility. There are a couple of special handling rules to deconflict the meaning of the two:
 
 - When specifying `fortify3` in a _positive_ sense (i.e. `hardeningEnable`, `defaultHardeningFlags`, `NIX_HARDENING_ENABLE`), `fortify3` _supersedes_ plain `fortify`.
 - When specifying `fortify` in a _negative_ sense (i.e. `hardeningDisable`, `hardeningUnsupportedFlags`, `hardening_unsupported_flags`), `fortify` _implies_ that `fortify3` should also be disabled.

Interestingly, the "negative" rule has to be implemented twice, once at the nix-level for `hardeningDisable` and once at the bash-level for `hardening_unsupported_flags`.

In this PR, `fortify3` is then added to `hardeningUnsupportedFlags` for all compilers but GCC 12 (importantly also the bootstrap compilers). According to the above article, clang also supposedly supports `FORTIFY_SOURCE=3`, but reliable information on clang's fortify-support at any level is very hard to come by so I'm not going down that rabbit hole.

I've done a lot of building on nixos x86_64 with this:
 - as-is, everything disabled (came across no failures)
 - `fortify3` enabled by default (came across no failures)
 - `fortify3` enabled by default & default compiler GCC 12 (a couple of failures, fixes included)

I was very surprised at how ready both GCC 12 and `fortify3` support appear to be, at least for nixos x86_64.

I also built a substantial amount on x86_64 darwin, including packages using `gccStdenv`, not finding any breakages.

This PR itself shouldn't change how any packages are built as it neither adds `fortify3` to the `defaultHardeningFlags` or has a default compiler that supports `fortify3`, but once we're ready we'll have to add a straightforward commit such as https://github.com/risicle/nixpkgs/commit/665b35484910bc1671c5d519212a8472d9e8ed98 to do so (:point_left: consider testing with this cherry-picked on top)

Edit: have also built some `pkgsMusl`, `pkgsStatic` and `pkgsCross.aarch64-multiplatform` packages on x86_64 linux under various configurations of compiler/`fortify3`-enablement/disablement.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Comment by risicle** [comment]
I will probably merge this next week unless there are any objections - want this to get a lot of testing before we approach release-time.

**Comment by vcunat** [comment]
Based on what I've read I wasn't sure if the level 3 is a suitable default (for us), but that certainly doesn't matter for _this_ PR.

**Comment by trofi** [comment]
I did not bisect precisely but I have a strong suspiction it's fortify. `libomxil-bellagio` fails to build in `staging` (due to a legitimate stack overflow) as a:

```
$ nix build --no-link -f. -L libomxil-bellagio
...
libomxil-bellagio> omx_base_component.c: In function 'omx_base_component_GetComponentVersion':
libomxil-bellagio> omx_base_component.c:830:3: error: 'memcpy' reading 72 bytes from a region of size 24 [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-overread-Werror=stringop-overread8;;]
libomxil-bellagio>   830 |   memcpy(*pComponentUUID, uuid, 3*sizeof(uuid));
libomxil-bellagio>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by risicle** [comment]
Hmm. The only unusual things this package does is set `NIX_CFLAGS_COMPILE` with `-Wno-error=stringop-overflow=8` among other flags. This isn't _exactly_ `stringop-overread` though. Is this linux x86_64 gcc?

**Comment by trofi** [comment]
Yeah, vanilla unpatched `x86_64-linux`. I can bisect, will take quite a bit (afraid I lost my main machine for a while).

**Comment by risicle** [comment]
You could try using the `NIX_DEBUG` env var to see if the same flags are getting through to the compiler before and after.

**Comment by trofi** [comment]
Finally bisected it down to 0eedcfc3f4570ae3df43116d5d1e3f586fc36f7d `Merge pull request #212498 from risicle/ris-fortify3`. Which is (AFAIU) a merge commit. `git show -m` shows that this merge commit switches from `gcc-11` to `gcc-12`.

That explains at least the warning change. I'll work on a natural fix.

**Comment by trofi** [comment]
Proposed the change as https://github.com/NixOS/nixpkgs/pull/217379

**Comment by risicle** [comment]
I still don't understand how this PR is related, because it doesn't actually _enable_ `fortify3` by default, even on gcc 12.

**Comment by trofi** [comment]
Good point. Could it be that we lost `fortify` unconditionally? `NIX_DEBUG=1` says it's off for that file:

```diff
--- a/pkgs/development/libraries/libomxil-bellagio/default.nix
+++ b/pkgs/development/libraries/libomxil-bellagio/default.nix
@@ -27,6 +27,8 @@ stdenv.mkDerivation rec {
     if stdenv.cc.isGNU then "-Wno-error=array-bounds -Wno-error=stringop-overflow=8"
     else "-Wno-error=absolute-value -Wno-error=enum-conversion -Wno-error=logical-not-parentheses -Wno-error=non-literal-null-conversion";

+  NIX_DEBUG="1";
+
   meta = with lib; {
     homepage = "https://omxil.sourceforge.net/";
     description = "An opensource implementation of the Khronos OpenMAX Integration Layer API to access multimedia components";
```

```
libomxil-bellagio> HARDENING: disabled flags: pie fortify
libomxil-bellagio> HARDENING: Is active (not completely disabled with "all" flag)
libomxil-bellagio> HARDENING: enabling pic
libomxil-bellagio> HARDENING: enabling format
libomxil-bellagio> HARDENING: enabling stackprotector
libomxil-bellagio> HARDENING: enabling strictoverflow
libomxil-bellagio> extra flags before to /nix/store/0spl4agq94fairydh94xjmsm47zfk684-gcc-12.2.0/bin/gcc:
libomxil-bellagio>   -fPIC
libomxil-bellagio>   -Wformat
libomxil-bellagio>   -Wformat-security
libomxil-bellagio>   -Werror=format-security
libomxil-bellagio>   -fstack-protector-strong
libomxil-bellagio>   --param
libomxil-bellagio>   ssp-buffer-size=4
libomxil-bellagio>   -fno-strict-overflow
libomxil-bellagio> original flags to /nix/store/0spl4agq94fairydh94xjmsm47zfk684-gcc-12.2.0/bin/gcc:
libomxil-bellagio>   -DHAVE_CONFIG_H
libomxil-bellagio>   -I.
libomxil-bellagio>   -I../..
libomxil-bellagio>   -I../../include
libomxil-bellagio>   -I../../src
libomxil-bellagio>   -Wall
libomxil-bellagio>   -Werror
libomxil-bellagio>   -DCONFIG_DEBUG_LEVEL=0
libomxil-bellagio>   -c
libomxil-bellagio>   omx_base_component.c
libomxil-bellagio> extra flags after to /nix/store/0spl4agq94fairydh94xjmsm47zfk684-gcc-12.2.0/bin/gcc:
libomxil-bellagio>   -B/nix/store/fcx9kxk5lnzw6wj9wsrfwbfmyapvp1x3-glibc-2.35-224/lib/
libomxil-bellagio>   -idirafter
libomxil-bellagio>   /nix/store/7g4gmx9injcjkcm87jjbkqb3mvjzdfq1-glibc-2.35-224-dev/include
libomxil-bellagio>   -idirafter
libomxil-bellagio>   /nix/store/0spl4agq94fairydh94xjmsm47zfk684-gcc-12.2.0/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/include-fixed
libomxil-bellagio>   -B/nix/store/pwz9248d67bbf1rwlcl22kb7bq2n5znb-gcc-12.2.0-lib/lib
libomxil-bellagio>   -B/nix/store/kppvssg3zckrry3xy3d7v07k8nz086bn-gcc-wrapper-12.2.0/bin/
libomxil-bellagio>   -Wno-error=array-bounds
libomxil-bellagio>   -Wno-error=stringop-overflow=8
libomxil-bellagio>   -frandom-seed=1303k8pk7r
```

File: pkgs/build-support/cc-wrapper/add-hardening.sh [hunk 1]
```diff
@@ -12,8 +12,17 @@ done
...
+  fi
 done
 
+# make fortify and fortify3 mutually exclusive
+if [[ -z "${hardeningEnableMap[fortify3]-}" ]]; then
+  unset -v "hardeningEnableMap['fortify']"
+fi
+
 if (( "${NIX_DEBUG:-0}" >= 1 )); then
   declare -a allHardeningFlags=(fortify stackprotector pie pic strictoverflow format)
```
Comment (trofi) [inline pkgs/build-support/cc-wrapper/add-hardening.sh:27]: I wonder if we should add `fortify3` flag here to avoid ignorance.

Comment (risicle) [reply pkgs/build-support/cc-wrapper/add-hardening.sh:27]: Yes probably I think the first time I scanned this I assumed it was another default setting, not just debugging output.

**Comment by risicle** [comment]
At this point I should probably reveal #217390 that I've been working on.

**Comment by risicle** [comment]
...however, I haven't had the resources & time lately to do the rebuild required to test this PR with those tests.

File: pkgs/build-support/cc-wrapper/add-hardening.sh [hunk 2]
```diff
@@ -12,8 +12,17 @@ done
...
+  # fortify being unsupported implies fortify3 is unsupported
+  if [[ "$flag" = 'fortify' ]] ; then
+    unset -v "hardeningEnableMap['fortify3']"
+  fi
 done
 
+# make fortify and fortify3 mutually exclusive
+if [[ -z "${hardeningEnableMap[fortify3]-}" ]]; then
+  unset -v "hardeningEnableMap['fortify']"
+fi
```
Comment (trofi) [inline pkgs/build-support/cc-wrapper/add-hardening.sh:24]: If I read it correctly it unsets `fortify` if `fortify3` is not present (i.e. always).

File: pkgs/build-support/cc-wrapper/add-hardening.sh [hunk 3]
```diff
@@ -12,8 +12,17 @@ done
...
 for flag in @hardening_unsupported_flags@; do
   unset -v "hardeningEnableMap[$flag]"
+  # fortify being unsupported implies fortify3 is unsupported
+  if [[ "$flag" = 'fortify' ]] ; then
+    unset -v "hardeningEnableMap['fortify3']"
+  fi
 done
 
+# make fortify and fortify3 mutually exclusive
+if [[ -z "${hardeningEnableMap[fortify3]-}" ]]; then
```
Comment (risicle) [inline pkgs/build-support/cc-wrapper/add-hardening.sh:22]: I think I've got the sense of this flipped. This should be `-n` shouldn't it?

File: pkgs/build-support/cc-wrapper/add-hardening.sh (hunk 2 above)
Comment (risicle) [reply pkgs/build-support/cc-wrapper/add-hardening.sh:24]: Snap. See #217394

**Comment by trofi** [comment]
Surprisingly `samba` also was broken by dropped fortify flag with very amusing linker failures. https://github.com/NixOS/nixpkgs/pull/217394 fixes `samba` as well.
