### PR TITLE
rgbds: 0.4.2 -> 0.5.1

### PR DESCRIPTION
**Pull request by sbruder**
This also changes the owner of the GitHub repository and the homepage
URL because the repository was moved to a different organisation (the
old GitHub repository now redirects to the new one).

Also, since upstream switched to GNU Bison[1], the comment about byacc
is no longer necessary.

[1] https://github.com/gbdev/rgbds/issues/595

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132928` at bf6d934c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>rgbds</li>
    <li>sameboy</li>
  </ul>
</details>

**Comment by NieDzejkob** [comment]
Diff LGTM; smoke-tested the new release and didn't encounter issues.

**Review by meithecatte — APPROVED** [review]

**Comment by risicle** [comment]
Fails to build on macos 10.15:

```
builder for '/nix/store/lb40f7qys8d0909ig60rzpq71pmnf3b4-rgbds-0.5.1.drv' failed with exit code 2; last 10 log lines:
  ld: warning: ignoring file src/hashmap.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0xDE 0xC0 0x17 0x0B 0x00 0x00 0x00 0x00 0x14 0x00 0x00 0x00 0x90 0x1B 0x00 0x00 )
  ld: warning: ignoring file src/linkdefs.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0xDE 0xC0 0x17 0x0B 0x00 0x00 0x00 0x00 0x14 0x00 0x00 0x00 0x64 0x09 0x00 0x00 )
  ld: warning: ignoring file src/opmath.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0xDE 0xC0 0x17 0x0B 0x00 0x00 0x00 0x00 0x14 0x00 0x00 0x00 0x68 0x0D 0x00 0x00 )
  ld: warning: ignoring file /private/tmp/nix-build-rgbds-0.5.1.drv-0/version-0dd1e3.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0xDE 0xC0 0x17 0x0B 0x00 0x00 0x00 0x00 0x14 0x00 0x00 0x00 0x64 0x08 0x00 0x00 )
  Undefined symbols for architecture x86_64:
    "_main", referenced from:
       implicit entry/start for main executable
  ld: symbol(s) not found for architecture x86_64
  clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [Makefile:109: rgbasm] Error 1
```

**Comment by Artturin** [comment]
darwin failure is preexisting https://github.com/nix-community/hydra-check

**Comment by NieDzejkob** [comment]
Can I reproduce this failure interactively if I don't own a Mac?

**Comment by risicle** [comment]
I was going by https://hydra.nixos.org/build/148999310

**Comment by risicle** [comment]
And now sure enough https://hydra.nixos.org/build/149744255

**Comment by NieDzejkob** [comment]
Upstream suggests using up-to-date clang for the Mac build, as that's what gets tested. Not sure how I can check whether that fixes the build, as, again, I don't have a Mac to test with.
