### PR TITLE
perlPackages.Socket6: fix sv_undef compilation error

### PR DESCRIPTION
**Pull request by mbrgm**
###### Motivation for this change

Socket6.xs redefines `PV_sv_undef`, which breaks compilation from 306d5cdf03ad6375861a20b8885ef38699ca3c23.

###### Things done

 I added a patch to remove this redefinition. Compilation is now working again.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mbrgm** [comment]
@shlevy this fixes what I was asking you on IRC few days ago.

**Review by shlevy — APPROVED** [review]

**Comment by bjornfor** [comment]
Applied to master (4d7da18f5c09f04249a125143d49c3da5117b951). Thanks! (I hit this as I depend on munin in my config. Now munin works again.)
