### PR TITLE
nvidia-x11: Add patches for kernel 5.1.

### LINKED ISSUE #61165: Nividia Drivers with Linux 5.1 are broken
## Issue description

Nividia Prop drivers appears to have a missing dependancy and is unable to build correctly with the Linux 5.1 Kernel

### Steps to reproduce

sudo nix-rebuild boot --upgrade

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.13, NixOS, 19.09pre178675.24debf74ef5 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre178846.7defc47944f"`
 - channels(falcon): `"nixos-19.09pre177249.dfd8f84aef1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by ambrop72**
Fixes https://github.com/NixOS/nixpkgs/issues/61165

Produced this on my own based on the errors and kernel changes:

https://github.com/torvalds/linux/commit/3d3539018d2cbd12e5af4a132636ee7fd8d43ef0
This is an intentional breaking change forcing drivers to acknowledge that the
return type of vm_vault handlers has changed to vm_fault_t and that VM_FAULT_*
must be returned. The driver only needs to be fixed to actually return vm_fault_t,
it already returns VM_FAULT_* values.

https://github.com/torvalds/linux/commit/fcd70cd36b9bf697122538c9e38e8cf954b2342b
Some DRM helper functions were moved to a separate header.

###### Motivation for this change

Drivers do not build with kernel 5.1.

###### Things done
Builds without warning/errors and runs without obvious problem on my system with kernel 5.1. Plasma desktop with compositing and some random WebGL samples work fine. I think a few more people should test it.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ambrop72** [comment]
Sorry this doesn't actually work with these drivers, I was testing this with 418 drivers. I tried backporting but hit some issue about apparent breakage in linux acpi headers:
```
/nix/store/kaxpcplyarp30d6c5dxw5k742xzp6rrs-linux-5.1-dev/lib/modules/5.1.0/source/include/acpi/acpi_bus.h:44:25: error: unknown type name 'acpi_handle'; did you mean '__sighandler_t'?
```

**Comment by ambrop72** [comment]
I managed to fix that but there are more errors, I don't think it is reasonable to keep trying to patch this version.
