### PR TITLE
Ytermusic: return cargo.lock to git version

### PR DESCRIPTION
**Pull request by Lite5h4dow**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by codebam** [comment]
Please read https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md

Specifically: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#writing-good-commit-messages

Other than that I see no issues with this, it would make it a lot easier to keep the Cargo.lock in sync.

**Comment by Lite5h4dow** [comment]
@codebam yeah im terrible with commit messages, will do better in future. ty for the heads up tho.

**Comment by Lite5h4dow** [comment]
@NixOS/nixpkgs-merge-bot merge

**Comment by Lite5h4dow** [comment]
am i supposed to make a seperate pr to add myself as a maintainer?

**Comment by bengsparks** [comment]
Hey there ^^
In order for this PR to be considered for review, you will need to fixup your commits, as this PR should only contain one commit per task completed. Here these are the `ytermusic` and the `maintainer-list` changes.

The commits labelled `updating ytermusic` and `updating` should be combined into a singular commit with the message `ytermusic: remove Cargo.lock`.

The other commit (`adding maintainer details`) should be reworded into `maintainer-list: add Lite5h4dow`. 
This assumes you intend to actually maintain packages in nixpkgs. If this is not the case, then you can remove that commit from this PR, and it will still be eligible for acceptance.

**Comment by bengsparks** [comment]
As for the merge bot, that can only be used by maintainers of a package (found under `meta.maintainers` in a `default.nix` / `package.nix`) on a PR that modifies said package. As you do not maintain `ytermusic`, this failed for you.

Once you have fixed your commits, your PR can be reviewed and other contributors can offer feedback and / or approve your PR after having built your package using `nix`. Once enough approving reviews have come in (usually 2), someone with merge permissions will merge your changes and close your PR for you.

I hope that has made things clearer 😄

**Comment by Lite5h4dow** [comment]
@bengsparks @codebam 
All commit message changes have been completed as requested.

**Comment by bengsparks** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 390235`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ytermusic</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ytermusic</li>
  </ul>
</details>

File: pkgs/by-name/yt/ytermusic/package.nix [hunk 1]
```diff
@@ -19,14 +19,9 @@ rustPlatform.buildRustPackage rec {
...
-    lockFile = ./Cargo.lock;
-    outputHashes = {
-      "rusty_ytdl-0.6.6" = "sha256-htXD8v9Yd7S0iLjP6iZu94tP5KO5vbmkdUybqA7OtlU=";
-      "symphonia-0.5.4" = "sha256-uf0BbpqtlpZhsnV7Cm8egxjb/fXSINsOANTjDUQ4U9M=";
-    };
-  };
-  postPatch = "cp ${./Cargo.lock} Cargo.lock";
+  useFetchCargoVendor = true;
+
+  cargoHash = "sha256-5rHJ/ilARC/+9QieaLNHO4maXh/z0BDwTX7p7SBTDCc=";
```
Comment (bengsparks) [inline pkgs/by-name/yt/ytermusic/package.nix:24]: my builds on `{x86_64,aarch64}-linux` fail with:
```
specified: sha256-5rHJ/ilARC/+9QieaLNHO4maXh/z0BDwTX7p7SBTDCc=
   got:    sha256-B4qey0ibBCc0BDObxgE8wR9fIERKF38EMxYPrS73b/I=
```

you'll have to update `cargoHash` to the correct value, merge that commit into the [ytermusic: remove Cargo.lock](https://github.com/NixOS/nixpkgs/pull/390235/commits/4334d82f0ea4f4d0c697ecdfe281c31180167a2a) commit, then push with `git push --force-with-lease`. You can ping me again once you've completed that or have further questions 😄

**Review by bengsparks — CHANGES_REQUESTED** [review]

File: pkgs/by-name/yt/ytermusic/package.nix (hunk 1 above)
Comment (Lite5h4dow) [reply pkgs/by-name/yt/ytermusic/package.nix:24]: thanks, the hash must have changed, ill update that now!

Comment (Lite5h4dow) [reply pkgs/by-name/yt/ytermusic/package.nix:24]: resolved now, thanks for the catch! didnt even think to rebuild. just assumed the hash hadnt changed.

**Comment by bengsparks** [comment]
You'll need to remove that merge commit.
`git push upstream HEAD~1:ytermusic-update --force-with-lease` should do it.

**Comment by Lite5h4dow** [comment]
noob mistake, after noob mistake, ty for your patience :D

**Comment by Lite5h4dow** [comment]
done

**Review by bengsparks — APPROVED** [review]

**Review by codebam — APPROVED** [review]
LGTM

**Review by bengsparks — CHANGES_REQUESTED** [review]
```
┏━ 4 Errors: 
┃ error: builder for '/nix/store/zl5vnqbm4izxnfwcy5krlnb6xl9685id-source.drv' failed with exit code 1
┃ error: build of '/nix/store/zl5vnqbm4izxnfwcy5krlnb6xl9685id-source.drv' on 'ssh-ng://rosetta-builder' failed: hash mismatch in fixed-output derivation '/nix/store/zl5vnqbm4izxnfwcy5krlnb6xl9685id-source.drv':
┃          specified: sha256-B4qey0ibBCc0BDObxgE8wR9fIERKF38EMxYPrS73b/I=
┃             got:    sha256-nu/vedQNs5TgCG1v5qwwDTnFTyXCS2KnLVrnEhCtzCs=
┃ error: builder for '/nix/store/n9hm7y8ks62dhi4gm9hsmp9ba46p678f-source.drv' failed with exit code 1
┃ error: build of '/nix/store/n9hm7y8ks62dhi4gm9hsmp9ba46p678f-source.drv' on 'ssh-ng://rosetta-builder' failed: hash mismatch in fixed-output derivation '/nix/store/n9hm7y8ks62dhi4gm9hsmp9ba46p678f-source.drv':
┃          specified: sha256-B4qey0ibBCc0BDObxgE8wR9fIERKF38EMxYPrS73b/I=
┃             got:    sha256-nu/vedQNs5TgCG1v5qwwDTnFTyXCS2KnLVrnEhCtzCs=
```
Something odd is going on here.

File: pkgs/by-name/yt/ytermusic/package.nix (hunk 1 above)
Comment (bengsparks) [reply pkgs/by-name/yt/ytermusic/package.nix:24]: @Lite5h4dow my review comment referenced `cargoHash`, but you've used it for the repository hash instead.

File: pkgs/by-name/yt/ytermusic/package.nix [hunk 2]
```diff
@@ -16,17 +16,12 @@ rustPlatform.buildRustPackage rec {
     owner = "ccgauche";
     repo = "ytermusic";
     rev = "beta-${version}";
-    hash = "sha256-nu/vedQNs5TgCG1v5qwwDTnFTyXCS2KnLVrnEhCtzCs=";
```
Comment (bengsparks) [inline pkgs/by-name/yt/ytermusic/package.nix:19]: I suspect the issue is due to the hash changing. 
It shouldn't have changed, as you are still using the same git commit as the source for your package.
Please reread my comment related to `cargoHash`.

Comment (bengsparks) [inline pkgs/by-name/yt/ytermusic/package.nix:19]: This should be
```nix
  src = fetchFromGitHub {
    owner = "ccgauche";
    repo = "ytermusic";
    tag = "beta-${version}";
    hash = "sha256-nu/vedQNs5TgCG1v5qwwDTnFTyXCS2KnLVrnEhCtzCs=";
  };
  ```

File: pkgs/by-name/yt/ytermusic/package.nix [hunk 3]
```diff
@@ -16,17 +16,12 @@ rustPlatform.buildRustPackage rec {
...
-    lockFile = ./Cargo.lock;
-    outputHashes = {
-      "rusty_ytdl-0.6.6" = "sha256-htXD8v9Yd7S0iLjP6iZu94tP5KO5vbmkdUybqA7OtlU=";
-      "symphonia-0.5.4" = "sha256-uf0BbpqtlpZhsnV7Cm8egxjb/fXSINsOANTjDUQ4U9M=";
-    };
-  };
-  postPatch = "cp ${./Cargo.lock} Cargo.lock";
+  useFetchCargoVendor = true;
+
+  cargoHash = "sha256-5rHJ/ilARC/+9QieaLNHO4maXh/z0BDwTX7p7SBTDCc=";
```
Comment (bengsparks) [inline pkgs/by-name/yt/ytermusic/package.nix:24]: This should be:
```nix
cargoHash = "sha256-B4qey0ibBCc0BDObxgE8wR9fIERKF38EMxYPrS73b/I=";
```

**Review by bengsparks — CHANGES_REQUESTED** [review]

File: pkgs/by-name/yt/ytermusic/package.nix (hunk 3 above)
Comment (Lite5h4dow) [reply pkgs/by-name/yt/ytermusic/package.nix]: done

File: pkgs/by-name/yt/ytermusic/package.nix (hunk 2 above)
Comment (Lite5h4dow) [reply pkgs/by-name/yt/ytermusic/package.nix]: done

Comment (Lite5h4dow) [reply pkgs/by-name/yt/ytermusic/package.nix:19]: gotcha, thanks

**Comment by bengsparks** [comment]
Compilation still fails, but it's not your fault 🫠 
```console
       > error[E0282]: type annotations needed for `Box<_>`
       >   --> /build/ytermusic-0.1.0-vendor/time-0.3.34/src/format_description/parse/mod.rs:83:9
       >    |
       > 83 |     let items = format_items
       >    |         ^^^^^
       > ...
       > 86 |     Ok(items.into())
       >    |              ---- type must be known at this point
       >    |
       >    = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
       ```

**Comment by bengsparks** [comment]
What's even funnier is that running `cargo update` will fix the time bug, but introduce another type inference regression in `deranged` 😄

**Comment by bengsparks** [comment]
@Lite5h4dow 
you can update the Cargo.lock by running `cargo update time` in the root of the ytermusic repository,
then generate a diff with `git diff > $PATH-TO-NIXPKGS/pkgs/by-name/yt/ytermusic/time-crate.patch`.

tack this in just below the `src` of your `package.nix`
```nix
  # The `time` crate doesn't build on Rust 1.80+
  # https://github.com/NixOS/nixpkgs/issues/332957
  cargoPatches = [ ./time-crate.patch ];
```
and finally update the `cargoHash`; that should fix it all :)

**Comment by bengsparks** [comment]
@Lite5h4dow do you plan on adding this final touch to the PR? otherwise I can open a separate PR that reuses your commits (maintaining your authorship ofc), and put the fix on top of that? 😄

**Comment by Lite5h4dow** [comment]
> @Lite5h4dow do you plan on adding this final touch to the PR? otherwise I can open a separate PR that reuses your commits (maintaining your authorship ofc), and put the fix on top of that? 😄 

Hi, yes I do, I've just been traveling over the last few days so I'm exhausted, I'll give it a shot tonight

**Comment by bengsparks** [comment]
Superseded by #401217
