### PR TITLE
spoolman: fix static file responses with Starlette 1.0

### LINKED ISSUE #556848: spoolman: fails to serve assets
### Nixpkgs version

- Stable (26.05)

### Describe the bug

Installing the spoolman service with default configuration simply fails to load.
Requests to paths under `/assets/` fail 

### Steps to reproduce

1. `services.spoolman.enable = true;`
2. Attempt to load http://127.0.0.1:7912/

### Expected behaviour

Spoolman loads normally

### Screenshots

_No response_

### Relevant log output

```console
uvicorn.access             INFO     127.0.0.1:43418 - "GET / HTTP/1.1" 200
uvicorn.access             INFO     127.0.0.1:43418 - "GET /config.js HTTP/1.1" 200
uvicorn.access             INFO     127.0.0.1:43434 - "GET /assets/index-CfEY3xBo.js HTTP/1.1" 500
uvicorn.error              ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "/nix/store/v10vgzfnr9rbqf97b0i3z27b0swa8y1p-python3.12-uvicorn-0.40.0/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 416, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/v10vgzfnr9rbqf97b0i3z27b0swa8y1p-python3.12-uvicorn-0.40.0/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/z8l5pykzwr1kmrh03p1y627r0g5gn1mk-python3.12-fastapi-0.136.3/lib/python3.12/site-packages/fastapi/applications.py", line 1159, in __call__
    await super().__call__(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/applications.py", line 90, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 29, in __call__
    await responder(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 130, in __call__
    await super().__call__(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 46, in __call__
    await self.app(scope, receive, self.send_with_compression)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/nix/store/z8l5pykzwr1kmrh03p1y627r0g5gn1mk-python3.12-fastapi-0.136.3/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/routing.py", line 660, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/routing.py", line 680, in app
    await route.handle(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/routing.py", line 448, in handle
    await self.app(scope, receive, send)
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/staticfiles.py", line 98, in __call__
    response = await self.get_response(path, scope)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wq9l8y50dlvw6bfq54ijw4knpa6ls27q-python3.12-starlette-1.1.0/lib/python3.12/site-packages/starlette/staticfiles.py", line 132, in get_response
    return self.file_response(full_path, stat_result, scope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wrwxc5nysd7pwkh9h3ar16f4b5a28xdw-python3.12-spoolman-0.23.1/runpath/spoolman/client.py", line 62, in file_response
    response = FileResponse(full_path, status_code=status_code, stat_result=stat_result, method=method)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FileResponse.__init__() got an unexpected keyword argument 'method'
```

### Additional context

It seems like this is caused by #524412, which has breaking changes, like https://github.com/Kludex/starlette/pull/3147.
`starlette` is an indirect dependency via `fastapi`, but it's also directly used in `spoolman` code, despite not being explicitly defined.
According to the upstream PR for starlette, the argument was never used in the first place and had been deprecated for a long time.
`spoolman` has since updated its dependencies in [v0.24.0](https://github.com/Donkie/Spoolman/releases/tag/v0.24.0), the specific commit fixing this issue is https://github.com/Donkie/Spoolman/commit/d9fd44eab95b6dc6c6ded6b6ff69063437dc0735.

The update to a newer spoolman version (#550183) is blocked by a different dependency issue, [`inline-snapshot`](https://github.com/NixOS/nixpkgs/issues/550183#issuecomment-5294351499).

If updating spoolman directly is not achievable short term, it would help to at least backport part of the spoolman commit changing the python code to stop passing the deprecated `method` parameter.

### System metadata

 - system: `"aarch64-linux"`
 - host os: `Linux 6.18.46, NixOS, 26.05 (Yarara), 26.05.20260825.f4f6986`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.8`
 - nixpkgs: `/nix/store/pspa3balgpvp6p7vfm8f9yqvmi5gsfyc-source`

### Notify maintainers

@MayNiklas @pinpox

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by VykosMolt**
Starlette 1.0 removed the `method` argument of `FileResponse`, so Spoolman's static file handler raises a `TypeError` on every asset request and the web UI never loads. This backports the fix from Spoolman 0.24 to the packaged 0.23.1 source, so the runtime copy under `runpath` gets it too.

Fixes #556848.

Built on x86_64-linux with sandboxing. Started spoolman with an SQLite database and fetched the index page and its first JS asset: the asset returns HTTP 500 with the traceback from the issue before, and HTTP 200 after. The python 3.12 `inline-snapshot` test suite currently fails on master, so I built with its checks disabled for this test only; that is unrelated to this change.

Assisted by Claude Code (Claude Fable 5.1) for the issue, fix and tests, and Codex for wording. Leaving this as a draft for my review.

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [x] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

https://claude.ai/code/session_017BRSfkVqsVtFHCs43Yo2KF

### CODE REVIEW

**Comment by MayNiklas** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 560670`
Commit: `cb8c4ea05f77560c7e4e9ad44273a4e7b099668b`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>spoolman</li>
  </ul>
</details>

I wasn't able to build this PR.
Since you are backporting a fix from 0.24: how about we version bump Spoolman instead?

**Comment by VykosMolt** [comment]
Agreed, the bump is the better fix. The build failure in your review is not this patch: on master `python312Packages.inline-snapshot` fails 3 of 1402 tests, which takes `fastapi` and then anything pinned to `python312` down with it. #562916 moves the package to the default `python3` and I have built and tested it there. Closing this in favour of #562916.
