### PR TITLE
samtools: pull upstream fix for ncurses-6.3

### PR DESCRIPTION
**Pull request by trofi**
Without the fix build on ncurses-6.3 fails as:

    bam_tview_curses.c:88:5: error: format not a string literal and no format arguments [-Werror=format-security]
       88 |     mvprintw(y,x,str);
          |     ^~~~~~~~

### CODE REVIEW

**Comment by unode** [comment]
samtools 1.14 is out since October. Shall we bump the version instead of cherry-picking patches?

**Comment by trofi** [comment]
Naive `1.13` -> `1.14` bump fails to build for me against current `master` as:

```
samtools> bam_import.c:180:35: error: 'FASTQ_OPT_NAME2' undeclared (first use in this function); did you mean 'FASTQ_OPT_RNUM'?
samtools>   180 |             hts_set_opt(fp_in[i], FASTQ_OPT_NAME2, 1);
samtools>       |                                   ^~~~~~~~~~~~~~~
samtools>       |                                   FASTQ_OPT_RNUM
```

**Comment by trofi** [comment]
Ah, it requires newer `htslib` as well. I'll give it a try.

**Comment by trofi** [comment]
Attempt to update `htslib` broke `python3Packages.pysam`. Attempt to update `python3Packages.pysam` broke `python3Packages.cnvkit`. I'm way out of my depth here. I'd suggest sorting update separately from ncurses compat.
