### ISSUE TITLE
`python310Packages.tensorflow` build failure on x86_64-linux as of `8a8c18b3`

### ISSUE THREAD

**Issue by mcwitt** [NixOS/nixpkgs#185273]
### Steps To Reproduce
```console
nix-build -A python310Packages.tensorflow
```

### Build log
[gist](https://gist.github.com/mcwitt/9925990bbc4cf2e611a10dd0c22675e5)

### Additional context
First bad commit from bisection: 8a8c18b31e5f34cbdce47271571ed39e730aeb88

### Notify maintainers

@jyp @abbradar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.0-1046-oem, Ubuntu, 20.04.2 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - channels(matt): `"home-manager, nixgl"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by SuperSandro2000** [comment]
```
./tensorflow/lite/schema/schema_generated.h:3406:32: error: no matching function for call to 'tflite::QuantizationParameters::VerifyField<uint8_t>(flatbuffers::Verifier&, tflite::QuantizationParameters::FlatBuffersVTableOffset) const'
 3406 |            VerifyField<uint8_t>(verifier, VT_DETAILS_TYPE) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/flatbuffer_builder.h:31,
                 from /nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/flatbuffers.h:27,
                 from ./tensorflow/lite/schema/schema_conversion_utils.h:18,
                 from tensorflow/lite/schema/schema_conversion_utils.cc:15:
/nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/table.h:115:8: note: candidate: 'bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const [with T = unsigned char; flatbuffers::voffset_t = short unsigned int; size_t = long unsigned int]'
  115 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/table.h:115:8: note:   candidate expects 3 arguments, 2 provided
In file included from ./tensorflow/lite/schema/schema_conversion_utils.h:19,
                 from tensorflow/lite/schema/schema_conversion_utils.cc:15:
./tensorflow/lite/schema/schema_generated.h:3409:32: error: no matching function for call to 'tflite::QuantizationParameters::VerifyField<int32_t>(flatbuffers::Verifier&, tflite::QuantizationParameters::FlatBuffersVTableOffset) const'
 3409 |            VerifyField<int32_t>(verifier, VT_QUANTIZED_DIMENSION) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/flatbuffer_builder.h:31,
                 from /nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/flatbuffers.h:27,
                 from ./tensorflow/lite/schema/schema_conversion_utils.h:18,
                 from tensorflow/lite/schema/schema_conversion_utils.cc:15:
/nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/table.h:115:8: note: candidate: 'bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const [with T = int; flatbuffers::voffset_t = short unsigned int; size_t = long unsigned int]'
  115 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/nix/store/v7374h4362440cz6b3brx28lffm3dbkw-flatbuffers-2.0.6/include/flatbuffers/table.h:115:8: note:   candidate expects 3 arguments, 2 provided
In file included from ./tensorflow/lite/schema/schema_conversion_utils.h:19,
                 from tensorflow/lite/schema/schema_conversion_utils.cc:15:                 
```

**Comment by SuperSandro2000** [comment]
#183172

**Comment by samuela** [comment]
> #183172

How is the apache-beam issue related? Seems like tensorflow is failing in this case due to flatbuffers upgrade?

**Comment by mcwitt** [comment]
Closing as fixed by https://github.com/NixOS/nixpkgs/commit/161ea79c15e300e671edf4e5cfd294d221a2e766
