### ISSUE TITLE
nvidia-x11 384.90 no longer compiles with linuxPackages_latest 4.14.3 on NixOS 17.09

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#32330]
## Issue description

My NixOS 17.09 configuration with `linuxPackages_4_13` broke on upgrade because 4.13 was removed from the stable release branch yesterday (b6428f9e9cf0e2bb773398097c236eb3fe69f71c). I tried changing `4_13` to `latest` which had been bumped from 4.13 to 4.14 (d390d843cc6a752a5b39dcc8ce5ad9985a94afd0), but now the nvidia driver doesn’t compile (see below).

### Steps to reproduce

Try to `nixos-rebuild` a NixOS 17.09 configuration including:

```
boot.kernelPackages = pkgs.linuxPackages_latest;
services.xserver.enable = true;
services.xserver.videoDrivers = [ "nvidia" ];
```

and you get:

```
  CC [M]  /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.o
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:173:5: error: unknown field 'enable' specified in initializer
     .enable     = nvidia_crtc_enable,
     ^
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:173:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .enable     = nvidia_crtc_enable,
                   ^~~~~~~~~~~~~~~~~~
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:173:19: note: (near initialization for 'nv_crtc_helper_funcs.mode_valid')
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c: In function 'nvidia_plane_create':
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:223:9: error: incompatible type for argument 7 of 'drm_universal_plane_init'
         plane_type
         ^~~~~~~~~~
In file included from /nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drm_crtc.h:45:0,
                 from /nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drmP.h:69,
                 from /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-priv.h:30,
                 from /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:27:
/nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drm_plane.h:548:5: note: expected 'const uint64_t * {aka const long long unsigned int *}' but argument is of type 'enum drm_plane_type'
 int drm_universal_plane_init(struct drm_device *dev,
     ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:219:11: error: too few arguments to function 'drm_universal_plane_init'
     ret = drm_universal_plane_init(
           ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drm_crtc.h:45:0,
                 from /nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drmP.h:69,
                 from /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-priv.h:30,
                 from /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:27:
/nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drm_plane.h:548:5: note: declared here
 int drm_universal_plane_init(struct drm_device *dev,
     ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c: In function 'nvidia_drm_add_crtc':
/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:348:11: error: too few arguments to function 'drm_crtc_init_with_planes'
     ret = drm_crtc_init_with_planes(dev,
           ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drmP.h:69:0,
                 from /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-priv.h:30,
                 from /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.c:27:
/nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/include/drm/drm_crtc.h:899:5: note: declared here
 int drm_crtc_init_with_planes(struct drm_device *dev,
     ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/scripts/Makefile.build:315: /tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel/nvidia-drm/nvidia-drm-crtc.o] Error 1
make[2]: *** [/nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source/Makefile:1503: _module_/tmp/nix-build-nvidia-x11-384.90-4.14.3.drv-0/kernel] Error 2
make[2]: Leaving directory '/nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/build'
make[1]: *** [Makefile:146: sub-make] Error 2
make[1]: Leaving directory '/nix/store/1wp026ym0qsb4d703p39rqaszc6pzhn9-linux-4.14.3-dev/lib/modules/4.14.3/source'
make: *** [Makefile:81: modules] Error 2
builder for ‘/nix/store/7viw4zcvnnsr2k3g52w0yjc4z2nyxxwk-nvidia-x11-384.90-4.14.3.drv’ failed with exit code 2
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.16, NixOS, 17.09.2253.559ebb7ed02 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2281.b4a0c011e81"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by andersk** [comment]
Cherry-picking 2517cea04075fce96268431a03ec43324cb08859 “nvidia-x11-stable: 384.90 -> 387.22” to release-17.09 would fix this.

**Comment by yellowgh0st** [comment]
See issue 31640

**Comment by vcunat** [comment]
I don't think we should backport _major_ updates to the nvidia driver, but a minor update will probably fix the build.  As noted above, 4.14 may have more caveats for you, and I'm not confident that all fixes are backported to 17.09 branch ATM.

**Comment by vcunat** [comment]
Pushed.  I tested it builds.  I'm confident this update itself won't break anything; reopen otherwise.
