### ISSUE TITLE
Build failure: python3Packages.vtk

### ISSUE THREAD

**Issue by me-and** [NixOS/nixpkgs#542507]
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

`nix-build -A python3Packages.vtk`

### Can Hydra reproduce this build failure?

Yes, Hydra can reproduce this build failure.

### Link to Hydra build job

https://hydra.nixos.org/build/337985184

### Relevant log output

```console
[ 38%] Building CXX object IO/GDAL/CMakeFiles/IOGDAL.dir/vtkGDALVectorReader.cxx.o
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx: In member function 'void vtkGDALRasterReader::vtkGDALRasterReaderInternal::ReadMetaData(const std::string&)':
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx:185:43: error: invalid conversion from 'CSLConstList' {aka 'const char* const*'} to 'char**' [-fpermissive]
  185 |     char** papszMetaData = GDALGetMetadata(this->GDALData, nullptr);
      |                            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           CSLConstList {aka const char* const*}
[ 38%] Building CXX object Domains/Microscopy/CMakeFiles/DomainsMicroscopy.dir/vtkOpenSlideReader.cxx.o
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx: In member function 'std::vector<std::__cxx11::basic_string<char> > vtkGDALRasterReader::GetDomainMetaData(const std::string&)':
/build/VTK-9.5.2/IO/GDAL/vtkGDALRasterReader.cxx:881:41: error: invalid conversion from 'CSLConstList' {aka 'const char* const*'} to 'char**' [-fpermissive]
  881 |   char** papszMetadata = GDALGetMetadata(this->Impl->GDALData, domain.c_str());
      |                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         CSLConstList {aka const char* const*}
```

### Additional context

Found during testing of #542357.

The failure was previously hidden by #541085 and exposed when that was fixed in #541146.

### System metadata

 - system: `"aarch64-linux"`
 - host os: `Linux 6.18.31, NixOS, 26.11 (Zokor), 26.11.20260702.6517942`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.7`
 - nixpkgs: `/home/adam/.cache/nixpkgs-review/pr-542357-1/nixpkgs`

### Notify maintainers

@qbisi 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by amarshall** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/537721
