### ISSUE TITLE
virtualbox-guestadditions 6.1.6 vboxvideo fails to build with linux 5.7.17-dev

### ISSUE THREAD

**Issue by adamlwgriffiths** [NixOS/nixpkgs#96365]
**Describe the bug**

vboxguest-6.1.6 fails to compile the vboxvideo module

```
/build/install/src/vboxguest-6.1.6/vboxvideo/vbox_fb.c: In function 'vbox_fbdev_init':
/build/install/src/vboxguest-6.1.6/vboxvideo/vbox_fb.c:430:8: error: too many arguments to function 'drm_fb_helper_init'
  430 |  ret = drm_fb_helper_init(dev, &fbdev->helper, vbox->num_crtcs);
      |        ^~~~~~~~~~~~~~~~~~
In file included from /build/install/src/vboxguest-6.1.6/vboxvideo/vbox_drv.h:117,
                 from /build/install/src/vboxguest-6.1.6/vboxvideo/vbox_fb.c:41:
/nix/store/233b79hfvhsac1nmdwwqqsd8p5nmgyjg-linux-5.7.17-dev/lib/modules/5.7.17/source/include/drm/drm_fb_helper.h:216:5: note: declared here
  216 | int drm_fb_helper_init(struct drm_device *dev, struct drm_fb_helper *helper);
      |     ^~~~~~~~~~~~~~~~~~
/build/install/src/vboxguest-6.1.6/vboxvideo/vbox_fb.c:439:8: warning: implicit declaration of function 'drm_fb_helper_single_add_all_connectors' [-Wimplicit-function-declaration]
  439 |  ret = drm_fb_helper_single_add_all_connectors(&fbdev->helper);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [/nix/store/233b79hfvhsac1nmdwwqqsd8p5nmgyjg-linux-5.7.17-dev/lib/modules/5.7.17/source/scripts/Makefile.build:267: /build/install/src/vboxguest-6.1.6/vboxvideo/vbox_fb.o] Error 1
```

```
$ uname -a
Linux nixos 5.4.60 #1-NixOS SMP Fri Aug 21 11:05:39 UTC 2020 x86_64 GNU/Linux
```

**To Reproduce**
Using configuration.nix attached

`$ sudo nixos-rebuild switch`

**Screenshots**
![image](https://user-images.githubusercontent.com/1239156/91303108-df1ffb00-e7ea-11ea-88f0-2bde0a1dbb3a.png)

**Additional context**
Running inside latest VirtualBox (6.1.12 r139181)

Literally just updated.
Updated as 6.0 was unable to run X/GDM. 6.1 Seems to have fixed that.

**Notify maintainers**
@svanderburg 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.60, NixOS, 20.03.2839.0c59c1296b2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: linuxPackages_5_7.virtualboxGuestAdditions
# a list of nixos modules affected by the problem
module: ?
```

**Comment by vcunat** [comment]
This should compile fine, probably for a long time.  I now tried nixpkgs 21.11 and unstable/master, with kernels 5.4 and 5.10 (nothing in between those is maintained anymore).

Well, on unstable/master there's just one _other_ problem, but that just appeared and hopefully disappears very fast as well: PR #169177
