### PR TITLE
obs-studio: Add builtin support for browser source

### LINKED ISSUE #98035: obs studio with obs-browser
**Project description**

The obs-studio package does not currently have a way to build the new obs-browser plugin. Since version 25, OBS Studio has shipped with a version of obs-browser that includes linux support (which means that we don't need the obs-linuxbrowser any more), however, it seems like the nix version of obs-studio is not compiled with support for obs-browser.

More information in the notice at the top of the README [here](https://github.com/bazukas/obs-linuxbrowser)  and [here](https://github.com/obsproject/obs-browser)

### PR DESCRIPTION
**Pull request by Munksgaard**
###### Motivation for this change

Bump obs-studio and enable builtin support for browser source.

Since version 25, OBS Studio has shipped with a version of obs-browser that includes linux support (which means that we don't need the obs-linuxbrowser any more). However, previously, we didn't built obs-studio with that support enabled. This PR enables it.

For some reason, I'm getting a `patchelf: open: Permission denied` at the end of my `nix-build -A obs-studio`, but I can run the binary manually, and I have confirmed that the browser source is present and working. Does anyone have an idea how I can fix the permission issue?

This PR removes the need for the obs-linuxbrowser package (obs-linuxbrowser has also been archived and discontinued, as detailed [here](https://github.com/bazukas/obs-linuxbrowser))

Fixes #98035

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Munksgaard** [comment]
Oh damn, I'm late to the party! https://github.com/NixOS/nixpkgs/pull/99242

I'll update my PR to only add support for the browser source.

**Comment by Munksgaard** [comment]
I've updated it now. Should I also remove obs-linuxbrowser, now that it's not needed any longer? If so, how do I do that?

**Comment by mohe2015** [comment]
@Munksgaard I would assume you would need to remove https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/top-level/all-packages.nix#L21026 and https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/applications/video/obs-studio/linuxbrowser.nix

**Comment by mohe2015** [comment]
@Munksgaard 
Also I fixed the patchelf thing by using the following patch
```patch
diff --git a/pkgs/applications/video/obs-studio/default.nix b/pkgs/applications/video/obs-studio/default.nix
index 35c7ce93c6d..93eecae8d5c 100644
--- a/pkgs/applications/video/obs-studio/default.nix
+++ b/pkgs/applications/video/obs-studio/default.nix
@@ -80,12 +80,13 @@ in mkDerivation rec {
   postUnpack = ''
     mkdir -p cef/Release cef/Resources cef/libcef_dll_wrapper/
     for i in ${libcef}/share/cef/*; do
-      ln -s $i cef/Release/
-      ln -s $i cef/Resources/
+      cp -r $i cef/Release/
+      cp -r $i cef/Resources/
     done
-    ln -s ${libcef}/lib/libcef.so cef/Release/
-    ln -s ${libcef}/lib/libcef_dll_wrapper.a cef/libcef_dll_wrapper/
-    ln -s ${libcef}/include cef/
+    cp -r ${libcef}/lib/libcef.so cef/Release/
+    cp -r ${libcef}/lib/libcef_dll_wrapper.a cef/libcef_dll_wrapper/
+    cp -r ${libcef}/include cef/
+    ls -R cef
   '';
 
   # obs attempts to dlopen libobs-opengl, it fails unless we make sure
```
I don't know if this is a proper fix but this works. I think the underlying issues is that obs-studio's findCEF.cmake is flawed.

**Comment by Munksgaard** [comment]
Thank you, I'll try it later tonight.

**Review by mohe2015 — APPROVED** [review]
Tested it locally - the changes in https://github.com/NixOS/nixpkgs/pull/99284#issuecomment-702743779 could still be done in my opinion. I don't think a migration of the package is necessary.

**Comment by Munksgaard** [comment]
> Tested it locally - the changes in [#99284 (comment)](https://github.com/NixOS/nixpkgs/pull/99284#issuecomment-702743779) could still be done in my opinion. I don't think a migration of the package is necessary.

Oh yes, I forgot! Fixed that now :)

**Comment by mohe2015** [comment]
Not pushed yet? @Munksgaard

**Comment by Munksgaard** [comment]
Sorry! Should be done now :)

**Review by mohe2015 — APPROVED** [review]

**Comment by Munksgaard** [comment]
What's needed for this to get merged?

**Comment by Munksgaard** [comment]
Rebased on top of current master (to support 26.0.2)

**Comment by Munksgaard** [comment]
Can we get this merged? @mohe2015

File: pkgs/applications/video/obs-studio/default.nix [hunk 1]
```diff
@@ -73,13 +76,29 @@ in mkDerivation rec {
...
+  postUnpack = ''
+    mkdir -p cef/Release cef/Resources cef/libcef_dll_wrapper/
+    for i in ${libcef}/share/cef/*; do
+      cp -r $i cef/Release/
+      cp -r $i cef/Resources/
+    done
+    cp -r ${libcef}/lib/libcef.so cef/Release/
+    cp -r ${libcef}/lib/libcef_dll_wrapper.a cef/libcef_dll_wrapper/
+    cp -r ${libcef}/include cef/
+    ls -R cef
```
Comment (mohe2015) [inline pkgs/applications/video/obs-studio/default.nix:89]: This line should probably be removed

**Review by mohe2015 — CHANGES_REQUESTED** [review]
Otherwise it should be good do go.
I don't have merge permissions btw.

File: pkgs/applications/video/obs-studio/default.nix (hunk 1 above)
Comment (Munksgaard) [reply pkgs/applications/video/obs-studio/default.nix]: Fixed and rebased

**Review by mohe2015 — APPROVED** [review]
~~This can be merged in my opinion.~~ @Munksgaard Where did you get the version of cef from? Because I couldn't find any recommendation at obs-studio's repository and http://opensource.spotify.com/cefbuilds/index.html#linux64 shows that version 86 would be available. Or is cef also used by other packages? Anyways this would be something for a later pull request.

**Review by mohe2015 — CHANGES_REQUESTED** [review]
I think you broke something. My rebuild took a bit longer because I also rebased to master but I can't find the browser source option. Please check yourself.
**Edit: Submodule fetching seems to be broken** @Munksgaard 

If we're at it you could also change the commit messages according to the contributing guide. I think "libcef: oldversion ->  75.1.14" should be better. See https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md

File: pkgs/applications/video/obs-studio/default.nix [hunk 2]
```diff
@@ -44,8 +45,9 @@ in mkDerivation rec {
   src = fetchFromGitHub {
     owner = "obsproject";
     repo = "obs-studio";
-    rev = version;
+    rev = "refs/tags/${version}";
     sha256 = "1d502f80whh686mvq0yn6zpa5nvmnlzxwp5sjz43vpbbvhpbrdqj";
```
Comment (mohe2015) [inline pkgs/applications/video/obs-studio/default.nix:49]:
```suggestion
    sha256 = "vMrPMuZPeFefpbtQykeWifLBkhkSM47tDPid5cU3xa0=";
```
fetching submodules changed the hash and this didn't get attention because we both had the old version in cache probably.

**Comment by Munksgaard** [comment]
> ~This can be merged in my opinion.~ @Munksgaard Where did you get the version of cef from? Because I couldn't find any recommendation at obs-studio's repository and http://opensource.spotify.com/cefbuilds/index.html#linux64 shows that version 86 would be available. Or is cef also used by other packages? Anyways this would be something for a later pull request.

I took it from the build instructions on the obs-studio wiki: https://github.com/obsproject/obs-studio/wiki/Install-Instructions#linux-build-directions.

Trying to build with cef 86.0.2 causes problems I don't know how to fix:

```

/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: warning: libdrm.so.2, needed by /build/cef/Release/libcef.so, not found (try using -rpath or -rpath-link)
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: warning: libgbm.so.1, needed by /build/cef/Release/libcef.so, not found (try using -rpath or -rpath-link)
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_get_stride'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_get_handle'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_get_height'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_device_destroy'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_create_device'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_destroy'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_import'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_device_is_format_supported'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `drmPrimeHandleToFD'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_get_device'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_device_get_fd'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_create'
/nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cef/Release/libcef.so: undefined reference to `gbm_bo_get_width'
collect2: error: ld returned 1 exit status
make[2]: *** [plugins/obs-browser/CMakeFiles/obs-browser-page.dir/build.make:150: plugins/obs-browser/obs-browser-page] Error 1
make[1]: *** [CMakeFiles/Makefile2:1381: plugins/obs-browser/CMakeFiles/obs-browser-page.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I've updated the sha now, and it should compile correctly again. Please take a look when you have time @mohe2015

**Review by mohe2015 — APPROVED** [review]
LGTM!

**Comment by Munksgaard** [comment]
@puffnfresh How can I push this forward?

**Comment by Munksgaard** [comment]
@MP2E, @jb55, @puffnfresh: You guys were automatically assigned as reviewers on this PR, what can I do to push it forward? Is there someone else I should be nudging instead?

**Comment by Munksgaard** [comment]
@mweinelt, I saw you merged #101710, could you also merge this one, so we don't need to rely on obs-linuxbrowser anymore?

**Comment by jb55** [comment]
Philip Munksgaard <notifications@github.com> writes:
> @MP2E, @jb55, @puffnfresh: You guys were automatically assigned as
> reviewers on this PR, what can I do to push it forward? Is there
> someone else I should be nudging instead?

I haven't been able to test this yet but it's an awesome plugin that I
would love to see in nixpkgs!

I don't have commit access so I can't do much personally to push it
through

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 99284` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-ndi</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>libcef</li>
    <li>obs-studio</li>
    <li>obs-v4l2sink</li>
    <li>obs-wlrobs</li>
  </ul>
</details>

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
Thanks, tested and  LGTM.

**Comment by Munksgaard** [comment]
Thank you @mweinelt :)

**Comment by mweinelt** [comment]
Happy to help.
