### PR TITLE
haskell.packages.ghc94.gtk2hs-buildtools: remove patch for upstream fix

### PR DESCRIPTION
**Pull request by tbidne**
###### Description of changes

The `gtk2hs-buildtools-fix-ghc-9.4` patch was introduced in 962633e4d16c3a268f1e48e509a156cc33ba99ef to address https://github.com/gtk2hs/gtk2hs/issues/323. That issue has since been fixed upstream and a new release added to [hackage on 2023-05-12](https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.10.0), so if you try to run `nix build .#haskell.packages.ghc945.gtk2hs-buildtools` now you get an error like:

```
gtk2hs-buildtools> src/Gtk2HsSetup.hs:297:20: error:
gtk2hs-buildtools>     duplicate field name ‘ppOrdering’ in record construction
gtk2hs-buildtools>     |
gtk2hs-buildtools> 297 | ourC2hs bi lbi _ = PreProcessor {
gtk2hs-buildtools>     |                    ^^^^^^^^^^^^^^...
error: builder for '/nix/store/v138akp5dfcjky86d83gzgjgij64p2zr-gtk2hs-buildtools-0.13.10.0.drv' failed with exit code 1;
       last 10 log lines:
       > [43 of 46] Compiling GenBind          ( c2hs/gen/GenBind.hs, dist/build/GenBind.o, dist/build/GenBind.dyn_o )
       > [44 of 46] Compiling Version          ( c2hs/toplevel/Version.hs, dist/build/Version.o, dist/build/Version.dyn_o )
       > [45 of 46] Compiling Gtk2HsC2Hs       ( c2hs/toplevel/Gtk2HsC2Hs.hs, dist/build/Gtk2HsC2Hs.o, dist/build/Gtk2HsC2Hs.dyn_o )
       > [46 of 46] Compiling Gtk2HsSetup      ( src/Gtk2HsSetup.hs, dist/build/Gtk2HsSetup.o, dist/build/Gtk2HsSetup.dyn_o )
       >
       > src/Gtk2HsSetup.hs:297:20: error:
       >     duplicate field name ‘ppOrdering’ in record construction
       >     |
       > 297 | ourC2hs bi lbi _ = PreProcessor {
       >     |                    ^^^^^^^^^^^^^^...
       For full logs, run 'nix log /nix/store/v138akp5dfcjky86d83gzgjgij64p2zr-gtk2hs-buildtools-0.13.10.0.drv'.
```

due to both upstream and the patch adding the `ppOrdering` field. This PR removes the unnecessary patch.

Thanks!

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
Thanks!

Could you rebase this on the `haskell-updates` branch?  We generally ask all Haskell-related PRs to be targeted on the `haskell-updates` branch.

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by tbidne** [comment]
Ah of course, oversight.

**Comment by cdepillabout** [comment]
Looks like it now builds fine, thanks!

**Comment by tbidne** [comment]
Thank you!
