### PR TITLE
nvidia_x11: 2020.06

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg eval

File: pkgs/os-specific/linux/nvidia-x11/default.nix [hunk 1]
```diff
@@ -30,7 +30,12 @@ rec {
     else legacy_390;
 
   # No active beta right now
-  beta = stable;
+  beta = generic {
+    version = "450.51";
+    sha256_64bit = "17pam9737jx9vvczma5rafa0rihprccmfz84clb1y4nhbay5alf2";
```
Comment (veprbl) [inline pkgs/os-specific/linux/nvidia-x11/default.nix:35]: I think, this doesn't evaluate on i686-linux.

**Review by veprbl — APPROVED** [review]

**Comment by baracoder** [comment]
`nvidia_x11` and `nvidia_x11_legacy_390` builds with `linuxPackages_latest` (5.7) :tada: This would fix https://github.com/NixOS/nixpkgs/issues/90459

Changes for reference: 

440.100
> Added a workaround for some Pascal based notebooks, where the GPU could fall off the bus when idle.
> 
> Added support for the following GPUs:
> 
> GeForce GTX 1650 Ti
> GeForce GTX 1650 Ti with Max-Q Design
> GeForce RTX 2060 with Max-Q Design
> Quadro T1000 with Max-Q Design
> 
> Added new "Connector-N" display device aliases to the X driver's X configuration option parser.  This is useful in conjunction with the "ConnectedMonitor" X configuration option, for emulating the presence of connected monitors without knowing what specific connectors are available.  See the "Display Device Names" appendix in the README for details.

390.138
> Fixed a driver installation failure on Linux kernel 5.6 release candidates, where the NVIDIA kernel module failed to build with error "implicit declaration of function 'timespec_to_ns'".
> Fixed a driver installation failure on Linux kernel 5.6 release candidates, where the NVIDIA kernel module failed to build with error "implicit declaration of function 'getrawmonotonic'".
> Fixed a driver installation failure on Linux kernel 5.6 release candidates, where the NVIDIA kernel module failed to build with error "implicit declaration of function 'getnstimeofday'".
> Fixed a driver installation failure on Linux kernel 5.6 release candidates, where the NVIDIA kernel module failed to build with error "dereferencing pointer to incomplete type 'struct timeval'".
> Fixed a driver installation failure on Linux kernel 5.6 release candidates, where the NVIDIA kernel module failed to build with error "implicit declaration of function 'jiffies_to_timespec'".
> Fixed driver installation failure on Linux kernel 5.6 release candidates, where the NVIDIA kernel module failed to build with error "passing argument 4 of 'proc_create_data' from incompatible pointer type".
> Fixed driver installation failure on Linux kernel 5.6 release candidates, where the NVIDIA kernel module failed to build with error "implicit declaration of function 'ioremap_nocache'".
> Fixed driver installation failure on Oracle Linux 7.7 systems, where the NVIDIA kernel module failed to build with error "unknown type name 'vm_fault_t'".
> Add PRIME Synchronization support for Linux kernel 5.4 and newer.

340.108

> Updated the nvidia-drm kernel module for compatibility with the removal of the DRIVER_PRIME flag in recent Linux kernel versions.
> Updated nvidia-bug-report.sh to search the systemd journal for gdm-x-session logs.
> Fixed a bug that could prevent nvidia-xconfig from disabling the X Composite extension on version 1.20 of the X.org X server.
> Added support to nvidia-installer for systems which provide ncurses libraries supporting the ncurses widechar ABI only.
> Updated nvidia-installer to avoid problems with commands whose proper functionality may be dependent on system localization (e.g. via the LANG environment variable.) For example, some kernel configurations may produce unusable kernel modules if LANG is set to a language other than English.
> Updated nvidia-installer for better compatibility with ncurses when libncurses.so.6 exposes the ncurses reentrant ABI, such as on openSUSE Leap 15 and SUSE Linux Enterprise 15.
> Fixed a build failure, "too many arguments to function 'get_user_pages'", when building the NVIDIA kernel module for Linux kernel v4.4.168.
> Fixed a build failure, "implicit declaration of function do_gettimeofday", when building the NVIDIA kernel module for Linux kernel 5.0 release candidates.

**Review by baracoder — APPROVED** [review]

**Comment by kuznero** [comment]
When will it be possible to see this available in the `release-20.03`? Does anybody have a link to Hydra for this?

**Comment by veprbl** [comment]
@kuznero There was no backport to `release-20.03` yet.
