### ISSUE TITLE
rls doesn't build

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#77108]
**Describe the bug**

on master (254d6e5cbf5d366df46d4651706f9ff59427a57d)

```
   Compiling rls-rustc v0.6.0 (/build/rustc-1.40.0-src/src/tools/rls/rls-rustc)
error[E0463]: can't find crate for `rustc`
 --> src/tools/rls/rls-rustc/src/lib.rs:4:1
  |
4 | extern crate rustc;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `rls-rustc`.
warning: build failed, waiting for other jobs to finish...
error: build failed
builder for '/nix/store/bbjm5mgxyfmxj72ypnv7x65588icm9hh-rls-1.40.0.drv' failed with exit code 101
error: build of '/nix/store/bbjm5mgxyfmxj72ypnv7x65588icm9hh-rls-1.40.0.drv' failed
```

**To Reproduce**
1. cd nixpkgs
2. nix-build -A rls

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.92, NixOS, 20.03pre208171.2e8fc97dbfa (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre208171.2e8fc97dbfa"`
 - channels(bbigras2): `"home-manager, nixos-19.09-19.09.1776.b926503738c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bbigras** [comment]
cc @symphorien

**Comment by symphorien** [comment]
It seems like it has been caused by https://github.com/rust-lang/rust/pull/64823
I will have a look next week-end.

**Comment by bjornfor** [comment]
Fixed on master (13a4b486b919ea82ceb0c6b010c357ab62ee3b06).

**Comment by bbigras** [comment]
thanks!
