### PR TITLE
syncplay: apply TLS fix patch

### LINKED ISSUE #543881: syncplay: fails to connect to TLS-enabled servers
### Nixpkgs version

- Unstable (26.11)

### Describe the bug

Attempting to connect to a TLS-enabled Syncplay server, such as the official `syncplay.pl:8995`, fails and repeatedly logs the following error:

```
Unhandled Error
Traceback (most recent call last):
  File "/nix/store/53xai2r1z3d8qcs46ragsb2kamn7wymn-syncplay-1.7.5/lib/syncplay/syncplay/vendor/qt5reactor.py", line 153, in _read
    why = w.doRead()
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/internet/tcp.py", line 253, in doRead
    return self._dataReceived(data)
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/internet/tcp.py", line 258, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/protocols/tls.py", line 335, in dataReceived
    self._checkHandshakeStatus()
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/protocols/tls.py", line 266, in _checkHandshakeStatus
    self.wrappedProtocol.handshakeCompleted()
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/internet/endpoints.py", line 228, in handshakeCompleted
    self._wrappedProtocol.handshakeCompleted()
  File "/nix/store/53xai2r1z3d8qcs46ragsb2kamn7wymn-syncplay-1.7.5/lib/syncplay/syncplay/protocols.py", line 405, in handshakeCompleted
    if (self._serverCertificateTLS.get_extension(x).get_short_name() == b'subjectAltName'):
builtins.AttributeError: 'X509' object has no attribute 'get_extension'
```

### Steps to reproduce

1. Run Syncplay (tested on 753cc8a3a87467296ddd1fa93f0cc3e81120ee46)
2. Connect to the official server `syncplay.pl:8995`
3. Observe the repeated failure and error logs.

### Expected behaviour

1. Run Syncplay
2. Connect to the official server `syncplay.pl:8995`
3. Observe a working connection without error logs.

### Screenshots

_No response_

### Relevant log output

```console
Unhandled Error
Traceback (most recent call last):
  File "/nix/store/53xai2r1z3d8qcs46ragsb2kamn7wymn-syncplay-1.7.5/lib/syncplay/syncplay/vendor/qt5reactor.py", line 153, in _read
    why = w.doRead()
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/internet/tcp.py", line 253, in doRead
    return self._dataReceived(data)
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/internet/tcp.py", line 258, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/protocols/tls.py", line 335, in dataReceived
    self._checkHandshakeStatus()
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/protocols/tls.py", line 266, in _checkHandshakeStatus
    self.wrappedProtocol.handshakeCompleted()
  File "/nix/store/rqkjzz6s6prjrnxv8x22c9cls8sg91mm-python3.14-twisted-26.4.0/lib/python3.14/site-packages/twisted/internet/endpoints.py", line 228, in handshakeCompleted
    self._wrappedProtocol.handshakeCompleted()
  File "/nix/store/53xai2r1z3d8qcs46ragsb2kamn7wymn-syncplay-1.7.5/lib/syncplay/syncplay/protocols.py", line 405, in handshakeCompleted
    if (self._serverCertificateTLS.get_extension(x).get_short_name() == b'subjectAltName'):
builtins.AttributeError: 'X509' object has no attribute 'get_extension'
```

### Additional context

Upstream issue: https://github.com/Syncplay/syncplay/issues/774. This appears to be due to pyOpenSSL 26.2.0 (so presumably caused by bf2d049739a5).

Syncplay has [fixed the issue on `HEAD`](https://github.com/Syncplay/syncplay/pull/775), but has not made a release yet.

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 7.1.3, NixOS, 26.11 (Zokor), 26.11.20260715.753cc8a`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Lix, like Nix) 2.96.0-dev-pre20260717-dev_4c4d8b8
System type: x86_64-linux
Additional system types: aarch64-linux, i686-linux
Features: signed-caches, gc
System configuration file: /etc/nix/nix.conf
User configuration files: /home/qyriad/.config/nix/nix.conf:/nix/store/ihq3kim72pbm3ii3v8w8w2a33yf5v7bl-plasma-workspace-6.7.2/etc/xdg/nix/nix.conf:/nix/store/6cb3zjnwz0v3dz0cxralv4ym8y9al7hd-kglobalacceld-6.7.2/etc/xdg/nix/nix.conf:/nix/store/vah0fry2dsj8n2ai17ig7lb90xkw4sk5-baloo-6.27.0/etc/xdg/nix/nix.conf:/home/qyriad/.config/kdedefaults/nix/nix.conf:/home/qyriad/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/qyriad/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/qyriad/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/qyriad/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/i8bb62b2p0xnmrd6pnrrh2mjfkd37vc2-lix-patched-2.96.0-dev-pre20260717-dev_4c4d8b8/share`
 - nixpkgs: `/nix/store/7hlsbdxjq2mgczhlipabzn52sarzx0yd-source`

### Notify maintainers

cc @Assistant 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Assistant**
Applied patch Syncplay/syncplay#775 which fixes incompatibility with newer versions of pyOpenSSL and is not available on a release yet. 
Fixes #543881.

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [x] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

**Review by Qyriad — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 543895`
Commit: `db216dac7abe7d25b8b0a86c62089a9e12ce5a5c`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>syncplay</li>
    <li>syncplay-nogui</li>
  </ul>
</details>

File: pkgs/by-name/sy/syncplay/package.nix [hunk 1]
```diff
@@ -22,6 +22,9 @@ python3Packages.buildPythonApplication (finalAttrs: {
 
   patches = [
     ./trusted_certificates.patch
+    # https://github.com/Syncplay/syncplay/pull/775
```
Comment (SuperSandro2000) [inline pkgs/by-name/sy/syncplay/package.nix:26]: Now that the PR is merged we can fetchpatch it.

**Comment by Assistant** [comment]
Patch no longer needed on latest version. (#549303)
