### PR TITLE
lxpanel: fix build with gcc14, modernize

### PR DESCRIPTION
**Pull request by ghpzin**
lxpanel: fix build with gcc14

- add patch from upstream commit:
https://github.com/lxde/lxpanel/commit/0853b0fc981285ebd2ac52f8dfc2a09b1090748c
fixing `incompatible-pointer-types` error with gcc14

---

lxpanel: modernize

- replace `rec` with `finalAttrs`
- remove `with lib;` from `meta`

---

Fixes build failure of `lxpanel` since update to GCC 14 in #356812:
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.lxde.lxpanel.x86_64-linux
https://hydra.nixos.org/build/293037254

Log:
```
tray.c:634:19: error: assignment to 'GtkWidget *' {aka 'struct _GtkWidget *'} from incompatible pointer type 'GObject *' {aka 'struct _GObject *'} [-Wincompatible-pointer-types]
  634 |     tr->invisible = g_object_ref_sink(G_OBJECT(invisible));
      |                   ^
make[3]: *** [Makefile:1302: libbuiltin_plugins_a-tray.o] Error 1
make[3]: Leaving directory '/build/lxpanel-0.10.1/plugins'
make[2]: *** [Makefile:1107: builtin-plugins-hook] Error 2
make[2]: Leaving directory '/build/lxpanel-0.10.1/src'
make[1]: *** [Makefile:521: all-recursive] Error 1
make[1]: Leaving directory '/build/lxpanel-0.10.1'
make: *** [Makefile:424: all] Error 2
```

Tracking issue: #388196 

---

If somebody wants to test whether it runs after building, fyi - it immediately segfaults on wayland (same way it does on 24.11), backtrace goes: `main() -> resolve_atoms() -> XInternAtoms`
I assume it is not expected to run on wayland or through XWayland.
Seems to run fine in X11 VM (panel opens, shows currently open windows), tested inside `nixosTests.i3wm.driverInteractive` by adding `environment.systemPackages = [ pkgs.lxpanel ];` in test config.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ghpzin** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 395103`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>lxpanel (lxde.lxpanel)</li>
  </ul>
</details>

**Comment by Sigmanificient** [comment]
I love the effort you put in the PR descriptions, great work!

**Review by ryneeverett — APPROVED** [review]
I haven't tested because I haven't run Xorg for some years now. (And obviously don't use this package anymore either.) But this seems pretty reasonable.

**Review by ethancedwards8 — APPROVED** [review]
