### PR TITLE
ceres-solver: cleanup, fix cuda build

### LINKED ISSUE #560909: Build failure: pkgsCuda.ceres-solver
### Nixpkgs version

- Unstable (26.11)

### Steps to reproduce

`nix-build -A pkgsCuda.ceres-solver`

### Can Hydra reproduce this build failure?

Hydra doesn’t try to build the package.

### Link to Hydra build job

_No response_

### Relevant log output

```console
In file included from /nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/SuiteSparseQR.hpp:23,
                 from /build/ceres-solver-2.2.0/internal/ceres/suitesparse.h:46,
                 from /build/ceres-solver-2.2.0/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:45:
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:937:39: error: 'cublasHandle_t' does not name a type
  937 |         #define CHOLMOD_CUBLAS_HANDLE cublasHandle_t
      |                                       ^~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:947:5: note: in expansion of macro 'CHOLMOD_CUBLAS_HANDLE'
  947 |     CHOLMOD_CUBLAS_HANDLE cublasHandle ;
      |     ^~~~~~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:938:39: error: 'cudaStream_t' does not name a type
  938 |         #define CHOLMOD_CUDASTREAM    cudaStream_t
      |                                       ^~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:950:5: note: in expansion of macro 'CHOLMOD_CUDASTREAM'
  950 |     CHOLMOD_CUDASTREAM  gpuStream [CHOLMOD_HOST_SUPERNODE_BUFFERS] ;
      |     ^~~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:939:39: error: 'cudaEvent_t' does not name a type
  939 |         #define CHOLMOD_CUDAEVENT     cudaEvent_t
      |                                       ^~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:952:5: note: in expansion of macro 'CHOLMOD_CUDAEVENT'
  952 |     CHOLMOD_CUDAEVENT   cublasEventPotrf [3] ;
      |     ^~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:939:39: error: 'cudaEvent_t' does not name a type
  939 |         #define CHOLMOD_CUDAEVENT     cudaEvent_t
      |                                       ^~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:953:5: note: in expansion of macro 'CHOLMOD_CUDAEVENT'
  953 |     CHOLMOD_CUDAEVENT   updateCKernelsComplete ;
      |     ^~~~~~~~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:939:39: error: 'cudaEvent_t' does not name a type
  939 |         #define CHOLMOD_CUDAEVENT     cudaEvent_t
      |                                       ^~~~~~~~~~~
/nix/store/l1r4n70gjd26f7chxcc4xybg4jqh7r2k-suitesparse-7.10.0-dev/include/suitesparse/cholmod.h:954:5: note: in expansion of macro 'CHOLMOD_CUDAEVENT'
  954 |     CHOLMOD_CUDAEVENT   updateCBuffersFree [CHOLMOD_HOST_SUPERNODE_BUFFERS] ;
      |     ^~~~~~~~~~~~~~~~~
make[2]: *** [internal/ceres/CMakeFiles/ceres_internal.dir/build.make:1241: internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_sparse_normal_cholesky_solver.cc.o] Error 1
make[2]: *** [internal/ceres/CMakeFiles/ceres_internal.dir/build.make:1031: internal/ceres/CMakeFiles/ceres_internal.dir/covariance_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:324: internal/ceres/CMakeFiles/ceres_internal.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### Additional context

Seems to be broken by https://github.com/NixOS/nixpkgs/pull/503891

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.48, NixOS, 26.11 (Zokor), 26.11.20260826.9fbb54b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.34.8`

### Notify maintainers

@giogadi 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+label%3A%220.kind%3A+build+failure%22).
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.
- [x] I assert that I have read the [automation/AI policy](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy) and that this issue report complies with it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Adapted from https://github.com/ConnorBaker/nixpkgs/commit/31a5f15104bd51babc9a41fbe313a163dcf9b495

Fixes #560909

Reported here: https://github.com/NixOS/nixpkgs/pull/503891#issuecomment-5574514869

cc @nixos/cuda-maintainers

- Built on platform:
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [ ] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.
- [ ] Follows the [automation/AI policy].

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[automation/AI policy]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#automationai-policy
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

### CODE REVIEW

File: pkgs/by-name/ce/ceres-solver/package.nix [hunk 1]
```diff
@@ -1,47 +1,96 @@
...
 
-  src = fetchurl {
-    url = "http://ceres-solver.org/ceres-solver-${finalAttrs.version}.tar.gz";
-    sha256 = "sha256-SLIwKnmG7OFyiYR3w7zW3rj7XPGbMye8SZaarUzt6C0=";
+  __structuredAttrs = true;
+  strictDeps = true;
+
+  src = fetchFromGitHub {
+    owner = "ceres-solver";
+    repo = finalAttrs.pname;
```
Comment (ethancedwards8) [inline pkgs/by-name/ce/ceres-solver/package.nix]:
```suggestion
    repo = "ceres-solver";
```
nit: https://github.com/NixOS/nixpkgs/issues/277994

**Review by ethancedwards8 — APPROVED** [review]
this looks good to me, though

File: pkgs/by-name/ce/ceres-solver/package.nix (hunk 1 above)
Comment (GaetanLepage) [reply pkgs/by-name/ce/ceres-solver/package.nix]: Good catch thanks!

File: pkgs/by-name/ce/ceres-solver/package.nix [hunk 2]
```diff
@@ -1,47 +1,96 @@
...
   enableStatic ? stdenv.hostPlatform.isStatic,
   withBlas ? true,
+  cudaSupport ? config.cudaSupport,
 }:
+let
+  effectiveStdenv = if cudaSupport then cudaPackages.backendStdenv else stdenv;
+in
+
+# gflags is required to run tests
+assert runTests -> gflags != null;
```
Comment (joe-saronic) [inline pkgs/by-name/ce/ceres-solver/package.nix]: `gflags` is always enabled, no?

File: pkgs/by-name/ce/ceres-solver/package.nix [hunk 3]
```diff
@@ -1,47 +1,96 @@
...
+
+  nativeBuildInputs = [
+    cmake
+  ]
+  ++ lib.optionals cudaSupport [
+    cudaPackages.cuda_nvcc
+  ];
+
+  buildInputs =
+    lib.optionals runTests [
```
Comment (joe-saronic) [inline pkgs/by-name/ce/ceres-solver/package.nix]: Which makes this always `true`, no?

**Review by joe-saronic — COMMENTED** [review]
Closes #560909

**Comment by joe-saronic** [comment]
Plural in PR title (and commit I think) is a typo, right?

File: pkgs/by-name/ce/ceres-solver/package.nix [hunk 4]
```diff
@@ -1,47 +1,96 @@
...
   ++ lib.optionals withBlas [
     blas
-    suitesparse
     metis
+    suitesparse
   ];
 
   cmakeFlags = [
-    "-DBUILD_SHARED_LIBS=${if enableStatic then "OFF" else "ON"}"
+    (lib.cmakeBool "BUILD_SHARED_LIBS" (!enableStatic))
```
Comment (joe-saronic) [inline pkgs/by-name/ce/ceres-solver/package.nix:88]:
```suggestion
    (lib.cmakeBool "BUILD_SHARED_LIBS" (!enableStatic))
    (lib.cmakeBool "USE_CUDA" cudaSupport)
```

**Comment by joe-saronic** [comment]
Reading through the options, it looks like if CUDA is missing, the build will continue with a warning. Might be worth adding a `postConfigure` check that verifies that `USE_CUDA` is still `ON` for the cases where `cudaSupport` is enabled.

File: pkgs/by-name/ce/ceres-solver/package.nix [hunk 5]
```diff
@@ -1,47 +1,93 @@
...
+
+  # propagatedBuildInputs
+  eigen,
   glog,
-  suitesparse,
+  blas,
   metis,
+  suitesparse,
+
   runTests ? false,
```
Comment (joe-saronic) [inline pkgs/by-name/ce/ceres-solver/package.nix]: Would you consider adding a `passthru.tests.full` attribute instead?

File: pkgs/by-name/ce/ceres-solver/package.nix (hunk 4 above)
Comment (GaetanLepage) [reply pkgs/by-name/ce/ceres-solver/package.nix:88]: Nice catch. Done.

Comment (joe-saronic) [reply pkgs/by-name/ce/ceres-solver/package.nix:88]: I hope to forget what I just learned about the cmake options sooner rather than later :)

File: pkgs/by-name/ce/ceres-solver/package.nix (hunk 5 above)
Comment (joe-saronic) [reply pkgs/by-name/ce/ceres-solver/package.nix]: Probably should delete the argument?

File: pkgs/by-name/ce/ceres-solver/package.nix [hunk 6]
```diff
@@ -1,47 +1,96 @@
...
+
+  nativeBuildInputs = [
+    cmake
+  ]
+  ++ lib.optionals cudaSupport [
+    cudaPackages.cuda_nvcc
+  ];
+
+  buildInputs =
+    lib.optionals runTests [
```
Comment (joe-saronic) [inline pkgs/by-name/ce/ceres-solver/package.nix]: And move this into the `passthru`?

Comment (GaetanLepage) [reply pkgs/by-name/ce/ceres-solver/package.nix]: I think it's more correct to have the derivation "complete", and `passthru.tests` be a simple `overrideAttrs`.
I removed `runTests` in favor of `doCheck` though.

File: pkgs/by-name/ce/ceres-solver/package.nix (hunk 2 above)
Comment (GaetanLepage) [reply pkgs/by-name/ce/ceres-solver/package.nix]: Removed this assert. Not sure why it was there.

File: pkgs/by-name/ce/ceres-solver/package.nix (hunk 6 above)
Comment (joe-saronic) [reply pkgs/by-name/ce/ceres-solver/package.nix]: That is indeed much more elegant. I have learned much from your edits to my PRs and yours.

File: pkgs/by-name/ce/ceres-solver/package.nix [hunk 7]
```diff
@@ -1,47 +1,95 @@
...
-  suitesparse,
+  blas,
   metis,
-  runTests ? false,
+  suitesparse,
+
+  # passthru
+  nix-update-script,
+
   enableStatic ? stdenv.hostPlatform.isStatic,
```
Comment (joe-saronic) [inline pkgs/by-name/ce/ceres-solver/package.nix:24]: Is this going to be a potential problem with how `effectiveStdenv` is defined if `cudaSupport` is set?

Comment (GaetanLepage) [reply pkgs/by-name/ce/ceres-solver/package.nix:24]: Which thing might be a potential problem? (GitHub UI is not great).

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 561033 --package ceres-solver --package cudaPackages.pkgs.ceres-solver`
Commit: `636dd92b82d70245f882c8a50115e274986879d8`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ceres-solver</li>
  </ul>
</details>


---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ceres-solver</li>
  </ul>
</details>


---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ceres-solver</li>
  </ul>
</details>

File: pkgs/by-name/ce/ceres-solver/package.nix (hunk 7 above)
Comment (joe-saronic) [reply pkgs/by-name/ce/ceres-solver/package.nix:24]: The definition of `enableStatic` which is still using `stdenv`, which my understanding is not going to depend on the status of CUDA

**Comment by joe-saronic** [comment]
`ceres-solvers` should be `ceres-solver`?

**Review by joe-saronic — APPROVED** [review]

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 561033 --package ceres-solver --package cudaPackages.pkgs.ceres-solver.tests --package cudaPackages_13.pkgs.ceres-solver.tests --package cudaPackages_13.pkgs.ceres-solver --package ceres-solver.tests --package cudaPackages.pkgs.ceres-solver`
Commit: `c7c8399010c377cc80c0b118d62e62632b63ef65`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>ceres-solver</li>
    <li>ceres-solver.tests.withTests</li>
  </ul>
</details>


---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>ceres-solver</li>
    <li>ceres-solver.tests.withTests</li>
  </ul>
</details>


---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>ceres-solver</li>
    <li>ceres-solver.tests.withTests</li>
  </ul>
</details>
