### PR TITLE
miniupnpc: fix missing include

### PR DESCRIPTION
**Pull request by FliegendeWurst**
If this is not sufficient to fix the build failures we can revert the upgrade.

## Things done

- Built on platform(s)
  - [x] x86_64-linux: and `libtransmission_3`
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [Nixpkgs 25.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/doc/release-notes/rl-2511.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/doc/manual/release-notes/rl-2505.section.md) Nixpkgs Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
- [NixOS 25.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2511.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) NixOS Release notes)
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by phanirithvij — APPROVED** [review]
except elementsd-simplicity (already broken before miniupnpc update to 2.3.3) all packages build on [aarch64-linux](https://github.com/phanirithvij/nixpkgs-review-gha/actions/runs/15437111191/job/43445949861)

in the gha runner nixpkgs-review for this on x86_64-linux is unlikely to finish before the 6h limit. previous [run](https://github.com/phanirithvij/nixpkgs-review-gha/actions/runs/15435891414/job/43442170344) for the update pr

maybe [darwin](https://github.com/phanirithvij/nixpkgs-review-gha/actions/runs/15444114391) runners will be able to.

**Comment by FliegendeWurst** [comment]
elementsd-simplicity: #413918

**Comment by phanirithvij** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review-gha`](https://github.com/Defelo/nixpkgs-review-gha)

Command: `nixpkgs-review pr 413829`

Logs: https://github.com/phanirithvij/nixpkgs-review-gha/actions/runs/15444114391


---
### `x86_64-darwin` (sandbox = relaxed)
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>bitcoin-knots</li>
    <li>bitcoind-knots</li>
    <li>elementsd-simplicity</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 34 packages built:</summary>
  <ul>
    <li>aerc</li>
    <li>dante</li>
    <li>elements</li>
    <li>elementsd</li>
    <li>groestlcoin</li>
    <li>groestlcoind</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>i2pd</li>
    <li>libtransmission_3</li>
    <li>libtransmission_3.apparmor</li>
    <li>libtransmission_4</li>
    <li>libtransmission_4.apparmor</li>
    <li>miniupnpc</li>
    <li>openomf</li>
    <li>particl-core</li>
    <li>pshs</li>
    <li>qodem</li>
    <li>tests.fetchtorrent.http-link</li>
    <li>tests.fetchtorrent.magnet-link</li>
    <li>transmission_3 (transmission_3_noSystemd)</li>
    <li>transmission_3-gtk</li>
    <li>transmission_3-gtk.apparmor</li>
    <li>transmission_3-qt</li>
    <li>transmission_3-qt.apparmor</li>
    <li>transmission_3.apparmor (transmission_3_noSystemd.apparmor)</li>
    <li>transmission_4</li>
    <li>transmission_4-gtk</li>
    <li>transmission_4-gtk.apparmor</li>
    <li>transmission_4-qt (transmission_4-qt5)</li>
    <li>transmission_4-qt.apparmor (transmission_4-qt5.apparmor)</li>
    <li>transmission_4-qt6</li>
    <li>transmission_4-qt6.apparmor</li>
    <li>transmission_4.apparmor</li>
  </ul>
</details>

---
<details>
<summary>Error logs: `x86_64-darwin`</summary>
<details>
<summary>bitcoin-knots</summary>
<pre>2025-06-04T15:20:49.883059Z [test] [validationinterface.cpp:187] [UpdatedBlockTip] [validation] Enqueuing UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T15:20:49.883088Z [test] [validationinterface.cpp:192] [ActiveTipChange] [validation] ActiveTipChange: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T15:20:49.883151Z [scheduler] [validationinterface.cpp:222] [operator()] [validation] BlockConnected: block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T15:20:49.883175Z [scheduler] [validationinterface.cpp:187] [operator()] [validation] UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T15:20:49.883472Z [test] [banman.cpp:42] [LoadBanlist] Recreating the banlist database
2025-06-04T15:20:49.883768Z [test] [banman.cpp:69] [DumpBanlist] [net] Flushed 0 banned node addresses/subnets to disk  0ms
2025-06-04T15:20:49.883790Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T15:20:49.883807Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T15:20:49.883915Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T15:20:49.883937Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T15:20:49.884428Z [test] [net.cpp:3831] [CNode] [net] Added connection to 127.0.0.1:8333 peer=1
2025-06-04T15:20:49.884474Z [test] [net.cpp:417] [ConnectNode] [net] trying v2 connection localhost lastseen=0.0hrs
make[3]: *** [Makefile:23200: test/net_peer_connection_tests.cpp.test] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/private/tmp/nix-build-bitcoin-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[2]: *** [Makefile:21066: check-am] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-bitcoin-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[1]: *** [Makefile:20738: check-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-bitcoin-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make: *** [Makefile:820: check-recursive] Error 1</pre>
</details>
<details>
<summary>bitcoind-knots</summary>
<pre>2025-06-04T15:06:01.305805Z [scheduler] [validationinterface.cpp:222] [operator()] [validation] BlockConnected: block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T15:06:01.305893Z [test] [validationinterface.cpp:187] [UpdatedBlockTip] [validation] Enqueuing UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T15:06:01.305941Z [scheduler] [validationinterface.cpp:187] [operator()] [validation] UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T15:06:01.305994Z [test] [validationinterface.cpp:192] [ActiveTipChange] [validation] ActiveTipChange: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T15:06:01.306449Z [test] [banman.cpp:42] [LoadBanlist] Recreating the banlist database
2025-06-04T15:06:01.306712Z [test] [banman.cpp:69] [DumpBanlist] [net] Flushed 0 banned node addresses/subnets to disk  0ms
2025-06-04T15:06:01.306733Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T15:06:01.306751Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T15:06:01.306791Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T15:06:01.306802Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T15:06:01.307510Z [test] [net.cpp:3831] [CNode] [net] Added connection to 127.0.0.1:8333 peer=1
2025-06-04T15:06:01.307572Z [test] [net.cpp:417] [ConnectNode] [net] trying v2 connection localhost lastseen=0.0hrs
make[3]: *** [Makefile:23200: test/net_peer_connection_tests.cpp.test] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/private/tmp/nix-build-bitcoind-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[2]: *** [Makefile:21066: check-am] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-bitcoind-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[1]: *** [Makefile:20738: check-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-bitcoind-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make: *** [Makefile:820: check-recursive] Error 1</pre>
</details>
<details>
<summary>elementsd-simplicity</summary>
<pre>      |                                                          copy_options
include/boost/filesystem/operations.hpp:44:12: note: 'copy_options' declared here
   44 | enum class copy_options : unsigned int
      |            ^
wallet/bdb.cpp:627:71: error: no member named 'overwrite_if_exists' in 'boost::filesystem::copy_options'; did you mean 'overwrite_existing'?
  627 |                     fs::copy_file(pathSrc, pathDest, fs::copy_option::overwrite_if_exists);
      |                                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
      |                                                                       overwrite_existing
include/boost/filesystem/operations.hpp:50:5: note: 'overwrite_existing' declared here
   50 |     overwrite_existing = 1u << 1u,      // Overwrite existing file
      |     ^
2 errors generated.
make[2]: *** [Makefile:12877: wallet/libbitcoin_wallet_a-bdb.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
1 warning generated.
make[2]: Leaving directory '/private/tmp/nix-build-elementsd-unstable-2023-04-18.drv-0/source/src'
make[1]: *** [Makefile:18957: all-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-elementsd-unstable-2023-04-18.drv-0/source/src'
make: *** [Makefile:833: all-recursive] Error 1</pre>
</details>
</details>


---
### `aarch64-darwin` (sandbox = relaxed)
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>bitcoin-knots</li>
    <li>bitcoind-knots</li>
    <li>elementsd-simplicity</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 34 packages built:</summary>
  <ul>
    <li>aerc</li>
    <li>dante</li>
    <li>elements</li>
    <li>elementsd</li>
    <li>groestlcoin</li>
    <li>groestlcoind</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>i2pd</li>
    <li>libtransmission_3</li>
    <li>libtransmission_3.apparmor</li>
    <li>libtransmission_4</li>
    <li>libtransmission_4.apparmor</li>
    <li>miniupnpc</li>
    <li>openomf</li>
    <li>particl-core</li>
    <li>pshs</li>
    <li>qodem</li>
    <li>tests.fetchtorrent.http-link</li>
    <li>tests.fetchtorrent.magnet-link</li>
    <li>transmission_3 (transmission_3_noSystemd)</li>
    <li>transmission_3-gtk</li>
    <li>transmission_3-gtk.apparmor</li>
    <li>transmission_3-qt</li>
    <li>transmission_3-qt.apparmor</li>
    <li>transmission_3.apparmor (transmission_3_noSystemd.apparmor)</li>
    <li>transmission_4</li>
    <li>transmission_4-gtk</li>
    <li>transmission_4-gtk.apparmor</li>
    <li>transmission_4-qt (transmission_4-qt5)</li>
    <li>transmission_4-qt.apparmor (transmission_4-qt5.apparmor)</li>
    <li>transmission_4-qt6</li>
    <li>transmission_4-qt6.apparmor</li>
    <li>transmission_4.apparmor</li>
  </ul>
</details>

---
<details>
<summary>Error logs: `aarch64-darwin`</summary>
<details>
<summary>bitcoin-knots</summary>
<pre>2025-06-04T14:48:12.250569Z [test] [validationinterface.cpp:187] [UpdatedBlockTip] [validation] Enqueuing UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T14:48:12.250580Z [test] [validationinterface.cpp:192] [ActiveTipChange] [validation] ActiveTipChange: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T14:48:12.250591Z [scheduler] [validationinterface.cpp:222] [operator()] [validation] BlockConnected: block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T14:48:12.250609Z [scheduler] [validationinterface.cpp:187] [operator()] [validation] UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T14:48:12.250817Z [test] [banman.cpp:42] [LoadBanlist] Recreating the banlist database
2025-06-04T14:48:12.251024Z [test] [banman.cpp:69] [DumpBanlist] [net] Flushed 0 banned node addresses/subnets to disk  0ms
2025-06-04T14:48:12.251035Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T14:48:12.251042Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T14:48:12.251060Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T14:48:12.251064Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T14:48:12.251525Z [test] [net.cpp:3831] [CNode] [net] Added connection to 127.0.0.1:8333 peer=1
2025-06-04T14:48:12.251680Z [test] [net.cpp:417] [ConnectNode] [net] trying v2 connection localhost lastseen=0.0hrs
make[3]: *** [Makefile:23200: test/net_peer_connection_tests.cpp.test] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/private/tmp/nix-build-bitcoin-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[2]: *** [Makefile:21066: check-am] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-bitcoin-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[1]: *** [Makefile:20738: check-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-bitcoin-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make: *** [Makefile:820: check-recursive] Error 1</pre>
</details>
<details>
<summary>bitcoind-knots</summary>
<pre>2025-06-04T14:37:34.401081Z [scheduler] [validationinterface.cpp:222] [operator()] [validation] BlockConnected: block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T14:37:34.401092Z [test] [validationinterface.cpp:187] [UpdatedBlockTip] [validation] Enqueuing UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T14:37:34.401100Z [scheduler] [validationinterface.cpp:187] [operator()] [validation] UpdatedBlockTip: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f fork block hash=null (in IBD=true)
2025-06-04T14:37:34.401113Z [test] [validationinterface.cpp:192] [ActiveTipChange] [validation] ActiveTipChange: new block hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f block height=0
2025-06-04T14:37:34.401330Z [test] [banman.cpp:42] [LoadBanlist] Recreating the banlist database
2025-06-04T14:37:34.401595Z [test] [banman.cpp:69] [DumpBanlist] [net] Flushed 0 banned node addresses/subnets to disk  0ms
2025-06-04T14:37:34.401607Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T14:37:34.401621Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T14:37:34.401647Z [test] [net.cpp:2384] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
2025-06-04T14:37:34.401652Z [test] [net.cpp:3167] [SetNetworkActive] SetNetworkActive: true
2025-06-04T14:37:34.411689Z [test] [net.cpp:3831] [CNode] [net] Added connection to 127.0.0.1:8333 peer=1
2025-06-04T14:37:34.411761Z [test] [net.cpp:417] [ConnectNode] [net] trying v2 connection localhost lastseen=0.0hrs
make[3]: *** [Makefile:23200: test/net_peer_connection_tests.cpp.test] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/private/tmp/nix-build-bitcoind-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[2]: *** [Makefile:21066: check-am] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-bitcoind-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make[1]: *** [Makefile:20738: check-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-bitcoind-knots-28.1.knots20250305.drv-0/bitcoin-28.1.knots20250305/src'
make: *** [Makefile:820: check-recursive] Error 1</pre>
</details>
<details>
<summary>elementsd-simplicity</summary>
<pre>      |                                                          copy_options
include/boost/filesystem/operations.hpp:44:12: note: 'copy_options' declared here
   44 | enum class copy_options : unsigned int
      |            ^
wallet/bdb.cpp:627:71: error: no member named 'overwrite_if_exists' in 'boost::filesystem::copy_options'; did you mean 'overwrite_existing'?
  627 |                     fs::copy_file(pathSrc, pathDest, fs::copy_option::overwrite_if_exists);
      |                                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
      |                                                                       overwrite_existing
include/boost/filesystem/operations.hpp:50:5: note: 'overwrite_existing' declared here
   50 |     overwrite_existing = 1u << 1u,      // Overwrite existing file
      |     ^
2 errors generated.
make[2]: *** [Makefile:12877: wallet/libbitcoin_wallet_a-bdb.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
1 warning generated.
make[2]: Leaving directory '/private/tmp/nix-build-elementsd-unstable-2023-04-18.drv-0/source/src'
make[1]: *** [Makefile:18957: all-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-elementsd-unstable-2023-04-18.drv-0/source/src'
make: *** [Makefile:833: all-recursive] Error 1</pre>
</details>
</details>

**Comment by phanirithvij** [comment]
for context this pr fixes issue introduced in #413619
